IOS-2417 Design review "Reset to factory view"
tangem/tangem-app-ios-old pull request #1101
Opened 2022-12-23 08:33 UTC by Balashov152

2022-12-26 06:28 UTC, megakoko requested changes
Посмотри эти изменения

https://github.com/tangem/tangem-app-ios/pull/1072/files

2022-12-26 06:28 UTC, megakoko commented on Tangem/Modules/ResetToFactory/ResetToFactoryViewModel.swift
> +    func mainButtonDidTap() {
didTapMainButton

2022-12-26 06:28 UTC, megakoko commented on Tangem/Modules/ResetToFactory/ResetToFactoryViewModel.swift
> +                .destructive(Text(Localization.cardSettingsActionActionSheetReset)) { [weak self] in
actionaction actionaction

2022-12-26 06:28 UTC, megakoko commented on Tangem/Resources/Localizations/de.lproj/Localizable.strings
> +"card_settings_reset_card_with_backup_footer" = "This action will lead to the complete removal of the wallet from the selected card. It will not be possible to restore its current wallet on it or use
Мы недавно специально делали футер и текст сообщения на экране одинаковыми.

2022-12-26 06:28 UTC, megakoko commented on Tangem/Resources/Localizations/de.lproj/Localizable.strings
> +"reset_card_with_backup_to_factory_message" = "Factory Reset will completely delete the wallet from the selected card. You will not be able to restore the current wallet or use the card to recover th
Почему отревертил текстовки на предыдущие?

2022-12-26 06:28 UTC, megakoko commented on Tangem/Resources/Localizations/de.lproj/Localizable.strings
> +"card_settings_action_action_sheet_reset" = "Reset";
Отсутствуют в табличке

2022-12-27 08:33 UTC, tureck1y reviewed
✅

2022-12-27 09:02 UTC, Balashov152 commented on Tangem/Modules/ResetToFactory/ResetToFactoryViewModel.swift
> +    func mainButtonDidTap() {
✅

2022-12-27 09:03 UTC, Balashov152 commented on Tangem/Resources/Localizations/de.lproj/Localizable.strings
> +"reset_card_with_backup_to_factory_message" = "Factory Reset will completely delete the wallet from the selected card. You will not be able to restore the current wallet or use the card to recover th
с фигмы брал, за погляжу, видать там уже не актуально

2022-12-27 09:12 UTC, Balashov152 commented on Tangem/Resources/Localizations/de.lproj/Localizable.strings
> +"card_settings_reset_card_with_backup_footer" = "This action will lead to the complete removal of the wallet from the selected card. It will not be possible to restore its current wallet on it or use
а есть задачка? в дизайне прям специально разделено

2022-12-27 09:13 UTC, Balashov152 commented on Tangem/Modules/ResetToFactory/ResetToFactoryViewModel.swift
> +                .destructive(Text(Localization.cardSettingsActionActionSheetReset)) { [weak self] in
✅

2022-12-27 09:14 UTC, Balashov152 commented on Tangem/Resources/Localizations/de.lproj/Localizable.strings
> +"reset_card_with_backup_to_factory_message" = "Factory Reset will completely delete the wallet from the selected card. You will not be able to restore the current wallet or use the card to recover th
посмотрел твой МР, вернул как было

2022-12-27 09:14 UTC, Balashov152 commented on Tangem/Resources/Localizations/de.lproj/Localizable.strings
> +"card_settings_action_action_sheet_reset" = "Reset";
Добавил ✅

2022-12-28 13:48 UTC, megakoko commented on Tangem/Resources/Localizations/de.lproj/Localizable.strings
> +"card_settings_reset_card_with_backup_footer" = "This action will lead to the complete removal of the wallet from the selected card. It will not be possible to restore its current wallet on it or use
Вот изменения по той задаче. Изначально хотели только в одном месте поменять, потом в обоих сделали одинакого

https://github.com/tangem/tangem-app-ios/pull/1072/files

2022-12-28 13:53 UTC, megakoko commented on Tangem/Resources/Localizations/de.lproj/Localizable.strings
> -"reset_card_to_factory_warning_message" = "I understand that after performing this action, I will no longer have access to the current wallet";
Не забывай удалять из таблички. Удалил

2022-12-28 13:53 UTC, megakoko commented on Tangem/Resources/Localizations/ru.lproj/Localizable.strings
> +"card_settings_action_sheet_title" = "Вы уверены, что хотите это сделать?";
Лучше так

```
Вы уверены, что хотите сделать это?
```

2022-12-28 13:54 UTC, megakoko commented on Tangem/Resources/Localizations/de.lproj/Localizable.strings
> +"reset_card_with_backup_to_factory_message" = "Factory Reset will completely delete the wallet from the selected card. You will not be able to restore the current wallet or use the card to recover th
Эти две текстовки остались в МРе. Можно использовать reset_card_with_backup_to_factory_message и т.д.?

card_settings_reset_card_without_backup_footer" = "This action will lead to the complete removal of the wallet from the selected card. It will not be possible to restore its current wallet on it.";
 "card_settings_reset_card_with_backup_footer" = "This action will lead to the complete removal of the wallet from the selected card. It will not be possible to restore its current wallet on it or use the card to recover the access code.";

2022-12-29 07:53 UTC, Balashov152 commented on Tangem/Resources/Localizations/ru.lproj/Localizable.strings
> +"card_settings_action_sheet_title" = "Вы уверены, что хотите это сделать?";
✅

2022-12-29 07:55 UTC, Balashov152 commented on Tangem/Resources/Localizations/de.lproj/Localizable.strings
> +"reset_card_with_backup_to_factory_message" = "Factory Reset will completely delete the wallet from the selected card. You will not be able to restore the current wallet or use the card to recover th
посмотри плиз, оставил более простую реализацию, Яну коменты оставил в фигме, что бы текст был один и тот же

2022-12-29 07:55 UTC, Balashov152 commented on Tangem/Resources/Localizations/de.lproj/Localizable.strings
> +"card_settings_reset_card_with_backup_footer" = "This action will lead to the complete removal of the wallet from the selected card. It will not be possible to restore its current wallet on it or use
Удалил footer, сделал мессадж

2022-12-29 08:47 UTC, megakoko approved these changes

2022-12-29 09:20 UTC, tureck1y approved these changes

2022-12-29 09:20 UTC, merged