IOS-2836 Fixes approve flow
tangem/tangem-app-ios-old pull request #1185
Opened 2023-01-17 11:35 UTC by Balashov152

- Добавлен дизайн "транзакция в процессе"
- Теперь если allowance достаточен, то вызывается метод /swap
- Убраны лишние методы из делегата, UI зависит только от одного state
- Добавлен cache балансов токенов
- Исправлен таймер автообновления

2023-01-17 11:46 UTC, skibinalexander submitted a review, later dismissed

2023-01-17 12:01 UTC, megakoko requested changes
У тебя еще сабмодуль отревертился

2023-01-17 12:01 UTC, megakoko commented on Tangem/Modules/Swapping/SwappingViewModel.swift
> +            updateRequiredPermission(isEnoughAllowance: !result.isPermissionRequired)
Может переименовать имя параметра?

2023-01-17 12:01 UTC, megakoko commented on Tangem/Modules/SwappingPermission/SwappingPermissionViewModel.swift
> +    private var didBecomeActiveNotificationBag: AnyCancellable?
Тогда это не bag, а subscription

2023-01-17 12:01 UTC, megakoko commented on Tangem/Modules/SwappingPermission/SwappingPermissionViewModel.swift
> +
Лишняя строка

2023-01-17 12:01 UTC, megakoko commented on Tangem/Resources/Localizations/ru.lproj/Localizable.strings
> +"wallet_choose_trade_action" = "Вы хотите купить или продать криптовалюту?";
Отсортируй файл, пожалуйста

2023-01-17 12:01 UTC, megakoko commented on Tangem/Resources/Localizations/ru.lproj/Localizable.strings
> +"send_total_subtitle_fiat_format" = "≈ %@ (вкл. комиссию: %@)";
Такого не должно быть

2023-01-17 12:01 UTC, megakoko commented on TangemExchange/Managers/DefaultExchangeManager.swift
> +                    self?.refreshValues(silent: false)
А зачем так?

2023-01-17 12:01 UTC, megakoko commented on Tangem/Resources/Localizations/ru.lproj/Localizable.strings
> +"wallet_choose_trade_action" = "Вы хотите купить или продать криптовалюту?";
Слишком много изменений

2023-01-17 12:21 UTC, ba1ashov commented on Tangem/Resources/Localizations/ru.lproj/Localizable.strings
> +"wallet_choose_trade_action" = "Вы хотите купить или продать криптовалюту?";
гляну, чет это не должно было залетать

2023-01-17 12:30 UTC, Balashov152 commented on TangemExchange/Managers/DefaultExchangeManager.swift
> +                    self?.refreshValues(silent: false)
потом надо будет обновлять каждую секунду, что бы пользователю показывать сколько осталось permit методу, решил сразу заложить

2023-01-17 12:53 UTC, megakoko commented on TangemExchange/Managers/DefaultExchangeManager.swift
> +                    self?.refreshValues(silent: false)
Окей. Давай тогда переименуем startTimestamp -> timeStarted, period -> timeElapsed

И вместо кастинга в Int давай сделаем round. Не знаю как в айос с точностью таймеров, но как-то стремно всегда с ними работать, вдруг там не 10.00000001 секунд будет, а 9.99999999

2023-01-18 13:51 UTC, Balashov152 commented on Tangem/Modules/Swapping/SwappingViewModel.swift
> +            updateRequiredPermission(isEnoughAllowance: !result.isPermissionRequired)
✅

2023-01-18 13:51 UTC, Balashov152 commented on Tangem/Modules/SwappingPermission/SwappingPermissionViewModel.swift
> +    private var didBecomeActiveNotificationBag: AnyCancellable?
✅

2023-01-18 13:51 UTC, Balashov152 commented on Tangem/Modules/SwappingPermission/SwappingPermissionViewModel.swift
> +
✅

2023-01-18 13:51 UTC, Balashov152 commented on Tangem/Resources/Localizations/ru.lproj/Localizable.strings
> +"wallet_choose_trade_action" = "Вы хотите купить или продать криптовалюту?";
✅

2023-01-18 13:56 UTC, Balashov152 commented on TangemExchange/Managers/DefaultExchangeManager.swift
> +                    self?.refreshValues(silent: false)
✅

2023-01-18 14:14 UTC, megakoko commented on TangemExchange/Managers/DefaultExchangeManager.swift
> +                    self?.refreshValues(silent: false)
Давай еще round сделаем

2023-01-18 14:17 UTC, megakoko commented
Сабмодуль все еще с изменениями

2023-01-18 14:28 UTC, Balashov152 commented on Tangem/Resources/Localizations/ru.lproj/Localizable.strings
> +"send_total_subtitle_fiat_format" = "≈ %@ (вкл. комиссию: %@)";
✅

2023-01-18 14:29 UTC, Balashov152 commented
> Сабмодуль все еще с изменениями

запушил

2023-01-18 14:30 UTC, Balashov152 commented on TangemExchange/Managers/DefaultExchangeManager.swift
> +                    self?.refreshValues(silent: false)
<img width="492" alt="Screenshot 2023-01-18 at 17 28 51" src="https://user-images.githubusercontent.com/25799680/213197718-a4c77feb-4719-463e-acb1-fb6a373f172f.png">

добавил ✅

2023-01-18 14:32 UTC, megakoko commented on TangemExchange/Managers/DefaultExchangeManager.swift
> +                    self?.refreshValues(silent: false)
А, извини, не увидел

2023-01-18 14:32 UTC, megakoko approved these changes

2023-01-18 14:53 UTC, tureck1y approved these changes

2023-01-18 14:53 UTC, tureck1y commented on Tangem/Modules/SwappingPermission/SwappingPermissionViewModel.swift
> +        didBecomeActiveNotificationCancellable = NotificationCenter
а если отменить сканирование и плашка закроется?

2023-01-18 14:53 UTC, tureck1y commented on TangemExchange/Models/Constants.swift
> +    static let exchangeAPIBaseURL: URL = .init(string: "https://api-tangem.1inch.io/\(OneInchAPIVersion.v5.rawValue)/")!
😁

2023-01-18 14:53 UTC, tureck1y commented on TangemExchange/Models/Constants.swift
> +    static let exchangeAPIBaseURL: URL = .init(string: "https://api-tangem.1inch.io/\(OneInchAPIVersion.v5.rawValue)/")!
😁

2023-01-18 15:03 UTC, Balashov152 commented on Tangem/Modules/SwappingPermission/SwappingPermissionViewModel.swift
> +        didBecomeActiveNotificationCancellable = NotificationCenter
Это же будет userCancel case, и получается в этот метод даже не зайдем

2023-01-18 15:04 UTC, Balashov152 commented on TangemExchange/Models/Constants.swift
> +    static let exchangeAPIBaseURL: URL = .init(string: "https://api-tangem.1inch.io/\(OneInchAPIVersion.v5.rawValue)/")!
поднял версию )
может убрать вообще enum этот )

2023-01-18 15:05 UTC, Balashov152 commented on TangemExchange/Models/Constants.swift
> +    static let exchangeAPIBaseURL: URL = .init(string: "https://api-tangem.1inch.io/\(OneInchAPIVersion.v5.rawValue)/")!
аж два раза )

2023-01-18 15:14 UTC, tureck1y commented on Tangem/Modules/SwappingPermission/SwappingPermissionViewModel.swift
> +        didBecomeActiveNotificationCancellable = NotificationCenter
А. Ты подписываешься после сканирования. Ну главное чтоб гонки не было, можно же смахнуть руками быстро.  В онбординге мы делали через combineLatest паблишера от сдк и паблишера от NotificationCenter.

2023-01-18 15:19 UTC, Balashov152 commented on Tangem/Modules/SwappingPermission/SwappingPermissionViewModel.swift
> +        didBecomeActiveNotificationCancellable = NotificationCenter
а, ща тогда гляну как там

2023-01-18 15:34 UTC, skibinalexander approved these changes

2023-01-18 15:34 UTC, skibinalexander commented on TangemExchange/Managers/DefaultExchangeManager.swift
> +    func loadApproveData(preview: PreviewSwappingDataModel, quoteData: QuoteDataModel) async throws {
Наверное можно разнести на 2 отдельных метода

2023-01-18 15:34 UTC, merged