IOS-2863 Fixing analytics events
tangem/tangem-app-ios-old pull request #1194
Opened 2023-01-19 15:43 UTC by megakoko

2023-01-19 16:02 UTC, Balashov152 commented on Tangem/App/Services/TotalBalanceProvider/TotalBalanceAnalyticsService.swift
> +        Self.signedInCards.insert(totalBalanceCardSupportInfo.cardNumberHash)
а получается что если Set, то и проверка не нужна )

2023-01-19 16:04 UTC, megakoko commented on Tangem/App/Services/TotalBalanceProvider/TotalBalanceAnalyticsService.swift
> +        Self.signedInCards.insert(totalBalanceCardSupportInfo.cardNumberHash)
Ну тут же не только insert, там дальше код, который отправляет аналитику. Это надо делать один раз на каждую карту один раз за запуск приложения

2023-01-19 16:04 UTC, Balashov152 approved these changes, later dismissed

2023-01-19 16:05 UTC, Balashov152 commented on Tangem/App/Services/TotalBalanceProvider/TotalBalanceAnalyticsService.swift
> +        Self.signedInCards.insert(totalBalanceCardSupportInfo.cardNumberHash)
понял )

2023-01-19 16:23 UTC, megakoko commented
Алексей по твинам ответил только сейчас, обновил одно событие

2023-01-20 07:21 UTC, tureck1y requested changes

2023-01-20 07:21 UTC, tureck1y commented on Tangem/App/Services/TotalBalanceProvider/TotalBalanceAnalyticsService.swift
> +    private static var signedInCards: Set<String> = []
Тут явно что-то не так.  И в UserDefaults какая-то инфа сохраняется и в статическую переменную(выглядит не очень)

2023-01-20 07:21 UTC, tureck1y commented on Tangem/Modules/Welcome/WelcomeViewModel.swift
> +}
Очень сложно и запутанно. Можно же наверное слать нажатие на кнопку предварительно, чтобы понять откуда сканирование пришло. Обсудите пожалуйста что можно сделать, чтобы код так сильно не загрязнять

2023-01-20 07:21 UTC, tureck1y commented on Tangem/App/Services/UserWalletRepository/UserWalletRepository.swift
> +extension UserWalletRepositoryResult {
Я не очень понял что происходит. Мы кидаем инфу в репу из вью модели, из репы кидаем обратно во вью модель, чтобы отправить ивент в аналитику из нее?

2023-01-20 08:03 UTC, megakoko commented on Tangem/App/Services/TotalBalanceProvider/TotalBalanceAnalyticsService.swift
> +    private static var signedInCards: Set<String> = []
Это для разных событий.

signedIn должен отправляться для каждой карты один раз за запуск приложения

toppedUp должен отправляться для каждой карты один раз за установку приложения

2023-01-20 10:13 UTC, megakoko commented on Tangem/Modules/Welcome/WelcomeViewModel.swift
> +}
Вообще у нас и так есть событие нажатия на кнопку сканирования. На главном экране, на сторисах, на экране сохраненных карт — везде разное событие. Но хотят еще разные события для самого факта сканирования карты. Спрошу согласятся ли на единое событие.

2023-01-20 10:30 UTC, tureck1y commented on Tangem/App/Services/TotalBalanceProvider/TotalBalanceAnalyticsService.swift
> +    private static var signedInCards: Set<String> = []
Как событие signedIn связано с тотал балансом? Если это просто вход в карту, то может отправлять из репозитория?

2023-01-20 11:24 UTC, megakoko commented on Tangem/App/Services/UserWalletRepository/UserWalletRepository.swift
> +extension UserWalletRepositoryResult {
This code is used only to determine the fact that the card was scanned (the scan didn't occur if get `troubleshooting`).

We're not bouncing this info back and forth, no, we just start the scan from the Welcome VM with the appropriate 'source' option and it logs it when it receives the scan results back.

2023-01-20 11:31 UTC, megakoko commented on Tangem/App/Services/TotalBalanceProvider/TotalBalanceAnalyticsService.swift
> +    private static var signedInCards: Set<String> = []
We have to wait for the total balance to finish loading to send an empty/not empty parameter for this event.

2023-01-20 13:57 UTC, megakoko commented
Отрефакторил логгирование скана карты — https://github.com/tangem/tangem-app-ios/pull/1194/commits/ff55b2d8ac03d85c86d05415e26e3db46b86fcba

Событие signedIn — https://github.com/tangem/tangem-app-ios/pull/1194/commits/f46274ef2c4fc92e3436681018b76aa73981b5bd

Добавил защиту от дурака — https://github.com/tangem/tangem-app-ios/pull/1194/commits/9b4bb8aafcddb2d65e709a89de95af08130578d4

2023-01-20 13:58 UTC, megakoko commented on Tangem/App/Services/UserWalletRepository/UserWalletRepository.swift
> +extension UserWalletRepositoryResult {
Refactored

2023-01-20 13:58 UTC, megakoko commented on Tangem/Modules/Welcome/WelcomeViewModel.swift
> +}
Refactored

2023-01-20 13:58 UTC, megakoko commented on Tangem/App/Services/TotalBalanceProvider/TotalBalanceAnalyticsService.swift
> +    private static var signedInCards: Set<String> = []
Refactored

2023-01-20 14:17 UTC, tureck1y approved these changes
❤️

2023-01-20 14:57 UTC, Balashov152 approved these changes

2023-01-20 15:34 UTC, Andoran90 approved these changes

2023-01-20 15:34 UTC, Andoran90 commented on Tangem/App/Services/Common/Analytics/Analytics.swift
> +    static private let additionalDataRepository = AdditionalDataRepository()
I think we need to create Refactoring task for this stuff. It looks like that we need to create separate entity for card analytics, this entity should track all events related to card scanning, loading and so on. But as I understand not in this MR)
This code becomes too complex and complicated...

2023-01-20 15:35 UTC, merged