IOS-3029 Amount exceed balance
tangem/tangem-app-ios-old pull request #1290
Opened 2023-02-17 10:41 UTC by Balashov152

- Проблема была в том, что сейчас мы не умеем работать с токенами, которые не в добавлены в WaletManager
- По уровне blockchain sdk отделил эту логику, и сделал что можно теперь не юзать WalletModel или WalletManger для отправки транзакции 
- Переименовал TangemExchange.BlockchainDataProvider -> WalletDataProvider, по логике он занимается предоставлением данных по кошельку

2023-02-17 13:47 UTC, megakoko commented
@Balashov152 в девелоп мержуем?

2023-02-17 13:50 UTC, Balashov152 commented
> @Balashov152 в девелоп мержуем?

сейчас поменяю blockchain sdk

2023-02-19 20:40 UTC, skibinalexander commented on Tangem/App/Services/Exchange/ExchangeBlockchainDataProvider.swift
> +class ExchangeWalletDataProvider {
Может быть документашку добавить?

2023-02-19 20:41 UTC, skibinalexander commented on TangemExchange/Interfaces/WalletDataProvider.swift
> +public protocol WalletDataProvider {
Тут тоже может быть документашку?

2023-02-21 08:53 UTC, tureck1y commented
а недобавленный токен добавляется в итоге?

2023-02-21 13:53 UTC, Balashov152 commented
> а недобавленный токен добавляется в итоге?

Ага, это уже было реализовано через инкапсуляцию userWalletModel

2023-02-27 07:40 UTC, Balashov152 commented
Отребейзил на `develop`, поменял base brach to `develop`

2023-02-27 08:43 UTC, tureck1y commented
что-то многовато изменений, видимо надо синкануть релиз и дев

2023-02-27 13:02 UTC, tureck1y requested changes

2023-02-27 13:02 UTC, tureck1y commented on Tangem/Modules/Onboarding/Wallet/WalletOnboardingViewModel.swift
> +                case .claim, .finished:
Лишнее изменение попало

2023-02-27 13:02 UTC, tureck1y commented on TangemApp.xcodeproj/project.pbxproj
> -				CODE_SIGN_ENTITLEMENTS = "$ENTITLEMENTS_PATH";
Что-то тоже лишнее кажется

2023-02-27 13:19 UTC, Balashov152 commented on Tangem/App/Services/Exchange/ExchangeBlockchainDataProvider.swift
> +class ExchangeWalletDataProvider {
А какую?)

2023-02-27 13:20 UTC, Balashov152 commented on TangemExchange/Interfaces/WalletDataProvider.swift
> +public protocol WalletDataProvider {
А какую?)

2023-02-27 14:33 UTC, Balashov152 commented on Tangem/Modules/Onboarding/Wallet/WalletOnboardingViewModel.swift
> +                case .claim, .finished:
Поправил ✅

2023-02-27 14:33 UTC, Balashov152 commented on TangemApp.xcodeproj/project.pbxproj
> -				CODE_SIGN_ENTITLEMENTS = "$ENTITLEMENTS_PATH";
Убрал как было ✅

2023-02-27 14:46 UTC, tureck1y approved these changes

2023-02-28 07:21 UTC, skibinalexander commented on Tangem/App/Services/Exchange/ExchangeBlockchainDataProvider.swift
> +class ExchangeWalletDataProvider {
Хотя отбой, наверное по названию класса и так понятно.

2023-02-28 07:21 UTC, skibinalexander approved these changes

2023-02-28 09:54 UTC, megakoko approved these changes

2023-02-28 10:04 UTC, merged