IOS-3038 add gas limit from our RPC
tangem/tangem-app-ios-old pull request #1365
Opened 2023-03-04 17:30 UTC by Balashov152

2023-03-05 11:54 UTC, skibinalexander submitted a review, later dismissed

2023-03-06 03:53 UTC, tureck1y submitted a review, later dismissed

2023-03-06 07:03 UTC, Andoran90 requested changes

2023-03-06 07:03 UTC, Andoran90 commented on Tangem/App/Services/Exchange/ExchangeWalletDataProvider.swift
> +    private let ethereumGasLoader: EthereumGasLoader
похоже можно переименовать из `ExchangeWalletDataProvider` в `EVMExchangeWalletDataProvider`, для биткоин-подобных все равно не применишь. Ну это так, мисли вслух.

2023-03-06 07:03 UTC, Andoran90 commented on Tangem/App/Services/Exchange/ExchangeWalletDataProvider.swift
> +        return EthereumGasDataModel(blockchain: blockchain, gasPrice: Int(price), gasLimit: Int(limit))
давай заменим на такой вариант:
```suggestion
        async let price = ethereumGasLoader.getGasPrice().async()
        let amount = createAmount(from: blockchain, amount: value)
        async let limit = ethereumGasLoader.getGasLimit(
            to: destinationAddress,
            from: sourceAddress,
            value: amount.encodedForSend,
            data: "0x\(data.hexString)"
        ).async()

        return try await EthereumGasDataModel(blockchain: blockchain, gasPrice: Int(price), gasLimit: Int(limit))
```

В чем смысл такой замены: в твоем варианте у тебя происходит в начале ожидание одного запроса, потом ожидание другого запроса. В обновленном варианте у тебя срезу отправятся оба запроса (если будут свободные потоки для этого) и будет быстрее отрабатывать :)

2023-03-06 07:03 UTC, Andoran90 commented on TangemApp.xcodeproj/project.pbxproj
> +				CODE_SIGN_ENTITLEMENTS = $ENTITLEMENTS_PATH;
O_o

2023-03-06 07:03 UTC, Andoran90 commented on TangemExchange/Managers/DefaultExchangeManager.swift
>                  try Task.checkCancellation()
это можно убрать, т.к. `isEnoughAmountForExchange()` не асинхронное и почти не займет времени

2023-03-06 07:03 UTC, Andoran90 commented on TangemExchange/Managers/DefaultExchangeManager.swift
> +
```suggestion

    try Task.checkCancellation()

```

можно вставить после каждого асинхронного запроса, чтобы не выполнять последующие

2023-03-06 07:03 UTC, Andoran90 commented on TangemExchange/Managers/DefaultExchangeManager.swift
> +        let result = try await mapToSwappingResultDataModel(transaction: info)
```suggestion
        let info = try await mapToExchangeTransactionInfo(exchangeData: exchangeData)
        
        try Task.checkCancellation()
        
        let result = try await mapToSwappingResultDataModel(transaction: info)
```

2023-03-06 07:03 UTC, Andoran90 commented on TangemExchange/Managers/DefaultExchangeManager.swift
>          let approvedDataModel = try await getExchangeApprovedDataModel()
```suggestion
        async let quoteData = getQuoteDataModel()
        async let approvedDataModel = getExchangeApprovedDataModel()
```

не зависят друг от друга запросы. Можно ускорить

2023-03-06 07:03 UTC, Andoran90 commented on TangemExchange/Managers/DefaultExchangeManager.swift
```suggestion

        try Task.checkCancellation()

```

2023-03-06 07:03 UTC, Andoran90 commented on TangemExchange/Managers/DefaultExchangeManager.swift
> +    func mapPreviewSwappingDataModel(from quoteData: QuoteDataModel) async throws -> PreviewSwappingDataModel {
не нужно это тут. Внутри ничего асинхронного нет.

2023-03-06 07:03 UTC, Andoran90 commented on TangemExchange/Models/DataModels/ExchangeApprovedDataModel.swift
> -        guard let gasPrice = Int(approveTxData.gasPrice),
а в `ApprovedTransactionData` нужен ещё `gasPrice`? может оттуда тоже потереть?

2023-03-06 08:10 UTC, Balashov152 commented on Tangem/App/Services/Exchange/ExchangeWalletDataProvider.swift
> +        return EthereumGasDataModel(blockchain: blockchain, gasPrice: Int(price), gasLimit: Int(limit))
да, я так и понял, заменю

2023-03-06 08:11 UTC, Balashov152 commented on TangemApp.xcodeproj/project.pbxproj
> +				CODE_SIGN_ENTITLEMENTS = $ENTITLEMENTS_PATH;
Да блин, оно само :)

2023-03-06 08:12 UTC, Balashov152 commented on TangemExchange/Managers/DefaultExchangeManager.swift
>                  try Task.checkCancellation()
✅

2023-03-06 08:13 UTC, Balashov152 commented on TangemExchange/Managers/DefaultExchangeManager.swift
> +
✅

2023-03-06 08:13 UTC, Balashov152 commented on TangemExchange/Managers/DefaultExchangeManager.swift
> +        let result = try await mapToSwappingResultDataModel(transaction: info)
✅

2023-03-06 08:14 UTC, ba1ashov commented on TangemExchange/Managers/DefaultExchangeManager.swift
>          let approvedDataModel = try await getExchangeApprovedDataModel()
✅

2023-03-06 08:15 UTC, Balashov152 commented on TangemExchange/Models/DataModels/ExchangeApprovedDataModel.swift
> -        guard let gasPrice = Int(approveTxData.gasPrice),
ну там написан маппинг с DTO, решил что там пока оставлю, а в этих моделях для менеджера убрал, что бы не спутать

2023-03-06 08:17 UTC, Balashov152 commented on Tangem/App/Services/Exchange/ExchangeWalletDataProvider.swift
> +    private let ethereumGasLoader: EthereumGasLoader
Да вообще у нас все своплка EVMExhageManager, не знаю, оставлю лучше как есть, а то тогда имеет смысл ее все переименововать )

2023-03-06 08:17 UTC, Balashov152 commented on Tangem/App/Services/Exchange/ExchangeWalletDataProvider.swift
> +        return EthereumGasDataModel(blockchain: blockchain, gasPrice: Int(price), gasLimit: Int(limit))
✅

2023-03-06 09:03 UTC, Andoran90 commented on Tangem/App/Services/Exchange/ExchangeWalletDataProvider.swift
> +    private let ethereumGasLoader: EthereumGasLoader
да, это на будущее, если вообще добавятся какие-то другие. Может стоит переименовать все и либу вместе с ней, но это задача для иОС-разрабов Танжема из будущего))

2023-03-06 09:04 UTC, Andoran90 approved these changes

2023-03-06 09:13 UTC, tureck1y approved these changes

2023-03-06 09:18 UTC, megakoko approved these changes

2023-03-06 09:18 UTC, merged