IOS-3123 Showing "1 Card" for old multicurrency cards
tangem/tangem-app-ios-old pull request #1406
Opened 2023-03-22 13:23 UTC by megakoko

Протестировать не могу, нет карт. Надо было для многовалютных карт 4.12 сделать приписку "1 Card" на "My Wallets".

2023-03-22 14:03 UTC, skibinalexander commented on Tangem/App/Models/UserWallet/Implementations/LegacyConfig.swift
> +        if isMultiwallet {
return isMultiwallet ? Localization.cardLabelCardCount(1) : nil
- ?

2023-03-22 14:03 UTC, skibinalexander submitted a review, later dismissed

2023-03-22 14:43 UTC, megakoko commented on Tangem/App/Models/UserWallet/Implementations/LegacyConfig.swift
> +        if isMultiwallet {
Обновил

2023-03-22 19:09 UTC, skibinalexander submitted a review, later dismissed

2023-03-22 21:33 UTC, Balashov152 approved these changes, later dismissed

2023-03-23 07:01 UTC, tureck1y approved these changes

2023-03-23 07:02 UTC, tureck1y commented
хотя это же не для myWallets

2023-03-23 07:10 UTC, tureck1y requested changes
<img width="768" alt="Screenshot 2023-03-23 at 12 10 07" src="https://user-images.githubusercontent.com/4981841/227129429-67e8357f-d737-408d-8e79-7bf70bf2c02a.png">

2023-03-23 08:03 UTC, megakoko commented
Спасибо, обновил. Потестировал через замену конфига для ноута.

2023-03-23 14:10 UTC, tureck1y commented
может лучше просто в конфиги добавим строчку для этого лейбла?

2023-03-24 06:41 UTC, skibinalexander approved these changes, later dismissed

2023-03-24 07:54 UTC, megakoko commented
Не знаю, стоит ли заморачиваться, эту шторку все равно будем выпиливать с редизайном.

2023-03-24 13:13 UTC, tureck1y commented on Tangem/Modules/UserWalletList/UserWalletListViewModel.swift
> +    private func isMultiCurrency(config: UserWalletConfig) -> Bool {
cardModel.isMultiWallet даст же тот же самый результат

2023-03-27 09:24 UTC, megakoko commented on Tangem/Modules/UserWalletList/UserWalletListViewModel.swift
> +    private func isMultiCurrency(config: UserWalletConfig) -> Bool {
В методе `mapToUserWalletListCellViewModel` эта модель отсутствует, поэтому сделал через конфиг, чтобы одна логика была

2023-03-27 13:41 UTC, Andoran90 approved these changes, later dismissed
попробовал, у 4.12 и SwissKey показывается "1 Card"

2023-03-28 07:22 UTC, tureck1y commented on Tangem/Modules/UserWalletList/UserWalletListViewModel.swift
> +    private func isMultiCurrency(config: UserWalletConfig) -> Bool {
CardInfo, как и конфиг должен быть приватный, его открыли, когда делали биометрию. К нему доступа не будет когда подчистим и  подрефакторим.

2023-03-28 11:46 UTC, megakoko commented on Tangem/Modules/UserWalletList/UserWalletListViewModel.swift
> +    private func isMultiCurrency(config: UserWalletConfig) -> Bool {
Переделал

2023-03-29 07:19 UTC, tureck1y approved these changes

2023-03-29 07:26 UTC, Andoran90 approved these changes
<img src="https://user-images.githubusercontent.com/24321494/228458115-fd67fcef-99fe-4b2e-99c1-8582e5722f5b.jpeg" width="300"/>

2023-03-29 11:38 UTC, merged