IOS-3264 Move on weak self for Task {}
tangem/tangem-app-ios-old pull request #1436
Opened 2023-03-30 13:21 UTC by Balashov152

Прилетело для крэша из FB по обращению к `unowned coordinator` что бы открыл следующий экран
Как будто пользователь сам уходит с экрана, а мы еще хотим открыть экран об успешности отправки

2023-03-30 13:32 UTC, Andoran90 commented on Tangem/Modules/Swapping/SwappingViewModel.swift
> +        runTask(in: self) { obj in
блин, все на костылях работает... жесть какая-то. Сделали современный подход к многопоточности :(

2023-03-30 13:32 UTC, Andoran90 approved these changes, later dismissed

2023-03-30 14:08 UTC, Balashov152 commented on Tangem/Modules/Swapping/SwappingViewModel.swift
> +        runTask(in: self) { obj in
боюсь что может не помочь, будем смотреть, может исправят)

2023-03-30 14:18 UTC, skibinalexander submitted a review, later dismissed

2023-03-30 15:36 UTC, tureck1y commented on Tangem/Modules/Swapping/SwappingViewModel.swift
> +        runTask(in: self) { obj in
Странно выглядит, давайте просто отменять таски перед выходом

2023-03-31 12:08 UTC, Balashov152 commented
Может тогда вообще это оставить на переделку работу с Task {} в этом экране

2023-03-31 12:10 UTC, Andoran90 commented on Tangem/Modules/Swapping/SwappingViewModel.swift
> +        runTask(in: self) { obj in
вообще странно, они должны отменяться автоматом, когда уходишь с экрана. `.task { }` модификатор отменяет все задачи, но он с 15 только оси, очередное гадство

2023-04-01 17:19 UTC, tureck1y approved these changes

2023-04-03 06:24 UTC, skibinalexander approved these changes

2023-04-03 06:37 UTC, merged

2023-04-03 06:42 UTC, Andoran90 requested changes
знаю что уже смержили, но вот моё мнение на этот счет))

2023-04-03 06:42 UTC, Andoran90 commented on Tangem/App/Services/FiatRatesProvider/FiatRatesProvider.swift
> +    func getSyncFiat(for currency: Currency, amount: Decimal) -> Decimal? {
стременное название, которое не отражает логику) если смотреть по названиям есть синхронная загрузка фиата и есть асинхронная, но синхронная грузит из памяти, а асинхронная из сети. Лучше их подогнать по смыслу, `getStoredFiat` и `loadRemoteFiat`, что-то такое. Ну и вообще асинхронные сетевые вызовы стоит называть `load`, а локальные `get`, ну это уже ИМХО, конечно)

2023-04-03 06:42 UTC, Andoran90 commented on Tangem/Modules/Swapping/SwappingViewModel.swift
> +        .store(in: &workingTasks)
думаю это не сработает, надо перепроверить. Надо везде прописывать слабые ссылки на `self` или же отменять все задачи на `onDisappear`. Сейчас получается:
создается таск с ссылками на `SwappingViewModel`, 
эти таски сохраняются в сет внутри `SwappingViewModel`
получается SwappingViewModel хранит ссылки на самого себя в сете с тасками. 
т.к. количество сильных ссылок на `SwappingViewModel` всегда больше 0 - `deinit` не будет вызываться. + когда завершается задача - надо её удалять из сэта. То же самое касается паблишеров, они же никуда магическим образом не деваются, а сет хранил не слабые ссылки, а сильные.

Думаю что получилось плохо, но надо перепроверять.

2023-04-03 07:06 UTC, Balashov152 commented on Tangem/App/Services/FiatRatesProvider/FiatRatesProvider.swift
> +    func getSyncFiat(for currency: Currency, amount: Decimal) -> Decimal? {
Вообще норм поинт, запомню, надо бы поправить, это просто для одно места, где нам нужно без async взять рейты