Ios 3456 add group sort buttons component
tangem/tangem-app-ios-old pull request #1567
Opened 2023-05-14 19:31 UTC by skibinalexander

- Сделал Flexy кнопку компонент атомарную по аналогии которую делал @Andoran90 не растягиваемую
- Сделал вьюху для сортировки списка токенов  без биндингов, ждем список токенов
- Добавил локализацию для кнопок, выгружал текстовки с локолайза, поэтому по текстовкам появился диф большой

2023-05-15 06:33 UTC, Balashov152 commented on Tangem/Resources/Assets/Assets.xcassets/Group.imageset/Contents.json
> +    },
надо `individual case` проставить, что бы вариант один был

2023-05-15 09:17 UTC, Andoran90 requested changes

2023-05-15 09:17 UTC, Andoran90 commented on Tangem/UIComponents/TogglableGroupButtonWithIcon/TogglableGroupButtonWithIcon.swift
> +            gourpButton
```suggestion
            groupButton
```

2023-05-15 09:17 UTC, Andoran90 commented on Tangem/UIComponents/TogglableGroupButtonWithIcon/TogglableGroupButtonWithIcon.swift
> +public struct TogglableGroupButtonWithIcon: View {
Для чего эта вьюха нужна? она же ничего не делает. При интеграции этого компонента надо будет дорабатывать его почти полностью. По сути в этом МРе только растягивающаяся кнопка сделана, но не сделаны кнопки, которые должны переключать свое состояние. И этой вьюхой даже нельзя снаружи управлять, её невозможно будет переиспользовать без ее изменения.
Тогглиться будут кнопки, т.е. у кнопки сортировки будет состояние - включена/выключена и у кнопки группировки будет состояние - включена/выключена.
Ты не разговаривал с Лешей про логику сортировки/группировки? как что ведет себя при переключении кнопок?

2023-05-15 10:40 UTC, skibinalexander commented on Tangem/UIComponents/TogglableGroupButtonWithIcon/TogglableGroupButtonWithIcon.swift
> +public struct TogglableGroupButtonWithIcon: View {
Мы в пятницу как раз проговорили, что отбельные вью тоже оборачиваем в компонент, также обговорили чтобы привязать толлинг нужны биндиги , в чате дизайна ещё обсуждаем , я в целом дескрипшен к МР оставил

2023-05-15 10:40 UTC, skibinalexander commented on Tangem/Resources/Assets/Assets.xcassets/Group.imageset/Contents.json
> +    },
> надо `individual case` проставить, что бы вариант один был 

Ага забыл сделаю

2023-05-15 11:23 UTC, Andoran90 commented on Tangem/UIComponents/TogglableGroupButtonWithIcon/TogglableGroupButtonWithIcon.swift
> +public struct TogglableGroupButtonWithIcon: View {
добавь хотя бы тудушки, чтобы при просмотре кодовой базы было понятно что это ещё незаконченная вьюха, что в ней будут доработки. Т.к. закрываешь текущую задачу - создай новую, в которой будет доработка биндингов и номер задачи добавь в тудушку, пожалуйста. А то получается: задачу выполнил - вьюха нефункциональна. Описание к МРам это хорошо, но лучше когда есть задача в жире, чтобы не потерялась

2023-05-15 13:28 UTC, skibinalexander commented on Tangem/UIComponents/TogglableGroupButtonWithIcon/TogglableGroupButtonWithIcon.swift
> +public struct TogglableGroupButtonWithIcon: View {
Добавил задачу IOS-3627

2023-05-15 13:36 UTC, skibinalexander commented on Tangem/UIComponents/TogglableGroupButtonWithIcon/TogglableGroupButtonWithIcon.swift
> +            gourpButton
Исправил

2023-05-15 13:37 UTC, skibinalexander commented on Tangem/Resources/Assets/Assets.xcassets/Group.imageset/Contents.json
> +    },
Исправил

2023-05-15 14:55 UTC, Andoran90 commented on Tangem/Resources/Assets/Assets.xcassets/by_balance.imageset/Contents.json
> +      "scale" : "3x"
тут тоже 1 размер должен быть

2023-05-17 07:01 UTC, Andoran90 approved these changes

2023-05-17 09:05 UTC, tureck1y approved these changes

2023-05-17 09:06 UTC, Balashov152 approved these changes

2023-05-17 09:06 UTC, Balashov152 commented on Tangem/UIComponents/TogglableGroupButtonWithIcon/TogglableGroupButtonWithIcon.swift
> +        HStack {
spacing бы не помешал. Можно в след MR

2023-05-17 09:44 UTC, merged