IOS-3748 Show warning on priority fee
tangem/tangem-app-ios-old pull request #1630
Opened 2023-06-02 11:10 UTC by Balashov152

https://github.com/tangem/tangem-app-ios/assets/25799680/a49e3133-2ff4-405a-966e-8df7f2f6d0d6

2023-06-02 11:20 UTC, megakoko commented on Tangem/Modules/Swapping/SwappingViewModel.swift
> +            let isEnoughAmountForFee = model.isEnoughAmountForFee(for: policy)
Один и тот же вызов. Все в порядке?

2023-06-02 11:20 UTC, megakoko commented on TangemSwapping/Manager/CommonSwappingManager.swift
> +        }
Может объединить и пробегаться через `for in`? Будет короче, по ощущениям меньше копипасты.

2023-06-06 07:51 UTC, Balashov152 commented on Tangem/Modules/Swapping/SwappingViewModel.swift
> +            let isEnoughAmountForFee = model.isEnoughAmountForFee(for: policy)
не, чет попутал )

2023-06-06 07:52 UTC, Balashov152 commented on TangemSwapping/Manager/CommonSwappingManager.swift
> +        }
✅

2023-06-06 09:08 UTC, megakoko approved these changes

2023-06-06 09:15 UTC, megakoko requested changes
Так, погоди, мы же еще хотели чтобы прыгать перестало

2023-06-06 09:17 UTC, Balashov152 commented
> Так, погоди, мы же еще хотели чтобы прыгать перестало

Это я сделал, перезапишу ща

2023-06-06 09:18 UTC, megakoko approved these changes
А, да, вижу коммит, тогда аппрув

2023-06-06 18:08 UTC, tureck1y approved these changes

2023-06-07 06:55 UTC, merged