IOS-3984 wc 2 for all cards
tangem/tangem-app-ios-old pull request #1791
Opened 2023-07-24 07:37 UTC by Andoran90

Пришлось сделать миграцию со старой версии хранения на новую, чтобы в будущем было проще поддерживать хранение. Идея хранить по `UserWalletId` оказалась не очень прям удобная структура. Переименовал файлы `WalletConnectServicing` -> `WalletConnectService` и `WalletConnectService` -> `CommonWalletConnectService`, т.к. контент не соответствовал названию файлов

2023-07-24 13:36 UTC, tureck1y requested changes
Надо сделать понятный флоу
- На старте приложения происходит восстановление всех сессий
- Перед этим происходит миграция всех раздельных сессий всех кошельков в одну. Код временный, спрятан в коде хранилища, вынесен в отдельную функцию с комментариями
- Мы работаем со всеми картами одновременно, поэтому никаких фильтраций в репозитории у нас нет (поправь меня если не так)
- нужно прибраться в интерфейсах, протоколах и сущностях. 
- Все новые подключение делаем с текущей картой?
-

2023-07-24 13:36 UTC, tureck1y commented on Tangem/App/Services/UserWalletRepository/CommonUserWalletRepository.swift
> +                    self.walletConnectService.initialize()
Эта инициализация уже есть в  ServicesManager. Кажется можно тут убрать вообще инжект walletConnect

2023-07-24 13:36 UTC, tureck1y commented on Tangem/App/Services/WalletConnect/CommonWalletConnectService.swift
> +class CommonWalletConnectService {
Непонятно назначение этого сервиса. Ведь можно юзать WalletConnectV2Service напрямую?

2023-07-24 13:36 UTC, tureck1y commented on Tangem/App/Services/WalletConnect/Utilities/WalletConnectWalletModelProvider.swift
> +    func getModel(with address: String, in blockchain: Blockchain) throws -> WalletModel
DerivationPath совсем не учитывается. Мы же не запрещаем работать с кастомными сетями

2023-07-24 13:36 UTC, tureck1y commented on Tangem/App/Services/WalletConnect/Utilities/WalletConnectWalletModelProvider.swift
> +    init(userWallet: UserWalletModel) {
Можно проинициализировать сразу с walletModelsManager?

2023-07-24 13:36 UTC, tureck1y commented on Tangem/App/Services/WalletConnect/WalletConnectV2Service/Models/WalletConnectV2Error.swift
> +    case missingUserWalletWithTargetId
Не совсем понятно что за ошибка

2023-07-24 13:36 UTC, tureck1y commented on Tangem/App/Services/WalletConnect/WalletConnectV2Service/WalletConnectSessionsStorage.swift
> +    func clearStorage(for userWalletId: String)
removeSessions, clearStorage. Предлагаю что-то одно. Типа migrate

2023-07-24 13:36 UTC, tureck1y commented on Tangem/App/Services/WalletConnect/WalletConnectV2Service/WalletConnectSessionsStorage.swift
> +    private let allSessions: CurrentValueSubject<[WalletConnectSavedSession], Never> = .init([])
Я вообще не понимаю что тут происходит. В Restore делаем миграцию, при этом есть отдельный remove, в котором тоже что-то происходит, который торчит интерфейсом аж в сервис. А еще есть clear. Давай пожалуйста наведем порядок.

2023-07-24 13:36 UTC, tureck1y commented on Tangem/App/Services/WalletConnect/WalletConnectV2Service/WalletConnectSessionsStorage.swift
> +
Как-то не очень иметь такую зависимость на таком низком уровне. WalletConnectSessionsStorage не должен о таком знать

Зачем вообще что-то фильтровать я не понимаю. Мы работаем сразу со всеми картами

2023-07-24 13:36 UTC, tureck1y commented on Tangem/App/Services/WalletConnect/WalletConnectV2Service/WalletConnectV2Service.swift
> +    private var infoProvider: WalletConnectUserWalletInfoProvider? { userWalletRepository.selectedModel }
не будет работать если выключена биометрия, надо думать что делать...

2023-07-24 13:40 UTC, Andoran90 commented on Tangem/App/Services/WalletConnect/CommonWalletConnectService.swift
> +class CommonWalletConnectService {
сейчас он хэндлит диплинки, хочется с одной стороны разделить эту логику, а не тащить все в сервис WC 2.0, но согласен, что он не прям так дико нужен. Наверное рассчитывать, что начнут пилить другую версию WC не стоит) Вот не знаю тут ли делать это или отдельно рефакторить уже весь код связанный с WС. Можно оставить на попозже и избавиться, когда будем выделять WC в отдельный таргет

2023-07-24 13:41 UTC, Andoran90 commented on Tangem/App/Services/UserWalletRepository/CommonUserWalletRepository.swift
> +                    self.walletConnectService.initialize()
затащил в репозиторий, потому что в `ServicesManager` у нас ещё не загружены модели, они грузятся после сканирования карточки или же пальца/лица. Можно затащить в `ServicesManager` загрузку моделей, конечно, но это больше задача рефакторинга `CommonUserWalletRepository`

2023-07-24 13:42 UTC, Andoran90 commented on Tangem/App/Services/WalletConnect/Utilities/WalletConnectWalletModelProvider.swift
> +    func getModel(with address: String, in blockchain: Blockchain) throws -> WalletModel
она учитывает через адрес, из дАппа не приходит информация про деривацию, это можно понять только в сочетании blockchain+address

2023-07-24 13:46 UTC, tureck1y commented on Tangem/App/Services/UserWalletRepository/CommonUserWalletRepository.swift
> +                    self.walletConnectService.initialize()
Тогда зачем этот код в ServicesManager? И зачем для восстановления сессий ждать загрузку чего-то еще?

2023-07-24 13:47 UTC, tureck1y commented on Tangem/App/Services/WalletConnect/CommonWalletConnectService.swift
> +class CommonWalletConnectService {
В этом мр так много изменений, не связанных напрямую с задачей, что имхо можно и тут, если это конечно не повлечет за собой еще +100 изменений, смотри сам

2023-07-24 13:47 UTC, tureck1y commented on Tangem/App/Services/WalletConnect/Utilities/WalletConnectWalletModelProvider.swift
> +    func getModel(with address: String, in blockchain: Blockchain) throws -> WalletModel
Ок, добавь тогда плиз коммент

2023-07-24 13:49 UTC, Andoran90 commented on Tangem/App/Services/UserWalletRepository/CommonUserWalletRepository.swift
> +                    self.walletConnectService.initialize()
блэт, пардон, забыл его оттуда удалить. Изначально пытался проинициализировать сессии через `ServiceManager`, но нихрена

2023-07-24 13:52 UTC, Andoran90 commented on Tangem/App/Services/WalletConnect/CommonWalletConnectService.swift
> +class CommonWalletConnectService {
да вроде как не так и много левых изменений, концепция работы WC прям сильно изменилась и что-то по маленьким кусочкам менять не особо правильно, не до конца ясно было как именно это все встроится в нашу текущую реализацию(

2023-07-24 13:53 UTC, Andoran90 commented on Tangem/App/Services/WalletConnect/Utilities/WalletConnectWalletModelProvider.swift
> +    init(userWallet: UserWalletModel) {
да, согласен, сделаю

2023-07-25 12:21 UTC, Andoran90 commented on Tangem/App/Services/WalletConnect/WalletConnectV2Service/Models/WalletConnectV2Error.swift
> +    case missingUserWalletWithTargetId
😅

2023-07-25 13:51 UTC, Andoran90 commented on Tangem/App/Services/WalletConnect/WalletConnectSessionsStorage/WalletConnectSessionsStorage.swift
> +protocol WalletConnectSessionsStorage: Actor, Initializable {
Перенес файл в другую папку, до этого была неправильная иерархия (лежало в папке V2, хотя не связано именно со второй версией)

2023-07-25 13:52 UTC, Andoran90 commented on Tangem/App/Services/WalletConnect/WalletConnectSessionsStorage/WalletConnectSessionsStorage.swift
> +protocol WalletConnectSessionsStorage: Actor, Initializable {
@tureck1y обновил тут протокол, вынес миграцию (дергается через `Initializable` реализация в конце файла)

2023-07-25 13:54 UTC, Andoran90 commented on Podfile.lock
> +PODFILE CHECKSUM: 4df8c6f5104b08ba665522c9804de77f70228e84
в деве сломан билд, неправильная чексума указана

2023-07-25 16:48 UTC, tureck1y commented on Tangem/Modules/WalletConnect/WalletConnectViewModel.swift
> +                let filteredSessions = sessions.filter { $0.userWalletId == cardModel.userWalletId.stringValue }
а зачем сессии фильтровать если мы сразу со всеми работаем?

2023-07-25 18:03 UTC, Andoran90 commented on Tangem/Modules/WalletConnect/WalletConnectViewModel.swift
> +                let filteredSessions = sessions.filter { $0.userWalletId == cardModel.userWalletId.stringValue }
Ну у нас флоу такой, что мы открываем карту и потом можем навигироваться. Вдобавок будет непонятно к какой карте привязаны сессии. И ещё, пользователи уже привыкли к такому флоу, сейчас менять его внезапно и без дизайна думаю будет лишним

2023-07-25 18:08 UTC, tureck1y commented on Tangem/Modules/WalletConnect/WalletConnectViewModel.swift
> +                let filteredSessions = sessions.filter { $0.userWalletId == cardModel.userWalletId.stringValue }
Ничего не поняль(

2023-07-26 14:27 UTC, tureck1y approved these changes

2023-07-26 15:30 UTC, ba1ashov commented on Tangem/App/Services/WalletConnect/CommonWalletConnectService.swift
> +            .eraseToAnyPublisher()
```suggestion
        v2Service.canEstablishNewSessionPublisher.eraseToAnyPublisher()
```
что то лишнего )

2023-07-26 15:33 UTC, tureck1y commented on Tangem/Modules/WalletConnect/WalletConnectViewModel.swift
> +                let filteredSessions = sessions.filter { $0.userWalletId == cardModel.userWalletId.stringValue }
разобрались, ничего не фильтруем

2023-07-26 15:34 UTC, ba1ashov approved these changes

2023-07-26 15:34 UTC, merged