IOS-3983 Refactor supported blockchains
tangem/tangem-app-ios-old pull request #1792
Opened 2023-07-24 07:43 UTC by Balashov152

2023-07-24 13:14 UTC, Balashov152 commented
Жду https://github.com/tangem/blockchain-sdk-swift/pull/370

2023-07-25 05:10 UTC, Andoran90 commented on Tangem/App/Models/Config/SupportedBlockchains.swift
> +    func emvBlockchains() -> Set<Blockchain> {
```suggestion
    func evmBlockchains() -> Set<Blockchain> {
```

2023-07-25 07:31 UTC, Balashov152 commented on Tangem/App/Models/Config/SupportedBlockchains.swift
> +    func emvBlockchains() -> Set<Blockchain> {
✅

2023-07-26 11:00 UTC, Andoran90 approved these changes, later dismissed

2023-07-26 11:42 UTC, tureck1y requested changes

2023-07-26 11:42 UTC, tureck1y commented on Tangem/Modules/TokenList/TokenListViewModel.swift
> +        let supportedBlockchains = mode.settings?.supportedBlockchains ?? SupportedBlockchains().blockchains(for: .v1)
Давай сделаем константу для таких случаев. Типа дайте все, чтобы не думать в точке вызова какой стиль использовать. Это пригодится здесь и во всех других вызовах, где это не важно

2023-07-26 11:42 UTC, tureck1y commented on Tangem/App/Services/WalletConnect/WalletConnectV2Service/Utilities/WalletConnectV2Utils.swift
> +            let blockchains = SupportedBlockchains().evmBlockchains()
Немного не то. Тут мы просто объединяли тестнет и обычные. Воллет коннект может работать не только с евм. Такое объединение делается только тут вроде. Лучше не выносить эту логику за пределы, чтобы не было мисюза

2023-07-26 11:42 UTC, tureck1y commented on Tangem/App/Models/UserWallet/Implementations/Wallet2Config.swift
> +        let allBlockchains = SupportedBlockchains().blockchains(for: .v2)
Надо не забыть пофиксить отдельно для шибы. Запишу себе

2023-07-26 11:42 UTC, tureck1y commented on Tangem/App/Models/Config/SupportedBlockchains.swift
> +    func mainnetBlockchains(for version: Version) -> Set<Blockchain> {
Какой сейчас флоу? Когда дают ок, мы идем сюда и добавляем в mainnet список?

2023-07-26 11:43 UTC, Balashov152 commented on Tangem/App/Services/WalletConnect/WalletConnectV2Service/Utilities/WalletConnectV2Utils.swift
> +            let blockchains = SupportedBlockchains().evmBlockchains()
Я просто решил так сделать из-за того что дальше идет проверка на chainID, а это только для EVM актуально

2023-07-26 11:44 UTC, Balashov152 commented on Tangem/App/Models/Config/SupportedBlockchains.swift
> +    func mainnetBlockchains(for version: Version) -> Set<Blockchain> {
да, такой получается

2023-07-26 11:58 UTC, tureck1y commented on Tangem/App/Services/WalletConnect/WalletConnectV2Service/Utilities/WalletConnectV2Utils.swift
> +            let blockchains = SupportedBlockchains().evmBlockchains()
Ну ты возвращаешь все блокчейны, а не только evm. И в будущем тут будут не только evm. Так что самое простое тут просто все поддерживаемое аггрегировать

2023-07-26 11:59 UTC, Balashov152 commented on Tangem/App/Services/WalletConnect/WalletConnectV2Service/Utilities/WalletConnectV2Utils.swift
> +            let blockchains = SupportedBlockchains().evmBlockchains()
Так же фильтр сейчас `.filter { $0.isEvm }`
Ну окей, переделаю на mainnet + testnet )

2023-07-26 12:01 UTC, tureck1y commented on Tangem/App/Services/WalletConnect/WalletConnectV2Service/Utilities/WalletConnectV2Utils.swift
> +            let blockchains = SupportedBlockchains().evmBlockchains()
А точно, проглядел фильтр). Ну тем не менее это логика одного места в wc, зачем ее светить)

2023-07-26 13:19 UTC, Balashov152 commented on Tangem/Modules/TokenList/TokenListViewModel.swift
> +        let supportedBlockchains = mode.settings?.supportedBlockchains ?? SupportedBlockchains().blockchains(for: .v1)
Добавил `SupportedBlockchains.all` ✅

2023-07-26 13:20 UTC, Balashov152 commented on Tangem/App/Services/WalletConnect/WalletConnectV2Service/Utilities/WalletConnectV2Utils.swift
> +            let blockchains = SupportedBlockchains().evmBlockchains()
Вернул обединение только в WC )

2023-07-26 13:20 UTC, Balashov152 commented on Tangem/App/Services/WalletConnect/WalletConnectV2Service/Utilities/WalletConnectV2Utils.swift
> +            let blockchains = SupportedBlockchains().evmBlockchains()
✅

2023-07-26 15:28 UTC, ba1ashov commented
Готово, можно смотреть )

2023-07-26 15:34 UTC, tureck1y approved these changes

2023-07-27 05:05 UTC, Andoran90 approved these changes

2023-07-27 07:27 UTC, merged