IOS-1352 Add stories
tangem/tangem-app-ios-old pull request #180
Opened 2022-02-18 07:11 UTC by megakoko

2022-02-18 14:49 UTC, tureck1y requested changes

2022-02-18 14:49 UTC, tureck1y commented on Tangem/Onboarding/Welcome/WelcomeOnboardingViewModel.swift
> +    @Published var isSeeingStoriesFirstTime = true
Может сделать проще, типа такого? 
var isSeeingStoriesFirstTime: Bool { userPrefsService.isSeeingStoriesFirstTime }

Честно говоря я бы лучше инвертировал условие. Как правило дефолтное значение, оно же отсутствующее, обычно false. У нас так все ворнинги сделаны, сплэши, дисклеймеры, будет единообразно. Типа "видели сторис" = false. И после успешного сканирования я бы сразу выставлял его в true. Потому что сейчас, если после сканирования вернуться на главный, кнопок не будет.

2022-02-18 14:49 UTC, tureck1y commented on Tangem/Onboarding/Welcome/WelcomeOnboardingView.swift
> +    }
лишнее

2022-02-18 14:49 UTC, tureck1y commented on Tangem/Onboarding/Welcome/WelcomeOnboardingView.swift
> +    }
это можно тоже лучше во вьюмодель унести

2022-02-18 14:49 UTC, tureck1y commented on Tangem/Onboarding/Welcome/WelcomeOnboardingView.swift
> +                    EmptyView()
Я бы предложил небольшой рефакторинг для чистоты.
1) Унести  viewModel.isSeeingStoriesFirstTime в storiesModel. Сейчас WelcomeOnboardingViewModel просто проксирует эту штуку.
2) Свитч тоже унести в storiesModel. Добавить метод, который будет в параметрах принимать scanCard и orderCard и возвращать вьюху. Тогда верстка станет чище. progress уже есть в storiesModel
3) storiesModel.selection сделать не Int, а WelcomeStoryPage. Тогда не придется с интами работать, а то есть enum, но не используется на полную
-тогда можно будет написать вместо
private let lightStories: [WelcomeStoryPage] = [
        .backup,
        .currencies,
        .web3,
    ]
 lightStories.map { $0.rawValue }.contains(storiesModel.selection) ? .light : .dark
просто:
storiesModel.selection.colorScheme

2022-02-18 14:49 UTC, tureck1y commented on Tangem/Onboarding/Stories/StoriesBottomButtons.swift
> +            Button {
Думаю тут можно использовать нашу структуру TangemButton

2022-02-18 14:49 UTC, tureck1y commented on Tangem/Onboarding/Stories/StoriesViewModel.swift
> +    let highFpsViews: [Int]
Я думаю WelcomeStoryPage может сам сказать является он  highFpsView или нет. Сейчас получается сложно есть массив интов, который определяется в фабрике.

2022-02-18 14:49 UTC, tureck1y commented on Tangem/Onboarding/Stories/StoriesViewModel.swift
> +    private let storyDuration: Double
Похоже на просто константу. Сейчас передается 8ка из фабрики.

2022-02-18 14:49 UTC, tureck1y commented on Tangem/Onboarding/Stories/StoriesViewModel.swift
> +    let numberOfViews: Int
Если честно не очень понял историю с numberOfViews. Ты не сможешь таким образом отключить какую-то сторис, кроме последней. Тогда уже лучше передавать в конструктор массив из WelcomeStoryPage. И ходить вперед назад по нему. Тогда будет нагляднее и можно управлять тем какие сторис показывать, а какие  - нет

2022-02-21 06:28 UTC, megakoko commented on Tangem/Onboarding/Welcome/WelcomeOnboardingView.swift
> +                    EmptyView()
Я делал StoriesView и StoriesViewModel максимально абстрагированными от конкретных сторис, которые мы планируем показывать на главном экране. С прицелом на то, что возможно может будем использовать их еще где-то.

2022-02-21 06:39 UTC, megakoko commented on Tangem/Onboarding/Welcome/WelcomeOnboardingViewModel.swift
> +    @Published var isSeeingStoriesFirstTime = true
Так и задумано, т.к. мы берем значение из настроек на момент запуска приложения и сразу же изменяем его.

Само условие инвертировал.

2022-02-21 06:49 UTC, megakoko commented on Tangem/Onboarding/Welcome/WelcomeOnboardingView.swift
> +    }
Убрал

2022-02-21 06:49 UTC, megakoko commented on Tangem/Onboarding/Welcome/WelcomeOnboardingView.swift
> +    }
Переместил

2022-02-21 06:52 UTC, megakoko commented on Tangem/Onboarding/Stories/StoriesBottomButtons.swift
> +            Button {
Исправил

2022-02-21 06:54 UTC, megakoko commented on Tangem/Onboarding/Stories/StoriesViewModel.swift
> +    private let storyDuration: Double
Это чтобы не привязываться к конкретным сторисам.

2022-02-21 06:55 UTC, megakoko commented on Tangem/Onboarding/Stories/StoriesViewModel.swift
> +    let highFpsViews: [Int]
Это чтобы не привязываться к конкретным сторисам. Можно наверное через Preferences передавать, но у меня сразу не получилось, не стал тратить время.

2022-02-21 06:55 UTC, megakoko commented on Tangem/Onboarding/Stories/StoriesViewModel.swift
> +    let numberOfViews: Int
Это чтобы не привязываться к конкретным сторисам.

2022-02-21 09:51 UTC, tureck1y commented on Tangem/Onboarding/Stories/StoriesViewModel.swift
> +    private let storyDuration: Double
Все равно не понял, почему storyDuration нельзя сделать константой? Либо пусть сама сторя говорит свой duration

2022-02-21 09:55 UTC, tureck1y commented on Tangem/Onboarding/Stories/StoriesViewModel.swift
> +    let numberOfViews: Int
Не стоит проектировал эту вью модель, как универсальный движок, который переварит все что угодно. Такой задачи нет и скорее всего никогда не появится. YAGNI наше все. Даже если мы воткнем сторис на главный экран, то это будут все те же сторис, сделанные таким же образом.  Если хочется абстракции, то просто закрой свой enum со страничками каким-то описательным протоколом, в котором будет цвет, время, fps и прочая инфа. Пусть эта вьюмодель с этим протоколом и работает.

2022-02-22 09:16 UTC, megakoko commented on Tangem/Onboarding/Stories/StoriesViewModel.swift
> +    let numberOfViews: Int
Вынес в enum.

2022-02-22 09:16 UTC, megakoko commented on Tangem/Onboarding/Stories/StoriesViewModel.swift
> +    private let storyDuration: Double
Вынес в enum.

2022-02-22 09:17 UTC, megakoko commented on Tangem/Onboarding/Stories/StoriesViewModel.swift
> +    let highFpsViews: [Int]
Вынес в enum.

2022-02-22 09:39 UTC, megakoko commented on Tangem/Onboarding/Welcome/WelcomeOnboardingView.swift
> +                    EmptyView()
Исправил

2022-02-22 12:32 UTC, tureck1y requested changes

2022-02-22 12:32 UTC, tureck1y commented on Tangem/Onboarding/Stories/StoriesViewModel.swift
> +            .store(in: &bag)
эти подписки остаются активными, даже если ты уйдешь с экрана.

2022-02-22 12:32 UTC, tureck1y commented on Tangem/Onboarding/Welcome/WelcomeOnboardingView.swift
> +    ]
🪚🪚🪚

2022-02-22 15:41 UTC, megakoko commented on Tangem/Onboarding/Stories/StoriesViewModel.swift
> +            .store(in: &bag)
Исправил

2022-02-22 15:42 UTC, megakoko commented on Tangem/Onboarding/Welcome/WelcomeOnboardingView.swift
> +    ]
Выпилил

2022-02-22 15:44 UTC, tureck1y approved these changes

2022-02-22 15:45 UTC, merged