IOS-4105: Add card images to config
tangem/tangem-app-ios-old pull request #1823
Opened 2023-07-27 12:09 UTC by Andoran90

2023-07-27 12:43 UTC, tureck1y requested changes

2023-07-27 12:43 UTC, tureck1y commented on Tangem/App/Models/UserWallet/Implementations/GenericConfig.swift
> +    var cardImage: ImageType? {
я так понимаю эта картинка нужна только для хидера. В онбординге мы будем грузить как обычно. Может это как-то учесть в названии? Типа headerImage

2023-07-27 12:43 UTC, tureck1y commented on Tangem/App/Models/UserWallet/UserWalletConfig.swift
> +    var cardImage: ImageType? { nil }
давай тут не будем дефолтное создавать. Смысла не имеет, потому что в большинстве конфигов ты уже прописал, а для демо валетов - забыл, в итоге будет баг

2023-07-28 05:05 UTC, Andoran90 commented on Tangem/App/Models/UserWallet/UserWalletConfig.swift
> +    var cardImage: ImageType? { nil }
для дело воллетов я специально ничего не указывал. Уточню у Леши какая политика в отношении демо карточек.

2023-07-28 07:36 UTC, tureck1y commented on Tangem/App/Models/UserWallet/UserWalletConfig.swift
> +    var cardImage: ImageType? { nil }
ну демо на то и демо, должно быть одинаково

2023-07-28 08:08 UTC, m3g0byt3 commented on Tangem/App/Models/UserWallet/Implementations/Wallet2Config.swift
> +        cardsCount == 2 ? Assets.Cards.wallet2Double : Assets.Cards.wallet2Triple
nit: switch c ассертом на все количество карточек, кроме 2 и 3. 
Более future-proof)

2023-07-28 08:11 UTC, megakoko commented on Tangem/App/Models/UserWallet/Implementations/Wallet2Config.swift
> +        cardsCount == 2 ? Assets.Cards.wallet2Double : Assets.Cards.wallet2Triple
Переусложнение как по мне. Это продукт "воллет", он только 2х и 3х

2023-07-28 11:50 UTC, tureck1y commented on Tangem/App/Models/UserWallet/Implementations/Wallet2Config.swift
> +        cardsCount == 2 ? Assets.Cards.wallet2Double : Assets.Cards.wallet2Triple
а там не может быть ничего другого еще на уровне карты

2023-07-28 11:50 UTC, tureck1y approved these changes

2023-07-28 12:23 UTC, m3g0byt3 approved these changes

2023-07-28 12:23 UTC, merged