IOS-4118 update card header view
tangem/tangem-app-ios-old pull request #1832
Opened 2023-07-28 13:31 UTC by Andoran90

Когда реализовался заголовок было не до конца понятно надо делать раздельные вьюхи для сингл- и мультиволлет карточек, наконец в дизайне более-менее утрясли все.
* Доработал для однокошельковых карточек заголовок.
* Добавил поддержу заблокированных карточек
<img width="343" alt="TangemApp — CardHeaderView swift 2023-07-28 18-24-23" src="https://github.com/tangem/tangem-app-ios/assets/24321494/e114e0fe-ccab-4a25-bd6c-0ed15ab7d0e7">
<img width="343" alt="TangemApp — CardHeaderView - dark" src="https://github.com/tangem/tangem-app-ios/assets/24321494/85c93896-ede2-4a85-9111-0bf122f5efff">

2023-07-31 08:56 UTC, tureck1y requested changes

2023-07-31 08:56 UTC, tureck1y commented on Tangem/App/Services/UserWalletRepository/LockedUserWallet.swift
> +                self?.userWallet.name = newName
- мы хотим позволить менять имя на заблокированных кошельках? Тогда тут еще сохранение понадобится.
- на такие подписки отлично ложится weakAssign

2023-07-31 08:56 UTC, tureck1y commented on Tangem/UIComponents/CardHeaderView/CardHeaderSubtitleProvider/CardHeaderSubtitleProviderFactory.swift
> +        guard userWalletModel.isMultiWallet else {
как это будет ложиться на одновалютки с токенами, у которых дизайн мультивалюток? И две walletModel

2023-07-31 08:56 UTC, tureck1y commented on Tangem/UIComponents/CardHeaderView/CardHeaderSubtitleProvider/MultiWalletCardHeaderSubtitleProvider.swift
> +    init(userWalletModel: UserWalletModel) {
Давай не будем передавать сюда userWallet целиком

2023-07-31 08:56 UTC, tureck1y commented on Tangem/UIComponents/CardHeaderView/CardHeaderSubtitleProvider/MultiWalletCardHeaderSubtitleProvider.swift
> +        }
а потом это все рефакторить... Лучше сразу сюда передать что надо и все, может через паблишер тогда уж

2023-07-31 08:56 UTC, tureck1y commented on Tangem/UIComponents/CardHeaderView/CardHeaderSubtitleProvider/SingleWalletCardHeaderSubtitleProvider.swift
> +    init(userWalletModel: UserWalletModel, walletModel: WalletModel?) {
тут то же самое. Слишком большие сущности в конструкторе

2023-07-31 08:56 UTC, tureck1y commented on Tangem/UIComponents/CardHeaderView/CardHeaderViewModel.swift
> +        cardInfoProvider: CardHeaderInfoProvider,
сейчас только заметил, что у нас проблема с терминологией тут. Это вообще не CardHeader. Нужно будет либо разу либо отдельным мр избавиться от всех cardImage, isCardLocked, cardInfoProvider, cardSubtitle итп. С картой мы работаем только после доп сканирования, тут везде - userWallet

2023-07-31 09:04 UTC, Andoran90 commented on Tangem/UIComponents/CardHeaderView/CardHeaderSubtitleProvider/CardHeaderSubtitleProviderFactory.swift
> +        guard userWalletModel.isMultiWallet else {
по идее во время рефакторинга `CardViewModel` должна определиться логика там. Я думаю что это не обязанность фабрики вытаскивать `WalletModelManager` и проверять сколько там воллет моделов.
Думаю `CardViewModel` (или как он там будет называться в будущем) говорит кошелек мультивалютный или нет на основании `WalletModelManager`.

2023-07-31 09:07 UTC, Andoran90 commented on Tangem/UIComponents/CardHeaderView/CardHeaderSubtitleProvider/MultiWalletCardHeaderSubtitleProvider.swift
> +        }
можно добавить `UserWalletModel.isImported`. Вообще эта инфа должна быть статичной. Давай тогда булку добавлю в интерфейс `UserWalletModel` и буду эту булку сразу передавать в провайдер, потому что она меняться в принципе не должна

2023-07-31 09:11 UTC, Andoran90 commented on Tangem/UIComponents/CardHeaderView/CardHeaderSubtitleProvider/MultiWalletCardHeaderSubtitleProvider.swift
> +    init(userWalletModel: UserWalletModel) {
не совсем представляю как тогда это лучше сделать. По идее в инициализатор можно положить:
1. заблокирован кошелек или нет - булка
2. импортирован кошелек или нет - булка
3. количество карточек - паблишер.

Это все тогда отразится на интерфейсе `UserWalletModel`. Мне что-то кажется, что сейчас он растолстеет и станет ужасным, каким и является `CardViewModel`. Надо обсудить что будем делать с этим. Может отдельную сущность сделать, которая будет предоставлять инфу о `UserWallet` и о карточке?.. `UserWalletInfoProvider` какой-нибудь и в него вынести всякие свойства

2023-07-31 11:05 UTC, Andoran90 commented on Tangem/UIComponents/CardHeaderView/CardHeaderViewModel.swift
> +        cardInfoProvider: CardHeaderInfoProvider,
предлагаю сейчас все же оставить названия как есть, потому что в МРе будет совсем непонятно что было добавлено, а что удалено. Надо обсудить вообще терминологию и потом уже поправить все разом. Потому что у нас будет тогда ещё больший бардак, например есть `CardsInfoPagerView`, а он должен быть `MainPagerView`? `UserWalletPagerView`? `MainPager`? и т.д.
Ну или могу все новые файлы, которые в этом МРе назвать через UserWallet:
`UserWalletHeaderSubtitleInfo`, `UserWalletHeaderSubtitleProvider`, `MultiWalletHeaderSubtitle`, `SingleWalletHeaderSubtitle`, а с остальными несоответствиями смириться и добавить тудушки на переименовывание

2023-07-31 12:53 UTC, Andoran90 commented on Tangem/App/Services/UserWalletRepository/LockedUserWallet.swift
> +                self?.userWallet.name = newName
не даем возможность менять имя

2023-07-31 12:53 UTC, Andoran90 commented on Tangem/UIComponents/CardHeaderView/CardHeaderSubtitleProvider/MultiWalletCardHeaderSubtitleProvider.swift
> +    init(userWalletModel: UserWalletModel) {
переделал

2023-07-31 12:54 UTC, Andoran90 commented on Tangem/UIComponents/CardHeaderView/CardHeaderSubtitleProvider/SingleWalletCardHeaderSubtitleProvider.swift
> +    init(userWalletModel: UserWalletModel, walletModel: WalletModel?) {
обновил, но чет не очень прям нравится. Надо обсудить @tureck1y

2023-07-31 12:54 UTC, Andoran90 commented on Tangem/UIComponents/CardHeaderView/CardHeaderViewModel.swift
> +        cardInfoProvider: CardHeaderInfoProvider,
Поменял названия

2023-08-01 07:48 UTC, tureck1y approved these changes, later dismissed

2023-08-01 11:02 UTC, m3g0byt3 commented on Tangem/UIComponents/MainHeaderView/MainHeaderSubtitleProvider/MultiWalletMainHeaderSubtitleProvider.swift
> +    private func subscribeToUpdates() {
Кажется забыли дернуть этот метод, чтобы подписаться?

2023-08-01 11:02 UTC, m3g0byt3 commented on Tangem/UIComponents/MainHeaderView/MainHeaderSubtitleProvider/SingleWalletMainHeaderSubtitleProvider.swift
> +        }
nit: выглядит так, что это не ответственность этого метода. 

Можно разнести на два, что-то врод:
- `bind`, где выполняются все подписки, если это не локнутый юзер воллет 
и
- `applyInitialState` (не могу придумать нейминг получше), где как раз определяется, что эмитить в `self.subject` - `displayLockedWalletMessage` для локнутого или `.empty` для не-локнутого)

2023-08-01 12:32 UTC, Andoran90 commented on Tangem/UIComponents/MainHeaderView/MainHeaderSubtitleProvider/SingleWalletMainHeaderSubtitleProvider.swift
> +        }
переделал на отдельную функцию `initialSetup`, которая либо настраивает сообщение, либо же подписывается на оповещения

2023-08-01 12:33 UTC, Andoran90 commented on Tangem/UIComponents/MainHeaderView/MainHeaderSubtitleProvider/MultiWalletMainHeaderSubtitleProvider.swift
> +    private func subscribeToUpdates() {
да, добавил

2023-08-01 12:44 UTC, m3g0byt3 approved these changes

2023-08-02 05:05 UTC, tureck1y approved these changes

2023-08-02 05:05 UTC, merged