IOS-3463 main screen module with pages
tangem/tangem-app-ios-old pull request #1833
Opened 2023-07-28 14:32 UTC by Andoran90

Главная с генерацией страниц в зависимости от содержимого в репозитории. Пока только основной каркас, дальше будут заполнять контент для однокошельковых карт и для многокошельковых

https://github.com/tangem/tangem-app-ios/assets/24321494/474c5202-217c-4c8c-abbf-7c02d715e1dc

2023-07-31 08:22 UTC, skibinalexander commented on Tangem/Modules/Main/MainCardPageBuilder/MainCardPageBuilderFactory.swift
> +struct CommonMainPageContentFactory: MainPageContentFactory {
Тут какой то рассинхрон в неймингах, фабрика контента, где есть метод создания page который возвращает билдер

2023-07-31 08:22 UTC, skibinalexander commented on Tangem/Modules/Main/MainCardPageBuilder/MainCardPageBuilderFactory.swift
> +struct CommonMainPageContentFactory: MainPageContentFactory {
> Тут какой то рассинхрон в неймингах, фабрика контента, где есть метод создания page который возвращает билдер

В целом то понятно, но глаз чуть режет конечно

2023-07-31 08:23 UTC, skibinalexander commented on Tangem/Modules/Main/MainCardPageBuilder/MainCardPageBuilderFactory.swift
> +        return models.compactMap {
Тут не вижу строчку где nil возвращается для compact

2023-07-31 08:24 UTC, skibinalexander commented on Tangem/Modules/Main/MainCardPageBuilder/CardMainPageBuilder.swift
> +enum CardMainPageBuilder: Identifiable {
А мы такие вещи через enum решили делать? Не проще ли структуру данных?

2023-07-31 08:27 UTC, skibinalexander commented on Tangem/Modules/Main/MultiWalletContent/MultiWalletContentCoordinator.swift
> +    // MARK: - Child coordinators
Пустой Марк какой-то

2023-07-31 08:28 UTC, skibinalexander commented on Tangem/Modules/Main/MultiWalletContent/MultiWalletContentViewModel.swift
> +    // MARK: - ViewState
Пустой марк

2023-07-31 08:28 UTC, skibinalexander commented on Tangem/Modules/Main/SingleWalletContent/SingleWalletContentCoordinator.swift
> +    // MARK: - Child coordinators
Пустой марк

2023-07-31 08:29 UTC, skibinalexander commented on Tangem/Modules/Main/SingleWalletContent/SingleWalletContentView.swift
> +            Text("Hello, single wallet!")
Тут не очень понял, не должно быть локализовано разве?

2023-07-31 08:33 UTC, skibinalexander commented on Tangem/Modules/Main/SingleWalletContent/SingleWalletContentViewModel.swift
> +    // MARK: - ViewState
Тоже пустой, вероятно ты специально раскидывал, мы как решили, делаем так?

2023-07-31 08:34 UTC, Andoran90 commented on Tangem/Modules/Main/MultiWalletContent/MultiWalletContentCoordinator.swift
> +    // MARK: - Child coordinators
сюда будет добавляться в последующих задачах

2023-07-31 08:34 UTC, Andoran90 commented on Tangem/Modules/Main/SingleWalletContent/SingleWalletContentView.swift
> +            Text("Hello, single wallet!")
Неа, это временная заглушка, дальше будет контент набиваться)

2023-07-31 08:36 UTC, Andoran90 commented on Tangem/Modules/Main/MainCardPageBuilder/CardMainPageBuilder.swift
> +enum CardMainPageBuilder: Identifiable {
через енум проще определять какой контент лежит (через свитч можно удобно работать с ними) и меньше шансов поднакосячить

2023-07-31 08:37 UTC, Andoran90 commented on Tangem/Modules/Main/MultiWalletContent/MultiWalletContentViewModel.swift
> +    // MARK: - ViewState
обновил описание МРа

2023-07-31 08:48 UTC, Andoran90 commented on Tangem/Modules/Main/MainCardPageBuilder/MainCardPageBuilderFactory.swift
> +struct CommonMainPageContentFactory: MainPageContentFactory {
привел названия к общему. Вроде новые названия лучше всего описывают происходящее

2023-07-31 08:49 UTC, Andoran90 commented on Tangem/Modules/Main/MainCardPageBuilder/MainCardPageBuilderFactory.swift
> +        return models.compactMap {
переделал на `map`, в одной из итераций возвращался `nil`, но с тех пор много воды утекло)) а компакт мапу забыл убрать.

2023-07-31 09:12 UTC, tureck1y requested changes

2023-07-31 09:12 UTC, tureck1y commented on Tangem/Modules/Main/MainCardPageBuilder/MainCardPageBuilderFactory.swift
> +                let coordinator = MultiWalletContentCoordinator()
Тут что-то не в логике. Этот код должен запускаться в слое с координаторами.

2023-07-31 09:12 UTC, tureck1y commented on Tangem/Modules/Main/MainViewModel.swift
> +        userWalletRepository: UserWalletRepository,
Через DI

2023-07-31 09:12 UTC, tureck1y commented on Tangem/Modules/Main/MainViewModel.swift
> +        userWalletModel: UserWalletModel,
- А почему тут userWalletModel? Выбранную модель можно же получить другим способом из AppSettings.
- Надо придерживаться методологии, когда передаем минимально необходимую зависимость, а не всю сущность

2023-07-31 09:39 UTC, Andoran90 commented on Tangem/Modules/Main/MainViewModel.swift
> +        userWalletRepository: UserWalletRepository,
сделал специально так, чтобы можно было в превью подсовывать фейковый репозиторий. Что вообще думаешь на счет хранения таких зависимостей в координаторах? координаторы же создают вью модели у нас. Такой подход облегчит тестирование (юнит и превью)

2023-07-31 09:42 UTC, Andoran90 commented on Tangem/Modules/Main/MainViewModel.swift
> +        userWalletModel: UserWalletModel,
тут можно передавать вообще `UserWalletId` только, чтобы индекс воллета в репозитории получить.

2023-07-31 09:42 UTC, Andoran90 commented on Tangem/Modules/Main/MainViewModel.swift
> +        userWalletModel: UserWalletModel,
обновлю

2023-07-31 09:47 UTC, skibinalexander commented on Tangem/Modules/Main/MainCardPageBuilder/CardMainPageBuilder.swift
> +enum CardMainPageBuilder: Identifiable {
> через енум проще определять какой контент лежит (через свитч можно удобно работать с ними) и меньше шансов поднакосячить

просто тогда можно сделать структуру для: 

{
id: String, 
headerModel: CardHeaderViewModel, 
bodyModel: SingleWalletContentCoordinator
}

и в enum ее класть.

кмк enum верхедить параметрами структурного типа странновато кажется

2023-07-31 13:25 UTC, Andoran90 commented on Tangem/Modules/Main/MainCardPageBuilder/CardMainPageBuilder.swift
> +enum CardMainPageBuilder: Identifiable {
2 причины:
1. у нас разные модели в контенте. Можно сделать дженерик, но тогда надо будет на лету определять что за тип лежит внутри и создавать правильную координаторскую вьюху. Лишние усложнения на ровном месте.
2. нам надо определять что за тип, можно положить внутрь `isMultiWallet`, но мне кажется это не очень вариант, менее расширяемый

2023-07-31 13:50 UTC, Andoran90 commented
Поменял немного названия модулей, добавил к ним `Main` чтобы пояснить к чему именно относится модуль. Внутри ничего не менялось

2023-07-31 13:56 UTC, Andoran90 commented on Tangem/Modules/Main/MainCardPageBuilder/MainCardPageBuilderFactory.swift
> +                let coordinator = MultiWalletContentCoordinator()
он не может запускаться в коде с координаторами, потому что эти страницы будут генерироваться динамически, получается их надо будет все время гнать в `MainCoordinator` со всеми параметрами, чтобы они запустились?.. Спагетти какие-то получатся. Вообще мне кажется нормально что тот кто создает координатор должен его сразу же и запустить, потому что у него есть все параметры для его создания и запуска. Вроде довольно прямолинейная логика получается.

Как вариант можно добавить в `MainRoutable` какую-нибудь функцию типа: `StartCoordinators(for userWallets:[UserWalletModel]) -> [MainUserWalletPageBuilder]`, в `MainCoordinator` хранить ссылку на фабрику и потом возвращать это все во `MainViewModel`, но мне кажется это усложнит все на ровном месте... 

Может у тебя какие-то идеи есть на этот счет?

2023-07-31 14:44 UTC, Andoran90 commented on Tangem/Modules/Main/MainViewModel.swift
> +        userWalletRepository: UserWalletRepository,
обновил

2023-07-31 14:53 UTC, skibinalexander submitted a review, later dismissed

2023-08-02 05:07 UTC, tureck1y approved these changes

2023-08-02 05:49 UTC, skibinalexander approved these changes

2023-08-02 05:49 UTC, merged