IOS-3450: Update navbar on main, add new card scanning logic
tangem/tangem-app-ios-old pull request #1839
Opened 2023-07-31 08:06 UTC by Andoran90

Пришлось вынести офсет из `NavbarDotsImage` в целевые экраны где он нужен (`LegacyMainView`, `TokenDetailsView`). Офсет на новой главной сдвигает кнопки чтобы положение соответствовало дизайну.
Известные баги:
1. Не переключается на новую карточку по окончанию сканирования: https://tangem.atlassian.net/browse/IOS-4130
2. Не отображается название новых карточек: https://tangem.atlassian.net/browse/IOS-4129

https://github.com/tangem/tangem-app-ios/assets/24321494/a28a00ec-0234-42e5-a51b-f2125b3018ef

2023-07-31 09:19 UTC, tureck1y requested changes

2023-07-31 09:19 UTC, tureck1y commented on Tangem/Modules/Main/MainViewModel.swift
> +    func scanCard() {
Название неудачное. Это нажатие на кнопку, а не скан

2023-07-31 09:19 UTC, tureck1y commented on Tangem/Modules/Main/MainViewModel.swift
> +    private func scanNewCard() {
а вот это просто scanCard, не обязательно новой)

2023-07-31 09:19 UTC, tureck1y commented on Tangem/Modules/Main/MainViewModel.swift
> +    private func addNewPage(for cardModel: CardViewModel) {
давай в новом дизайне по максимуму избавляться от CardViewModel. Чтобы после рефакторинга send, details, ее больше тут нигде не осталось. Если не получатся ее тут выкинуть, то лейбл хотя бы поменять

2023-07-31 09:19 UTC, tureck1y commented on Tangem/Modules/Main/MainCardPageBuilder/MainCardPageBuilderFactory.swift
> +        let id = model.userWalletId.stringValue
Опять у нас где-то String, где-то Data. Надо что-то одно по возможности, лучше Data, чтобы не было доп конвертаций, либо весь UserWalletId, что еще лучше

2023-07-31 10:24 UTC, Balashov152 submitted a review, later dismissed

2023-07-31 16:08 UTC, Andoran90 commented on Tangem/Modules/Main/MainViewModel.swift
> +    private func addNewPage(for cardModel: CardViewModel) {
да, убрал, вообще не нужно тут

2023-07-31 16:09 UTC, Andoran90 commented on Tangem/Modules/Main/MainViewModel.swift
> +    private func scanNewCard() {
поменял

2023-07-31 16:09 UTC, Andoran90 commented on Tangem/Modules/Main/MainViewModel.swift
> +    func scanCard() {
переименовал в `scanCardAction`

2023-07-31 18:06 UTC, Andoran90 commented on Tangem/Modules/Main/MainCardPageBuilder/MainCardPageBuilderFactory.swift
> +        let id = model.userWalletId.stringValue
обновил на UserWalletId

2023-08-02 05:09 UTC, tureck1y approved these changes, later dismissed

2023-08-02 07:22 UTC, merged