IOS-4135 Renamed TokenList -> LegacyTokenList
tangem/tangem-app-ios-old pull request #1841
Opened 2023-07-31 13:20 UTC by megakoko

Тут только переименование

2023-07-31 13:34 UTC, Andoran90 requested changes

2023-07-31 13:34 UTC, Andoran90 commented on Tangem/Modules/LegacyMain/LegacyMainCoordinator.swift
> +    @Published var tokenListCoordinator: LegacyTokenListCoordinator? = nil
пригодится, когда будешь тогглом закрывать
```suggestion
    @Published var legacyTokenListCoordinator: LegacyTokenListCoordinator? = nil
```

2023-07-31 13:34 UTC, Andoran90 commented on Tangem/Modules/LegacyTokenList/LegacyManageTokensSettings.swift
> +struct LegacyManageTokensSettings {
а они тоже поменяются? сейчас получается что в `LegacyMainRoutable` есть `func openTokensList(with settings: LegacyManageTokensSettings, userTokensManager: UserTokensManager)`. Можно его тоже переименовать `openLegacyTokenList`, чтобы соответствовало параметрам и потом добавить не легаси

2023-07-31 13:35 UTC, megakoko commented on Tangem/Modules/LegacyTokenList/LegacyManageTokensSettings.swift
> +struct LegacyManageTokensSettings {
Я все переименовывал чтобы с чистого листа начать и изменения в новом не касались старого.

2023-07-31 13:38 UTC, megakoko commented on Tangem/Modules/LegacyMain/LegacyMainCoordinator.swift
> +    @Published var tokenListCoordinator: LegacyTokenListCoordinator? = nil
Переименовал, спасибо

2023-07-31 13:39 UTC, megakoko commented on Tangem/Modules/LegacyTokenList/LegacyManageTokensSettings.swift
> +struct LegacyManageTokensSettings {
Насчет openTokenList не согласен, проще внутри нужное открыть, чем динамически решать какой модуль открыть изнутри

2023-07-31 13:40 UTC, megakoko commented on Tangem/Modules/LegacyTokenList/LegacyManageTokensSettings.swift
> +struct LegacyManageTokensSettings {
А хотя не, часть функций все таки переименую

2023-07-31 13:42 UTC, Andoran90 commented on Tangem/Modules/LegacyTokenList/LegacyManageTokensSettings.swift
> +struct LegacyManageTokensSettings {
ну тут я в общем-то и не спорю, не уверен где именно будет решаться это, в новой главной уже, наверное старый или новый координатор показывать

2023-07-31 13:43 UTC, megakoko commented on Tangem/Modules/LegacyTokenList/LegacyManageTokensSettings.swift
> +struct LegacyManageTokensSettings {
В главной переименовал как ты предложил, на сторисах оставил такой код:

```
func openTokensList() {
    let dismissAction: Action = { [weak self] in
        self?.legacyTokenListCoordinator = nil
    }
    let coordinator = LegacyTokenListCoordinator(dismissAction: dismissAction)
    coordinator.start(with: .show)
    legacyTokenListCoordinator = coordinator
}

```

2023-07-31 13:45 UTC, Andoran90 submitted a review, later dismissed

2023-08-02 05:23 UTC, tureck1y commented on Tangem/Modules/LegacyTokenList/LegacyListDataLoader.swift
> -//  ListDataLoader.swift
Тоже меняется так сильно, что надо писать новый?

2023-08-02 07:54 UTC, megakoko commented on Tangem/Modules/LegacyTokenList/LegacyListDataLoader.swift
> -//  ListDataLoader.swift
Вообще нет, не должен. Я все переименовывал в legacy, чтобы начать с чистого листа и изменения в новом коде никак не влияли на старый. Если что всегда можно legacy классы использовать в новом.

2023-08-02 08:12 UTC, tureck1y commented on Tangem/Modules/LegacyTokenList/LegacyListDataLoader.swift
> -//  ListDataLoader.swift
Переименовываем только сущности модуля (View, ViewModel, CordinatorView и CoordinatorViewModel, Routable). Всякие сущности нижних уровней остаются то прежними, нет цели переписывать приложение, наоборот это вредно.

2023-08-02 08:48 UTC, megakoko commented on Tangem/Modules/LegacyTokenList/LegacyListDataLoader.swift
> -//  ListDataLoader.swift
Вообще поменяется CoinModel, которые мы в лоадере держим. Туда помимо названия/картинки надо будет добавить цену и ее изменение.

Получается изменения будут, и в слое данных, и в сетевом — другой запрос или дополнительный запрос к существующему.

2023-08-02 11:08 UTC, tureck1y commented on Tangem/Modules/LegacyTokenList/LegacyListDataLoader.swift
> -//  ListDataLoader.swift
Уточни тогда плиз как будет приходить график. Потому что на изменение цены отдельный запрос и он будет не тут скорее всего, а прям из модели ячейки запускаться. В таком случае CoinModel не поменяется. Это модель ответа на запрос коинов.

2023-08-03 08:58 UTC, tureck1y commented on Tangem/Modules/LegacyTokenList/LegacyListDataLoader.swift
> -//  ListDataLoader.swift
я предлагаю сам лоадер не переименовывать, по крайней мере пока. Его можно будет сделать дженериковым и переиспользовать

2023-08-04 11:37 UTC, megakoko commented on Tangem/Modules/LegacyTokenList/LegacyListDataLoader.swift
> -//  ListDataLoader.swift
Отревертил переименование

2023-08-04 11:37 UTC, megakoko commented
@Andoran90 @tureck1y посмотрите пожалуйста еще

2023-08-04 11:53 UTC, Andoran90 approved these changes

2023-08-08 08:44 UTC, tureck1y approved these changes

2023-08-08 08:49 UTC, merged