IOS-4059 main multi wallet content
tangem/tangem-app-ios-old pull request #1851
Opened 2023-08-03 17:13 UTC by Andoran90

Есть несколько моментов, которые будут исправлены в других МРах, пока что используются простенькие заглушки, но которые в принципе работают правильно. Места, которые будут перерабатываться пометил TODO-шками, их можно смотреть по диагонали.

Пока что убрал логику блокировки горизонтального скролла, за исключением случая ПТРа, @m3g0byt3 предложил сохранить визуальную живость интерфейса. Посмотрим как пойдет, понравится или нет такой функционал. 

В видео есть баги и глитчи UI, но они не относятся к этому МРу. Тут только отображение списка токенов. Так же есть проблема с добавлением токенов для новых сканируемых карточек, пока что загрузчик списка токенов не появляется. @tureck1y надо обсудить что с этим делать.

https://github.com/tangem/tangem-app-ios/assets/24321494/80a063dd-4102-4bd8-88ef-124d9c51c277

2023-08-07 09:09 UTC, m3g0byt3 commented on Tangem/App/Services/UserTokensManager/LockedUserTokensManager.swift
> +    }
nit: не крит, но где-то implicit return, где-то explicit (я за explicit, если тело функции находится на новой строке)

2023-08-07 09:09 UTC, m3g0byt3 commented on Tangem/App/ViewModels/CardViewModel.swift
> +            self?._didPerformInitialTokenSync.send(true)
Тут в коллбек может прилететь ошибка транспорта/бека - все равно считаем в таком случае, что изначальный синк проведен?

2023-08-07 09:09 UTC, m3g0byt3 commented on Tangem/Modules/Main/MultiWalletMainContent/MultiWalletMainContentView.swift
> +        VStack(spacing: 0) {
А это будет лениво работать, ты проверял? 
Я имею в виду `LazyVStack` в `tokensList`, завернутый в `VStack`

2023-08-07 09:09 UTC, m3g0byt3 commented on Tangem/Modules/Main/MultiWalletMainContent/MultiWalletMainContentView.swift
> +                }
Хм, возможно мне в органайз тоже надо затащить эту логику, как считаешь?🤔 
С empty/non-empty листами

_`TokenListLoadingPlaceholderView()` в органайзе не надо, так как без контента на главной не будет кнопки для перехода в органайз_

2023-08-07 09:09 UTC, m3g0byt3 commented on Tangem/Modules/Main/MultiWalletMainContent/MultiWalletMainContentView.swift
> +            ForEach(viewModel.sections, id: \.id) { section in
nit: тут и ниже возможно можно убрать явное ` id: \.id`, если модельки и так Identifiable

2023-08-07 09:09 UTC, m3g0byt3 commented on Tangem/Modules/Main/MultiWalletMainContent/MultiWalletMainContentViewModel.swift
> +        tokenSyncSubscription = nil
Не могу понять, для чего эта логика, с хранением подписки в отдельной проперти (вместо bag) и затем зануления ее? 

Если чтобы однократно дождаться `true` из `didPerformInitialTokenSyncPublisher` - то можно заюзать `filter { $0 }` +  `prefix(1)`

2023-08-07 09:09 UTC, m3g0byt3 commented on Tangem/Preview Content/Fakes/FakeWalletModelsManager.swift
> +    func updateAll(silent: Bool, completion: @escaping () -> Void) {
Понятно что фейк - но эта логика разве будет работать? Тут ведь создаем подписку, но ничего не эмитим.

Или паблишеры в 31 строчке сразу что-то заэмитят?

2023-08-07 10:42 UTC, m3g0byt3 commented on Tangem/Modules/Main/MainCardPageBuilder/MainUserWalletPageBuilderFactory.swift
> +                sectionsProvider: GroupedTokenListInfoProvider(userWalletId: id, walletModelsManager: model.walletModelsManager)
FYI завел таску на поддержку адаптера на главном https://tangem.atlassian.net/browse/IOS-4207

2023-08-07 11:47 UTC, Andoran90 commented on Tangem/App/Services/UserTokensManager/LockedUserTokensManager.swift
> +    }
мой косяк, мы в сталгайдах обсуждали, что однострочные функции должны всегда писать `return`

2023-08-07 11:48 UTC, Andoran90 commented on Tangem/App/ViewModels/CardViewModel.swift
> +            self?._didPerformInitialTokenSync.send(true)
да, т.к. тут важен сам факт начального запуска синхронизации. То что он был не успешен - не так важно, вдобавок это вообще никак не хэндлится, так что отдельной задачей возможно надо дорабатывать. Думаю в идеале показывать скрываемый ворнинг, но это не обсуждалось даже

2023-08-07 11:49 UTC, Andoran90 commented on Tangem/Modules/Main/MainCardPageBuilder/MainUserWalletPageBuilderFactory.swift
> +                sectionsProvider: GroupedTokenListInfoProvider(userWalletId: id, walletModelsManager: model.walletModelsManager)
отлично, поменял номер в комментарии

2023-08-07 12:01 UTC, Andoran90 commented on Tangem/Modules/Main/MultiWalletMainContent/MultiWalletMainContentView.swift
> +        VStack(spacing: 0) {
да, нормально, не сразу все грузит, а по частям

2023-08-07 12:04 UTC, Andoran90 commented on Tangem/Modules/Main/MultiWalletMainContent/MultiWalletMainContentView.swift
> +                }
ммм, нет, не понадобится. Кнопка `Organize Tokens` будет скрыта для случаев если токенов меньше 2. Так что пустого списка у тебя точно не будет. Обсуждал это и с Настей и с Лешей

2023-08-07 12:08 UTC, Andoran90 commented on Tangem/Preview Content/Fakes/FakeWalletModelsManager.swift
> +    func updateAll(silent: Bool, completion: @escaping () -> Void) {
да, там фейковые воллет менеджеры (`FakeWalletManager` 49 строка) кидают события

2023-08-07 12:13 UTC, Andoran90 commented on Tangem/Modules/Main/MultiWalletMainContent/MultiWalletMainContentViewModel.swift
> +        tokenSyncSubscription = nil
да, ты прав) тут даже префикс не нужен. Достаточно просто отфильтровать позитивный результат и схлопнуться. Сделал через `withExtendedLifetime` и локальной ссылкой

2023-08-08 09:16 UTC, m3g0byt3 submitted a review, later dismissed

2023-08-08 10:28 UTC, Andoran90 commented
подлил дев, поправил конфликты

2023-08-08 11:04 UTC, tureck1y requested changes

2023-08-08 11:04 UTC, tureck1y commented on Tangem/App/Services/UserWalletModel/UserWalletModel.swift
> +    var didPerformInitialTokenSync: Bool { get }
Это же относится к userTokenListManager, а не к UserWallet

2023-08-08 11:04 UTC, tureck1y commented on Tangem/Modules/Main/MultiWalletMainContent/Views/TokenList/GroupedTokenListInfoProvider.swift
> +    init(userWalletId: UserWalletId = .init(with: Data()), walletModelsManager: WalletModelsManager) {
может лучше убрать значение по умолчанию? Тут оно вообще левое

2023-08-08 11:15 UTC, Andoran90 commented on Tangem/Modules/Main/MultiWalletMainContent/Views/TokenList/GroupedTokenListInfoProvider.swift
> +    init(userWalletId: UserWalletId = .init(with: Data()), walletModelsManager: WalletModelsManager) {
мы потом выкинем этот провайдер и будем использовать тот что в `Organize tokens` используется. Давай комментарий добавлю, для чего этот инфо провайдер, чтобы никого он не сбивал

2023-08-08 11:23 UTC, Andoran90 commented on Tangem/App/Services/UserWalletModel/UserWalletModel.swift
> +    var didPerformInitialTokenSync: Bool { get }
мммм, а может и нет?.. по идее тогда надо в `UserTokenListManager` добавлять функцию `initialTokenSync` или что-то типа такого. А надо ли нам это? У нас в общем-то нет такого функционала в `UserTokenListManager` он постоянно синкается с серваком.
Или ты предлагаешь просто перетащить эту всю логику в `UserTokenListManager`?

2023-08-10 15:27 UTC, tureck1y submitted a review, later dismissed

2023-08-11 08:32 UTC, merged