IOS-4127: Add scan troubleshoot alert and onboarding navigation logic
tangem/tangem-app-ios-old pull request #1852
Opened 2023-08-03 18:35 UTC by Andoran90

Добавлена навигация на онбординг и добавление страницы для новой карточки. Сейчас эта логика выглядит странно через события `UserWalletRepository`, но не хочу ждать никаких рефакторингов, потому что непонятно как в финальном варианте это будет выглядеть, да и вообще когда подоспеет этот рефакторинг. Печаль(

Так же добавил старую логику с помощью при неудачных сканированиях карточки. Тут ничего нового

2023-08-04 13:30 UTC, skibinalexander approved these changes, later dismissed

2023-08-08 11:07 UTC, tureck1y requested changes

2023-08-08 11:07 UTC, tureck1y commented on Tangem/App/Services/UserWalletModel/UserWalletModel.swift
> +    var emailConfig: EmailConfig? { get }
так  `var config: UserWalletConfig { get }` же есть

2023-08-09 14:27 UTC, Andoran90 commented on Tangem/App/Services/UserWalletModel/UserWalletModel.swift
> +    var emailConfig: EmailConfig? { get }
самое веселое что я его нигде и не заюзал)) убрал

2023-08-09 15:19 UTC, tureck1y submitted a review, later dismissed

2023-08-11 08:35 UTC, merged