IOS-4158 Implement utxo transaction history
tangem/tangem-app-ios-old pull request #1858
Opened 2023-08-04 16:58 UTC by Balashov152

Жду https://github.com/tangem/tangem-app-ios/pull/1857

2023-08-10 10:29 UTC, m3g0byt3 commented on Tangem/App/Services/TransactionHistoryRepository/TransactionHistoryRepository.swift
> +        TransactionHistoryRepository.storage[blockchain] ?? []
А это сознательно так сделано (чтобы скрыть тот факт, что это по факту синглтон), что идет обращение к статик проперти в инстанс методах одного и того же типа?

Если это так - то предложил бы не скрывать это, а сделать этот тип классом и у него сделать проперть `shared`/`istance`, где и будет жить синглтон

2023-08-10 10:29 UTC, m3g0byt3 commented on Tangem/App/Utilities/TransactionHistoryMapper.swift
>          let dateFormatter = DateFormatter()
Предлагаю кешировать тут и в остальных местах в этом файле date форматтеры в статик пропертях, это рекомендация от эппла:
https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/DataFormatting/Articles/dfDateFormatting10_4.html#//apple_ref/doc/uid/TP40002369-SW10

2023-08-10 10:29 UTC, m3g0byt3 commented on Tangem/App/Utilities/TransactionHistoryMapper.swift
> +                        .filter { $0.address == walletAddress }
Тут и ниже, в аналогичных сравнениях `smth == walletAddress` - не может быть приколов с разным регистром, наличием/отсутствием префикса `0x` и т.д.?

2023-08-10 10:29 UTC, m3g0byt3 commented on Tangem/App/Utilities/TransactionHistoryMapper.swift
> +                        .reduce(0) { $0 + $1.amount }
nit: повторяющася логика, кажется можно вынести в что-то типа `sumForWallet(withAddress:)` (в экстеншене или же как отдельный метод в этом маппере)

2023-08-10 10:29 UTC, m3g0byt3 commented on Tangem/App/Utilities/TransactionHistoryMapper.swift
> +    func formatted(amount: Decimal) -> String {
Существующие форматтеры вроде тех, которые в `BalanceFormatter.swift` и `Decimal+.swift` - они отличаются по поведению и не подходят?

2023-08-10 10:29 UTC, m3g0byt3 commented on Tangem/App/ViewModels/WalletModel.swift
> -            .combineLatest(updateTransactionsHistory())
Если я дерну `generalUpdate` и подпишусь на него - то выходит я не получу уведомления о загрузке транзакций

Подразумевается, что теперь надо явно подписаться на ` transactionHistoryState` для этого? Если да - то эта логика обновлена во всех тех местах, где история отображается?

2023-08-10 10:29 UTC, m3g0byt3 commented on Tangem/Common/WalletManagerFactoryProvider.swift
>  class WalletManagerFactoryProvider {
nit: нейминг кажется теперь не очень отражает то, чем занимается этот класс?

2023-08-10 10:29 UTC, m3g0byt3 commented on Tangem/App/Models/LegacyTransactionRecord.swift
>  struct LegacyTransactionRecord: Hashable, Identifiable {
А почему в этом файле изменения? Он перестал юзаться как модель и оставлен просто, чтобы собирался проект? Если да - то мб завести техдолг-таску на выпил + сюда TODO с указанием таски?

2023-08-10 10:29 UTC, m3g0byt3 commented on Tangem/App/Services/TransactionHistoryRepository/WalletTransactionHistoryService.swift
> +                currentPage = response.page.number
А на каком потоке прилетает этот коллбек и происходит мутация этих пропертей? 
Нет тут проблем с многопоточкой?

2023-08-10 10:29 UTC, m3g0byt3 commented on Tangem/App/Services/TransactionHistoryRepository/WalletTransactionHistoryService.swift
> +        case notLoaded
nit: немного странно, что `notLoaded` это однократный начальный стейт, а вот `loaded` многократный и может чередоваться с `loading`.
Скорее это что-то типа `initial`

2023-08-10 10:29 UTC, m3g0byt3 commented on Tangem/Modules/TokenDetails/TokenDetailsViewModel.swift
> +                if self?.isReloadingTransactionHistory == true {
nit: Эта проверка имеет смысл?)

2023-08-10 10:29 UTC, m3g0byt3 commented on Tangem/Modules/TokenDetails/TokenDetailsViewModel.swift
>              if case .notLoaded = newState {
Это же никогда не выполнится или меня глючит?)
Мб в этот метод раньше кидался арг `oldState` и на него была тут проверка?

2023-08-10 10:29 UTC, m3g0byt3 commented on Tangem/UIComponents/TransactionHistory/TransactionsListView.swift
> +                }
Интересная логика)

А это будет работать, если уже после того, как эта логика выполнилась и progress view отобразился и дернул`fetchMoreBlock` - сам коллбек `fetchMoreBlock` сменился? 

Тут ожидается выполнение такого нового коллбека или нет? Или такая смена коллбека невозможна?

2023-08-10 14:15 UTC, tureck1y requested changes

2023-08-10 14:15 UTC, tureck1y commented on Tangem/App/Services/TransactionHistoryRepository/TransactionHistoryRepository.swift
> +        TransactionHistoryRepository.storage[blockchain] ?? []
а зачем вообще статик? Историю можно держать по аналогии с walleManager'ами.
Создавать их при создании WalletModel, пусть их WalletModel держит и шарит между собой в рамках сети.

2023-08-10 14:15 UTC, tureck1y commented on Tangem/Common/WalletManagerFactoryProvider.swift
>  class WalletManagerFactoryProvider {
я бы сделал все же отдельную фабрику под историю, она не связана с walletManager

2023-08-10 14:15 UTC, tureck1y commented on Tangem/App/Services/TransactionHistoryRepository/WalletTransactionHistoryService.swift
> +    init?(
Лучше все же вынести создание transactionHistoryProvider на уровень выше и создавать там, тогда уйдет опциоанальность конструктора

Еще как-будто не хватает закрытия этого класса протоколом, его нигде мотать не надо будет?

2023-08-10 14:15 UTC, tureck1y commented on Tangem/App/Services/TransactionHistoryRepository/WalletTransactionHistoryService.swift
> +    }
Давай сделаем var, почище будет

2023-08-10 14:15 UTC, tureck1y commented on Tangem/App/Services/TransactionHistoryRepository/WalletTransactionHistoryService.swift
> +    init?(
Еще надо подумать над неймингом. Может просто TransactionHistoryService

2023-08-10 14:15 UTC, tureck1y commented on Tangem/App/ViewModels/WalletModel.swift
> -            .combineLatest(updateTransactionsHistory())
тут сломалась логика. Метод должен паблишить когда обновлена и история и баланс

2023-08-10 14:15 UTC, tureck1y commented on Tangem/App/ViewModels/WalletModel.swift
> +    var transactionHistoryState: AnyPublisher<WalletTransactionHistoryService.State, Never> {
Удаленный вариант выглядит чище по названию

>     /// Listen tx history changes
>      var transactionHistoryPublisher: AnyPublisher<TransactionHistoryState, Never> {
>          _transactionsHistory.eraseToAnyPublisher()
>      }

2023-08-10 14:15 UTC, tureck1y commented on Tangem/App/ViewModels/WalletModel.swift
> +        walletTransactionHistoryService?.fetch()
Слишком много торчит наружу лишнего имхо. Достаточно
-апдейт истории
-сама история в виде паблишера + геттера

transactions для пользователя звучит  лучше чем transactionRecordList

И я вот думаю что WalletModel начинают пухнуть. Лучше отдавать тогда протоколом закрытую сущность для работы с историей транзакций, как мы сейчас делаем везде в UserWalletModel.

2023-08-10 14:15 UTC, tureck1y commented on Tangem/Modules/TokenDetails/TokenDetailsView.swift
> +                    fetchMoreBlock: viewModel.canFetchMoreTransactionHistory ? viewModel.fetchTransactionHistory : nil
логика по вью появилась(тернарники). Лучше во viewModel перенести.

2023-08-10 14:15 UTC, tureck1y commented on Tangem/Modules/TokenDetails/TokenDetailsViewModel.swift
> +        walletModel.fetchTransactionsHistory()
вот я так и думал, что лишнее торчит. Чем отличается load от reload. Какая вообще логика работы с историей транзакций? При заходе на экран всегда апдейтим? Или только один раз? PTR апдейтит?

2023-08-10 14:15 UTC, tureck1y commented on Tangem/Modules/TokenDetails/TokenDetailsViewModel.swift
>              if case .notLoaded = newState {
тут вообще неожиданный  сайд-эффект у метода updateHistoryState(to newState:), что вызывается fetch

2023-08-15 13:19 UTC, Balashov152 commented on Tangem/App/Services/TransactionHistoryRepository/TransactionHistoryRepository.swift
> +        TransactionHistoryRepository.storage[blockchain] ?? []
вообще идея была в том что хранить под блокчейн историю отдельно. но вообще да, можно избавиться от кэша

2023-08-15 13:20 UTC, ba1ashov commented on Tangem/App/Services/TransactionHistoryRepository/TransactionHistoryRepository.swift
> +        TransactionHistoryRepository.storage[blockchain] ?? []
Удалил вообще репозиторий этот ✅

2023-08-15 13:21 UTC, Balashov152 commented on Tangem/App/Utilities/TransactionHistoryMapper.swift
> +                        .filter { $0.address == walletAddress }
вообще не должно быть, нам тут важен адрес именно такой который передали

2023-08-15 13:32 UTC, Balashov152 commented on Tangem/App/Utilities/TransactionHistoryMapper.swift
> +                        .reduce(0) { $0 + $1.amount }
Добавил extension ✅

2023-08-15 13:32 UTC, Balashov152 commented on Tangem/App/Utilities/TransactionHistoryMapper.swift
> +    func formatted(amount: Decimal) -> String {
BalanceFormatter.swift ✅

2023-08-15 13:32 UTC, Balashov152 commented on Tangem/App/ViewModels/WalletModel.swift
> -            .combineLatest(updateTransactionsHistory())
Вернул логику, все ок

2023-08-15 13:33 UTC, Balashov152 commented on Tangem/Common/WalletManagerFactoryProvider.swift
>  class WalletManagerFactoryProvider {
Отдельный провайдер для фабрики провайдеров 😄 ✅

2023-08-15 13:34 UTC, Balashov152 commented on Tangem/Modules/TokenDetails/TokenDetailsViewModel.swift
>              if case .notLoaded = newState {
Убрал сайд эффект, первая загрузка вызывается в методе prepareSelf() ✅

2023-08-15 13:35 UTC, Balashov152 commented on Tangem/Modules/TokenDetails/TokenDetailsViewModel.swift
> +                if self?.isReloadingTransactionHistory == true {
Убрано ✅

2023-08-15 13:35 UTC, ba1ashov commented on Tangem/App/Services/TransactionHistoryRepository/WalletTransactionHistoryService.swift
> +        case notLoaded
initial  ✅

2023-08-15 13:36 UTC, Balashov152 commented on Tangem/App/Services/TransactionHistoryRepository/WalletTransactionHistoryService.swift
> +                currentPage = response.page.number
Да не должно быть, прилетает на потоке в котором была загрузка, можно как вариант на global() переключить, не знаю даже

2023-08-15 13:36 UTC, Balashov152 commented on Tangem/App/Services/TransactionHistoryRepository/WalletTransactionHistoryService.swift
> +    init?(
TransactionHistoryService/CommonTransactionHistoryService ✅

2023-08-15 13:37 UTC, Balashov152 commented on Tangem/App/Services/TransactionHistoryRepository/WalletTransactionHistoryService.swift
> +    }
✅

2023-08-15 13:37 UTC, Balashov152 commented on Tangem/App/ViewModels/WalletModel.swift
> +    var transactionHistoryState: AnyPublisher<WalletTransactionHistoryService.State, Never> {
вернул как было ✅

2023-08-15 13:37 UTC, Balashov152 commented on Tangem/Modules/TokenDetails/TokenDetailsView.swift
> +                    fetchMoreBlock: viewModel.canFetchMoreTransactionHistory ? viewModel.fetchTransactionHistory : nil
Разделил на два блока, так понятнее выглядит

2023-08-15 13:43 UTC, Balashov152 commented on Tangem/App/Utilities/TransactionHistoryMapper.swift
>          let dateFormatter = DateFormatter()
вынес как проперти

2023-08-15 14:30 UTC, Balashov152 commented on Tangem/App/Services/TransactionHistoryRepository/FakeTransactionHistoryService.swift
> +    func update() -> AnyPublisher<Void, Never> {
просто перенес из WalletModel логику

2023-08-15 14:38 UTC, Balashov152 commented on Tangem/UIComponents/TransactionHistory/TransactionsListView.swift
> +                }
Вообще такая логика работает на подгрузке токенов, и там все ок
как только лоадер появляется на экране, он начинает загрузку

2023-08-15 14:42 UTC, Balashov152 commented on Tangem/App/ViewModels/WalletModel.swift
> +        walletTransactionHistoryService?.fetch()
Все переделал )

2023-08-16 15:38 UTC, tureck1y approved these changes, later dismissed

2023-08-16 16:14 UTC, Balashov152 commented
зарезолвил конфликты

2023-08-16 16:16 UTC, tureck1y approved these changes

2023-08-17 08:18 UTC, m3g0byt3 commented on Tangem/App/ViewModels/WalletModel.swift
> +            .CombineLatest(update(silent: silent), updateTransactionsHistory())
А тут разве не будет двойных сетевых запросов за рейтами и историей транзакций?

`CombineLatest` тут подписывается на `update(silent:)` и  `updateTransactionsHistory()` и внешний потребитель тоже на них подписывается

Так как это не шаренные паблишеры - то в итоге обе подписки (и подписка тут внутри wallet model и подписка внешнего потребителя) триггернут два похода в сеть каждая

Я не вижу шаринга ни в этом пуле, не в BSDK https://github.com/tangem/blockchain-sdk-swift/pull/380/

https://jllnmercier.medium.com/combine-share-and-multicast-dcd75fa7d9d6
https://www.swiftbysundell.com/articles/using-combines-share-operator-to-avoid-duplicate-work/
https://github.com/CombineCommunity/CombineExt#sharereplay

Можешь пожалуйста проверить этот момент?

2023-08-17 08:37 UTC, m3g0byt3 commented on Tangem/App/ViewModels/WalletModel.swift
> +            .CombineLatest(update(silent: silent), updateTransactionsHistory())
Обсудили

>Andrey Fedorov [11:25 AM](https://tangem.slack.com/archives/D058FP1968L/p1692260738671449)
>ну то есть проблемы будут только если потребитель дергает и generalUpdate и updateTransactionsHistory одновременно например по кнопке?

>Sergey Balashov :green_apple: [11:28 AM](https://tangem.slack.com/archives/D058FP1968L/p1692260889027899)
>так получится что будет два запроса на историю, да

Сейчас таких мест в приложении нет, но возможность мисюза API wallet model (и двойных запросов как следствие) остается т.к. паблишеры не шарятся

2023-08-17 08:37 UTC, m3g0byt3 approved these changes

2023-08-17 08:38 UTC, merged