IOS-4240 Added FiatValue with display/raw values
tangem/tangem-app-ios-old pull request #1895
Opened 2023-08-11 13:22 UTC by megakoko

При рефакторинге потерялся код, который делал max(fiatValue, 0.01) для тотал баланса

Добавил структуру FiatValue с полями display/raw, чтобы явно каждый раз надо было выбирать что использовать. В display отформатированное, в raw обычное.

2023-08-15 08:41 UTC, m3g0byt3 commented on Tangem/App/ViewModels/WalletModel.swift
> +            }
Может переиспользовать тут логику из `BalanceFormatter.swift`, сделав у него `roundDecimal(_ :with:)` доступным снаружи?
А то сейчас расползается этот код по приложению.

2023-08-15 08:45 UTC, tureck1y commented
А где этот код был, который потерялся?

2023-08-15 08:49 UTC, megakoko commented
> А где этот код был, который потерялся?

В WalletModel

https://tangem.atlassian.net/browse/IOS-4240?focusedCommentId=17281

2023-08-15 08:58 UTC, megakoko commented on Tangem/App/ViewModels/WalletModel.swift
> +            }
Вынес в AmountRounder

2023-08-16 08:49 UTC, m3g0byt3 commented on Tangem/App/ViewModels/WalletModel.swift
> +            }
Еще такая же логика дублируется в `PushTxViewModel` и `SendViewModel`, но не предлагаю ее менять в рамках этого пула
Мб при дальнейших рефаках в этих местах

2023-08-16 08:49 UTC, m3g0byt3 approved these changes, later dismissed

2023-08-16 12:53 UTC, tureck1y requested changes
Изменения пошли немного не туда.
- Отдельная структура усложняет интерфейс ❌
- не надо выносить логику по форматированию из форматтера  ❌
- WalletModel отдает неокругленное сырое `fiatValue: Decimal` для различных вычислений
- WalletModel отдает округленную и форматированную строку `fiatBalance: String` готовую для показа на экране
- total собирает fiatValue и сам их округляет и форматирует для себя, с использованием готового форматтера

2023-08-17 09:25 UTC, megakoko commented
Упростил

2023-08-17 09:33 UTC, tureck1y commented
ты суммируешь округленные балансы, тем самым накапливая ошибку. Сначала надо сделать всю математику, потом округлять, перед отображением на экране

2023-08-17 09:37 UTC, megakoko commented
Так и надо, так раньше показывали

Если у тебя на экране

0.01 ~ 0.00005
0.01 ~ 0.00002
0.01 ~ 0.00007

То тотал должен быть 

0.03

2023-08-17 10:30 UTC, tureck1y commented
> То тотал должен быть
> 
> 0.03

Это неправильно. Тотал не становится  0.03, он по прежнему 0.01. Уже есть задача на дописывания знака < во всех таких случаях.

2023-08-17 11:13 UTC, megakoko commented
Когда еще до нее доберемся... Эта проблема есть уже сейчас. Согласен, не супер критично, но есть.

Чего тогда, закрываем этот кейс? Это регресс с прошлой версии, смена поведения

2023-08-17 11:35 UTC, closed without merging

2023-08-17 11:37 UTC, tureck1y commented
Круто, что сменилось на правильное поведение. Надо перепроверить, что у тотала есть это правильное округление на 0.01. И если там все ок, то закрываем. Отдельной задачей будем лить знак <

2023-08-17 11:39 UTC, megakoko commented
Ага, я сегодня утром перед переделкой делал всем валютам баланс по одной эфирошной копейке, показывалось 0.01 в тотале