IOS-4179 cards list doesnt refresh after disabling biometry
tangem/tangem-app-ios-old pull request #1902
Opened 2023-08-14 15:24 UTC by megakoko

* при отключении биометрии будет оставаться одна CardVM и UserWallet
* событие UserWalletRepository.deleted теперь несет в себе список UserWalletID удаленных кошельков

2023-08-15 06:12 UTC, Andoran90 requested changes

2023-08-15 06:12 UTC, Andoran90 commented on Tangem/App/Services/UserWalletRepository/CommonUserWalletRepository.swift
> +        userWallets = newUserWallets
сюда можно передать не `UserWallet`, а `UserWalletModel` и ничего по второму кругу не фильтровать. Нам вообще надо избавляться от манипуляций и с `UserWallet` и с `UserWalletModel`, а работать только с второй. Не совсем понятно зачем выполнять `savedUserWallet(withSensitiveData: false)`, если тут по названию и по контексту использования ничего не должно остаться, только 1 кошелек. Я так понимаю что `discard` будет использоваться всегда после очистки хранилища, значит там не должно быть ни одного сохраненного `UserWallet`, а значит его абсолютно бесполезно грузить и можно написать:
```suggestion
        models = [userWalletModelToKeep]
        userWallets = [userWalletModelToKeep.userWallet]
```

А ещё тут получается два действия:
1. Сохранение списка `UserWalletModel` - не sensitive data
2. Сохранение списка `UserWallet` - sensitive data.

Может лучше переименовать в `discardUserWallets(except:)`?

2023-08-15 06:12 UTC, Andoran90 commented on Tangem/App/Services/UserWalletRepository/UserWalletRepository.swift
> +    case deleted(userWalletIds: [Data])
думаю тут стоит переделать сразу с `Data` на `UserWalletId`

2023-08-15 06:12 UTC, Andoran90 commented on Tangem/Modules/Main/MainViewModel.swift
> +    private func removePage(with userWalletIds: [Data]) {
и тут тоже на `UserWalletId`. Постепенно будем переезжать на `UserWalletId` везде

``` suggestion
    private func removePages(with userWalletIds: [Data]) {
```

2023-08-15 06:12 UTC, Andoran90 commented on Tangem/Modules/Main/MainViewModel.swift
> +        selectedCardIndex = 0
тут нужна ещё проверка, если репозиторий пустой - в нем не осталось `UserWalletModel` - выйти на экран назад, но это в IOS-4156 должно быть добавлено. Оставь, пожалуйста, тудушку с новым описанием и номером задачи

2023-08-15 08:18 UTC, megakoko commented on Tangem/App/Services/UserWalletRepository/UserWalletRepository.swift
> +    case deleted(userWalletIds: [Data])
Согласен, но давай в другом МРе. Тут только исправление краша и минимальный рефакторинг

2023-08-15 08:18 UTC, megakoko commented on Tangem/Modules/Main/MainViewModel.swift
> +    private func removePage(with userWalletIds: [Data]) {
Согласен, но давай в другом МРе. Тут только исправление краша и минимальный рефакторинг

2023-08-15 08:23 UTC, megakoko commented on Tangem/App/Services/UserWalletRepository/CommonUserWalletRepository.swift
> +        userWallets = newUserWallets
Отрефакторил. Этот код вызывается в том числе когда мы делаем логаут, в этом случае будут удалены все модели/воллеты.

Название discardSensitiveData оставил, тут в том числе ключи шифрования очищаются.

2023-08-15 08:25 UTC, megakoko commented on Tangem/Modules/Main/MainViewModel.swift
> +        selectedCardIndex = 0
Добавил TODO, в этом случае логика другая будет, через логаут, в другом кейсе посмотрю

2023-08-16 09:45 UTC, Andoran90 commented on Tangem/App/Services/UserWalletRepository/CommonUserWalletRepository.swift
> +        userWallets = newUserWallets
а что ты отрефакторил? ты по комментарию отрефакторил или как?

2023-08-16 09:57 UTC, megakoko commented on Tangem/App/Services/UserWalletRepository/CommonUserWalletRepository.swift
> +        userWallets = newUserWallets
По комментарию

2023-08-16 10:01 UTC, Andoran90 commented on Tangem/App/Services/UserWalletRepository/CommonUserWalletRepository.swift
> +        userWallets = newUserWallets
вопрос: что ты отрефакторил? остается уместным. с 403 по 411 строку ничего не поменялось. Я писал коммент вчера, последние изменения были позавчера.

2023-08-16 11:23 UTC, megakoko commented on Tangem/App/Services/UserWalletRepository/CommonUserWalletRepository.swift
> +        userWallets = newUserWallets
Забыл залить изменения

2023-08-16 11:27 UTC, Andoran90 commented on Tangem/App/Services/UserWalletRepository/CommonUserWalletRepository.swift
> +    private func discardSensitiveData(except userWalletModelToKeep: CardViewModel? = nil) {
а зачем тут `CardViewModel`? мы везде стараемся от неё избавляться в пользу протокола, вдобавок в `models` лежат `UserWalletModel`

2023-08-16 11:33 UTC, megakoko commented on Tangem/App/Services/UserWalletRepository/CommonUserWalletRepository.swift
> +    private func discardSensitiveData(except userWalletModelToKeep: CardViewModel? = nil) {
Передаем selectedModel, она CardVM

2023-08-16 11:34 UTC, Andoran90 commented on Tangem/App/Services/UserWalletRepository/CommonUserWalletRepository.swift
> +    private func discardSensitiveData(except userWalletModelToKeep: CardViewModel? = nil) {
ну так она будет передаваться в виде `UserWalletModel`, нам надо избавляться от конкретной реализации в пользу протоколов и тут нет никакой сложности в этом

2023-08-16 11:43 UTC, megakoko commented on Tangem/App/Services/UserWalletRepository/CommonUserWalletRepository.swift
> +    private func discardSensitiveData(except userWalletModelToKeep: CardViewModel? = nil) {
Поменял

2023-08-16 11:44 UTC, Andoran90 approved these changes, later dismissed

2023-08-16 14:15 UTC, tureck1y commented
а это наверное в релиз надо? Там уже новая логика репы залита

2023-08-16 14:17 UTC, tureck1y reviewed
👀

2023-08-17 07:29 UTC, megakoko commented
> а это наверное в релиз надо? Там уже новая логика репы залита

В старом дизайне насколько я помню нет завязки на то, что обязательно должна быть хотя бы одна модель в списке, падало в новом. Лучше лишних изменений не превностить в релиз

2023-08-17 07:50 UTC, tureck1y submitted a review, later dismissed

2023-08-18 08:06 UTC, megakoko commented
Были конфликты, подлил дев. Посмотрите еще, пожалуйста

2023-08-18 08:25 UTC, Andoran90 approved these changes

2023-08-18 09:16 UTC, tureck1y approved these changes

2023-08-18 09:16 UTC, merged