IOS-4152: Token items repository refactoring
tangem/tangem-app-ios-old pull request #1905
Opened 2023-08-15 06:52 UTC by m3g0byt3

[IOS-4152](https://tangem.atlassian.net/browse/IOS-4152)

2023-08-17 18:17 UTC, m3g0byt3 commented on Tangem/App/Migrators/StorageEntriesMigrator.swift
> +        v1Wallets.forEach { cardId, v1StorageEntries in
перекладываем v1 в v2 (эта логика взята as is из `CommonTokenItemsRepository`)...

2023-08-17 18:18 UTC, m3g0byt3 commented on Tangem/App/Migrators/StorageEntriesMigrator.swift
> +            let walletMigrationResult = migrateV2StorageEntries(v2StorageEntries, forCardID: cardId)
...затем перекладываем полученные v2 в v3

2023-08-17 18:19 UTC, m3g0byt3 commented on Tangem/App/Migrators/StorageEntriesMigrator.swift
> +        }
v1 - это то что сейчас `LegacyToken` и `LegacyCloudToken`
v2 - это то что сейчас `StorageEntry`
v3 - последняя версия

2023-08-17 18:23 UTC, m3g0byt3 commented on Tangem/App/Models/StorageEntry/StorageEntry.V1.swift
> +    enum V1 {
В принципе если эта модель еще нужна - ее можно утащить внутрь `StorageEntriesMigrator`, чтобы не загрязнять неймспейс. В идеале конечно она должна быть с internal видимостью в своем отдельном модуле

2023-08-17 18:24 UTC, m3g0byt3 commented on Tangem/App/Models/StorageEntry/StorageEntry.V2.swift
> +    enum V2 {
Это то что сейчас`StorageEntry`

В принципе если эта модель еще нужна - ее можно утащить внутрь `StorageEntriesMigrator`, чтобы не загрязнять неймспейс. В идеале конечно она должна быть с internal видимостью в своем отдельном модуле

2023-08-17 18:30 UTC, m3g0byt3 commented on Tangem/App/Models/UserWallet/UserWalletConfig.swift
> +    var embeddedBlockchains: [StorageEntry.V3.Entry]? { get }
Мне не очень нравится этот интерфейс для конфигов, хотелось бы обсудить как лучше сделать:
1. Почему тут в интерфейсе модели слоя хранения данных, а не домена (`Blockchain` и `Token`)?
2. Чтобы повторить логику, когда в некоторых конфигах `embeddedBlockchains` это не только сама сетка, но иногда еще и ее токены - пришлось сделать тут массив, что сбивает с толку и неочевидно. Возможно тут стоит завести модельку-контейнер типа `StorageEntry.V2` чтобы все лежало в одном месте:
```
struct ConfigBlockchain {
    let blockchainNetwork: BlockchainNetwork
    var tokens: [Token]
}
```
и юзать ее во всех трех этих пропертях у конфига

2023-08-17 18:32 UTC, m3g0byt3 commented on Tangem/App/Models/UserWallet/Implementations/GenericConfig.swift
> +    var defaultBlockchains: [StorageEntry.V3.Entry] {
Во всех конфигах сохранена существующая логика для пропертей `defaultBlockchains`, `persistentBlockchains`, `embeddedBlockchains`, только с учетом того, что теперь и коины и токены - это свободный список

Алсо для обсуждения https://github.com/tangem/tangem-app-ios/pull/1905/files#r1297596091

2023-08-17 18:38 UTC, m3g0byt3 commented on Tangem/App/Services/TokenItemsRepository/CommonTokenItemsRepository.swift
> -        let entries: [StorageEntry]? = try? persistanceStorage.value(for: .wallets(cid: key))
Не было защищено очередью, это же наверное случайно забыли добавить?

2023-08-17 18:45 UTC, m3g0byt3 commented on Tangem/App/Services/TokenItemsRepository/CommonTokenItemsRepository.swift
>          lockQueue.sync {
Логика по добавлению новых токенов/сеток, добавлению новых токенов к существующим сеткам и обновлений существующих токенов без id сохранена:
1. Где возможно - поиск за O(1) в словарях вместо многократного O(N)
2. Логика вынесена из экстеншенов коллекций, мне кажется странно ее держать в них (пусть даже и приватных)

2023-08-17 18:48 UTC, m3g0byt3 commented on Tangem/App/Services/TokenItemsRepository/TokenItemsRepository.swift
> -    func remove(_ tokens: [Token], blockchainNetwork: BlockchainNetwork)
Показалось странно, что ранее репозиторий в своем интерфейсе работал не со своими моделями (`StorageEntry`), а доменными моделями из BSDK

2023-08-17 18:57 UTC, m3g0byt3 commented on Tangem/App/Services/TokenItemsRepository/StorageEntriesConverter.swift
> +            id: blockchainNetwork.blockchain.coinId,
Я почитал комменты в `Blockchain+.swift`, но не уверен, что мне надо юзать в качестве айдишника тут для модельки сохраняемой на диск - `coinId` или `networkId`?

С таким расчетом, чтобы потом из этой модельки восстановить `BlockchainNetwork`

2023-08-17 19:01 UTC, m3g0byt3 commented on Tangem/App/Services/TokenItemsRepository/TokenItemsRepository.swift
> -    var containsFile: Bool { get }
По неймингу вообще не понял, для чего проперть
Но можно обсудить, если так привычнее

2023-08-17 19:04 UTC, m3g0byt3 commented on Tangem/App/Services/UserTokenListManager/UserTokenListManager.swift
>      var userTokenList: AnyPublisher<UserTokenList, Never> { get }
Выставлять DTO сетевое наружи такое себе, выпиливается в IOS-4297

2023-08-17 19:06 UTC, m3g0byt3 commented on Tangem/App/Services/UserTokenListManager/CommonUserTokenListManager.swift
> -    func mapToTokens(entries: [StorageEntry]) -> [UserTokenList.Token] {
Вынесено в `UserTokenListConverter`

2023-08-17 19:10 UTC, m3g0byt3 commented on Tangem/App/Services/UserTokensManager/CommonUserTokensManager.swift
> +        guard !storageEntries.isEmpty else { return false }
Эквивалентные проверки

2023-08-17 19:10 UTC, m3g0byt3 commented on Tangem/App/Services/UserTokensManager/CommonUserTokensManager.swift
> +        guard !storageEntries.isEmpty else { return false }
Эквивалентные проверки

2023-08-17 19:12 UTC, m3g0byt3 commented on Tangem/App/Services/UserTokensManager/CommonUserTokensManager.swift
> -        let hasNoTokens = entry.tokens.isEmpty
Эквивалентные проверки

2023-08-17 19:15 UTC, m3g0byt3 commented on Tangem/Common/Extensions/Array+.swift
> -
Переехало в `Sequence`, т.к. эти хелперы были где-то нужны не только для массива

2023-08-17 19:17 UTC, m3g0byt3 commented on Tangem/Modules/LegacyMain/LegacyMultiWalletContentView/LegacyMultiWalletContentViewModel.swift
>      func collectTokenItemViewModels() -> [LegacyTokenItemViewModel] {
Логика по формированию вьюмоделей не менялась, где возможно - поиск за O(1) в словарях вместо многократного O(N)

2023-08-17 19:18 UTC, m3g0byt3 commented on Tangem/Modules/Main/MultiWalletMainContent/Views/TokenList/GroupedTokenListInfoProvider.swift
> +    private func convertToSectionInfo(
Логика по формированию вьюмоделей не менялась, где возможно - поиск за O(1) в словарях вместо многократного O(N)

2023-08-21 10:10 UTC, ba1ashov commented on Tangem/App/Services/TokenItemsRepository/StorageEntriesConverter.swift
> +            id: blockchainNetwork.blockchain.coinId,
лучше coinId, это id монеты, бывает что для монеты и для сети(этой монеты) разные id. Хз зачем так делают, и получается что есть токены в сети(networkId) а есть основная монета сети(coinId)

2023-08-21 10:12 UTC, Balashov152 commented on Tangem/App/Services/TokenItemsRepository/TokenItemsRepository.swift
> -    func remove(_ tokens: [Token], blockchainNetwork: BlockchainNetwork)
Вообще надо `Token` который в BSDK переводить на наш `Token`. Как понимаю добавлялось ранее из за того что торопились

2023-08-21 14:58 UTC, Andoran90 reviewed
1 часть, завтра утром продолжу

2023-08-21 14:58 UTC, Andoran90 commented on Tangem/App/Migrators/StorageEntriesMigrator.swift
> +        to newVersion: StorageEntry.Version,
немного странно, что сюда передается версия но только для записи лога. Думаю лучше вынести отдельно текущую версию в константу и на неё ориентироваться. Например передавать её в инициализаторе, т.к. у тебя все равно не будет миграций на несколько разных версий.

2023-08-21 14:58 UTC, Andoran90 commented on Tangem/App/Migrators/StorageEntriesMigrator.swift
> +            AppLog.shared.debug(
думаю нам стоит сделать для себя всякие информационные события и отправлять их в амлитуду, чтобы лучше понимать что происходит на устройствах у пользователей. Надо обсудить с @tureck1y  и Лешей. До этого Леша соглашался на события для разработчиков, хорошо бы разработать систему под это. К примеру, мы отправляем событие, что у пользователя запустилась миграция с первой версии, и если больше двух месяцев не приходят такие события - удалять нафиг эту миграционную логику. А то захламляем себе код всем этим

2023-08-21 14:58 UTC, Andoran90 commented on Tangem/App/Migrators/StorageEntriesMigrator.swift
> +        v1Wallets.forEach { cardId, v1StorageEntries in
хотелось бы избавиться от логики перекладывания из одного в другое, а потом в третье. Возможно вообще лучше дропнуть эту штуку и забыть. Вряд ли у кого-то есть ещё первый вариант хранения

2023-08-21 14:58 UTC, Andoran90 commented on Tangem/App/Models/StorageEntry/StorageEntry.V1.swift
> +    enum V1 {
думаю можно грохнуть её

2023-08-21 14:58 UTC, Andoran90 commented on Tangem/App/Models/StorageEntry/StorageEntry.V2+.swift
> +    }
а зачем это? нигде вроде не используется. вдобавок мигрируем с этой версии

2023-08-21 14:58 UTC, Andoran90 commented on Tangem/App/Models/StorageEntry/StorageEntry.V3.swift
> +        typealias BlockchainNetwork = Tangem.BlockchainNetwork
а зачем это?

2023-08-21 14:58 UTC, Andoran90 commented on Tangem/App/Models/UserWallet/UserWalletConfig.swift
> +    var embeddedBlockchains: [StorageEntry.V3.Entry]? { get }
2. В старых карточках была зашита сеть и иногда токен, т.е. это карточки в которых всегда есть сеть + токен и ты не можешь их удалить. Например есть карточка `NODL` - Сеть `Stellar` и токен `NODL`

2023-08-21 14:58 UTC, Andoran90 commented on Tangem/App/Models/UserWallet/UserWalletConfig.swift
> +    var embeddedBlockchains: [StorageEntry.V3.Entry]? { get }
думаю тут уместно будет сразу переименовать все в `...Tokens`. @tureck1y

2023-08-21 14:58 UTC, Andoran90 commented on Tangem/App/Models/UserWallet/Implementations/LegacyConfig.swift
> +        return defaultBlockchains.filter { $0.blockchainNetwork == blockchainNetworks.first }
Мне кажется так более понятная логика получается и меньше операций необходимо выполнить.
```suggestion
        guard let firstBlockchainNetwork = defaultBlockchains.first?.blockchainNetwork else {
            return []
        }

        return defaultBlockchains.filter { $0.blockchainNetwork == firstBlockchainNetwork }
```

2023-08-21 14:58 UTC, Andoran90 commented on Tangem/App/Services/TokenItemsRepository/StorageEntriesConverter.swift
> +    func convert(
мне кажется стоит название дополнить: `convertToEntry` или `convertToStorageEntry`
и следующую функцию тоже

2023-08-22 07:55 UTC, Andoran90 reviewed
2 часть 😅😅

2023-08-22 07:55 UTC, Andoran90 commented on Tangem/App/Models/UserWallet/UserWalletConfig.swift
> +    var embeddedBlockchains: [StorageEntry.V3.Entry]? { get }
@tureck1y может обновим `TokenItem`? заменим `Blockchain` -> `BlockchainNetwork` и будем его использовать везде в приложении, а `StorageEntry` оставим только в `UserTokenListManager` и его зависимостях (создание, превращение `TokenItem` в `StorageEntry`, синк с серваком, сохранение в локальное хранилище)?

2023-08-22 07:55 UTC, Andoran90 commented on Tangem/App/Services/TokenItemsRepository/TokenItemsRepository.swift
> -    var containsFile: Bool { get }
потому что инициализация не означает наличие файла. Инициализация может подразумевать множество различных действий (например миграция хранилища, сохранение версии хранилища), а важно было знать имеется ли файл со списком токенов на диске или нет, остальное не важно. 

Например:
1. Карточка, которая прошла онбординг, у неё нет старой версии в хранилище (т.к. карточка только заонбордилась), но мы записываем самостоятельно файл с 2 токенами - биток и эфир. Наличие файла - `true`. Надо отправить информацию на бэк, чтобы сохранить информацию о новой карточке. Скелетон списка токенов показывать не надо
2. Карточка, в которой есть уже кошельки (не надо проходить онбординг), в хранилище нет файла (значит новая карточка для приложения), нам надо показать скелетон списка токенов и запросить информацию с бэка о списке валют. Результат с бэка записать в хранилище.
3. Карточка, которая у тебя была ранее сохранена, у неё есть старая версия хранилища, для нее файл есть, значит скелетон списка показывать не надо, но обновить инфу с бэка нужно.

2023-08-22 07:55 UTC, Andoran90 commented on Tangem/App/Services/TokenItemsRepository/CommonTokenItemsRepository.swift
> +    private var currentStorageVersion: StorageEntry.Version = .v3
немного странная логика с версиями получается. Репозиторий говорит о том что он 3 версии, мигратор проверяет есть ли старые записи и игнорирует эту инфу. Может лучше пусть мигратор тогда сам все время определяет версию, а репозиторий говорит какой версии должно быть хранилище? Потому что запись этой версии выглядит бессмысленно, если мигратор все равно перепроверяет все, да и не используется это поле нигде больше. `StorageEntriesMigrator.getCurrentStorageVersion` может не принимать никакие параметры, а просто возвращать версию `v3`, если записи 1 и 2 версии не были найдены

2023-08-22 07:55 UTC, Andoran90 commented on Tangem/App/Migrators/StorageEntriesMigrator.swift
> +final class StorageEntriesMigrator {
может спрятать `StorageEntriesMigrator` внутрь `CommonTokenItemsRepository`? Все равно он нужен только для него, а тут внутри нет очереди для чтения и записи. Очередь создается внутри репозитория, но доступ к этому мигратору открытый по всему приложению.

Вообще в идеале бы сделать протокол мигратора и передавать его в инициализатор `CommonTokenItemsRepository` (влажные мечты о хотя бы 50% покрытии тестами аппки)...

2023-08-22 07:55 UTC, Andoran90 commented on Tangem/App/Services/TokenItemsRepository/CommonTokenItemsRepository.swift
> +        forCardID cardID: String
`cardId` надо убрать. Вдобавок тут не используется `cardId`, а используется `UserWalletId` для 2 версии, а для первой использовался `card id`

2023-08-22 07:55 UTC, Andoran90 commented on Tangem/App/Migrators/StorageEntriesMigrator.swift
> +        v1Wallets.forEach { cardId, v1StorageEntries in
вот тут удалялась миграция с 1 версии на вторую, т.к. это было давно и вряд ли кем-то использовалась. Так что можно удалять `v1`. Сейчас достаточно миграции с `v2` -> `v3`
https://github.com/tangem/tangem-app-ios/pull/1908/files

2023-08-22 07:55 UTC, Andoran90 commented on Tangem/App/Services/TokenItemsRepository/CommonTokenItemsRepository.swift
> +            let existingEntriesWithIndicesGroupedByBlockchainNetworks = Dictionary(
слишком много информации в названии. Для локальных функций думаю можно проще брать названия и сокращать какие-то части, т.к. их не надо запоминать для всего класса.
```suggestion
            let existingEntriesGroupedByNetwork = Dictionary(
```

2023-08-22 07:55 UTC, Andoran90 commented on Tangem/App/Services/TokenItemsRepository/CommonTokenItemsRepository.swift
> +            let newBlockchainNetworks = entries.unique(by: \.blockchainNetwork).map(\.blockchainNetwork)
много где используется один и тот же код. Думаю стоит добавить для `Sequence` расширение:
``` swift
  func extractUniqueProperties<T>(by keyPath: KeyPath<Element, T>) -> [T] where T: Hashable {
      var seen: Set<T> = []

      return compactMap { element in
          let property = element[keyPath: keyPath]
          return seen.insert(property).inserted ? property : nil
      }
  }
```

2023-08-22 15:50 UTC, Andoran90 reviewed
3 часть 😅😅😅
почти закончил осталось несколько больших функций с конвертациями во вью модели, но думаю там ничего уже особо не будет

2023-08-22 15:50 UTC, Andoran90 commented on Tangem/App/Services/TokenItemsRepository/CommonTokenItemsRepository.swift
> +            markCacheAsDirty()
не совсем понимаю зачем именно так делать. Можно же сразу в кэш закинуть новую версию и усе

2023-08-22 15:50 UTC, Andoran90 commented on Tangem/App/Services/TokenItemsRepository/CommonTokenItemsRepository.swift
> +        let existingEntriesWithIndicesKeyedByContractAddress = existingEntriesWithIndices.keyedFirst(by: \.1.contractAddress)
[Optional]
не знаю как остальным, но мне тяжело читать такие длинные названия. Не думаю что в них есть много смысла для локальных переменных. Вдобавок тут итак понятно из контекста что ключем будет - `contractAddress`.
```suggestion
        let existingEntriesKeyedByContract = existingEntriesWithIndices.keyedFirst(by: \.1.contractAddress)
```

2023-08-22 15:50 UTC, Andoran90 commented on Tangem/App/Services/UserTokensManager/CommonUserTokensManager.swift
> +            }
чет тут неправильно будто и в старом и в новом варианте... `TokenItem` является или основной валютой или токеном. Получается что лишние записи добавляются и основная сеть будет дублироваться. Ты не проверял этот момент?

2023-08-22 15:50 UTC, Andoran90 commented on Tangem/App/Services/UserTokensManager/CommonUserTokensManager.swift
> +        guard !storageEntries.isEmpty else { return false }
думаю не совсем, в твоем варианте будет проверяться весь список, в старом варианте ранний выход из цикла был. Тут уместнее всю функцию переписать, т.к. теперь будет плоский список. Не тестировал код, но думаю будет норм работать

``` swift
func contains(_ tokenItem: TokenItem, derivationPath: DerivationPath?) -> Bool {
    let blockchainNetwork = makeBlockchainNetwork(for: tokenItem.blockchain, derivationPath: derivationPath)
    switch tokenItem {
    case .blockchain(let blockchain):
        return userTokenListManager.userTokens.first(where: { $0.blockchainNetwork == blockchainNetwork }) != nil
    case .token(let token, let blockchain):
        let searchingEntry = StorageEntriesConverter().convert(token, in: blockchainNetwork)
        return userTokenListManager.userTokens.contains(searchingEntry)
    }
}
```

Надо учитывать что у пользователей может быть добавлено много разных сетей и множество токенов в каждой сети.

2023-08-23 10:56 UTC, tureck1y commented on Tangem/App/Models/UserWallet/UserWalletConfig.swift
> +    var embeddedBlockchains: [StorageEntry.V3.Entry]? { get }
это в планах, но не сейчас, очень много изменений

2023-08-23 10:57 UTC, tureck1y commented
слишком много лишних изменений

2023-08-23 10:57 UTC, tureck1y commented
на данном этапе нужен рефакторинг нижнего слоя и все

2023-08-23 11:05 UTC, tureck1y requested changes
Слишком значительные изменения. У нас невероятно сжатые сроки. Сейчас нам нужно решить проблему хранения списка, вместо наших моделей и все.  МИНИМУМ изменений.

- миграция должна быть только одна с текущего метода хранения - на список. Остальные можно снести.
- не нужно накручивать версионирования, это не то что будет часто меняться и не стоит тратить время.
- в моем понимании - при первом старте делаем миграцию на список (уже Был код получений списку)
- правим tokenitemsrepository. Нужно сохранить логику, интерфейсы, чтобы не было дубликатов и прочего. Продолжаем работать со StorageEntry

2023-08-25 10:48 UTC, m3g0byt3 commented on Tangem/App/Services/TokenItemsRepository/CommonTokenItemsRepository.swift
>          lockQueue.sync {
Вообще достаточно странно, что репо занимается такой логикой, как обновление токенов при добавлении. Это явно не его зона ответственности, а менеджеров выше

2023-08-25 11:00 UTC, m3g0byt3 commented on Tangem/App/Services/TokenItemsRepository/TokenItemsRepository.swift
> -    var containsFile: Bool { get }
Странно выглядит, когда у нас абстрактный интерфейс репозитория, реализация хранилища в которомо может быть каким угодно (remote, sql, in-memory, file) - но при этом в этом интерфейсе явное упоминание каких-то файлов.

Но вернул обратно для уменьшения чейнджей

2023-08-25 11:03 UTC, m3g0byt3 commented on Tangem/App/Services/TokenItemsRepository/UserTokenListConverter.swift
> +            .unique() /// Additional uniqueness check for remote tokens (replicates old behavior)
Ранее при маппинге local->remote была проверка на уникальность (`CommonUserTokenListManager.swift:209` и `CommonUserTokenListManager.swift:223`)

2023-08-25 11:05 UTC, m3g0byt3 commented on Tangem/App/Services/TokenItemsRepository/UserTokenListConverter.swift
> +                    return nil // Duplicate detected
Ранее при маппинге remote->local была проверка на уникальность (`CommonUserTokenListManager.swift:259`)

**Только для токенов**

2023-08-25 11:14 UTC, m3g0byt3 commented on Tangem/Common/OrganizeWalletModels/OrganizeWalletModelsAdapter.swift
>  final class OrganizeWalletModelsAdapter {
Поддержка токенов без деривации и уход от WalletModel в этом классе (включая нейминг) - реализована в IOS-4297

2023-08-25 11:16 UTC, m3g0byt3 commented on Tangem/Preview Content/Fakes/FakeUserTokenListManager.swift
>  class FakeUserTokenListManager: UserTokenListManager {
Мок/стаб, можно не смотреть

2023-08-25 11:16 UTC, m3g0byt3 commented on Tangem/Preview Content/Fakes/FakeUserTokensManager.swift
> +extension FakeUserTokensManager: UserTokensReordering {
Мок/стаб, можно не смотреть

2023-08-25 11:16 UTC, m3g0byt3 commented on Tangem/Preview Content/Mocks/UserTokenListManagerMock.swift
> +    var userTokensList: StoredUserTokenList { .empty }
Мок/стаб, можно не смотреть

2023-08-25 11:17 UTC, m3g0byt3 commented on Tangem/Preview Content/Mocks/UserTokensManagerMock.swift
> +extension UserTokensManagerMock: UserTokensReordering {
Мок/стаб, можно не смотреть

2023-08-25 12:24 UTC, m3g0byt3 commented on Tangem/App/Migrators/StorageEntriesMigrator.swift
> +        v1Wallets.forEach { cardId, v1StorageEntries in
Не актуально

2023-08-25 12:24 UTC, m3g0byt3 commented on Tangem/App/Models/StorageEntry/StorageEntry.V1.swift
> +    enum V1 {
Legacy (v1) entry удалены

2023-08-25 12:25 UTC, m3g0byt3 commented on Tangem/App/Models/UserWallet/UserWalletConfig.swift
> +    var embeddedBlockchains: [StorageEntry.V3.Entry]? { get }
Не актуально

2023-08-25 12:28 UTC, m3g0byt3 commented on Tangem/App/Services/TokenItemsRepository/CommonTokenItemsRepository.swift
>          lockQueue.sync {
Задача на рефакторинг `TokenItemsRepository` и `UserTokenListManager` https://tangem.atlassian.net/browse/IOS-4403 

Как минимум вижу следующие проблемы:
1. TokenItemsRepository делает логику верхнего уровня, вроде обновления кастомных токенов
2. `UserTokenListManager` имеет кучу разных методов в интерфейсе, какие-то работают с StorageEntry, какие-то с StoredUserTokenList - полный бардак
3. `UserTokenListManager` - это медиатор, но почему то сам ходит в сеть

2023-08-25 12:29 UTC, m3g0byt3 commented on Tangem/App/Services/TokenItemsRepository/StorageEntriesConverter.swift
> +            id: blockchainNetwork.blockchain.coinId,
Используется coinId

2023-08-25 12:29 UTC, m3g0byt3 commented on Tangem/App/Services/UserTokensManager/CommonUserTokensManager.swift
> +        guard !storageEntries.isEmpty else { return false }
Не актуально

2023-08-25 12:30 UTC, m3g0byt3 commented on Tangem/App/Migrators/StorageEntriesMigrator.swift
> +            AppLog.shared.debug(
Логирование выпилено для уменьшения чейнджей

2023-08-25 12:30 UTC, m3g0byt3 commented on Tangem/App/Migrators/StorageEntriesMigrator.swift
> +        to newVersion: StorageEntry.Version,
Логирование выпилено для уменьшения чейнджей

2023-08-25 12:31 UTC, m3g0byt3 commented on Tangem/App/Models/StorageEntry/StorageEntry.V3.swift
> +        typealias BlockchainNetwork = Tangem.BlockchainNetwork
Не актуально

2023-08-25 12:31 UTC, m3g0byt3 commented on Tangem/App/Models/UserWallet/Implementations/LegacyConfig.swift
> +        return defaultBlockchains.filter { $0.blockchainNetwork == blockchainNetworks.first }
Не актуально

2023-08-25 12:31 UTC, m3g0byt3 commented on Tangem/App/Services/TokenItemsRepository/CommonTokenItemsRepository.swift
> +    private var currentStorageVersion: StorageEntry.Version = .v3
Не актуально

2023-08-25 12:31 UTC, m3g0byt3 commented on Tangem/App/Services/TokenItemsRepository/CommonTokenItemsRepository.swift
> +        forCardID cardID: String
Не актуально

2023-08-25 12:33 UTC, m3g0byt3 commented on Tangem/App/Models/StorageEntry/StorageEntry.V2+.swift
> +    }
Не актуально

2023-08-25 12:34 UTC, m3g0byt3 commented on Tangem/App/Services/UserTokensManager/CommonUserTokensManager.swift
> +            }
Не актуально

2023-08-25 12:36 UTC, m3g0byt3 commented on Tangem/App/Services/TokenItemsRepository/StorageEntriesConverter.swift
> +    func convert(
Добавлено, но теперь это переехало в `LegacyStorageEntriesConverter` и используется только для миграции

2023-08-25 12:37 UTC, m3g0byt3 commented on Tangem/App/Migrators/StorageEntriesMigrator.swift
> +final class StorageEntriesMigrator {
Миграция перемещена внутрь `CommonTokenItemsRepository`

2023-08-25 12:38 UTC, m3g0byt3 commented on Tangem/App/Services/TokenItemsRepository/CommonTokenItemsRepository.swift
> +            let newBlockchainNetworks = entries.unique(by: \.blockchainNetwork).map(\.blockchainNetwork)
Да, норм идея - добавил `uniqueProperties`

2023-08-25 12:39 UTC, m3g0byt3 commented on Tangem/App/Services/TokenItemsRepository/CommonTokenItemsRepository.swift
> +            markCacheAsDirty()
Не актуально

2023-08-25 12:39 UTC, m3g0byt3 commented on Tangem/App/Services/TokenItemsRepository/CommonTokenItemsRepository.swift
> +        let existingEntriesWithIndicesKeyedByContractAddress = existingEntriesWithIndices.keyedFirst(by: \.1.contractAddress)
Не актуально

2023-08-25 12:50 UTC, m3g0byt3 commented on Tangem/App/Services/TokenItemsRepository/TokenItemsRepository.swift
> -    func remove(_ tokens: [Token], blockchainNetwork: BlockchainNetwork)
Не актуально, сейчас репозиторий хранит `StoredUserTokenList.Entry` - соответственно на удаление поступает `StoredUserTokenList.Entry` (который конвертится из `Token` на уровне выше, в `CommonUserTokenListManager`)

2023-08-25 12:51 UTC, m3g0byt3 commented on Tangem/App/Services/TokenItemsRepository/CommonTokenItemsRepository.swift
> +            let existingEntriesWithIndicesGroupedByBlockchainNetworks = Dictionary(
Поправил в тех местах, где еще актуально

2023-08-25 12:53 UTC, m3g0byt3 commented
Обновил пул, затронуты только нижние слои

2023-08-25 14:36 UTC, tureck1y reviewed
Выглядит ок, сейчас еще кейсов потестить накидаю

2023-08-25 14:36 UTC, tureck1y commented on Tangem/App/Services/TokenItemsRepository/TokenItemsRepository.swift
>      func remove(_ blockchainNetworks: [BlockchainNetwork])
А этот остается?

2023-08-28 14:01 UTC, Andoran90 commented on Tangem/App/Services/TokenItemsRepository/TokenItemsRepository.swift
> -    var containsFile: Bool { get }
да, согласен, надо другое название подобрать

2023-08-28 14:01 UTC, Andoran90 commented on Tangem/App/Services/TokenItemsRepository/TokenItemsRepository.swift
> -    var containsFile: Bool { get }
кстати, проверь, пожалуйста, на новой главной нормально ли происходит переключение с загрузчика списка токенов на, собственно, сам список. Сейчас есть бажок связанный со старой реализацией синка списка. Если не происходит и так дальше и висит загрузчик списка, создай баг на меня, пожалуйста

2023-08-28 14:01 UTC, Andoran90 commented on Tangem/App/Services/UserTokensManager/CommonUserTokensManager.swift
> +                guard !reorderingActions.isEmpty else {
```suggestion
                if reorderingActions.isEmpty {
```

2023-08-28 14:01 UTC, Andoran90 commented on Tangem/App/Services/UserTokensReordering/UserTokensReordering.swift
> +protocol UserTokensReordering {
`UserTokensOrganizable`?.. 🤔

2023-08-29 10:28 UTC, m3g0byt3 commented on Tangem/App/Services/TokenItemsRepository/TokenItemsRepository.swift
>      func remove(_ blockchainNetworks: [BlockchainNetwork])
Ты про `func remove(_ blockchainNetworks: [BlockchainNetwork])`?

Если да - то остается, метод используется и у него другая семантика, чем у `func remove(_ entries: [StoredUserTokenList.Entry])`.

Хотя очевидно что потребитель может удалить все токены в нужных сетях и через `func remove(_ entries: [StoredUserTokenList.Entry])`, передав туда все токены в нужных сетях. Но так можно было сделать и раньше, до рефакторинга  Это просто менее удобно

2023-08-29 11:07 UTC, tureck1y approved these changes, later dismissed

2023-08-29 11:10 UTC, Andoran90 approved these changes, later dismissed

2023-08-30 07:04 UTC, m3g0byt3 commented on Tangem/App/Services/TokenItemsRepository/TokenItemsRepository.swift
> -    var containsFile: Bool { get }
>Сейчас есть бажок связанный со старой реализацией синка списка. Если не происходит и так дальше и висит загрузчик списка, создай баг на меня, пожалуйста

да, наткнулся на этот баг
стрельнуло при добавлении второго воллета (т.е. вторая страница на пейджере)

2023-08-30 07:05 UTC, m3g0byt3 commented on Tangem/App/Services/UserTokensManager/CommonUserTokensManager.swift
> +                guard !reorderingActions.isEmpty else {
Поправил

2023-08-30 07:08 UTC, m3g0byt3 commented on Tangem/App/Services/UserTokensReordering/UserTokensReordering.swift
> +protocol UserTokensReordering {
Нет, `able` тут не подходит)

Вот тут мне кажется хорошо объяснено про нейминг протоколов:
https://dev.srdanstanic.com/swift-protocol-types-and-naming/#:~:text=If%20the%20implementer%20is%20doing,%2C%20e.g.%20Comparable%20%2C%20Codable%20%2C%20Cachable

1. If the implementer is something, name the protocol with a noun, e.g. Sequence, View, Repository
2. If the implementer is doing something, name the protocol with an adjective ending with ing, e.g. Loading, Generating, Coordinating
3. If something is done to the implementer, name the protocol with an adjective ending with able or ible, e.g. Comparable, Codable, Cachable

Статья в этом блоге это тоже самое, что эппл заявляет в стайлгайде:
```
If we look at the Swift API design guidelines, there are two bullets describing the naming of protocols.

Protocols that describe what something is should read as nouns (e.g. Collection).
Protocols that describe a capability should be named using the suffixes able, ible, or ing (e.g. Equatable, ProgressReporting).
```
но другими словами и с понятными примерами

2023-08-30 07:47 UTC, m3g0byt3 commented on Tangem/App/Services/TokenItemsRepository/StorageEntryConverter.swift
> +            .uniqueProperties(\.blockchainNetwork)
Нашел в ходе прогона кейсов, это не баг, а скорее нюанс формирования `StorageEntry` из плоского списка токенов.

Из-за другой логики доставания `blockchainNetwork` могло получаться такое:
https://gist.github.com/m3g0byt3/793c5937c2ef9da3c2caf2b688ee4b7a

Это могло влиять только на старый главный, на новом мы ориентируемся на порядок в плоском списке токенов.
Поправил логику конвертирования плоского списка чтобы она матчилась с тем, что сейчас в dev.

2023-08-30 10:14 UTC, Andoran90 approved these changes

2023-08-30 12:56 UTC, m3g0byt3 commented on Tangem/App/Services/TokenItemsRepository/StorageEntryConverter.swift
> +            .uniqueProperties(\.blockchainNetwork)
user-tokens для примера:

```
{
  "tokens": [{
    "symbol": "WBTC",
    "networkId": "ethereum",
    "id": "wrapped-bitcoin",
    "decimals": 8,
    "derivationPath": "m\/44'\/60'\/0'\/0\/0",
    "contractAddress": "0x2260fac5e5542a773aa44fbcfedf7c193bc2c599",
    "name": "Wrapped Bitcoin"
  }, {
    "decimals": 6,
    "id": "ripple",
    "networkId": "xrp",
    "symbol": "XRP",
    "name": "XRP Ledger",
    "derivationPath": "m\/44'\/144'\/0'\/0\/0"
  }, {
    "decimals": 18,
    "id": "ethereum",
    "networkId": "ethereum",
    "symbol": "ETH",
    "name": "Ethereum",
    "derivationPath": "m\/44'\/60'\/0'\/0\/0"
  }]
}
```

В dev будет сформирован список:
- XRP
- Ethereum
- Wrapped Bitcoin

в пуле до этой правки был бы сформирован список:
- Ethereum
- Wrapped Bitcoin
- XRP

2023-09-05 07:55 UTC, tureck1y approved these changes

2023-09-05 09:00 UTC, merged