IOS-4300 Add mainButtonIcon to OnboardingButtonsInfoProvider
tangem/tangem-app-ios-old pull request #1943
Opened 2023-08-22 13:39 UTC by Balashov152

- Обновил, что все кнопки которые ведут на сканирование карты с иконкой `Assets.tangemIcon`

2023-08-22 13:45 UTC, Andoran90 requested changes

2023-08-22 13:45 UTC, Andoran90 commented on Tangem/Modules/Onboarding/Wallet/WalletOnboardingStep.swift
> +        case .createWallet, .createWalletSelector, .scanPrimaryCard, .selectBackupCards:
по экранам с сид-фразой надо тоже пройти. Там кнопки внутри спрятаны из-за нестандартного положения. Они есть в `OnboardingSeedPhraseImportView` и в `OnboardingSeedPhraseUserValidationView`. В старом дизайне онбординга иконка была перед текстом, а не после него

2023-08-22 13:47 UTC, megakoko commented on Tangem/Modules/Onboarding/Wallet/WalletOnboardingViewModel.swift
> -            icon = .leading(Assets.plusMini)
plusMini выпилили?

2023-08-22 13:58 UTC, Balashov152 commented on Tangem/Modules/Onboarding/Wallet/WalletOnboardingViewModel.swift
> -            icon = .leading(Assets.plusMini)
Еще нужен 
![Screenshot 2023-08-22 at 16 57 55](https://github.com/tangem/tangem-app-ios/assets/25799680/449fd219-346b-4b6a-b3de-88e31bae2df2)

2023-08-22 13:58 UTC, tureck1y reviewed
Бегло просмотрел, можно еще по всем enum разных шагов пройтись и посмотреть не надо ли где еще добавить.

2023-08-22 13:59 UTC, megakoko commented on Tangem/Modules/Onboarding/Wallet/WalletOnboardingViewModel.swift
> -            icon = .leading(Assets.plusMini)
Я про онбординг. В онбординге больше не нужен?

2023-08-22 14:02 UTC, Balashov152 commented on Tangem/Modules/Onboarding/Wallet/WalletOnboardingStep.swift
> +        case .createWallet, .createWalletSelector, .scanPrimaryCard, .selectBackupCards:
Обновил там тоже, по дизайну теперь справа после текста

2023-08-22 14:35 UTC, megakoko commented
При онбординге воллета 2.0 показываются правильные картинки карты?

2023-08-23 07:16 UTC, Balashov152 commented on Tangem/Modules/Onboarding/Wallet/WalletOnboardingViewModel.swift
> -            icon = .leading(Assets.plusMini)
А, ну тут да, больше нет его нигде)

2023-08-23 07:16 UTC, Balashov152 commented
> Бегло просмотрел, можно еще по всем enum разных шагов пройтись и посмотреть не надо ли где еще добавить.

Ну я так и делал, и потом еще прошел онбординг по всем картам, кроме W2.0

2023-08-23 07:19 UTC, Balashov152 commented
> При онбординге воллета 2.0 показываются правильные картинки карты?

Ну тут задача не про это, но вообще картинки у нас сейчас загружаются по номеру карты, соответственно пока не могу проверить, надо номер по которому будут W2 идти

2023-08-23 07:21 UTC, megakoko commented
> > При онбординге воллета 2.0 показываются правильные картинки карты?
> 
> Ну тут задача не про это, но вообще картинки у нас сейчас загружаются по номеру карты, соответственно пока не могу проверить, надо номер по которому будут W2 идти

Проверишь? В fanstackview захардкожена картинка старая например

<img width="623" alt="Screenshot 2023-08-23 at 10 20 47" src="https://github.com/tangem/tangem-app-ios/assets/12209839/93e24d5f-5582-4660-aa14-822bd40ce9fd">

2023-08-23 07:24 UTC, Balashov152 commented
> > > При онбординге воллета 2.0 показываются правильные картинки карты?
> > 
> > 
> > Ну тут задача не про это, но вообще картинки у нас сейчас загружаются по номеру карты, соответственно пока не могу проверить, надо номер по которому будут W2 идти
> 
> Проверишь? В fanstackview захардкожена картинка старая например
> 
> <img alt="Screenshot 2023-08-23 at 10 20 47" width="623" src="https://user-images.githubusercontent.com/12209839/262587522-93e24d5f-5582-4660-aa14-822bd40ce9fd.png">

Обнаружил, что `FanStackPreviewModel` и `FanStackView` вообще не используются нигде, надо выпилить

2023-08-23 08:51 UTC, tureck1y approved these changes

2023-08-23 10:54 UTC, Andoran90 approved these changes

2023-08-23 11:36 UTC, merged