IOS-4506 stories add geo ip for stories screen
tangem/tangem-app-ios-old pull request #2081
Opened 2023-09-08 14:59 UTC by megakoko

Правила такие:
- как только на экране появляется изображение карты мы спрашиваем у сервиса регион
- изображение может появиться на странице с летающими воллетами, а может на первой странице в середине прогресса
- если "выбрали" какую-то картинку то ее впредь и будем показывать

Проверял вот так:
<img width="780" alt="Screenshot 2023-09-08 at 17 59 33" src="https://github.com/tangem/tangem-app-ios/assets/12209839/c4636dff-4bfe-4c09-976b-b42a11719c98">

2023-09-10 17:37 UTC, tureck1y commented on Tangem/Modules/Welcome/Stories/StoriesViewModel.swift
> +    @Published var useWallet2Image = true
предлагаю optional и избавиться от второй булки

2023-09-11 07:50 UTC, megakoko commented on Tangem/Modules/Welcome/Stories/StoriesViewModel.swift
> +    @Published var useWallet2Image = true
Неудобно, тогда получается страницы должны будут сами решать какую карту показать если там nil, логика в двух местах. А тут модель сама решает

2023-09-11 09:05 UTC, tureck1y commented on Tangem/Modules/Welcome/Stories/StoriesViewModel.swift
> +    @Published var useWallet2Image = true
Я к тому, что плохо иметь две переменных для решения одной задачи.

2023-09-11 10:57 UTC, m3g0byt3 commented on Tangem/Modules/Welcome/Stories/StoriesViewModel.swift
> +    @Published var useWallet2Image = true
Опциональный bool тоже противоречивая вещь) 
_(за исключением слоев где происходит сериализация/десериализация)_

2023-09-11 10:58 UTC, m3g0byt3 approved these changes, later dismissed

2023-09-11 10:58 UTC, m3g0byt3 commented on Tangem/Modules/Welcome/Stories/StoriesViewModel.swift
> +        switch tangemApiService.geoIpRegionCode {
Триггерить запрос региона надо, он уже триггернут (например в ините сервиса)?

2023-09-11 11:42 UTC, megakoko commented on Tangem/Modules/Welcome/Stories/StoriesViewModel.swift
> +    @Published var useWallet2Image = true
> Я к тому, что плохо иметь две переменных для решения одной задачи.

Согласен, но переносить логику и дублировать ее в двух вьюхах — хуже

2023-09-11 11:43 UTC, megakoko commented on Tangem/Modules/Welcome/Stories/StoriesViewModel.swift
> +        switch tangemApiService.geoIpRegionCode {
Да, при инициализации запрашиваем

2023-09-12 08:30 UTC, tureck1y requested changes
- нужно убрать копипасту с if из страниц BackupStoryPage и MeetTangemStoryPage. Передавай сразу картинку
- нужно упростить StoriesViewModel. По умолчанию одна картинка, после ответа от быка, она может поменяться. Если так трудно уместить все в одну переменную, то сделать хелпер

2023-09-12 08:30 UTC, tureck1y commented on Tangem/Modules/Welcome/Stories/StoriesViewModel.swift
> +    @Published var useWallet2Image = true
вы куда-то не туда пошли

2023-09-12 08:30 UTC, tureck1y commented on Tangem/Modules/Welcome/Stories/StoriesViewModel.swift
> +                    self?.didReachWalletImage()
а зачем из двух мест триггерить?

2023-09-12 11:05 UTC, megakoko commented on Tangem/Modules/Welcome/Stories/StoriesViewModel.swift
> +                    self?.didReachWalletImage()
В двух сторях картинка используется. В одной она посреди прогресса показывается, в другой при появлении

2023-09-12 11:06 UTC, megakoko commented
> нужно убрать копипасту с if из страниц BackupStoryPage и MeetTangemStoryPage. Передавай сразу картинку

Нет копипасты, там разные картинки

2023-09-12 11:20 UTC, tureck1y commented
> > нужно убрать копипасту с if из страниц BackupStoryPage и MeetTangemStoryPage. Передавай сразу картинку
> 
> 
> 
> Нет копипасты, там разные картинки
> 
> 

Не заметил, что картинки разные, но копипасту логики принятия решения это не отменяет. Вместо того, чтобы настроить вью модель в точке вызова, ты передаешь туда инструмент, на основе которого она решит внутри себя. Это размазало фичу по трем разным сущностям, вместо одной.

2023-09-12 11:22 UTC, tureck1y commented on Tangem/Modules/Welcome/Stories/StoriesViewModel.swift
> +                    self?.didReachWalletImage()
Мне кажется это оверинжениринг уже. Начало сторис показывать - решили какую картинку брать. Эти сложности излишни

2023-09-12 11:24 UTC, megakoko commented on Tangem/Modules/Welcome/Stories/StoriesViewModel.swift
> +                    self?.didReachWalletImage()
Тогда и логику не надо никакую, раз принимаем решение в начале самой первой страницы. Гео-ип все равно не загрузится к этому моменту.

2023-09-12 12:33 UTC, megakoko commented
Отрефакторил

2023-09-13 08:19 UTC, tureck1y commented on Tangem/Modules/Welcome/Stories/StoriesViewModel.swift
> +    @Published var handWithCardImage = Assets.Stories.handWithCard.image
вычисляемые проперти не работают?

2023-09-13 08:21 UTC, tureck1y commented on Tangem/Modules/Welcome/Stories/StoriesViewModel.swift
> +                    self?.didReachWalletImage()
ты это проверил, что не загрузится?

2023-09-13 10:51 UTC, megakoko commented on Tangem/Modules/Welcome/Stories/StoriesViewModel.swift
> +                    self?.didReachWalletImage()
Это первая страница сторисов, там нет никакого времени на загрузку

2023-09-13 11:01 UTC, tureck1y approved these changes
Ладно, давайте уже мержить. Не очень нравится, но это временно

2023-09-13 11:03 UTC, m3g0byt3 approved these changes

2023-09-13 11:07 UTC, merged