IOS-4495 the send button is active on old multi currency cards with balance
tangem/tangem-app-ios-old pull request #2087
Opened 2023-09-11 11:37 UTC by megakoko

Код был удален в рефакторинге:

https://github.com/tangem/tangem-app-ios/commit/af4c9c3e80214b9dffd229ee7758fc340b4074e0
https://github.com/tangem/tangem-app-ios/commit/7197e85548dc83e7b667ba1b72c0d1c3de6b79a8

2023-09-11 12:05 UTC, Andoran90 requested changes

2023-09-11 12:05 UTC, Andoran90 commented on Tangem/Modules/SingleTokenBase/SingleTokenBaseViewModel.swift
> +        guard card.canSend else {
надо компилировать перед пушем и созданием МР. Тут нет `card`

2023-09-11 12:07 UTC, Andoran90 commented on Tangem/Modules/SingleTokenBase/SingleTokenBaseViewModel.swift
> +        guard card.canSend else {
через `userWalletModel.config` можно проверить может ли карточка отправлять транзакции или нет

2023-09-11 12:08 UTC, megakoko commented on Tangem/Modules/SingleTokenBase/SingleTokenBaseViewModel.swift
> +        guard card.canSend else {
Точно, спасибо

2023-09-11 12:09 UTC, megakoko commented on Tangem/Modules/SingleTokenBase/SingleTokenBaseViewModel.swift
> +        guard card.canSend else {
Исправил

2023-09-11 12:32 UTC, Andoran90 approved these changes

2023-09-13 17:04 UTC, tureck1y approved these changes

2023-09-13 17:05 UTC, merged