Ios 4573 add token list welcome screen
tangem/tangem-app-ios-old pull request #2122
Opened 2023-09-18 11:31 UTC by skibinalexander

Что сделано:

- Добавил новый модуль WelcomeTokenList перенес логику из LegacyTokenList предварительно убрав не нужное
- Сделал роутинг на сторисах на новый модуль
- Вьюшки пока берутся Legacy предлагаю как сберем новый manage так и думать переехать, сейчас согласовывать пересогласовывать будет долго, а избавляться от legacy потихоньку нужно
- Пока draft нужно решить ок не ок, и нужно ли что-то еще в рамках этой задачи сделать

2023-09-18 11:31 UTC, skibinalexander commented on Tangem/Modules/LegacyTokenList/LegacyCoinItemViewModel.swift
> +    var isSelected: Binding<Bool>?
Опциональный потому что для не будет выбора

2023-09-18 11:32 UTC, skibinalexander commented on Tangem/Modules/Welcome/WelcomeCoordinator.swift
> -        if FeatureProvider.isAvailable(.manageTokens) {
Роутинг на новый модуль, как и говорили в прошлом МР, с переездом на новый модуль

2023-09-18 11:37 UTC, skibinalexander commented
![Simulator Screenshot - iPhone 14 - 2023-09-18 at 14 36 10](https://github.com/tangem/tangem-app-ios/assets/5384724/57fed3fc-187c-4498-976c-a7f9af71736b)
![Simulator Screenshot - iPhone 14 - 2023-09-18 at 14 36 22](https://github.com/tangem/tangem-app-ios/assets/5384724/8c702004-0856-4a20-9fe2-e211313c6ff0)
![Simulator Screenshot - iPhone 14 - 2023-09-18 at 14 36 02](https://github.com/tangem/tangem-app-ios/assets/5384724/afe5dbf6-c90d-48e7-b214-1dc4ec7d47fa)
![Simulator Screenshot - iPhone 14 - 2023-09-18 at 14 35 58](https://github.com/tangem/tangem-app-ios/assets/5384724/709e4c48-c9ac-434a-8ffe-5c2dc039f60a)

2023-09-18 13:02 UTC, Andoran90 commented on Tangem/Modules/LegacyTokenList/LegacyCoinItemViewModel.swift
> +    var isSelected: Binding<Bool>?
мне кажется правильнее будет вообще скопировать эту модель. В любом случае в старом `Manage Tokens` вряд ли будет обновляться уже логика ячеек, поэтому можно копирнуть и для `WelcomeTokenListItem` почистить все что не нужно. Сделать структуру, без подписок и какой-либо логики. Единственное что: будет ли работать копирование на `WelcomeTokenListItem`?

2023-09-18 13:02 UTC, Andoran90 commented on Tangem/Modules/Welcome/WelcomeTokenList/WelcomeTokenListCoordinator.swift
> +class WelcomeTokenListCoordinator: CoordinatorObject {
а зачем тут координатор? он же для этого экрана вообще не нужен, дальше никакой навигации нет, только скрытие этого экрана, а разворачивать систему координатора для этого лишнее абсолютно

2023-09-18 13:02 UTC, Andoran90 commented on Tangem/Modules/Welcome/WelcomeTokenList/WelcomeTokenListViewModel.swift
> +    @Published var isSaving: Bool = false
продукт копипасты? тут ничего не сохраняется вроде как

2023-09-18 13:02 UTC, Andoran90 commented on Tangem/Modules/Welcome/WelcomeTokenList/WelcomeTokenListViewModel.swift
> +    }
Нет никакой логики, можно просто перенести во вью

2023-09-18 13:02 UTC, Andoran90 commented on Tangem/Modules/Welcome/WelcomeTokenList/WelcomeTokenListViewModel.swift
> +    }
тоже непонятно зачем эта функция. Надо удалить всю копипасту, которая не используется, и оставить только конвертацию загруженных моделей во вью модели + поиск. Сейчас очень сильно отличаются `CoinItemViewModel` и не смысла подгонять новый экран под старые требования, надо сделать чистовой сразу вариант, чтобы при удалении старого `ManageTokens` можно было просто удалить всю папку, а не рефачить потом отдельно ещё и эти вью модели

2023-09-18 13:02 UTC, Andoran90 commented on Tangem/Modules/Welcome/WelcomeTokenList/WelcomeTokenListViewModel.swift
> +            )
как сделаешь `WelcomeTokenListItemViewModel` (или что-то подобное по названию) - тут сразу все станет красивей и чище

2023-09-18 13:02 UTC, Andoran90 commented on Tangem/Modules/Welcome/WelcomeTokenList/WelcomeTokenListViewModel.swift
> +        let supportedBlockchains = SupportedBlockchains.all
хм, а может нам тут надо показывать не `v1`, а для `v2`?.. `SupportedBlockchains` не покажет токены, которые поддерживает Wallet 2.0. Уточни, пожалуйста, у Леши, но думаю так будет правильно + глянь реализацию `SupportedBlockchains`

2023-09-18 13:44 UTC, skibinalexander commented on Tangem/Modules/Welcome/WelcomeTokenList/WelcomeTokenListCoordinator.swift
> +class WelcomeTokenListCoordinator: CoordinatorObject {
> а зачем тут координатор? он же для этого экрана вообще не нужен, дальше никакой навигации нет, только скрытие этого экрана, а разворачивать систему координатора для этого лишнее абсолютно

Окей, спасибо уберу

2023-09-18 13:45 UTC, skibinalexander commented on Tangem/Modules/Welcome/WelcomeTokenList/WelcomeTokenListViewModel.swift
> +            )
> как сделаешь `WelcomeTokenListItemViewModel` (или что-то подобное по названию) - тут сразу все станет красивей и чище

Да окей спасибо

2023-09-19 11:17 UTC, skibinalexander commented on Tangem/Modules/LegacyTokenList/LegacyCoinItemViewModel.swift
> +    var isSelected: Binding<Bool>?
> мне кажется правильнее будет вообще скопировать эту модель. В любом случае в старом `Manage Tokens` вряд ли будет обновляться уже логика ячеек, поэтому можно копирнуть и для `WelcomeTokenListItem` почистить все что не нужно. Сделать структуру, без подписок и какой-либо логики. Единственное что: будет ли работать копирование на `WelcomeTokenListItem`?

Скопирована, убрал не нужное

2023-09-19 11:33 UTC, skibinalexander commented
Убрал координатор

2023-09-19 15:16 UTC, tureck1y requested changes
опечатку надо поправить

2023-09-19 15:16 UTC, tureck1y commented on Tangem/Modules/Welcome/WelcomeCoordinatorView.swift
> +                        .navigationLinks(
по идее navigationLinks можно убрать

2023-09-19 15:16 UTC, tureck1y commented on Tangem/Modules/Welcome/WelcomeTokenList/WelcomTokenListSectionView.swift
> +//  WelcomTokenListSectionView.swift
WelcomE E пропущено везде

2023-09-19 15:16 UTC, tureck1y commented on Tangem/Modules/Welcome/WelcomeTokenList/WelcomeTokenListViewModel.swift
> +        let supportedBlockchains = SupportedBlockchains.all
Тут надо все показывать, all как раз для этого. v1/v2 тут роли не играет

2023-09-19 15:38 UTC, skibinalexander commented
> опечатку надо поправить

Да Конечно ....

2023-09-20 07:10 UTC, skibinalexander commented
@tureck1y Обновлено

2023-09-20 08:17 UTC, tureck1y approved these changes, later dismissed

2023-09-20 10:52 UTC, Balashov152 requested changes

2023-09-20 10:52 UTC, Balashov152 commented on Tangem/Modules/Welcome/WelcomeTokenList/WelcomeTokenListItemView.swift
> +    let arrowWidth: Double
```suggestion
private enum Constants { 
    static let arrowWidth: Double = 46
}
```
так лучше будет
И можно вниз перенести

2023-09-20 10:52 UTC, Balashov152 commented on Tangem/Modules/Welcome/WelcomeTokenList/WelcomeTokenListItemView.swift
> +    }
Тоже вниз под `body`

2023-09-20 10:52 UTC, Balashov152 commented on Tangem/Modules/Welcome/WelcomeTokenList/WelcomeTokenListItemView.swift
> +                        .font(.system(size: 14, weight: .semibold, design: .default))
Из наших шрифтов надо взять

2023-09-20 10:52 UTC, Balashov152 commented on Tangem/Modules/Welcome/WelcomeTokenList/WelcomeTokenListItemView.swift
> +                            .font(.system(size: 14))
Тут тоже

2023-09-20 10:52 UTC, Balashov152 commented on Tangem/Modules/Welcome/WelcomeTokenList/WelcomeTokenListItemViewModel.swift
> +    let id: UUID = .init()
Вроде как не надо для `class`

2023-09-20 10:52 UTC, Balashov152 commented on Tangem/Modules/Welcome/WelcomeTokenList/WelcomeTokenListItemViewModel.swift
> +extension WelcomeTokenListItemViewModel: Hashable {
А `hashValue` используется?

2023-09-20 10:52 UTC, Balashov152 commented on Tangem/Modules/Welcome/WelcomeTokenList/WelcomeTokenListSectionView.swift
> +    var subtitle: String = Localization.currencySubtitleExpanded
Только в одном месте используется, можно без переменной

2023-09-20 10:52 UTC, Balashov152 commented on Tangem/Modules/Welcome/WelcomeTokenList/WelcomeTokenListSectionView.swift
> +                    .font(.system(size: 17, weight: .medium, design: .default))
Тоже бы шрифт из наших подобрать

2023-09-20 10:52 UTC, Balashov152 commented on Tangem/Modules/Welcome/WelcomeTokenList/WelcomeTokenListSectionView.swift
> +                            Text(subtitle)
```suggestion
                            Text(Localization.currencySubtitleExpanded)
```

2023-09-20 10:52 UTC, Balashov152 commented on Tangem/Modules/Welcome/WelcomeTokenList/WelcomeTokenListView.swift
> +        }
```suggestion
        list
```

2023-09-20 10:52 UTC, Balashov152 commented on Tangem/Modules/Welcome/WelcomeTokenList/WelcomeTokenListView.swift
> +            .padding([.leading])
```suggestion
            .padding(.leading)
```

2023-09-20 10:52 UTC, Balashov152 commented on Tangem/Modules/Welcome/WelcomeTokenList/WelcomeTokenListView.swift
> +            .font(Font.system(size: 30, weight: .bold, design: .default))
тоже бы из `Fonts`

2023-09-20 12:00 UTC, Balashov152 commented
Это я все к тому, что бы потом не надо было переделывать, сразу по мелочам причесывать

2023-09-21 09:41 UTC, Balashov152 requested changes

2023-09-21 09:41 UTC, Balashov152 commented on Tangem/Modules/Welcome/WelcomeTokenList/WelcomeTokenListItemViewModel.swift
> +    var contractNameForegroundColor: Color { tokenItem.isBlockchain ? Colors.Text.accent : Color(name: "manage_tokens_contract_name") }
а тут на наши цвета можно будет?

2023-09-21 09:41 UTC, Balashov152 commented on Tangem/Modules/Welcome/WelcomeTokenList/WelcomeTokenListItemViewModel.swift
> +extension WelcomeTokenListItemViewModel: Hashable {
Можно удалить наверно, если не нужно

2023-09-21 09:41 UTC, Balashov152 commented on Tangem/Modules/Welcome/WelcomeTokenList/WelcomeTokenListSectionView.swift
> +                    .frame(maxWidth: .infinity, alignment: .leading)
Group не нужна вроде как

2023-09-21 09:41 UTC, Balashov152 commented on Tangem/Modules/Welcome/WelcomeTokenList/WelcomeTokenListSectionView.swift
> +                            .foregroundColor(Color(name: "manage_tokens_gray_text"))
а. ну на style и цвет наш, было бы прекрасно

2023-09-21 09:41 UTC, Balashov152 commented on Tangem/Modules/Welcome/WelcomeTokenList/WelcomeTokenListSectionView.swift
> +                                .foregroundColor(Color(name: "manage_tokens_gray_text"))
style(font:color:)

2023-09-21 09:41 UTC, Balashov152 commented on Tangem/Modules/Welcome/WelcomeTokenList/WelcomeTokenListSectionView.swift
> +            .padding(.vertical, 4)
цвят и шрифт )

2023-09-21 09:41 UTC, Balashov152 commented on Tangem/Modules/Welcome/WelcomeTokenList/WelcomeTokenListSectionViewModel.swift
> +    let id: UUID = .init()
Можно удалить, `Identifiable` для класса по ссылке работает

2023-09-21 09:41 UTC, Balashov152 commented on Tangem/Modules/Welcome/WelcomeTokenList/WelcomeTokenListSectionViewModel.swift
> +extension WelcomeTokenListSectionViewModel: Hashable {
И это вроде вроде как не нужно, так как id есть

2023-09-21 09:41 UTC, Balashov152 commented on Tangem/Modules/Welcome/WelcomeTokenList/WelcomeTokenListViewModel.swift
> +    let id: UUID = .init()
тут тоже можно убрать )

2023-09-21 10:55 UTC, Balashov152 commented on Tangem/Modules/Welcome/WelcomeTokenList/WelcomeTokenListItemView.swift
> +                        .foregroundColor(model.networkNameForegroundColor)
style ?)

2023-09-21 10:55 UTC, Balashov152 commented on Tangem/Modules/Welcome/WelcomeTokenList/WelcomeTokenListItemView.swift
> +                            .foregroundColor(model.contractNameForegroundColor)
style )

2023-09-21 10:55 UTC, Balashov152 commented on Tangem/Modules/Welcome/WelcomeTokenList/WelcomeTokenListSectionView.swift
> +                            .foregroundColor(.tangemGrayDark6)
Цвет)

2023-09-21 10:55 UTC, Balashov152 commented on Tangem/Modules/Welcome/WelcomeTokenList/WelcomeTokenListSectionView.swift
> +                                .foregroundColor(Colors.Text.tertiary)
style 
```suggestion
                                .style(font: Fonts.Regular.footnote, color: Colors.Text.tertiary)
```

2023-09-21 11:29 UTC, skibinalexander commented on Tangem/Modules/Welcome/WelcomeTokenList/WelcomeTokenListSectionView.swift
> +                            .foregroundColor(.tangemGrayDark6)
А ок, эти тоже

2023-09-21 11:30 UTC, skibinalexander commented on Tangem/Modules/Welcome/WelcomeTokenList/WelcomeTokenListSectionView.swift
> +                            .foregroundColor(.tangemGrayDark6)
Я просто смотрел те которые хардкором и не ассетом

2023-09-21 13:07 UTC, Balashov152 commented on Tangem/Modules/Welcome/WelcomeTokenList/WelcomeTokenListSectionView.swift
> +                            .foregroundColor(.tangemGrayDark6)
Все равно от старых надо избавляться)

2023-09-22 08:19 UTC, Balashov152 requested changes

2023-09-22 08:19 UTC, Balashov152 commented on Tangem/Modules/Welcome/WelcomeTokenList/WelcomeTokenListView.swift
> +            .style(Fonts.Bold.title1, color: .primary)
Цвет не наш, `Colors.Text.primary`  ?

2023-09-22 08:19 UTC, Balashov152 commented on Tangem/Modules/Welcome/WelcomeTokenList/WelcomeTokenListItemViewModel.swift
> +    var contractNameForegroundColor: Color { tokenItem.isBlockchain ? Colors.Text.accent : Color(name: "manage_tokens_contract_name") }
up)

2023-09-22 08:37 UTC, skibinalexander commented on Tangem/Modules/Welcome/WelcomeTokenList/WelcomeTokenListView.swift
> +            .style(Fonts.Bold.title1, color: .primary)
Да, спасибо, я посмотрел , что styler наш, думал уже Colors наш

2023-09-22 08:39 UTC, tureck1y commented
Что-то увязли в этой задаче. Экран со сторис тоже будет меняться, пусть пока работает на старом дизайне. Смысла в копипасте и тюнинге нет. Закрывайте и двигаемся дальше

2023-09-22 15:32 UTC, skibinalexander commented
> Что-то увязли в этой задаче. Экран со сторис тоже будет меняться, пусть пока работает на старом дизайне. Смысла в копипасте и тюнинге нет. Закрывайте и двигаемся дальше

Поменял все по комментам можно заливать

2023-09-22 15:34 UTC, Balashov152 approved these changes

2023-09-24 18:21 UTC, closed without merging