IOS-4540 manage tokens wallet selector
tangem/tangem-app-ios-old pull request #2123
Opened 2023-09-18 14:17 UTC by megakoko

2023-09-18 14:20 UTC, megakoko commented on Tangem/Modules/ManageTokens/WalletSelector/WalletSelectorItemViewModel.swift
> +    }
Копипаста из легаси кода который скоро выпилим, не стал выносить

2023-09-18 14:37 UTC, skibinalexander commented
Не очень понял, почему в ManageTokens -> WalletSelector живет

2023-09-18 15:13 UTC, megakoko commented
> Не очень понял, почему в ManageTokens -> WalletSelector живет

Вытащил выше

2023-09-19 08:41 UTC, skibinalexander approved these changes, later dismissed

2023-09-19 15:20 UTC, tureck1y approved these changes

2023-09-19 15:24 UTC, tureck1y commented on Tangem/Modules/WalletSelector/WalletSelectorCoordinator.swift
> +    required init(output: WalletSelectorCoordinatorOutput, dismissAction: @escaping Action<Void>, popToRootAction: @escaping Action<PopToRootOptions>) {
можно сделать проще, через dismissAction возвращать данные, я так с онбордингом делал

2023-09-19 15:26 UTC, tureck1y commented on Tangem/Modules/WalletSelector/WalletSelectorCoordinator.swift
> +    required init(output: WalletSelectorCoordinatorOutput, dismissAction: @escaping Action<Void>, popToRootAction: @escaping Action<PopToRootOptions>) {
Я в целом не уверен, нужен ли тут целый модуль. Глобальное правило, что модуль обязателен, когда есть навигация, а тут ее нет. Можно тот же аутпут передавать во вью модель и все

2023-09-19 15:31 UTC, tureck1y commented on Tangem/Modules/WalletSelector/WalletSelectorViewModel.swift
> +        coordinator.didSelectWallet(with: userWallet.userWalletId)
тут тоже неправильное использование координаторов

2023-09-19 15:31 UTC, tureck1y requested changes
Заметил ошибки с координатором

2023-09-21 12:26 UTC, megakoko commented
Да, я неправильно понял экран, он будет всегда через пуш добавляться. Удалил координатор, сделал коллбек через делегат.

2023-09-21 14:01 UTC, skibinalexander approved these changes

2023-09-21 14:01 UTC, skibinalexander commented on Tangem/Modules/WalletSelector/WalletSelectorViewModel.swift
> +                cardImageProvider: CardImageProvider()
Не лучше ли один инстанс?

2023-09-21 14:02 UTC, skibinalexander commented on Tangem/Modules/WalletSelector/WalletSelectorViewModel.swift
> +                cardImageProvider: CardImageProvider()
Или там в item сломается логика

2023-09-22 06:24 UTC, megakoko commented on Tangem/Modules/WalletSelector/WalletSelectorViewModel.swift
> +                cardImageProvider: CardImageProvider()
Не помню почему, но в шторке userwallet так же сделано

2023-09-22 09:06 UTC, tureck1y approved these changes

2023-09-22 11:00 UTC, merged