IOS-4564 custom token network selector screen
tangem/tangem-app-ios-old pull request #2137
Opened 2023-09-19 12:50 UTC by megakoko

2023-09-19 14:39 UTC, skibinalexander commented on Tangem/Modules/NetworkSelector/AddCustomTokenNetworkSelectorCoordinatorView.swift
> +                    .navigationLinks(links)
Не уверен, а это точно нужно?

2023-09-19 14:43 UTC, skibinalexander commented on Tangem/Modules/NetworkSelector/AddCustomTokenNetworkSelectorCoordinator.swift
> +    let output: AddCustomTokenNetworkSelectorCoordinatorOutput
Обычно оутпуты делают слабо опциональными, во избежания лишних захватов, ибо не известно что тебе сюда прилетит. 

И в целом это парттер делегат, который в iOS должен быть weak

2023-09-19 14:49 UTC, megakoko commented on Tangem/Modules/NetworkSelector/AddCustomTokenNetworkSelectorCoordinatorView.swift
> +                    .navigationLinks(links)
Нет, удалю

2023-09-19 14:49 UTC, megakoko commented on Tangem/Modules/NetworkSelector/AddCustomTokenNetworkSelectorCoordinator.swift
> +    let output: AddCustomTokenNetworkSelectorCoordinatorOutput
Точно, спасибо

2023-09-19 15:30 UTC, tureck1y requested changes

2023-09-19 15:30 UTC, tureck1y commented on Tangem/Modules/NetworkSelector/AddCustomTokenNetworkSelectorCoordinator.swift
> +        output: AddCustomTokenNetworkSelectorCoordinatorOutput,
Тут то же самое, вместо отдельного output можно и нужно возвращать данные через dismiss.

Но я бы отказался от модуля вообще, если не будет навигации внутри него самого

2023-09-19 15:30 UTC, tureck1y commented on Tangem/Modules/NetworkSelector/AddCustomTokenNetworkSelectorViewModel.swift
> +        coordinator.didSelectNetwork(blockchain: blockchain)
в координаторах только навигация

2023-09-21 13:09 UTC, megakoko commented
Удалил координаторы, сделал через делегат

2023-09-21 13:58 UTC, skibinalexander submitted a review, later dismissed

2023-09-21 17:12 UTC, skibinalexander approved these changes, later dismissed

2023-09-22 09:15 UTC, tureck1y commented on Tangem/Modules/AddCustomToken/AddCustomTokenNetworkSelector/AddCustomTokenNetworkSelectorViewModel.swift
> +    init(selectedBlockchain: Blockchain, blockchains: [Blockchain]) {
Давай сразу делать на id блокчейнов там где это возможно, например selectedBlockchain

2023-09-22 14:08 UTC, megakoko commented on Tangem/Modules/AddCustomToken/AddCustomTokenNetworkSelector/AddCustomTokenNetworkSelectorViewModel.swift
> +    init(selectedBlockchain: Blockchain, blockchains: [Blockchain]) {
Обновил

2023-09-26 10:39 UTC, tureck1y commented on Tangem/Modules/AddCustomToken/AddCustomTokenNetworkSelector/AddCustomTokenNetworkSelectorViewModel.swift
> +            itemViewModel.isSelected = (blockchain.networkId == itemViewModel.networkId)
@Balashov152 посмотри плиз, тут надо coinId использовать?

2023-09-26 10:50 UTC, Balashov152 commented on Tangem/Modules/AddCustomToken/AddCustomTokenNetworkSelector/AddCustomTokenNetworkSelectorViewModel.swift
> +            itemViewModel.isSelected = (blockchain.networkId == itemViewModel.networkId)
Ну вообще здесь все про сеть как я понял, по этому networkId норм
Да и во ViewModel `networkId` передаем. выглядит все ок

2023-09-26 16:46 UTC, tureck1y approved these changes

2023-09-26 17:04 UTC, skibinalexander approved these changes

2023-09-26 17:12 UTC, merged