IOS-4520: Custom token indicator
tangem/tangem-app-ios-old pull request #2139
Opened 2023-09-19 14:26 UTC by Andoran90

<img width="300" src="https://github.com/tangem/tangem-app-ios/assets/24321494/f5208ebd-d5e0-4eba-b3b5-883ce0aaa8e0">
<img width="300" src="https://github.com/tangem/tangem-app-ios/assets/24321494/3d78699a-62d0-4a45-93c5-554e1bd5573b">
<img width="300" src="https://github.com/tangem/tangem-app-ios/assets/24321494/bbcd226c-3ad7-41f0-94e7-de35421e7ee6">
<img width="300" src="https://github.com/tangem/tangem-app-ios/assets/24321494/92678024-009d-4afd-b1dc-99298105eee8">

2023-09-19 14:27 UTC, Andoran90 commented on Tangem/Preview Content/Mocks/ForComponents/OrganizeTokens/OrganizeTokensPreviewProvider.swift
> -                            in: .bitcoin(testnet: false)
для превью, можно не смотреть

2023-09-19 15:38 UTC, tureck1y requested changes

2023-09-19 15:38 UTC, tureck1y commented on Tangem/Modules/TokenSectionsAdapter/TokenSectionsAdapter.swift
> +        var isCustom: Bool {
давай лучше это перенесем в точку вызова. Мне кажется странным, что секция умеет говорить о кастомности

2023-09-20 05:09 UTC, Andoran90 commented on Tangem/Modules/TokenSectionsAdapter/TokenSectionsAdapter.swift
> +        var isCustom: Bool {
обновил

2023-09-20 05:41 UTC, m3g0byt3 approved these changes

2023-09-20 09:49 UTC, tureck1y approved these changes

2023-09-20 09:51 UTC, merged