Ios 4076 assembly manage tokens screen
tangem/tangem-app-ios-old pull request #2155
Opened 2023-09-21 17:51 UTC by skibinalexander

2023-09-25 11:24 UTC, Balashov152 requested changes

2023-09-25 11:24 UTC, Balashov152 commented on Tangem/Modules/ManageTokens/ManageTokensCoordinatorView.swift
> +                }
Если модель Coordinator, то и открываться должен CoordinatorView

2023-09-25 11:24 UTC, Balashov152 commented on Tangem/Modules/ManageTokens/ManageTokensItemViewModel.swift
> +    private func getPriceChangeState(by quote: TokenQuote) -> TokenPriceChangeView.State {
Давай может сюда опционал прокинем
и `if quote == nil { return .noData }`

Мало загрузиться не смогло, или еще что-то, не нашлось на сервере
будет бесконечный скелетон

2023-09-25 11:24 UTC, Balashov152 commented on Tangem/Modules/ManageTokens/ManageTokensView.swift
> +                Color.clear.frame(width: 10, height: 58, alignment: .center)
```suggestion
                Color.clear.frame(height: 58)
```
выглядит что так должно сработать

2023-09-25 11:24 UTC, Balashov152 commented on Tangem/Modules/ManageTokens/ManageTokensView.swift
> +    }
Не наш дизайн, вроде как `minimumScaleFactor` не используем. И шрифт не тот

2023-09-25 11:24 UTC, Balashov152 commented on Tangem/Modules/ManageTokens/ManageTokensViewModel.swift
> +        let supportedBlockchains = Set(userWalletRepository.models.map { $0.config.supportedBlockchains }.joined())
Тут прям для всех карт показываем?

2023-09-25 11:24 UTC, Balashov152 commented on Tangem/Modules/ManageTokens/ManageTokensViewModel.swift
> +                print(alreadyUpdateQuoteCoinIds.count)
```suggestion
```

2023-09-25 11:24 UTC, Balashov152 commented on Tangem/Modules/ManageTokens/ManageTokensViewModel.swift
> +                updateQuote(by: items.filter { !alreadyUpdateQuoteCoinIds.contains($0.id) }.map { $0.id })
```suggestion
                let itemsShouldLoadQuote = items.filter { !alreadyUpdateQuoteCoinIds.contains($0.id) }.map { $0.id }
                updateQuote(by: itemsShouldLoadQuote)
```
давай разделим, а то сложно читается, название можно другое

2023-09-25 11:24 UTC, Balashov152 commented on Tangem/Modules/ManageTokens/ManageTokensViewModel.swift
> +    }
Давай лучше отдельную подписку сделаем что бы она отменялась если новая пришла
```suggestion
        self.loadQuotesSubscribtion = tokenQuotesRepository
            .loadQuotes(coinIds: coinIds)
            .sink()
    }
```

2023-09-25 11:24 UTC, Balashov152 commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkSelectorCoordinatorView.swift
> +struct ManageTokensNetworkSelectorCoordinatorView: CoordinatorView {
Собственно вот эта `ManageTokensNetworkSelectorCoordinatorView`

2023-09-25 11:24 UTC, Balashov152 commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkSelectorViewModel.swift
> +            )
Вообще все в каких то абстракциях( 
```suggestion
        selectorItems = tokenItems.map { item in
            ManageTokensNetworkSelectorItemViewModel(
                isMain: item.isBlockchain,
                iconName: "",
                iconNameSelected: "",
                networkName: item.networkName,
                tokenTypeName: item.name,
                isSelected: .constant(false)
            )
```

2023-09-25 11:24 UTC, Balashov152 commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkSelectorViewModel.swift
> +            )
А вообще я так понимаю этот код не работает пока?

2023-09-25 11:24 UTC, Balashov152 commented on Tangem/Modules/Welcome/WelcomeCoordinator.swift
> +//        }
?

2023-09-25 13:23 UTC, skibinalexander commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkSelectorViewModel.swift
> +            )
> А вообще я так понимаю этот код не работает пока?

Ага в комменте написал, что это для заглушек, в другом МР на этот экран будет сборка

2023-09-25 13:23 UTC, skibinalexander commented on Tangem/Modules/Welcome/WelcomeCoordinator.swift
> +//        }
> ?

Задеклайнили этот МР, вычищу

2023-09-25 13:24 UTC, skibinalexander commented on Tangem/Modules/ManageTokens/ManageTokensViewModel.swift
> +        let supportedBlockchains = Set(userWalletRepository.models.map { $0.config.supportedBlockchains }.joined())
> Тут прям для всех карт показываем?

Ну я так понимаю да, ибо этот список по всем картам ....

2023-09-25 13:24 UTC, skibinalexander commented on Tangem/Modules/ManageTokens/ManageTokensViewModel.swift
> +        let supportedBlockchains = Set(userWalletRepository.models.map { $0.config.supportedBlockchains }.joined())
> > Тут прям для всех карт показываем?
> 
> Ну я так понимаю да, ибо этот список по всем картам ....

На ревью @tureck1y погляди пожалуйста

2023-09-25 13:25 UTC, skibinalexander commented on Tangem/Modules/ManageTokens/ManageTokensView.swift
> +    }
> Не наш дизайн, вроде как `minimumScaleFactor` не используем. И шрифт не тот

Ага , спасибо перепроверю это в меня

2023-09-25 13:25 UTC, skibinalexander commented on Tangem/Modules/ManageTokens/ManageTokensItemViewModel.swift
> +    private func getPriceChangeState(by quote: TokenQuote) -> TokenPriceChangeView.State {
> Давай может сюда опционал прокинем и `if quote == nil { return .noData }`
> 
> Мало загрузиться не смогло, или еще что-то, не нашлось на сервере будет бесконечный скелетон

Ага спасибо погляжу проверю

2023-09-25 13:26 UTC, skibinalexander commented on Tangem/Modules/ManageTokens/ManageTokensCoordinatorView.swift
> +                }
> Если модель Coordinator, то и открываться должен CoordinatorView

Ага , видимо по разному пробовал, спасибо

2023-09-26 14:50 UTC, skibinalexander commented on Tangem/Modules/ManageTokens/ManageTokensViewModel.swift
> +                updateQuote(by: items.filter { !alreadyUpdateQuoteCoinIds.contains($0.id) }.map { $0.id })
Добавил

2023-09-26 14:54 UTC, skibinalexander commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkSelectorCoordinatorView.swift
> +struct ManageTokensNetworkSelectorCoordinatorView: CoordinatorView {
> Собственно вот эта `ManageTokensNetworkSelectorCoordinatorView`

Обновил

2023-09-27 10:26 UTC, Balashov152 commented on Tangem/App/Models/Coins/CoinModel.swift
> +struct CoinModel: Identifiable {
Есть небольшие сомнения, правильно ли DTO с сервера использовать в ViewModel слое, правда и перекладывание выглядит лишним

2023-09-27 10:26 UTC, Balashov152 commented on Tangem/Modules/ManageTokens/ManageTokensItemViewModel.swift
> +    private func getPriceChangeState(by quote: TokenQuote) -> TokenPriceChangeView.State {
Как здесь ?

2023-09-27 10:26 UTC, Balashov152 commented on Tangem/Modules/ManageTokens/ManageTokensView.swift
> +                Color.clear.frame(height: 58)
А почему 58 ? 
Высота кнопки? Может тогда в `private Constants`

2023-09-27 10:26 UTC, Balashov152 commented on Tangem/Modules/ManageTokens/ManageTokensView.swift
> +            .padding([.leading])
NIT: 
```suggestion
            .padding(.leading)
```

2023-09-27 10:26 UTC, Balashov152 commented on Tangem/Modules/ManageTokens/ManageTokensViewModel.swift
> +    private var balanceFormatter = BalanceFormatter()
Я бы чуть переставил. Ну или хотя бы надо `var` у форматов убрать 
```suggestion
    private unowned let coordinator: ManageTokensRoutable

    private lazy var loader = setupListDataLoader()
    private let percentFormatter = PercentFormatter()
    private let balanceFormatter = BalanceFormatter()
    private var bag = Set<AnyCancellable>()
    private var loadQuotesSubscribtion: AnyCancellable?
```

2023-09-27 10:27 UTC, skibinalexander commented on Tangem/App/Models/Coins/CoinModel.swift
> +struct CoinModel: Identifiable {
Как я понял это модель , специально для этого экрана и была сделана

2023-09-27 10:28 UTC, skibinalexander commented on Tangem/Modules/ManageTokens/ManageTokensItemViewModel.swift
> +    private func getPriceChangeState(by quote: TokenQuote) -> TokenPriceChangeView.State {
Сейчас проверю добавлял ..

2023-09-27 12:23 UTC, Balashov152 commented on Tangem/App/Models/Coins/CoinModel.swift
> +struct CoinModel: Identifiable {
А, ну тогда ок)

2023-09-27 12:24 UTC, Balashov152 submitted a review, later dismissed

2023-10-02 19:46 UTC, tureck1y requested changes

2023-10-02 19:46 UTC, tureck1y commented on Tangem/Modules/ManageTokens/ManageTokensCoordinator.swift
> +extension ManageTokensCoordinator: LegacyAddCustomTokenRoutable {
Тут наверное не должно быть такого конформанса? Это же легаси

2023-10-02 19:46 UTC, tureck1y commented on Tangem/Modules/ManageTokens/ManageTokensRoutable.swift
> +    func openTokenSelectorModule(with tokenItems: [TokenItem])
Не надо добавлять Module, излишне.

2023-10-02 19:46 UTC, tureck1y commented on Tangem/App/Models/Coins/CoinModel.swift
> +struct CoinModel: Identifiable {
Тут не должно быть Identifiable. Это логика SUI, а не модели данных

2023-10-02 19:46 UTC, tureck1y commented on Tangem/Modules/ManageTokens/ManageTokensItemViewModel.swift
> +        didTapAction: @escaping (Action, CoinModel) -> Void
Было лучше, без зависимости на CoinModel и я не уверен, что надо прям всю модель в didTapAction кидать, можно же просто id

2023-10-02 19:46 UTC, tureck1y commented on Tangem/Modules/ManageTokens/ManageTokensItemViewModel.swift
> +            update(quote: quote)
может тут стоит проверку какую-то сделать, чтобы ничего не дергать, если значение не изменилось?

2023-10-02 19:46 UTC, tureck1y commented on Tangem/Modules/ManageTokens/ManageTokensViewModel.swift
> +        let supportedBlockchains = Set(userWalletRepository.models.map { $0.config.supportedBlockchains }.joined())
Вот тут пока я не понял
https://tangem.slack.com/archives/C055M6ECABY/p1696275180439179

2023-10-02 19:46 UTC, tureck1y commented on Tangem/Modules/ManageTokens/ManageTokensViewModel.swift
> +                let alreadyUpdateQuoteCoinIds = tokenViewModels.filter {
А зачем это здесь? Мы грузим список. Ячейка сама не может обновлять все что ей нужно? И пусть перерисовывает свою часть

2023-10-02 19:46 UTC, tureck1y commented on Tangem/Modules/ManageTokens/ManageTokensViewModel.swift
> +            coinModel.items.contains(where: { tokenItem in
Хочется как-то оптимизировать.
1) Этот поиск будет гоняться для всех ячеек, хотя это состояние не меняется (можно закешировать), пока пользователь не изменит список (тогда можно сбрасывать кеш).
2) Не совсем понятно зачем проверять по каждой сети, можно же искать по coinModel.id? 
Если у нас есть USDT, не имеет значения, в какой он сети, кнопка уже будет edit

2023-10-02 20:18 UTC, skibinalexander commented on Tangem/Modules/ManageTokens/ManageTokensItemViewModel.swift
> +        didTapAction: @escaping (Action, CoinModel) -> Void
> Было лучше, без зависимости на CoinModel и я не уверен, что надо прям всю модель в didTapAction кидать, можно же просто id

Сделал так что ячейка инициализируется моделью, и чтобы потом в рутовой вью модели не делать поиски, чтобы дальше переходить на экран свитчера токенов, с CoinModel работать более удобнее

2023-10-02 20:19 UTC, skibinalexander commented on Tangem/Modules/ManageTokens/ManageTokensItemViewModel.swift
> +            update(quote: quote)
> может тут стоит проверку какую-то сделать, чтобы ничего не дергать, если значение не изменилось?

окей добавлю проверку по state

2023-10-02 20:21 UTC, skibinalexander commented on Tangem/Modules/ManageTokens/ManageTokensViewModel.swift
> +                let alreadyUpdateQuoteCoinIds = tokenViewModels.filter {
> А зачем это здесь? Мы грузим список. Ячейка сама не может обновлять все что ей нужно? И пусть перерисовывает свою часть

Вернусь провірю можно ли это запаковать, были трудности кажется с этим, проверю

2023-10-02 20:22 UTC, skibinalexander commented on Tangem/Modules/ManageTokens/ManageTokensViewModel.swift
> +            coinModel.items.contains(where: { tokenItem in
> Хочется как-то оптимизировать.
> 
> 1. Этот поиск будет гоняться для всех ячеек, хотя это состояние не меняется (можно закешировать), пока пользователь не изменит список (тогда можно сбрасывать кеш).
> 2. Не совсем понятно зачем проверять по каждой сети, можно же искать по coinModel.id?
>    Если у нас есть USDT, не имеет значения, в какой он сети, кнопка уже будет edit

Тут Пересмотрю, может не совсем корректно проверяю конечно, но кажется должны смотреть как раз на состояние токене в сети

2023-10-03 07:03 UTC, skibinalexander commented on Tangem/Modules/ManageTokens/ManageTokensViewModel.swift
> +                let alreadyUpdateQuoteCoinIds = tokenViewModels.filter {
> А зачем это здесь? Мы грузим список. Ячейка сама не может обновлять все что ей нужно? И пусть перерисовывает свою часть

Вообщем проверки эти сделаны потому что:

ListDataLoader при пагинация выкидывает не 50 записей а всю пачку записей, и чем больше крутишь тем больше он выкидывает, поэтому нужна проверка, по каким ячейкам уже есть квоты чтобы не грузить лишнего .... Упаковать в ячейку наверное не получится

2023-10-03 07:26 UTC, skibinalexander commented
https://github.com/tangem/tangem-app-ios/pull/2155#discussion_r1343077608

@tureck1y  Может отдельной задачей поменяем как будет решение , чтобы не блочилось? Я могу таску добавить чтобы не потерялась?

2023-10-03 07:27 UTC, skibinalexander commented on Tangem/Modules/ManageTokens/ManageTokensViewModel.swift
> +                let alreadyUpdateQuoteCoinIds = tokenViewModels.filter {
@tureck1y Давай обсудим, я в целом остальные комменты поправил, надо с этим доразобраться

2023-10-03 07:36 UTC, skibinalexander commented on Tangem/Modules/ManageTokens/ManageTokensViewModel.swift
> +            coinModel.items.contains(where: { tokenItem in
Вынес в инициализатор изменения `fetchAlreadyExistTokenUserList`

2023-10-03 07:39 UTC, skibinalexander commented on Tangem/Modules/ManageTokens/ManageTokensItemViewModel.swift
> +            update(quote: quote)
Проверил, не нужна тут проверка, думаю ячейка должна обновляться если обновили coin quote, как и говорили, чтобы держать значение актуальным, а сюда прилетают только обновленные значения. Так что насколько вижу, здесь ок все работает

2023-10-05 11:36 UTC, tureck1y commented on Tangem/App/Models/Coins/CoinModel.swift
> +struct CoinModel: Identifiable {
Identifiable остался тут

2023-10-05 11:39 UTC, tureck1y requested changes

2023-10-05 11:39 UTC, tureck1y commented on Tangem/Modules/ManageTokens/ManageTokensViewModel.swift
> +    func updateAlreadyExistTokenUserList() {
Можно сделать private?

2023-10-05 11:39 UTC, tureck1y commented on Tangem/Modules/ManageTokens/ManageTokensViewModel.swift
> +        let isAlreadyExistToken = coinModel.items.contains(where: { tokenItem in
По coinId надо сравнивать

2023-10-05 12:17 UTC, skibinalexander commented on Tangem/Modules/ManageTokens/ManageTokensViewModel.swift
> +    func updateAlreadyExistTokenUserList() {
> Можно сделать private?

Ага пропустил ... добавил

2023-10-05 13:08 UTC, skibinalexander commented on Tangem/Modules/ManageTokens/ManageTokensViewModel.swift
> +        let isAlreadyExistToken = coinModel.items.contains(where: { tokenItem in
Обновил реализацию

2023-10-05 13:09 UTC, skibinalexander commented on Tangem/App/Models/Coins/CoinModel.swift
> +struct CoinModel: Identifiable {
> Identifiable остался тут

Ну вообще это же абстрактный протокол к моделям тоже применим, я его использую дальше по CoinModel.ID так выглядит безопасней

2023-10-05 13:10 UTC, skibinalexander commented on Tangem/App/Models/Coins/CoinModel.swift
> +struct CoinModel: Identifiable {
@tureck1y  Убрать?

2023-10-05 13:10 UTC, skibinalexander commented on Tangem/App/Models/Coins/CoinModel.swift
> +struct CoinModel: Identifiable {
К слову например UIDiffableDataSource работает на Identifiable

2023-10-05 13:42 UTC, tureck1y commented on Tangem/App/Models/Coins/CoinModel.swift
> +struct CoinModel: Identifiable {
У CoinModel уже же есть свой id.  Еня смущает добавление еще одного.

2023-10-05 14:30 UTC, skibinalexander commented on Tangem/App/Models/Coins/CoinModel.swift
> +struct CoinModel: Identifiable {
Да, конечно если режет глаз давай обновлю

2023-10-05 16:00 UTC, tureck1y submitted a review, later dismissed

2023-10-06 09:22 UTC, Balashov152 requested changes

2023-10-06 09:22 UTC, Balashov152 commented on Tangem/Modules/ManageTokens/ManageTokensItemViewModel.swift
> +        coin = coinModel
давай может одинаково назовем, либо все `coin` либо `coinModel`

2023-10-06 09:22 UTC, Balashov152 commented on Tangem/Modules/ManageTokens/ManageTokensItemViewModel.swift
> +    }
Что то сложный код получается

Давай проверку 
```
if priceValue.isEmpty || priceChangeState == .loading || priceChangeState == .noData {
             return itemQuote
         }
```
перенесем в `update(quote: TokenQuote)`
Еще бы я это назвал `updateView` а то сначала показалось, что будет запрос на обновление данный
а код
```
        guard let itemQuote = item else {
             return nil
         }
```
перенесем в `tokenQuotesRepository.pricesPublisher`

2023-10-06 09:22 UTC, Balashov152 commented on Tangem/Modules/ManageTokens/ManageTokensItemViewModel.swift
> +        .store(in: &bag)
```suggestion
        tokenQuotesRepository.pricesPublisher.sink { [weak self] itemQuote in
            if let findQuote = itemQuote[coin.id] {
                 self?.updateView(quote: findQuote)
            }
        }
        .store(in: &bag)
```

2023-10-06 09:22 UTC, Balashov152 commented on Tangem/Modules/ManageTokens/ManageTokensItemViewModel.swift
> +    }
```suggestion
    private func updateView(quote: TokenQuote) {
          guard priceValue.isEmpty || priceChangeState == .loading || priceChangeState == .noData else {
            return
        }
        
        priceChangeState = getPriceChangeState(by: quote)
        priceValue = balanceFormatter.formatFiatBalance(quote.price)
    }
```

2023-10-06 09:22 UTC, Balashov152 commented on Tangem/App/Services/TokenQuotesRepository/CommonTokenQuotesRepository.swift
> +    }
Давай это уберем, есть же `loadQuotes`

2023-10-06 09:22 UTC, Balashov152 commented on Tangem/Modules/ManageTokens/ManageTokensViewModel.swift
> +        tokenQuotesRepository.updateQuotes(coinIds: coinIds)
```suggestion
        tokenQuotesRepository.loadQuotes(coinIds: coinIds)
             .sink()
             .store(in: &bag)
```

2023-10-06 09:22 UTC, Balashov152 commented on Tangem/App/Services/TokenQuotesRepository/TokenQuotesRepository.swift
> +    func updateQuotes(coinIds: [String])
Тоже надо убрать

2023-10-06 09:22 UTC, Balashov152 commented on Tangem/Modules/ManageTokens/ManageTokensCoordinatorView.swift
> +            sheets
```suggestion
            NavigationView {
                if let model = coordinator.manageTokensViewModel {
                    ManageTokensView(viewModel: model)
                }
                
                sheets
            }
            .navigationViewStyle(.stack)
```
Мне кажется что так надо, хз, надо проверить
В `SwappingCoordinatorView` Андрей Ч сделал так

2023-10-06 09:22 UTC, Balashov152 commented on Tangem/Modules/ManageTokens/ManageTokensItemViewModel.swift
> +        self.priceHistory = nil
```suggestion
        self.priceHistory = priceHistory
```

2023-10-06 09:22 UTC, Balashov152 commented on Tangem/Preview Content/Fakes/FakeTokenQuotesRepository.swift
> +    }
Тут надо убрать тоже

2023-10-16 07:45 UTC, skibinalexander commented on Tangem/Modules/ManageTokens/ManageTokensCoordinatorView.swift
> +            sheets
> Мне кажется что так надо, хз, надо проверить В `SwappingCoordinatorView` Андрей Ч сделал так

Поправил

2023-10-16 07:45 UTC, skibinalexander commented on Tangem/Modules/ManageTokens/ManageTokensItemViewModel.swift
> +    }
> Suggested change
>         if priceValue.isEmpty || priceChangeState == .loading || priceChangeState == .noData {
>             return itemQuote
>         }
>         return nil
>     }
>     private func update(quote: TokenQuote) {
>         priceChangeState = getPriceChangeState(by: quote)
>         priceValue = balanceFormatter.formatFiatBalance(quote.price)
>     }
>     private func updateView(quote: TokenQuote) {
>           guard priceValue.isEmpty || priceChangeState == .loading || priceChangeState == .noData else {
>             return
>         }
>         
>         priceChangeState = getPriceChangeState(by: quote)
>         priceValue = balanceFormatter.formatFiatBalance(quote.price)
>     }

Сделал как предложил, в целом согласен путанно немного было

2023-10-16 08:05 UTC, Balashov152 approved these changes

2023-10-16 08:27 UTC, tureck1y approved these changes

2023-10-16 08:28 UTC, merged