IOS-4549 Reset wallet rework
tangem/tangem-app-ios-old pull request #2188
Opened 2023-09-28 12:50 UTC by Balashov152

https://github.com/tangem/tangem-app-ios/assets/25799680/4300d2f5-492f-4cf7-a2b6-f6f6dd4342ec

2023-09-28 12:50 UTC, ba1ashov commented on Tangem/Common/TangemSdk/CardInteractor.swift
> +        if tangemSdk.config.accessCodeRequestPolicy == .alwaysWithBiometrics {
Выглядит как костыль, не знаю, как лучше прокидывать)

2023-09-28 12:58 UTC, megakoko commented on Tangem/Common/TangemSdk/CardInteractor.swift
> +        }
А обратно...

2023-09-28 12:58 UTC, megakoko commented on Tangem/Modules/ResetToFactory/ResetToFactoryView.swift
> +    private struct SelectableIcon: View {
Может в extension положить?

2023-09-28 12:58 UTC, megakoko commented on Tangem/Modules/ResetToFactory/ResetToFactoryView.swift
> +                    .frame(width: 22, height: 22)
NP: имхо проще читать если будет if { circle() } else { circle() }

2023-09-28 12:58 UTC, megakoko commented on Tangem/Resources/Localizations/de.lproj/Localizable.strings
> +"reset_card_to_factory_condition_2" = "I realize that I can\’t use this card to recover my access code on the other cards.";
Надо обычную кавычку, без экранирования

2023-09-28 12:58 UTC, megakoko commented on Tangem/Resources/Localizations/zh-Hant.lproj/Localizable.strings
> +"reset_card_to_factory_condition_1" = "我了解執行此操作後，我將無法再訪問當前錢包";
А текстовка уже существующая? Надо удалить старый идентификатор

2023-09-28 17:52 UTC, tureck1y requested changes

2023-09-28 17:52 UTC, tureck1y commented on Tangem/Common/TangemSdk/CardInteractor.swift
> +        }
Достаточно просто добавить `var shouldAskForAccessCode: Bool { false }` в `ResetToFactorySettingsTask`.  Будет двойной прикладывание - то что надо)

2023-09-29 09:16 UTC, Balashov152 commented on Tangem/Resources/Localizations/zh-Hant.lproj/Localizable.strings
> +"reset_card_to_factory_condition_1" = "我了解執行此操作後，我將無法再訪問當前錢包";
Проверил, оказалось, что старого уже нет в проекте

2023-09-29 09:17 UTC, Balashov152 commented on Tangem/Resources/Localizations/de.lproj/Localizable.strings
> +"reset_card_to_factory_condition_2" = "I realize that I can\’t use this card to recover my access code on the other cards.";
✅

2023-09-29 09:17 UTC, Balashov152 commented on Tangem/Modules/ResetToFactory/ResetToFactoryView.swift
> +                    .frame(width: 22, height: 22)
согласен ✅

2023-09-29 09:17 UTC, Balashov152 commented on Tangem/Common/TangemSdk/CardInteractor.swift
> +        }
Добавил `var shouldAskForAccessCode: Bool { false }`

2023-09-29 09:18 UTC, Balashov152 commented on Tangem/Modules/ResetToFactory/ResetToFactoryView.swift
> +    private struct SelectableIcon: View {
Убрал в extension ✅

2023-09-29 09:35 UTC, tureck1y approved these changes

2023-09-29 11:08 UTC, megakoko approved these changes

2023-09-29 11:08 UTC, merged