IOS-4701: Manage tokens bottom scrollable sheet integration
tangem/tangem-app-ios-old pull request #2190
Opened 2023-09-28 23:50 UTC by m3g0byt3

[IOS-4701](https://tangem.atlassian.net/browse/IOS-4701)

2023-10-05 14:52 UTC, m3g0byt3 commented on Tangem/Common/Extensions/UIKit/UIPanGestureRecognizer+Value.swift
> +extension UIPanGestureRecognizer {
Практически без изменений выехало в отдельный файлик из удаленного Tangem/UIComponents/ScrollViewRepresentable/ScrollViewRepresentable.swift

2023-10-05 15:33 UTC, m3g0byt3 commented on Tangem/Common/UI/DragGesturePassthroughView.swift
> +struct DragGesturePassthroughView: UIViewRepresentable {
Пробовал разные варианты как заставить работать `SwiftUI.ScrollView` (потому что с `UIScrollView` не работает ленивость в lazy стеках) - сработал такой вариант, работает на удивление отлично

2023-10-05 15:35 UTC, m3g0byt3 commented on Tangem/Common/UI/Modifiers/IOS15AndBelowScrollDisabledCompatModifier.swift
> +struct IOS15AndBelowScrollDisabledCompatModifier: ViewModifier {
Используется только на iOS 15 и ниже, где точно не будет уже никаких изменений со стороны эплл и нет опасности, что сломается

2023-10-05 15:39 UTC, m3g0byt3 commented on Tangem/Modules/App/AppCoordinatorView.swift
> +        .if(isMainScreenBottomSheetEnabled) { view in
Как и написано в комменте ниже, к сожалению нельзя сделать conditional modifier по условию `coordinator.manageTokensViewModel != nil` - т.к. это приведет к изменению identity этой вьюхи и соотв к сбросу ее внутреннего стейта

2023-10-05 15:42 UTC, m3g0byt3 commented on Tangem/Modules/Main/MainCardPageBuilder/MainUserWalletPageBuilder.swift
>          }
Заодно тут фиксится отсутствие отступов от низа экрана если и anageTokensViewModel == nil и footerViewModel == nil (за счет EmptyMainFooterView())

2023-10-05 15:44 UTC, m3g0byt3 commented on Tangem/Modules/Main/MainViewModel.swift
> +    private func updateManageTokensSheetViewModel(forPageAtIndex newIndex: Int) {
Метод позволяет обновлять контент в шторке (т.к. согласно последним обсуждениям в этой шторке может быть самый разный контент, не только manage tokens)

2023-10-05 15:48 UTC, m3g0byt3 commented on Tangem/Modules/ManageTokensBottomSheet/ManageTokensBottomSheetDisplayable.swift
> +protocol ManageTokensBottomSheetDisplayable: AnyObject {
ManageTokensBottomSheetDisplayable, ManageTokensBottomSheetIntermediateDisplayable и экстеншн для CoordinatorObject позволяет прокидывать VM от координатора, который отвечает за главную страницу, до AppCoordinator - где и отображается шторка

2023-10-05 15:50 UTC, m3g0byt3 commented on Tangem/Modules/App/AppCoordinatorView.swift
> +            view.bottomScrollableSheet(
Применять модификатор надо именно на `AppCoordinatorView`, т.к. это позволяет скейлить source view и подкладывать под него черную подложку

2023-10-05 15:52 UTC, m3g0byt3 commented on Tangem/UIComponents/BottomScrollableSheet/BottomScrollableSheet.swift
> +        ScrollView(.vertical) {
Перешел на `SwiftUI.ScrollView` тк с `UIScrollView` не работает ленивость lazy стеков и это приводит к лагам даже на производительном девайсе

2023-10-05 16:02 UTC, m3g0byt3 commented on Tangem/UIComponents/BottomScrollableSheet/BottomScrollableSheet.swift
> +        .overlay(headerGestureOverlayView(proxy: proxy), alignment: .top) // Mustn't be hidden (by the 'isHidden' flag)
Тут достаточно сложная логика с коллбеками на анимацию и прозрачными оверлеями с жестами, т.к. нужно было выполнить несколько условий.
1. К шторке должны быть применены анимации переключения страницы на главном (opacity + offset) - т.е. шторка должна лежать в скроллвью конкретной страницы на главном экране
2. При раскрытии шторки необходимо скейлить контент под ней и подкладывать под него черную подложку (как делает нативный боттом шит) - то есть шторка должна быть применена к `AppCoordinatorView`

В итоге это достигается тем, что в скроллвью конкретной страницы на главном экране кладется dummy placeholder, который выглядит как торчащий хидер шторки. А настоящая шторка полностью скрыта и становится видимой только если прогресс анимации (программного разворачивания по тапу по текстфилду в хидере шторки или разворачивание drag жестом) становится больше 0.

Чтобы жесты тапа и drag работали при скрытой шторке - они добавляются на прозрачный `headerGestureOverlayView`

2023-10-05 16:10 UTC, m3g0byt3 commented on Tangem/UIComponents/BottomScrollableSheet/BottomScrollableSheet.swift
> +        .overlay(headerGestureOverlayView(proxy: proxy), alignment: .top) // Mustn't be hidden (by the 'isHidden' flag)
Первый скрин это dummy placeholder, настоящая шторка скрыта (но ее жесты работают т.к. лежат на `headerGestureOverlayView`)
<img width="300" src="https://github.com/tangem/tangem-app-ios/assets/21194149/c6dff6b4-2cfa-4578-828d-e1a3e8bb4b8f">

Прогресс анимации разворачивания шторки > 0, настоящая шторка становится видимой
<img width="300" src="https://github.com/tangem/tangem-app-ios/assets/21194149/6310e825-5847-45b1-b465-e83ae72dbbc4">

2023-10-05 16:11 UTC, m3g0byt3 commented on Tangem/UIComponents/BottomScrollableSheet/BottomScrollableSheetShadowView.swift
> +        .offset(y: -39.0)
макеты ¯\_(ツ)_/¯

2023-10-05 16:12 UTC, m3g0byt3 commented on Tangem/UIComponents/BottomScrollableSheet/BottomScrollableSheetStateObject.swift
> -    private func bindKeyboard() {
Такой вариант очевидно не подходит, т.к. разворачивание шторки триггерит любой инпут

2023-10-05 16:25 UTC, m3g0byt3 commented on Tangem/UIComponents/BottomScrollableSheet/BottomScrollableSheet.swift
> +    func onAnimationStarted<Value>(
Будет дергаться многократно, на каждое изменение прогресса анимации, если она больше нуля 
Это ок в том месте, где я его использую - потому что там есть доп проверка

Но из-за этого не хочу выносить этот экстеншн в common, т.к. такое поведение может быть неожиданным

2023-10-10 08:59 UTC, ba1ashov commented on Tangem/Modules/CardSettings/CardSettingsCoordinator.swift
> +    weak var nextManageTokensBottomSheetDisplayable: ManageTokensBottomSheetDisplayable?
Может через EnvironmentObject сделать?
что бы прикидывать так много не нужно было

2023-10-10 08:59 UTC, ba1ashov commented on Tangem/UIComponents/BottomScrollableSheet/BottomScrollableSheetStateObject.swift
> +            return false
```suggestion
    self == .bottom
```
Так может?

2023-10-10 08:59 UTC, ba1ashov commented on Tangem/UIComponents/BottomScrollableSheet/BottomScrollableSheetModifier.swift
> +                .scaleEffect(stateObject.scale, anchor: .bottom)
Если кстати открыть прозрачный sheet, то scaleEffect у него идет от центра как будто
нижняя View со всех углов уходит назад. Это не так важно, так как не видно, но все же

2023-10-10 14:13 UTC, tureck1y requested changes
1) Шторка - абстрактный контейнер (как sheet), нужно учесть в именовании ее компонентов и пропекшей в координаторах.
2) Шторка является самостоятельным слоем приложения. Нужно постараться сделать максимально похоже на стандартный механизм (например, sheet, в котором лежит координатор определенного модуля). Подумать где это должно лежать в единственном экземпляре и как с этим слоем взаимодейстовать.
3) Очень ненадежно выглядит то, что нужно повсюду пропихивать доп свойство для корректной работы шторки, нужно поискать другое решение, чтобы работало автоматически, по возможности и чтобы остальные координаторы не получали лишних знаний. Можем вместе побрейинштормить

2023-10-10 14:13 UTC, tureck1y commented on Tangem/Modules/App/AppCoordinator.swift
> +    @Published private(set) var manageTokensViewModel: ManageTokensBottomSheetViewModel?
Шторка будет развиваться, как отдельный модуль. Релизиться с маркетпрайсом вместе. Нужно абстрактное название и наверное у нее должен быть свой координатор? Это точно не будет вьюмодель менеджтокенс

2023-10-10 14:13 UTC, tureck1y commented on Tangem/Modules/CardSettings/CardSettingsCoordinator.swift
> +    weak var nextManageTokensBottomSheetDisplayable: ManageTokensBottomSheetDisplayable?
а для чего это вообще нужно?

2023-10-10 14:13 UTC, tureck1y commented on Tangem/Modules/App/AppCoordinatorView.swift
> +        .if(isMainScreenBottomSheetEnabled) { view in
А почему на AuthCoordinatorView? Если биометрии нет, то мы идем в WelcomCoordinatorView

2023-10-10 14:13 UTC, tureck1y commented on Tangem/Modules/CardSettings/CardSettingsCoordinator.swift
> +    weak var nextManageTokensBottomSheetDisplayable: ManageTokensBottomSheetDisplayable?
Надо обсудить, хочется избежать прокидывания везде, если получится

2023-10-10 14:13 UTC, tureck1y commented on Tangem/Modules/Main/LockedWalletMainContent/LockedWalletMainContentViewModel.swift
> +    private(set) lazy var manageTokensViewModel: ManageTokensBottomSheetViewModel? = {
Шторка должна существовать всегда

2023-10-31 13:14 UTC, m3g0byt3 commented
>Очень ненадежно выглядит то, что нужно повсюду пропихивать доп свойство для корректной работы шторки, нужно поискать другое решение, чтобы работало автоматически, по возможности и чтобы остальные координаторы не получали лишних знаний. Можем вместе побрейинштормить

Это сделано потому что надо соблюсти два требования:
1. Bottom sheet должен презентится на рутовой вьюхе, чтобы был эффект скейла на черном фоне всей вьюхи, включая `NavigatinView`. 
Рутовый `NavigatinView` находится в `AppCoordinatorView` - поэтому боттом шит презентится оттуда.
Если презентить боттом шит с мейна (`MainView`/`MainCoordinatorView`) - то будет вот так (навигейшн остается неизменным, без скейла):
<img src="https://github.com/tangem/tangem-app-ios/assets/21194149/7543b9de-bbc1-46f8-ad83-2afeeee6bf9a" width=300px>

2. Bottom sheet должен быть показан conditionally только когда показан мейн, иначе он будет показан всегда, в том числе поверх сплеш-скрина с кнопками **face id** и **scan card** (не знаю как он называется):
<img src="https://github.com/tangem/tangem-app-ios/assets/21194149/90cd3f06-e5e2-4f44-b5b8-17bafb77c637" width=300px>

--------------------

То есть для выполнения обоих условий мне надо прокинуть VM для боттом шита (ну или просто флаг `показать/скрыть боттом шит`, не суть важно, главное триггернуть показ боттом шита) по следующей цепочке:
`MainViewModel` -> `MainCoordinator` -> `AuthCoordinator` -> `AppCoordinator`
где `MainViewModel` кидает флаг когда происходит `onViewAppear` у main view, а в `AppCoordinator` собственно триггерт в `AppCoordinatorView` показ боттом шита

--------------------

Но это только базовый кейс, кроме него `MainCoordinator` создается еще в `WelcomeCoordinator` `OnboardingCoordinator` - а значит оттуда тоже можно стартовать main flow.

То есть получается есть еще как минимум две цепочки, через которые наверх мне надо прокидывать события из `MainView`:
`MainViewModel` -> `WelcomeCoordinator` -> _произвольное количество координаторов_ -> `AppCoordinator`
`MainViewModel` -> `OnboardingCoordinator` -> _произвольное количество координаторов_ -> `AppCoordinator`

Для этого и был придуман механизм прокидывания вверх по цепочке координаторов в этом пуле.
В качестве альтернативы я могу предложить:
1. Использовать swiftui preferences и кидать флаг/VM через них вверх по иерархии вьюх
2. Заинжектить какой-нибудь управляющий объект через swiftui environments и использовать его для передачи флага/VM
3. Кидать нотификации
4. Переписать на UIKit и применять скейл к root view controller

2023-11-03 09:23 UTC, m3g0byt3 commented on Tangem/Modules/App/AppCoordinatorView.swift
> +        .if(isMainScreenBottomSheetEnabled) { view in
Применяется на app coord view, не на auth coord view
Ну и обсудили причины этого на созвоне

2023-11-03 09:25 UTC, m3g0byt3 commented on Tangem/Modules/CardSettings/CardSettingsCoordinator.swift
> +    weak var nextManageTokensBottomSheetDisplayable: ManageTokensBottomSheetDisplayable?
Обсудили на созвоне что это и зачем надо
Передел на `@Injected` (по сути синглтон) вместо прокидывания по нав стеку вверх

2023-11-03 09:25 UTC, m3g0byt3 commented on Tangem/UIComponents/BottomScrollableSheet/BottomScrollableSheetStateObject.swift
> +            return false
Поправил

2023-11-03 09:27 UTC, m3g0byt3 commented on Tangem/UIComponents/BottomScrollableSheet/BottomScrollableSheetModifier.swift
> +                .scaleEffect(stateObject.scale, anchor: .bottom)
В таком случае получается очень странный скейл, а кажется что нативный шит все-таки скейлится с bottom anchor. Я попробовал поменять - мне не понравилось, как выглядит

В любом случае в описании к пулу я писал, что надо посмотреть подробнее - т.к. сейчас как-то странно системой применяется scaleEffect к навбару (как будто навбар сам еще имеет какую-то transform)

2023-11-03 09:27 UTC, m3g0byt3 commented on Tangem/Modules/Main/LockedWalletMainContent/LockedWalletMainContentViewModel.swift
> +    private(set) lazy var manageTokensViewModel: ManageTokensBottomSheetViewModel? = {
Теперь существует всегда (но ее visibility меняется)

2023-11-03 09:34 UTC, m3g0byt3 commented
> * Шторка - абстрактный контейнер (как sheet), нужно учесть в именовании ее компонентов и пропекшей в координаторах.

Поправил нейминг
Сейчас все файлы в этом пуле разделяются на две группы:
1. Абстрактный UI component - его файлы лежат в `Tangem/UIComponents/BottomScrollableSheet/`
2. Специфичные вьюхи и VM именно для шторки главного экрана - лежат в `Tangem/Modules/Main/MainBottomSheet/` и `Tangem/Modules/Main/MainFooterView/MainBottomSheet/`. Эти сущности временные/не финальные, для тестов интеграции и именно их будет модифицировать или же заменять своими @skibinalexander в своих задачах

> * Шторка является самостоятельным слоем приложения. Нужно постараться сделать максимально похоже на стандартный механизм (например, sheet, в котором лежит координатор определенного модуля). Подумать где это должно лежать в единственном экземпляре и как с этим слоем взаимодейстовать.

- Сейчас реализовано как раз как стандартный механизм (через экстеншн к вьюхе)
- Координатор и модуль - это явно не то, что должно быть в компоненте шторки (то что сделано в этом пуле). Это как раз то, что делает @skibinalexander в своих задачах


> * Очень ненадежно выглядит то, что нужно повсюду пропихивать доп свойство для корректной работы шторки, нужно поискать другое решение, чтобы работало автоматически, по возможности и чтобы остальные координаторы не получали лишних знаний. Можем вместе побрейинштормить

Обсудили это на звонке, поменял как описано тут https://github.com/tangem/tangem-app-ios/pull/2190#discussion_r1381383083

2023-11-03 09:35 UTC, m3g0byt3 commented on Tangem/Modules/Main/MainCardPageBuilder/MainUserWalletPageBuilder.swift
> +            EmptyMainFooterView()
Показываем шторку на всех типах карт

2023-11-03 09:38 UTC, m3g0byt3 commented on Tangem/UIComponents/BottomScrollableSheet/BottomScrollableSheetModifier.swift
> +        allowsHitTesting: Bool = true,
Кастомизабельные параметры, которые нужны для реализации шторки на главном экране (где есть нюанс в виде футера, который встроен на карточку главного), но в общем случае для дженерик компонента должны иметь такие значения

2023-11-03 09:42 UTC, m3g0byt3 commented on Tangem/Modules/Main/SingleWalletMainContent/SingleWalletMainContentView.swift
> -            .padding(.bottom, 40)
Заодно (т.к. для синглволлетов тоже надо показывать шторку) поправил вот этот баг из задачи https://tangem.atlassian.net/browse/IOS-4659

В задаче есть коммент, что будет исправлено при речеке всех отступов и размеров в приложении, но видимо забыли.

В итоге так выглядит с/без шторки на челочном девайсе:
<img src="https://github.com/tangem/tangem-app-ios/assets/21194149/06d25e74-cceb-42ff-8958-0a5a127a1c9c" width=350px>
<img src="https://github.com/tangem/tangem-app-ios/assets/21194149/d9ca24ca-1b28-4666-b177-64379e80cf61" width=350px>

И на безчелочном:
<img src="https://github.com/tangem/tangem-app-ios/assets/21194149/3cfcc35e-ec49-4542-80d0-0a7a2a662a55" width=350px>
<img src="https://github.com/tangem/tangem-app-ios/assets/21194149/3dfd9551-c292-4031-9dab-b14ccc733baa" width=350px>

2023-11-08 08:16 UTC, skibinalexander submitted a review, later dismissed

2023-11-08 19:44 UTC, tureck1y reviewed
Единственный минус этого пулла - много косметических изменений. Приходится всматриваться, поменялась ли логика. Понимаю, что много мест, которые хочется подчистить и сложно пройти мимо, но лучше все же отдельно такое, по возможности)

2023-11-08 19:44 UTC, tureck1y commented on Tangem/Modules/App/AppCoordinator.swift
> +        let mainBottomSheetViewModel = MainBottomSheetViewModel()
А не хочешь сделать свойством всего класса, каким-нибудь _mainBottomSheetViewModel?
Тогда и коммент наверно не понадобится

2023-11-09 08:41 UTC, m3g0byt3 commented on Tangem/Modules/App/AppCoordinator.swift
> +        let mainBottomSheetViewModel = MainBottomSheetViewModel()
Можно, но на `mainBottomSheetViewModel` уже висит property wrapper, то есть `_mainBottomSheetViewModel` уже занята и сгенерена компилятором.

Если не критичен нейминг `__mainBottomSheetViewModel` - могу добавить так 
ну или же `mainBottomSheetViewModelStorage`

Но честно говоря без комента оба этих названия для свойства класса ни о чем не говорят, мне по крайней мере.
Почему `__`?  Что за `*Storage` и зачем он?

2023-11-09 09:20 UTC, tureck1y commented on Tangem/Modules/App/AppCoordinator.swift
> +        let mainBottomSheetViewModel = MainBottomSheetViewModel()
Да тут дело даже не в названии, а чтобы был явный ретейн

2023-11-09 13:20 UTC, m3g0byt3 commented on Tangem/Modules/App/AppCoordinator.swift
> +        let mainBottomSheetViewModel = MainBottomSheetViewModel()
Поместил эту VM в проперть

2023-11-09 13:48 UTC, tureck1y approved these changes

2023-11-09 15:30 UTC, Balashov152 approved these changes

2023-11-09 15:30 UTC, merged