IOS-4658 custom tokens icon
tangem/tangem-app-ios-old pull request #2192
Opened 2023-09-29 07:29 UTC by megakoko

2023-10-02 06:52 UTC, Andoran90 requested changes

2023-10-02 06:52 UTC, Andoran90 commented on Tangem/Common/Extensions/Token+.swift
>              // This code will be simplified after refactoring token storage on card and on phone
эх какие наивные мечты))

2023-10-02 06:52 UTC, Andoran90 commented on Tangem/Common/UI/IconView/IconView.swift
> +    private let customTokenColor: Color?
плохое название, `IconView` не привязан к токенам, это просто вьюха, которая отображает загружаемую иконку. и тут внезапно появляется логика с цветом кастомного токена.
Помимо прочего, почему-то по наличию или же отсутствию цвета должно определяться что будет показываться загружаемая иконка или же значок кастомного токена.
Эта логика не тут должна быть

2023-10-02 06:52 UTC, Andoran90 commented on Tangem/Common/UI/SwappingTokenIconView/SwappingTokenIconView.swift
> -            IconView(url: imageURL, size: imageSize)
и вот тут это видно. Свапать кастомные токены, которые мы не поддерживаем, нельзя, но почему-то вьюха должна знать об этом

2023-10-02 06:52 UTC, Andoran90 commented on Tangem/UIComponents/TokenIcon/TokenIcon.swift
> -        IconView(url: imageURL, size: size, forceKingfisher: true)
вот тут должна быть логика определения кастомную иконку показывать или нет. Тут уже даже есть поле `isCustom`

2023-10-02 06:52 UTC, Andoran90 commented on Tangem/Modules/LegacyTokenList/LegacyCoinView.swift
> +                IconView(url: model.imageURL, customTokenColor: nil, size: CGSize(width: iconWidth, height: iconWidth), forceKingfisher: true)
тут сейчас всюду проблема, что у нас появилось слишком много разных вьюх, которые рисуют иконки. Должно быть 2 вьюхи:
1. Загружает картинки по `url`, не важно через что.
2. Отображает иконку токена. Если это кастомный токен - то специальную иконку, если стандартный - тогда грузит его изображение.

Сейчас количество хаоса увеличивается. Думаю надо создать задачу на рефакторинг и влить его перед фиксом бага или же сразу после фикса бага сделать рефакторинг всего этого, если мы хотим отдать этот функционал в ближайшем срезе. @tureck1y что скажешь?

2023-10-02 06:58 UTC, megakoko commented on Tangem/Modules/LegacyTokenList/LegacyCoinView.swift
> +                IconView(url: model.imageURL, customTokenColor: nil, size: CGSize(width: iconWidth, height: iconWidth), forceKingfisher: true)
Я специально все в одну вьюху запихнул, потому что если дробить на две то будем забывать про кастомные токены. Если потом объединить IconView и CustomTokenIconView, то получится то же самое

2023-10-02 06:59 UTC, megakoko commented on Tangem/Modules/LegacyTokenList/LegacyCoinView.swift
> +                IconView(url: model.imageURL, customTokenColor: nil, size: CGSize(width: iconWidth, height: iconWidth), forceKingfisher: true)
Ну или рефакторить все на использование TokenIconInfo

2023-10-02 20:12 UTC, tureck1y requested changes

2023-10-02 20:12 UTC, tureck1y commented on Tangem/Common/UI/TokenIconView/TokenIconViewModel.swift
> +        case token(_ blockchainIconName: String, customTokenColor: Color?)
да надо было просто еще один кейс тут добавить

2023-10-02 20:12 UTC, tureck1y commented on Tangem/Modules/LegacyTokenList/LegacyCoinView.swift
> +                IconView(url: model.imageURL, customTokenColor: nil, size: CGSize(width: iconWidth, height: iconWidth), forceKingfisher: true)
Да потому что все перепуталось.
IconView - это просто загрузка по урлу, ничего больше (для менеджер токенс например)
TokenIconView - это как раз то что надо, с поддержкой кастомности. Она должна использоваться везде, по приложению (главная, токен детеилс, сенд и тп)

2023-10-03 05:17 UTC, Andoran90 commented on Tangem/Modules/LegacyTokenList/LegacyCoinView.swift
> +                IconView(url: model.imageURL, customTokenColor: nil, size: CGSize(width: iconWidth, height: iconWidth), forceKingfisher: true)
Вообще я добавлял `TokenIcon`, который должен был заменить `TokenIconView`, чтобы не использовать модели `TokenIconViewModel`, т.к. вью модель совершенно не нужна, как по мне, для этой вьюхи, в неё можно напрямую передать нужные параметры и не плодить вью модельки. Для такого типа вьюх нужны модели, если они в списке отображаются, например, список иконок, но оно не используется нигде, поэтому я заменил `TokenIconView` на `TokenIcon` (используется сейчас на главной, но не на `TokenDetails`, потому что эта вьюха появилась после создания `TokenDetails` и там забыл обновить((()

2023-10-03 07:17 UTC, megakoko commented on Tangem/Modules/LegacyTokenList/LegacyCoinView.swift
> +                IconView(url: model.imageURL, customTokenColor: nil, size: CGSize(width: iconWidth, height: iconWidth), forceKingfisher: true)
TokenIconView помечен как deprecated, написано используйте IconView

2023-10-03 07:30 UTC, Andoran90 commented on Tangem/Modules/LegacyTokenList/LegacyCoinView.swift
> +                IconView(url: model.imageURL, customTokenColor: nil, size: CGSize(width: iconWidth, height: iconWidth), forceKingfisher: true)
`TokenIconView` не содержал в себе логики кастомной иконки, там был только `placeholder` для иконки.
Это уже специфика `TokenIcon`, которая может либо загружаться из сети, либо показывать кастомную иконку.

2023-10-03 08:33 UTC, megakoko commented
@Andoran90 @tureck1y обновил

2023-10-03 08:34 UTC, tureck1y commented on Tangem/Modules/LegacyTokenList/LegacyCoinView.swift
> +                IconView(url: model.imageURL, customTokenColor: nil, size: CGSize(width: iconWidth, height: iconWidth), forceKingfisher: true)
> TokenIconView помечен как deprecated, написано используйте IconView

это неправильно, кто написал?)

> TokenIconView не содержал в себе логики кастомной иконки

что такое кастовая иконка?

> Вообще я добавлял TokenIcon, который должен был заменить TokenIconView, 

Сам насоздавал иконок)) 

Короче IconView не трогаем. Дорабатываем TokenIcon?

2023-10-03 08:39 UTC, Andoran90 commented on Tangem/Modules/LegacyTokenList/LegacyCoinView.swift
> +                IconView(url: model.imageURL, customTokenColor: nil, size: CGSize(width: iconWidth, height: iconWidth), forceKingfisher: true)
я написал `deprecated` :)

<img width="193" alt="image" src="https://github.com/tangem/tangem-app-ios/assets/24321494/2e8255c8-ef2a-4f1f-a62e-7c1b820173bf">

да, я за доработку `TokenIcon`

2023-10-03 09:00 UTC, Andoran90 submitted a review, later dismissed

2023-10-03 09:00 UTC, Andoran90 commented on Tangem/Common/UI/TokenIconView/TokenIconViewModel.swift
> +        case customToken(color: Color)
по идее правки в этом файле вообще не нужны, т.к. эта вьюха только в старом дизе должна использоваться

2023-10-03 09:06 UTC, megakoko commented on Tangem/Common/UI/TokenIconView/TokenIconViewModel.swift
> +        case customToken(color: Color)
Увы...

```
class TokenDetailsHeaderViewModel {
    ...
    let tokenIconModel: TokenIconViewModel
```

2023-10-03 09:30 UTC, Andoran90 commented on Tangem/Common/UI/TokenIconView/TokenIconViewModel.swift
> +        case customToken(color: Color)
ну так его надо заменить на `TokenIconInfo`. В `TokenDetailsHeaderView` используется `TokenIcon` логично, что там должен быть `TokenIconInfo` вместо `TokenIconViewModel`

2023-10-03 09:39 UTC, megakoko commented on Tangem/Common/UI/TokenIconView/TokenIconViewModel.swift
> +        case customToken(color: Color)
Предлагаешь сейчас заменить?

2023-10-03 10:59 UTC, Andoran90 commented on Tangem/Common/UI/TokenIconView/TokenIconViewModel.swift
> +        case customToken(color: Color)
ну да, в `TokenDetailsHeaderView` ведь тоже неправильно отображается иконка, значит часть задачи, да и нет смысла вносить правки уже в легаси код, которому это и не надо

2023-10-03 11:02 UTC, megakoko commented on Tangem/Common/UI/TokenIconView/TokenIconViewModel.swift
> +        case customToken(color: Color)
Я легаси код правил только потому что через него сделано. Окей, допилю

2023-10-03 11:11 UTC, megakoko commented on Tangem/Common/UI/TokenIconView/TokenIconViewModel.swift
> +        case customToken(color: Color)
Переделал

2023-10-04 05:19 UTC, Andoran90 approved these changes

2023-10-05 11:32 UTC, tureck1y approved these changes

2023-10-05 11:33 UTC, merged