IOS-4514 showing buy notification
tangem/tangem-app-ios-old pull request #2194
Opened 2023-09-29 10:34 UTC by megakoko

2023-09-29 11:43 UTC, Andoran90 commented
СалоНах

2023-10-02 07:55 UTC, Andoran90 requested changes

2023-10-02 07:55 UTC, Andoran90 commented on Tangem/App/Services/NotificationManagers/SingleWalletNotificationManager.swift
> +        }
вроде это оповещение должно быть выше предыдущих двух. Ты не уточнял какой именно порядок должен быть?

2023-10-02 07:55 UTC, Andoran90 commented on Tangem/App/Services/NotificationManagers/TokenNotificationEvent.swift
>      case notEnoughtFeeForTokenTx(message: String)
вообще этот вариант предполагался, что будет использоваться. Он сейчас вроде нигде не юзается, надо либо его обновить, либо его удалить. Когда он добавлялся не было однозначных ещё трабований

2023-10-02 07:55 UTC, Andoran90 commented on Tangem/App/Services/NotificationManagers/TokenNotificationEvent.swift
> +    case unableToCoverFee(token: Token, blockchain: Blockchain)
вообще хотелось бы не использовать такую информацию в оповещении и сохранить тут только примитивы

2023-10-02 07:55 UTC, Andoran90 commented on Tangem/Modules/Main/Utilities/SingleTokenRouter.swift
> +    func openNetworkCurrency(for model: WalletModel, userWalletModel: UserWalletModel)
а зачем это тут? оно должно быть только для `TokenDetails` же. В итоге эта логика попадает во все экраны, хотя должна быть только в одном. Это надо перенести в `TokenDetailsRoutable` и реализовать в `TokenDetailsViewModel` экшон для кнопки с оповещения, возможно перезаписать реализацию базового класса.

2023-10-02 07:55 UTC, Andoran90 commented on Tangem/Modules/SingleTokenBase/SingleTokenBaseViewModel.swift
> +    private let networkCurrencyWalletModel: WalletModel?
это точно тут не должно быть

2023-10-02 07:55 UTC, Andoran90 commented on Tangem/Modules/TokenDetails/TokenDetailsViewModel.swift
> +        networkCurrencyWalletModel: WalletModel?,
этого тут тоже не должно быть.

Если у пользователя появилась такая плашка, внутри `TokenDetailsViewModel` есть доступ к `UserWalletModel`, оттуда можно получить ссылку на `WalletModelsManager` и внутри `TokenDetailsViewModel` найти нужную `WalletModel`, таскать всюду родительскую не надо, много лишнего кода и усложнение интерфейсов

2023-10-02 11:06 UTC, megakoko commented on Tangem/App/Services/NotificationManagers/SingleWalletNotificationManager.swift
> +        }
Леха сказал что между красными и желтыми, пододвинул. Повезло что в sendblockedreason все одинакового желтого приоритета

2023-10-02 11:20 UTC, tureck1y commented
А точно buy? Хотели же кидать на детальный экран токена?

2023-10-02 11:24 UTC, megakoko commented on Tangem/Modules/TokenDetails/TokenDetailsViewModel.swift
> +        networkCurrencyWalletModel: WalletModel?,
Удалил. Подумал что наоборот все зависимости предоставляем

2023-10-02 11:25 UTC, megakoko commented
> А точно buy? Хотели же кидать на детальный экран токена?

Туда и кидаем через пуш

2023-10-02 11:32 UTC, tureck1y commented
> Туда и кидаем через пуш

смутило название Buy

2023-10-02 12:22 UTC, megakoko commented on Tangem/App/Services/NotificationManagers/TokenNotificationEvent.swift
>      case notEnoughtFeeForTokenTx(message: String)
Используется на старой главной, пока оставил

2023-10-02 12:23 UTC, megakoko commented on Tangem/App/Services/NotificationManagers/TokenNotificationEvent.swift
> +    case unableToCoverFee(token: Token, blockchain: Blockchain)
Переделал

2023-10-02 12:23 UTC, megakoko commented on Tangem/Modules/Main/Utilities/SingleTokenRouter.swift
> +    func openNetworkCurrency(for model: WalletModel, userWalletModel: UserWalletModel)
Удолил

2023-10-02 12:23 UTC, megakoko commented on Tangem/Modules/SingleTokenBase/SingleTokenBaseViewModel.swift
> +    private let networkCurrencyWalletModel: WalletModel?
Удалил

2023-10-02 12:24 UTC, megakoko commented
@Andoran90 @tureck1y обновил

Леха сказал пока оставляем название BUY, потом может будем думать

2023-10-02 13:24 UTC, Andoran90 commented on Tangem/App/Services/NotificationManagers/TokenNotificationEvent.swift
>      case notEnoughtFeeForTokenTx(message: String)
ммм, он не может использоваться на старой главной, потому что `TokenNotificationEvent` появился только для нового дизайна. В старом дизайне используется `WalletModel.SendBlockedReason.notEnoughtFeeForTokenTx(tokenName: String, networkName: String, coinSymbol: String)`.

2023-10-02 13:27 UTC, Andoran90 commented on Tangem/App/Services/NotificationManagers/TokenNotificationEvent.swift
> +import BlockchainSdk
забыл импорт удалить :)

2023-10-02 13:27 UTC, Andoran90 commented on Tangem/App/ViewModels/WalletModel/WalletModel+.swift
> +        #warning("TODO: still used after the old token details is remvoed?")
```suggestion
        #warning("TODO: still used after the old token details is removed?")
```

2023-10-02 13:33 UTC, megakoko commented on Tangem/App/Services/NotificationManagers/TokenNotificationEvent.swift
>      case notEnoughtFeeForTokenTx(message: String)
А, вот оно что... Ну там получается в TokenNotificationEvent.event(for reason:) используется. Давай оставим пока, с удалением старых предупреждений удалим. Добавлю туду

2023-10-02 13:35 UTC, megakoko commented on Tangem/App/Services/NotificationManagers/TokenNotificationEvent.swift
> +import BlockchainSdk
Удолил тоже

2023-10-02 13:40 UTC, Andoran90 approved these changes, later dismissed

2023-10-02 13:40 UTC, Andoran90 commented on Tangem/Modules/TokenDetails/TokenDetailsViewModel.swift
> +            case .token(_, let blockchain) = walletModel.tokenItem,
@tureck1y уже не хватает инфы по деривации в `TokenItem`))

2023-10-02 19:05 UTC, tureck1y commented on Tangem/Modules/TokenDetails/TokenDetailsCoordinator.swift
> +        Analytics.log(.tokenIsTapped)
Ок ли что тут это событие осталось, нужно другое?

2023-10-03 07:03 UTC, megakoko commented on Tangem/Modules/TokenDetails/TokenDetailsCoordinator.swift
> +        Analytics.log(.tokenIsTapped)
Косяк копипасты. Леха говорит аналитика будет, но потом

2023-10-03 07:03 UTC, megakoko commented
@tureck1y @Andoran90 нужно еще ревью, удалил аналитику

2023-10-03 08:35 UTC, tureck1y approved these changes

2023-10-03 08:36 UTC, Andoran90 approved these changes

2023-10-03 08:36 UTC, merged