IOS-4730 sprinklr integration
tangem/tangem-app-ios-old pull request #2216
Opened 2023-10-06 11:19 UTC by megakoko

2023-10-09 09:25 UTC, Balashov152 commented on Tangem/Modules/SupportChat/Sprinklr/SprinklrSupportChatViewModel.swift
> +        let id = UIDevice.current.identifierForVendor ?? UUID()
Может при установке генерировать, и сохранять в defaults?

2023-10-09 09:25 UTC, Balashov152 commented on Tangem/App/Navigation/SheetModifier.swift
> +    private let fullScreen: Bool
Думаю лучше создать новый `struct FullScreenSheetModifier` и через него показывать
Выглядит, что как лишняя `if` тут

2023-10-09 10:17 UTC, megakoko commented on Tangem/App/Navigation/SheetModifier.swift
> +    private let fullScreen: Bool
Не знаю. Этот модификатор без дела лежал в коде, просто нашел ему применение. Это все равно временное решение, потом от зендеска откажемся

2023-10-09 10:18 UTC, megakoko commented on Tangem/Modules/SupportChat/Sprinklr/SprinklrSupportChatViewModel.swift
> +        let id = UIDevice.current.identifierForVendor ?? UUID()
Не хочется переусложнять. Этот идентификатор поменяется только если с устройства удалить все приложения нашего танжемовского аккаунта.

2023-10-10 14:24 UTC, tureck1y commented on Tangem/App/Navigation/SheetModifier.swift
> +    private let fullScreen: Bool
а зачем его вообще использовать? Стандартный шит не работает или что?

2023-10-10 14:25 UTC, megakoko commented on Tangem/App/Navigation/SheetModifier.swift
> +    private let fullScreen: Bool
У них вьюконтроллер в обычном шите сходит с ума и клавиатура перекрывает поле ввода. Советуют показывать на полный экран. Обещали исправить

2023-10-10 14:49 UTC, tureck1y requested changes
С одной стороны так меньше изменений, с другой стороны, неочевидны действия по удалению старого чата в будущем. Надо тогда пометить туду все что нужно сделать будет (удалить SheetModifier, переделать на постоянный фуллскрин и тп)

2023-10-10 14:49 UTC, tureck1y commented on Tangem/Common/AppPresenter.swift
> -    func showSupportChat(input: SupportChatInputModel) {
это нужно для отображения чата из алертов, лучше оставить

2023-10-10 14:49 UTC, tureck1y commented on Tangem/App/Navigation/SheetModifier.swift
> +    private let fullScreen: Bool
тогда надо будет этот модификатор снести целиком, вместе со старым частом, раз не используется

2023-10-10 14:49 UTC, tureck1y commented on Tangem/Modules/SupportChat/SupportChatView.swift
> +    static var useFullScreen: Bool {
давай хотя бы во вьюмодели напишем, несмотря на то что это временно

2023-10-11 09:08 UTC, megakoko commented on Tangem/Common/AppPresenter.swift
> -    func showSupportChat(input: SupportChatInputModel) {
Вернул, добавил сквирта туда

2023-10-11 09:08 UTC, megakoko commented on Tangem/Modules/SupportChat/SupportChatView.swift
> +    static var useFullScreen: Bool {
Перенес

2023-10-11 09:08 UTC, megakoko commented on Tangem/App/Navigation/SheetModifier.swift
> +    private let fullScreen: Bool
Добавил TODO

2023-10-11 16:47 UTC, megakoko commented
@Balashov152 @tureck1y переделал на хотфикс

2023-10-11 17:06 UTC, tureck1y commented on Tangem/App/Services/EnvironmentProvider/Feature.swift
> +        case .mainV2: return .version("5.0")
main открылся

2023-10-11 17:08 UTC, tureck1y commented on Tangem/Modules/SupportChat/SupportChatView.swift
> +    static var useFullScreen: Bool {
вроде не перенеслось

2023-10-12 07:17 UTC, megakoko commented on Tangem/App/Services/EnvironmentProvider/Feature.swift
> +        case .mainV2: return .version("5.0")
Исправил

2023-10-12 07:17 UTC, megakoko commented on Tangem/Modules/SupportChat/SupportChatView.swift
> +    static var useFullScreen: Bool {
Удалил полностью из вьюхи

2023-10-12 08:18 UTC, tureck1y approved these changes

2023-10-12 10:44 UTC, Balashov152 approved these changes

2023-10-12 10:47 UTC, merged