IOS-4682 Transaction history for legacy address
tangem/tangem-app-ios-old pull request #2222
Opened 2023-10-09 09:36 UTC by Balashov152

Добавил объеденение транзакций с легаси адресами

2023-10-10 07:01 UTC, Andoran90 commented on Tangem/App/Services/TransactionHistoryRepository/MutipleAddressTransactionHistoryService.swift
> +        guard !publishers.isEmpty else {
```suggestion
       if publishers.isEmpty {
```

2023-10-10 07:01 UTC, Andoran90 commented on Tangem/App/Services/TransactionHistoryRepository/MutipleAddressTransactionHistoryService.swift
> +        guard !_state.value.isLoading else {
Что ж все так помешались на `guard`? гораздо же проще будет конструкция без отрицания для чтения и понимания:
```suggestion
        if _state.value.isLoading {
```

2023-10-10 07:01 UTC, Andoran90 commented on Tangem/App/Services/TransactionHistoryRepository/MutipleAddressTransactionHistoryService.swift
> +                    service.currentPage[response.address, default: 0] = response.response.page.number
думаю дефолтные значения не нужны, тут же назначение происходит, а не чтение
```suggestion
                    service.totalPages[response.address] = response.response.totalPages
                    service.currentPage[response.address] = response.response.page.number
```

2023-10-10 07:10 UTC, megakoko commented on Tangem/App/Services/TransactionHistoryRepository/MutipleAddressTransactionHistoryService.swift
> +        guard !_state.value.isLoading else {
Не помешались, у них семантика разная. Гард — это не просто if наоборот

2023-10-10 12:29 UTC, Andoran90 commented on Tangem/App/Services/TransactionHistoryRepository/MutipleAddressTransactionHistoryService.swift
> +        guard !_state.value.isLoading else {
как по мне, постоянно излишне используется `guard`, когда гораздо уместнее `if`

2023-10-10 12:55 UTC, ba1ashov commented on Tangem/App/Services/TransactionHistoryRepository/MutipleAddressTransactionHistoryService.swift
> +        guard !publishers.isEmpty else {
✅

2023-10-10 12:56 UTC, Balashov152 commented on Tangem/App/Services/TransactionHistoryRepository/MutipleAddressTransactionHistoryService.swift
> +        guard !_state.value.isLoading else {
Я как будто не вспоминаю просто про `if` в таком случае)
если нужна обязательная проверка, иначе return или throw сразу в голову приходит guard

2023-10-10 14:14 UTC, tureck1y commented on Tangem/App/Services/TransactionHistoryRepository/MutipleAddressTransactionHistoryService.swift
> +        guard !_state.value.isLoading else {
имхо guard в начале метода читается лучше чем if всегда, это стандартный подход. Не вижу проблемы в отрицаниях. Надо вынести на обсуждение и закрыть этот вопрос раз и навсегда.

2023-10-10 14:20 UTC, tureck1y requested changes

2023-10-10 14:20 UTC, tureck1y commented on Tangem/App/Factories/WalletModels/CommonWalletModelsFactory.swift
> +    private func makeTransactionHistoryService(tokenItem: TokenItem, wallet: Wallet) -> TransactionHistoryService? {
лучше передать массив адресов тогда, зачем передавать большую сущность

2023-10-10 14:20 UTC, tureck1y commented on Tangem/App/Services/TransactionHistoryRepository/MutipleAddressTransactionHistoryService.swift
> +        Deferred {
если перестать слушать этот update, то результат запроса просто потеряется? А зачем тут комбинировать completion и rx? Может все сделать на rx?

2023-10-10 14:20 UTC, tureck1y commented on Tangem/App/Services/TransactionHistoryRepository/MutipleAddressTransactionHistoryService.swift
> +    func fetch(result: @escaping (Result<Void, Never>) -> Void) {
Добавь плиз комментов, очень много всего, невозможно разобраться за разумное время 😀. Лучше конечно как-то упростить

2023-10-10 14:48 UTC, Balashov152 commented on Tangem/App/Factories/WalletModels/CommonWalletModelsFactory.swift
> +    private func makeTransactionHistoryService(tokenItem: TokenItem, wallet: Wallet) -> TransactionHistoryService? {
✅

2023-10-10 14:50 UTC, ba1ashov commented on Tangem/App/Services/TransactionHistoryRepository/MutipleAddressTransactionHistoryService.swift
> +        Deferred {
>  запроса просто потеряется

нет, так как там все завязано на `cancellable` внутри `MutipleAddressTransactionHistoryService`

> А зачем тут комбинировать completion и rx?

Здесь используется Deferred/Future для того что бы потребитель мог понять когда запрос прошел
по факту вся логика с сохранением подписки живет внутри класса, логика похоже как в WalletModel

2023-10-10 14:50 UTC, Balashov152 commented on Tangem/App/Services/TransactionHistoryRepository/MutipleAddressTransactionHistoryService.swift
> +    func fetch(result: @escaping (Result<Void, Never>) -> Void) {
Добавил комментов)

2023-10-10 14:51 UTC, Balashov152 commented on Tangem/App/Services/TransactionHistoryRepository/MutipleAddressTransactionHistoryService.swift
> +    func fetch(result: @escaping (Result<Void, Never>) -> Void) {
Такого рода `LoadingPublisher` надо собрать по каждому адресу, что бы постранично их грузить

2023-10-10 15:31 UTC, Balashov152 commented on Tangem/App/Services/TransactionHistoryRepository/MutipleAddressTransactionHistoryService.swift
> +                    service.currentPage[response.address, default: 0] = response.response.page.number
✅

2023-10-11 05:19 UTC, Andoran90 approved these changes

2023-10-11 08:25 UTC, tureck1y approved these changes

2023-10-11 09:28 UTC, merged