IOS-4331 recheck paddings
tangem/tangem-app-ios-old pull request #2263
Opened 2023-10-18 12:15 UTC by megakoko

2023-10-18 12:28 UTC, megakoko commented on Tangem/Modules/Main/MainHeaderView/MainHeaderSubtitleProvider/MultiWalletMainHeaderSubtitleProvider.swift
> -    private let separator = " • "
Сепаратор теперь рендерится вручную

2023-10-18 12:28 UTC, megakoko commented on Tangem/Modules/TokenDetails/Views/TokenDetailsHeaderView.swift
>                  Text(viewModel.tokenName)
Переделал лейаут, иконка сети распирала внутренний HStack, все шло по бороде

2023-10-18 17:26 UTC, ba1ashov commented on Tangem/Modules/Main/MainHeaderView/MainHeaderSubtitleProvider/MultiWalletMainHeaderSubtitleProvider.swift
> +        let numberOfCardsPrefix = Localization.cardLabelCardCount(2)
Хардкод появился 
```suggestion
        let numberOfCardsPrefix = Localization.cardLabelCardCount(numberOfCards)
```

2023-10-18 17:26 UTC, ba1ashov commented on Tangem/Common/AppConstants.swift
> +    static let minusSign = "−"
может еще и plusSign закинем ?

2023-10-18 17:26 UTC, Balashov152 commented on Tangem/Common/UI/Buttons/MainButton.swift
> +        }
вроде это должно шрифтом решаться

2023-10-18 17:26 UTC, Balashov152 commented on Tangem/Modules/Main/MainHeaderView/MainHeaderSubtitleProvider/SingleWalletMainHeaderSubtitleProvider.swift
> +        subject.send(.init(messages: [balance], formattingOption: .default))
Как будто везде по элементу, зачем массив?

2023-10-18 17:45 UTC, tureck1y requested changes
Я же просил не подгонять верстку под неправильные макеты. 
- Никаких 3,5,13, тем более 3.5 быть не должно. Должно быть кратно 4. В крайнем случае - 2.
- Не должно быть такого, что сверху 14, а снизу - 15. Это все баги макетов, мы договорились с дизайнерами, что они это поправят. 
- Манипуляции над шрифтами выкидываем, это тоже баги макетов. Мы еще в процессе решения этой проблемы, скорее всего идеального совпадения добиться не получится

У этой задачи одна цель - убрать явные расхождения, которые бросаются в глаза. После правки макетов, уже будем смотреть

2023-10-18 17:45 UTC, tureck1y commented on Tangem/Common/Extensions/View+.swift
> +    func kerningCompat(_ kerning: CGFloat) -> some View {
а, так это еще и не на всех иосах, тогда убираем

2023-10-18 17:45 UTC, tureck1y commented on Tangem/Common/UI/Buttons/MainButton.swift
> +        }
да, я сначала думал оставить, но тут костыли, поэтому манипуляции над шрифтами все убираем

2023-10-18 17:45 UTC, tureck1y commented on Tangem/Common/UI/Buttons/MainButton.swift
> +                return 14
а это точно не баг, что значения разные? Если баг, то надо править на стороне макетов

2023-10-18 17:45 UTC, tureck1y commented on Tangem/Modules/Main/MultiWalletMainContent/MultiWalletMainContentView.swift
> +                .lineSpacing(2)
тоже убираем здесь и везде, это шрифтами потом будем решать

2023-10-18 17:45 UTC, tureck1y commented on Tangem/Modules/Main/UnlockCardBottomSheet/UnlockUserWalletBottomSheetView.swift
> +                state.wrappedValue = bottomSheetModel
Тут все ок? Не похоже на правки разметки

2023-10-18 17:45 UTC, tureck1y commented on Tangem/UIComponents/PendingTransactionsListView/PendingTransactionsListView.swift
> -                    .ios14FixedHeight(Constants.ios14ListItemHeight)
а это точно ничего на 14 не сломает? @Andoran90

2023-10-18 17:45 UTC, tureck1y commented on Tangem/UIComponents/TokenItemView/TokenItemView.swift
> +        .padding(.horizontal, 14)
это конечно все выглядит как баги в моках, мы договорились, что все отступы должны быть кратны 2 или 4.

2023-10-19 07:25 UTC, megakoko commented on Tangem/Modules/Main/MainHeaderView/MainHeaderSubtitleProvider/MultiWalletMainHeaderSubtitleProvider.swift
> +        let numberOfCardsPrefix = Localization.cardLabelCardCount(2)
Спасибо, осталось после тестирования

2023-10-19 07:26 UTC, megakoko commented on Tangem/Common/AppConstants.swift
> +    static let minusSign = "−"
Да не хочется, plusSign тот же что на клавиатуре. Вообще это бы в форматтер унести и форматировать с +/- явно через какой-то параметр

2023-10-19 07:27 UTC, megakoko commented on Tangem/Common/UI/Buttons/MainButton.swift
> +        }
В фигме задан отрицательный кернинг. Ты сам говорил что оставляем раз сделали

2023-10-19 07:28 UTC, megakoko commented on Tangem/Modules/Main/MainHeaderView/MainHeaderSubtitleProvider/SingleWalletMainHeaderSubtitleProvider.swift
> +        subject.send(.init(messages: [balance], formattingOption: .default))
Для разделения элементов кругляшом. Кругляш рендерим программно

2023-10-19 07:28 UTC, megakoko commented on Tangem/Common/UI/Buttons/MainButton.swift
> +                return 14
Не баг

2023-10-19 07:28 UTC, megakoko commented on Tangem/Modules/Main/UnlockCardBottomSheet/UnlockUserWalletBottomSheetView.swift
> +                state.wrappedValue = bottomSheetModel
Это правка превью

2023-10-19 07:40 UTC, megakoko commented on Tangem/Modules/Main/MultiWalletMainContent/MultiWalletMainContentView.swift
> +                .lineSpacing(2)
Во всем проекте убрать lineSpacing?

2023-10-19 07:59 UTC, megakoko commented on Tangem/UIComponents/PendingTransactionsListView/PendingTransactionsListView.swift
> -                    .ios14FixedHeight(Constants.ios14ListItemHeight)
Я в других местах такие штуки заменял на явный паддинг, думаю не должно. Тут не помню почему так осталось, но проверял и внутреннего паддинга самой TransactionView хватало чтобы распереть ячейку.

2023-10-19 10:43 UTC, megakoko commented on Tangem/UIComponents/TokenItemView/TokenItemView.swift
> +        .padding(.horizontal, 14)
Откатил такие места

2023-10-19 10:46 UTC, megakoko commented on Tangem/Common/Extensions/View+.swift
> +    func kerningCompat(_ kerning: CGFloat) -> some View {
Отрицательный кернинг задан в фигме

2023-10-19 10:48 UTC, tureck1y commented on Tangem/Modules/Main/MultiWalletMainContent/MultiWalletMainContentView.swift
> +                .lineSpacing(2)
не надо в всем, в новом дизайне только не добавляй новых

2023-10-19 10:48 UTC, tureck1y commented on Tangem/Common/Extensions/View+.swift
> +    func kerningCompat(_ kerning: CGFloat) -> some View {
Все что в фигме - это параметры мотков, это не для нас

2023-10-19 10:49 UTC, megakoko commented on Tangem/Modules/Main/MultiWalletMainContent/MultiWalletMainContentView.swift
> +                .lineSpacing(2)
Ну в новом дизайне уже и до меня были, видно было что пытались подгонять под фигму. Уберу тогда в новых экранах

2023-10-19 10:53 UTC, megakoko commented on Tangem/Modules/Main/MultiWalletMainContent/MultiWalletMainContentView.swift
> +                .lineSpacing(2)
Убрал

2023-10-19 10:54 UTC, megakoko commented on Tangem/Common/UI/Buttons/MainButton.swift
> +        }
Удалил кернинг

2023-10-19 10:55 UTC, megakoko commented on Tangem/Common/Extensions/View+.swift
> +    func kerningCompat(_ kerning: CGFloat) -> some View {
Удалил кернинг

2023-10-19 10:55 UTC, megakoko commented on Tangem/Common/Extensions/View+.swift
> +    func kerningCompat(_ kerning: CGFloat) -> some View {
Сказать бы еще Андрею, что в фигме параметры не для нас чтоб говном не кидался

2023-10-19 10:56 UTC, tureck1y commented on Tangem/Common/Extensions/View+.swift
> +    func kerningCompat(_ kerning: CGFloat) -> some View {
я на встрече расскажу подробнее как с фирмой работаем

2023-10-19 12:50 UTC, Andoran90 requested changes

2023-10-19 12:50 UTC, Andoran90 commented on Tangem/Modules/Main/UnlockCardBottomSheet/UnlockUserWalletBottomSheetView.swift
> -                title: Localization.scanCardSettingsButton,
какой смысл этой правки? она не относится к pixel perfect, и не привносит ясности в код. Если хочется сделать такую правку - надо тогда делать `common_scan_card`, но это же не относится к этой задаче

2023-10-19 12:50 UTC, Andoran90 commented on Tangem/Modules/OrganizeTokens/ListItem/OrganizeTokensListItemView.swift
> +            VStack(alignment: .leading, spacing: 5) {
странное значение, не кратно ни 2, ни 4.

2023-10-19 12:50 UTC, Andoran90 commented on Tangem/Modules/OrganizeTokens/ListSection/OrganizeTokensListSectionView.swift
> +        .padding(.vertical, 11)
и снова странные значения

2023-10-19 12:50 UTC, Andoran90 commented on Tangem/Modules/TokenDetails/Views/TokenDetailsHeaderView.swift
> +            VStack(alignment: .leading, spacing: 7) {
странные значения

2023-10-19 12:50 UTC, Andoran90 commented on Tangem/Modules/TokenDetails/Views/TokenDetailsHeaderView.swift
>                  Text(viewModel.tokenName)
не понял что где распирало, что пошло по бороде?..

2023-10-19 12:50 UTC, Andoran90 commented on Tangem/UIComponents/BalanceWithButtonsView/BalanceWithButtonsView.swift
> +                    .padding(.top, 7)
```suggestion
                    .padding(.top, 8)
```

вообще выглядит так, будто надо просто `VStack(alignment: .leading, spacing: 8) {`

2023-10-19 12:50 UTC, Andoran90 commented on Tangem/Common/Extensions/View+.swift
> -    }
зачем удалил? это фикс для скролла при наличии истории транзакций. С красным балансом Tangem Alpha это с твоей ветки собранный билд

https://github.com/tangem/tangem-app-ios/assets/24321494/80ed0c12-c92d-41e5-9613-33ee01ab9fc0

2023-10-19 12:50 UTC, Andoran90 commented on Tangem/UIComponents/TokenItemView/TokenItemView.swift
> -        .frame(minHeight: 68)
этот минимальный размер подгонял ячейки по высоте, сейчас они расходятся с дизайном

<img width="515" alt="Monosnap 2023-10-19 17-28-21" src="https://github.com/tangem/tangem-app-ios/assets/24321494/a6d77c5f-2072-4573-a1ce-93cc62effa07">



Вот тут в описании МРа можешь посмотреть как выглядел список до твоих правок если накладывать скриншот на диз. В итоге сейчас получается нифига не pixel perfect.
https://github.com/tangem/tangem-app-ios/pull/2169

<img width="515" src="https://user-images.githubusercontent.com/24321494/270357654-624e7a38-8e98-44f0-b41b-e934c9ca02aa.png">

2023-10-19 12:50 UTC, Andoran90 commented on Tangem/UIComponents/PendingTransactionsListView/PendingTransactionsListView.swift
> -                    .ios14FixedHeight(Constants.ios14ListItemHeight)
ломает на 14 оси ptr. Приложил видос в комментарии к `View+.swift`

2023-10-19 12:50 UTC, Andoran90 commented on Tangem/UIComponents/TransactionHistory/TransactionsListView.swift
> -        VStack(spacing: 20) {
Сломал верстку для токенов с двухстрочным названием монет, ну и текст в какую-то кашу превратился. Как по мне тут лучше оставить хотя бы подобранный руками `lineSpacing`.

<img width="300" src="https://github.com/tangem/tangem-app-ios/assets/24321494/d7125403-b651-4a50-aee3-40a8c0a89694">
<img width="300" src="https://github.com/tangem/tangem-app-ios/assets/24321494/215f0482-5bf7-4b01-bacc-bae1e82f62bd">
<img width="300" src="https://github.com/tangem/tangem-app-ios/assets/24321494/c6e5f873-8c76-4b2e-acbf-bdd91d77ffc9">

2023-10-19 12:50 UTC, Andoran90 commented on Tangem/UIComponents/TransactionView/TransactionView.swift
> +                HStack(spacing: 7) {
```suggestion
            VStack(alignment: .leading, spacing: 4) {
                HStack(spacing: 8) {
```

2023-10-19 12:53 UTC, megakoko commented on Tangem/Modules/TokenDetails/Views/TokenDetailsHeaderView.swift
>                  Text(viewModel.tokenName)
https://tangem.slack.com/archives/C055M6ECABY/p1697613003778499

Верхний HStack распирало

2023-10-19 12:57 UTC, megakoko commented on Tangem/Common/Extensions/View+.swift
> -    }
Удалил потому что надо делать через паддинги. С динамичными шрифтами это не будет работать.

2023-10-19 12:58 UTC, megakoko commented on Tangem/UIComponents/TokenItemView/TokenItemView.swift
> -        .frame(minHeight: 68)
Надо делать через паддинги. У меня все сходилось

2023-10-19 13:03 UTC, megakoko commented on Tangem/Modules/Main/UnlockCardBottomSheet/UnlockUserWalletBottomSheetView.swift
> -                title: Localization.scanCardSettingsButton,
Делал чтобы было совпадение по дизайну

2023-10-19 13:05 UTC, megakoko commented on Tangem/Modules/OrganizeTokens/ListItem/OrganizeTokensListItemView.swift
> +            VStack(alignment: .leading, spacing: 5) {
Поищи по проекту `spacing: \d*[13579]\b`

В чем проблема нечетных размеров?

2023-10-19 13:09 UTC, megakoko commented on Tangem/UIComponents/TransactionHistory/TransactionsListView.swift
> -        VStack(spacing: 20) {
Что здесь сломано на экране?

2023-10-19 13:25 UTC, Andoran90 commented on Tangem/Modules/TokenDetails/Views/TokenDetailsHeaderView.swift
>                  Text(viewModel.tokenName)
вот теперь понятно. Когда делаешь что-то связанное с UI прикладывай скриншоты, видео, чтобы было понятно зачем и что меняет, что исправляется. А то приходится тратить дохрена часов, чтобы посмотреть что изменилось в МРе

2023-10-19 13:27 UTC, megakoko commented on Tangem/UIComponents/PendingTransactionsListView/PendingTransactionsListView.swift
> -                    .ios14FixedHeight(Constants.ios14ListItemHeight)
@Andoran90 minHeight подойдет вместо фиксированной высоты?

2023-10-19 13:30 UTC, Andoran90 commented on Tangem/Modules/Main/UnlockCardBottomSheet/UnlockUserWalletBottomSheetView.swift
> -                title: Localization.scanCardSettingsButton,
а что не совпадает по дизайну? Или в дизайне указан ключевик, который надо использовать? и почему не `home_button_scan`?

Конкретней отвечай, почему чтобы понять твой ответ надо 100500 вопросов задавать или же лезть и всюду проверять?

2023-10-19 13:31 UTC, Andoran90 commented on Tangem/Modules/OrganizeTokens/ListItem/OrganizeTokensListItemView.swift
> +            VStack(alignment: .leading, spacing: 5) {
как минимум:
<img width="700" alt="image" src="https://github.com/tangem/tangem-app-ios/assets/24321494/14ce58ce-e242-4072-941e-5886022d938c">

мы уже много раз обсуждали, что будем использовать кратные 2 или 4 значения.

2023-10-19 13:34 UTC, Andoran90 commented on Tangem/UIComponents/TokenItemView/TokenItemView.swift
> -        .frame(minHeight: 68)
я хз как у тебя сходилось, ты ни один скрин не приложил, я сделал сборку с твоей ветки чтобы проверять, первый скриншот - то что у меня на девайсе получилось.

Вообще сделать огромный МР, в котором куча изменений по UI и не показать что ты сделал, закинуть 2 комментария, по которым потом все спрашивают какого черта происходит - это вообще наплевать на всех кто будет смотреть твой МР, или тебе вообще наплевать на тех кто будет ревьюить твой код и на их время?

2023-10-19 13:35 UTC, Andoran90 commented on Tangem/Common/Extensions/View+.swift
> -    }
молодец, возвращай этот код или чини PTR для 14 оси

2023-10-19 13:35 UTC, Andoran90 commented on Tangem/UIComponents/TransactionHistory/TransactionsListView.swift
> -        VStack(spacing: 20) {
<img width="854" alt="image" src="https://github.com/tangem/tangem-app-ios/assets/24321494/97d93b1f-6750-4d5c-94cd-ed1c7b744968">

2023-10-19 13:38 UTC, megakoko commented on Tangem/UIComponents/PendingTransactionsListView/PendingTransactionsListView.swift
> -                    .ios14FixedHeight(Constants.ios14ListItemHeight)
Вернул обратно

2023-10-19 13:40 UTC, Andoran90 commented on Tangem/UIComponents/PendingTransactionsListView/PendingTransactionsListView.swift
> -                    .ios14FixedHeight(Constants.ios14ListItemHeight)
проблема в том что при разных высотах ячеек скролл ломается и вообще нифига не работает на 14 оси

2023-10-19 14:13 UTC, megakoko commented on Tangem/UIComponents/TransactionView/TransactionView.swift
> +                HStack(spacing: 7) {
Откатил

2023-10-19 14:13 UTC, megakoko commented on Tangem/Common/Extensions/View+.swift
> -    }
Откатил

2023-10-19 14:14 UTC, megakoko commented on Tangem/UIComponents/BalanceWithButtonsView/BalanceWithButtonsView.swift
> +                    .padding(.top, 7)
Откатил

2023-10-19 14:14 UTC, megakoko commented on Tangem/Modules/TokenDetails/Views/TokenDetailsHeaderView.swift
> +            VStack(alignment: .leading, spacing: 7) {
Откатил

2023-10-19 14:14 UTC, megakoko commented on Tangem/Modules/OrganizeTokens/ListSection/OrganizeTokensListSectionView.swift
> +        .padding(.vertical, 11)
Откатил

2023-10-19 14:14 UTC, megakoko commented on Tangem/Modules/OrganizeTokens/ListItem/OrganizeTokensListItemView.swift
> +            VStack(alignment: .leading, spacing: 5) {
Откатил

2023-10-19 14:14 UTC, megakoko commented on Tangem/Modules/Main/UnlockCardBottomSheet/UnlockUserWalletBottomSheetView.swift
> -                title: Localization.scanCardSettingsButton,
Откатил

2023-10-19 14:20 UTC, megakoko commented on Tangem/UIComponents/TransactionHistory/TransactionsListView.swift
> -        VStack(spacing: 20) {
Откатидл

2023-10-19 16:12 UTC, megakoko commented on Tangem/UIComponents/TokenItemView/TokenItemView.swift
> -        .frame(minHeight: 68)
Андрей, дорогой мой, конечно же мне не наплевать. Я считаю нет смысла выкладывать скриншоты МРа у которого цель — пиксельперфекционизм. Там было 1-в-1 соответствие с погрешностью в полпикселя. Какие моменты были неочевидны на мой взгляд те и описал. Надеюсь не сильно испортил твой вечер ❤️

Все захардкоженные высоты я выкидывал и заменял на паддинги. Нет хороших причин хардкодить высоту, даже если мы не поддерживаем динамические шрифты. Обновили лейаут и что, надо обновлять теперь высоту? Зачем рассыпать грабли будущим поколениям? Не должно ничего быть прибито.

То, что не углублялся в костыли 14-й айос — да, мой косяк, предположил что там так же без хороших причин было сделано и что паддингом все вылечится.

2023-10-19 16:21 UTC, megakoko commented on Tangem/UIComponents/TokenItemView/TokenItemView.swift
> -        .frame(minHeight: 68)
Касательно съехавшего лейаута — я откатился на свой последний коммит и да, действительно, лейаут поехал. Поехал в районе заголовка. Но я 100% сравнивал весь список вместе с заголовками и 100% было отлично. Предполагаю, что поехало после того как начал править Organize Tokens, потому что главная и органайз используют одну и ту же вьюху в качестве заголовка и я этого не заметил. Или забыл. Прости, был заебан рассматриванием пикселей в лупу в течении нескольких дней.

И нет, я ни в коем случае не виню никого что одну вьюху переиспользовали вместе с внутренними паддингами. Это нормально, не досмотрели, упустили, все люди.

Прямо сейчас — да, есть несовпадение. Смысла его чинить нет, потому что без нечетных паддингов совпадения не добиться.

Чтобы показать что мне не наплевать прикладываю скриншот с коммита 13acbb49a9d9bde8e8ddd5eb97141c503c58f7c1. Патч с захардкоженными рейтами и балансами прикладывать  не буду, если надо — пришлю в личку.

<img width="592" alt="Screenshot 2023-10-19 at 19 04 26" src="https://github.com/tangem/tangem-app-ios/assets/12209839/58a1d76d-01d7-4be4-9336-597e3b29f10d">

Чтобы показать что я тебя на скриншоте не обманываю и там действительно есть данные вот скрин со смещением.

<img width="589" alt="Screenshot 2023-10-19 at 19 04 36" src="https://github.com/tangem/tangem-app-ios/assets/12209839/92d71f3f-e6ef-4796-9455-1f6fcdd537f3">

2023-10-19 16:51 UTC, megakoko commented
Появилась проблема с высотой баланса в token details, починил

2023-10-19 17:07 UTC, tureck1y commented on Tangem/UIComponents/PendingTransactionsListView/PendingTransactionsListView.swift
> -                    .ios14FixedHeight(Constants.ios14ListItemHeight)
давай тогда вернем как было да и все? Сейчас minHeight

2023-10-19 17:14 UTC, tureck1y reviewed
Раз ломается то тут то там, давайте перенаправим в девелоп, возьмем в след релиз

2023-10-19 17:25 UTC, megakoko commented on Tangem/UIComponents/TokenItemView/TokenItemView.swift
> -        .frame(minHeight: 68)
А, не, оказывается одинаковые паддинги у этого заголовка. Не знаю в чем причина тогда

2023-10-20 07:43 UTC, Andoran90 commented on Tangem/UIComponents/TransactionHistory/TransactionsListView.swift
> -        VStack(spacing: 20) {
блин, оказывается не в то место добавил коммент. В общем проблема на 14 оси осталась, на 17 все норм. Хз может изменение верстки заголовка сломало, вроде не сильно `notSupportedContent` менялся.

2023-10-20 07:47 UTC, Andoran90 commented on Tangem/UIComponents/PendingTransactionsListView/PendingTransactionsListView.swift
> -                    .ios14FixedHeight(Constants.ios14ListItemHeight)
с `minHeight` подлагивает скролл, но прям в 100% случаев, но случается. + верстка выглядит вот так
<img width="300" src="https://github.com/tangem/tangem-app-ios/assets/24321494/cacafad3-2851-4e16-a9a3-519f24a3cc30">

Но, кстати, может быть проблема не в этом, а в измененной верстке в `TransactionsListView.swift` внутри `func transactionsContent`.

2023-10-20 07:52 UTC, Andoran90 commented on Tangem/UIComponents/TokenItemView/TokenItemView.swift
> -        .frame(minHeight: 68)
проблема не в обмане, а в том, что смотришь МР и нифига не понимаешь почему именно изменили верстку полностью и какой это профит принесло. Причем мы это обсуждали на командном сборе, что надо оформлять МРы, писать описание, прикладывать скриншоты, видосы, комментарии к МРу, который поясняет что к чему, чтобы облегчить другим работу, а не усложнять её, все равно каждый из нас занимается задачей и может легко сделать пару скринов результатов конечных, если конечно с UI работаешь.

2023-10-20 07:53 UTC, megakoko commented on Tangem/UIComponents/PendingTransactionsListView/PendingTransactionsListView.swift
> -                    .ios14FixedHeight(Constants.ios14ListItemHeight)
Вернул fixed height. Еще одна причина отказаться от 14

2023-10-20 07:58 UTC, Andoran90 commented
ломается в основном на 14 оси, на 17 не такие уж и сильные изменения, большую часть вряд ли заметишь, если не смотришь версии до и после бок о бок. Как будто лучше бы после правок по шрифтам и фиксов по дизу, но это непонятно сколько ждать придется.

2023-10-20 07:59 UTC, Andoran90 commented on Tangem/UIComponents/PendingTransactionsListView/PendingTransactionsListView.swift
> -                    .ios14FixedHeight(Constants.ios14ListItemHeight)
да, из-за 14 оси много костылей и постоянно ломается то тут то там, непонятно когда выстрелит

2023-10-20 08:13 UTC, megakoko commented on Tangem/UIComponents/TransactionHistory/TransactionsListView.swift
> -        VStack(spacing: 20) {
Странно, ни хедер, ни BalanceWithButtons сильно не затронуты

Можешь пожалуйста посмотреть в чем там может быть причина?

2023-10-20 08:37 UTC, Andoran90 commented on Tangem/UIComponents/TransactionHistory/TransactionsListView.swift
> -        VStack(spacing: 20) {
надо решить будем его сейчас брать в релиз или уже в следующий возьмем, если сейчас берем - тогда займусь сейчас этим. @tureck1y что будем делать?

2023-10-20 08:38 UTC, megakoko commented on Tangem/UIComponents/TransactionHistory/TransactionsListView.swift
> -        VStack(spacing: 20) {
Сейчас не берем, я начеррипикал наиболее важные изменения в другой МР

2023-10-20 08:47 UTC, Andoran90 commented on Tangem/UIComponents/TransactionHistory/TransactionsListView.swift
> -        VStack(spacing: 20) {
давай тогда в драфт пока положим, я в понедельник займусь

2023-11-03 14:21 UTC, megakoko commented
Были конфликты в TokenDetailsView из-за     `    if viewModel.canHideToken `

В receivebottomsheetview из-за https://github.com/tangem/tangem-app-ios/commit/278bd700acee3aed8bfd149ff863e159a3a62b27

В tokenitemview из-за https://github.com/tangem/tangem-app-ios/commit/1aae017acfde3f9b19fb97599ca915c21773354a

2023-11-03 14:24 UTC, megakoko commented
@Andoran90 обновил, можно посмотреть

2023-11-07 12:19 UTC, tureck1y approved these changes, later dismissed
Ждем еще проверки на 14 оси

2023-11-07 13:43 UTC, Andoran90 commented on Tangem/UIComponents/TransactionHistory/TransactionsListView.swift
> -        .ios14FixedHeight(Constants.ios14ListItemHeight)
слева то что было до правок, справа - после. Такое чувство будто лучше оставить старую верстку, ну или сделать старый вариант только для 14 оси. @tureck1y @megakoko 
![IMG_DBFFA77431C7-1](https://github.com/tangem/tangem-app-ios/assets/24321494/821f7a12-ef1d-4117-a17a-dbe6560c5e42)

![IMG_2D8305F4675F-1](https://github.com/tangem/tangem-app-ios/assets/24321494/77bae656-6440-4af2-a414-6c0ac3f2c889)

2023-11-07 13:47 UTC, Andoran90 commented on Tangem/UIComponents/TransactionHistory/TransactionsListView.swift
> -                .lineSpacing(Constants.lineSpacing)
Просто на заметку, из-за удаления этого значения вот так выглядит. точно стоит удалять этот костыль до синхронизации и фиксов по шрифтам? Кажется фиксы по шрифтам не особо помогут в этом случае

<img width="400" src="https://github.com/tangem/tangem-app-ios/assets/24321494/09d91d45-fc24-46ae-80ae-7adb9e6eb113">
<img width="400" src="https://github.com/tangem/tangem-app-ios/assets/24321494/08259b4d-42e1-4a3c-8cd7-478c8b64aae7">

2023-11-07 13:47 UTC, megakoko commented on Tangem/UIComponents/TransactionHistory/TransactionsListView.swift
> -        .ios14FixedHeight(Constants.ios14ListItemHeight)
Если честно то и до правок на 14 выглядит не очень, много пространства

Может просто расставить эти костыли везде где надо? Я вроде везде вернул фиксированную ширину. Или даже обычный HStack распирает так?

2023-11-07 13:57 UTC, Andoran90 commented on Tangem/UIComponents/TransactionHistory/TransactionsListView.swift
> -        .ios14FixedHeight(Constants.ios14ListItemHeight)
да, тут на 14 оси все криво, просто до правок хотя бы блок `Transactions` не такой жуткий. 
Про какую фиксированную ширину ты говоришь? тут проблема в высоте ячеек и их заголовков

2023-11-07 14:08 UTC, megakoko commented on Tangem/UIComponents/TransactionHistory/TransactionsListView.swift
> -        .ios14FixedHeight(Constants.ios14ListItemHeight)
Имел в виду фиксированную высоту

2023-11-07 14:13 UTC, Andoran90 commented on Tangem/UIComponents/TransactionHistory/TransactionsListView.swift
> -        .ios14FixedHeight(Constants.ios14ListItemHeight)
ты же верстку прям поменял, когда вынес `header` из `makeSectionHeader`, поэтому заголовок истории транзакции получился таким, раньше он был частью первого заголовка и в результате визуально было более-менее. Я именно в этом и предлагаю вернуть верстку старую или только для 14 или для всех

2023-11-07 14:26 UTC, megakoko commented on Tangem/UIComponents/TransactionHistory/TransactionsListView.swift
> -        .ios14FixedHeight(Constants.ios14ListItemHeight)
Обновил, сделал костыль чуть покороче (56 -> 42 px) для заголовков этих

2023-11-07 14:33 UTC, tureck1y commented on Tangem/UIComponents/TransactionHistory/TransactionsListView.swift
> -        .ios14FixedHeight(Constants.ios14ListItemHeight)
Сделайте так, как ближе к дизайну. Если на 14 немного будет отличаться - не страшно. Главное, чтоб на 14 все было функционально в плане логики

2023-11-07 14:42 UTC, Andoran90 commented on Tangem/UIComponents/TransactionHistory/TransactionsListView.swift
> -        .ios14FixedHeight(Constants.ios14ListItemHeight)
@megakoko давай просто оставим старую версию для 14 оси, а для 15 и выше - новый твой вариант. Нам тут лучше сделать ифчик, который мы в феврале просто 🪚 и забудем. Думаю можно прямо сделать сделать проверку версии в `transactionsContent` в блоке `else` и сделать 2 реализации. Сгруппировать их под `// MARK: - iOS 15 and above` и `// MARK: - iOS 14. Deprecated will be removed with iOS 14 support`.

2023-11-07 14:43 UTC, megakoko commented on Tangem/UIComponents/TransactionHistory/TransactionsListView.swift
> -        .ios14FixedHeight(Constants.ios14ListItemHeight)
Я уже поправил, должно лучше выглядеть

2023-11-08 06:10 UTC, Andoran90 commented on Tangem/UIComponents/TransactionHistory/TransactionsListView.swift
> -        .ios14FixedHeight(Constants.ios14ListItemHeight)
нет, не годится, птр перестает работать. Попробовал разные значения заголовка, ломается птр. Вот так выглядит на твоем последнем коммите:

https://github.com/tangem/tangem-app-ios/assets/24321494/f5072256-07ba-4faf-9838-2972bb186dc4

2023-11-08 06:11 UTC, Andoran90 commented on Tangem/UIComponents/TransactionHistory/TransactionsListView.swift
> -        .ios14FixedHeight(Constants.ios14ListItemHeight)
давай делать 2 версии, одну для 14 оси со старой реализацией и одну с новой

2023-11-09 06:09 UTC, Andoran90 commented on Tangem/UIComponents/TransactionHistory/TransactionsListView.swift
> +        .padding(.vertical, useVerticalPadding ? 14 : 0)
для 17 оси поехало
<img width="505" alt="image" src="https://github.com/tangem/tangem-app-ios/assets/24321494/da687839-0022-403e-b921-d4f03ac7af6a">

2023-11-09 06:09 UTC, Andoran90 commented on Tangem/UIComponents/TransactionHistory/TransactionsListView.swift
> +        .padding(.vertical, useVerticalPadding ? 14 : 0)
на 14 оси первый заголовок нормально встал, а вот второй кривой, а третий уже норм О_о
Но птр на 14 оси норм работает, так что с 14 думаю можно закончить, проверь, пожалуйста, на 17 или 16 оси первую заголовок с датой, у тебя норм или нет

2023-11-09 07:26 UTC, megakoko commented on Tangem/UIComponents/TransactionHistory/TransactionsListView.swift
> +        .padding(.vertical, useVerticalPadding ? 14 : 0)
Обновил, теперь должно быть норм
<img width="635" alt="Screenshot 2023-11-09 at 10 24 53" src="https://github.com/tangem/tangem-app-ios/assets/12209839/7ea7034e-19cc-4235-9681-c553b2269c6e">
<img width="565" alt="Screenshot 2023-11-09 at 10 26 00" src="https://github.com/tangem/tangem-app-ios/assets/12209839/cc071f58-b788-4be3-be32-ea5b1c96a6c4">

2023-11-09 07:31 UTC, Andoran90 approved these changes

2023-11-09 08:07 UTC, tureck1y approved these changes

2023-11-09 08:12 UTC, merged