Ios 4704 add binding for action manage tokens list
tangem/tangem-app-ios-old pull request #2271
Opened 2023-10-19 07:35 UTC by skibinalexander

Реализован биндинг, для корректного обновления списка токенов на экране поиска, если мы сделали изменения на экране выбора токенов для кошелька.

2023-10-23 08:46 UTC, megakoko commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkSelectorCoordinator.swift
> +        var delegate: ManageTokensNetworkSelectorViewModelDelegate?
Можно let?

2023-10-23 08:46 UTC, megakoko commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkSelectorViewModel.swift
>  // MARK: - Settings
Давай в отдельный файл вынесем

2023-10-23 09:34 UTC, skibinalexander commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkSelectorCoordinator.swift
> +        var delegate: ManageTokensNetworkSelectorViewModelDelegate?
> Можно let?

Так опционал же, тут наверное и слабым его надо сделать ...

2023-10-23 09:34 UTC, skibinalexander commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkSelectorViewModel.swift
>  // MARK: - Settings
> Давай в отдельный файл вынесем

Да окей сделаю

2023-10-23 09:35 UTC, megakoko commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkSelectorCoordinator.swift
> +        var delegate: ManageTokensNetworkSelectorViewModelDelegate?
Это Options же, они недолно живут

2023-10-23 11:45 UTC, megakoko approved these changes, later dismissed

2023-10-25 15:40 UTC, tureck1y requested changes
Я вижу сейчас две проблемы:
- Обновление экрана через делегат происходит при выходе, независимо от того были ли изменения
- Делегат загромождает конструкцию
- А что будет, если токен добавится в кошелек другим способом? Например через реферралку?

Мое предложение - отказаться от делегата и вместо этого подписаться на
UserTokenListManager.userTokensPublisher от всех кошельков. Тогда при любом изменении, экран будет в правильном состоянии

2023-10-25 19:52 UTC, skibinalexander commented
> Я вижу сейчас две проблемы:
> 
> * Обновление экрана через делегат происходит при выходе, независимо от того были ли изменения
> * Делегат загромождает конструкцию
> * А что будет, если токен добавится в кошелек другим способом? Например через реферралку?
> 
> Мое предложение - отказаться от делегата и вместо этого подписаться на UserTokenListManager.userTokensPublisher от всех кошельков. Тогда при любом изменении, экран будет в правильном состоянии

Ага спс, понял,  посмотрю подписку

2023-10-27 15:54 UTC, tureck1y reviewed
конфликт, в остальном ок

2023-10-27 16:22 UTC, tureck1y approved these changes

2023-10-30 08:11 UTC, megakoko approved these changes

2023-10-30 08:40 UTC, merged