IOS-4807: Refactoring quotes repository
tangem/tangem-app-ios-old pull request #2288
Opened 2023-10-20 11:57 UTC by Balashov152

2023-10-20 17:38 UTC, skibinalexander commented on Tangem/App/Services/WalletModelsManager/CommonWalletModelsManager.swift
> +        walletModelsPublisher
А тут не очень понял, точно ли в зоне ответственности WalletManager держать репозиторий на квоты, просто по коду мы везде отдельно запрашиваем

2023-10-20 19:49 UTC, Balashov152 commented on Tangem/App/Services/WalletModelsManager/CommonWalletModelsManager.swift
> +        walletModelsPublisher
Тут вообще надо подумать где эту подписку сделать
Мне надо что бы на каждое изменение WalletModel подписаться

2023-10-22 14:46 UTC, skibinalexander commented on Tangem/App/Services/WalletModelsManager/CommonWalletModelsManager.swift
> +        walletModelsPublisher
> Тут вообще надо подумать где эту подписку сделать
> Мне надо что бы на каждое изменение WalletModel подписаться

Ну в целом раз менеджер , значит норм аггрерировать состояния разного типа

2023-10-22 14:55 UTC, skibinalexander submitted a review, later dismissed

2023-10-25 16:19 UTC, tureck1y requested changes

2023-10-25 16:19 UTC, tureck1y commented on Tangem/App/ViewModels/WalletModel/WalletModel.swift
> -            .combineLatest(loadQuotes())
мы должны тут дергать апдейт обязательно

2023-10-25 16:19 UTC, tureck1y commented on Tangem/App/Services/WalletModelsManager/CommonWalletModelsManager.swift
> +        walletModelsPublisher
Это точно неправильное место. Это же менеджер walletModel и это его единственная ответственность. В моем понимании такой подписки быть не должно.  Где апдейт квот на пул-ту-рефреш? Зачем смотреть на добавление? Надо смотреть на апдейт. Тут вообще недоделано получается.

Каждая walletModel дергает апдейт квот у репы с квотами. Репа с квотами может эти апдейты аггрегировать с каким-то дебаунсом. walletModel сейчас держит подписку на репу, чтобы услышать обновления своей квоты.

Вот перенос подписки на выбранную валюту в репу это да

2023-10-30 15:13 UTC, ba1ashov commented on Tangem/App/ViewModels/WalletModel/WalletModel.swift
> -            .combineLatest(loadQuotes())
вернул

2023-10-30 15:13 UTC, Balashov152 commented
Вернул обнволения через PTR и сделал через debounce(0.3)

2023-10-30 15:15 UTC, ba1ashov commented on Tangem/App/Services/TokenQuotesRepository/CommonTokenQuotesRepository.swift
> +            .collect(debouncedTime: 0.3, scheduler: DispatchQueue.global())
Решил использовать `PassthroughSubject` и новый `decouncedCollector`
что бы не добавлять лишний стейт.

Модно сделать через `CurrentValueSubject` + обычный `debounce` но я так не смог решить когда очищать в нем `value`.

У `PassthroughSubject` `value` нет поэтому вся очередь собирается через `scan`

2023-10-30 15:19 UTC, Balashov152 commented on Tangem/App/Services/TokenQuotesRepository/CommonTokenQuotesRepository.swift
> +                change: quote.priceChange?.rounded(scale: 1),
поменял здесь округление на 1 так как на экране округляем для одного знака

2023-10-30 20:50 UTC, skibinalexander commented on Tangem/Common/Extensions/Combine/DebouncedCollector.swift
> +    struct DebouncedCollector<Upstream: Publisher, S: Scheduler>: Publisher {
Может доку докинем небольшую, чтобы не вчитываться в код?

2023-10-30 20:56 UTC, skibinalexander commented on Tangem/App/Services/TokenQuotesRepository/CommonTokenQuotesRepository.swift
>              .replaceError(with: [])
Может ошибку тоже как нибудь залогируем? или она логируется на уровне сервиса?

2023-11-01 13:34 UTC, tureck1y commented on Tangem/App/Services/TokenQuotesRepository/CommonTokenQuotesRepository.swift
> +                change: quote.priceChange?.rounded(scale: 1),
Лучше все же не округлять в моделях. Это же уже логика крана

2023-11-01 13:47 UTC, tureck1y commented on Tangem/App/Services/TokenQuotesRepository/CommonTokenQuotesRepository.swift
> +        AppSettings.shared.$selectedCurrencyCode
Я добавлял тут
.delay(for: 0.3, scheduler: DispatchQueue.main) из-за willChange. Тут ниже будет старый код валюты?

2023-11-01 14:11 UTC, Balashov152 commented on Tangem/App/Services/TokenQuotesRepository/CommonTokenQuotesRepository.swift
> +        AppSettings.shared.$selectedCurrencyCode
Я сделал 0.5 сейчас, это помогает если часто щелкать на экране валют, что бы лишнего не уходило

2023-11-01 14:12 UTC, Balashov152 commented on Tangem/App/Services/TokenQuotesRepository/CommonTokenQuotesRepository.swift
>              .replaceError(with: [])
Добавил ✅

2023-11-01 14:12 UTC, Balashov152 commented on Tangem/Common/Extensions/Combine/DebouncedCollector.swift
> +    struct DebouncedCollector<Upstream: Publisher, S: Scheduler>: Publisher {
Добавил ✅

2023-11-01 14:13 UTC, Balashov152 commented on Tangem/App/Services/TokenQuotesRepository/CommonTokenQuotesRepository.swift
> +                change: quote.priceChange?.rounded(scale: 1),
Убрал вообще округление, раньше проблема была с определением 0.0% и серого цвета )
Сейчас если с API 0.000052 на экране было как +0.0%, сейчас это ок

2023-11-01 15:27 UTC, tureck1y commented on Tangem/App/Services/TokenQuotesRepository/CommonTokenQuotesRepository.swift
> +        AppSettings.shared.$selectedCurrencyCode
Debounce получается тут как delay работает?

2023-11-01 16:11 UTC, Balashov152 commented on Tangem/App/Services/TokenQuotesRepository/CommonTokenQuotesRepository.swift
> +        AppSettings.shared.$selectedCurrencyCode
Debounce отменяет цепочку если получил новое значение в течении 0.5 секунды, и пришлет только последнее.

Delay просто задерживает значение на 0.5, то если отправить два значение одновременно, то придет тоже два, просто через 0.5 секунды

2023-11-01 16:57 UTC, tureck1y approved these changes

2023-11-02 11:54 UTC, skibinalexander approved these changes

2023-11-02 13:30 UTC, merged