IOS-4901 Move analytics event on right path coordinator
tangem/tangem-app-ios-old pull request #2304
Opened 2023-10-24 07:35 UTC by skibinalexander

Не логировалось событие открытие онбординга из AppSettings, перенес в Coordinator онбординга, чтобы точно ивент не терялся

2023-10-24 07:41 UTC, megakoko submitted a review, later dismissed

2023-10-24 18:44 UTC, tureck1y requested changes
Analytics.log(.onboardingStarted) тогда нужно подчистить в остальных местах

2023-10-24 20:43 UTC, skibinalexander commented
> onboardingStarted

Да, спасибо, не проверил что еще есть ... :(

2023-10-24 20:45 UTC, skibinalexander commented
> Analytics.log(.onboardingStarted) тогда нужно подчистить в остальных местах

Да, спасибо, не проверил что еще есть ...

2023-10-25 07:10 UTC, skibinalexander commented
@tureck1y готово

2023-10-25 07:25 UTC, megakoko approved these changes

2023-10-25 08:04 UTC, tureck1y approved these changes

2023-10-25 08:27 UTC, merged