IOS-4782 Add `InformationHiddenBalancesSheet` showing logic
tangem/tangem-app-ios-old pull request #2313
Opened 2023-10-25 13:12 UTC by Balashov152

2023-10-25 16:40 UTC, tureck1y requested changes

2023-10-25 16:40 UTC, tureck1y commented on Tangem/Modules/InformationHiddenBalances/InformationHiddenBalancesViewModel.swift
> +        coordinator.dismissInformationHiddenBalances(forever: true)
а зачем передавать эту булку через много слоев, если можно прям тут в UserDefault записать?

2023-10-25 16:40 UTC, tureck1y commented on Tangem/App/Services/SensitiveTextVisibilityService/SensitiveTextVisibilityService.swift
> +    @Published var informationHiddenBalancesViewModel: InformationHiddenBalancesViewModel?
Cтранно, что сервис держит вью модель. Как будто бы должно быть наоборот. В AppCoordinator есть вьюмодель, как обычно + подписка на сервис, чтобы показать шит.

Ну либо сервис показывает сам через AppPresenter, как это делает WalletConnect

2023-10-26 14:35 UTC, Balashov152 commented on Tangem/Modules/InformationHiddenBalances/InformationHiddenBalancesViewModel.swift
> +        coordinator.dismissInformationHiddenBalances(forever: true)
что то подумал что лучше все в сервисе держать, ща подумаю еще

2023-10-26 17:40 UTC, Balashov152 commented on Tangem/App/Services/SensitiveTextVisibilityService/SensitiveTextVisibilityService.swift
> +            .store(in: &bag)
вот из за этой логики захотелось оставить все в сервисе

2023-10-26 17:41 UTC, Balashov152 commented on Tangem/App/Services/SensitiveTextVisibilityService/SensitiveTextVisibilityService.swift
> +    @Published var informationHiddenBalancesViewModel: InformationHiddenBalancesViewModel?
Переименовал по ViewModel, хочется как то сделать всю логику в одном месте, можно будет созвониться, вместе подумать. 
Через подписку не очень, так как логика в координаторе появляется
и плюс надо еще включать/выключать сервис. Что бы пока sheet горит, балансы нельзя было скрыть

2023-10-26 17:42 UTC, Balashov152 commented
Чуть переименовал, и перенес в MainCordinator что бы на Welcome не срабатывало

2023-10-27 16:01 UTC, tureck1y commented on Tangem/App/Services/SensitiveTextVisibilityService/SensitiveTextVisibilityService.swift
> +    @Published var informationHiddenBalancesViewModel: InformationHiddenBalancesViewModel?
Да вроде норм. Надеюсь шит не отвалится, если его реализация поменяется

2023-10-27 16:01 UTC, tureck1y approved these changes

2023-10-27 17:26 UTC, Balashov152 commented on Tangem/App/Services/SensitiveTextVisibilityService/SensitiveTextVisibilityService.swift
> +    @Published var informationHiddenBalancesViewModel: InformationHiddenBalancesViewModel?
ну если уйдет оттуда UIViewController то надо будет переделывать

UIHostingController -> BottomSheetModifier ->  UIHostingController -> BottomSheetContainer -> InformationHiddenBalancesView
сейчас первый пункт пропущен )

Не хотелось создавать UIHostingController для того что бы обернуть в еще один

2023-10-30 15:29 UTC, skibinalexander approved these changes

2023-10-30 15:29 UTC, merged