IOS-4943 make settings for manage tokens and other entity
tangem/tangem-app-ios-old pull request #2315
Opened 2023-10-25 20:03 UTC by skibinalexander

@megakoko Нужна модель настроек, чтобы код не дублировать нужно было вынести эту структуру данных + решили добавить фабрику для того чтобы конфигурировать из CardViewModel

2023-10-26 07:54 UTC, megakoko commented on Tangem/Modules/ManageTokens/Settings/ManageTokensSettingsFactory.swift
> +            hdWalletsSupported: cardViewModel?.userWallet.isHDWalletAllowed ?? false,
давай как в MultiWalletMainContentViewModel.openManageTokens

через userwalletmodel

и дукалиса удалять

2023-10-26 08:39 UTC, tureck1y commented on Tangem/Modules/ManageTokens/Settings/ManageTokensSettingsFactory.swift
> +            hdWalletsSupported: cardViewModel?.userWallet.isHDWalletAllowed ?? false,
только не надо все CVM передавать

2023-10-26 11:17 UTC, skibinalexander commented on Tangem/Modules/ManageTokens/Settings/ManageTokensSettingsFactory.swift
> +            hdWalletsSupported: cardViewModel?.userWallet.isHDWalletAllowed ?? false,
> только не надо все CVM передавать

Да, обсудили с @megakoko как правильней

2023-10-26 12:34 UTC, megakoko commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkSelectorViewModel.swift
> +    let settingsFactory = ManageTokensSettingsFactory()
private

2023-10-26 12:34 UTC, megakoko commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkSelectorViewModel.swift
> +        settings = settingsFactory.make(from: userWalletRepository.selectedModel)
Надо еще при выборе кошелька обновлять

2023-10-26 13:08 UTC, megakoko commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkSelectorViewModel.swift
> -        userWalletRepository.setSelectedUserWalletId(userWalletId, reason: .userSelected)
Давай это оставим для другого МРа, надо будет переделать

2023-10-26 13:29 UTC, skibinalexander commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkSelectorViewModel.swift
> -        userWalletRepository.setSelectedUserWalletId(userWalletId, reason: .userSelected)
Да, окей верну

2023-10-26 13:37 UTC, megakoko approved these changes, later dismissed

2023-10-26 15:01 UTC, tureck1y commented on Tangem/Modules/ManageTokens/Settings/ManageTokensSettingsFactory.swift
> +        guard let userWalletModel = userWalletModel else {
Странно выглядит. Надо просто убрать опционал

2023-10-26 15:01 UTC, tureck1y commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkSelectorViewModel.swift
> +    private let settingsFactory = ManageTokensSettingsFactory()
я бы создавал in place

2023-10-26 15:01 UTC, tureck1y commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkSelectorViewModel.swift
> +    private var settings: ManageTokensSettings?
а зачем вообще их тут держать и обновлять?

2023-10-26 16:23 UTC, skibinalexander commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkSelectorViewModel.swift
> +    private var settings: ManageTokensSettings?
Ну параметры этой модели нужны в проверках , это сущность как union идет

2023-10-26 16:24 UTC, skibinalexander commented on Tangem/Modules/ManageTokens/Settings/ManageTokensSettingsFactory.swift
> +        guard let userWalletModel = userWalletModel else {
Опционал смогу убрать , когда докину логику по 1ому выбранному кошельку с учетом того что проговорили сегодня

2023-10-26 16:34 UTC, tureck1y commented on Tangem/Modules/ManageTokens/Settings/ManageTokensSettingsFactory.swift
> +        guard let userWalletModel = userWalletModel else {
Ну тут даже с точки зрения проектирования api. Зачем метод принимает nil, если сразу же выходит из него, ничего не делая

2023-10-26 16:34 UTC, tureck1y commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkSelectorViewModel.swift
> +    private var settings: ManageTokensSettings?
А почему var? Что может поменяться?

2023-10-26 18:31 UTC, skibinalexander commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkSelectorViewModel.swift
> +    private var settings: ManageTokensSettings?
Так , если переключать UserWalletModel , мы должны брать по новому конфигу карты

2023-10-26 18:32 UTC, skibinalexander commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkSelectorViewModel.swift
> +    private var settings: ManageTokensSettings?
И список блокчейнов и лонг хеши

2023-10-27 08:41 UTC, skibinalexander commented
@tureck1y сделал computed, сделал так чтобы, корректно брался userWalletModel, настройки через guard дергаются один раз в проверке токена

userWalletRepository.setSelectedUserWalletId(userWalletId, reason: .userSelected) уберу в рамках следующего МР, который правильно будет филить список кошельков и подкидывать первый правильно выбранный

2023-10-27 15:50 UTC, tureck1y requested changes

2023-10-27 15:50 UTC, tureck1y commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkSelectorViewModel.swift
> +            existingCurves: (userWalletModel as? CardViewModel)?.card.walletCurves ?? []
CardViewModel больше не используем явно нигде. Только через UserWalletModel

2023-10-27 16:19 UTC, skibinalexander commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkSelectorViewModel.swift
> +            existingCurves: userWalletModel.userWallet.card.walletCurves
@tureck1y тоже поменял

2023-10-27 20:55 UTC, skibinalexander commented on Tangem/App/Models/UserWallet/UserWalletConfig.swift
> +    var walletCurves: [EllipticCurve] { get }
Добавил по просьбе @tureck1y чтобы сразу делать правильно

2023-10-27 20:56 UTC, skibinalexander commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkSelectorViewModel.swift
> -        userWalletRepository.setSelectedUserWalletId(userWalletId, reason: .userSelected)
Все таки сразу уберу потому МР чуть больше уже идет , сразу неправильную логику уберу

2023-10-30 14:42 UTC, tureck1y approved these changes

2023-10-30 16:20 UTC, megakoko approved these changes

2023-10-30 16:22 UTC, merged