Ios 5004 make provider correct selector wallet
tangem/tangem-app-ios-old pull request #2338
Opened 2023-11-01 15:19 UTC by skibinalexander

Сделан локальный по отношению к модулю провайдер который помогает в фильтрации кошельков которые доступны для выбора и выкидывает первый кошелек который мы должны показывать в качестве выбранного. 

Необходимость провайдера Обусловлена тем что он также будет использоваться в кастомных токенах

@megakoko проверяет обязательно

2023-11-01 15:32 UTC, megakoko commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkSelectorViewModel.swift
> +        }
Лучше в другое место перенести. Я как пользователь этого кода не ожидаю что ты мне какие-то алерты будешь показывать сайд-эффектом

2023-11-01 15:32 UTC, megakoko commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkSelectorViewModel.swift
> +        }
Тут не надо ничего сбрасывать?

2023-11-01 15:32 UTC, megakoko commented on Tangem/Modules/ManageTokensNetworkSelector/WalletSelector/WalletSelectorProvider.swift
fetch — это про сетевые запросы скорее. Давай уберем и сделаем через проперти — var availableWallets, currentWallet — давай везде сделаем через UserWalletModel чтобы интерфейс одинаковый был

В общем списке кошельков может не оказаться current судя по коду — см. isMultiWallet. Надо сделать без копипасты логики филттрования

2023-11-01 16:13 UTC, skibinalexander commented on Tangem/Modules/ManageTokensNetworkSelector/WalletSelector/WalletSelectorProvider.swift
Да согласен переделаю

2023-11-01 17:43 UTC, skibinalexander commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkSelectorViewModel.swift
> +        }
> Тут не надо ничего сбрасывать?

Ситуация исключительная полагаю, ибо на главной будет все равно выбранный кошелек, но добавлю Алерт стандартный

2023-11-01 17:47 UTC, skibinalexander commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkSelectorViewModel.swift
> +        }
> Лучше в другое место перенести. Я как пользователь этого кода не ожидаю что ты мне какие-то алерты будешь показывать сайд-эффектом

Не очень понял суть, это основная ViewModel экрана которая отвечает за бизнес логику, на нем же генерируется Алерт

2023-11-01 18:07 UTC, skibinalexander commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkSelectorViewModel.swift
> +        }
> Лучше в другое место перенести. Я как пользователь этого кода не ожидаю что ты мне какие-то алерты будешь показывать сайд-эффектом

 private func fillWalletSelector() {
        guard let currentUserWalletModel = walletSelectorProvider.currentWalletSelected() else {
            alert = AlertBinder(title: "TODO:", message: "wallet does not support more than one network")
            return
        }

        currentWalletName = currentUserWalletModel.userWallet.name

        // TODO: - Need display alert with string "wallet does not support more than one network" wait localize IOS-4902

        if !currentUserWalletModel.isMultiWallet {
            alert = AlertBinder(title: "TODO:", message: "wallet does not support more than one network")
        }
    }

2023-11-02 08:17 UTC, megakoko commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkSelectorViewModel.swift
> +        }
Функция называется "заполни селектор кошельков" и при этом показывает алерт, если б init называлась или doEverything то другое дело

2023-11-02 08:19 UTC, skibinalexander commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkSelectorCoordinator.swift
> +        userWallets: [UserWalletModel],
тут все таки userWallets -> userWalletModels переименовать

2023-11-02 08:20 UTC, megakoko commented on Tangem/Modules/ManageTokensNetworkSelector/WalletSelector/WalletSelectorProvider.swift
Проблема-то осталась. Если у тебя в приложении одни только ноуты, то список будет пустой, но current при этом будет ненулевым.

2023-11-02 08:30 UTC, skibinalexander commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkSelectorViewModel.swift
> +        }
> Функция называется "заполни селектор кошельков" и при этом показывает алерт, если б init называлась или doEverything то другое дело

initCurrentWalletSelectorOrDisplayAlert -?

2023-11-02 08:32 UTC, skibinalexander commented on Tangem/Modules/ManageTokensNetworkSelector/WalletSelector/WalletSelectorProvider.swift
> Проблема-то осталась. Если у тебя в приложении одни только ноуты, то список будет пустой, но current при этом будет ненулевым.

Так а проблема в чем не очень понимаю, предложение какое ?

2023-11-02 08:34 UTC, megakoko commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkSelectorViewModel.swift
> +        }
Лучше просто разнести по разным методам

2023-11-02 08:34 UTC, skibinalexander commented on Tangem/Modules/ManageTokensNetworkSelector/WalletSelector/WalletSelectorProvider.swift
То что мы туда current передаем и список пустой ?

2023-11-02 08:42 UTC, skibinalexander commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkSelectorViewModel.swift
> +        }
> Лучше просто разнести по разным методам

Ну в целом странно немного, мы же не всегда бьем методы по единичной функциональности, но ладно вынесу

2023-11-07 08:33 UTC, megakoko commented on Tangem/App/Services/WarningsService/Warnings/WarningEvent.swift
> +            return "\(blockchainDescription.capitalizingFirstLetter()) \(Localization.commonOnly)"
Надо сделать через нормальную текстовку. Мы не знаем с какой стороны название блокчейна будет в русском, белорусском, арабском

2023-11-07 08:33 UTC, megakoko commented on Tangem/Resources/Localizations/ru.lproj/Localizable.strings
> +"common_only" = "только";
"Bitcoin только"?

2023-11-07 08:33 UTC, megakoko commented on Tangem/Resources/Localizations/zh-Hant.lproj/Localizable.strings
> +"common_only" = "только";
Сначала заводим текстовки в локалайз, из локалайза делаем экспорт в код. НЕ наоборот

2023-11-07 08:33 UTC, megakoko commented on Tangem/Modules/ManageTokensNetworkSelector/WalletSelector/WalletSelectorProvider.swift
> +    }
У меня в кастомных токенах нет coinID, если тут нужен — давай сделаем опциональным

2023-11-07 08:33 UTC, megakoko commented on Tangem/Modules/ManageTokensNetworkSelector/WalletSelector/WalletSelectorProvider.swift
> +    func listWalletForSelector(for coinId: String) -> [UserWalletModel] {
Давай назоваем `userWalletModels()`, `currentUserWalletModel()`

2023-11-07 08:33 UTC, megakoko commented on Tangem/Modules/ManageTokensNetworkSelector/WalletSelector/WalletSelectorProvider.swift
> +    }
Тут точно через && надо?

Давай лучше инвертируем все и назовем selectedUserWalletModelSupports(coinId: ...) если я правильно понимаю

Зачем передаем userWalletModels если проверяем текущий кошелек?

2023-11-07 08:33 UTC, megakoko commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkSelectorViewModel.swift
> +    @Published var isNeedDisplaySupportsNotificationInput: Bool = false
showWalletSelector

Второе можно убрать, сделать notificationinput опциональным

2023-11-07 08:33 UTC, megakoko commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkSelectorViewModel.swift
> +            for: .walletSupportsOnlyOneCurrency(blockchainDescription: coinId),
Почему coinID передаем в уведомление и текстовку?

2023-11-07 08:33 UTC, megakoko commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkSelectorViewModel.swift
> +    var supportsNotificationInput: NotificationViewInput {
Давай назовем просто notificationInput и сделаем опциональным

2023-11-07 09:17 UTC, skibinalexander commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkSelectorViewModel.swift
> +    @Published var isNeedDisplaySupportsNotificationInput: Bool = false
> showWalletSelector
> 
> Второе можно убрать, сделать notificationinput опциональным

А что с неймингом не так? мы же флаг определяем префикс как раз подразумевает bool значение

2023-11-07 09:17 UTC, skibinalexander commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkSelectorViewModel.swift
> +    @Published var isNeedDisplaySupportsNotificationInput: Bool = false
> > showWalletSelector
> > Второе можно убрать, сделать notificationinput опциональным
> 
> А что с неймингом не так? мы же флаг определяем префикс как раз подразумевает bool значение

тут либо 2 флага либо enum потому как может быть 3 состояния:

- показан выбор кошельков
- показана нотификация
- ничего не показывается

2023-11-07 09:19 UTC, skibinalexander commented on Tangem/Modules/ManageTokensNetworkSelector/WalletSelector/WalletSelectorProvider.swift
> +    func isCurrentSelectedNonMultiWalletWallet(by coinId: String, with userWalletModels: [UserWalletModel]) -> Bool {
WalletWallet - ошибка поправлю

2023-11-07 09:22 UTC, skibinalexander commented on Tangem/Modules/ManageTokensNetworkSelector/WalletSelector/WalletSelectorProvider.swift
> +    }
Сюда придет список доступных кошельков для выбора, который определился в init вью модели.

Логика такая, если сейчас на главном экране выбрана одна валютка, и при этом нет ни одной карты мультивалютной, и при этомодновалютка выбрана по текущей валюте одновалютной карты

2023-11-07 09:23 UTC, skibinalexander commented on Tangem/Resources/Localizations/zh-Hant.lproj/Localizable.strings
> +"common_only" = "только";
> Сначала заводим текстовки в локалайз, из локалайза делаем экспорт в код. НЕ наоборот

Так и сделано же

2023-11-07 09:29 UTC, megakoko commented on Tangem/Resources/Localizations/zh-Hant.lproj/Localizable.strings
> +"common_only" = "только";
Почему тогда в китайском файле русская текстовка?

2023-11-07 09:30 UTC, megakoko commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkSelectorViewModel.swift
> +    @Published var isNeedDisplaySupportsNotificationInput: Bool = false
> А что с неймингом не так? мы же флаг определяем префикс как раз подразумевает bool значение

isNeedDisplay = show, проще читается

2023-11-07 09:31 UTC, megakoko commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkSelectorViewModel.swift
> +    @Published var isNeedDisplaySupportsNotificationInput: Bool = false
> тут либо 2 флага либо enum потому как может быть 3 состояния:

Ну... можно оставить флаг для селектора и опциональное свойство для уведомления. Минус один флаг

2023-11-07 11:08 UTC, skibinalexander commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkSelectorViewModel.swift
> +    @Published var isNeedDisplaySupportsNotificationInput: Bool = false
> > тут либо 2 флага либо enum потому как может быть 3 состояния:
> 
> Ну... можно оставить флаг для селектора и опциональное свойство для уведомления. Минус один флаг

Окей переименую, и сделал через опциональный инпут нотификации и флаг

2023-11-07 11:55 UTC, skibinalexander commented on Tangem/Modules/ManageTokens/ManageTokensCoordinator.swift
> +    func openTokenSelector(coinModel: CoinModel) {
@tureck1y пришлось вернуть кидать CoinModel потому что для нотификации (по дизайну) требуется и название блокчейна и символ валюты

2023-11-07 11:57 UTC, skibinalexander commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkSelectorViewModel.swift
> +                        coinModel.name,
@tureck1y вот здесь нужны эти поля

2023-11-07 11:59 UTC, skibinalexander commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkSelectorViewModel.swift
> +            for: .walletSupportsOnlyOneCurrency(blockchainDescription: coinId),
> Почему coinID передаем в уведомление и текстовку?

Вынес в текстовые как обсудили

2023-11-07 16:20 UTC, tureck1y requested changes

2023-11-07 16:20 UTC, tureck1y commented on Tangem/App/Services/UserWalletRepository/CommonUserWalletRepository.swift
> +    var selectedUserModelModel: UserWalletModel? {
selectedUserModelModelModelModel))

2023-11-07 16:20 UTC, tureck1y commented on Tangem/App/Services/WarningsService/Warnings/WarningEvent.swift
> +    case walletSupportsOnlyOneCurrency(description: String)
SingleCurrencyWallet?

2023-11-07 16:20 UTC, tureck1y commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkSelectorView.swift
> +            Text(viewModel.currentWalletName ?? "")
Это уже логика и должна быть во ViewModel

2023-11-07 16:20 UTC, tureck1y commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkSelectorViewModel.swift
> +        selectedUserWalletModel = userWalletRepository.models.first(where: { $0.userWalletId.value == userWalletId })
Появилась же поперти в репозитории для этого?

2023-11-07 16:20 UTC, tureck1y commented on Tangem/Modules/ManageTokensNetworkSelector/WalletSelector/WalletSelectorProvider.swift
> +    /// Return flag if currency selected UserWalletModel is single currency wallet
currently selected?

2023-11-07 16:20 UTC, tureck1y commented on Tangem/Modules/ManageTokensNetworkSelector/WalletSelector/WalletSelectorProvider.swift
> +    /// Return flag if currency selected UserWalletModel is single currency wallet
Из названия метода совсем непонятно что он делает
isCurrentSelectedNonMultiUserWalletModel

Честно говоря я не очень понимаю назначение этого класса. Все извне передается, стейта нет, зачем он нужен?

Селектор кошельков будет появляться то тут то там, его надо сделать общим и может настройки какие-то передавать? 

Например, он инициализируется из репозитория, но стейт текущего выбранного кошелька у него свой и никак репозиторий не аффектит.

2023-11-07 16:21 UTC, skibinalexander commented on Tangem/App/Services/UserWalletRepository/CommonUserWalletRepository.swift
> +    var selectedUserModelModel: UserWalletModel? {
> selectedUserModelModelModelModel))

угу, при подтягивании задублировал ....

2023-11-07 16:24 UTC, skibinalexander commented on Tangem/Modules/ManageTokensNetworkSelector/WalletSelector/WalletSelectorProvider.swift
> +    /// Return flag if currency selected UserWalletModel is single currency wallet
> Из названия метода совсем непонятно что он делает isCurrentSelectedNonMultiUserWalletModel
> 
> Честно говоря я не очень понимаю назначение этого класса. Все извне передается, стейта нет, зачем он нужен?
> 
> Селектор кошельков будет появляться то тут то там, его надо сделать общим и может настройки какие-то передавать?
> 
> Например, он инициализируется из репозитория, но стейт текущего выбранного кошелька у него свой и никак репозиторий не аффектит.

@megakoko посмотри пожалуйста, как раз с тобой говорили что может сделать его более нагруженным по логике , чем настраивать из вне?

2023-11-07 16:30 UTC, skibinalexander commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkSelectorViewModel.swift
> +        selectedUserWalletModel = userWalletRepository.models.first(where: { $0.userWalletId.value == userWalletId })
> Появилась же поперти в репозитории для этого?

@tureck1y  Дело в том что, в репозитории выбранный кошелек зависит от главной, что понятно, мы глобально меняем Стейт, а здесь выбранный кошелек может по сути быть только мультивалюткой пройдя все фильтрации провайдера

2023-11-07 16:32 UTC, skibinalexander commented on Tangem/Modules/ManageTokensNetworkSelector/WalletSelector/WalletSelectorProvider.swift
> +    /// Return flag if currency selected UserWalletModel is single currency wallet
@tureck1y 

Я как раз как-то и предполагал , чтобы эту вьюшку наградить логикой, чтобы она откидывала список и выбранный кошелек и уже внешний потребитель подстраивал UI, сошлись на том чтобы сделать это через дополнительную локальную сущность привязанную к модулю. 

Отдельно сущность вынесена потому-что требуется переиспользование логики

2023-11-07 16:36 UTC, skibinalexander commented on Tangem/App/Services/WarningsService/Warnings/WarningEvent.swift
> +    case walletSupportsOnlyOneCurrency(description: String)
> SingleCurrencyWallet?

В целом да можно переименовать

2023-11-07 16:42 UTC, tureck1y commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkSelectorViewModel.swift
> +        selectedUserWalletModel = userWalletRepository.models.first(where: { $0.userWalletId.value == userWalletId })
Большое количество мест с похожим кодом, где идет фильтр по моделям. Надо собрать все в одном месте по возможности. Где единый источник правды?

2023-11-07 16:44 UTC, tureck1y commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkSelectorViewModel.swift
> +        selectedUserWalletModel = userWalletRepository.models.first(where: { $0.userWalletId.value == userWalletId })
Условно говоря, вот сделал провайдера, пусть он и отдаем готовый список и держит выбранный cтейт. Все вот эти поиски и фильтры в других местах надо убрать и все делать через него

2023-11-07 16:44 UTC, skibinalexander commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkSelectorViewModel.swift
> +        selectedUserWalletModel = userWalletRepository.models.first(where: { $0.userWalletId.value == userWalletId })
> Большое количество мест с похожим кодом, где идет фильтр по моделям. Надо собрать все в одном месте по возможности. Где единый источник правды?

Может тебя название смутило? Просто тут как бы получается кошелек не совсем выбирается относительно репозитория, а выбирается локально относительно модуля

2023-11-07 16:45 UTC, skibinalexander commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkSelectorViewModel.swift
> +        selectedUserWalletModel = userWalletRepository.models.first(where: { $0.userWalletId.value == userWalletId })
> Условно говоря, вот сделал провайдера, пусть он и отдаем готовый список и держит выбранный cтейт. Все вот эти поиски и фильтры в других местах надо убрать и все делать через него

Да так в целом понятнее что имеешь в виду

2023-11-08 20:18 UTC, skibinalexander commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkDataSource.swift
> +    public func isSelectedNonMultiUserWalletModelForCoinId() -> Bool {
Переименовать

2023-11-13 11:28 UTC, tureck1y requested changes
Пока что очень плохо, без меня не мержить

2023-11-13 11:28 UTC, tureck1y commented on Tangem/App/Services/WarningsService/Warnings/WarningEvent.swift
> +    case failedSupportedBlockchainByWallets
неудачные название, непонятно что за ворнинг

2023-11-13 11:28 UTC, tureck1y commented on Tangem/App/Models/UserWallet/UserWalletConfig.swift
> +    var cardId: String { get }
CardId не должен торчать из конфига ни при каких обстоятельствах

2023-11-13 11:28 UTC, tureck1y commented on Tangem/Modules/ManageTokens/ManageTokensSettings.swift
> +    let isAvailableTokenSelection: Bool
Не очень понимаю как это будет работать. Менеджер токенjd живет сам по себе и должен сам уметь настраиваться

2023-11-13 11:28 UTC, tureck1y commented on Tangem/Resources/Localizations/zh-Hant.lproj/Localizable.strings
> +"manage_tokens_wallet_does_not_supported_blockchain" = "Wallet Incompatible with selected Coin";
Wallet Incompatible - с большой буквы I

2023-11-13 11:28 UTC, tureck1y commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkSelectorCoordinator.swift
> +    func openWalletSelectorModule(with dataSource: WalletSelectorDataSource) {
Module нигде не пишем

2023-11-13 11:28 UTC, tureck1y commented on Tangem/Modules/ManageTokensNetworkSelector/WalletSelector/WalletSelectorViewModel.swift
> +    func fillItemViewModels() {
private?

2023-11-13 11:28 UTC, tureck1y commented on Tangem/Modules/ManageTokensNetworkSelector/WalletSelector/WalletSelectorViewModel.swift
> +            WalletSelectorItemViewModel(
почему dataSource этого экрана не отдает сразу в нужном формате?

2023-11-13 11:28 UTC, tureck1y commented on Tangem/Modules/ManageTokensNetworkSelector/WalletSelector/WalletSelectorItemViewModel.swift
> +        userWalletModel: UserWalletModel,
А в этой ячейке правда нужна вся огромная UserWalletModel целиком? У нас экраны экраны без нее работают. Логика по загрузке картинки уже где-то есть, ее нельзя пошарить?

2023-11-13 11:28 UTC, tureck1y commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkSelectorViewModel.swift
> +    private var selectedUserWalletModel: UserWalletModel?
вроде бы есть dataSorce, почему тогда существует еще одна переменная тут? Где источник правды?

2023-11-13 11:28 UTC, tureck1y commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkSelectorViewModel.swift
> +        networkDataSource.prepare()
Создали датасорс, потом вызвали абсолютно внешний bind, а потом вызывали prepare??? Что-то совсем не то

2023-11-13 11:28 UTC, tureck1y commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkDataSource.swift
> +    func prepare() {
почему это не делается в конструкторе?

2023-11-13 11:28 UTC, tureck1y commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkDataSource.swift
> +    public func isExistSingleCurrencyWalletSupportedCoinId() -> Bool {
насколько я понимаю, в этот жатасорс сингл карренси вообще попасть не может. Мы вроде бы иную реализацию обсуждали с двумя датасорсами

2023-11-13 12:41 UTC, skibinalexander commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkSelectorViewModel.swift
> +        networkDataSource.prepare()
> Создали датасорс, потом вызвали абсолютно внешний bind, а потом вызывали prepare??? Что-то совсем не то

Как раз таки обсуждали что в дата сорсе живет паблишер, мы на него подписываемся

2023-11-13 12:42 UTC, skibinalexander commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkSelectorViewModel.swift
> +    private var selectedUserWalletModel: UserWalletModel?
> вроде бы есть dataSorce, почему тогда существует еще одна переменная тут? Где источник правды?

Да тут ты прав, это действительно проговаривали, прикапывать на уровне этой ViewModel лишее

2023-11-13 12:42 UTC, skibinalexander commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkSelectorViewModel.swift
> +    private var selectedUserWalletModel: UserWalletModel?
> > вроде бы есть dataSorce, почему тогда существует еще одна переменная тут? Где источник правды?
> 
> Да тут ты прав, это действительно проговаривали, прикапывать на уровне этой ViewModel лишее

Просто тут значение как раз сетится из паблишера

2023-11-13 12:44 UTC, skibinalexander commented on Tangem/Resources/Localizations/zh-Hant.lproj/Localizable.strings
> +"manage_tokens_wallet_does_not_supported_blockchain" = "Wallet Incompatible with selected Coin";
> Wallet Incompatible - с большой буквы I

Текстовки добавил из требований, Леша, будет проходиться по ним, и при выгрузке они заменятся, другого варианта я пока предложить не могу

2023-11-13 12:56 UTC, skibinalexander commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkDataSource.swift
> +    public func isExistSingleCurrencyWalletSupportedCoinId() -> Bool {
> > насколько я понимаю, в этот жатасорс сингл карренси вообще попасть не может. Мы вроде бы иную реализацию обсуждали с двумя датасорсами
> 
> Как раз таки говорили что сюда попадает для того чтобы не терчал репозиториий во ViewModel экрана

2023-11-13 13:19 UTC, skibinalexander commented on Tangem/Modules/ManageTokensNetworkSelector/WalletSelector/WalletSelectorItemViewModel.swift
> +        userWalletModel: UserWalletModel,
> А в этой ячейке правда нужна вся огромная UserWalletModel целиком? У нас экраны экраны без нее работают. Логика по загрузке картинки уже где-то есть, ее нельзя пошарить?

Обсуждали на звонке что UserWallet быть не должно, необходимо переделать на UserWalletModel

2023-11-13 13:21 UTC, skibinalexander commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkSelectorCoordinator.swift
> +    func openWalletSelectorModule(with dataSource: WalletSelectorDataSource) {
> Module нигде не пишем

Да, помню, не хотел лишние изменения тянуть и ренейм делал, код был померджен, чтобы не попало в лишний дифф

2023-11-13 13:22 UTC, skibinalexander commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkSelectorCoordinator.swift
> +    func openWalletSelectorModule(with dataSource: WalletSelectorDataSource) {
> > Module нигде не пишем
> 
> Да, помню, не хотел лишние изменения тянуть и ренейм делать, код был померджен, чтобы не попало в лишний дифф

2023-11-13 13:25 UTC, skibinalexander commented on Tangem/Modules/ManageTokensNetworkSelector/WalletSelector/WalletSelectorViewModel.swift
> +            WalletSelectorItemViewModel(
> почему dataSource этого экрана не отдает сразу в нужном формате?

Мы проговаривали что у этого микромодуля есть свой dataSource закрытый протоколом для переиспользования, и инджектим через инициализатор

2023-11-13 14:55 UTC, skibinalexander commented on Tangem/Modules/ManageTokens/ManageTokensSettings.swift
> +    let isAvailableTokenSelection: Bool
> Не очень понимаю как это будет работать. Менеджер токенjd живет сам по себе и должен сам уметь настраиваться

Мне нужно уметь дизейблить свитчеры по дизайну, сейчас условие такое , что свитчеры активны только когда есть кошелек где мы можем включить / выключить токены, и в случае если одновалютная карта поддерживает или не поддерживает токен.

ManageTokensSettings доступны как раз только в случае если есть хоть один кошелек для выбора. Сделал это в настройках потому что может появится еще условия для свитера, так выглядит гибче

2023-11-13 15:23 UTC, skibinalexander commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkDataSource.swift
> +    func prepare() {
> почему это не делается в конструкторе?

Там коммент при вызове функции есть, можно обсудить это как лучше сделать

2023-11-13 15:24 UTC, skibinalexander commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkDataSource.swift
> +                return walletCondition && userWalletModel.config.supportedBlockchains.contains(where: { $0.coinId == coinId })
@tureck1y на самом деле смущает немного это, потому что сюда переем CoinId а если будет USDT , как быть тогда

2023-11-13 15:26 UTC, skibinalexander commented on Tangem/App/Models/UserWallet/UserWalletConfig.swift
> +    var cardId: String { get }
> CardId не должен торчать из конфига ни при каких обстоятельствах

Эта нужно для реализации:

```
let artwork: CardArtwork
        if let artworkInfo = userWalletModel.userWallet.artwork {
            artwork = .artwork(artworkInfo)
        } else {
            artwork = .notLoaded
        }

        cardImageProvider.loadImage(
            cardId: userWalletModel.config.cardId,
            cardPublicKey: userWalletModel.userWallet.card.cardPublicKey,
            artwork: artwork
        )
        .sink { [weak self] loadResult in
            guard let self else { return }

            image = scaleImage(loadResult.uiImage, newHeight: imageHeight * UIScreen.main.scale)
        }
        .store(in: &bag)
```

На звонке обсудили, что нужно избавляться от UserWalletModel, при этом смотрел на реализацию:

UserWalletListCellViewModel

Если есть другая возможность загрузить изображение нужно обсудить как тогда

2023-11-13 15:27 UTC, skibinalexander commented on Tangem/App/Models/UserWallet/UserWalletConfig.swift
> +    var cardId: String { get }
> CardId не должен торчать из конфига ни при каких обстоятельствах

И опять таки , это за скоупом задачи как-то выходит

2023-11-13 15:29 UTC, skibinalexander commented on Tangem/Modules/ManageTokensNetworkSelector/WalletSelector/WalletSelectorItemViewModel.swift
> +        userWalletModel: UserWalletModel,
> А в этой ячейке правда нужна вся огромная UserWalletModel целиком? У нас экраны экраны без нее работают. Логика по загрузке картинки уже где-то есть, ее нельзя пошарить?

Переделывать полностью item за рамками задачи выходит как-то

2023-11-13 15:29 UTC, skibinalexander commented on Tangem/App/Services/WarningsService/Warnings/WarningEvent.swift
> +    case failedSupportedBlockchainByWallets
> неудачные название, непонятно что за ворнинг

Сделал rename

2023-11-13 15:40 UTC, skibinalexander commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkDataSource.swift
> +    public func isExistSingleCurrencyWalletSupportedCoinId() -> Bool {
> насколько я понимаю, в этот жатасорс сингл карренси вообще попасть не может. Мы вроде бы иную реализацию обсуждали с двумя датасорсами

Второй дата сорс показался избыточным , я об этом писал , кажется что достаточно обойтись вычисляемым свойством , также писал об этом

2023-11-13 17:16 UTC, tureck1y commented on Tangem/App/Models/UserWallet/UserWalletConfig.swift
> +    var cardId: String { get }
Ну переделка то здесь. Сделай загрузку картинок внутри UserWaleltModel

2023-11-13 17:17 UTC, tureck1y commented on Tangem/Resources/Localizations/zh-Hant.lproj/Localizable.strings
> +"manage_tokens_wallet_does_not_supported_blockchain" = "Wallet Incompatible with selected Coin";
главное не забыть это поправить, пингани всех кого нужно по опечатке

2023-11-13 17:17 UTC, tureck1y commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkSelectorCoordinator.swift
> +    func openWalletSelectorModule(with dataSource: WalletSelectorDataSource) {
Тогда надо отдельной задачей поправить обязательно

2023-11-13 17:18 UTC, skibinalexander commented on Tangem/Resources/Localizations/zh-Hant.lproj/Localizable.strings
> +"manage_tokens_wallet_does_not_supported_blockchain" = "Wallet Incompatible with selected Coin";
Есть на это тред

2023-11-13 17:18 UTC, skibinalexander commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkSelectorCoordinator.swift
> +    func openWalletSelectorModule(with dataSource: WalletSelectorDataSource) {
Сделал также изменения убрал

2023-11-13 17:19 UTC, tureck1y commented on Tangem/Modules/ManageTokensNetworkSelector/WalletSelector/WalletSelectorViewModel.swift
> +            WalletSelectorItemViewModel(
Тут тут маппишь из этого dataSource в WalletSelectorItemViewModel, используя данные из самого dataSource. Этот dataSource он конкретно для этого экрана так пусть и отдает уже готово все

2023-11-13 17:23 UTC, tureck1y commented on Tangem/Modules/ManageTokensNetworkSelector/WalletSelector/WalletSelectorItemViewModel.swift
> +        userWalletModel: UserWalletModel,
> UserWallet быть не должно, необходимо переделать на UserWalletModel

- Мы обсуждали, что не должно быть UserWallet.
- От UserWalletModel используется название, загрузка картинки и id (не уверен, что id тут вообще нужно,  Identifiable можно получить и без). Зачем передавать огромную сущность целиком?

2023-11-13 17:23 UTC, tureck1y commented on Tangem/Modules/ManageTokensNetworkSelector/WalletSelector/WalletSelectorItemViewModel.swift
> +        userWalletModel: UserWalletModel,
> Переделывать полностью item за рамками задачи выходит как-то

Ну заметили плохой код, почему бы сразу не поправить, либо надо было более точечно делить и выносить это в отдельный таск изначально. Откатывать нет смысла уже имхо

2023-11-13 17:25 UTC, tureck1y commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkSelectorViewModel.swift
> +        networkDataSource.prepare()
Дело не в том, что обсуждали, а это получается очень хрупко, с точки зрения проектирования кода. Не должно меняться поведение от перестановки строчек.

Я предлагал два датасорса. Один общий, на весь менеджер токены и один отдельный, настраиваемый под валюту

2023-11-13 17:26 UTC, tureck1y commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkDataSource.swift
> +    public func isExistSingleCurrencyWalletSupportedCoinId() -> Bool {
Нет не избыточный. У тебя тут код про Single currency на экране, где ее быть не может. Ответственности двух разных сущностей смешали в одно

2023-11-13 17:27 UTC, tureck1y commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkDataSource.swift
> +            let walletCondition = userWalletModel.isMultiWallet && !userWalletModel.isUserWalletLocked
мы обсуждали, что таких проверок везде быть не должно, только в одном месте

2023-11-13 17:28 UTC, tureck1y commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkDataSource.swift
> +                return walletCondition && userWalletModel.config.supportedBlockchains.contains(where: { $0.coinId == coinId })
Ну так видимо надо netwotkId передавать, нам же сеть нужна. Еще дополнительно вопрос как тогда будут обрабатываться угловой кейс с токсинами соланы

2023-11-13 17:38 UTC, skibinalexander commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkDataSource.swift
> +    public func isExistSingleCurrencyWalletSupportedCoinId() -> Bool {
Я не использую эту сущность на экране списка валют , дата сорс используется только на экране выбора токенов

2023-11-13 17:39 UTC, skibinalexander commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkDataSource.swift
> +    public func isExistSingleCurrencyWalletSupportedCoinId() -> Bool {
> Нет не избыточный. У тебя тут код про Single currency на экране, где ее быть не может. Ответственности двух разных сущностей смешали в одно

Фильтры не одни и те же получаются , для этих экранов , я тоже писал об этом

2023-11-13 17:45 UTC, skibinalexander commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkDataSource.swift
> +            let walletCondition = userWalletModel.isMultiWallet && !userWalletModel.isUserWalletLocked
> мы обсуждали, что таких проверок везде быть не должно, только в одном месте

Тут совершенно разные состояния экрана, и последовательные проверки в теории можно конечно попытаться объединить, но здесь не 1кк элементов , а условие определенного стейта

2023-11-13 17:46 UTC, skibinalexander commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkDataSource.swift
> +                return walletCondition && userWalletModel.config.supportedBlockchains.contains(where: { $0.coinId == coinId })
> Ну так видимо надо netwotkId передавать, нам же сеть нужна. Еще дополнительно вопрос как тогда будут обрабатываться угловой кейс с токсинами соланы

- Не понятно как взять у CoinModel networkId мне тут нужна помощь. 

- Кейс Соланы обрабатывается на уровне свитчера, когда мы пытаемся подключить , с ним проблем нет

2023-11-13 17:47 UTC, skibinalexander commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkSelectorViewModel.swift
> +        networkDataSource.prepare()
> Дело не в том, что обсуждали, а это получается очень хрупко, с точки зрения проектирования кода. Не должно меняться поведение от перестановки строчек.
> 
> Я предлагал два датасорса. Один общий, на весь менеджер токены и один отдельный, настраиваемый под валюту

Я согласен получается хрупко, тогда будет и биндинг висеть и браться изначально значение , сделаю так хорошо

2023-11-13 17:48 UTC, skibinalexander commented on Tangem/Modules/ManageTokensNetworkSelector/WalletSelector/WalletSelectorItemViewModel.swift
> +        userWalletModel: UserWalletModel,
> > Переделывать полностью item за рамками задачи выходит как-то
> 
> Ну заметили плохой код, почему бы сразу не поправить, либо надо было более точечно делить и выносить это в отдельный таск изначально. Откатывать нет смысла уже имхо

Не проблема , переделаем , просто надо утвердить что именно не так, чтобы точно норм получилось

2023-11-13 17:49 UTC, skibinalexander commented on Tangem/Modules/ManageTokensNetworkSelector/WalletSelector/WalletSelectorViewModel.swift
> +            WalletSelectorItemViewModel(
> Тут тут маппишь из этого dataSource в WalletSelectorItemViewModel, используя данные из самого dataSource. Этот dataSource он конкретно для этого экрана так пусть и отдает уже готово все

На мой взгяд это нормально, протокол WalletSelectorDataSource должен для тебя подготовить BL модели, ViewModel экрана целиковая должна тебе перемапить в UI модели, точно не ок? , не нравится мне совсем в DataSource складывать UI модели по сути

2023-11-13 17:53 UTC, skibinalexander commented on Tangem/App/Models/UserWallet/UserWalletConfig.swift
> +    var cardId: String { get }
> Ну переделка то здесь. Сделай загрузку картинок внутри UserWaleltModel

Может здесь все таки обратиться в UserWallet пока (тем более еще места где надо рефачить в таком случае) , и потом в рамках рефакторинг убрать, а то изменения полезут в UserWalletModel.

А то еще ревьюить ArtWork в UserWalletModel

2023-11-26 20:11 UTC, skibinalexander commented on Tangem/App/Services/UserWalletRepository/CommonUserWalletRepository.swift
> +                    self.sendEvent(.biometryUnlocked)
Без ивента не обойтись, не хватает текущих для корректной работы

2023-12-01 12:31 UTC, tureck1y requested changes

2023-12-01 12:31 UTC, tureck1y commented on Tangem/App/Services/UserWalletRepository/CommonUserWalletRepository.swift
> +    var selectedUserModelModel: UserWalletModel? {
коммент зарезолвил, но не переименовал

2023-12-01 12:31 UTC, tureck1y commented on Tangem/App/Services/UserWalletRepository/CommonUserWalletRepository.swift
> +    var selectedUserModelModel: UserWalletModel? {
У нас уже есть selectedModel. Используй ее

2023-12-01 12:31 UTC, tureck1y commented on Tangem/App/Services/UserWalletRepository/CommonUserWalletRepository.swift
> +                    self.sendEvent(.biometryUnlocked)
почему не хватает? Там ниже updated отсылается

2023-12-01 12:31 UTC, tureck1y commented on Tangem/App/Services/UserWalletRepository/UserWalletRepository.swift
> +    var selectedUserModelModel: UserWalletModel? { get }
var selectedModel: CardViewModel? { get } этой должно быть достаточно, ее позже на протокол поменяем

2023-12-01 12:31 UTC, tureck1y commented on Tangem/App/ViewModels/CardViewModel.swift
> +        longHashesSupported: longHashesSupported
Можно тут написать config.hasFeature(.longHashes) и удалить longHashesSupported?

2023-12-01 12:31 UTC, tureck1y commented on Tangem/Resources/Localizations/zh-Hant.lproj/Localizable.strings
> +"manage_tokens_wallet_does_not_supported_blockchain" = "Wallet Incompatible with selected Coin";
до сих пор не исправлено? Может уже есть новая текстовка

2023-12-01 12:31 UTC, tureck1y commented on Tangem/Modules/ManageTokens/TokenList/ManageTokensDataSource.swift
> +            .filter { event in
такое ощущение, что тут можно просто слушать все события сразу

2023-12-01 12:31 UTC, tureck1y commented on Tangem/Modules/ManageTokens/TokenList/ManageTokensDataSource.swift
> +    var userWalletModelsSubject: CurrentValueSubject<[UserWalletModel], Never> = .init([])
Давай сделаем как везде. Subject в названии плохо выглядит

private var _userWalletModels: CurrentValueSubject<[UserWalletModel], Never> = .init([]) 
var userWalletModels: [UserWalletModel] {  _userWalletModels.value } 

и если надо

var userWalletModelsPublisher: AnyPublisher<[UserWalletModel], Never> { _userWalletModels.eraseToAnyPublisher()) /

2023-12-01 12:31 UTC, tureck1y commented on Tangem/Modules/ManageTokens/TokenList/ManageTokensViewModel.swift
> +        userWalletModelsBind()
просто bind

2023-12-01 12:31 UTC, tureck1y commented on Tangem/Modules/ManageTokens/TokenList/ManageTokensViewModel.swift
>              .flatMap { userTokenListManager in
Давай map и flatMap объединим

2023-12-01 12:31 UTC, tureck1y commented on Tangem/Modules/ManageTokens/TokenList/ManageTokensViewModel.swift
> +    }
кажется можно без этой проперти обойтись dataSource.userWalletModels

2023-12-01 12:31 UTC, tureck1y commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkDataSource.swift
> +    var selectedUserWalletModelPublisher: CurrentValueSubject<UserWalletModel?, Never> = .init(nil)
тут тоже, должен быть единообразный подход

2023-12-01 12:31 UTC, tureck1y commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkDataSource.swift
> +    var walletSelectorItemViewModels: [WalletSelectorItemViewModel] {
Почему не перемаппить сразу в конструкторе?

2023-12-01 12:31 UTC, tureck1y commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkSelectorViewModel.swift
> +    private let parentDataSource: ManageTokensDataSource
Кажется тебе не нужно хранить parent

2023-12-01 12:31 UTC, tureck1y commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkSelectorViewModel.swift
> +    private func setNeedDisplayNotification(with parentDataSource: ManageTokensDataSource) {
Думаю надо объединить с методом ifSingleCurrencyDataSourceCompareUserWalletModels.
Название давай сделаем какое-нибудь типа checkConditions. Мы запускаем метод, который проверяет что-то, в этом его цель, а не показать алерт. Название метода покажи нотификацию, в которой вызывается метод с проверкой выглядит шиворот-навыворот.

2023-12-01 12:31 UTC, tureck1y commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkSelectorViewModel.swift
> +        if dataSource.userWalletModels.isEmpty {
такой if хорошо заменить на guard, слишком много вложенностей

2023-12-01 12:31 UTC, tureck1y commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkSelectorViewModel.swift
> +                   return isContains ? $0.coinId == coinId : $0.coinId != coinId
Невозможно разобраться что тут происходит. Сделай пожалуйста более человекочитаемо, если надо лучше добавить комменты. Как я помню тут не один кейс хэндлится

2023-12-01 12:31 UTC, tureck1y commented on Tangem/App/Services/UserTokensManager/CommonUserTokensManager.swift
> +    func tryCanAdd(_ tokenItem: TokenItem, derivationPath: DerivationPath?) throws {
1)  derivationPath не используется. Не надо его передавать просто так
2) asssertCanAdd ? try считывается как попытаться добавить.

2023-12-01 12:31 UTC, tureck1y commented on Tangem/Modules/ManageTokensNetworkSelector/WalletSelector/WalletSelectorDataSource.swift
> +    var selectedUserWalletModelPublisher: CurrentValueSubject<UserWalletModel?, Never> { get set }
1) Здесь тоже в протоколе торчит AnyPublisher, не сабжект. Чтобы только подписываться, а не пушить изменения снаружи

2) Префикс walletSelector у walletSelectorItemViewModels  кажется излишним, потому что мы и так внутри WalletSelectorDataSource

2023-12-01 12:31 UTC, tureck1y commented on Tangem/Modules/ManageTokensNetworkSelector/WalletSelector/WalletSelectorViewModel.swift
> +                    item.isSelected = item.id == userWalletModel?.userWalletId
Вот тут заметно, что ты сравниваешь какой-то id c userWalletId. Нет единообразия в нейминге. Пусть будет везде userWalletId?

2023-12-01 13:17 UTC, skibinalexander commented on Tangem/App/Services/UserWalletRepository/CommonUserWalletRepository.swift
> +                    self.sendEvent(.biometryUnlocked)
update не срабатывал в нужное время , и не происходило обновление

2023-12-01 13:19 UTC, skibinalexander commented on Tangem/App/Services/UserWalletRepository/UserWalletRepository.swift
> +    var selectedUserModelModel: UserWalletModel? { get }
Да , справедливо , лишнее получилось давно слишком тянется , уже понял , что CardViewModel это оно

2023-12-02 19:23 UTC, skibinalexander commented on Tangem/App/Services/UserTokensManager/CommonUserTokensManager.swift
> +    func tryCanAdd(_ tokenItem: TokenItem, derivationPath: DerivationPath?) throws {
> 1. derivationPath не используется. Не надо его передавать просто так
> 2. asssertCanAdd ? try считывается как попытаться добавить.

1. Да, подумал делать единообразно и мало ли понадобится.
2. Ну вообще tryCanAdd вполне общепринятое название, но в целом assertCanAdd если кажется понятнее поменяю

2023-12-04 09:10 UTC, skibinalexander commented on Tangem/Modules/ManageTokens/TokenList/ManageTokensViewModel.swift
> +    }
> кажется можно без этой проперти обойтись dataSource.userWalletModels

Делал для удобства, окей уберу

2023-12-04 14:48 UTC, skibinalexander commented on Tangem/Modules/ManageTokensNetworkSelector/WalletSelector/WalletSelectorViewModel.swift
> +                    item.isSelected = item.id == userWalletModel?.userWalletId
> Вот тут заметно, что ты сравниваешь какой-то id c userWalletId. Нет единообразия в нейминге. Пусть будет везде userWalletId?

Обновил

2023-12-04 14:55 UTC, skibinalexander commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkDataSource.swift
> +    var walletSelectorItemViewModels: [WalletSelectorItemViewModel] {
> Почему не перемаппить сразу в конструкторе?

Во вьюшку передается событие action, нужно сделать слабый захват, + чтобы не было рассинхрона в источниках, есть источник это модели, ViewModel вычисляются, там все равно 1-3 элемента, через свойство даже лучше думаю

2023-12-05 08:47 UTC, skibinalexander commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkSelectorViewModel.swift
> +    private let parentDataSource: ManageTokensDataSource
> Кажется тебе не нужно хранить parent

Мне нужно в случае если кошельков в которые я добавить не смог, понять что есть выбранный ондовалютный, а понять что есть одновалютный я могу только по паренту

2023-12-05 08:55 UTC, skibinalexander commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkSelectorViewModel.swift
> +    private func setNeedDisplayNotification(with parentDataSource: ManageTokensDataSource) {
> Думаю надо объединить с методом ifSingleCurrencyDataSourceCompareUserWalletModels. Название давай сделаем какое-нибудь типа checkConditions. Мы запускаем метод, который проверяет что-то, в этом его цель, а не показать алерт. Название метода покажи нотификацию, в которой вызывается метод с проверкой выглядит шиворот-навыворот.

Тут не очень удобным выглядит объединение, предлагаю переименовать:

displayNotificationIfNeededWithCheckCondition - метод который показывает алерт если выполняется условие одновалютности

isExistOnlySingleCurrencyUserWalletModelWithCoin - метод который проверяет есть ли одновалютнка и параметр coinId для того чтобы понять поддерживает или нет, чтобы показывать / не показывать Алерт , а также на него опирается свитчер в методе isAdded

2023-12-05 08:55 UTC, skibinalexander commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkSelectorViewModel.swift
> +    private func setNeedDisplayNotification(with parentDataSource: ManageTokensDataSource) {
Переименовал сделал более понятно

2023-12-05 08:57 UTC, skibinalexander commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkSelectorViewModel.swift
> +                   return isContains ? $0.coinId == coinId : $0.coinId != coinId
> Невозможно разобраться что тут происходит. Сделай пожалуйста более человекочитаемо, если надо лучше добавить комменты. Как я помню тут не один кейс хэндлится

Переименовал добавил коммент

2023-12-05 08:58 UTC, skibinalexander commented on Tangem/Modules/ManageTokensNetworkSelector/WalletSelector/WalletSelectorDataSource.swift
> +    var selectedUserWalletModelPublisher: CurrentValueSubject<UserWalletModel?, Never> { get set }
> 1. Здесь тоже в протоколе торчит AnyPublisher, не сабжект. Чтобы только подписываться, а не пушить изменения снаружи
> 2. Префикс walletSelector у walletSelectorItemViewModels  кажется излишним, потому что мы и так внутри WalletSelectorDataSource

Поправил

2023-12-05 10:44 UTC, skibinalexander commented on Tangem/Modules/ManageTokens/TokenList/ManageTokensDataSource.swift
> +            .filter { event in
> такое ощущение, что тут можно просто слушать все события сразу

Обсудили, оставляем

2023-12-06 17:38 UTC, tureck1y commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkSelectorViewModel.swift
> +    private let parentDataSource: ManageTokensDataSource
ну ты же сразу в конструкторе это обрабатываешь, зачем хранить?

2023-12-06 17:41 UTC, tureck1y commented on Tangem/Modules/ManageTokens/TokenList/ManageTokensDataSource.swift
> +    let _userWalletModels: CurrentValueSubject<[UserWalletModel], Never> = .init([])
надо сделать private

2023-12-06 17:41 UTC, tureck1y commented on Tangem/Modules/ManageTokens/TokenList/ManageTokensDataSource.swift
> +    let _userWalletModels: CurrentValueSubject<[UserWalletModel], Never> = .init([])
и сразу увидишь где ошибка)

2023-12-06 17:43 UTC, tureck1y commented on Tangem/Modules/ManageTokensNetworkSelector/WalletSelector/WalletSelectorDataSource.swift
> +    var _selectedUserWalletModel: CurrentValueSubject<UserWalletModel?, Never> { get }
В протоколе не должно быть этой строчки вообще. Торчит getter если надо и AnyPublisher если надо

2023-12-06 17:45 UTC, tureck1y commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkDataSource.swift
> +    let _selectedUserWalletModel: CurrentValueSubject<UserWalletModel?, Never> = .init(nil)
после того как WalletSelectorDataSource будет поправлен, можно сделать тут конферанс протоколу через экстеншен, будет чище, смотри как пример WalletModelsManager/CommonWalletModelsManager

2023-12-06 17:53 UTC, tureck1y requested changes

2023-12-06 17:53 UTC, tureck1y commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkSelectorViewModel.swift
> +        displayNotificationIfNeededWithCheckCondition()
вот тут назвать функцию configure/setup и передать этот парент. Это же константа, меняться не может. Один раз настроил стейт экрана и все

2023-12-06 17:53 UTC, tureck1y commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkSelectorViewModel.swift
> +    /// This method that checks whether there is a single currency and contain supported the coinId parameter
непонятно что тут написано(

2023-12-06 17:53 UTC, tureck1y commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkSelectorViewModel.swift
> +               return condition ? $0.coinId == coinId : $0.coinId != coinId
я же попросил отрефакторить эту строку

2023-12-07 08:39 UTC, skibinalexander commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkSelectorViewModel.swift
> +               return condition ? $0.coinId == coinId : $0.coinId != coinId
> я же попросил отрефакторить эту строку

Обсудили, вообще удалил

2023-12-07 08:39 UTC, skibinalexander commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkSelectorViewModel.swift
> +        displayNotificationIfNeededWithCheckCondition()
> вот тут назвать функцию configure/setup и передать этот парент. Это же константа, меняться не может. Один раз настроил стейт экрана и все

Обсудили, поміняли

2023-12-07 08:39 UTC, skibinalexander commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkSelectorViewModel.swift
> +    private let parentDataSource: ManageTokensDataSource
> ну ты же сразу в конструкторе это обрабатываешь, зачем хранить?

Переделали на defaultCoinId

2023-12-07 08:40 UTC, skibinalexander commented on Tangem/Modules/ManageTokensNetworkSelector/WalletSelector/WalletSelectorDataSource.swift
> +    var _selectedUserWalletModel: CurrentValueSubject<UserWalletModel?, Never> { get }
> В протоколе не должно быть этой строчки вообще. Торчит getter если надо и AnyPublisher если надо

Ага поменял на то как везде через AnyPublisher

2023-12-07 08:59 UTC, tureck1y commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkDataSource.swift
> +    var selectedUserWalletModel: UserWalletModel? { _selectedUserWalletModel.value }
Посмотри пожалуйста, тут торчат два публичных var. Они используются? Может тогда они должны быть частью протокола WalletSelectorDataSource?

2023-12-07 09:04 UTC, skibinalexander commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkDataSource.swift
> +    var selectedUserWalletModel: UserWalletModel? { _selectedUserWalletModel.value }
Да, как используется в тех методах в guard и проверках которые вчера меняли. Не добавил эти проперти в протокол, потому что, хотели как раз сделать модуль выбора кошелька гибким и не привязанным к какому нибудь другому модулю

2023-12-07 09:05 UTC, skibinalexander commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkDataSource.swift
> +    var selectedUserWalletModel: UserWalletModel? { _selectedUserWalletModel.value }
Я бы не стал затаскивать их в протокол, потому что протокол он сугубо для модуля выбора кошелька

2023-12-07 09:09 UTC, skibinalexander commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkDataSource.swift
> +    var selectedUserWalletModel: UserWalletModel? { _selectedUserWalletModel.value }
> Я бы не стал затаскивать их в протокол, потому что протокол он сугубо для модуля выбора кошелька, а модуль токенов работает со своим дата сурсом

2023-12-07 09:57 UTC, tureck1y submitted a review, later dismissed

2023-12-08 11:13 UTC, m3g0byt3 commented on Tangem/App/Services/UserTokensManager/CommonUserTokensManager.swift
> +    private let existingCurves: [EllipticCurve]
nit: это можно наверное сделать сетом для быстрого лукапа?

2023-12-08 11:13 UTC, m3g0byt3 commented on Tangem/App/Services/UserTokensManager/CommonUserTokensManager.swift
> +        }
Тут разве не `!longHashesSupported` должно быть?

2023-12-08 11:13 UTC, m3g0byt3 commented on Tangem/App/Services/UserWalletRepository/LockedUserWallet.swift
> +            artwork = .notLoaded
А почему не `noArtwork`?
Мы же не знаем, идет загрузка прямо сейчас или нет

Или таким образом мы форсим загрузку далее?

2023-12-08 11:13 UTC, m3g0byt3 commented on Tangem/App/Services/WarningsService/Warnings/WarningEvent+.swift
> +            // New cases won't be displayed in new design
А где будут отображаться эти кейсы?

_Все, что связано с Warning вообще кажется будет скоро выпилено - и легаси главный и легаси сенд_

2023-12-08 11:13 UTC, m3g0byt3 commented on Tangem/App/ViewModels/CardViewModel.swift
> +        longHashesSupported: longHashesSupported
А эти параметры могут измениться уже после создания этой lazy проперти?
Или они на весь период жизни приложения readonly?

2023-12-08 11:13 UTC, m3g0byt3 commented on Tangem/App/ViewModels/CardViewModel.swift
> +    var cardImagePublisher: AnyPublisher<CardImageResult, Never> {
nit: какая-то копипаста (с потенциально меняющейся логикой насчет `notLoaded`/`noArtwork`) тут и в LockedUserWallet - может вынести в экстеншн для CardImageProvider?

2023-12-08 11:13 UTC, m3g0byt3 commented on Tangem/Modules/ManageTokens/TokenList/ManageTokensViewModel.swift
> +        dataSource = ManageTokensDataSource()
nit: странно что VM сама себе создает датасорс, а он не инжектится в ините например

2023-12-08 11:13 UTC, m3g0byt3 commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkSelectorView.swift
>              if !viewModel.nativeSelectorItems.isEmpty {
Если вот это условие не выполнится и nativeNetworksContent не будет в иерархии - то кажется будет дырка?
спейсер на 26 строке + спейсер на 30 строке

2023-12-08 11:13 UTC, m3g0byt3 commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkSelectorViewModel.swift
> +    private var isTokenAvailableForSwitching: Bool {
А что значит For Switching в данном контексте?

2023-12-08 11:13 UTC, m3g0byt3 commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkSelectorViewModel.swift
> +        dataSource = ManageTokensNetworkDataSource(parentDataSource)
🧐

2023-12-08 11:13 UTC, m3g0byt3 commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkSelectorViewModel.swift
> +                self?.displayAlertAndUpdateSelection(for: tokenItem, error: error as? LocalizedError)
Вроде тут и ниже на 340 строчке не надо кастить.

Если тип конформит `LocalizedError` - то его non-nil имплементация `LocalizedError.errorDescription` отдается в `Error.localizedDescription`

2023-12-08 11:13 UTC, m3g0byt3 commented on Tangem/Modules/ManageTokensNetworkSelector/WalletSelector/WalletSelectorViewModel.swift
> +    private weak var dataSource: WalletSelectorDataSource?
Какие-то проперти с датасорсами сильные, какие-то слабые - можешь рассказать про иерархию датасорсов и вообще к чему вы пришли при обсуждении?

2023-12-08 12:35 UTC, skibinalexander commented on Tangem/App/Services/UserTokensManager/CommonUserTokensManager.swift
> +        }
> Тут разве не `!longHashesSupported` должно быть?

Да, спасибо нужно через !

2023-12-08 12:39 UTC, skibinalexander commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkSelectorViewModel.swift
> +    private var isTokenAvailableForSwitching: Bool {
> А что значит For Switching в данном контексте?

_доступно для перключения_ - задизейблен свитчер или нет

2023-12-08 12:42 UTC, skibinalexander commented on Tangem/App/Services/UserTokensManager/CommonUserTokensManager.swift
> +    private let existingCurves: [EllipticCurve]
> nit: это можно наверное сделать сетом для быстрого лукапа?

В конфигах это лежит в массиве, думаю не стоит оверинженерить тут

2023-12-08 12:42 UTC, skibinalexander commented on Tangem/App/Services/UserTokensManager/CommonUserTokensManager.swift
> +    private let existingCurves: [EllipticCurve]
> > nit: это можно наверное сделать сетом для быстрого лукапа?
> 
> В конфигах это лежит в массиве, думаю не стоит оверинженерить тут

2023-12-08 12:47 UTC, skibinalexander commented on Tangem/Modules/ManageTokensNetworkSelector/WalletSelector/WalletSelectorViewModel.swift
> +    private weak var dataSource: WalletSelectorDataSource?
> Какие-то проперти с датасорсами сильные, какие-то слабые - можешь рассказать про иерархию датасорсов и вообще к чему вы пришли при обсуждении?

Есть 2 дата сорта, парент и чаилд , где viewModel держат их Стронгом. При этом есть модуль выбора кошельков, где дата сорс это протокол, и он уже держит слабо потому что инджектится в него. В целом все стандартно, инджектим, держим слабо, если владеем держим сильно

2023-12-08 12:52 UTC, skibinalexander commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkSelectorViewModel.swift
> +        dataSource = ManageTokensNetworkDataSource(parentDataSource)
> 🧐

Сделал Rename

2023-12-08 13:36 UTC, skibinalexander commented on Tangem/App/Services/WarningsService/Warnings/WarningEvent+.swift
> +            // New cases won't be displayed in new design
> А где будут отображаться эти кейсы?
> 
> _Все, что связано с Warning вообще кажется будет скоро выпилено - и легаси главный и легаси сенд_

Тут погасить компилятор нужно было, Андрей сказал без разницы, WarningEvent+ будет удаляться

2023-12-08 14:09 UTC, skibinalexander commented on Tangem/App/ViewModels/CardViewModel.swift
> +        longHashesSupported: longHashesSupported
> А эти параметры могут измениться уже после создания этой lazy проперти? Или они на весь период жизни приложения readonly?

По Идее нет , с конфига же берутся

2023-12-08 14:16 UTC, skibinalexander commented on Tangem/App/Services/UserWalletRepository/LockedUserWallet.swift
> +            artwork = .notLoaded
> А почему не `noArtwork`? Мы же не знаем, идет загрузка прямо сейчас или нет
> 
> Или таким образом мы форсим загрузку далее?

Обсудили , оставляем

2023-12-08 14:22 UTC, skibinalexander commented on Tangem/App/ViewModels/CardViewModel.swift
> +    var cardImagePublisher: AnyPublisher<CardImageResult, Never> {
Обсудили

2023-12-08 15:01 UTC, m3g0byt3 approved these changes

2023-12-08 16:12 UTC, tureck1y approved these changes

2023-12-08 16:17 UTC, merged