IOS-5021 Updated l10n
tangem/tangem-app-ios-old pull request #2344
Opened 2023-11-02 12:10 UTC by megakoko

2023-11-02 18:47 UTC, tureck1y requested changes
очепятка

2023-11-02 18:47 UTC, tureck1y commented on Tangem/Resources/Localizations/ru.lproj/Localizable.stringsdict
> +        <string>кошелека</string>
кошелека?

2023-11-03 09:11 UTC, megakoko commented on Tangem/Resources/Localizations/ru.lproj/Localizable.stringsdict
> +        <string>кошелека</string>
Спасибо, исправил

2023-11-03 11:08 UTC, tureck1y approved these changes

2023-11-04 08:42 UTC, skibinalexander approved these changes

2023-11-04 08:42 UTC, merged