IOS-5054 Update locale for alert_messages
tangem/tangem-app-ios-old pull request #2351
Opened 2023-11-03 10:31 UTC by skibinalexander

@megakoko

2023-11-03 10:54 UTC, tureck1y requested changes

2023-11-03 10:54 UTC, tureck1y commented on Tangem/Modules/LegacyTokenList/AddCustomToken/LegacyAddCustomTokenViewModel.swift
> +        case tokensNotSupported(Blockchain)
сюда можно передать не блокчейн, а displayName: String

2023-11-03 10:54 UTC, tureck1y commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkSelectorViewModel.swift
> +            case .failedSupportedLongHahesTokens(let tokenItem):
И тут. Чем конкретнее передается сущность, тем лучше

2023-11-03 11:03 UTC, skibinalexander commented on Tangem/Modules/ManageTokensNetworkSelector/ManageTokensNetworkSelectorViewModel.swift
> +            case .failedSupportedLongHahesTokens(let tokenItem):
Да хорошо, поправлю

2023-11-03 12:54 UTC, megakoko approved these changes, later dismissed

2023-11-07 16:00 UTC, tureck1y commented on Tangem/Modules/LegacyTokenList/AddCustomToken/LegacyAddCustomTokenViewModel.swift
> +        case tokensNotSupported(String)
Добавь лейбл плиз, чтобы было понятно что за String

2023-11-07 16:21 UTC, tureck1y approved these changes

2023-11-07 16:21 UTC, merged