IOS-5026 send recipient input UI
tangem/tangem-app-ios-old pull request #2367
Opened 2023-11-08 11:17 UTC by megakoko

2023-11-13 12:58 UTC, Andoran90 requested changes

2023-11-13 12:58 UTC, Andoran90 commented on Tangem/Modules/Send/Destination/SendDestinationInputView.swift
> +            Group {
а зачем эта группа? можно либо её удалить, либо вынести `padding(.vertical, 12)` и сделать единый для группы.

2023-11-13 12:58 UTC, Andoran90 commented on Tangem/Modules/Send/Destination/SendDestinationInputView.swift
> +                    DispatchQueue.main.async {
а есть какие-то проблемы со вставкой или что?

вроде `PasteButton` отмечена как `@MainActor` и она весь код будет исполнять на главной потоке только

2023-11-13 12:58 UTC, Andoran90 commented on Tangem/Modules/Send/Destination/SendDestinationInputViewModel.swift
> +    init(name: String, input: Binding<String>, showAddressIcon: Bool, placeholder: String, description: String, didPasteAddress: @escaping ([String]) -> Void) {
разбей, пожалуйста, по строчкам, длинновато

2023-11-13 12:58 UTC, Andoran90 commented on Tangem/Modules/Send/Destination/SendDestinationInputViewModel.swift
> +    var input: Binding<String>
опять вразнобой, отдели `let` от `var`

2023-11-13 12:58 UTC, Andoran90 commented on Tangem/Modules/Send/Destination/SendDestinationInputViewModel.swift
> +    @objc
эт што?))

2023-11-13 12:58 UTC, Andoran90 commented on Tangem/Modules/Send/Destination/SendDestinationInputViewModel.swift
> +        NotificationCenter.default.addObserver(
надо сделать через паблишер

2023-11-13 12:59 UTC, megakoko commented on Tangem/Modules/Send/Destination/SendDestinationInputView.swift
> +                    DispatchQueue.main.async {
Не помню, там было сделано в старом сенде

2023-11-13 14:18 UTC, tureck1y submitted a review, later dismissed

2023-11-13 14:18 UTC, tureck1y commented on Tangem/Modules/Send/Destination/SendDestinationInputView.swift
> +                    DispatchQueue.main.async {
можно не добавлять, пока не столкнемся с проблемой

2023-11-13 14:23 UTC, megakoko commented on Tangem/Modules/Send/Destination/SendDestinationInputView.swift
> +                    DispatchQueue.main.async {
Вызывает на негуёвом потоке

<img width="1025" alt="Screenshot 2023-11-13 at 17 23 09" src="https://github.com/tangem/tangem-app-ios/assets/12209839/20291a63-c313-4933-bd10-49eb08aad69e">

2023-11-13 14:27 UTC, megakoko commented on Tangem/Modules/Send/Destination/SendDestinationInputViewModel.swift
> +        NotificationCenter.default.addObserver(
Сделал

2023-11-13 14:27 UTC, megakoko commented on Tangem/Modules/Send/Destination/SendDestinationInputViewModel.swift
> +    @objc
Удолил

2023-11-13 14:27 UTC, megakoko commented on Tangem/Modules/Send/Destination/SendDestinationInputViewModel.swift
> +    init(name: String, input: Binding<String>, showAddressIcon: Bool, placeholder: String, description: String, didPasteAddress: @escaping ([String]) -> Void) {
Разбил

2023-11-13 14:27 UTC, megakoko commented on Tangem/Modules/Send/Destination/SendDestinationInputViewModel.swift
> +    var input: Binding<String>
Сделал

2023-11-13 14:28 UTC, megakoko commented on Tangem/Modules/Send/Destination/SendDestinationInputView.swift
> +            Group {
Не знаю зачем так делал, убрал группу

2023-11-13 14:28 UTC, megakoko commented
@Andoran90 @tureck1y поправил по комментам, подлил девелоп

2023-11-13 15:22 UTC, tureck1y submitted a review, later dismissed

2023-11-13 15:51 UTC, Andoran90 commented on Tangem/Modules/Send/Destination/SendDestinationInputView.swift
> +                    DispatchQueue.main.async {
хм... странно

2023-11-13 15:52 UTC, Andoran90 commented on Tangem/Modules/Send/Destination/SendDestinationInputViewModel.swift
> +        NotificationCenter.default.removeObserver(self)
тут только не обсервер, а надо чистить сумочку

2023-11-14 11:18 UTC, megakoko commented on Tangem/Modules/Send/Destination/SendDestinationInputViewModel.swift
> +        NotificationCenter.default.removeObserver(self)
Убрал

2023-11-14 11:49 UTC, megakoko commented
@Andoran90 @tureck1y обновил

2023-11-15 05:40 UTC, Andoran90 submitted a review, later dismissed

2023-11-15 08:03 UTC, m3g0byt3 approved these changes, later dismissed

2023-11-15 08:03 UTC, m3g0byt3 commented on Tangem/Modules/Send/Destination/SendDestinationInputView.swift
> +        .onReceive(NotificationCenter.default.publisher(for: UIApplication.didBecomeActiveNotification)
nit: Немного странно выглядит эта подписка во вьюхе, с учетом того, что внутри VM уже есть другие подписки

2023-11-15 08:03 UTC, m3g0byt3 commented on Tangem/Modules/Send/Destination/SendDestinationInputViewModel.swift
> +        NotificationCenter.default.publisher(for: UIPasteboard.changedNotification)
nit: эту и другую подписку на didbecomeactive в принципе можно не делать на 16+

2023-11-15 10:50 UTC, megakoko commented on Tangem/Modules/Send/Destination/SendDestinationInputView.swift
> +        .onReceive(NotificationCenter.default.publisher(for: UIApplication.didBecomeActiveNotification)
Согласен, перенес

2023-11-15 10:50 UTC, megakoko commented on Tangem/Modules/Send/Destination/SendDestinationInputViewModel.swift
> +        NotificationCenter.default.publisher(for: UIPasteboard.changedNotification)
Понаставил #unavailable где надо

2023-11-15 10:52 UTC, megakoko commented
@m3g0byt3 @Andoran90 обновил, посмотрите еще, пожалуйста

2023-11-15 11:10 UTC, Andoran90 approved these changes

2023-11-15 11:10 UTC, m3g0byt3 approved these changes

2023-11-15 11:11 UTC, merged