IOS-5023 send amount UI
tangem/tangem-app-ios-old pull request #2384
Opened 2023-11-10 08:49 UTC by megakoko

Поле ввода допилим потом, можно будет это распараллелить 

<img width="497" alt="Screenshot 2023-11-10 at 11 40 59" src="https://github.com/tangem/tangem-app-ios/assets/12209839/79b31dad-322c-4ec9-8b93-5cc6f3223c0c">

2023-11-13 12:45 UTC, tureck1y commented
> Поле ввода допилим потом, можно будет это распараллелить

На это есть задача уже?

2023-11-13 12:45 UTC, tureck1y commented
промахнулся и закрыл)

2023-11-13 12:51 UTC, megakoko commented
> > Поле ввода допилим потом, можно будет это распараллелить
> 
> На это есть задача уже?

Да. Пока сделал ее подзадачей, если что можно вынести — https://tangem.atlassian.net/browse/IOS-5024

2023-11-13 12:52 UTC, tureck1y commented
А нам нужна такая контейнер вью? Это же просто экран и компоновка body.

2023-11-13 12:53 UTC, tureck1y commented
Жирный конструктор намекает

2023-11-13 12:55 UTC, megakoko commented
Ну это скорее ради разбиения экрана на более мелкие кусочки. Там еще будет селектор валюты и кнопка МАХ. Плюс для создания всей страницы хотелось бы скелет модуля смержить, его пока нет

2023-11-13 13:14 UTC, tureck1y commented
Давай лучше это сделаем в рамках локальных разбиений вьюхи самого экрана. У нас был такой опыт толстыми вью для баланса, которые нигде не переиспользовались, только были проблемы с распутыванием спагетти и лишним прокидыванием параметров.

2023-11-13 13:21 UTC, megakoko commented
Сделаю тогда здесь весь экран

2023-11-14 14:00 UTC, megakoko commented
<img width="391" alt="Screenshot 2023-11-14 at 16 59 21" src="https://github.com/tangem/tangem-app-ios/assets/12209839/c65fd0c0-43ae-49d6-ae35-2daa7bfeecc4">

2023-11-14 14:01 UTC, megakoko commented
- перенес все во вьюху страницы
- добавил max, fiat/crypto
- сделал чтобы sendmodel хранила сумму в виде decimal вместо строки
- добавил TODO где будет связь walletmodel и вьюхи

2023-11-14 14:02 UTC, megakoko commented
@Andoran90 @tureck1y обновил

2023-11-22 14:06 UTC, tureck1y commented
конфликты набежали

2023-11-22 14:07 UTC, megakoko commented
Я жду ревью, иначе каждый день будут набегать

2023-11-22 14:20 UTC, tureck1y requested changes

2023-11-22 14:20 UTC, tureck1y commented on Tangem/Modules/Send/Amount/SendAmountViewModel.swift
>  protocol SendAmountViewModelInput {
Может побьем на файлы?

2023-11-22 14:20 UTC, tureck1y commented on Tangem/Modules/Send/Amount/SendAmountViewModel.swift
> +    var decimalValue: Binding<DecimalNumberTextField.DecimalValue?> { get }
Предлагаю названия сделать более информативные.

2023-11-22 14:20 UTC, tureck1y commented on Tangem/Modules/Send/Amount/SendAmountViewModel.swift
> +    var decimalValue: Binding<DecimalNumberTextField.DecimalValue?> { get }
Видимо надо сделать ревизию параметров, обсудить, тут 4 поля только к иконке относятся. Как-будто не должно столько быть. Инпут идет из модели сенда, не уверен, что он что-то про иконку должен знать.

2023-11-22 14:20 UTC, tureck1y commented on Tangem/Modules/Send/Amount/SendAmountViewModel.swift
> +        walletName = input.walletName
Может оставим инпут, чтобы не перекладывать?

2023-11-22 14:20 UTC, tureck1y commented on Tangem/Modules/Send/SendModel.swift
> +    private var amount = CurrentValueSubject<DecimalNumberTextField.DecimalValue?, Never>(nil)
Смущает, что SendModel начинает знать о каких-то DecimalNumberTextField.DecimalValue. Думаю это нужно маппить где-то в другом месте, во вью модели соотв

2023-11-22 14:20 UTC, tureck1y commented on Tangem/Modules/Send/SendModel.swift
> +    var walletName: String {
@Andoran90 что думаешь? Моя мысль, что это нужно как минимум сгруппировать, а вообще может вынести из SendModel? SendModel - форма отправки, почему она должна такую инфу предоставлять.

2023-11-23 08:46 UTC, Andoran90 commented on Tangem/Modules/Send/Amount/SendAmountViewModel.swift
> +    var tokenIconBlockchainIconName: String? { get }
надо дев подлить, потому что там был рефакторинг `TokenIcon`, есть теперь `TokenIconInfo`

2023-11-23 08:46 UTC, Andoran90 commented on Tangem/Modules/Send/Amount/SendAmountViewModel.swift
> +    var balance: String { get }
по идее можно сделать отдельным протоколом, используется ещё и в саммари

2023-11-23 08:46 UTC, Andoran90 commented on Tangem/Modules/Send/SendModel.swift
> +    private var amount = CurrentValueSubject<DecimalNumberTextField.DecimalValue?, Never>(nil)
поддерживаю, во вью модель должен передаваться биндинг на `Decimal`, а внутри вью модели уже оборачиваться в паблишер `DecimalNumberTextField.DecimalValue` и использоваться как UI часть. А ещё из `SendModel` надо удалить `import SwiftUI`, потому что он никак не должен быть связать с UI

2023-11-23 08:46 UTC, Andoran90 commented on Tangem/Modules/Send/SendModel.swift
> +    private(set) var isFiatCalculation: Bool = false
хм, а разве это тут должно быть? по идее фиатный или не фиатный расчет - `SendModel` нет разницы, потому что отправляет он исключительно в крипте значения всегда, а эти фиатные делишки чисто для UI

2023-11-23 08:46 UTC, Andoran90 commented on Tangem/Modules/Send/SendModel.swift
> +    var walletName: String {
`SendModel` чет становится божественным объектом, надо бы его разбить?..
Наверное часть сущностей можно положить в `SendViewModel`, которые предоставляют неизменяемую инфу - вроде названия кошелька, баланса в крипте, инфы про иконку и т.д. По идее вся эта инфа не нужна в `SendModel` и можно её спокойно положить в другом месте. А тут оставить исключительно все что заполняет пользователь и только в том формате, который будет отправляться в блокчеин (в смысле никаких фиатных дел, только крипта, а все конвертации делать внутри вью моделей).

2023-11-23 08:46 UTC, Andoran90 commented on Tangem/Modules/Send/SendModel.swift
> +    var walletName: String {
вообще конвертации из фиата в крипту и обратно должно быть в `SendAmountViewModel`, и передача в `SendModel` инфы о введенной крипте
вся инфа про адреса в `SendDestinationViewModel`
А что-то эти вью модели получаются довольно бестолковые и вся логика уходит в `SendModel`

2023-11-23 14:38 UTC, megakoko commented on Tangem/Modules/Send/SendModel.swift
> +    private var amount = CurrentValueSubject<DecimalNumberTextField.DecimalValue?, Never>(nil)
Биндинги лежат в SwiftUI

2023-11-24 08:49 UTC, Andoran90 commented on Tangem/Modules/Send/SendModel.swift
> +    private var amount = CurrentValueSubject<DecimalNumberTextField.DecimalValue?, Never>(nil)
как было бы хорошо избавиться от биндингов 😅😅

2023-11-24 08:50 UTC, megakoko commented on Tangem/Modules/Send/SendModel.swift
> +    private var amount = CurrentValueSubject<DecimalNumberTextField.DecimalValue?, Never>(nil)
Да я думаю уйдут, я постепенно их заменяю на паблишеры там

2023-11-24 09:32 UTC, megakoko commented on Tangem/Modules/Send/SendModel.swift
> +    private(set) var isFiatCalculation: Bool = false
Убрал, будет переформатироваться в amointviewmodel, сделал todo

2023-11-24 09:32 UTC, megakoko commented on Tangem/Modules/Send/Amount/SendAmountViewModel.swift
> +    var balance: String { get }
Сделал отдельный параметр SendWalletInfo

2023-11-24 09:33 UTC, megakoko commented on Tangem/Modules/Send/Amount/SendAmountViewModel.swift
> +    var tokenIconBlockchainIconName: String? { get }
Переделал

2023-11-24 09:34 UTC, megakoko commented on Tangem/Modules/Send/SendModel.swift
> +    var walletName: String {
Сделал параметр SendWalletInfo где все это барахло хранится и через которое передается, почистил sendmodel

2023-11-24 09:34 UTC, megakoko commented on Tangem/Modules/Send/SendModel.swift
> +    private var amount = CurrentValueSubject<DecimalNumberTextField.DecimalValue?, Never>(nil)
Убрал, sendmodel будет получать значение в крипте

2023-11-24 09:35 UTC, megakoko commented on Tangem/Modules/Send/Amount/SendAmountViewModel.swift
> +        walletName = input.walletName
А все равно же нужны локальные переменные, мы договаривались один уровень вложенности везде делать

2023-11-24 09:36 UTC, megakoko commented on Tangem/Modules/Send/Amount/SendAmountViewModel.swift
> +    var decimalValue: Binding<DecimalNumberTextField.DecimalValue?> { get }
Сделал просто amount

2023-11-24 09:36 UTC, megakoko commented on Tangem/Modules/Send/Amount/SendAmountViewModel.swift
> +    var decimalValue: Binding<DecimalNumberTextField.DecimalValue?> { get }
Информацию об иконках положил в tokeniconinfo

2023-11-24 09:37 UTC, megakoko commented on Tangem/Modules/Send/Amount/SendAmountViewModel.swift
>  protocol SendAmountViewModelInput {
Давай сейчас так оставим, я добавил TODO на потом. Если что сразу все перенести чтобы не погрязнуть сейчас в конфликтах

2023-11-24 10:01 UTC, Andoran90 commented on Tangem/Modules/Send/Amount/SendAmountViewModel.swift
> +    private var _amount: DecimalNumberTextField.DecimalValue? = nil
хм, хотел в начале предложить переделать на `@Published var amount: DecimalNumberTextField.DecimalValue?`, но получается что циклические изменения будут, надо подумать как бы это сделать, потому что `var amount: Binding...` выглядит стремно, для этих целей во вью моделях есть `@Published`, что-то тут не клеится и не используем средства системы

2023-11-24 12:52 UTC, megakoko commented on Tangem/Modules/Send/Amount/SendAmountViewModel.swift
> +    private var _amount: DecimalNumberTextField.DecimalValue? = nil
Сделал через паблишер, все норм

2023-11-27 07:59 UTC, Andoran90 approved these changes, later dismissed
без биндингов красиве, как по мне

2023-11-27 07:59 UTC, Andoran90 commented on Tangem/Modules/Send/Amount/SendAmountViewModel.swift
> +                self?.objectWillChange.send()
думаю это не нужно больше

2023-12-07 10:12 UTC, tureck1y commented on Tangem/Modules/Send/Amount/SendAmountViewModel.swift
> +                self?.objectWillChange.send()
да, надо вычищать такие костыли

2023-12-07 10:13 UTC, tureck1y reviewed
👀

2023-12-11 07:32 UTC, megakoko commented on Tangem/Modules/Send/Amount/SendAmountViewModel.swift
> +                self?.objectWillChange.send()
Удолил

2023-12-11 07:32 UTC, megakoko commented
@tureck1y @Andoran90  обновил

2023-12-11 09:31 UTC, tureck1y approved these changes

2023-12-12 05:35 UTC, Andoran90 approved these changes

2023-12-12 05:35 UTC, merged