IOS-5028 Send recipient logic
tangem/tangem-app-ios-old pull request #2429
Opened 2023-11-20 15:45 UTC by megakoko

2023-11-20 15:54 UTC, megakoko commented on Tangem/Modules/Send/Summary/SendSummaryViewModel.swift
> +//        destinationText = input.destinationTextBinding.wrappedValue
Это summary экран, тут все тестовое, потом переделается

2023-12-07 19:47 UTC, tureck1y requested changes

2023-12-07 19:47 UTC, tureck1y commented on Tangem/App/Utilities/TransactionHistoryMapper.swift
> +    func transferAmount(from record: TransactionRecord, showSign: Bool) -> String {
может не прикидывать а сделать стейтом маппера?

2023-12-07 19:47 UTC, tureck1y commented on Tangem/Modules/Send/Destination/SendDestinationInputViewModel.swift
> +class SendDestinationInputViewModel: ObservableObject, Identifiable {
не странно ли, что вся вью модель Identifiable? Для чего это нужно?

2023-12-07 19:47 UTC, tureck1y commented on Tangem/Modules/Send/Destination/SendDestinationInputViewModel.swift
> +        errorText: AnyPublisher<Error?, Never>,
Надо обсудить состав конструктора. Много параметров и названия не очень понятны

2023-12-07 19:47 UTC, tureck1y commented on Tangem/Modules/Send/Destination/SendDestinationViewModel.swift
> +protocol SendDestinationViewDelegate: AnyObject {
Надо обсудить зачем нужен делегат и можно ли без него обойтись

2023-12-07 19:47 UTC, tureck1y commented on Tangem/Modules/Send/Destination/SendDestinationViewModel.swift
>  protocol SendDestinationViewModelInput {
наличие и SendDestinationViewModelInput и SendDestinationInputViewModel очень смущает

2023-12-07 19:47 UTC, tureck1y commented on Tangem/Modules/Send/Destination/SendDestinationViewModel.swift
> +        addressViewModel = SendDestinationInputViewModel(
Не уверен что нужны такие перекладывания, очень сложно получается, надо обсудить

2023-12-07 19:47 UTC, tureck1y commented on Tangem/Modules/Send/SendModel.swift
> +    private lazy var transactionHistoryMapper = TransactionHistoryMapper(
Не уверен что это нужно здесь. Это же фича самого экрана, зачем форме ввода уметь маппить транзакции?

2023-12-07 19:47 UTC, tureck1y commented on Tangem/Modules/Send/SendModel.swift
> +    private func otherUserWalletDestinations() -> [SendSuggestedDestinationWallet] {
мне кажется это вообще все отдельным хелпером надо сделать и положить в соответствии вью модель

2023-12-12 08:46 UTC, Andoran90 commented on Tangem/Modules/Send/Destination/SendDestinationInputView.swift
>                      }
слушай, а почему тут во вьюхе идет переключение на основной поток? Зачем оно нужно именно для `PasteButton`?

Сама по себе `PasteButton` отмечена `@MainActor`, значит весь её функционал будет работать на основном потоке, зачем дополнительно переключать на основную очередь ещё?

2023-12-12 08:46 UTC, Andoran90 commented on Tangem/Modules/Send/Destination/SendDestinationInputView.swift
>      }
мне кажется лишним выносить это в отдельное свойство, раз оно не переиспользуется больше и лучше его оставить в основном `body`

2023-12-12 08:46 UTC, Andoran90 commented on Tangem/Modules/Send/Destination/SendDestinationInputViewModel.swift
> +        errorText: AnyPublisher<Error?, Never>,
может объединить все константы в какую-то модельку?

По верстке кажется будто стоит разделить на `SendDestinationAddressView` и `SendDestinationAdditionalInfoView`, но в них дофига одинаковой логики...

2023-12-12 08:46 UTC, Andoran90 commented on Tangem/Modules/Send/Destination/SendDestinationViewModel.swift
> +protocol SendDestinationViewDelegate: AnyObject {
напомните, пожалуйста, почему у нас сейчас все идет через `SendViewModel`?
Сейчас вся информация все время идет через `SendViewModel`, вью модель каждого шага подписывается на изменения напрямую из `SendModel`, но назначает изменения через `SendViewModel`. 

Думаю нам не стоит отказываться от делегатов, но и не надо ходить всегда через `SendViewModel`. Если откажемся от делегатов то каждый экран сможет менять любое свойство `SendModel`

2023-12-13 06:16 UTC, megakoko commented on Tangem/Modules/Send/Destination/SendDestinationInputView.swift
>                      }
Не знаю почему так, но без этого код вызывается в негуёвом потоке

2023-12-18 06:43 UTC, megakoko commented on Tangem/Modules/Send/Destination/SendDestinationInputView.swift
>      }
Так body чище выглядит, не хочется держать там мешанину свойств и вьюх

2023-12-18 06:46 UTC, megakoko commented on Tangem/Modules/Send/Destination/SendDestinationViewModel.swift
>  protocol SendDestinationViewModelInput {
Да вроде норм. Инпут вью модели и вьюмодель инпута

Можно конечно переименовать второе в SendDestinationTextFieldView + SendDestinationTextFieldViewModel или что-то такое

2023-12-18 06:53 UTC, megakoko commented on Tangem/Modules/Send/Destination/SendDestinationViewModel.swift
> +        addressViewModel = SendDestinationInputViewModel(
У нас input-ом служит SendModel, не хочется там создавать такие вьюмодели

2023-12-18 08:33 UTC, megakoko commented on Tangem/Modules/Send/Destination/SendDestinationViewModel.swift
> +protocol SendDestinationViewDelegate: AnyObject {
Ну там есть чисто гуёвые вещи, а есть вещи, которые лучше обрабатывать в SendModel. Чтобы два разных делегата не делать все идет через SendVM

2023-12-18 08:34 UTC, megakoko commented on Tangem/Modules/Send/SendModel.swift
> +    private lazy var transactionHistoryMapper = TransactionHistoryMapper(
Перенес во вьюмодель destination

2023-12-18 08:34 UTC, megakoko commented on Tangem/Modules/Send/SendModel.swift
> +    private func otherUserWalletDestinations() -> [SendSuggestedDestinationWallet] {
Перенес во вьюмодель destination

2023-12-18 08:39 UTC, megakoko commented on Tangem/App/Utilities/TransactionHistoryMapper.swift
> +    func transferAmount(from record: TransactionRecord, showSign: Bool) -> String {
Согласен, переделал

2023-12-18 08:40 UTC, megakoko commented on Tangem/Modules/Send/Destination/SendDestinationInputViewModel.swift
> +class SendDestinationInputViewModel: ObservableObject, Identifiable {
Это надо для островков GroupedSection, принимают identifiable модели

2023-12-18 08:45 UTC, megakoko commented on Tangem/Modules/Send/Destination/SendDestinationInputViewModel.swift
> +        errorText: AnyPublisher<Error?, Never>,
Не, делить не хочу, это по примерно одинаковые вьюхи, только с чуть разным лейаутом

2023-12-18 08:46 UTC, megakoko commented on Tangem/Modules/Send/Destination/SendDestinationInputViewModel.swift
> +        errorText: AnyPublisher<Error?, Never>,
По конструктору не вижу ничего плохого, давайте обсудим что не так

2023-12-22 15:15 UTC, tureck1y commented on Tangem/Modules/Send/Destination/SendDestinationViewModel.swift
>  protocol SendDestinationViewModelInput {
обсудили SendDestinationTextView/ViewModel

2023-12-22 15:24 UTC, tureck1y commented on Tangem/Modules/Send/Destination/SendDestinationInputView.swift
>                      }
давайте коммент оставим в коде

2023-12-22 16:14 UTC, megakoko commented on Tangem/Modules/Send/Destination/SendDestinationInputViewModel.swift
> +        errorText: AnyPublisher<Error?, Never>,
Сделать через TestFieldStyle etc

2023-12-25 09:45 UTC, megakoko commented on Tangem/Modules/Send/Destination/SendDestinationViewModel.swift
>  protocol SendDestinationViewModelInput {
Сделал

2023-12-25 10:47 UTC, megakoko commented on Tangem/Modules/Send/Destination/SendDestinationInputViewModel.swift
> +        errorText: AnyPublisher<Error?, Never>,
Сделал

2023-12-25 10:47 UTC, megakoko commented on Tangem/Modules/Send/Destination/SendDestinationInputView.swift
>                      }
Сделал

2023-12-25 11:06 UTC, megakoko commented
@tureck1y обновил, можно посмотреть

2023-12-27 12:08 UTC, megakoko commented
Тут тоже сейчас делегат занесу в инпут

2023-12-27 17:29 UTC, tureck1y commented on Tangem/App/Utilities/TransactionHistoryMapper.swift
> +    func transferAmount(from record: TransactionRecord, showSign: Bool) -> String {
а что изменилось?

2023-12-27 17:32 UTC, tureck1y approved these changes

2023-12-27 17:32 UTC, merged