IOS-5196 Added TransactionParam validation/parsing service
tangem/tangem-app-ios-old pull request #2431
Opened 2023-11-21 11:27 UTC by megakoko

2023-12-07 16:29 UTC, tureck1y submitted a review, later dismissed

2023-12-12 08:52 UTC, Andoran90 requested changes

2023-12-12 08:52 UTC, Andoran90 commented on Tangem/Modules/Send/SendAdditionalFieldService.swift
> +protocol SendAdditionalFieldService {
может лучше `SendTransactionParametersBuilder`? Отвязаться от `AdditionalField`. 
Да и в целом это не сервис, а утилита, которая из введенного значения и указанного блокчеина делает парамсы. Думаю можно удалить протокол и оставить просто структуру и генерировать её по необходимости. И тут точно не должен быть класс

А то в `SendModel` приватное поле с этим сервисом, который извне ты задать не можешь (протокол бесполезен получается), он нужен в очень редких случаях (т.к. мало в каких сетях есть параметры транзакции), но будет висеть в памяти

2023-12-12 08:52 UTC, Andoran90 commented on Tangem/Modules/Send/SendModel.swift
> +            transactionParameters = try additionalFieldService.transactionParameters(from: _destinationAdditionalFieldText)
вот тут ты можешь создать утилиту, создать параметры и она сразу уничтожится

2023-12-13 11:05 UTC, megakoko commented on Tangem/Modules/Send/SendAdditionalFieldService.swift
> +protocol SendAdditionalFieldService {
Сделал

2023-12-13 11:05 UTC, megakoko commented on Tangem/Modules/Send/SendModel.swift
> +            transactionParameters = try additionalFieldService.transactionParameters(from: _destinationAdditionalFieldText)
Сделал

2023-12-13 11:05 UTC, megakoko commented
@Andoran90 @tureck1y обновил

2023-12-13 13:52 UTC, Andoran90 submitted a review, later dismissed

2023-12-13 13:53 UTC, Andoran90 commented on TangemApp.xcodeproj/project.pbxproj
> +				DA75905F2B0CC3E30016D906 /* SendAdditionalFieldService.swift */,
```suggestion
				DA75905F2B0CC3E30016D906 /* SendTransactionParametersBuilder.swift */,
```

2023-12-13 13:53 UTC, Andoran90 commented on TangemApp.xcodeproj/project.pbxproj
> +				DA75905F2B0CC3E30016D906 /* SendAdditionalFieldService.swift */,
название файла не поменял

2023-12-18 05:10 UTC, megakoko commented on TangemApp.xcodeproj/project.pbxproj
> +				DA75905F2B0CC3E30016D906 /* SendAdditionalFieldService.swift */,
Переименовал

2023-12-18 08:00 UTC, Andoran90 approved these changes, later dismissed

2023-12-25 07:16 UTC, megakoko commented
@tureck1y ping

2023-12-27 17:33 UTC, tureck1y submitted a review, later dismissed
поправь плиз конфликты, смержу завтра

2023-12-28 10:05 UTC, tureck1y approved these changes

2023-12-28 10:05 UTC, merged