IOS-5199 [send screen] demo error + support alert + loading view
tangem/tangem-app-ios-old pull request #2437
Opened 2023-11-22 15:16 UTC by megakoko

2023-12-07 18:43 UTC, tureck1y requested changes

2023-12-07 18:43 UTC, tureck1y commented on Tangem/Modules/Send/SendCoordinator.swift
> +        let userWalletModel: UserWalletModel
только не надо всю модель целиком сюда

2023-12-12 10:26 UTC, Andoran90 commented on Tangem/Modules/Send/SendCoordinator.swift
> +        let userWalletModel: UserWalletModel
хм... наверное надо доработать сбор данных для письма и как раз вытаскивать инфу из репозитория напрямую о текущей карточке активной

2023-12-13 07:44 UTC, megakoko commented on Tangem/Modules/Send/SendCoordinator.swift
> +        let userWalletModel: UserWalletModel
Вынес в протокол, отрефакторил. Надо получать данные в момент создания письма запрашивать из-за number of signed hashes

2023-12-13 07:44 UTC, megakoko commented
@Andoran90 @tureck1y поглядите пожалуйста

2023-12-14 06:37 UTC, Andoran90 commented on Tangem/Modules/Send/SendViewModel.swift
> +    private let walletModel: WalletModel
я так понимаю можно заменить на `isDemo`, раз ничего другое не нужно.

2023-12-14 06:43 UTC, megakoko commented on Tangem/Modules/Send/SendViewModel.swift
> +    private let walletModel: WalletModel
Давай оставим как есть, не хочется на такие мелочи дробить

2023-12-18 08:00 UTC, Andoran90 approved these changes, later dismissed

2023-12-22 17:28 UTC, tureck1y commented on Tangem/Modules/Send/SendViewModel.swift
> +    private let walletModel: WalletModel
Мне тоже кажется избыточно тут и в sendModel держать walletModel. Я бы старался минимизировать. Ну и кстати почему тут demo, мы же полноценно даем сымитировать отправку транзакции в демо режиме

2023-12-25 07:06 UTC, megakoko commented on Tangem/Modules/Send/SendViewModel.swift
> +    private let walletModel: WalletModel
Сымитировать даем, но вместо ошибки показываем сообщение о демо-версии

2023-12-25 11:29 UTC, megakoko commented on Tangem/Modules/Send/SendViewModel.swift
> +    private let walletModel: WalletModel
Там еще для отправки письма в саппорт надо несколько полей из walletModel. Давай не будем дробить

2023-12-27 17:36 UTC, tureck1y submitted a review, later dismissed

2023-12-28 09:03 UTC, tureck1y approved these changes

2023-12-28 09:06 UTC, merged