IOS-4838: Main screen rate app
tangem/tangem-app-ios-old pull request #2516
Opened 2023-12-07 20:38 UTC by m3g0byt3

[IOS-4838](https://tangem.atlassian.net/browse/IOS-4838)

2023-12-14 03:59 UTC, m3g0byt3 commented on Tangem/App/Services/Common/AppSettings.swift
> +    @AppStorageCompat(StorageType.appTheme, store: .standard)
Я не знаю, намеренно ли это было сделано или по ошибке - но в AppStorage для типов, которые конформят `RawRepresentable` и у которых raw value это `String` - не был задано дефолтное значение для параметра store:
https://github.com/tangem/tangem-app-ios/pull/2516/files#diff-f9311beced20963d25ea4c6f78dee2cbfb46c14e9fe5b849800e83c36e1d0a60L296

А это значит, что по умолчанию юзался фоллбек на 297 строке:
`let store = (store ?? .standard)`

и соответственно ключ сохраняется не в `UserDefault(suiteName: AppEnvironment.current.suiteName)`, а в `UserDefault.standard`
---

Такой тип (`RawRepresentable` и у которых raw value это `String`) сейчас в приложении только один и это как раз проперть текущей темы.
Поэтому чтобы ничо не сломать и сохранить текущее поведение (так как у юзеров уже может быть что-то лежать в этом ключе) - указал тут store `standard` явно

2023-12-14 04:02 UTC, m3g0byt3 commented on Tangem/App/Services/RateAppService/Actual/CommonRateAppService.swift
> +    }
По этому ключу уже может лежать факт того, что когда был положительный баланс (засетанный прошлой версией сервиса rate app) - поэтому используем его

2023-12-14 04:03 UTC, m3g0byt3 commented on Tangem/App/Services/RateAppService/Actual/CommonRateAppService.swift
> +            systemReviewPromptRequestDates = systemReviewPromptRequestDates.suffix(storageMaxSize)
Дропаем старые данные (они добавляются конечно со скоростью не более 3 штук в год, но мало ли)

2023-12-14 04:13 UTC, m3g0byt3 commented on Tangem/Common/Storage/AppStorageCompat.swift
> -extension AppStorageCompat where Value == Bool {
Удалил тут всю копипасту, заменив дженерик экстеншеном для поддерживаемых типов отсюда https://developer.apple.com/documentation/foundation/userdefaults/1414067-set for more info.

2023-12-14 04:15 UTC, m3g0byt3 commented on Tangem/Modules/Main/MainViewModel.swift
> +        selectedCardIndexPublisher
Смена воллета может триггернуть условие 

>У пользователя нет активных warning/error notification на кошельке, на котором он находится в момент показа нотификации.

поэтому его необходимо обсервить

2023-12-14 04:17 UTC, m3g0byt3 commented on Tangem/Modules/Main/MainViewModel.swift
> +            .subscribe(loadedBalancesSubject)
Не очень красивый вариант положить новое значение isBalanceLoaded в словарь для конкретного воллета ¯\_(ツ)_/¯

2023-12-14 04:19 UTC, m3g0byt3 commented on Tangem/Modules/Main/MultiWalletMainContent/MultiWalletMainContentViewModel.swift
> +        [userWalletNotificationPublisher, tokensNotificationPublisher]
Шлем отображаемые нотификации в наш делегат (`MainViewModel`)
Аналогичная логика и в `SingleWalletMainContentViewModel`

2023-12-14 04:20 UTC, m3g0byt3 commented on Tangem/Modules/Main/RateAppBottomSheet/RateAppBottomSheetView.swift
> +    /// Therefore `CGFloat` in the range `0...1` is used instead.
`CGFloat` заменее на `Bool` в булку в https://tangem.atlassian.net/browse/IOS-5413

2023-12-14 04:27 UTC, m3g0byt3 commented on Tangem/Modules/Main/RateAppBottomSheet/RateAppBottomSheetView.swift
> +                Image(systemName: Constants.sfSymbolsName)
Кажется, что SF symbols лучше ассетов, потому что они будут масштабироваться при включении доступности.
По форме звезды из ассетов и из SF symbols одинаковы, а размер шрифта подобрал, чтобы было близко к макетам (зеленое макеты, красное SF symbols):

![IMG_9677](https://github.com/tangem/tangem-app-ios/assets/21194149/a821d851-4a90-45bf-a3e4-ce2dd9843f51)

2023-12-14 04:32 UTC, m3g0byt3 commented on Tangem/Resources/Localizations/ru.lproj/Localizable.strings
> +"rate_app_sheet_title" = "Enjoying our app?";
Запросил ru перевод https://tangem.slack.com/archives/C01HARKDLQ0/p1702459428100119

2023-12-14 08:47 UTC, m3g0byt3 commented on Tangem/App/Services/NotificationManagers/ExpressNotifications/ExpressNotificationEvent.swift
> +    var severity: NotificationView.Severity {
Т.к. severity добавлена уже после реализации самих уведомлений - то мне тут нужна помощь, правильно ли я ее распределил для уведомлений экспресса
@Balashov152

2023-12-14 08:48 UTC, m3g0byt3 commented on Tangem/App/Services/NotificationManagers/SingleTokenNotifications/TokenNotificationEvent.swift
> +    var severity: NotificationView.Severity {
И тут аналогично - нужна помощь с определением того, правильно ли я распределил severity для уведомлений в этом месте
@Andoran90

2023-12-14 08:49 UTC, m3g0byt3 commented on Tangem/App/Services/WarningsService/Warnings/WarningEvent.swift
> +    var severity: NotificationView.Severity {
Тут тоже вопрос, правильно ли я распределил severity для уведомлений в этом месте?
Исходя из того, что это `WarningEvent` - я всем назначил `.warning`
Но возможно это неправильно и часть из этих ивентов имеет другую severity?
@Andoran90

2023-12-14 09:17 UTC, Balashov152 commented on Tangem/App/Services/NotificationManagers/ExpressNotifications/ExpressNotificationEvent.swift
> +    var severity: NotificationView.Severity {
А как `severity` повлияет? По какому принципу распределять

2023-12-14 12:34 UTC, m3g0byt3 commented on Tangem/App/Services/NotificationManagers/ExpressNotifications/ExpressNotificationEvent.swift
> +    var severity: NotificationView.Severity {
Ну тот кто заводит нотификацию, должен примерно понимать ее критичность
Я не знаю как еще это определить)

На примере абстрактной свопалки:
- не удалось загрузить рейт - это critical
- price impact is to high - это warning
- fee могут быть от x до y % - это info
ну и тому подобное

Если что, severity (сейчас) не влияет на UI, это семантический атрибут нотификации, который нужен для бизнес-логики

2023-12-18 10:35 UTC, Balashov152 commented on Tangem/App/Services/NotificationManagers/ExpressNotifications/ExpressNotificationEvent.swift
> +        }
```suggestion
        switch self {
        case .permissionNeeded,
             .hasPendingTransaction,
             .hasPendingApproveTransaction,
             .verificationRequired,
             .feeWillBeSubtractFromSendingAmount:
            return .info
        case .notEnoughFeeForTokenTx,
             .notEnoughAmountToSwap,
             .notEnoughBalanceToSwap,
             .noDestinationTokens,
             .highPriceImpact:
            return .warning
        case  .refreshRequired,
                  .cexOperationFailed:
            return .critical
        }
```

2023-12-18 10:35 UTC, Balashov152 commented on Tangem/App/Services/NotificationManagers/ExpressNotifications/ExpressNotificationEvent.swift
> +    var severity: NotificationView.Severity {
> не влияет на UI 
Мне пока это главное )

2023-12-18 10:35 UTC, Balashov152 commented on Tangem/App/Services/NotificationManagers/ExpressNotifications/ExpressNotificationEvent.swift
> +        }
я бы refreshRequired в critical перенес, а отсальное норм

2023-12-20 11:52 UTC, m3g0byt3 commented on Tangem/App/Services/NotificationManagers/ExpressNotifications/ExpressNotificationEvent.swift
> +        }
Спасибо, перенес refreshRequired в critical

2023-12-20 13:10 UTC, Andoran90 commented on Tangem/App/Services/NotificationManagers/SingleTokenNotifications/TokenNotificationEvent.swift
> +        }
```suggestion
        switch self {
        case .noAccount,
              .rentFee,
             .existentialDepositWarning,
             .hasPendingTransactions,
             .notEnoughFeeForTokenTx:
            return .info
        case .someNetworksUnreachable,
             .networkUnreachable,
             .longTransaction:
            return .warning
        }
```

2023-12-20 13:10 UTC, Andoran90 commented on Tangem/App/Services/NotificationManagers/SingleTokenNotifications/TokenNotificationEvent.swift
> +        }
пока думаю так будет, но в целом с Настей не обсудили до конца этот вопрос
```suggestion
        switch self {
        case .noAccount,
             .rentFee,
             .existentialDepositWarning,
             .hasPendingTransactions:
            return .info
        case .networkUnreachable,
             .someNetworksUnreachable,
             .notEnoughFeeForTokenTx
             .longTransaction,:
            return .warning
        }
```

2023-12-20 13:10 UTC, Andoran90 commented on Tangem/App/Services/RateAppService/Legacy/LegacyRateAppService.swift
> +protocol LegacyRateAppService: AnyObject {
а зачем его оставлять? если делаешь полностью новый, то этот удаляй сразу, мы его все равно не используем, оставляли чтобы потом его снова заюзать, но раз не нужен, то можно грохнуть

2023-12-20 13:10 UTC, Andoran90 commented on Tangem/App/Services/WarningsService/Warnings/WarningEvent.swift
> +        }
```suggestion
        switch self {
        case .walletLocked,
            .failedToVerifyCard,
            .devCard:
           return .critical
        case .demoCard,
            .legacyDerivation,
            .systemDerprecationTemporary,
            .missingDerivation,
            .rateApp:
           return .info
        case .numberOfSignedHashesIncorrect,
             .testnetCard,
             .oldDeviceOldCard,
             .oldCard,
             .lowSignatures,
             .systemDeprecationPermanent,
             .missingBackup,
             .supportedOnlySingleCurrencyWallet:
            return .warning
        }
```

2023-12-20 13:10 UTC, Andoran90 commented on Tangem/App/Services/NotificationManagers/ExpressNotifications/ExpressNotificationEvent.swift
> +    var severity: NotificationView.Severity {
вообще в идеале бы потом по этому критерию определять очередность отображения оповещений. Пока что логика такая
1. Critical - восклицательный знак в красном кружке
2. Info - восклицательный знак в синем кружочке
3. Warning - восклицательный знак в желтом треугольнике.

Это пока что очень условное разделение, нет пока что финального решения. По идее сложнее условия, но пока что так разделили + я не понимаю почему у нас инфо идет до ворнинга, как по мне ерунда какая-то, но пока пусть так будет...

2023-12-20 13:10 UTC, Andoran90 commented on Tangem/App/Services/RateAppService/Actual/CommonRateAppService.swift
> +        }
думаю это можно чуть выше поднять (под `isBalanceLoaded`) и написать: 
``` swift
if positiveBalanceAppearanceDate == nil {
    return
}
```

2023-12-20 13:10 UTC, Andoran90 commented on Tangem/Modules/Main/MainCardPageBuilder/MainUserWalletPageBuilderFactory.swift
> +    func createPages(from models: [UserWalletModel], lockedUserWalletDelegate: MainLockedUserWalletDelegate, singleWalletContentDelegate: SingleWalletMainContentDelegate, multiWalletContentDelegate:
не знаю как относиться к таким изменениям) вроде лишнее это все и надо бы делать в отдельном МРе, но мы у нас не хватает времени на такие рефакторинги и хорошо что сделал для более понятного интерфейса...

2023-12-20 13:10 UTC, Andoran90 commented on Tangem/App/Services/RateAppService/Actual/CommonRateAppService.swift
> +    }
хм, такое чувство, будто кто-то другой должен этим заниматься - именно искать `WalletModel` с позитивным балансом, а не этот сервис. Думаю лучше вынести в утилиту, а `registerBalances(of:)` поменять на `registerPositiveBalanceDate()`

2023-12-20 13:10 UTC, Andoran90 commented on Tangem/Modules/Main/MainViewModel.swift
> +    private let notificationInputsSubject: CurrentValueSubject<[Data: [NotificationViewInput]], Never> = .init([:])
хм... надо бы сделать `typealias UserWalletIdData = Data`, чтобы в таких местах было явно о чем речь

2023-12-20 13:10 UTC, Andoran90 commented on Tangem/Modules/Main/Utilities/MainNotificationsObserver.swift
> +    func didChangeNotificationInputs(_ inputs: [NotificationViewInput], forUserWalletWithId userWalletId: UserWalletId)
```suggestion
    func didChangeNotificationInputs(_ inputs: [NotificationViewInput], for userWalletId: UserWalletId)
```

тогда при вызове будет:
``` swift
observer.didChangeNotificationInputs(inputs, for: userWalletModel.userWalletId)
```
Мне кажется так покрасивше

2023-12-20 13:10 UTC, Andoran90 commented on Tangem/App/Services/RateAppService/Actual/RateAppServiceDelegate.swift
> +        _ service: RateAppService,
есть все же сомнения на счет необходимости этого в делегатах. В это не та сущность, у которой ты можешь что-то дополнительно запросить из делегата, да и свойств никаких нет.

2023-12-20 19:20 UTC, tureck1y requested changes
Этот мр надо разбить на 3
- рефак нотификаций
- рефак appstoragecompat
- rate app ( удаление стартого + новый)

2023-12-29 12:23 UTC, tureck1y reviewed
Давайте обсудим вместе @m3g0byt3 @Andoran90. Мне не очень нравится, как прорастает логика оценки по всему приложению. Подумаем что можно сделать.

2023-12-29 12:23 UTC, tureck1y commented on Tangem/App/Services/RateAppService/Legacy/LegacyRateAppService.swift
> +protocol LegacyRateAppService: AnyObject {
конечно, сносим его нафиг и все с ним связанное

2023-12-29 12:23 UTC, tureck1y commented on Tangem/Modules/Main/MainCardPageBuilder/MainUserWalletPageBuilderFactory.swift
> +    func createPages(from models: [UserWalletModel], lockedUserWalletDelegate: MainLockedUserWalletDelegate, singleWalletContentDelegate: SingleWalletMainContentDelegate, multiWalletContentDelegate:
желательно не делать в идеальном мире, в нашем мире только в пределах разумного. Чем меньше и проще пулл, тем быстрее мержится

2023-12-29 12:23 UTC, tureck1y commented on Tangem/Modules/Main/MainCoordinator.swift
> +        let rateAppService = CommonRateAppService()
А почему не в DI? Тогда и делегат наверное не понадобится

2023-12-29 12:23 UTC, tureck1y commented on Tangem/App/Services/RateAppService/Actual/CommonRateAppService.swift
> +    private var userDismissedLastRequestedReview: Bool = false
Прежде мы все такие свойства консолидировали в одном месте. Будем теперь делить?

2024-01-10 08:39 UTC, m3g0byt3 commented on Tangem/App/Services/RateAppService/Actual/CommonRateAppService.swift
> +        }
Заменил на ифчик, поднял повыше и заодно еще сместил проверку нотификаций пониже
Конкретный порядок проверок тут ни на что вроде как не влияет, но в таком случае он становится таким, который указан в задаче

2024-01-10 08:41 UTC, m3g0byt3 commented on Tangem/Modules/Main/MainCardPageBuilder/MainUserWalletPageBuilderFactory.swift
> +    func createPages(from models: [UserWalletModel], lockedUserWalletDelegate: MainLockedUserWalletDelegate, singleWalletContentDelegate: SingleWalletMainContentDelegate, multiWalletContentDelegate:
Я и так вынес все мелкие рефаки и правки кодстайла из этой задачи в отдельную задачу, https://github.com/tangem/tangem-app-ios/pull/2550

Здесь же в аргументах фабричных методов добавился еще один арг, поэтому изменения в любом случае были бы

2024-01-10 08:49 UTC, m3g0byt3 commented on Tangem/App/Services/RateAppService/Actual/RateAppServiceDelegate.swift
> +        _ service: RateAppService,
Как тогда разнести бизнесовую логику (когда показывать алерты и запросы оценки) и презентацию (как показывать алерты и запросы оценки)?

В старом legacy app rate service:
- Не было показа алерта в UI (обычного алерта в приложении, не алерта сторкита), то есть если не выносить презентацию в другую сущность - то UI штуки проникнут в этот сервис
- Размазывалась ответственность между сущностями - в случае позитивного фидбека сторкитовый алерта презентует legacy app rate service, а в случае негативного фидбека email презентует `LegacyMainViewModel`

Если весь вопрос в нейминге - я могу переименовать в `*Presenter` эту сущность, а интерфейс в `*Presenting`

2024-01-10 08:49 UTC, m3g0byt3 commented
> Давайте обсудим вместе @m3g0byt3 @Andoran90. Мне не очень нравится, как прорастает логика оценки по всему приложению. Подумаем что можно сделать.

Пункты на обсудить:
https://github.com/tangem/tangem-app-ios/pull/2516#discussion_r1447057860

2024-01-10 08:50 UTC, m3g0byt3 commented on Tangem/App/Services/RateAppService/Legacy/LegacyRateAppService.swift
> +protocol LegacyRateAppService: AnyObject {
Удалил

2024-01-10 08:54 UTC, m3g0byt3 commented on Tangem/App/Services/RateAppService/Actual/CommonRateAppService.swift
> +    private var userDismissedLastRequestedReview: Bool = false
Я могу занести в AppSettings, мне не принципиально.

Но как по мне, эти свойства не выглядит как именно app settings.

Типичное app settings это когда пользователь в настройках поставил флажок, это записалось на диск и в куче мест в приложении мы читаем этот флажок из `AppSettings.shared` - как например `selectedCurrencyCode`

Здесь же эти проперти - это детали реализации именно этого rate app сервиса, которые не юзаются снаружи

2024-01-10 08:59 UTC, m3g0byt3 commented on Tangem/Modules/Main/Utilities/MainNotificationsObserver.swift
> +    func didChangeNotificationInputs(_ inputs: [NotificationViewInput], forUserWalletWithId userWalletId: UserWalletId)
Заменил, видимо раньше я юзал тут builtin тип (типа Data или Int), для которых рекомендуется задавать больше инфы в arg label ¯\_(ツ)_/¯

2024-01-10 15:21 UTC, m3g0byt3 commented on Tangem/Modules/Main/MainViewModel.swift
> +    private let notificationInputsSubject: CurrentValueSubject<[Data: [NotificationViewInput]], Never> = .init([:])
Добавил, и правда много где внутри этой VM юзалась `Data`
Речь же шла про приватный алиас?

2024-01-11 06:18 UTC, Andoran90 commented on Tangem/Modules/Main/MainCardPageBuilder/MainUserWalletPageBuilderFactory.swift
> +    func createPages(from models: [UserWalletModel], lockedUserWalletDelegate: MainLockedUserWalletDelegate, singleWalletContentDelegate: SingleWalletMainContentDelegate, multiWalletContentDelegate:
да это так, увидел вентилятор крутится, подумал дай подойду, посмотрю красиво крутится или можно украсить 😅

2024-01-11 06:18 UTC, Andoran90 commented on Tangem/Modules/Main/MainViewModel.swift
> +    private let notificationInputsSubject: CurrentValueSubject<[Data: [NotificationViewInput]], Never> = .init([:])
да, все так :) пасиб

2024-01-11 06:22 UTC, Andoran90 commented on Tangem/App/Services/RateAppService/Actual/CommonRateAppService.swift
> +    private var userDismissedLastRequestedReview: Bool = false
вообще тут мне нравится разделение: остальным частям приложения не надо ничего знать про то когда последний раз запрашивали ревью, закрывал ли пользователь ревью или нет и т.д.

2024-01-18 18:56 UTC, tureck1y commented on Tangem/Modules/Main/SingleWalletMainContent/SingleWalletMainContentViewModel.swift
> -            .removeDuplicates()
ничего не оторвет @Andoran90?

2024-01-18 19:54 UTC, m3g0byt3 commented on Tangem/Modules/Main/SingleWalletMainContent/SingleWalletMainContentViewModel.swift
> -            .removeDuplicates()
Это случайно отвалилось, уже вернул)

Правки в процессе, я перезапрошу ревью как закончу

2024-01-19 14:36 UTC, m3g0byt3 commented on Tangem/Modules/Main/SingleWalletMainContent/SingleWalletMainContentRoutable.swift
> +protocol SingleWalletMainContentRoutable: AnyObject {
В SingleWalletMainContentDelegate роутинг запихивать кажется неуместно, в SingleTokenRoutable тоже

2024-01-19 14:39 UTC, m3g0byt3 commented on Tangem/Modules/Main/MultiWalletMainContent/MultiWalletMainContentViewModel.swift
> +        }
Эта логика копипастится между VM, что не очень красиво. 

Но пока у меня нет идей, как можно существенно уменьшить количество копипасты

2024-01-19 14:41 UTC, m3g0byt3 commented on Tangem/Modules/Main/MainCardPageBuilder/MainUserWalletPageBuilder.swift
> +        case .lockedWallet, .visaWallet:
@Andoran90 нужно ли в VM визы аналогично форвардить коллбеки `onPageAppear`/`onPageDisappear`?

2024-01-19 15:34 UTC, Andoran90 commented on Tangem/Modules/Main/MainCardPageBuilder/MainUserWalletPageBuilder.swift
> +        case .lockedWallet, .visaWallet:
нет, там по минимуму функционала, это не для широкого круга пользователей

2024-01-19 15:41 UTC, Andoran90 commented on Tangem/Modules/Main/MultiWalletMainContent/MultiWalletMainContentViewModel.swift
> +        }
а если сделать отдельный хэндлер для экшона и положить его во все вью модели. Внутрь хэндлера передавать зависимость в роутером оценки приложения (может быть `MainCoordinator` может быть роутером? тут вопрос будет ли нормально боттом щит показываться поверх всего) и вью модели будут передавать команду в хэндлер. Но во вью моделях останется логика подписок на оповещения

2024-01-19 15:42 UTC, Andoran90 commented on Tangem/Modules/Main/MultiWalletMainContent/MultiWalletMainContentViewModel.swift
> +        }
что-то похожее у нас уже есть: `SingleTokenRouter`, который хранит в себе логику навигации для мультивалюток и для токен детейлз

2024-01-22 15:32 UTC, m3g0byt3 commented on Tangem/App/Services/RateAppService/RateAppService.swift
> +    enum Constants {
Уменьшил некоторые константы в альфа сборке чтобы QA могли протестить поведение
Надо будет собрать обе сборки, и альфа и бета

2024-01-22 15:34 UTC, m3g0byt3 commented
Добавлен контроллер (RateAppController) с шаренной логикой для rate the app

2024-01-22 15:34 UTC, m3g0byt3 commented on Tangem/Modules/Main/MultiWalletMainContent/MultiWalletMainContentViewModel.swift
> +        }
Обсудили, шаренная логика по возможности вынесена в контроллер

2024-01-23 09:51 UTC, Andoran90 approved these changes, later dismissed
не настаиваю ни на чем 😅

2024-01-23 09:51 UTC, Andoran90 commented on Tangem/Modules/Main/MultiWalletMainContent/MultiWalletMainContentViewModel.swift
> +        isPageSelectedSubject.send(true)
хм, такое чувство, будто в новой реализации можно избавиться от этого паблишера и вместо отправки  инфы в `isPageSelectedSubject`, делать `rateAppController.bind()` с паблишером оповещений. Чтобы `rateAppController` привязывался всегда только к одной странице (убрать там сумку и т.д.)

2024-01-25 07:03 UTC, Andoran90 submitted a review, later dismissed

2024-01-25 09:23 UTC, Balashov152 submitted a review, later dismissed

2024-01-26 17:09 UTC, tureck1y submitted a review, later dismissed

2024-01-26 17:09 UTC, tureck1y commented on Tangem/App/Services/RateAppService/RateAppRoutabe.swift
> +protocol RateAppRoutabe: AnyObject {
NP: RateAppRoutabLe

2024-01-30 21:00 UTC, m3g0byt3 commented on Tangem/App/Services/RateAppService/RateAppRoutabe.swift
> +protocol RateAppRoutabe: AnyObject {
Поправил

2024-01-30 21:01 UTC, m3g0byt3 commented on Tangem/Modules/Main/MultiWalletMainContent/MultiWalletMainContentViewModel.swift
> +        isPageSelectedSubject.send(true)
Переподписка на каждый свайп честно говоря выглядит как овероптимизация + возможность пропустить какой-то ивент, влияющий на условия показа алерта (если паблишер этого ивента например passthrough, а не curr value)

2024-01-30 21:02 UTC, m3g0byt3 commented on Tangem/App/Services/RateAppService/RateAppService.swift
> +    enum Constants {
Откатил)
QA сказали что не нужно ¯\_(ツ)_/¯

2024-01-30 21:16 UTC, tureck1y approved these changes
Решим куда лить

2024-01-30 21:16 UTC, merged