IOS-5316 add promo banners
tangem/tangem-app-ios-old pull request #2533
Opened 2023-12-12 10:13 UTC by megakoko

2023-12-12 11:20 UTC, Andoran90 requested changes

2023-12-12 11:20 UTC, Andoran90 commented on Tangem/App/Services/Common/AppSettings.swift
> +    var crosschainExchangeTokenPromoDismissed: Bool = false
а мы не будем сохранять эту инфу по каждому токену по отдельности?

2023-12-12 11:20 UTC, Andoran90 commented on Tangem/App/Services/NotificationManagers/SingleTokenNotifications/SingleTokenNotificationManager.swift
> +                    setupTangemExpressPromotionNotification(showPromotion: canSwap && canShowTangemExpressPromotion)
тут дублируется `canShowTangemExpressPromotion`, этой подписки не будет, если нельзя показывать промо

2023-12-12 11:20 UTC, Andoran90 commented on Tangem/App/Services/NotificationManagers/SingleTokenNotifications/SingleTokenNotificationManager.swift
> +            swapPairService.canSwap()
вообще не очень получается логика, не очень нравится что это подписка, у тебя же не будет меняться состояние с течением времени, по сути надо 1 раз узнать можно показать оповещение или нет. думаю тут уместнее было бы сделать через асинк.

2023-12-12 11:20 UTC, Andoran90 commented on Tangem/App/Services/NotificationManagers/SingleTokenNotifications/SingleTokenNotificationManager.swift
> +    private func setupTangemExpressPromotionNotification(showPromotion: Bool) {
а зачем тут `showPromotion`? эта штука не должна же то появляться, то исчезать. Она один раз либо появилась, либо нет, а тут в функции создается фабрика, генерируется инпут, чтобы потом понять удаляем мы его или нет. Удаление должно быть внутри `dismissNotification` и думаю больше нигде оно не нужно. Вряд ли будет логика, которая в начале покажет оповещение, а потом сама же его скроет, без участия пользователя.

Думаю тут надо сделать по аналогии с `loadRentNotificationIfNeeded`

2023-12-12 11:20 UTC, Andoran90 commented on Tangem/App/Services/NotificationManagers/UserWalletNotifications/UserWalletNotificationManager.swift
> +        }
промо же должно быть сразу после баланса, а не после всех оповещений или как?

2023-12-12 11:20 UTC, Andoran90 commented on Tangem/App/Services/SwapAvailabilityManager/SwapPairService.swift
> +    func canSwap() -> AnyPublisher<Bool, Never> {
думаю эту всю штуку надо переделать с паблишера на асинк, нам надо один раз получить ответ и все. Надо созвониться и обсудить.
А ещё получился большая функция, которую можно побить, если сделать асинком

2023-12-12 11:20 UTC, Andoran90 commented on Tangem/Modules/Main/MainCoordinator.swift
> +        let swapPairService = SwapPairService(walletModelsManager: cardViewModel.walletModelsManager, userWalletId: cardViewModel.userWalletId.stringValue)
думаю эта генерация должна быть внутри `TokenDetailsCoordinator` в `start` прямо перед созданием `SingleTokenNotificationManager`

2023-12-12 11:20 UTC, Andoran90 commented on Tangem/Modules/Main/MainCoordinator.swift
> +        let swapPairService = SwapPairService(walletModelsManager: cardViewModel.walletModelsManager, userWalletId: cardViewModel.userWalletId.stringValue)
и тогда это дублирование уйдет.

2023-12-12 11:20 UTC, Andoran90 commented on Tangem/Modules/TokenDetails/TokenDetailsCoordinator.swift
> +        let swapPairService = SwapPairService(walletModelsManager: cardViewModel.walletModelsManager, userWalletId: cardViewModel.userWalletId.stringValue)
а ещё вот это удалится.

2023-12-12 11:20 UTC, Andoran90 commented on Tangem/UIComponents/NotificationView/NotificationView+Settings.swift
> +                return .white
`Colors.Text.Constant` не затащили?

2023-12-12 11:20 UTC, Andoran90 commented on Tangem/UIComponents/NotificationView/NotificationView+Settings.swift
> +        case swap
давай лучше `expressPromo`, а то в свопе много оповещений, но ни один из них не должен быть таким. А ещё лучше было бы, наверное, сделать `case custom(ColorSettings)`

``` swift
protocol ColorSettings {
    var background: some View { get }
    var dismissButtonColor: Color { get }
    var titleColor: Color { get }
    var messageColor: Color { get }
}
```

2023-12-12 11:59 UTC, megakoko commented on Tangem/UIComponents/NotificationView/NotificationView+Settings.swift
> +        case swap
Пока просто переименовал

2023-12-12 11:59 UTC, megakoko commented on Tangem/UIComponents/NotificationView/NotificationView+Settings.swift
> +                return .white
Сделал

2023-12-12 12:41 UTC, megakoko commented on Tangem/App/Services/NotificationManagers/SingleTokenNotifications/SingleTokenNotificationManager.swift
> +            swapPairService.canSwap()
Сделал как обговорили

2023-12-12 12:41 UTC, megakoko commented on Tangem/App/Services/NotificationManagers/SingleTokenNotifications/SingleTokenNotificationManager.swift
> +                    setupTangemExpressPromotionNotification(showPromotion: canSwap && canShowTangemExpressPromotion)
Убрал

2023-12-12 12:41 UTC, megakoko commented on Tangem/App/Services/NotificationManagers/SingleTokenNotifications/SingleTokenNotificationManager.swift
> +    private func setupTangemExpressPromotionNotification(showPromotion: Bool) {
Сделал

2023-12-12 12:42 UTC, megakoko commented on Tangem/App/Services/NotificationManagers/UserWalletNotifications/UserWalletNotificationManager.swift
> +        }
Сделал

2023-12-12 12:42 UTC, megakoko commented on Tangem/App/Services/NotificationManagers/UserWalletNotifications/UserWalletNotificationManager.swift
> +        }
Должно быть первым

2023-12-12 12:42 UTC, megakoko commented on Tangem/App/Services/SwapAvailabilityManager/SwapPairService.swift
> +    func canSwap() -> AnyPublisher<Bool, Never> {
Сделал

2023-12-12 12:42 UTC, megakoko commented on Tangem/Modules/Main/MainCoordinator.swift
> +        let swapPairService = SwapPairService(walletModelsManager: cardViewModel.walletModelsManager, userWalletId: cardViewModel.userWalletId.stringValue)
Перенес

2023-12-12 12:43 UTC, megakoko commented on Tangem/Modules/Main/MainCoordinator.swift
> +        let swapPairService = SwapPairService(walletModelsManager: cardViewModel.walletModelsManager, userWalletId: cardViewModel.userWalletId.stringValue)
Угумс

2023-12-12 12:43 UTC, megakoko commented on Tangem/Modules/TokenDetails/TokenDetailsCoordinator.swift
> +        let swapPairService = SwapPairService(walletModelsManager: cardViewModel.walletModelsManager, userWalletId: cardViewModel.userWalletId.stringValue)
`+`

2023-12-12 13:24 UTC, Andoran90 commented on Tangem/App/Services/NotificationManagers/SingleTokenNotifications/SingleTokenNotificationManager.swift
> +                    self.notificationInputsSubject.value.append(input)
оно разве не в начало должно тоже тут вставляться?

2023-12-12 13:24 UTC, Andoran90 commented on Tangem/App/Services/SwapAvailabilityManager/SwapPairService.swift
> +    let walletModel: WalletModel
наверное можно обойтись либо `TokenItem`, либо `ExpressCurrency`?

2023-12-12 16:20 UTC, tureck1y reviewed
👀

2023-12-13 05:03 UTC, megakoko commented on Tangem/App/Services/NotificationManagers/SingleTokenNotifications/SingleTokenNotificationManager.swift
> +                    self.notificationInputsSubject.value.append(input)
Спасибо, поправил

2023-12-13 05:03 UTC, megakoko commented on Tangem/App/Services/SwapAvailabilityManager/SwapPairService.swift
> +    let walletModel: WalletModel
Сделал expresscurrency

2023-12-13 05:27 UTC, megakoko commented
@Andoran90 @tureck1y обновил, потестировал — все работает

2023-12-13 05:49 UTC, Andoran90 submitted a review, later dismissed

2023-12-13 10:22 UTC, Andoran90 commented on Tangem/App/Services/Analytics/Analytics+Event.swift
> +        case swapPromoClosed = "[Swap Promo] Button - Close"
давай как в других ивентах:
`swapPromoButtonExchangeNow`
`swapPromoButtonClose`

Чтобы проще было искать нужные ивенты и мапить их

2023-12-13 10:22 UTC, Andoran90 commented on Tangem/Modules/Main/Utilities/SingleTokenRouter.swift
> +
давай не будем лучше усложнять интерфейс, аналитика она же про нажатие кнопки, а не про навигацию. Там где обработали нажатие кнопки, там и отправили событие в аналитику

2023-12-13 10:22 UTC, Andoran90 commented on Tangem/Modules/Main/Utilities/SingleTokenRouter.swift
> +
В `TokenDetailsViewModel` в функции `didTapNotificationButton` можно добавить отправку события и тогда никакие дополнительные действия не нужны будут

2023-12-13 10:54 UTC, megakoko commented on Tangem/App/Services/Analytics/Analytics+Event.swift
> +        case swapPromoClosed = "[Swap Promo] Button - Close"
cделал

2023-12-13 10:54 UTC, megakoko commented on Tangem/Modules/Main/Utilities/SingleTokenRouter.swift
> +
сделал

2023-12-13 10:59 UTC, Andoran90 approved these changes

2023-12-13 11:31 UTC, tureck1y approved these changes

2023-12-13 11:31 UTC, tureck1y commented on Tangem/App/Services/NotificationManagers/SingleTokenNotifications/SingleTokenNotificationManager.swift
> +    private func setupTangemExpressPromotionNotification() {
Мне конечно не нравится архитектурно как получилось. Нужен класс, который возьмет в себя всю эту логику. А тут получается что вроде как есть swapPairService, в котором есть часть логики и часть логики лежит тут. Одна ответственность размазана по двум сущностям.  С учетом временного характера этого кода и того что торопимся оставляем так. В будущем надо такого избегать

2023-12-13 11:37 UTC, merged

2023-12-13 11:37 UTC, Andoran90 commented on Tangem/App/Services/NotificationManagers/SingleTokenNotifications/SingleTokenNotificationManager.swift
> +    private func setupTangemExpressPromotionNotification() {
ммм, не совсем понял тебя, в сервисе лежит вся логика обработки можно ли свапать или нет. Тут лежит логика генерации самого оповещения и запроса надо ли его показать. Или ты про `canShowTangemExpressPromotion`?
Согласен что `canShowTangemExpressPromotion` можно вынести отсюда.

2023-12-13 11:40 UTC, Andoran90 commented on Tangem/App/Services/NotificationManagers/SingleTokenNotifications/SingleTokenNotificationManager.swift
> +    private func setupTangemExpressPromotionNotification() {
у меня вообще была идея ещё сделать сервис, который запрашивает доступные пары для какой-то монеты, чтобы этот сервис можно было заюзать в свапалке, а не через `ExpressManager` все делать. Ну и вообще, сделать несколько сервисов, которые отвечают за разные части экспресса (загрузка ассетов, загрузка провайдеров, загрузка пар и т.д.), чтобы это все были атомарные сервисы и их можно было спокойно закидывать на любой экран, где она понадобится. Сейчас так произошло с парами, потом может ещё с другим запросом

2023-12-13 11:44 UTC, tureck1y commented on Tangem/App/Services/NotificationManagers/SingleTokenNotifications/SingleTokenNotificationManager.swift
> +    private func setupTangemExpressPromotionNotification() {
Как минимум, есть обращения к Appsettings, какие-то таски. В идеале нотификейшен менеджер должен спросить у ясеня булку можно ли показать и запросить уже готовый нотификейшен. Возможно, надо расширять этот менеджер какими-то плагинами, это на подумать скорее.