IOS-5564 send done using the correct UI
tangem/tangem-app-ios-old pull request #2664
Opened 2024-01-09 12:24 UTC by megakoko

Теперь на summary / finish нормальные вьюхи. Плюс чуток порефакторил

2024-01-10 05:57 UTC, Andoran90 requested changes
не ленись, пожалуйста, и к каждому МРу, который затрагивает UI делай скриншоты, а если какие-то анимации есть или переходы от одной вьюхи к другой, делай запись экрана. Это не такая большая сложность, не первый раз уже прошу об этом.

А зачем конфиг обновил?

2024-01-10 05:57 UTC, Andoran90 commented on Tangem/Modules/Send/Finish/SendFinishView.swift
> +                .transition(.asymmetric(insertion: .move(edge: .leading), removal: .opacity.combined(with: .scale)))
запиши видосы, пожалуйста, что поменялось или как теперь выглядит, не особо понятно

2024-01-10 05:57 UTC, Andoran90 commented on Tangem/Modules/Send/Finish/SendFinishView.swift
> +                GroupedSection(viewModel.destinationViewTypes) { type in
а норм что `amount` и `destination` поменялись местами?

2024-01-10 05:57 UTC, Andoran90 commented on Tangem/Modules/Send/SendSummarySectionViewModelFactory.swift
> +            amountFiat = fiatValue.currencyFormatted(code: AppSettings.shared.selectedCurrencyCode, maximumFractionDigits: 2)
используй `BalanceFormatter`, там есть форматирование для опционального значения тоже.

2024-01-10 05:57 UTC, Andoran90 commented on Tangem/Modules/Send/SendSummarySectionViewModelFactory.swift
> +            amountFiat: amountFiat ?? "",
сделай через `BalanceFormatter` и не будет опциональной строки

2024-01-10 05:57 UTC, Andoran90 commented on Tangem/Modules/Send/SendViewModel.swift
> +        walletInfo = SendWalletInfo(
жесть, какой огромный инициализатор у `SendViewModel`... будто бы можно вынести создание `SendWalletInfo` за пределы и положить `WalletModel` внутрь, но это так, мыслишки

2024-01-10 05:57 UTC, Andoran90 commented on Tangem/Modules/Send/SendViewModel.swift
> +    }
хм, думаю это можно добавить публично (на дейлике 😅) в `WalletModel`, периодически нужно такое свойство

2024-01-10 05:57 UTC, Andoran90 commented on Tangem/Modules/Send/Summary/SendSummaryView.swift
> +            GroupedScrollView {
а вот это можно было и разделить, чтобы не делать большой МР. отдельно саммари и отдельно финишный экран

2024-01-10 05:57 UTC, Andoran90 commented on Tangem/Modules/Send/Summary/SendSummaryViewModel.swift
> +            .map { [weak self] destination, additionalField in
красивее получается через `.withWeakCaptureOf(self)`, заодно не будет дальше опционала по коду

2024-01-10 06:47 UTC, megakoko commented
@Andoran90 так выглядит теперь

https://github.com/tangem/tangem-app-ios/assets/12209839/ec1a9bcd-a2e3-4004-9388-af03207ce2be

2024-01-10 06:51 UTC, megakoko commented on Tangem/Modules/Send/Finish/SendFinishView.swift
> +                GroupedSection(viewModel.destinationViewTypes) { type in
Да, мы экраны переставили

2024-01-10 06:52 UTC, megakoko commented
Конфиг обновил потому что в девелопе неактуальная версия

2024-01-10 06:52 UTC, megakoko commented on Tangem/Modules/Send/SendViewModel.swift
> +        walletInfo = SendWalletInfo(
Согласен, но сейчас рефакторить не хочется т.к. много чего параллельно идет. Можно ближе к концу разработки подумать

2024-01-10 18:24 UTC, tureck1y requested changes

2024-01-10 18:24 UTC, tureck1y commented on tangem-app-config
наверное лишнее?

2024-01-10 18:24 UTC, tureck1y commented on Tangem/Modules/Send/SendModel.swift
> +    var additionalFieldPublisher: AnyPublisher<(SendAdditionalFields, String)?, Never> {
может string завернуть в SendAdditionalFields как associated value? Тяжеловато tuple читается

2024-01-10 18:24 UTC, tureck1y commented on Tangem/Modules/Send/SendSummarySectionViewModelFactory.swift
> +    private var feeFormatter: SwappingFeeFormatter {
почему сваппинг тут? Наведите порядок в форматтерах пожалуйста вместе с @Balashov152

2024-01-10 18:24 UTC, tureck1y commented on Tangem/Modules/Send/SendViewModel.swift
> +    }
тем более оно уже практически там есть

2024-01-10 18:24 UTC, tureck1y commented on Tangem/Modules/Send/Summary/SendSummaryViewModel.swift
> +    var tokenItem: TokenItem { get }
А зачем тут tokenItem? Как он дальше используется? Не очень понимаю зачем в стенде такая низкоуровневая штука, нужно максимально walletModel юзать

2024-01-10 18:24 UTC, tureck1y commented on Tangem/Modules/Send/Summary/SendSummaryViewModel.swift
> +            .map { [weak self] destination, additionalField in
да это много где в этом мр можно использовать

2024-01-11 05:00 UTC, megakoko commented on Tangem/Modules/Send/Summary/SendSummaryViewModel.swift
> +            .map { [weak self] destination, additionalField in
Мне не нравится, лишние параметры появляются, неявно к self не обратиться

2024-01-11 05:23 UTC, megakoko commented on Tangem/Modules/Send/SendSummarySectionViewModelFactory.swift
> +            amountFiat = fiatValue.currencyFormatted(code: AppSettings.shared.selectedCurrencyCode, maximumFractionDigits: 2)
Сделал

2024-01-11 05:23 UTC, megakoko commented on Tangem/Modules/Send/SendSummarySectionViewModelFactory.swift
> +            amountFiat: amountFiat ?? "",
Сделал

2024-01-11 05:23 UTC, megakoko commented on Tangem/Modules/Send/Finish/SendFinishView.swift
> +                .transition(.asymmetric(insertion: .move(edge: .leading), removal: .opacity.combined(with: .scale)))
Ниже приложил

2024-01-11 05:35 UTC, megakoko commented on Tangem/Modules/Send/SendViewModel.swift
> +    }
Сделал через tokenitem

2024-01-11 05:36 UTC, megakoko commented on Tangem/Modules/Send/Summary/SendSummaryView.swift
> +            GroupedScrollView {
Зачем, это почти одни и те же яйца, только первый экран на паблишерах, а второй на константах

2024-01-11 05:36 UTC, megakoko commented on tangem-app-config
Обновил до последней версии чтобы 10 раз не дергать конфиг

2024-01-11 05:38 UTC, megakoko commented on Tangem/Modules/Send/SendModel.swift
> +    var additionalFieldPublisher: AnyPublisher<(SendAdditionalFields, String)?, Never> {
Тоже не нравится, но рефакторить старое не хочется, давай в TODO добавим. Там надо еще SendAdditionalFields.none убрать.

2024-01-11 05:42 UTC, megakoko commented on Tangem/Modules/Send/Summary/SendSummaryViewModel.swift
> +    var tokenItem: TokenItem { get }
Нужно максимально WalletModel использовать или же передавать только те поля, что надо?

TokenItem идет дальше в форматтер комиссии

2024-01-11 05:53 UTC, megakoko commented on Tangem/Modules/Send/SendSummarySectionViewModelFactory.swift
> +    private var feeFormatter: SwappingFeeFormatter {
https://github.com/tangem/tangem-app-ios/pull/2681

2024-01-11 08:27 UTC, Balashov152 commented on Tangem/Modules/Send/SendSummarySectionViewModelFactory.swift
> +    private var feeFormatter: SwappingFeeFormatter {
Я в удалении свапалки переименовал в FeeFormatter тоже. Будет один на всех

2024-01-11 08:54 UTC, megakoko commented
@Andoran90 @tureck1y можно посмотреть

2024-01-11 11:02 UTC, tureck1y commented on Tangem/Modules/Send/Summary/SendSummaryViewModel.swift
> +    var tokenItem: TokenItem { get }
зачем форматтеру комиссий tokenItem?

2024-01-11 11:02 UTC, tureck1y commented on Tangem/Modules/Send/SendModel.swift
> +    var additionalFieldPublisher: AnyPublisher<(SendAdditionalFields, String)?, Never> {
ок, давай TODO сделаем

2024-01-11 11:04 UTC, tureck1y commented on Tangem/Modules/Send/Summary/SendSummaryViewModel.swift
> +    var tokenItem: TokenItem { get }
Эта штука нужна для работы с токенами. Лучше сразу сформировать форматтер, чем переделать что-то, чтобы его сформировать. Ну и если уже надо что-то вытаскивать из tokenItem, то можно вытащить сразу

2024-01-11 11:17 UTC, megakoko commented on Tangem/Modules/Send/Summary/SendSummaryViewModel.swift
> +    var tokenItem: TokenItem { get }
> зачем форматтеру комиссий tokenItem?

Это уже существующий форматтер, tokenItem нужна для вызова метода, не для конструктора

2024-01-11 11:22 UTC, megakoko commented on Tangem/Modules/Send/SendModel.swift
> +    var additionalFieldPublisher: AnyPublisher<(SendAdditionalFields, String)?, Never> {
Добавил в табличку техдолга

2024-01-12 04:31 UTC, Andoran90 commented on Tangem/Modules/Send/SendSummarySectionViewModelFactory.swift
> +            amountFiat = AppConstants.dashSign
лучше из форматтера брать, чтобы палки не отличались, т.к. в остальных местах опциональное значение фиатное передается в форматтер и он возвращает либо прочерк, либо отформатированное значение, а тут разная логика, ты же не стал в форматтер добавлять `AppConstants.dashSign`

2024-01-12 04:31 UTC, Andoran90 commented on Tangem/Modules/Send/Summary/SendSummaryViewModel.swift
> +            .map { [weak self] destination, additionalField in
хм, а где ты неявно обращаешься к `self`? тут ты создаешь опционал, потом заменяешь его дефолным значением, ладно если бы разворачивал через `guard`, но ты же этого не далаешь и оставляешь чеининг опциональный. У тебя вместо `[weak self]` будет `viewModel`, те же яйца, только без опционала.

2024-01-12 08:20 UTC, megakoko commented on Tangem/Modules/Send/SendSummarySectionViewModelFactory.swift
> +            amountFiat = AppConstants.dashSign
По дизайну нужна такая палка для кастомных токенов

2024-01-12 08:22 UTC, megakoko commented on Tangem/Modules/Send/Summary/SendSummaryViewModel.swift
> +            .map { [weak self] destination, additionalField in
Я не про этот конкретно кейс а в общем

Зачем self менять на viewModel и думать потом что это за viewModel такой если можно спокойно использовать self?  В опционалах ничего страшного нет

2024-01-12 10:47 UTC, megakoko commented on Tangem/Modules/Send/Summary/SendSummaryViewModel.swift
> +    var tokenItem: TokenItem { get }
отрефакторить

2024-01-12 11:19 UTC, Andoran90 submitted a review, later dismissed

2024-01-12 13:11 UTC, megakoko commented on Tangem/Modules/Send/Summary/SendSummaryViewModel.swift
> +    var tokenItem: TokenItem { get }
Отрефакторил https://github.com/tangem/tangem-app-ios/pull/2664/commits/eb1a582301dfdadf33ef4c572a5d510b8cc071ac

2024-01-12 13:51 UTC, megakoko commented on Tangem/Modules/Send/Summary/SendSummaryViewModel.swift
> +    var tokenItem: TokenItem { get }
@Andoran90 @tureck1y отрефакторил, можно посмотреть

2024-01-12 17:49 UTC, tureck1y approved these changes

2024-01-15 06:12 UTC, Andoran90 approved these changes

2024-01-15 07:38 UTC, merged