IOS-5075: Visa main screen
tangem/tangem-app-ios-old pull request #2665
Opened 2024-01-09 12:39 UTC by Andoran90

Пока что логика захардкожена, будет обновлена при интеграции взаимодействия со смарт-контрактом. Для визы тотал баланс показывается в крипте, а фиатный показывается в подзаголовке. Договорились что все текстовки хардкодим и плюем на потенциальные расхождения между иОС и андроид. 

<img width="300" src="https://github.com/tangem/tangem-app-ios/assets/24321494/9d273a38-6a06-44a5-a161-d69e8ac78614">

2024-01-10 06:31 UTC, skibinalexander commented on Tangem/App/Models/UserWallet/Implementations/VisaConfig.swift
>          return [entry]
let visaToken = VisaUtilities().visaToken
[visaToken]

2024-01-10 06:40 UTC, skibinalexander commented on Tangem/App/Services/TotalBalanceProvider/SingleTokenTotalBalanceProvider.swift
> +                case .loading, .created:
по идее можно через filter цепочку сделать

2024-01-10 06:44 UTC, skibinalexander commented on Tangem/App/Services/TotalBalanceProvider/SingleTokenTotalBalanceProvider.swift
> +                    balanceProvider.totalBalanceSubject.send(
А это ок, что мы в провайдер что-то пушим? По идее провайдер провайдит данные

2024-01-10 06:47 UTC, skibinalexander commented on Tangem/App/Utilities/Visa/VisaUtilities.swift
> +        let blockchain = Blockchain.polygon(testnet: true)
Как будто бы хочется глобальный Стейт для этого, что именно на полигоне

2024-01-10 06:48 UTC, skibinalexander commented on Tangem/App/Utilities/Visa/VisaUtilities.swift
> +            fatalError("Visa failed to find mandatory Visa wallet model")
Я бы через exception throw сделал бы, странно что fatal error торчит

2024-01-10 06:49 UTC, skibinalexander commented on Tangem/Modules/Main/MainCardPageBuilder/MainUserWalletPageBuilderFactory.swift
> +        if model.config is VisaConfig {
Может это в Стейт какой-то?

2024-01-10 17:41 UTC, tureck1y requested changes

2024-01-10 17:41 UTC, tureck1y commented on Tangem/App/Factories/WalletManagers/VisaWalletManagerFactory.swift
> +        return try VisaUtilities().getWalletManager(keys: keys)
а зачем это в утилите держать?

2024-01-10 17:41 UTC, tureck1y commented on Tangem/Modules/Main/MainCardPageBuilder/MainUserWalletPageBuilderFactory.swift
> +    let visaCoordinator: VisaWalletRoutable
надо ли под визу отдельный координатор прям?

2024-01-10 17:41 UTC, tureck1y commented on Tangem/Modules/Main/MainCardPageBuilder/MainUserWalletPageBuilderFactory.swift
> +        if model.config is VisaConfig {
Давай заведем задачу на рефак этой фабрики. А то протоколом закрыта, а внутри все в кучу и синглы и мульти и виза теперь

2024-01-10 17:41 UTC, tureck1y commented on Tangem/Modules/Main/MainHeaderView/MainHeaderBalanceProvider/MainHeaderBalanceProviderFactory.swift
> +        if model.config is VisaConfig,
тут как-будто тоже уровня абстракции не хватает. Отдельную хочется фабрику для визы, как и в MainHeaderSubtitleProviderFactory

2024-01-11 05:59 UTC, Andoran90 commented on Tangem/App/Models/UserWallet/Implementations/VisaConfig.swift
>          return [entry]
хм, вроде бы хотел чтобы все манипуляции лежали в утилите и удобно было их просматривать в одном месте, но согласен, тут правильнее оно будет. перенес сюда

2024-01-11 05:59 UTC, Andoran90 commented on Tangem/App/Services/TotalBalanceProvider/SingleTokenTotalBalanceProvider.swift
> +                case .loading, .created:
updated

2024-01-11 05:59 UTC, Andoran90 commented on Tangem/App/Utilities/Visa/VisaUtilities.swift
> +        let blockchain = Blockchain.polygon(testnet: true)
провайдер это ссылка на самого себя, которая ловится через `withWeakCaptureOf(self)`, т.е. это то же самое что и `self.totalBalanceSubject.send`

2024-01-11 05:59 UTC, Andoran90 commented on Tangem/App/Services/TotalBalanceProvider/SingleTokenTotalBalanceProvider.swift
> +                    balanceProvider.totalBalanceSubject.send(
думаю нет смысла, т.к. все равно нужен будет свитч, чтобы определить что отправлять для остальных состояний

2024-01-11 05:59 UTC, Andoran90 commented on Tangem/Modules/Main/MainCardPageBuilder/MainUserWalletPageBuilderFactory.swift
> +        if model.config is VisaConfig {
ммммм, сделал через фаталочку, чтобы не протаскивать выбрасывание ошибок до `MainViewModel`. Вообще надо переделать фабрику экранов, потому что сейчас есть варианты, когда открывается пустой экран (`UserWalletModel` есть, для одновалютной карточки, но а `WalletModel` нет по какой-то причине, в итоге может открыться главная с пустым экраном), думаю сделаю это все вместе с рефакторингом `MainUserWalletPageBuilderFactory`

2024-01-11 05:59 UTC, Andoran90 commented on Tangem/App/Utilities/Visa/VisaUtilities.swift
> +            fatalError("Visa failed to find mandatory Visa wallet model")
ну оно по идее нужно только для создания `WalletManager`, дальше вся инфа будет на экранах браться из `WalletModel`, но давай сделаю по аналогии с визовским токеном, тоже приложу его в утилиту

2024-01-11 05:59 UTC, Andoran90 commented on Tangem/App/Factories/WalletManagers/VisaWalletManagerFactory.swift
> +        return try VisaUtilities().getWalletManager(keys: keys)
там всего будет 3 варианта:
1. Переход в эксплорер для адреса
2. переход в эксплорер для одной транзакции
3. Показ адреса кошелька

Не особо хочется давать `MainContentRoutable`, потому что там и переходы на органайз, на менедж токенс, на деталку токена. Это все не должно быть доступно для визы. Думаю лучше дать по минимуму, только то что надо визе

2024-01-11 05:59 UTC, Andoran90 commented on Tangem/Modules/Main/MainCardPageBuilder/MainUserWalletPageBuilderFactory.swift
> +    let visaCoordinator: VisaWalletRoutable
я вот думаю как бы это оформить. Можно сделать отдельную приватную функцию по созданию фабрики исходя из `UserWalletModel` и сделать для каждого типа главной свою фабрику...

2024-01-11 05:59 UTC, Andoran90 commented on Tangem/Modules/Main/MainHeaderView/MainHeaderBalanceProvider/MainHeaderBalanceProviderFactory.swift
> +        if model.config is VisaConfig,
ну в любом случае кто-то должен будет определять какую фабрику создать. Мне кажется тут фабричной функции достаточно,  думаю в плане количества и понятности кода мы не выиграем, если перейдем с фабричной функции на абстрактную фабрику.

Если в эти два места закрыть протоколами:
``` swift
protocol MainHeaderBalanceProviderBuilder {
    func buildProvider(for model: UserWalletModel) -> MainHeaderBalanceProvider
}

protocol MainHeaderSubtitleProviderBuilder {
    func buildProvider(for model: UserWalletModel) -> MainHeaderSubtitleProvider
}
```

нам надо будет сделать ещё для каждого реализацию каждого билдера и потом все равно внутри `CommonMainUserWalletPageBuilderFactory` будет куча ифчиков, которые будут определять какой билдер создать.
Я специально создал эти фабрики, чтобы инкапсулировать логику определения типов провайдеров в одном месте.

Ты такую реализацию имеешь ввиду? Если нет, то надо обсудить какой есть ещё вариант, я пока что не придумал...

2024-01-11 06:00 UTC, Andoran90 commented
блэт, почему-то комменты в неправильные места запостились О_о

2024-01-11 06:01 UTC, Andoran90 commented on Tangem/App/Utilities/Visa/VisaUtilities.swift
> +            fatalError("Visa failed to find mandatory Visa wallet model")
ммммм, сделал через фаталочку, чтобы не протаскивать выбрасывание ошибок до MainViewModel. Вообще надо переделать фабрику экранов, потому что сейчас есть варианты, когда открывается пустой экран (UserWalletModel есть, для одновалютной карточки, но а WalletModel нет по какой-то причине, в итоге может открыться главная с пустым экраном), думаю сделаю это все вместе с рефакторингом MainUserWalletPageBuilderFactory

2024-01-11 06:02 UTC, Andoran90 commented on Tangem/App/Services/TotalBalanceProvider/SingleTokenTotalBalanceProvider.swift
> +                    balanceProvider.totalBalanceSubject.send(
провайдер это ссылка на самого себя, которая ловится через withWeakCaptureOf(self), т.е. это то же самое что и self.totalBalanceSubject.send

2024-01-11 06:02 UTC, Andoran90 commented on Tangem/App/Services/TotalBalanceProvider/SingleTokenTotalBalanceProvider.swift
> +                case .loading, .created:
думаю нет смысла, т.к. все равно нужен будет свитч, чтобы определить что отправлять для остальных состояний

2024-01-11 06:02 UTC, Andoran90 commented on Tangem/App/Models/UserWallet/Implementations/VisaConfig.swift
>          return [entry]
обновил

2024-01-11 06:02 UTC, Andoran90 commented on Tangem/App/Factories/WalletManagers/VisaWalletManagerFactory.swift
> +        return try VisaUtilities().getWalletManager(keys: keys)
хм, вроде бы хотел чтобы все манипуляции лежали в утилите и удобно было их просматривать в одном месте, но согласен, тут правильнее оно будет. перенес сюда

2024-01-11 06:03 UTC, Andoran90 commented on Tangem/App/Utilities/Visa/VisaUtilities.swift
> +        let blockchain = Blockchain.polygon(testnet: true)
ну оно по идее нужно только для создания WalletManager, дальше вся инфа будет на экранах браться из WalletModel, но давай сделаю по аналогии с визовским токеном, тоже приложу его в утилиту

2024-01-11 06:04 UTC, Andoran90 commented on Tangem/Modules/Main/MainCardPageBuilder/MainUserWalletPageBuilderFactory.swift
> +    let visaCoordinator: VisaWalletRoutable
там всего будет 3 варианта:

1. Переход в эксплорер для адреса
2. переход в эксплорер для одной транзакции
3. Показ адреса кошелька

Не особо хочется давать MainContentRoutable, потому что там и переходы на органайз, на менедж токенс, на деталку токена. Это все не должно быть доступно для визы. Думаю лучше дать по минимуму, только то что надо визе

2024-01-11 06:05 UTC, Andoran90 commented on Tangem/Modules/Main/MainCardPageBuilder/MainUserWalletPageBuilderFactory.swift
> +        if model.config is VisaConfig {
я вот думаю как бы это оформить. Можно сделать отдельную приватную функцию по созданию фабрики исходя из UserWalletModel и сделать для каждого типа главной свою фабрику...

2024-01-11 06:26 UTC, skibinalexander commented on Tangem/App/Services/TotalBalanceProvider/SingleTokenTotalBalanceProvider.swift
> +                    balanceProvider.totalBalanceSubject.send(
> провайдер это ссылка на самого себя, которая ловится через `withWeakCaptureOf(self)`, т.е. это то же самое что и `self.totalBalanceSubject.send`

Ага, не увидел

2024-01-11 09:30 UTC, skibinalexander submitted a review, later dismissed
По своим комменты все ответы есть, я так понял на рефакторинг уйдет

2024-01-11 11:07 UTC, tureck1y commented on Tangem/Modules/Main/MainCardPageBuilder/MainUserWalletPageBuilderFactory.swift
> +        if model.config is VisaConfig {
да, надо подумать на базе  чего абстрактная фабрика будет решение принимать, ну либо по конфигам распихать, чтобы они давали нужные фабрики

2024-01-11 11:11 UTC, tureck1y commented on Tangem/Modules/Main/MainCardPageBuilder/MainUserWalletPageBuilderFactory.swift
> +    let visaCoordinator: VisaWalletRoutable
может` let coordinator: MainContentRoutable &  VisaWalletRoutable?`

2024-01-12 04:09 UTC, Andoran90 commented on Tangem/Modules/Main/MainCardPageBuilder/MainUserWalletPageBuilderFactory.swift
> +        if model.config is VisaConfig {
я тоже думал про конфиги, но мне идея не понравилась, т.к. конфиги будут знать про UI логику, а конфиги у нас карточку описывают

2024-01-12 08:33 UTC, skibinalexander submitted a review, later dismissed

2024-01-15 15:21 UTC, tureck1y approved these changes

2024-01-15 15:30 UTC, skibinalexander approved these changes

2024-01-16 06:04 UTC, merged