IOS-5567 correct currency switcher
tangem/tangem-app-ios-old pull request #2668
Opened 2024-01-09 14:15 UTC by megakoko

2024-01-10 06:54 UTC, Andoran90 requested changes

2024-01-10 06:54 UTC, Andoran90 commented on Tangem/Common/UI/IconView/IconView.swift
> +struct IconView<Placeholder: View>: View {
эти изменения надо в отдельный МР выносить и перепроверять на главной что все нормально отображается и переключается между состояниями, а тут ещё для разных осей разное поведение, так что надо это тоже проверить. У нас есть всякие косяки с иконками сетей, надо либо их решить, либо их хотя бы сохранить)

Ты проверил как на главной переключение иконок происходит? Почему видос и скриншоты не прикладываешь?

2024-01-10 06:54 UTC, Andoran90 commented on Tangem/Modules/Send/Amount/SendCurrencyPicker.swift
> +                fiatIconURL: URL(string: "XXX://vectorflags.s3-us-west-2.amazonaws.com/flags/us-square-01.png")!,
```suggestion
                cryptoIconURL: URL(string: "https://s3.eu-central-1.amazonaws.com/tangem.api/coins/large/tether.png")!,
                cryptoCurrencyCode: "USDT",
                fiatIconURL: URL(string: "https://vectorflags.s3-us-west-2.amazonaws.com/flags/us-square-01.png")!,
```

2024-01-10 06:54 UTC, Andoran90 commented on Tangem/Modules/Send/SendViewModel.swift
> +}
в другом МРе было уже это

2024-01-10 06:54 UTC, megakoko commented on Tangem/Modules/Send/SendViewModel.swift
> +}
Было, тут тоже надо

2024-01-10 06:55 UTC, megakoko commented on Tangem/Modules/Send/Amount/SendCurrencyPicker.swift
> +                fiatIconURL: URL(string: "XXX://vectorflags.s3-us-west-2.amazonaws.com/flags/us-square-01.png")!,
Это специально для невалидных URL-ов

2024-01-10 06:56 UTC, megakoko commented on Tangem/Common/UI/IconView/IconView.swift
> +struct IconView<Placeholder: View>: View {
Вынесу отдельно

2024-01-10 06:59 UTC, Andoran90 commented on Tangem/Modules/Send/Amount/SendCurrencyPicker.swift
> +                fiatIconURL: URL(string: "XXX://vectorflags.s3-us-west-2.amazonaws.com/flags/us-square-01.png")!,
слушай, а почему `PickerExample` лежит в `SendCurrencyPicker`? он же будет доступен по всему приложению. Думаю его надо вытащить из реального пикера и сделать приватным для файла

2024-01-10 07:01 UTC, Andoran90 commented on Tangem/Modules/Send/SendViewModel.swift
> +}
в смысле) я там коммент на счет выноса написал, надо сделать это свойство доступным для всех, а не точечно добавлять на каждом экране, оно нормально накладывается на логику `WalletModel`, вдобавок в других местах тоже пригодится

2024-01-10 07:02 UTC, Andoran90 commented on Tangem/Common/UI/IconView/IconView.swift
> +struct IconView<Placeholder: View>: View {
а ты потыкал на главной нормально ли все меняется, были же проблемы с переключением плейсхолдера

2024-01-10 07:07 UTC, megakoko commented on Tangem/Modules/Send/SendViewModel.swift
> +}
Да это тот же файл. Эти изменения накладываются друг на друга

2024-01-10 07:09 UTC, megakoko commented on Tangem/Modules/Send/Amount/SendCurrencyPicker.swift
> +                fiatIconURL: URL(string: "XXX://vectorflags.s3-us-west-2.amazonaws.com/flags/us-square-01.png")!,
Это насколько помню не работает с #preview, должно быть публичным

2024-01-10 07:09 UTC, megakoko commented on Tangem/Common/UI/IconView/IconView.swift
> +struct IconView<Placeholder: View>: View {
Да, нормально загружается

2024-01-10 17:52 UTC, tureck1y commented on Tangem/Modules/Send/Amount/SendAmountViewModel.swift
> +    @Published var useFiatCalculation = false
Кажется это свойство SendModel

2024-01-10 17:52 UTC, tureck1y commented on Tangem/Modules/Send/SendViewModel.swift
> +}
это уже есть в WalletModel, через tokenItem. Если надо, можно отдельным проперти добавить туда же

2024-01-11 04:36 UTC, megakoko commented on Tangem/Modules/Send/Amount/SendAmountViewModel.swift
> +    @Published var useFiatCalculation = false
Нет, мы наоборот решили что SendModel только о крипте знает

2024-01-11 04:50 UTC, megakoko commented on Tangem/Modules/Send/Amount/SendCurrencyPicker.swift
> +                fiatIconURL: URL(string: "XXX://vectorflags.s3-us-west-2.amazonaws.com/flags/us-square-01.png")!,
Сделал приватным

2024-01-11 04:56 UTC, megakoko commented on Tangem/Modules/Send/SendViewModel.swift
> +}
Спасибо, сделал через tokenitem

2024-01-11 12:37 UTC, megakoko commented
@Andoran90 @tureck1y обновил, можно посмотреть

2024-01-11 12:43 UTC, tureck1y commented on Tangem/Modules/Send/Amount/SendAmountViewModel.swift
> +    @Published var useFiatCalculation = false
SendModel  это форма ввода, она в целом может о таком знать. А как у тебя Стейт будет запоминаться, что переключатель переключили? Сейчас вьюмодели создаются сразу, а если будем их создавать на лету, то это сломается...

2024-01-11 12:45 UTC, megakoko commented on Tangem/Modules/Send/Amount/SendAmountViewModel.swift
> +    @Published var useFiatCalculation = false
Когда сломается тогда и починим. Сейчас работает. Мы это обсуждали, решили что SendModel ничего о фиате не должна знать

2024-01-12 04:17 UTC, Andoran90 commented
ну таки шо) как пикер-то выглядит и работает? давай видосик :)

2024-01-12 08:13 UTC, megakoko commented
> ну таки шо) как пикер-то выглядит и работает? давай видосик :)

Видосик был в МРе с реализацией пикера, тут только его впендюривание

2024-01-12 11:20 UTC, Andoran90 approved these changes

2024-01-12 12:02 UTC, tureck1y approved these changes

2024-01-12 12:04 UTC, merged