IOS-5672 send recipient add flash and gallery buttons
tangem/tangem-app-ios-old pull request #2704
Opened 2024-01-16 15:36 UTC by megakoko

2024-01-17 06:02 UTC, fedorov-d commented on Tangem/Modules/Send/QRScanView/QRScannerView.swift
> +        QRScanView(viewModel: .init(code: $code, text: "Please align your QR code with the square to scan it. Ensure you scan ERC-20 network address.", router: QRScanViewCoordinator(dismissAction: {
оффтопик: а почему тут текст не локализован?

2024-01-17 06:02 UTC, fedorov-d approved these changes, later dismissed

2024-01-17 06:53 UTC, megakoko commented on Tangem/Modules/Send/QRScanView/QRScannerView.swift
> +        QRScanView(viewModel: .init(code: $code, text: "Please align your QR code with the square to scan it. Ensure you scan ERC-20 network address.", router: QRScanViewCoordinator(dismissAction: {
А это превью, чисто для разработки

2024-01-17 06:53 UTC, megakoko commented
@Andoran90 FYI, забыл тебя выбрать ревьювером

2024-01-17 14:27 UTC, tureck1y commented on Tangem/Modules/Send/QRScanView/PhotoSelectorViewModel.swift
> +    let didSelectPhoto: (UIImage?) -> Void
паблишер не хочешь?

2024-01-17 14:27 UTC, tureck1y commented on Tangem/Modules/Send/QRScanView/QRScanViewCoordinator.swift
> +    private func scanQRCode(from image: UIImage) -> String? {
Раз такой код появляется в координаторе, который нужен только для навигации и сборки экранов, то кажется что координатор тут и не нужен, тем более чуть ниже есть такой код `self?.rootViewModel?.code.wrappedValue = code`

Давайте подумаем насчет того, что все положить во вью модель,  либо оставляем так, но тогда этот метод надо убирать отсюда

А лучше обсудить, потому что это новый кейс, надо решить как с ним жить

2024-01-18 06:32 UTC, Andoran90 requested changes

2024-01-18 06:32 UTC, Andoran90 commented on Tangem/Modules/Send/QRScanView/QRScannerView.swift
> +class QRScanViewModel: ObservableObject, Identifiable {
надо вынести в отдельный файл `QRScannerViewModel`

2024-01-18 06:32 UTC, Andoran90 commented on Tangem/Modules/Send/QRScanView/QRScannerView.swift
> +class QRScanViewModel: ObservableObject, Identifiable {
Чет тут вообще какой-то кабздец, куча разных сущностей навалена в одном файла. Разнеси их все по разным файлам, пожалуйста.

2024-01-18 07:33 UTC, megakoko commented on Tangem/Modules/Send/QRScanView/QRScannerView.swift
> +class QRScanViewModel: ObservableObject, Identifiable {
Это старый код

2024-01-18 16:11 UTC, megakoko commented on Tangem/Modules/Send/QRScanView/PhotoSelectorViewModel.swift
> +    let didSelectPhoto: (UIImage?) -> Void
Замыканием удобнее думаю

2024-01-18 16:12 UTC, megakoko commented on Tangem/Modules/Send/QRScanView/QRScanViewCoordinator.swift
> +    private func scanQRCode(from image: UIImage) -> String? {
Да не, это просто мой brain-fart опять. Тут у сканера QR кода появляется навигация, координатор нужен.

Перенес в модель все это барахло

2024-01-18 16:13 UTC, megakoko commented
@tureck1y @fedorov-d посмотрите еще пожалуйста

2024-01-19 06:04 UTC, Andoran90 commented on Tangem/Modules/Send/QRScanView/QRScannerView.swift
> +class QRScanViewModel: ObservableObject, Identifiable {
старый код был структурой, а у тебя тут появилась большая вью модель, вынеси её как минимум. То что где-то насрано, не означает что надо докладывать ещё. В чем проблема навести порядок?

2024-01-19 06:58 UTC, fedorov-d commented on Tangem/Modules/Send/QRScanView/QRScannerView.swift
> +class QRScanViewModel: ObservableObject, Identifiable {
мб стоит final добавить

2024-01-19 07:28 UTC, megakoko commented on Tangem/Modules/Send/QRScanView/QRScannerView.swift
> +class QRScanViewModel: ObservableObject, Identifiable {
У нас в гайдах такого нет, я сам считаю это экономией на спичках

2024-01-19 07:40 UTC, fedorov-d approved these changes

2024-01-19 09:32 UTC, Andoran90 approved these changes

2024-01-22 08:24 UTC, megakoko commented
@tureck1y давай заливать

2024-01-22 13:45 UTC, tureck1y approved these changes

2024-01-22 14:02 UTC, merged