IOS-5786 send summary update fee if 60 seconds passed
tangem/tangem-app-ios-old pull request #2751
Opened 2024-01-29 09:48 UTC by megakoko

2024-01-29 10:56 UTC, tureck1y requested changes

2024-01-29 10:56 UTC, tureck1y commented on Tangem/Modules/Send/SendModel.swift
> +                }
а какой смысл в этой части?

2024-01-29 10:56 UTC, tureck1y commented on Tangem/Modules/Send/SendModel.swift
> +                completion(.success(oldFee: oldFeeAmount?.amount, newFee: marketFeeValue.amount))
1) Предлагаю оставить что-то одно sink или receiveValue
2) Почему комбинируются  каллбэк и реактивщина? При рефаторингах такое делаем ради совместимости, но тут же новый модуль. Почему не сделать все реактивно?

2024-01-29 10:56 UTC, tureck1y commented on Tangem/Modules/Send/SendView.swift
> +                Color.clear.frame(width: 0.5, height: 0.5)
Для таких штук используем NavHolder()

2024-01-29 10:56 UTC, tureck1y commented on Tangem/Modules/Send/SendViewModel.swift
> +extension SendViewModel: NotificationTapDelegate {
Видно, что SendNotificationManager создается с send model
`SendNotificationManager(input: sendModel)`

Но при этом, они связываются через делегат(вьюмодель), где лежит 
`sendModel.updateFees { _ in }`

2024-01-29 10:56 UTC, tureck1y commented on Tangem/Modules/Send/SendView.swift
> +                Color.clear.frame(width: 0.5, height: 0.5)
Тут какая-то проблема? На SendSummaryView такой проблемы нет? Там Алерт лежит по-старому

2024-01-29 10:56 UTC, tureck1y commented on Tangem/Modules/Send/Summary/SendSummaryViewModel.swift
> +        input.updateFees { [weak self] result in
мне кажется тут вполне себе ляжет постоянная подписка + триггер, который будет отсыпаться в sendModel

2024-01-30 07:20 UTC, megakoko commented on Tangem/Modules/Send/SendModel.swift
> +                }
сюда по-идее вообще не должны попадать т.к. до тех пор пока неит адреса и суммы мы не будем запрашивапть комиссию и до соотвестсвующего экрана не дойдем

2024-01-30 07:20 UTC, megakoko commented on Tangem/Modules/Send/SendModel.swift
> +                completion(.success(oldFee: oldFeeAmount?.amount, newFee: marketFeeValue.amount))
как оставить одно если нам нужны и ошибки паблишера, и возвращаемые данные. надо и туда и туда заходить

все на комбайне неудобно получается, т.к. запрос на коммиссию может вызываться
1. автоматически когда адрес и сумма менчются
2. когда нажимаешь send после 60 секунд
3. когда нажимаешь refresh fee

подписку хочктся одну, возврващать cancellable не хочется. держать отдельный anypublisher куда будут лететь результаты всех обновлений и потом фильтровать на каждом экране чтобы не словить ненужное обновление тоже не хочется

2024-01-30 07:20 UTC, megakoko commented on Tangem/Modules/Send/SendViewModel.swift
> +extension SendViewModel: NotificationTapDelegate {
все notif manager-ы так сделаны, не хотел отступать

2024-01-30 07:20 UTC, megakoko commented on Tangem/Modules/Send/Summary/SendSummaryViewModel.swift
> +        input.updateFees { [weak self] result in
написал выше

2024-01-30 07:20 UTC, megakoko commented on Tangem/Modules/Send/SendView.swift
> +                Color.clear.frame(width: 0.5, height: 0.5)
Спасибо, исправил, копипастил из воллетконнекта. Была проблема с двумя алертами на одной вьюхе из-за камеры, в саммаре такой нет

2024-01-30 07:23 UTC, megakoko commented on Tangem/Modules/Send/SendViewModel.swift
> +extension SendViewModel: NotificationTapDelegate {
Или ты про что?

2024-01-30 07:33 UTC, Andoran90 commented on Tangem/Modules/Send/FeeUpdateResult.swift
> +enum FeeUpdateResult: Error {
странно, что результат является ошибкой причем с кейсом `success`, это уже не ошибка

2024-01-30 07:33 UTC, Andoran90 commented on Tangem/Modules/Send/FeeUpdateResult.swift
> +enum FeeUpdateResult: Error {
Думаю это должно быть:
``` swift
typealias FeeUpdateResult = Result<(oldFee: Amount?, newFee: Amount), Error>
```

если нужны отдельно кейсы ошибок, тогда нужен енум с ошибками

2024-01-30 07:33 UTC, Andoran90 commented on Tangem/Modules/Send/SendModel.swift
> +    private var lastTimeFeesWereFetched: Date?
записывается, но нигде не считывается

2024-01-30 07:33 UTC, Andoran90 commented on Tangem/Modules/Send/FeeUpdateResult.swift
> +enum FeeUpdateResult: Error {
посмотрел где это используется. Этот `enum` вообще не особо и нужен, если вместо кложуры возвращать паблишер, можно сделать:
`typealias FeeUpdateResult = (oldFee: Amount?, newFee: Amount)`
и обновить функцию `func updateFees(amount: Amount?, destination: String?) -> AnyPublisher<FeeUpdateResult, Error>`

2024-01-30 07:33 UTC, Andoran90 commented on Tangem/Modules/Send/SendModel.swift
> +                }
однозначно можно выкинуть вне зависимости используем кложуры или паблишеры. Через `guard` развернуть все опционалы и если чего-то не хватает сразу возвращать результать, а не гнать через всю цепочку

2024-01-30 07:33 UTC, Andoran90 commented on Tangem/Modules/Send/SendModel.swift
> +                completion(.success(oldFee: oldFeeAmount?.amount, newFee: marketFeeValue.amount))
можно сделать через `tryMap` + ` handleEvents(receiveOutput, receiveCompletion)` и возвращать паблишер, чтобы не плодить зоопарк, ну или вообще через асинки. В целом такой тип запросов (один раз запросил и все) красивее делать через асинки, а не паблишеры

2024-01-30 07:33 UTC, Andoran90 commented on Tangem/Modules/Send/SendNotifications/SendNotificationEvent.swift
> +        nil
аналитику ещё не предоставили? или её не будет тут?

2024-01-30 07:33 UTC, Andoran90 commented on Tangem/Modules/Send/SendViewModel.swift
> +extension SendViewModel: NotificationTapDelegate {
а что, норм же. Не хватало ещё чтобы `SendModel` обрабатывала нажатия на кнопки оповещений...

2024-01-30 07:51 UTC, megakoko commented on Tangem/Modules/Send/SendModel.swift
> +                completion(.success(oldFee: oldFeeAmount?.amount, newFee: marketFeeValue.amount))
А асинки и паблишеры вместе это не зоопарк?

2024-01-30 07:53 UTC, megakoko commented on Tangem/Modules/Send/SendModel.swift
> +    private var lastTimeFeesWereFetched: Date?
Спасибо. Пробовал разные варианты, не все подчистил

2024-01-30 07:53 UTC, megakoko commented on Tangem/Modules/Send/SendNotifications/SendNotificationEvent.swift
> +        nil
Аналитика? Какая аналитика? 

\*смеется и плачет\*

2024-01-30 08:08 UTC, megakoko commented on Tangem/Modules/Send/FeeUpdateResult.swift
> +enum FeeUpdateResult: Error {
Да, думаю можно так. Тоже пробовал разные варианты с отдельным кейсом feeIncreased, енам остался оттуда. Сделал через result

2024-01-30 08:11 UTC, megakoko commented on Tangem/Modules/Send/SendModel.swift
> +                }
Не хочется выносить, пусть все гоняется через sink, там логика на случай если amount и destination будут nil, комиссии сбросятся. В этих случаях все-таки попадает сюда

2024-01-30 08:14 UTC, Andoran90 commented on Tangem/Modules/Send/SendModel.swift
> +                completion(.success(oldFee: oldFeeAmount?.amount, newFee: marketFeeValue.amount))
более модный молодежный зоопарк без ада с отступами, скобками и прочим. Вдобавок стараемся переезжать в новых модулях на новые технологии, а тут старые варианты получаются. Вообще было бы хорошо избавиться от паблишеров и кложур в тех местах где идут запросы ваншоты и оставить паблишеры только в тех местах где выдается более одного результата (это можно тоже попробовать заменить на `AsyncSequence` и подобные сущности, но с этим сложнее, поэтому без этого пока пойдет)

Понятное дело, что от кложур не избавиться полность, да и не зачем, но в тех местах где можно сделать через паблишер или асинк, лучше делать через них

2024-01-30 08:15 UTC, Andoran90 commented on Tangem/Modules/Send/SendNotifications/SendNotificationEvent.swift
> +        nil
😭😭😭

2024-01-30 08:16 UTC, megakoko commented on Tangem/Modules/Send/SendModel.swift
> +                completion(.success(oldFee: oldFeeAmount?.amount, newFee: marketFeeValue.amount))
Ладно, попробую асинк. Только доеду на моноколесе до смузи-шопа и докурю вейп

2024-01-30 08:17 UTC, megakoko commented on Tangem/Modules/Send/SendModel.swift
> +                completion(.success(oldFee: oldFeeAmount?.amount, newFee: marketFeeValue.amount))
Можно я хоть этот асинк на obj-c напишу?

2024-01-30 08:25 UTC, Andoran90 commented on Tangem/Modules/Send/SendModel.swift
> +                }
ты об этой одной строчке (`_feeValues.send([:])`), которая в `else` в коде ниже?
``` swift
guard 
    let amount,
    let destination
else {
    _feeValues.send([:])
    completion(.failure(WalletError.failedToGetFee))
    return
}
```

2024-01-30 08:53 UTC, megakoko commented on Tangem/Modules/Send/SendModel.swift
> +                completion(.success(oldFee: oldFeeAmount?.amount, newFee: marketFeeValue.amount))
Обновил

2024-01-30 08:54 UTC, megakoko commented on Tangem/Modules/Send/SendModel.swift
> +                }
Сегодня одна, завтра — две. Чтобы копипасту не держать надо будет выносить в отдельный метод / замыкание. И это ради того чтобы избежать щепотки комбайна?

2024-01-30 08:59 UTC, Andoran90 commented on Tangem/Modules/Send/SendModel.swift
> +                }
хм, гораздо лучше сделать сложно-читаемый и не особо нужный код?

2024-01-30 09:00 UTC, Andoran90 commented on Tangem/Modules/Send/SendModel.swift
> +                }
окей, пусть Саня тогда решает, раз наши мнения разделились на этот счет

2024-01-30 18:11 UTC, tureck1y commented on Tangem/Modules/Send/SendModel.swift
> +                }
я не вижу смысла оборачивать переменные в Just, захватывать self и делать unwrap. Сразу переходи к делу, к паблишерам)

2024-01-30 18:12 UTC, tureck1y commented on Tangem/Modules/Send/SendModel.swift
> +                completion(.success(oldFee: oldFeeAmount?.amount, newFee: marketFeeValue.amount))
сайд эффекты надо в handleEvents переносить, ага

2024-01-30 18:13 UTC, tureck1y commented on Tangem/Modules/Send/SendModel.swift
> +                completion(.success(oldFee: oldFeeAmount?.amount, newFee: marketFeeValue.amount))
так зачем зоопарк? У тебя есть подписка, которая возвращает обновленные фи + есть триггер, который запускает обновление

2024-01-30 18:15 UTC, tureck1y commented on Tangem/Modules/Send/SendViewModel.swift
> +extension SendViewModel: NotificationTapDelegate {
Кажется мы друг друга не поняли... 

Почему менеджер сам не может дернуть sendModel.updateFees, если он и так про нее знает?

2024-01-30 18:18 UTC, tureck1y commented on Tangem/Modules/Send/SendModel.swift
> +                completion(.success(oldFee: oldFeeAmount?.amount, newFee: marketFeeValue.amount))
Я посмотрел код, мне кажется пошли не туда, не надо смешивать подходы. Мой коммент был про другое, можем завтра вместе посмотреть

2024-01-31 05:46 UTC, megakoko commented on Tangem/Modules/Send/SendViewModel.swift
> +extension SendViewModel: NotificationTapDelegate {
У нас все менеджеры работают через делегат

2024-01-31 13:12 UTC, megakoko commented on Tangem/Modules/Send/SendModel.swift
> +                }
Посмотрите еще раз на этот код. Если amount/destination nil, то мы пустой массив комиссий дальше передаем и обрабатываем, это не просто ранний выход

2024-01-31 13:13 UTC, megakoko commented on Tangem/Modules/Send/SendModel.swift
> +                completion(.success(oldFee: oldFeeAmount?.amount, newFee: marketFeeValue.amount))
Сделал через подписку

2024-01-31 13:13 UTC, megakoko commented
@tureck1y @Andoran90 обновил

2024-02-01 13:06 UTC, Andoran90 commented on Tangem/Modules/Send/SendModel.swift
> +    }
я говорил про вот такой вариант, если что. Вроде ничего не пропустил и должно работать так как и планировалось. Единственный нюанс - тот кто вызвал обновление фи, он обязательно должен ждать ответа, иначе не обновится. Не проверял работает или нет, но должно быть все норм

```suggestion
    private var feeUpdatePublisherAlt: AnyPublisher<FeeUpdateResult, Error>?
    private func updateFees(amount: Amount?, destination: String?) -> AnyPublisher<FeeUpdateResult, Error> {
        if let feeUpdatePublisherAlt {
            return feeUpdatePublisherAlt
        }

        guard let amount, let destination else {
            _feeValues.send([:])
            return .anyFail(error: WalletError.failedToGetFee)
        }

        let oldFee = fee.value

        let publisher = walletModel
            .getFee(amount: amount, destination: destination)
            .withWeakCaptureOf(self)
            .map { (self, fees) in
                return self.feeValues(fees)
            }
            .handleEvents(receiveOutput: { [weak self] feeValues in
                guard let self else { return }

                self._feeValues.send(feeValues)

                if let customFee = feeValues[.custom]?.value,
                   let ethereumFeeParameters = customFee.parameters as? EthereumFeeParameters,
                   !didSetCustomFee {
                    _customFee.send(customFee)
                    _customFeeGasPrice.send(ethereumFeeParameters.gasPrice)
                    _customFeeGasLimit.send(ethereumFeeParameters.gasLimit)
                }
            }, receiveCompletion: { [weak self] completion in
                guard let self else { return }

                feeUpdatePublisherAlt = nil

                if case .failure = completion {
                    let pairs: [(FeeOption, LoadingValue<Fee>)] = feeOptions.map { ($0, .failedToLoad(error: WalletError.failedToGetFee)) }
                    let feeValues = Dictionary(pairs, uniquingKeysWith: { v1, _ in v1 })
                    _feeValues.send(feeValues)
                }
            })
            .tryMap { [weak self] feeValues in
                guard
                    let self,
                    let selectedFee = feeValues[selectedFeeOption],
                    let selectedFeeValue = selectedFee.value
                else {
                    throw WalletError.failedToGetFee
                }

                return FeeUpdateResult(oldFee: oldFee?.amount, newFee: selectedFeeValue.amount)
            }
            .eraseToAnyPublisher()

        return publisher
    }
```

2024-02-01 13:08 UTC, Andoran90 commented on Tangem/Modules/Send/SendModel.swift
> +                }
я до сих пор не понимаю зачем нужны эти Just(amount), Just(destination).
Судя по твоему коду все закончится 280 строкой, вернее 259 паблишер закончит выполнение

2024-02-01 14:36 UTC, tureck1y commented on Tangem/Modules/Send/SendModel.swift
> +                }
Я уже устал про них говорить если честно

2024-02-01 14:40 UTC, tureck1y requested changes

2024-02-01 14:40 UTC, tureck1y commented on Tangem/Modules/Send/SendModel.swift
> +                _feeValues.send(feeValues)
Обсуждали делать правильно через сайд-эффект

2024-02-01 14:40 UTC, tureck1y commented on Tangem/Modules/Send/SendModel.swift
> +    }
> я говорил про вот такой вариант, если что. Вроде ничего не пропустил и должно работать так как и планировалось. Единственный нюанс - тот кто вызвал обновление фи, он обязательно должен ждать ответа, иначе не обновится. Не проверял работает или нет, но должно быть все норм
> 
> 
> 
> ```suggestion
> 
>     private var feeUpdatePublisherAlt: AnyPublisher<FeeUpdateResult, Error>?
> 
>     private func updateFees(amount: Amount?, destination: String?) -> AnyPublisher<FeeUpdateResult, Error> {
> 
>         if let feeUpdatePublisherAlt {
> 
>             return feeUpdatePublisherAlt
> 
>         }
> 
> 
> 
>         guard let amount, let destination else {
> 
>             _feeValues.send([:])
> 
>             return .anyFail(error: WalletError.failedToGetFee)
> 
>         }
> 
> 
> 
>         let oldFee = fee.value
> 
> 
> 
>         let publisher = walletModel
> 
>             .getFee(amount: amount, destination: destination)
> 
>             .withWeakCaptureOf(self)
> 
>             .map { (self, fees) in
> 
>                 return self.feeValues(fees)
> 
>             }
> 
>             .handleEvents(receiveOutput: { [weak self] feeValues in
> 
>                 guard let self else { return }
> 
> 
> 
>                 self._feeValues.send(feeValues)
> 
> 
> 
>                 if let customFee = feeValues[.custom]?.value,
> 
>                    let ethereumFeeParameters = customFee.parameters as? EthereumFeeParameters,
> 
>                    !didSetCustomFee {
> 
>                     _customFee.send(customFee)
> 
>                     _customFeeGasPrice.send(ethereumFeeParameters.gasPrice)
> 
>                     _customFeeGasLimit.send(ethereumFeeParameters.gasLimit)
> 
>                 }
> 
>             }, receiveCompletion: { [weak self] completion in
> 
>                 guard let self else { return }
> 
> 
> 
>                 feeUpdatePublisherAlt = nil
> 
> 
> 
>                 if case .failure = completion {
> 
>                     let pairs: [(FeeOption, LoadingValue<Fee>)] = feeOptions.map { ($0, .failedToLoad(error: WalletError.failedToGetFee)) }
> 
>                     let feeValues = Dictionary(pairs, uniquingKeysWith: { v1, _ in v1 })
> 
>                     _feeValues.send(feeValues)
> 
>                 }
> 
>             })
> 
>             .tryMap { [weak self] feeValues in
> 
>                 guard
> 
>                     let self,
> 
>                     let selectedFee = feeValues[selectedFeeOption],
> 
>                     let selectedFeeValue = selectedFee.value
> 
>                 else {
> 
>                     throw WalletError.failedToGetFee
> 
>                 }
> 
> 
> 
>                 return FeeUpdateResult(oldFee: oldFee?.amount, newFee: selectedFeeValue.amount)
> 
>             }
> 
>             .eraseToAnyPublisher()
> 
> 
> 
>         return publisher
> 
>     }
> 
> ```

Читается проще, только там надо по именованию кэпчур листа подправить

2024-02-07 09:34 UTC, tureck1y commented
Этот мр достаточно промариновался? чего-то ждем?

2024-02-07 09:47 UTC, Andoran90 commented
после нашего последнего ревью не было никаких изменений, так что правок ждем

2024-02-08 17:14 UTC, megakoko commented
@tureck1y посмотри тогда пожалуйста раз не получилось вместе

2024-02-09 06:34 UTC, Andoran90 commented on Tangem/Modules/Send/SendViewModel.swift
> +                }
если тут ничего не будет, тогда есть `.sink()`, но вообще странно, что тут всюду пусто. Может быть в оповещении должен появляться лоадер перед запросом `sendModel.updateFess()` надо какую-то булку обновлять, чтобы загрузчик появился на кнопке, а в `sink` обратно переключать булку?

2024-02-09 06:34 UTC, Andoran90 commented on Tangem/Modules/Send/SendModel.swift
> +            }
тоже можно заменить на `.sink()`

2024-02-09 06:34 UTC, Andoran90 commented on Tangem/Modules/Send/SendModel.swift
> +        if let feeUpdatePublisher {
`feeUpdatePublisher` нигде не назначается и внутри `SendModel` не захватывается

2024-02-09 06:44 UTC, megakoko commented on Tangem/Modules/Send/SendViewModel.swift
> +                }
Сделал sink()

2024-02-09 06:44 UTC, megakoko commented on Tangem/Modules/Send/SendModel.swift
> +            }
Сделал sink()

2024-02-09 06:44 UTC, megakoko commented on Tangem/Modules/Send/SendModel.swift
> +        if let feeUpdatePublisher {
Сделал сохранение

2024-02-09 11:50 UTC, Andoran90 approved these changes

2024-02-09 17:41 UTC, tureck1y approved these changes

2024-02-09 17:41 UTC, tureck1y commented on Tangem/Modules/Send/SendModel.swift
> +            .map { (self, fees) in
нейминг тут и ниже надо поправить, можно отдельно потом

2024-02-09 17:41 UTC, tureck1y commented on Tangem/Modules/Send/SendViewModel.swift
> +            .receive(on: RunLoop.main)
Надо кстати договориться что пишем, вынесу в ноушен

2024-02-09 17:41 UTC, merged