Ios 5738 make algorand history integration
tangem/tangem-app-ios-old pull request #2766
Opened 2024-01-31 11:49 UTC by skibinalexander

Relation блокирующий МР для https://github.com/tangem/blockchain-sdk-swift/pull/534

Поддержал изменения от BlockchainSdk чтобы заработала история транзакций для Algo
Обязательное ревью от @Balashov152

2024-01-31 11:50 UTC, skibinalexander commented on Podfile
> +  pod 'BlockchainSdk', :path => '../blockchain-sdk-swift'
Как только померджим SDK обновлю тег

2024-01-31 13:49 UTC, tureck1y requested changes

2024-01-31 13:49 UTC, tureck1y commented on Tangem/App/Services/TransactionHistoryRepository/MutipleAddressTransactionHistoryService.swift
> +        return Just(address)
Лишние обертки

2024-01-31 13:49 UTC, tureck1y commented on Tangem/App/Services/TransactionHistoryRepository/MutipleAddressTransactionHistoryService.swift
> +            .withUnownedCaptureOf(self)
Не unowned a weak

2024-02-01 08:14 UTC, skibinalexander commented on Tangem/App/Services/TransactionHistoryRepository/MutipleAddressTransactionHistoryService.swift
> +        return Just(address)
> Лишние обертки

Да немного погнал, там была ошибка с Swift.Error компилятор в упор не хотел инферить паблишеры. В итоге ошибку поменял, а тут забыл. Убрал

2024-02-01 08:52 UTC, skibinalexander commented
Тесты вижу что завалились , проверю финально как тег подниму, с изменениями сборку собирал, было ок

2024-02-01 14:23 UTC, tureck1y submitted a review, later dismissed

2024-02-01 16:55 UTC, Balashov152 reviewed
Чет такое ощущение что можно оставить один `CommonTransactionHistoryService`  и сделать там несколько адресов. Просто мысли в слух

P.S. Ну или лучше наверно оставить как есть, дебажить лучше будет на single address wallet

2024-02-01 16:55 UTC, Balashov152 commented on Tangem/App/Services/TransactionHistoryRepository/MutipleAddressTransactionHistoryService.swift
> +                }.joined(separator: ","),
```suggestion
                }.joined(separator: ", "),
```

2024-02-01 16:55 UTC, Balashov152 commented on Tangem/App/Factories/WalletModels/CommonWalletModelsFactory.swift
> +        _ = addresses.reduce(into: multiAddressProviders) { partialResult, address in
что ж у все с `reduce` проблемы ))

```suggestion
        let multiAddressProviders: [String: TransactionHistoryProvider?] = addresses.reduce(into: [:]) { partialResult, address in
```

2024-02-01 19:18 UTC, skibinalexander commented on Tangem/App/Factories/WalletModels/CommonWalletModelsFactory.swift
> +        _ = addresses.reduce(into: multiAddressProviders) { partialResult, address in
Проверю , может разные варианты пробовал осталось , спс

2024-02-02 14:53 UTC, Balashov152 approved these changes

2024-02-02 15:48 UTC, tureck1y approved these changes

2024-02-02 16:41 UTC, merged