IOS-5728 send animations
tangem/tangem-app-ios-old pull request #2799
Opened 2024-02-08 05:57 UTC by megakoko

2024-02-14 05:17 UTC, megakoko commented
https://github.com/tangem/tangem-app-ios/assets/12209839/0762f847-785b-4d7a-9489-0ee5ec8ca43d

2024-02-14 17:59 UTC, tureck1y approved these changes

2024-02-15 09:49 UTC, Balashov152 requested changes

2024-02-15 09:49 UTC, Balashov152 commented on Tangem/Common/Extensions/View+.swift
> +        }
NP: можно так
```suggestion
        } else if AppEnvironment.shared.isDebug {
            fatalError("You must set either both ID and namespace or neither")
         } else {
            self
        }
```

2024-02-15 09:49 UTC, Balashov152 commented on Tangem/Common/UI/GroupedScrollView/GroupedSection.swift
> +    private var backgroundNamespaceId: String?
плохо получается, что в секции появляется такое. Давай лучше Background сделаем generic или как то. И передавать его из вне будем

2024-02-15 09:49 UTC, Balashov152 commented on Tangem/Common/UI/GroupedScrollView/GroupedSection.swift
> +    private var backgroundNamespaceId: String?
Вот так давай лушче)
 cd432e2b15b6cc969d8d7b7b6f6618ffd75a864a

2024-02-15 10:51 UTC, megakoko commented on Tangem/Common/Extensions/View+.swift
> +        }
Это только для разработчиков сообщение

2024-02-15 11:07 UTC, megakoko commented on Tangem/Common/UI/GroupedScrollView/GroupedSection.swift
> +    private var backgroundNamespaceId: String?
Давай оставим как есть, это стандартный подход для таких анимаций. Везде через setupable передаем идентификаторы и неймспейс

2024-02-15 11:52 UTC, Balashov152 commented on Tangem/Common/UI/GroupedScrollView/GroupedSection.swift
> +    private var backgroundNamespaceId: String?
Получается что GroupedSection, которая есть в настройках, экспрессе и еще где нибудь будет имеет две проперти, которые необходимы только для одного модуля send
Такие вещи надо на стороне потребителя решать, а не внутри самой `GroupedSection`

2024-02-15 11:52 UTC, Balashov152 commented on Tangem/Common/Extensions/View+.swift
> +        }
ну так флаг тот же)

2024-02-15 11:59 UTC, megakoko commented on Tangem/Common/UI/GroupedScrollView/GroupedSection.swift
> +    private var backgroundNamespaceId: String?
Сегодня только для сенда, завтра для экспресса тоже попросят сделать анимацию

Я не хочу два разных API иметь — одно через задание кастомного anyview background, другое через сеттеры. Пробрасывать эти штуки надо не только для groupedsection, но и для обычных вьюх-контейнеров, где надо пробираться к подвьюхам типа Text

2024-02-15 14:28 UTC, ba1ashov commented on Tangem/Common/UI/GroupedScrollView/GroupedSection.swift
> +    private var backgroundNamespaceId: String?
Так тоже самое получится, просто этот код будет снаружи

2024-02-15 14:34 UTC, Balashov152 approved these changes

2024-02-15 14:51 UTC, merged