IOS-4591 open main with fade animation
tangem/tangem-app-ios-old pull request #2829
Opened 2024-02-16 08:28 UTC by fedorov-d

2024-02-16 08:49 UTC, tureck1y commented
Прикрепи видео пожалуйста

2024-02-16 16:27 UTC, tureck1y commented on Tangem/Common/Extensions/View+.swift
> +    func removeAnimation() -> some View {
а есть сделать явно через withanimation/withTransaction в координаторе?

2024-02-18 11:34 UTC, fedorov-d commented on Tangem/Common/Extensions/View+.swift
> +    func removeAnimation() -> some View {
в этом случае еще navigationBar анимируется, ну и SwiftUI импортировать в координатор не очень как по мне.
https://github.com/tangem/tangem-app-ios/assets/80246944/4e6292b6-f98a-4287-a81a-8f75b5b03df1

2024-02-19 14:22 UTC, tureck1y commented on Tangem/Modules/Auth/AuthCoordinatorView.swift
> +        .navigationBarHidden(coordinator.mainCoordinator == nil)
навбар на этой вью всегда должен быть скрыт, для чего это изменение?

2024-02-19 17:08 UTC, fedorov-d commented on Tangem/Modules/Auth/AuthCoordinatorView.swift
> +        .navigationBarHidden(coordinator.mainCoordinator == nil)
после правок AuthCoordinatorView умеет отображать как root не только AuthView, но MainCoordinatorView (он переехал из links), в случае AuthView - навбар не нужен, в случае MainCoordinatorView - нужен. Возможно эту логику имеет смысл перенести куда-то в другое место.

2024-03-07 13:22 UTC, tureck1y commented
Надо обсудить будет, мне кажется ViewState это лишнее

2024-03-28 15:38 UTC, fedorov-d commented on Tangem/Modules/Main/MainViewModel.swift
> -                guard let userWalletId = self?.pages[newIndex].id else {
тут крашило если ресетнуть карту сразу после ее создания

2024-03-28 15:42 UTC, fedorov-d commented
По ViewState: решил оставить, т.к. упрощает управление состоянием view и переносит часть логики с view в coordinator, где мне кажется более удачное место для этого. Плюс при попытке отката как раз столкнулся с проблемами корректной смены состояний, когда приходится управлять 2-4 переменными вместо одной логика становится сложнее и неочевиднее.

2024-04-01 12:16 UTC, tureck1y requested changes

2024-04-01 12:16 UTC, tureck1y commented on Tangem/Modules/App/AppCoordinator.swift
> +    enum ViewState: Equatable {
Давай это вниз файла унесем в extension во всех координаторах

2024-04-01 12:16 UTC, tureck1y commented on Tangem/Modules/App/AppCoordinator.swift
> +        authCoordinator.start(with: .init(unlockOnStart: unlockOnStart))
Тут и в остальных местах
Было:  старт координатора, потом ассайн вью
Стало: наоборот

Давай оставим старое поведение

2024-04-01 12:16 UTC, tureck1y commented on Tangem/Modules/App/AppCoordinator.swift
> +        }
Не понимаю эту часть. Тут же сета, значит никакого вью-стейта быть не должно по идее

2024-04-01 12:16 UTC, tureck1y commented on Tangem/Modules/Welcome/WelcomeCoordinator.swift
> +        switch viewState {
тут на старте же тоже не может быть кейсов. Старт модуля  в любом случае заново должен все делать

2024-04-01 12:16 UTC, tureck1y commented on Tangem/Modules/Welcome/WelcomeCoordinatorView.swift
> +        .navigationBarHidden(coordinator.viewState?.isMain == false)
Согласно нашим гайдам, используем level1 проверти, например coordinator.navigationBarHidden

2024-04-01 16:40 UTC, fedorov-d commented on Tangem/Modules/App/AppCoordinator.swift
> +    enum ViewState: Equatable {
перенес

2024-04-01 16:42 UTC, fedorov-d commented on Tangem/Modules/App/AppCoordinator.swift
> +        authCoordinator.start(with: .init(unlockOnStart: unlockOnStart))
вернул

2024-04-01 16:42 UTC, fedorov-d commented on Tangem/Modules/App/AppCoordinator.swift
> +        }
убрал лишнюю логику, вроде не сломалось ничего

2024-04-01 16:43 UTC, fedorov-d commented on Tangem/Modules/Welcome/WelcomeCoordinator.swift
> +        switch viewState {
убрал

2024-04-01 16:43 UTC, fedorov-d commented on Tangem/Modules/Welcome/WelcomeCoordinatorView.swift
> +        .navigationBarHidden(coordinator.viewState?.isMain == false)
поправил

2024-04-04 07:28 UTC, tureck1y commented on Tangem/Modules/Welcome/WelcomeCoordinator.swift
> +        pushedOnboardingCoordinator = nil
Если эта строчка нужна, то добавь плиз кейс в комменте. Вообще на старте у класса начальный стейт и по идее ничего загулять не надо

2024-04-04 07:28 UTC, tureck1y commented on Tangem/Modules/Welcome/WelcomeCoordinator.swift
> +    }
думаю надо унести во ViewState

2024-04-04 15:09 UTC, fedorov-d commented on Tangem/Modules/Welcome/WelcomeCoordinator.swift
> +        pushedOnboardingCoordinator = nil
убрал

2024-04-04 15:09 UTC, fedorov-d commented on Tangem/Modules/Welcome/WelcomeCoordinator.swift
> +    }
перенес

2024-04-04 15:28 UTC, tureck1y submitted a review, later dismissed

2024-04-09 13:13 UTC, m3g0byt3 reviewed
С viewState действительно удобнее получается, можно и на других экранах юзать подход

---

Прогнал кейсы отсюда 
https://tangem.slack.com/archives/C03FUDV2FAQ/p1711967311134569 на 15.7 - проблем не обнаружил

2024-04-09 13:13 UTC, m3g0byt3 commented on Tangem/Modules/Onboarding/OnboardingCoordinator.swift
> +    }
Мне кажется отдельная проперть тут и в других местах не нужна, ее существование и нейминг только путает (bool это обычно флаги, а тут это какой-то `value` - с ходу непонятно) и к тому же возможен рассинхрон с `navigationBarHidden` (которой под капотом эта проперть и является) - если кто-то будет рефачить этот код и забудет поправить в двух местах условие `viewState?.isMain == false`

Во вьюхе можно просто
`.animation(.default, value: coordinator.navigationBarHidden)`

2024-04-09 13:13 UTC, m3g0byt3 commented on Tangem/Modules/Onboarding/OnboardingCoordinator.swift
> +    var navigationBarHidden: Bool {
nit: `isNavigationBarHidden` - так как это все-таки проперть, а не SwiftUI метод `.navigationBarHidden(bool)`

2024-04-09 13:13 UTC, m3g0byt3 commented on Tangem/Modules/Auth/AuthCoordinator.swift
> +    }
Тут аналогично как в Tangem/Modules/Onboarding/OnboardingCoordinator.swift

2024-04-09 13:13 UTC, m3g0byt3 commented on Tangem/Modules/Auth/AuthCoordinatorView.swift
> +        .navigationBarHidden(coordinator.navigationBarHidden)
Тут другой порядок модификаторов (сначала `animation`, затем `navigationBarHidden`) чем в Tangem/Modules/Onboarding/OnboardingCoordinatorView.swift - это намеренно сделанно или случайно?
В SwiftUI разный порядок модификаторов может приводить к разным результатам

Если намеренно - то мб оставить коммент об этом? А то tricky место

2024-04-09 13:13 UTC, m3g0byt3 commented on Tangem/Modules/Main/MainViewModel.swift
> +                guard let userWalletId = self?.pages[safe: newIndex]?.id else {
А это не приведет к тому, что в каких-то кейсах код ниже не выполнится и карта не станет выбранной? Ведь нет никаких гарантий, что selectedCardIndex прилетит еще хотя бы один раз после того, как `self.pages` станет не пустым

2024-04-09 13:13 UTC, m3g0byt3 commented on Tangem/Modules/Welcome/Stories/StoriesViewModel.swift
> +        currentProgress = 0
nit: не лишнее? Вроде и так начальное значение 0

2024-04-09 16:27 UTC, fedorov-d commented on Tangem/Modules/Auth/AuthCoordinatorView.swift
> +        .navigationBarHidden(coordinator.navigationBarHidden)
да, это намеренно, тут отсутствие анимации навигейшн бара смотрится субъективно лучше чем ее наличие, в отличие от других мест, добавлю комент.

2024-04-09 16:38 UTC, fedorov-d commented on Tangem/Modules/Main/MainViewModel.swift
> +                guard let userWalletId = self?.pages[safe: newIndex]?.id else {
по идее код ниже может не выполниться только если newIndex за границами массива, но в этом случае тут упадет. но конечно на 100% не уверен, затронул только с целью поправить падение.

2024-04-09 16:45 UTC, fedorov-d commented on Tangem/Modules/Welcome/Stories/StoriesViewModel.swift
> +        currentProgress = 0
да, похоже что артефакт, убрал

2024-04-09 16:45 UTC, fedorov-d commented on Tangem/Modules/Onboarding/OnboardingCoordinator.swift
> +    }
поинт валидный, но мне кажется это все таки две не зависимых переменных, просто значение совпало, и
`.animation(.default, value: coordinator.navigationBarHidden)`
кажется чуть менее понятным: почему анимация должна зависеть от состояния бара.

2024-04-09 16:48 UTC, fedorov-d commented on Tangem/Modules/Main/MainViewModel.swift
> +                guard let userWalletId = self?.pages[safe: newIndex]?.id else {
мало знаком с этим кодом, если подскажете какие-то сценарии - могу протестить отдельно.

2024-04-09 16:56 UTC, fedorov-d commented on Tangem/Modules/Main/MainViewModel.swift
> +                guard let userWalletId = self?.pages[safe: newIndex]?.id else {
тут отбой, проверил на свежей сборке - не крашит, видимо было связано с правками, которые уже откатил, удаляю

2024-04-09 16:57 UTC, fedorov-d commented on Tangem/Modules/Onboarding/OnboardingCoordinator.swift
> +    var navigationBarHidden: Bool {
поправил

2024-04-10 00:41 UTC, m3g0byt3 commented on Tangem/Modules/Onboarding/OnboardingCoordinator.swift
> +    }
Так этот модификатор (`.animation`) занимается тем, что анимирует любую stateful проперть, а не зависит от чего-либо

и такой код 
`.animation(.default, value: coordinator.isNavigationBarHidden)`
одназначно читается как "в этом месте анимируется скрытие/отображение навбара"

а вот код же 
`.animation(.default, value: coordinator.transitionAnimationValue)`
\- я не понимаю, что он делает и что за проперть, изменения которой он анимирует

Впрочем не крит, можно оставить

2024-04-10 00:41 UTC, m3g0byt3 approved these changes

2024-04-10 19:23 UTC, tureck1y approved these changes

2024-04-10 20:10 UTC, merged