IOS-5943 send implement currency icons
tangem/tangem-app-ios-old pull request #2862
Opened 2024-02-26 09:11 UTC by megakoko

2024-02-26 15:11 UTC, Balashov152 approved these changes

2024-02-26 15:12 UTC, Balashov152 requested changes
а, стоп
Есть же `TokenIconURLBuilder`. Он тоже самое делает

2024-02-26 15:13 UTC, Balashov152 commented
> а, стоп Есть же `TokenIconURLBuilder`. Он тоже самое делает

а, не совсем, там `coins`. Ну можно еще один метод сделать лучше, чем отдельный билдер

2024-02-27 05:05 UTC, megakoko commented
> > а, стоп Есть же `TokenIconURLBuilder`. Он тоже самое делает
> 
> а, не совсем, там `coins`. Ну можно еще один метод сделать лучше, чем отдельный билдер

Зачем, тот для токенов, этот для фиатных иконок. Норм так

2024-02-27 11:23 UTC, megakoko commented
IconURLBuilder.tokenIconURL
IconURLBuilder.fiatIconURL

2024-02-27 12:55 UTC, megakoko commented on Tangem/App/Services/IconURLBuilder/IconURLBuilder.swift
> +    }
Новое

2024-02-27 12:55 UTC, megakoko commented on Tangem/Modules/Send/SendViewModel.swift
> +
Новое

2024-02-27 12:56 UTC, megakoko commented
@tureck1y @Balashov152 обновил. Переименовал старый билдер, положил рядом новое. Вышло с рефакторингом, в качестве исключения давайте так зальем чтобы не тормозить. Новые вещи отметил комментами

2024-02-27 13:01 UTC, tureck1y approved these changes

2024-02-27 14:09 UTC, Balashov152 approved these changes

2024-02-27 14:09 UTC, Balashov152 commented on Tangem/App/Services/IconURLBuilder/IconURLBuilder.swift
> +    func fiatIconURL(currencyCode: String) -> URL {
`size` имеет смысл передать?

2024-02-27 14:09 UTC, merged

2024-02-27 14:10 UTC, megakoko commented on Tangem/App/Services/IconURLBuilder/IconURLBuilder.swift
> +    func fiatIconURL(currencyCode: String) -> URL {
Я думал на этот счет, но смысла особо нет по-моему