IOS-5975 add arbitrum naming hack
tangem/tangem-app-ios-old pull request #2873
Opened 2024-02-27 11:17 UTC by fedorov-d

Добавил костыль для переименования кнопки для арбитрума "Go to ETH" -> "Go to Arbitrum One (ETH)"

2024-02-27 12:24 UTC, tureck1y requested changes
Не надо костыль, давай сделаем решение, что-то вроде feeDisplayName, пригодится для других сетей

2024-02-27 19:25 UTC, m3g0byt3 commented
На будущее лучше, когда у задачи несколько пулов (в разных SDK и/или в аппе) - поддерживать для этих пулов набор ревьюверов одним и тем же

Чтобы сохранялся контекст и не получалось так, что часть пулов смотрят одни люди, а часть другие

2024-02-27 19:26 UTC, m3g0byt3 commented
А для оптимизма кста не надо делать аналогичную правку?

А в будущем и для остальных L2 типа старка/бейза

2024-02-28 15:41 UTC, tureck1y commented on Tangem/App/ViewModels/WalletModel/WalletModel.swift
> +        var feeDisplayName = feeTokenItem.currencySymbol
думаю красивее сделать через экстеншн блокчейна. Для него всегда будет вот так

2024-02-29 05:30 UTC, fedorov-d commented on Tangem/App/ViewModels/WalletModel/WalletModel.swift
> +        var feeDisplayName = feeTokenItem.currencySymbol
часть логики перенес, но не до конца понял, Леша сказал что только для арбитрума пока сделать надо т.к. там могут быть длинные названия, которые не поместятся на кнопку.

2024-02-29 12:45 UTC, fedorov-d commented
Добавил optimism

2024-02-29 13:18 UTC, m3g0byt3 commented on Tangem/Common/Extensions/Blockchain+.swift
> +}
1. Я не очень понимаю, почему нужен такой свитч
Ведь и в оптимизме и в арбитруме есть другие монеты, кроме самих ARB и OP - для перевода которых тоже нужен ARB ETH или OP ETH.

Что-то такое не подойдет?
```
  public var feeDisplayName: String {
      switch self {
      case .arbitrum, .optimism:
          return displayName + " (\(currencySymbol))"

      // все остальные кейсы явно, чтобы не пропустить
          return currencySymbol
      }
  }
```

2. Во всех остальных местах в приложении (а их весьма много) в UI будет отображаться дефолтное значение для вместо feeDisplayName - это не запутает пользователя?

2024-02-29 13:23 UTC, fedorov-d commented on Tangem/Common/Extensions/Blockchain+.swift
> +}
1. проверю, спасибо
2. пока просили только этот кейс, но еще уточню

2024-02-29 14:11 UTC, tureck1y commented on Tangem/App/Services/TransactionSendAvailabilityProvider/TransactionSendAvailabilityProvider.swift
> +                transactionAmountTypeName: String,
Может лучше сделаем optional var, чтобы конструктор явно не писать?

2024-02-29 14:11 UTC, tureck1y commented on Tangem/App/ViewModels/WalletModel/WalletModel.swift
> +    var feeDisplayName: String {
Давай положим в tokenItem

2024-02-29 18:23 UTC, fedorov-d commented on Tangem/App/ViewModels/WalletModel/WalletModel.swift
> +    var feeDisplayName: String {
вообще убрал, беру прям из блокчейна, ок?

2024-02-29 18:23 UTC, fedorov-d commented on Tangem/App/Services/TransactionSendAvailabilityProvider/TransactionSendAvailabilityProvider.swift
> +                transactionAmountTypeName: String,
убрал, логика переехала в TokenNotificationEvent

2024-02-29 18:26 UTC, tureck1y submitted a review, later dismissed

2024-02-29 18:26 UTC, fedorov-d commented on Tangem/Common/Extensions/Blockchain+.swift
> +}
по первому замечанию были опасения что будет срабатывать в неправильных кейсах, но вроде все хорошо, оставил как предложил

2024-03-01 12:01 UTC, tureck1y approved these changes

2024-03-01 12:10 UTC, m3g0byt3 approved these changes

2024-03-01 12:13 UTC, merged