IOS-6059 send update subtract fee from amount logic
tangem/tangem-app-ios-old pull request #2884
Opened 2024-02-29 05:49 UTC by megakoko

Убрал переключатель subtract from amount, вместо него будет алерт с предложением вычесть сумму
Перенес нотификацию о вычете на саммари
На саммари теперь надо показывать сумму до вычета

2024-02-29 07:23 UTC, skibinalexander commented on Tangem/Modules/Send/SendViewModel.swift
> +
Давай тоже в отдельный метод, вроде как в соседнем МР писал, if { if смотрится совсем не очень, и в соседнем МР какие то другие изменения на этом шаге

2024-02-29 07:26 UTC, skibinalexander commented on Tangem/Modules/Send/SendModel.swift
> +    private func validateFee(amount: Amount?, fee: Fee?) {
Тут странновато смотрится, ValidateFee (amount) а потом еще fee

validate(fee: Fee?, amount: Amount) ?

Как раз сверху в месте вызова странно смотрится

2024-02-29 08:03 UTC, skibinalexander approved these changes

2024-02-29 08:04 UTC, skibinalexander submitted a review, later dismissed

2024-02-29 08:05 UTC, megakoko commented on Tangem/Modules/Send/SendModel.swift
> +    private func validateFee(amount: Amount?, fee: Fee?) {
Сделал validateFee, хочется чтобы в названии всетаки присутствовало

2024-02-29 08:05 UTC, megakoko commented on Tangem/Modules/Send/SendViewModel.swift
> +
Вынес

2024-02-29 14:40 UTC, tureck1y commented on Tangem/Modules/Send/Finish/SendFinishViewModel.swift
> +    var rawAmountValue: Amount? { get }
а чем amount от rawAmount отличается?

2024-02-29 14:44 UTC, tureck1y commented on Tangem/Modules/Send/SendModel.swift
> +    var totalExceedsBalance: Bool {
np: isTotal...

2024-02-29 14:44 UTC, tureck1y commented on Tangem/Modules/Send/SendModel.swift
> +    func subtractFeeFromAmount() {
- Я получается могу его вызывать сколько угодно раз и вычитать. Нужны проверка на isFeeIncluded? 
- По неймингу тоже не сходится с isFeeIncluded

2024-02-29 14:44 UTC, tureck1y commented on Tangem/Modules/Send/SendViewModel.swift
> +            }
может в метод перенести, чтобы не засорять метод работы с шагами?

2024-02-29 14:45 UTC, tureck1y commented
не забывай ставить ревьюверами нас с @Andoran90. У других контекста нет

2024-03-01 04:20 UTC, megakoko commented on Tangem/Modules/Send/Finish/SendFinishViewModel.swift
> +    var rawAmountValue: Amount? { get }
amount — это свалидированное значение, которое будет в транзакции. rawAmount — это сырое значение, то, которое пользователь ввел. Его надо на summary показывать

2024-03-01 04:20 UTC, megakoko commented on Tangem/Modules/Send/SendModel.swift
> +    var totalExceedsBalance: Bool {
Без is нормально читается

2024-03-01 04:21 UTC, megakoko commented on Tangem/Modules/Send/SendModel.swift
> +    func subtractFeeFromAmount() {
Можно вызывать сколько угодно, но вычитать будем из введенного значения, оно не меняется

2024-03-01 04:23 UTC, megakoko commented on Tangem/Modules/Send/SendModel.swift
> +    func subtractFeeFromAmount() {
Сделал includeFeeIntoAmount

2024-03-01 04:24 UTC, megakoko commented on Tangem/Modules/Send/SendViewModel.swift
> +            }
Не хочется скрывать `self?.openStep` в отдельный метод, постарался максимально компактно тут сделать

2024-03-01 04:33 UTC, megakoko commented
> не забывай ставить ревьюверами нас с @Andoran90. У других контекста нет

У Андрея проблемы с ревью, чтобы не тормозить выбираю тех, кто уже/еще работает в это время

2024-03-01 07:48 UTC, Andoran90 requested changes

2024-03-01 07:48 UTC, Andoran90 commented on Tangem/Modules/Send/SendModel.swift
> +    }
надо бы ещё парочку `amount` завезти, а то есть всего лишь `amount` и `_amount`

2024-03-01 07:48 UTC, Andoran90 commented on Tangem/Modules/Send/SendModel.swift
> +        _amount.value
поменяй название с `_amount` на `rawAmount`, раз у тебя есть `rawAmountPublisher`, `rawAmountValue`.

2024-03-01 07:48 UTC, Andoran90 commented on Tangem/Modules/Send/Finish/SendFinishViewModel.swift
> +    var rawAmountValue: Amount? { get }
тогда в `SendModel` надо поменять названия внутри:
`amount` -> `validatedAmount`
`_amount` -> `rawAmount` (или `userInputAmount`)

а то какой-то бардак получается, по всему приложению есть приватные поля `_state` и публичное или внутреннее `state`, а тут есть `amount` (который является `CurrentValueSubject`) и не соответствующий ему `_amount` (который тоже `CurrentValueSubject`) и это 2 разных по смыслу значения

2024-03-01 07:48 UTC, Andoran90 commented on Tangem/Modules/Send/SendViewModel.swift
> +    }
учитывая что будут ещё алерты - можно вынести в отдельный `SendAlertBuilder`

2024-03-01 08:27 UTC, megakoko commented on Tangem/Modules/Send/SendViewModel.swift
> +    }
Сделал

2024-03-01 08:30 UTC, megakoko commented on Tangem/Modules/Send/Finish/SendFinishViewModel.swift
> +    var rawAmountValue: Amount? { get }
Согласен, но тогда надо будет все остальное переименовывать

У нас сначала все идет в приватную переменную с префиксом "_", потом мы ее валидируем/меняем и т.д. и отправляем в завалидированную без префикса. rawAmount / rawAmount сейчас только торчит в интерфейсы и внутри sendmodel не используется

Я предлагаю оставить так, потом в ходе ревизии сенда обсудить этот момент

2024-03-01 12:05 UTC, tureck1y commented on Tangem/Modules/Send/Finish/SendFinishViewModel.swift
> +    var rawAmountValue: Amount? { get }
Amount/rawAmount адски путает. Сделай пожалуйста amount(userInputAmount) / validatedAmount

2024-03-01 12:47 UTC, megakoko commented on Tangem/Modules/Send/Finish/SendFinishViewModel.swift
> +    var rawAmountValue: Amount? { get }
Переименовал

2024-03-01 12:49 UTC, megakoko commented
Обновил по комментариям

2024-03-01 12:55 UTC, tureck1y commented on Tangem/Modules/Send/SendModel.swift
> +    func includeFeeIntoAmount() {
Надо будет отдельно уже сделать все же название, которое будет указывать на одноразовость. Условно toggle..

2024-03-01 12:55 UTC, tureck1y commented on Tangem/Modules/Send/SendViewModel.swift
> +            }
я же просил нотификации вынести из openStep

2024-03-01 13:39 UTC, tureck1y approved these changes

2024-03-04 05:45 UTC, Andoran90 approved these changes

2024-03-04 05:45 UTC, Andoran90 commented on Tangem/Modules/Send/SendModel.swift
> +    }
в названиях ерунда какая-то получается. 
У тебя есть `validatedAmount: CurrentValueSubject<Amount, Never>`, `validatedAmountValue: Amount`, но по названиям `validatedAmount: Amount`

и то же самое с `userInputAmount: CurrentValueSubject<Amount?, Never>`, `userInputAmountValue: Amount?`, `userInputAmountPublisher: AnyPublisher<Amount?, Never>`, а по названиям ожидаешь: `userInputAmount: Amount?`, `userInputAmountValue: Decimal`, `userInputAmountPublisher: AnyPublisher<Amount?, Never>`.

Не понимаю в чем проблема написать `userInputAmountSubject` ¯\_(ツ)_/¯

2024-03-04 05:45 UTC, Andoran90 commented on Tangem/Modules/Send/SendModel.swift
> +            let validatedAmount = validatedAmount.value,
и вот тут сразу видно что названия не подходящие.

2024-03-04 05:45 UTC, Andoran90 commented on Tangem/Modules/Send/SendModel.swift
> +            let userInputAmount = userInputAmount.value,
```suggestion
            let userInputAmount = userInputAmountValue,
```

2024-03-04 05:45 UTC, Andoran90 commented on Tangem/Modules/Send/SendModel.swift
> +    var amountPublisher: AnyPublisher<Amount?, Never> {
```suggestion
    var validatedAmountPublisher: AnyPublisher<Amount?, Never> {
```

2024-03-04 05:48 UTC, megakoko commented on Tangem/Modules/Send/SendModel.swift
> +    }
Давай обсудим потом по названиям когда общее ревью будем делать

Изначально amount = Subject<Amount>, потому что это и источник правды для суммы, и паблишер. Потом код расширялся, усложнялся, добавлялось новое

2024-03-04 05:48 UTC, merged