IOS-6058 send add transaction delay alert
tangem/tangem-app-ios-old pull request #2885
Opened 2024-02-29 06:48 UTC by megakoko

Показываем алерт когда кастомная комиссия ниже низкой

2024-02-29 07:17 UTC, skibinalexander commented on Tangem/Modules/Send/SendViewModel.swift
> +            if checkCustomFee, notificationManager.hasNotificationEvent(.customFeeTooLow) {
Я бы вынес в отдельный метод какой нибудь makeAkertSendAlertFeeTooLowText

2024-02-29 08:05 UTC, megakoko commented on Tangem/Modules/Send/SendViewModel.swift
> +            if checkCustomFee, notificationManager.hasNotificationEvent(.customFeeTooLow) {
Вынес

2024-02-29 08:05 UTC, skibinalexander approved these changes, later dismissed

2024-02-29 14:47 UTC, tureck1y commented on Tangem/Modules/Send/SendViewModel.swift
> +            if checkCustomFee, notificationManager.hasNotificationEvent(.customFeeTooLow) {
в соседнем пулле тоже тут Алерт создается, видимо нужен универсальный метод, в котором будут все алерты и проверки

2024-02-29 14:47 UTC, tureck1y reviewed
@Andoran90 тоже посмотри

2024-03-01 04:25 UTC, megakoko commented on Tangem/Modules/Send/SendViewModel.swift
> +            if checkCustomFee, notificationManager.hasNotificationEvent(.customFeeTooLow) {
Не хочется скрывать `self?.openStep` в отдельный метод, постарался максимально компактно тут сделать

2024-03-01 07:31 UTC, Andoran90 requested changes

2024-03-01 07:31 UTC, Andoran90 commented on Tangem/Resources/Localizations/en.lproj/Localizable.strings
> +"send_alert_fee_too_low_text" = "Вы указали комиссию ниже рекомендуемой, это может привести к задержке исполнения вашей транзакции. Продолжить?";
во всех языках ру текстовка, вместо англ

2024-03-01 08:17 UTC, megakoko commented on Tangem/Resources/Localizations/en.lproj/Localizable.strings
> +"send_alert_fee_too_low_text" = "Вы указали комиссию ниже рекомендуемой, это может привести к задержке исполнения вашей транзакции. Продолжить?";
Английской нет

2024-03-04 05:46 UTC, Andoran90 commented on Tangem/Modules/Send/SendViewModel.swift
> +    }
надо будет обновить МР, после мержа: https://github.com/tangem/tangem-app-ios/pull/2884

2024-03-04 06:04 UTC, megakoko commented
@tureck1y @Andoran90 обновил

2024-03-04 06:49 UTC, Andoran90 commented on Tangem/Modules/Send/SendViewModel.swift
> +    }
у тебя же теперь есть билдер алертов для сенда для этих целей.

2024-03-04 07:04 UTC, megakoko commented on Tangem/Modules/Send/SendViewModel.swift
> +    }
Спасибо, поспешил. Вынес в билдер

2024-03-04 07:22 UTC, skibinalexander submitted a review, later dismissed

2024-03-04 09:45 UTC, Andoran90 approved these changes, later dismissed

2024-03-04 10:14 UTC, tureck1y reviewed
С русской текстовкой мержить не будем

2024-03-04 14:29 UTC, megakoko commented
Добавил английскую текстовку

2024-03-04 15:01 UTC, tureck1y commented
> Добавил английскую текстовку

А в остальных файлах?

2024-03-05 06:37 UTC, megakoko commented
> > Добавил английскую текстовку
> 
> А в остальных файлах?

Спасибо, обновил

2024-03-05 07:00 UTC, skibinalexander approved these changes

2024-03-05 08:22 UTC, tureck1y approved these changes

2024-03-05 08:27 UTC, merged