IOS-6163 send settings add ability to set fee in settings by default
tangem/tangem-app-ios-old pull request #2933
Opened 2024-03-06 08:59 UTC by megakoko

Надо добавить возможность задать комиссию по-умолчанию для сенда и возможность пропускать экран

2024-03-07 06:12 UTC, Andoran90 reviewed
ну что, давай видос теперь как это все работает.

2024-03-07 08:20 UTC, megakoko commented
Зачем, это только автоматический переход. При нажатии на next если все норм вместо экрана fee открывается сразу summary. В настройках стандартная гуйня

2024-03-07 09:18 UTC, tureck1y requested changes

2024-03-07 09:18 UTC, tureck1y commented on Tangem/App/Services/Common/AppSettings.swift
> +    var defaultFeeOption: FeeOption = .market
а зачем две переменные? Можно же одной обойтись.

2024-03-07 09:18 UTC, tureck1y commented on Tangem/Modules/AppSettings/AppSettingsViewModel.swift
> +            }
np: assign

2024-03-07 09:18 UTC, tureck1y commented on Tangem/Modules/Send/SendViewModel.swift
> +        }
nextStep, который var, stepAfterNext, я не понимаю что тут происходит. 

Предлагаю `AppSettings.shared.useDefaultFee, sendModel.feeValue != nil ` переложить в sendModel под одну переменную. Неправильно, что sendViewModel сама ходит в разные места и собирает условия

2024-03-07 12:11 UTC, megakoko commented on Tangem/Modules/Send/SendViewModel.swift
> -
Сделал вместо этого универсальное `step(adding:)`

2024-03-07 12:11 UTC, megakoko commented on Tangem/App/Services/Common/AppSettings.swift
> +    var defaultFeeOption: FeeOption = .market
С двумя удобнее. Плюс можно переключать тоггл и настройка выбранного уровня комиссии не собьется

2024-03-07 12:11 UTC, megakoko commented on Tangem/Modules/AppSettings/AppSettingsViewModel.swift
> +            }
Сделал

2024-03-07 12:11 UTC, megakoko commented on Tangem/Modules/Send/SendViewModel.swift
> +        }
Упростил выбор шага

Не хочется переусложнять SendModel флагом useDefaultFee. То что ходит в разные места это нормально, она же связывает все по сути, пусть useDefaultFee остается гуёвой настройкой

2024-03-07 14:35 UTC, Andoran90 commented
затем что ты обновляешь UI, делаешь новый вариант перехода, новые менюшки добавляешь. Вообще дофига обновлений. Мне надо посмотреть как это выглядит, вдобавок я уже не один раз тебе говорил - делаешь правки по UI прикладывай видео или скрины что ты сделал. Ты упорно кладешь болт на это, да ещё и порожняком споришь на этот счет. Я так понимаю тебе откровенно наплевать на то что я прошу тебя сделать из раза в раз?

2024-03-07 14:42 UTC, tureck1y commented on Tangem/App/Services/Common/AppSettings.swift
> +    var defaultFeeOption: FeeOption = .market
var defaultFeeOption: FeeOption? дает все то же самое, в чем неудобнее? Сохранять последнюю не надо

2024-03-11 06:56 UTC, megakoko commented on Tangem/App/Services/Common/AppSettings.swift
> +    var defaultFeeOption: FeeOption = .market
Для пользователя удобнее когда последняя выбранная комиссия сохраняется, если туда-сюда передернул тоггл, то настройки не сбросятся

2024-03-11 06:57 UTC, megakoko commented
> затем что ты обновляешь UI, делаешь новый вариант перехода, новые менюшки добавляешь. Вообще дофига обновлений. Мне надо посмотреть как это выглядит, вдобавок я уже не один раз тебе говорил - делаешь правки по UI прикладывай видео или скрины что ты сделал. Ты упорно кладешь болт на это, да ещё и порожняком споришь на этот счет. Я так понимаю тебе откровенно наплевать на то что я прошу тебя сделать из раза в раз?

Здесь нет ничего нового. Первая часть — это стандартные островки в настройках, вторая часть — это автоматический переход из одного экрана на другой. То же самое что было бы если пользователь нажал next

2024-03-11 07:00 UTC, Andoran90 commented
тебе сложно записать видео?

2024-03-11 07:12 UTC, megakoko commented
> тебе сложно записать видео?

Не сложно, но я не считаю это необходимым. Тут нет ничего нового. Лейаут настроек я показывал ребятам, дизайнер видел, анимации обычные.

2024-03-11 07:15 UTC, Andoran90 commented
ну окей, как хочешь. я потом сам переключусь на ветку, соберу, потыкаю, посмотрю.

2024-03-12 16:02 UTC, tureck1y commented on Tangem/App/Services/Common/AppSettings.swift
> +    var defaultFeeOption: FeeOption = .market
нет такой задачи, оставь одну пожалуйста

2024-03-12 16:23 UTC, tureck1y requested changes

2024-03-12 16:23 UTC, tureck1y commented on Tangem/Modules/AppSettings/AppSettingsViewModel.swift
> +            .assign(to: \.defaultFeeOption, on: AppSettings.shared)
про ownership weak забыл

2024-03-12 16:23 UTC, tureck1y commented on Tangem/Modules/Send/SendModel.swift
> +    init(walletModel: WalletModel, transactionSigner: TransactionSigner, addressService: SendAddressService, defaultFeeOption: FeeOption, sendType: SendType) {
Кто является источником правды по дефектной комиссии? На мой взгляд, очевидно, что AppSettings. Тогда зачем еще одно место с этой настройкой появляется здесь?

2024-03-12 16:23 UTC, tureck1y commented on Tangem/Modules/Send/SendViewModel.swift
> +        let defaultFeeOption = (AppSettings.shared.useDefaultFee && walletModel.shouldShowFeeSelector) ? AppSettings.shared.defaultFeeOption : .market
Очень удобно с двумя

2024-03-12 16:23 UTC, tureck1y commented on Tangem/Modules/Send/SendViewModel.swift
> +    private func step(adding numberOfSteps: Int) -> SendStep? {
Давай лучше сюда внутрь ассерты перенесем, чтобы от опционала избавиться

2024-04-05 12:08 UTC, closed without merging

2024-04-05 12:25 UTC, megakoko commented
Пока закрываю, решили отложить этот функционал