IOS-6074 Add information about seed phrase and number of linked cards
tangem/tangem-app-ios-old pull request #2941
Opened 2024-03-07 06:00 UTC by fedorov-d

Добавил информацию о наличии сид-фразы и кол-ве карт

2024-03-07 08:26 UTC, m3g0byt3 commented on Tangem/App/Factories/CardEmailDataFactory.swift
> +            data.append(.init(type: .wallet(.hasSeedPhrase), data: "\(wallet.isImported ?? false)"))
А `isImported` точно то, что нужно?

Потому что можно же создать кошелек с сидом, сгенерив его непосредственно при активации карты - и логически это не будет imported wallet. 
Или в таком случае isImported тоже будет тру?

2024-03-07 09:37 UTC, tureck1y commented on Tangem/App/Factories/CardEmailDataFactory.swift
> +            data.append(.init(type: .wallet(.hasSeedPhrase), data: "\(wallet.isImported ?? false)"))
Все ключи созданные не на карте(сидом) помечаются этим флагом.

2024-03-07 09:42 UTC, tureck1y requested changes

2024-03-07 09:42 UTC, tureck1y commented on Tangem/App/Factories/CardEmailDataFactory.swift
> +            .init(type: .card(.linkedCardsCount), data: "\(card.backupStatus.flatMap { $0.linkedCardsCount } ?? 0)"),
- Давай вместо нуля поставим 1. Если бэкапа нет, то карта 1
- И сюда переместим про сидфразу. Просто смотрим все кошельки и если хоть один с isImported = true, пишем что есть сид. Микса быть не может тут

2024-03-07 13:19 UTC, tureck1y approved these changes

2024-03-11 08:04 UTC, m3g0byt3 approved these changes

2024-03-12 06:26 UTC, merged