IOS-6282: Add ThreadSafeContainer wrapper
tangem/tangem-app-ios-old pull request #3004
Opened 2024-03-20 08:51 UTC by amuraveinik

2024-03-20 10:11 UTC, m3g0byt3 commented on TangemExpress/Helpers/Extensions/OptionalType.swift
> +public protocol OptionalType {
Похожий интерфейс уже есть в основном таргете (OptionalProtocol.swift), предлагаю их объеденить

и потом добавить тудушку типа такой
> // TODO: Andrey Fedorov - Move into `Core`/`Common`/`Utils`/etc module (IOS-4029)

Чтобы когда до IOS-4029 дойдут руки - не забыть про этот тип

мимопроходил

2024-03-20 17:49 UTC, tureck1y requested changes

2024-03-20 17:49 UTC, tureck1y commented on Tangem/App/Services/Analytics/AnalyticsContext/CommonAnalyticsContext.swift
> +import class TangemExpress.ThreadSafeContainer
- Что-то не то. Не надо перемещать класс никуда, только сделать по аналогии с другими местами без каких-либо других изменений

2024-03-21 06:51 UTC, amuraveinik commented on Tangem/App/Services/Analytics/AnalyticsContext/CommonAnalyticsContext.swift
> +import class TangemExpress.ThreadSafeContainer
Это комментарий к строке с импортом? Если да, то в других местах, например в `CommonPendingExpressTransactionAnalyticsTracker` и в `CommonTransactionHistoryService` точно так же импортится.

Или ты к тому чтобы выпилить экстеншены, которые я в этой задаче написал?

2024-03-21 08:54 UTC, m3g0byt3 commented on Tangem/App/Services/Analytics/AnalyticsContext/CommonAnalyticsContext.swift
> +import class TangemExpress.ThreadSafeContainer
Если вопрос к тому, почему тут импортится экспресс - то это потому что пока нет common/utils модуля, где лежали бы такие хелперы (IOS-4029) и который бы импортили те, кому он нужен

В экспрессе этот враппер нужнее всего, соответственно временно положили этот враппер туда
И экспресс пока работает как common/utils модуль)

2024-03-21 15:27 UTC, tureck1y commented on Tangem/App/Services/Analytics/AnalyticsContext/CommonAnalyticsContext.swift
> +import class TangemExpress.ThreadSafeContainer
Да, имел в виду OptionalProtocol, а коммент прилепил к другому импорту. Пуллы должны быть атомарными, по возможности. Эта задача про багофикс, поэтому я ожидаю именно багофикс без каких-либо доработок ThreadSafeContainer, рефакторингов и перемещений файлов. Почему например здесь понадобилось добавлять отдельную переменную и добавлять read? 

Если нужно что-то отрефачить, то заводим отдельную задачу.

2024-03-25 16:00 UTC, tureck1y approved these changes

2024-03-26 11:10 UTC, m3g0byt3 approved these changes

2024-03-28 07:54 UTC, merged