IOS-6134: [Crashlytics] [New Fatal Issue] [Tangem] FileLogger.swift - closure #1 in FileLogger.log(_:level:)
tangem/tangem-app-ios-old pull request #3009
Opened 2024-03-20 16:00 UTC by amuraveinik

2024-03-20 17:51 UTC, tureck1y requested changes

2024-03-20 17:51 UTC, tureck1y commented on Tangem/App/Utilities/FileLogger.swift
> +                AppLog.shared.debug("Failed to convert '\(formattedMessage)' to \(Data.self)")
тут получится цикл, потому что блоггер пишет в файл в том числе. Так что тут надо выходить без логов

2024-03-21 09:12 UTC, fedorov-d approved these changes

2024-03-25 08:39 UTC, tureck1y approved these changes

2024-03-25 13:00 UTC, merged