IOS-6362: Express: Strange animation when  "Fee is increased" notification  is hiding  for XTZ.
tangem/tangem-app-ios-old pull request #3056
Opened 2024-03-29 09:22 UTC by amuraveinik

До фикса анимация выглядит так:
https://tangem.slack.com/archives/GMXC6PP71/p1711096195833539

После фикса анимация выглядит так:
https://github.com/tangem/tangem-app-ios/assets/163782033/0104f4b5-112e-4c42-b81e-2146137b184d

2024-03-29 09:44 UTC, fedorov-d commented on Tangem/Modules/ExpressView/ExpressView.swift
> +        .animation(nil, value: UUID())
мне кажется лучше
```
.transaction { transaction in
    transaction.animation = nil
}
```

2024-03-29 10:28 UTC, Balashov152 requested changes

2024-03-29 10:28 UTC, Balashov152 commented on Tangem/Modules/ExpressView/ExpressView.swift
> +        if viewModel.expressFeeRowViewModel != nil {
Если свапать токен через `1inch` то там есть кейс, что нужен `Permission Required`. В таком случае fee не отображается, а уведомление должно быть

2024-03-29 10:28 UTC, ba1ashov commented on Tangem/Modules/ExpressView/ExpressView.swift
> +                    .frame(height: max(providerViewHeight, loadingProviderViewHeight))
Лучше проверить(добавить/убрать) паддинги в `LoadingProvidersRow()`, вообще я их выравнивал, что бы одинаковая высота была

2024-04-01 11:27 UTC, Balashov152 commented on Tangem/Common/UI/ProviderRowView/LoadingProvidersRow.swift
> -        VStack(alignment: .leading, spacing: 6) {
Мы вообще договаривались что дробные не используем, если такое есть, то к дизайнерам идем
А если тут 4 сделать, уже не та высота?

2024-04-01 11:58 UTC, amuraveinik commented on Tangem/Common/UI/ProviderRowView/LoadingProvidersRow.swift
> -        VStack(alignment: .leading, spacing: 6) {
Да, там у вьюхи провайдера высота дробная. 
Можно округлить до целого, думаю это особо даже незаметно будет

2024-04-01 13:29 UTC, tureck1y commented on Tangem/Modules/ExpressView/ExpressViewModel.swift
> +        let makeNotificationPublisher = { [notificationManager] filter in
Добавь пожалуйста комментов к коду, не очень понятно что происходит без вчитывания

2024-04-01 16:11 UTC, Balashov152 commented on Tangem/Common/UI/ProviderRowView/LoadingProvidersRow.swift
> -        VStack(alignment: .leading, spacing: 6) {
Давай тогда до целого, и в фирме напиши коммент что надо поправить высоту вьюхи, так как дробные договорились не использовать нигде

2024-04-02 11:44 UTC, Balashov152 approved these changes

2024-04-02 11:55 UTC, fedorov-d approved these changes

2024-04-02 15:34 UTC, tureck1y approved these changes

2024-04-03 07:48 UTC, merged