IOS-6424 send adding custom fee option to bitcoin
tangem/tangem-app-ios-old pull request #3061
Opened 2024-04-02 07:07 UTC by megakoko

2024-04-02 15:32 UTC, tureck1y approved these changes, later dismissed

2024-04-04 04:22 UTC, megakoko commented
@tureck1y @Andoran90 обновил текстовку https://github.com/tangem/tangem-app-ios/pull/3061/commits/a9e0b34841a9eadc2db173b202df4d0b172ea0f8

2024-04-04 07:47 UTC, megakoko commented
@tureck1y @Andoran90 обновил, подлил сдк, чуток переименовал сервис

2024-04-04 07:58 UTC, tureck1y requested changes

2024-04-04 07:58 UTC, tureck1y commented on Tangem/Modules/Send/Fee/CustomFeeService/CustomBitcoinFeeService.swift
> +            let intValue = (decimalValue as NSDecimalNumber?)?.intValue
это же не сработает без округления, надо использовать имеющиеся инструменты, а не придумывать свои

2024-04-04 07:58 UTC, tureck1y commented on Tangem/Modules/Send/Fee/CustomFeeService/CustomFeeServiceFactory.swift
> +    let walletInfo: SendWalletInfo
не используется

2024-04-04 07:58 UTC, tureck1y commented on Tangem/Modules/Send/SendViewModel.swift
> +        }
- Зачем держать customFeeService тут?
- Это же вообще должна быть константа, почему это значение мутабельно?

2024-04-04 08:02 UTC, megakoko commented on Tangem/Modules/Send/Fee/CustomFeeService/CustomBitcoinFeeService.swift
> +            let intValue = (decimalValue as NSDecimalNumber?)?.intValue
Почему не сработает? Нам поле ввода уже целое число выдает

2024-04-04 08:02 UTC, megakoko commented on Tangem/Modules/Send/Fee/CustomFeeService/CustomFeeServiceFactory.swift
> +    let walletInfo: SendWalletInfo
Спасибо, убрал

2024-04-04 08:05 UTC, megakoko commented on Tangem/Modules/Send/SendViewModel.swift
> +        }
* потому что учавствует в создании и настройке sendfeeviewmodel и sendmodel
* потому что к тому моменту как мы создали customfeeservice sendmodel уже создана

2024-04-04 08:07 UTC, tureck1y commented on Tangem/Modules/Send/Fee/CustomFeeService/CustomBitcoinFeeService.swift
> +            let intValue = (decimalValue as NSDecimalNumber?)?.intValue
Кто гарантирует всегда целое?

2024-04-04 08:07 UTC, megakoko commented on Tangem/Modules/Send/Fee/CustomFeeService/CustomBitcoinFeeService.swift
> +            let intValue = (decimalValue as NSDecimalNumber?)?.intValue
Поле ввода

2024-04-04 08:07 UTC, tureck1y commented on Tangem/Modules/Send/SendViewModel.swift
> +        }
Значит надо создать customfeeservice раньше?

2024-04-04 08:08 UTC, megakoko commented on Tangem/Modules/Send/SendViewModel.swift
> +        }
Нельзя, customfeeservice зависит от sendmodel

2024-04-04 08:08 UTC, tureck1y commented on Tangem/Modules/Send/Fee/CustomFeeService/CustomBitcoinFeeService.swift
> +            let intValue = (decimalValue as NSDecimalNumber?)?.intValue
потом рефакторят поле ввода и у тебя все ломается тут

2024-04-04 08:08 UTC, tureck1y commented on Tangem/Modules/Send/SendViewModel.swift
> +        }
И зачем это вообще выносить из SendModel

2024-04-04 08:09 UTC, tureck1y requested changes
❌

2024-04-05 03:39 UTC, megakoko commented on Tangem/Modules/Send/Fee/CustomFeeService/CustomBitcoinFeeService.swift
> +            let intValue = (decimalValue as NSDecimalNumber?)?.intValue
Добавил округление

2024-04-05 03:42 UTC, megakoko commented on Tangem/Modules/Send/SendViewModel.swift
> +        }
Чтобы sendModel не разрастался от разных реализаций кастомных комиссий

2024-04-08 09:59 UTC, megakoko commented on Tangem/Modules/Send/SendViewModel.swift
> +        }
Сделал var Blockchain.supportsCustomFees

2024-04-08 10:00 UTC, megakoko commented
@tureck1y @Andoran90 обновил

2024-04-08 11:19 UTC, tureck1y commented on Tangem/Modules/Send/SendModel.swift
> +    init(walletModel: WalletModel, transactionSigner: TransactionSigner, addressService: SendAddressService, supportsCustomFees: Bool, sendType: SendType) {
так теперь же из walletModel можно взять

2024-04-08 11:21 UTC, megakoko commented on Tangem/Modules/Send/SendModel.swift
> +    init(walletModel: WalletModel, transactionSigner: TransactionSigner, addressService: SendAddressService, supportsCustomFees: Bool, sendType: SendType) {
Точно, ступил

2024-04-08 11:21 UTC, megakoko commented
@tureck1y @Andoran90  обновил

2024-04-08 12:12 UTC, tureck1y commented on Tangem/Modules/Send/SendModel.swift
> +    private var supportsCustomFees: Bool
Так это же менять нельзя. Давай удалим вообще и будем юзать  walletModel.supportsCustomFees

2024-04-08 12:16 UTC, megakoko commented on Tangem/Modules/Send/SendModel.swift
> +    private var supportsCustomFees: Bool
Сделал

2024-04-08 12:46 UTC, megakoko commented
Исправил конфликты

2024-04-08 15:23 UTC, tureck1y approved these changes

2024-04-09 07:48 UTC, Andoran90 approved these changes

2024-04-09 07:48 UTC, Andoran90 commented on Tangem/App/ViewModels/WalletModel/WalletModel.swift
> +        bitcoinTransactionFeeCalculator != nil || blockchainNetwork.blockchain.isEvm
думаю впоследствии это надо перенести в BSDK, чтобы приложение само не решало может ли кастомная комиссия быть использована или нет, а `WalletManager` отвечал на этот вопрос

2024-04-09 07:48 UTC, Andoran90 commented on Tangem/Modules/Send/Fee/CustomFeeService/CustomEvmFeeService.swift
> +        output?.setCustomFee(recalculateFee(gasPrice: gasPrice.value, gasLimit: gasLimit.value))
```suggestion
        output?.setCustomFee(recalculateFee(gasPrice: value, gasLimit: gasLimit.value))
```

2024-04-09 07:48 UTC, Andoran90 commented on Tangem/Modules/Send/Fee/CustomFeeService/CustomEvmFeeService.swift
> +        output?.setCustomFee(recalculateFee(gasPrice: gasPrice.value, gasLimit: gasLimit.value))
```suggestion
        output?.setCustomFee(recalculateFee(gasPrice: gasPrice.value, gasLimit: value))
```

2024-04-09 07:52 UTC, megakoko commented on Tangem/Modules/Send/Fee/CustomFeeService/CustomEvmFeeService.swift
> +        output?.setCustomFee(recalculateFee(gasPrice: gasPrice.value, gasLimit: gasLimit.value))
Тоже думал об этом, но решил так оставить, чтобы была какая-то последовательность. А то один параметр из value, другой из gasLimit.value. Если value переименовать в gasPrice то тоже не нравилось

2024-04-09 08:04 UTC, merged