IOS-6453 Recursive update of fee and amount
tangem/tangem-app-ios-old pull request #3072
Opened 2024-04-03 07:58 UTC by megakoko

Цикличное обновление комиссии и суммы при выводе всей суммы

2024-04-04 04:18 UTC, megakoko commented
@tureck1y @Andoran90 еще докинул обновление текстовки

И докинул несвязанное изменение — кнопку cancel в алерт с повтором комиссии. Прошу понять и простить https://github.com/tangem/tangem-app-ios/pull/3072/commits/a997c07a927c177dfbd55a240e16fda6bdab6a7f

2024-04-04 07:39 UTC, Andoran90 commented on Tangem/Modules/Send/SendModel.swift
>              return
не выбрасывается ошибка в хэндлер.
ещё можно добавить `feeValue?.amount` в `guard` и не надо будет проверять в `flatMap` его наличие

2024-04-04 07:39 UTC, Andoran90 commented on Tangem/Modules/Send/SendModel.swift
> +                    self?.feeInclusionSubject?.send(())
почему тут меняется значение введенное пользователем? значение же общее не должно меняться. И почему `isFeeIncluded` меняется только в этой ветке?

2024-04-04 07:47 UTC, tureck1y commented on Tangem/Modules/Send/SendViewModel.swift
> +                    self?.openStep(step, stepAnimation: stepAnimation, updateFee: false)
давай self развернем, будет чище

2024-04-04 07:47 UTC, tureck1y commented on Tangem/Modules/Send/SendModel.swift
> +                    self?.feeInclusionSubject?.send(())
Почему вызов  includeFeeIntoAmount приводит к обновлению fee?

2024-04-04 07:53 UTC, megakoko commented on Tangem/Modules/Send/SendModel.swift
>              return
Во flatMap проверяем потому что сумма комиссии меняется

2024-04-04 07:54 UTC, megakoko commented on Tangem/Modules/Send/SendModel.swift
> +                    self?.feeInclusionSubject?.send(())
Комиссия зависит от суммы, сумма зависит от комиссии

Циклично обновляем оба значения пока комиссия не устаканится

2024-04-04 07:58 UTC, megakoko commented on Tangem/Modules/Send/SendViewModel.swift
> +                    self?.openStep(step, stepAnimation: stepAnimation, updateFee: false)
Сделал

2024-04-04 07:58 UTC, megakoko commented on Tangem/Modules/Send/SendModel.swift
>              return
Ошибку добавил

2024-04-04 07:59 UTC, megakoko commented on Tangem/Modules/Send/SendModel.swift
> +                    self?.feeInclusionSubject?.send(())
Например такой сценарий

<img width="285" alt="Screenshot 2024-04-04 at 15 59 37" src="https://github.com/tangem/tangem-app-ios/assets/12209839/61772820-baea-45be-a93a-9d2a8459453b">

2024-04-04 08:00 UTC, megakoko commented
@tureck1y @Andoran90 обновил

2024-04-04 08:02 UTC, tureck1y commented on Tangem/Modules/Send/SendModel.swift
> +                    self?.feeInclusionSubject?.send(())
ну пусть это делается по подписке отдельно, не в самом методе же

2024-04-04 08:03 UTC, tureck1y commented on Tangem/Modules/Send/SendModel.swift
> +                    self?.feeInclusionSubject?.send(())
Я все равно ничего не понял что за магия

2024-04-04 08:10 UTC, tureck1y requested changes
Нужно объяснение этой логики, что еще за рекурсивное обновление фи

2024-04-04 08:13 UTC, megakoko commented
> Нужно объяснение этой логики, что еще за рекурсивное обновление фи

Я выше писал https://github.com/tangem/tangem-app-ios/pull/3072#discussion_r1551119959

Комиссия зависит от суммы, сумма зависит от комиссии. Комиссия зависит от размера транзакции, который зависит от того, какие там аутпуты, какая у нас сумма транзакции и какая комиссия установлена. Это в-основном для UTXO сделано. Но у Анжелики подобная проблема с полигоном вроде была

2024-04-04 08:29 UTC, tureck1y commented
> > Нужно объяснение этой логики, что еще за рекурсивное обновление фи
> 
> Я выше писал [#3072 (comment)](https://github.com/tangem/tangem-app-ios/pull/3072#discussion_r1551119959)
> 
> Комиссия зависит от суммы, сумма зависит от комиссии. Комиссия зависит от размера транзакции, который зависит от того, какие там аутпуты, какая у нас сумма транзакции и какая комиссия установлена. Это в-основном для UTXO сделано. Но у Анжелики подобная проблема с полигоном вроде была

А как раньше работало?

2024-04-05 05:31 UTC, megakoko commented
> > > Нужно объяснение этой логики, что еще за рекурсивное обновление фи
> > 
> > 
> > Я выше писал [#3072 (comment)](https://github.com/tangem/tangem-app-ios/pull/3072#discussion_r1551119959)
> > Комиссия зависит от суммы, сумма зависит от комиссии. Комиссия зависит от размера транзакции, который зависит от того, какие там аутпуты, какая у нас сумма транзакции и какая комиссия установлена. Это в-основном для UTXO сделано. Но у Анжелики подобная проблема с полигоном вроде была
> 
> А как раньше работало?

Раньше пользователь вводил сумму для максимального вывода и мы ей оперировали при подсчете комиссии. При изменении комиссии сумму мы не пересчитывали и в поле ввода ничего не меняли. Потом при создании транзакции просто указывали в ней изначальную сумму минус сумму комиссии.

То есть получается комиссию рассчитали для одной суммы, а в транзакции будет уже другая. Для UTXO это не совсем корректно, т.к. от суммы и аутпутов зависит структура транзакции, и соответственно ее размер.

2024-04-05 09:19 UTC, megakoko commented
Закрываю. Новый МР: https://github.com/tangem/tangem-app-ios/pull/3086

2024-04-05 09:19 UTC, closed without merging