IOS-6464 [send] - my wallets list - misc fixes
tangem/tangem-app-ios-old pull request #3079
Opened 2024-04-04 04:01 UTC by megakoko

* Disregarding blockchain curve when comparing blockchains
* Dont include tokens from the same user wallet

2024-04-04 08:20 UTC, tureck1y requested changes

2024-04-04 08:20 UTC, tureck1y commented on Tangem/Common/Extensions/Blockchain+.swift
> +    static func curveInsensitiveCompare(_ left: Blockchain, _ right: Blockchain) -> Bool {
- не надо сюда добавлять специфическую функцию сравнения, которая нужна в одном месте
- зачем смотреть на тестнет? Думаю этого не должно быть

2024-04-05 03:22 UTC, megakoko commented on Tangem/Common/Extensions/Blockchain+.swift
> +    static func curveInsensitiveCompare(_ left: Blockchain, _ right: Blockchain) -> Bool {
* перенес
* зачем не смотреть на тестнет? С одной стороны да, удобно будет переводить с мейннета на тестнет, но думаю лучше оставить проверку

2024-04-05 13:58 UTC, tureck1y requested changes

2024-04-05 13:58 UTC, tureck1y commented on Tangem/Modules/Send/Destination/SendDestinationViewModel.swift
> +}
сравни пожалуйста инлайн, без теснота

2024-04-08 03:42 UTC, megakoko commented on Tangem/Modules/Send/Destination/SendDestinationViewModel.swift
> +}
Окей, сделал

2024-04-08 07:58 UTC, Andoran90 approved these changes

2024-04-08 11:45 UTC, tureck1y approved these changes

2024-04-08 13:39 UTC, merged