IOS-6483 Handling lack of quotes
tangem/tangem-app-ios-old pull request #3088
Opened 2024-04-05 10:38 UTC by megakoko

Если рейты не загрузились надо выключать переключатель фиат-крипта

2024-04-05 15:23 UTC, Balashov152 commented on Tangem/Modules/Send/SendViewModel.swift
> +            canUseFiatCalculation: walletModel.tokenItem.currencyId != nil && Self.quotesRepository.quote(for: walletModel.tokenItem) != nil
Вообще в `quote(for: walletModel.tokenItem)` уже есть проверка на `currencyId`

2024-04-08 03:50 UTC, megakoko commented on Tangem/Modules/Send/SendViewModel.swift
> +            canUseFiatCalculation: walletModel.tokenItem.currencyId != nil && Self.quotesRepository.quote(for: walletModel.tokenItem) != nil
Спасибо, упростил

2024-04-08 08:01 UTC, Balashov152 submitted a review, later dismissed

2024-04-08 11:38 UTC, tureck1y requested changes

2024-04-08 11:38 UTC, tureck1y commented on Tangem/Modules/Send/SendViewModel.swift
> +    @Injected(\.quotesRepository) private static var quotesRepository: TokenQuotesRepository
не надо статик, зачем, это и так синглтон

2024-04-08 11:40 UTC, megakoko commented on Tangem/Modules/Send/SendViewModel.swift
> +    @Injected(\.quotesRepository) private static var quotesRepository: TokenQuotesRepository
В момент обращения self еще недоинициализован, поэтому статик

2024-04-08 11:41 UTC, tureck1y commented on Tangem/Modules/Send/SendViewModel.swift
> +    @Injected(\.quotesRepository) private static var quotesRepository: TokenQuotesRepository
тогда надо отрефачить сборку, не апрув

2024-04-08 12:00 UTC, megakoko commented on Tangem/Modules/Send/SendViewModel.swift
> +    @Injected(\.quotesRepository) private static var quotesRepository: TokenQuotesRepository
Сделал передачу флага сверху по иерархии

2024-04-08 12:00 UTC, megakoko commented
@tureck1y @Balashov152 обновил

2024-04-08 12:02 UTC, Balashov152 approved these changes

2024-04-08 12:17 UTC, tureck1y approved these changes

2024-04-08 12:17 UTC, tureck1y commented on Tangem/Modules/Send/SendCoordinator.swift
> +        let canUseFiatCalculation = quotesRepository.quote(for: options.walletModel.tokenItem) != nil
Точно надо будет сделать что-то типа CommonExpressModulesFactory

2024-04-08 13:43 UTC, merged