IOS-5914 Upgrade Amplitude
tangem/tangem-app-ios-old pull request #3135
Opened 2024-04-12 18:19 UTC by fedorov-d

В рамках фикса редкого краша (https://console.firebase.google.com/project/tangemapp/crashlytics/app/ios:com.tangem.Tangem/issues/5b7baf453e60ef206d66a34a33d4a914?utm_campaign=extensions&utm_medium=JIRA&utm_source=NEW_ISSUE) решил обновить библиотеку. Из АПИ амплитуды убрали instance, поэтому пришлось перенести в InjectedValues

2024-04-15 09:18 UTC, amuraveinik submitted a review, later dismissed

2024-04-15 09:20 UTC, Balashov152 approved these changes, later dismissed

2024-04-16 10:59 UTC, tureck1y requested changes

2024-04-16 10:59 UTC, tureck1y commented on Tangem/App/Services/Analytics/Analytics+Amplitude.swift
> +    }()
Давай просто перенесем это в класс с аналитикой. Не предполагается использование амплитуды напрямую, такие интерфейсы только будут смущать

2024-04-17 13:28 UTC, fedorov-d commented on Tangem/App/Services/Analytics/Analytics+Amplitude.swift
> +    }()
перенес

2024-04-17 13:30 UTC, tureck1y approved these changes, later dismissed

2024-04-18 09:20 UTC, Balashov152 approved these changes

2024-04-18 10:26 UTC, tureck1y approved these changes

2024-04-18 10:26 UTC, merged