IOS-6610 add a mechanism for automatic indexation of wallets
tangem/tangem-app-ios-old pull request #3204
Opened 2024-04-26 05:21 UTC by megakoko

2024-04-26 09:37 UTC, tureck1y commented
это уже не надо в релиз

2024-04-27 03:09 UTC, megakoko commented
Окей, потом перенаправлю

2024-04-27 16:36 UTC, tureck1y requested changes
У меня много замечений.
- Управление именем кошелька - это не ответственность репозитория. Вместо того, чтобы назначать дефолтное имя, а потом его апдейтить, нужно сразу давать правильное имя
- Всю логику по выбору дефолтного имени, валидации переименования и миграции нужно вынести в отдельный хелпер и покрыть его тестами
- В самой логике я так и не разобрался.
 Согласно требованиям:
`для уже созданных кошельков с одинаковым название добавить index после названия`

думаю достаточно разбить кошельки на массивы с одинаковыми именами и назначит индексы начиная с 2, если в массиве более одного элемента.

Для поиска последнего индекса думаю тоже можно сделать проще - в функцию приходят все имеющиеся имена и префикс нового кошелька (wallet, note и тп). Фильтруем все по префиксу, парами индексы, ищем максимальный, инкрементируем

2024-05-13 15:43 UTC, Sateetas commented
> Для поиска последнего индекса думаю тоже можно сделать проще - в функцию приходят все имеющиеся имена и префикс нового кошелька (wallet, note и тп). Фильтруем все по префиксу, парами индексы, ищем максимальный, инкрементируем

@tureck1y тогда в твоем варианте при наличии двух кошельков с именами "Wallet" и "Wallet 100" следующий добавленный будет иметь имя "Wallet 101", хотя должен быть "Wallet 2"
Мы с Настей этот момент обсуждали

2024-05-22 12:44 UTC, megakoko commented
https://github.com/tangem/tangem-app-ios/pull/3322

2024-05-22 12:44 UTC, closed without merging

2024-05-23 16:31 UTC, tureck1y commented
> > Для поиска последнего индекса думаю тоже можно сделать проще - в функцию приходят все имеющиеся имена и префикс нового кошелька (wallet, note и тп). Фильтруем все по префиксу, парами индексы, ищем максимальный, инкрементируем
> 
> @tureck1y тогда в твоем варианте при наличии двух кошельков с именами "Wallet" и "Wallet 100" следующий добавленный будет иметь имя "Wallet 101", хотя должен быть "Wallet 2" Мы с Настей этот момент обсуждали

Если нужна такая логика, то у нас есть уже похожая в сдк при вычислении следующего индекса кошелька в CreateWalletCommand.calculateWalletIndex