IOS-6753 send improve the loading of fees
tangem/tangem-app-ios-old pull request #3223
Opened 2024-05-06 08:59 UTC by megakoko

Переделали флоу загрузки

2024-05-06 14:25 UTC, tureck1y commented on Tangem/Modules/Send/SendViewModel.swift
> +            }
что-то непонятное

2024-05-07 08:26 UTC, megakoko commented on Tangem/Modules/Send/SendViewModel.swift
> +            }
Упростил

2024-05-07 10:31 UTC, tureck1y requested changes

2024-05-07 10:31 UTC, tureck1y commented on Tangem/Modules/Send/SendViewModel.swift
> +    private func openStep(_ step: SendStep, stepAnimation: SendView.StepAnimation, checkCustomFee: Bool = true, updateFee: Bool) {
Вызываем openStep, в нем проверки на стейт клавиатуры, потом из него вызывается hideKeyboard, который опять вызывает openStep. Можно же через каллбэки, асинки сделать. Метод с клавиатурой, пусть клавиатурой и занимается. OpenStep должен делать то, ради чего он создан - переходить на след шаг.

2024-05-13 08:42 UTC, megakoko commented on Tangem/Modules/Send/SendViewModel.swift
> +    private func openStep(_ step: SendStep, stepAnimation: SendView.StepAnimation, checkCustomFee: Bool = true, updateFee: Bool) {
Обновил

2024-05-13 08:59 UTC, tureck1y commented on Tangem/Modules/Send/SendViewModel.swift
> +    private func openStep(_ step: SendStep, stepAnimation: SendView.StepAnimation, checkCustomFee: Bool = true, updateFee: Bool) {
В этом методе есть несколько return. Нужны функциональные комменты зачем и почему, сейчас я вообще не понимаю почему при вызове openStep происходит updateFee и закрытие клавиатуры

2024-05-15 07:02 UTC, megakoko commented on Tangem/Modules/Send/SendViewModel.swift
> +    private func openStep(_ step: SendStep, stepAnimation: SendView.StepAnimation, checkCustomFee: Bool = true, updateFee: Bool) {
В openStep уже давно происходит updateFee и закрытие клавиатуры, return-ы тоже не вчера появились. Что сейчас поменялось что ты перестал понимать?

2024-05-15 09:35 UTC, tureck1y commented on Tangem/Modules/Send/SendViewModel.swift
> +    private func openStep(_ step: SendStep, stepAnimation: SendView.StepAnimation, checkCustomFee: Bool = true, updateFee: Bool) {
Ну это вопрос к тебе, почему в этот код постоянно вносятся изменения и его невозможно понять. Почему openStep помимо open step еще и клавиатуру закрывает и фи обновляет?

Какая-то сложность написать комменты? Ты сам сюда придешь через месяц и не вспомнишь что и почему

2024-05-15 11:30 UTC, megakoko commented on Tangem/Modules/Send/SendViewModel.swift
> +    private func openStep(_ step: SendStep, stepAnimation: SendView.StepAnimation, checkCustomFee: Bool = true, updateFee: Bool) {
Изменения вносятся потому что мы на лету меняем сенд. Я этот код понимаю без проблем, там все названия методов и переменных говорят сами за себя, писать комментарии ради комментариев — это лишнее

2024-05-16 09:57 UTC, tureck1y commented on Tangem/Modules/Send/SendViewModel.swift
> +    private func openStep(_ step: SendStep, stepAnimation: SendView.StepAnimation, checkCustomFee: Bool = true, updateFee: Bool) {
Тебе сложно комменты написать чтобы стало понятно еще кому-то кроме тебя?

2024-05-16 14:21 UTC, megakoko commented on Tangem/Modules/Send/SendViewModel.swift
> +    private func openStep(_ step: SendStep, stepAnimation: SendView.StepAnimation, checkCustomFee: Bool = true, updateFee: Bool) {
Задача этого кейса — обновить флоу загрузки комиссии, не писать комментарии к старому коду

Если вам непонятно что-то в этом методе — скажите что конкретно, сделаю. Объяснять код комментариями мне не нравится, лучше его упростить, переименовать, перетасовать. Можно вместе в рамках пост-релизного ревью кода обсудить этот кусок

2024-05-16 16:24 UTC, tureck1y commented on Tangem/Modules/Send/SendViewModel.swift
> +    private func openStep(_ step: SendStep, stepAnimation: SendView.StepAnimation, checkCustomFee: Bool = true, updateFee: Bool) {
> Задача этого кейса — обновить флоу загрузки комиссии, не писать комментарии к старому коду


Что значит старый код? Этого кода еще даже в продакшене нет, его писал ты чуть ранее. Пока делал эту задачу несколько раз вносил в этот метод изменения и мы на ревью пытались понять что к чему, финальный вариант по прежнему непонятен и я тебя попросил добавить ФУНКЦИОНАЛЬНЫЕ комменты к return!

Вот тут выходим потому-то потому-то, пользовательский кейс такой-то.

2024-05-16 17:05 UTC, tureck1y commented
Мержу так, код так и останется для нас загадкой

2024-05-16 17:05 UTC, merged

2024-05-17 04:43 UTC, megakoko commented on Tangem/Modules/Send/SendViewModel.swift
> +    private func openStep(_ step: SendStep, stepAnimation: SendView.StepAnimation, checkCustomFee: Bool = true, updateFee: Bool) {
Ты напиши что в этом коде непонятного

```
if updateFee {
            self.updateFee()
            keyboardVisibilityService.hideKeyboard(completion: openStepAfterDelay)
            return
        }
```

Или в этом. Мне писать комментарии вида `if keyboard visible and step not opensKeyboardByDefault — hide keyboard`?

```
        if keyboardVisibilityService.keyboardVisible, !step.opensKeyboardByDefault {
            keyboardVisibilityService.hideKeyboard(completion: openStepAfterDelay)
            return
        }
```

2024-05-17 09:36 UTC, tureck1y commented on Tangem/Modules/Send/SendViewModel.swift
> +    private func openStep(_ step: SendStep, stepAnimation: SendView.StepAnimation, checkCustomFee: Bool = true, updateFee: Bool) {
Я c самого первого сообщения просил смысловые комментарии, описание кейса