IOS-6673 Make format digits
tangem/tangem-app-ios-old pull request #3238
Opened 2024-05-08 07:58 UTC by skibinalexander

Задача была в том, что для токенов с маленькой стоимостью сделать цену с округлением до 8 знаков.

Добавил для Фиата форматер. На первый взгляд излишне, но зато легко расширять, по примеру TotalBalance форматера.

Нужно трекать значение от 0.01

Побоялся в свопе делать такой форматер, передал дефолтовый

![Simulator Screenshot - iPhone 15 - 2024-05-08 at 10 54 38](https://github.com/tangem/tangem-app-ios/assets/5384724/18be7c1c-d7cb-41a4-866c-34f7678d24ec)
![Simulator Screenshot - iPhone 15 - 2024-05-08 at 10 54 56](https://github.com/tangem/tangem-app-ios/assets/5384724/2de004ea-189a-4c90-9d5e-3d8c272cf89f)

2024-05-20 09:50 UTC, tureck1y requested changes

2024-05-20 09:50 UTC, tureck1y commented on Tangem/App/Services/FeeFormatter/CommonFeeFormatter.swift
> +    }
Плохо что дублируется логика

2024-05-20 09:50 UTC, tureck1y commented on Tangem/App/Utilities/BalanceFormatter/BalanceFormattingOptions.swift
> +}
Дефолтное поведение есть дефолтное, оно должно быть одно. Апи форматтера должно быть максимально простым к использованию. 

Создали форматтер, отформатировали. Если поведение нужно поменять, то подставили другую константу с понятным названием и комментом, либо переопределили полностью, если требуется. 

Сейчас я вижу две переменных с префиксом default и еще какой-то метод, куда надо передать какой-то value

Недавно у @megakoko была похожая задача с переопредением опций. Договоритесь, чтобы решение учитывало все варианты.

2024-05-20 10:30 UTC, skibinalexander commented on Tangem/App/Utilities/BalanceFormatter/BalanceFormattingOptions.swift
> +}
Понял посмотрю. Делал расширяемо чтобы не сломать там , где не требуется изменений. Посмотрю

2024-05-21 08:56 UTC, closed without merging

2024-05-21 08:56 UTC, skibinalexander commented
Закрыл, потому что обсудили сделать по другому