IOS-6835 Added SendFeatureProvider
tangem/tangem-app-ios-old pull request #3258
Opened 2024-05-14 04:10 UTC by megakoko

Спрашиваем у бека доступен ли сенд

По аналогии с гео

2024-05-14 09:52 UTC, tureck1y requested changes

2024-05-14 09:52 UTC, tureck1y commented on Tangem/App/Services/TangemApiService/TangemApiService.swift
> +    var features: [String: Bool] { get }
Это не ответственность TangemApiService. Ты же сделал SendFeatureProvider, пусть он и инкапсулирует всю логику.

2024-05-14 10:53 UTC, megakoko commented on Tangem/App/Services/TangemApiService/TangemApiService.swift
> +    var features: [String: Bool] { get }
Ответственность TangemApiService — получить и отдать фичи потребителям, что он и делает. SendFeatureProvider чтобы избежать копипасты по всем местам.

2024-05-14 11:28 UTC, Andoran90 commented on Tangem/App/Services/TangemApiService/TangemApiService.swift
> +    var features: [String: Bool] { get }
ответственность `TangemApiService` обратиться к апишке и загрузить информацию оттуда только. Он не должен хранить эту инфу, у `TangemApiService` запросили инфу, он дернул ручку бэка и вернул ответ. Может лучше сделать единую сущность что-то типа `FeatureAvailabilityProvider`, которая будет грузить инфу с бэка и отвечать доступна фича или нет.

2024-05-14 11:30 UTC, Andoran90 commented on Tangem/App/Services/TangemApiService/TangemApiService.swift
> +    var features: [String: Bool] { get }
собственно `SendFeatureProvider` сделать более глобальным, т.к. будет ещё добавляться туда и другой функционал

2024-05-15 07:04 UTC, megakoko commented on Tangem/App/Services/TangemApiService/TangemApiService.swift
> +    var features: [String: Bool] { get }
В чем разница между гео и фичами что одно мы позволяем хранить внутри сервиса, а другое — нет?

2024-05-15 09:33 UTC, tureck1y commented on Tangem/App/Services/TangemApiService/TangemApiService.swift
> +    var features: [String: Bool] { get }
Гео тут тоже быть не должно, был рефакторинг всех запросов в приложении и гео сюда попал как временное решение для уменьшения количества изменений. Этот фича тоггл не на постоянку, поэтому глобальным смысла делать нет.

2024-05-15 11:27 UTC, megakoko commented on Tangem/App/Services/TangemApiService/TangemApiService.swift
> +    var features: [String: Bool] { get }
Раз гео временное решение и фичетоггл не на постоянку я предлагаю оставить код как есть. С удалением фичетогла подчистим

2024-05-16 10:07 UTC, tureck1y commented on Tangem/App/Services/TangemApiService/TangemApiService.swift
> +    var features: [String: Bool] { get }
Если видишь плохой код, то надо не копировать, а завести задачку на техдолг/тудушку и сделать нормально, вот это правильный подход

2024-05-16 14:24 UTC, megakoko commented on Tangem/App/Services/TangemApiService/TangemApiService.swift
> +    var features: [String: Bool] { get }
> Гео тут тоже быть не должно, был рефакторинг всех запросов в приложении и гео сюда попал как временное решение для уменьшения количества изменений

Почему у нас плохой код остается в исходниках без записи в техдолг или тудушки? Если такой код есть я предполагаю что это допустимая реализация и делаю подобно чтобы не плодить разные реализации. Подход тут такой же — как можно раньше в процессе старта приложения запросить параметр и затем использовать его в разных потребителях

2024-05-16 16:25 UTC, tureck1y commented on Tangem/App/Services/TangemApiService/TangemApiService.swift
> +    var features: [String: Bool] { get }
Вместо того, чтобы поправить, ты второй день пишешь комменты

2024-05-16 17:48 UTC, tureck1y commented on Tangem/App/Services/TangemApiService/TangemApiService.swift
> +    var features: [String: Bool] { get }
Готово, завел тудушку с задачей, отрефакторил, теперь все на своих местах и удалять придется один файл и один метод

2024-05-16 17:49 UTC, merged