IOS-6785 Limiting recent transactions to 10
tangem/tangem-app-ios-old pull request #3261
Opened 2024-05-14 08:10 UTC by megakoko

2024-05-14 09:34 UTC, tureck1y requested changes

2024-05-14 09:34 UTC, tureck1y commented on Tangem/Modules/Send/Destination/SendDestinationViewModel.swift
> +                let numberOfRecentTransactions = 10
Оформи пожалуйста константу по правилам

2024-05-14 09:35 UTC, megakoko commented on Tangem/Modules/Send/Destination/SendDestinationViewModel.swift
> +                let numberOfRecentTransactions = 10
Через extension/constants?

2024-05-16 16:19 UTC, tureck1y commented on Tangem/Modules/Send/Destination/SendDestinationViewModel.swift
> +                let numberOfRecentTransactions = 10
Да, как и везде по проекту

2024-05-16 16:58 UTC, tureck1y commented on Tangem/Modules/Send/Destination/SendDestinationViewModel.swift
> +                let numberOfRecentTransactions = 10
Сделал сам, потратив 5 минут

2024-05-16 16:58 UTC, merged

2024-05-17 04:27 UTC, megakoko commented on Tangem/Modules/Send/Destination/SendDestinationViewModel.swift
> +                let numberOfRecentTransactions = 10
Эти правила только ко мне применяются?

https://github.com/tangem/tangem-app-ios/blob/6b450ddd1e3147f02709fac5fc1a43e4369cb9ef/Tangem/App/Services/APIListProvider/CommonAPIListProvider.swift#L16

2024-05-17 09:33 UTC, tureck1y commented on Tangem/Modules/Send/Destination/SendDestinationViewModel.swift
> +                let numberOfRecentTransactions = 10
Пропустили на ревью, это не повод повторять ошибки