IOS-6841 Added user wallet finder
tangem/tangem-app-ios-old pull request #3269
Opened 2024-05-15 05:54 UTC by megakoko

При переводе токенов на другие свои кошельки надо добавлять эти токены если они отсутствуют. Вынес отдельно чтобы не перегружать существующие модели. Над названием и API долго думал, ни к чему лучшему не пришел, если есть идеи — буду рад услышать

2024-05-15 10:42 UTC, tureck1y commented on Tangem/Modules/Send/UserWalletFinder.swift
> +//  UserWalletFinder.swift
Это все же WalletModelFinder

2024-05-15 10:42 UTC, tureck1y commented on Tangem/Modules/Send/UserWalletFinder.swift
> +                walletModels.contains { $0.tokenItem == blockchainTokenItem && $0.defaultAddress == address }
нагляднее будет искать по blockchainNetwork и isMainToken вместо создания blockchainTokenItem. В WC есть похожий код и адрес там сравнивается регистронезависимо, нужно ли тут также?

2024-05-15 11:45 UTC, megakoko commented on Tangem/Modules/Send/UserWalletFinder.swift
> +                walletModels.contains { $0.tokenItem == blockchainTokenItem && $0.defaultAddress == address }
Сделал

Регистронезависимость я думаю не нужна, кейсы в которых она понадобилась бы не очень реалистичны

2024-05-15 11:47 UTC, megakoko commented on Tangem/Modules/Send/UserWalletFinder.swift
> +//  UserWalletFinder.swift
Ищем все-таки UserWallet, и в него добавляем по необходимости. Я такой логикой руководствовался

Плюс сам вызов `WalletModelFinder().addTokenItem` плохо читается

2024-05-15 15:22 UTC, tureck1y submitted a review, later dismissed

2024-05-16 08:11 UTC, Andoran90 requested changes

2024-05-16 08:11 UTC, Andoran90 commented on Tangem/Modules/Send/UserWalletFinder.swift
> +                walletModels.contains { $0.isMainToken && $0.blockchainNetwork == blockchainNetwork && $0.defaultAddress == address }
надо поменять местами поиски, чтобы в начале проверить что это целевая сеть, а потом уже проверять добавлен токен или нет, поможет избежать лишнего прогона для каждой сети

2024-05-16 08:24 UTC, megakoko commented on Tangem/Modules/Send/UserWalletFinder.swift
> +                walletModels.contains { $0.isMainToken && $0.blockchainNetwork == blockchainNetwork && $0.defaultAddress == address }
Я не понимаю как это может помочь. Мы проверяем есть ли блокчейн tokenItem и есть ли токен-tokenItem, как по мне от перестановки не поменяется смысл

Объясни пожалуйста подробнее

2024-05-16 08:25 UTC, Andoran90 commented on Tangem/Modules/Send/UserWalletFinder.swift
> +                walletModels.contains { $0.isMainToken && $0.blockchainNetwork == blockchainNetwork && $0.defaultAddress == address }
у тебя первый поиск идет на проверку `!walletModels.contains { $0.tokenItem == tokenItem }`, а второй `walletModels.contains { $0.isMainToken && $0.blockchainNetwork == blockchainNetwork && $0.defaultAddress == address }`

ты в начале проходишь по всему списку и проверяешь нет ли целевого токена в списке, а потом уже проверяешь - а правильная ли это вообще сеть.

2024-05-16 08:29 UTC, Andoran90 commented on Tangem/Modules/Send/UserWalletFinder.swift
> +                walletModels.contains { $0.isMainToken && $0.blockchainNetwork == blockchainNetwork && $0.defaultAddress == address }
надо в начале проверить это вообще та сеть что нужна, а потом уже проверять есть или нет токен. В целом можно было бы и не делать это через 2 цикла, а в одном оформить все с флажками, но так приемлемо.

2024-05-16 08:32 UTC, megakoko commented on Tangem/Modules/Send/UserWalletFinder.swift
> +                walletModels.contains { $0.isMainToken && $0.blockchainNetwork == blockchainNetwork && $0.defaultAddress == address }
Поменял

2024-05-16 08:32 UTC, megakoko commented
@tureck1y @Andoran90 обновил

2024-05-16 08:33 UTC, Andoran90 approved these changes

2024-05-16 12:33 UTC, tureck1y approved these changes

2024-05-16 16:51 UTC, merged