IOS-6805 Allow to send funds to self for several blockchains
tangem/tangem-app-ios-old pull request #3271
Opened 2024-05-15 07:52 UTC by fedorov-d

Блокчейны соласованы с Лешей

2024-05-15 11:22 UTC, m3g0byt3 reviewed
У нас история транзакций (которая есть у нескольких UTXO из этого пула) насколько помню не поддерживает отображение транз, отправленных самому себе (на это есть тудушка в коде + задача).

Такие транзы просто отфильтровываются из списка, это 100% так для EVM сетей, насчет UTXO не скажу, надо смотреть в коде.

На такой кейс даже нет дизайна, как их отображать (это не outbound/inbound транзы)

2024-05-15 15:44 UTC, tureck1y requested changes

2024-05-15 15:44 UTC, tureck1y commented on Tangem/Modules/Send/SendAddressService.swift
> +    init(walletAddresses: [Address], addressService: AddressService, blockchain: Blockchain) {
Давай  будем передавать сюда bool, а в SendAddressFactory уже ходить в блокчейн за ее значением, чтобы не добавлять в DefaultSendAddressService зависимость от blockchain

2024-05-16 16:12 UTC, tureck1y approved these changes

2024-05-17 13:06 UTC, m3g0byt3 approved these changes
Задачку на чек истории транз и возможные ее доработки наверное можно сразу в некст (или через один) спринт закинуть

2024-05-17 13:57 UTC, merged