IOS-6741 send adding a mark before rounding numbers only for fiat
tangem/tangem-app-ios-old pull request #3272
Opened 2024-05-15 07:55 UTC by megakoko

Форматируем фиат как "< XXX" когда меньше одной копейки

2024-05-15 10:27 UTC, tureck1y submitted a review, later dismissed

2024-05-15 10:27 UTC, tureck1y commented on Tangem/App/Utilities/BalanceFormatter/BalanceFormatter.swift
> +           0 < balance, balance < lowestRepresentableValue {
np: рэнж или привычное balance > 0 читается намного лучше

2024-05-15 10:27 UTC, tureck1y commented on Tangem/Modules/Send/Summary/SendSummaryViewModel.swift
> +        let formattingOptions = BalanceFormattingOptions(
NP: Можно было бы добавить в BalanceFormattingOptions статичную дефолтную конфигурацию и резнуть

2024-05-15 11:01 UTC, megakoko commented on Tangem/App/Utilities/BalanceFormatter/BalanceFormatter.swift
> +           0 < balance, balance < lowestRepresentableValue {
Range не получится, там нижняя граница включена будет

0 < X && X < 0.01 специально сделал, так читается как интервал 0 < X < 0.01

2024-05-15 11:03 UTC, megakoko commented on Tangem/Modules/Send/Summary/SendSummaryViewModel.swift
> +        let formattingOptions = BalanceFormattingOptions(
Согласен, сделал через функцию иначе имя слишком длинное выходило

2024-05-15 11:03 UTC, megakoko commented
@tureck1y обновил

2024-05-15 15:36 UTC, tureck1y requested changes

2024-05-15 15:36 UTC, tureck1y commented on Tangem/App/Utilities/BalanceFormatter/BalanceFormattingOptions.swift
> +    static func defaultFiatFormattingOptions(formatEpsilonAsLowestRepresentableValue: Bool = false) -> BalanceFormattingOptions {
Зачем, было же нормально с переменной, просто сделать отдельную переменную для фиата со знаком меньше

2024-05-16 03:21 UTC, megakoko commented on Tangem/App/Utilities/BalanceFormatter/BalanceFormattingOptions.swift
> +    static func defaultFiatFormattingOptions(formatEpsilonAsLowestRepresentableValue: Bool = false) -> BalanceFormattingOptions {
Имя этой переменной получается слишком длинное, что-то типа `defaultFiatFormattingOptionsWithEpsilonAsLowestRepresentableValue`

2024-05-16 08:30 UTC, Andoran90 submitted a review, later dismissed
стремные названия получились, пока нет идеи как лучше это все переименовать. Что-то типа: `useLowestRepresentableValue` звучит не до конца однозначно

2024-05-16 16:14 UTC, tureck1y commented on Tangem/App/Utilities/BalanceFormatter/BalanceFormattingOptions.swift
> +    static func defaultFiatFormattingOptions(formatEpsilonAsLowestRepresentableValue: Bool = false) -> BalanceFormattingOptions {
можно сделать покороче и написать коммент, опять время тратим впустую

2024-05-17 04:13 UTC, megakoko commented on Tangem/App/Utilities/BalanceFormatter/BalanceFormattingOptions.swift
> +    static func defaultFiatFormattingOptions(formatEpsilonAsLowestRepresentableValue: Bool = false) -> BalanceFormattingOptions {
Откатил до предыдущего аппрува

2024-05-17 05:38 UTC, Andoran90 approved these changes

2024-05-17 10:49 UTC, tureck1y approved these changes

2024-05-17 10:49 UTC, merged