Bugfix/ios 6054 make send tx error interface
tangem/tangem-app-ios-old pull request #3288
Opened 2024-05-16 12:59 UTC by skibinalexander

Смежный МР для bsdk.

Пока драфт, потому что не влили BSDK. Изменения ломающие поэтому подготовил сразу

https://github.com/tangem/blockchain-sdk-swift/pull/671

2024-05-16 12:59 UTC, skibinalexander commented on TangemApp.xcworkspace/xcshareddata/swiftpm/Package.resolved
Вижу откачу, как будет тег

2024-05-16 12:59 UTC, skibinalexander commented on Podfile
Откачу как будет тег

2024-05-16 16:03 UTC, tureck1y requested changes

2024-05-16 16:03 UTC, tureck1y commented on Tangem/App/Email/DataCollectors.swift
> +        if let exceptionHost = lastError?.lastRetryHost {
давай под один if let с txHex загоним, будет чище

2024-05-16 16:03 UTC, tureck1y commented on Tangem/App/Email/EmailType.swift
> +        case execptionWalletManagerHost = "Exception Host"
typo "execption".

2024-05-16 16:03 UTC, tureck1y commented on Tangem/App/ViewModels/WalletModel/WalletModel.swift
> +                .eraseSendError()
А если mapSendError(tx: hash.hexString) писать в конце, все равно придется eraseSendError() вызывать?

2024-05-20 06:17 UTC, skibinalexander commented on Tangem/App/Email/EmailType.swift
> +        case execptionWalletManagerHost = "Exception Host"
Поправлю :(

2024-05-20 06:19 UTC, skibinalexander commented on Tangem/App/ViewModels/WalletModel/WalletModel.swift
> +                .eraseSendError()
Да, проблема как раз в том mapSendError(tx: hash.hexString) кидает any Error, так получается потому что в менеджерах надо кидать из цепочек тип Error, иначе совсем глубоко лезут изменения, смотрел с Андрюхами разные варианты, но это выходит как оптимальный, вернуть Error на мапе, и перетереть в конце его на SendTxError

2024-05-20 06:20 UTC, skibinalexander commented
Конфликты и проблемы с тестами вижу, обновлю когда будет тег в bsdk

2024-05-20 12:14 UTC, skibinalexander commented
Пример коллектора

Optional("Session ID: 4D5D0FEE-4471-4AEE-8FD9-830E1326E9CE\n\nCard ID: AC03000000148218\nFirmware version: 4.52r\nLinked cards count: 0\nHas seed phrase: false\nSigned hashes: secp256k1 - 144\nSigned hashes: ed25519 - 114\nSigned hashes: bls12381_G2_AUG - 53\nUserWalletId: 279D0107FB86D77B520B6D2A9AAFEC80158C4D92BA13CBD86FC0A2F06BCDDB36\n--------\nBlockchain: Polygon\nHost: polygon-rpc.com\nError: URLSessionTask failed with error: The Internet connection appears to be offline.\nDerivation path: m/44\'/60\'/0\'/0/0\n--------\nSource address: 0x45682185B571ACE12184AcdDc21Bf2da14B1A759\nDestination address: 0xD454F7a8C81454CfDf0C852550F30aA183cA63d4\nAmount: 0,0005 MATIC\nFee: 0,000756000003297 MATIC\nIs fee included: false\nException Host: rpc-mainnet.matic.quiknode.pro\nTransaction HEX: 0xf86d01850861c4689d82520894d454f7a8c81454cfdf0c852550f30aa183ca63d48701c6bf5263400080820135a050359993010d99ba135e4f6b1e65b036e4222b1213d8f89bc6c893c3f17e6f89a06b35e84213d1049562722eebd17845dd568263bd008602bd9ee4ca21d7bce0f2\n\nPhone model: iPhone XR\nOS version: iOS 17.4.1\nApp version: 1.0 (1)\n")

2024-05-20 14:57 UTC, tureck1y approved these changes, later dismissed

2024-05-21 06:10 UTC, skibinalexander commented
@tureck1y ничего не подливал, были конфликты, поправил

2024-05-21 09:05 UTC, Balashov152 approved these changes

2024-05-21 10:29 UTC, tureck1y approved these changes

2024-05-21 10:45 UTC, merged