IOS-6566 Wallet settings
tangem/tangem-app-ios-old pull request #3310
Opened 2024-05-21 10:42 UTC by Balashov152

![IMG_4216](https://github.com/tangem/tangem-app-ios/assets/25799680/86a669a5-55a3-437c-ad04-13b2c278432d)
![IMG_4217](https://github.com/tangem/tangem-app-ios/assets/25799680/f57e0ad2-74cc-44f8-92f8-cfc0a1db4ab5)
![IMG_4218](https://github.com/tangem/tangem-app-ios/assets/25799680/610b229b-8893-46ad-9065-c1d83e6dc7e0)
![IMG_4219](https://github.com/tangem/tangem-app-ios/assets/25799680/68333e4f-8f2a-4365-8446-970d30ea52e8)
![IMG_4220](https://github.com/tangem/tangem-app-ios/assets/25799680/b69e2f59-e25a-4325-a8c0-4e195bc2de33)
![IMG_4221](https://github.com/tangem/tangem-app-ios/assets/25799680/7a3d87f8-8b8c-4041-b54b-582b0afb2306)
![IMG_4222](https://github.com/tangem/tangem-app-ios/assets/25799680/3eb3d930-9d19-4f80-8f48-65eab525ab67)

2024-05-21 10:42 UTC, Balashov152 commented on Tangem/Common/Extensions/ScrollView+.swift
> +                }
раньше на iOS 15 вообще не было скрытия

2024-05-21 10:43 UTC, Balashov152 commented on Tangem/Common/Extensions/ScrollView+.swift
> +            case .interactively:
`interactively` не прыгает на сеттингах, в других местах оставил так же, что бы не сломать

2024-05-21 10:43 UTC, Balashov152 commented on Tangem/Common/UI/DefaultListViews/DefaultRowView/DefaultRowViewModel.swift
> +class DefaultRowViewModel: ObservableObject, Identifiable {
с `ObservableObject` действительно более правильно, обновил в местах где были костыли для этого

2024-05-21 10:44 UTC, Balashov152 commented on Tangem/Modules/AppSettings/AppSettingsViewModel.swift
> +                viewModel.updateThemeSettingsViewModel()
Больше не нужно пересоздавать ячейки

2024-05-21 10:44 UTC, Balashov152 commented on Tangem/Modules/CardSettings/CardSettingsScanUtil/CardSettingsScanUtil.swift
> +//  CardSettingsScanUtil.swift
По сути удалил `ScanCardSettingsViewModel`
добавил `CardSettingsScanUtil` для логи скана карты перед настройками

Экрана больше не будет

2024-05-21 10:45 UTC, Balashov152 commented on Tangem/Modules/Details/DetailsCoordinator.swift
> +    @Published var appSettingsCoordinator: AppSettingsCoordinator?
Все методы/проверти во View/ViewModel/Coordinator/CoordinatorView переставил в порядке их отображения на экране

2024-05-21 10:46 UTC, Balashov152 commented on Tangem/Modules/Details/DetailsCoordinator.swift
> -        UIApplication.shared.open(url)
Используется для соц сетей, решил что лучше все таки людей оставлять в приложении

2024-05-21 10:51 UTC, Balashov152 commented on Tangem/Modules/UserWalletSettings/UserWalletSettingsViewModel.swift
> +private extension UserWalletSettingsViewModel {
ниже в основном копи-паста с DetailsViewModel с некоторыми переименованиями

2024-05-21 11:09 UTC, Balashov152 commented
![IMG_4216](https://github.com/tangem/tangem-app-ios/assets/25799680/86a669a5-55a3-437c-ad04-13b2c278432d)
![IMG_4217](https://github.com/tangem/tangem-app-ios/assets/25799680/f57e0ad2-74cc-44f8-92f8-cfc0a1db4ab5)
![IMG_4218](https://github.com/tangem/tangem-app-ios/assets/25799680/610b229b-8893-46ad-9065-c1d83e6dc7e0)
![IMG_4219](https://github.com/tangem/tangem-app-ios/assets/25799680/68333e4f-8f2a-4365-8446-970d30ea52e8)
![IMG_4220](https://github.com/tangem/tangem-app-ios/assets/25799680/b69e2f59-e25a-4325-a8c0-4e195bc2de33)
![IMG_4221](https://github.com/tangem/tangem-app-ios/assets/25799680/7a3d87f8-8b8c-4041-b54b-582b0afb2306)
![IMG_4222](https://github.com/tangem/tangem-app-ios/assets/25799680/3eb3d930-9d19-4f80-8f48-65eab525ab67)

2024-05-22 17:39 UTC, tureck1y commented on Tangem/Modules/CardSettings/CardSettingsScanUtil/CardSettingsScanUtil.swift
> +//  CardSettingsScanUtil.swift
А этот экран точно на дизайне решили убрать, а не просто забыли?

2024-05-22 17:58 UTC, tureck1y commented on Tangem/Modules/Details/DetailsCoordinator.swift
> -        UIApplication.shared.open(url)
а если диплинк на инстаграм например?

2024-05-22 18:01 UTC, tureck1y commented on Tangem/Modules/CardSettings/CardSettingsScanUtil/CardSettingsScanUtil.swift
> +//  CardSettingsScanUtil.swift
Уточнил, забыли...

2024-05-22 18:05 UTC, tureck1y requested changes

2024-05-22 18:05 UTC, tureck1y commented on Tangem/Modules/Details/DetailsViewModel.swift
> -    func setupLegalSectionViewModels() {
кажется потерялось

2024-05-24 09:31 UTC, Balashov152 commented on Tangem/Modules/Details/DetailsViewModel.swift
> -    func setupLegalSectionViewModels() {
не, это теперь в `setupSupportSectionModels()`

2024-05-24 09:33 UTC, Balashov152 commented
Поправил конфликты

2024-05-24 09:33 UTC, Balashov152 commented on Tangem/Modules/Details/DetailsCoordinator.swift
> -        UIApplication.shared.open(url)
хм, тогда не знаю как лучше

2024-05-24 09:33 UTC, Balashov152 commented on Tangem/Modules/CardSettings/CardSettingsScanUtil/CardSettingsScanUtil.swift
> +//  CardSettingsScanUtil.swift
вернул экран ✅

2024-05-24 09:36 UTC, Balashov152 commented on Tangem/Modules/Details/DetailsCoordinator.swift
> -        UIApplication.shared.open(url)
вернул `UIApplication.shared.open` ✅

2024-05-24 13:17 UTC, tureck1y approved these changes, later dismissed

2024-05-27 10:59 UTC, tureck1y approved these changes, later dismissed

2024-05-27 11:14 UTC, tureck1y approved these changes

2024-05-27 11:41 UTC, fedorov-d commented on Tangem/Modules/UserWalletSettings/UserWalletSettingsCoordinator.swift
> +        Analytics.log(.referralScreenOpened)
в остальных навигационных методах не нужен вызов аналитики?

2024-05-27 11:42 UTC, Balashov152 commented on Tangem/Modules/UserWalletSettings/UserWalletSettingsCoordinator.swift
> +        Analytics.log(.referralScreenOpened)
Сохранял старую логику, там не было, если будет нужно, думаю отдельной задачей сделаем

2024-05-27 11:47 UTC, fedorov-d approved these changes

2024-05-27 12:28 UTC, merged