IOS-6928 Rename manage to markets
tangem/tangem-app-ios-old pull request #3317
Opened 2024-05-22 08:22 UTC by skibinalexander

Обсудили с @Andoran90 с переименованием в markets сразу, чтобы избегать конфликтов

2024-05-22 08:27 UTC, Andoran90 approved these changes, later dismissed
остались какие-то ещё вьюхи, но думаю с ними проблем не будет, вроде я у себя смогу свободно поменять названия сущностям.

2024-05-22 08:27 UTC, Andoran90 commented on Tangem/Modules/AddCustomToken/AddCustomTokenCoordinator.swift
> +        let dataSource: MarketsDataSource
хм... вот тут что-то не так, но думаю уже в задаче с добавлением кастомных токенов подтюню

2024-05-22 08:32 UTC, skibinalexander commented on Tangem/Modules/AddCustomToken/AddCustomTokenCoordinator.swift
> +        let dataSource: MarketsDataSource
> хм... вот тут что-то не так, но думаю уже в задаче с добавлением кастомных токенов подтюню

Там нормально, потому что это общая логика в принципе для работы добавления, видимо нужно делать утилиту которая вообще не будет так называться, а будет что-то типо AddTokenDataSource или что-то в этом духе

2024-05-22 08:33 UTC, skibinalexander commented
> остались какие-то ещё вьюхи, но думаю с ними проблем не будет, вроде я у себя смогу свободно поменять названия сущностям.

Остался ManageTokensNetworkSelector, кажется там уже не должно быть конфликтов и проще будет по месту

2024-05-22 09:26 UTC, tureck1y requested changes
Что-то тут все смешалось, давайте сразу норм сделаем нейминг, чтобы не ревьювить кругами. Маркетс - вполне конкретный модуль, которого еще нет. Все остальное - это manage tokens

2024-05-22 09:42 UTC, Andoran90 commented
сейчас неразбериха некоторая получилась из-за того что изначально делали `AddCustomToken` для `ManageTokens`, потом это все взяли и переиграли и теперь у нас нет `ManageTokens`, но есть `Markets`, а кастомные токены привязаны теперь к ещё более старому `LegacyTokenListViewModel`. А из-за того что у нас `ManageTokens` занято, я не могу `LegacyTokenListViewModel`  переименовать в `ManageTokensViewModel`, чем он теперь и будет являться по новым требованиям.

2024-05-22 09:48 UTC, Andoran90 commented
непонятно как изменится интерфейс и к чему он будет относиться, я это в своей задаче хотел сделать

2024-05-22 09:51 UTC, skibinalexander commented
> Что-то тут все смешалось, давайте сразу норм сделаем нейминг, чтобы не ревьювить кругами. Маркетс - вполне конкретный модуль, которого еще нет. Все остальное - это manage tokens

А я же как раз поменял название только экран списка токенов координатора и утилит

2024-05-23 11:37 UTC, Andoran90 approved these changes

2024-05-23 13:57 UTC, tureck1y approved these changes

2024-05-23 14:10 UTC, merged