IOS-6891 NotificationsFactory to work with ValidationError / WithdrawalNotification from BSDK
tangem/tangem-app-ios-old pull request #3319
Opened 2024-05-22 10:07 UTC by Balashov152

Вроде кода должно было стать меньше, а по факту больше(
по сути это просто перенос, в коммите 65cfb30d7c76d4803c22bd23fdb6bf0f5ff71a21 сравнивал текстовки и поведение, все совпало.

Объеденил маппинг `BlockchainSdk.ValidationError` и `BlockchainSdk.WithdrawalNotification` в одном `BlockchainSDKNotificationMapper` что бы не делать одно и тоже в Send/Swap/Stake

2024-05-23 05:58 UTC, Andoran90 requested changes
@megakoko пробегись тоже, пожалуйста, все ли норм в сенде

2024-05-23 05:58 UTC, Andoran90 commented on Tangem/Modules/Send/SendNotifications/SendNotificationManager.swift
> +            return false
```suggestion
            return true
```

2024-05-23 06:00 UTC, megakoko commented
Давайте подождем синка, я там чуток правил уведомления

2024-05-23 09:35 UTC, ba1ashov commented
> Давайте подождем синка, я там чуток правил уведомления

Если ты про reduceTo для депозита то это я взял, а customFee я не трогал, это только validationError

2024-05-23 16:26 UTC, tureck1y submitted a review, later dismissed
Тщательно в ивентах не просматривал. Я бы предложил на будущее, все надстройки над бсдк складывать в одну папку, по аналогии с сдк, независимо от того, к чему они относятся. Чтобы в случае чего это потом уехало в отдельный пекедж

2024-05-27 13:14 UTC, Balashov152 commented on Tangem/Modules/Send/SendNotifications/SendNotificationManager.swift
> +            return false
✅

2024-05-27 13:15 UTC, Balashov152 commented
> Тщательно в ивентах не просматривал. Я бы предложил на будущее, все надстройки над бсдк складывать в одну папку, по аналогии с сдк, независимо от того, к чему они относятся. Чтобы в случае чего это потом уехало в отдельный пекедж

Да, согласен что такой модуль было бы полезно иметь. Что-то правда не знаю в какую папку это отдельно класть, сейчас это и так в папке `BlockchainSDKNotifications`

2024-05-27 15:21 UTC, tureck1y approved these changes

2024-05-28 07:03 UTC, Andoran90 approved these changes

2024-05-28 09:05 UTC, merged