IOS-6610 add a mechanism for automatic indexation of wallets
tangem/tangem-app-ios-old pull request #3322
Opened 2024-05-22 12:44 UTC by megakoko

Прошлый МР: https://github.com/tangem/tangem-app-ios/pull/3204

Утилитка работает в двух режимах — миграция существующих кошельков и предложение нового имени. Пытался совместить в одно, но не получилось. Разделять на две утилиты не хочется.

Тесты с рандомайзером на всякий случай, 10 прогонов. Оба режима

2024-05-23 17:57 UTC, tureck1y requested changes

2024-05-23 17:57 UTC, tureck1y commented on TangemTests/UserWalletNameIndexationTests.swift
> +            ("Wallet 2", /*     -> */ "Wallet 2"),
если уже есть индекс его пропускаем, на дублирование не обращаем внимания? Может обсуждали где-то? в описании задачи не нашел

2024-05-23 17:57 UTC, tureck1y commented on Tangem/App/Services/UserWalletRepository/CommonUserWalletRepository.swift
> +        AppSettings.shared.didMigrateUserWalletNames = true
давай эту штуку вызовем в самом конце на случай краша и весь этот метод целиком унесем в миграцию, в другом комменте написал подробнее

2024-05-23 17:57 UTC, tureck1y commented on Tangem/App/Services/UserWalletNameIndexationHelper/UserWalletNameIndexationHelper.swift
> +    init(mode: Mode, names: [String]) {
Давай сделаем утилиту stateless, без mode. Просто набор методов и немного подрефачим для простоты

публичные методы
- **миграция**
Миграция пусть работает сразу с моделями кошельков, тогда эта логика переедет из репозитория сюда и позже будет удалена.

1) получили словари с занятыми индексами распарсив кошельки
2) пошли в цикле по кошелькам, ищем пустые,
- находим ближайший свободный индекс
- конструируем имя и обновляем у кошелька
- обновляем локальный словарь индексов (может сет заюзать?)
- продолжаем, пока кошельки не кончатся
3) возвращаем новые кошельки, если была миграция. Если не было, возвращаем nil или пустой массив, это хорошая оптимизация

- **поиск нового имени**
1) получили словари с занятыми индексами распарсив кошельки
2) взяли ближайший свободный
3) сконструировали имя и вернули

Приватные
- Парсинг кошельков
- поиск следующего индекса
- конструктор имени

2024-05-23 17:57 UTC, tureck1y commented on Tangem/App/Services/UserWalletNameIndexationHelper/UserWalletNameIndexationHelper.swift
> +    private var indexesByNameTemplate: [String: [Int]] = [:]
indexes -> indices

2024-05-24 12:37 UTC, tureck1y commented on TangemTests/UserWalletNameIndexationTests.swift
> +    func testUserWalletNameIndexation() {
Давай еще пожалуйста тесты упростим, чтобы было в стиле
1) тесты индексации нового кошелька
 - дано имя и пользовательский набор кошельков
 - ожидаемый результат такой-то
 - запустили, сравнили ассертом
2) тесты миграции
- дано: пользовательский массив
- ожидаемый результат
- сравнение

Все на хардкодах, без рандомных числе и тп

2024-05-27 03:53 UTC, megakoko commented on TangemTests/UserWalletNameIndexationTests.swift
> +    func testUserWalletNameIndexation() {
Тесты фактически на хардкодах, там рандом с сидом

2024-05-27 16:00 UTC, tureck1y commented on TangemTests/UserWalletNameIndexationTests.swift
> +    func testUserWalletNameIndexation() {
тесты чем тупее написаны, тем лучше)

2024-05-30 03:34 UTC, megakoko commented on TangemTests/UserWalletNameIndexationTests.swift
> +            ("Wallet 2", /*     -> */ "Wallet 2"),
Показывал Лехе результат миграции, он одобрил

2024-05-30 03:53 UTC, megakoko commented on Tangem/App/Services/UserWalletNameIndexationHelper/UserWalletNameIndexationHelper.swift
> +    private var indexesByNameTemplate: [String: [Int]] = [:]
Что не так с indexes?

2024-05-30 03:53 UTC, megakoko commented on Tangem/App/Services/UserWalletRepository/CommonUserWalletRepository.swift
> +        AppSettings.shared.didMigrateUserWalletNames = true
Перенес

2024-05-30 03:55 UTC, megakoko commented on TangemTests/UserWalletNameIndexationTests.swift
> +    func testUserWalletNameIndexation() {
В этих тестах ничего особо умного нет. Это тоже самое что 10 захардкоженных тесткейсов. Если так сильно режет глаза могу на 10 массивов заменить

2024-05-30 03:58 UTC, megakoko commented on Tangem/App/Services/UserWalletNameIndexationHelper/UserWalletNameIndexationHelper.swift
> +    init(mode: Mode, names: [String]) {
Ради простоты и тестов не хочется передавать сюда модели, поэтому сделал на строках. Передавать массив строк, получать его обратно и задавать имена массиву моделей выглядело ненадежно, поэтому сделал на скалярах

2024-05-30 08:53 UTC, tureck1y commented on TangemTests/UserWalletNameIndexationTests.swift
> +            ("Wallet 2", /*     -> */ "Wallet 2"),
Wallet, Wallet, Wallet2 превратятся в Wallet2, Wallet3, Wallet2 ?

2024-05-30 08:54 UTC, tureck1y commented on Tangem/App/Services/UserWalletNameIndexationHelper/UserWalletNameIndexationHelper.swift
> +    init(mode: Mode, names: [String]) {
это комментарий не к тестам же

2024-05-30 08:57 UTC, tureck1y commented on Tangem/App/Services/UserWalletNameIndexationHelper/UserWalletNameIndexationHelper.swift
> +    private var indexesByNameTemplate: [String: [Int]] = [:]
Чаще используется форма indices, в том числе Apple, это не крит в этой задаче

2024-05-30 08:58 UTC, tureck1y commented on TangemTests/UserWalletNameIndexationTests.swift
> +    func testUserWalletNameIndexation() {
Дело не в режет. Беглого взгляда на тесты недостаточно, чтобы понять что тестируется и какой ожидаемый результат. Не хочется тратить время на ревью еще и тестов

2024-05-30 13:57 UTC, megakoko commented on TangemTests/UserWalletNameIndexationTests.swift
> +            ("Wallet 2", /*     -> */ "Wallet 2"),
Wallet -> Wallet (потому что такого нет)
Wallet -> Wallet 3 (потому что 2 уже есть)
Wallet2 -> Wallet 2 (потому что пользователь задал имя)

В первом куске тестов есть подобное

2024-05-30 13:59 UTC, megakoko commented on Tangem/App/Services/UserWalletNameIndexationHelper/UserWalletNameIndexationHelper.swift
> +    private var indexesByNameTemplate: [String: [Int]] = [:]
Я бы предложил оставить как есть чтобы не переусложнять

2024-05-30 14:52 UTC, megakoko commented on TangemTests/UserWalletNameIndexationTests.swift
> +    func testUserWalletNameIndexation() {
Отрефакторил

2024-05-30 14:52 UTC, megakoko commented on Tangem/App/Services/UserWalletNameIndexationHelper/UserWalletNameIndexationHelper.swift
> +    init(mode: Mode, names: [String]) {
Мой тоже

2024-10-24 11:50 UTC, closed without merging