IOS-6930 split welcome manage tokens
tangem/tangem-app-ios-old pull request #3325
Opened 2024-05-22 14:15 UTC by Andoran90

* Разделил на 2 модели, чтобы упростить код и можно было спокойно без лишних данных использовать поиск токенов на экране Приветствия.
* Вынес отдельно отображение списка

В текущем решении не нравится что `ManageTokensListViewModel` используется опционалом `!`, но пока что решения получше не придумал. Можно, конечно просто разворачивать через `if let` во вьюхах и инициализировать через `func setup(_ loader: ManageTokensListLoader)`, но кажется приходится выбирать между сендвичем с дерьмом или гигантской клизмой... Может есть какие-то у вас предложения?

Собственно основная цель всех этих танцев вокруг `ManageTokensListView`, чтобы была вьюха, которая может отображать просто красивый список токенов, т.к. этот список отображается в разных местах:
1. Экран приветствия, где только показывают
2. Новый экран ManageTokens в настройках - тут поиск не будет находиться в навбаре, а будет отдельно лежать (предварительно, жду ответа от Яна)
3. Экран онбординга - поиск тоже будет лежать не в навбаре, но там изменяемая кнопка снизу (Later или Save)
4. Старый экран управления токенами - лежит в `NavigationView` поиск находится в навбаре

Пока вот так получилось. На видео немного лагает из-за того что во время дебажного режима записывал, 8+ лагает ужасно при тяжелых переходах.

https://github.com/tangem/tangem-app-ios/assets/24321494/9d805769-6593-439e-8c4a-571559fcd0c0

2024-05-23 13:15 UTC, Andoran90 commented
Добавил вынесение общей логики в адаптер, чтобы не плодить задачи схожие по смыслу

https://github.com/tangem/tangem-app-ios/assets/24321494/3077aade-25b1-4f47-ba0e-e3efc4d09771

2024-05-23 18:27 UTC, tureck1y commented on Tangem/Modules/Onboarding/BaseModels/OnboardingViewModel.swift
> -        // TODO: remove
когда понял очень буквально 😂

2024-05-23 18:50 UTC, tureck1y requested changes
- я немного запутался что легаси, а что нет, потому что в папке LegacyTokenList лежит ManageTokenListView, который вроде не легаси. Может разобьем по папкам сразу, чтобы был порядок? 
- мы же забанили unowned везде, кроме легаси экранов)
- я вижу проблему с вложенным ManageTokensListViewModel: ObservableObject, это не работает до сих пор. Там тогда надо уйти от Published. Тогда учитывая weak у loader и сложности с прокидыванием Published(а еще и сайд эффекты, от его использования) смысл в ManageTokensListViewModel теряется, можем еще вместе подумать

2024-05-23 18:50 UTC, tureck1y commented on Tangem/Modules/Welcome/SearchTokens/WelcomeSearchTokensViewModel.swift
> +            .map { viewModel, items -> [LegacyCoinViewModel] in
Видимо еще LegacyCoinViewModel придется повысить до неLegacy (можно отдельно)

2024-05-23 18:50 UTC, tureck1y commented on Tangem/Modules/Welcome/SearchTokens/WelcomeSearchTokensViewModel.swift
> +            .map { viewModel, items -> [LegacyCoinViewModel] in
А может есть смысл setupListDataLoader() и mapToCoinViewModel тоже как-то переиспользовать? Через хелпер какой-нибудь отдельный?

2024-05-23 18:55 UTC, tureck1y commented
В целом с этим разбиением стало сильно сложнее имхо. Может пойти иначе, сделать какие-то общие мелкие вьюшки, В хелперах собраться всякие настройки лоадеров и мапперы, а вью-вью модели для экранов делать плоскими - View/ViewModel, без вложенности
- для велком
- для настроек
- Легаси лист я бы оставил вообще как есть, чтобы не регрессить

2024-05-24 06:00 UTC, Andoran90 commented on Tangem/Modules/Welcome/SearchTokens/WelcomeSearchTokensViewModel.swift
> +            .map { viewModel, items -> [LegacyCoinViewModel] in
я думал вынести маппинг в утилиту, но там будет 2 варианта, которые используются в двух разных местах, как-то пока не звучит будто где-то ещё понадобится переиспользование. Вдобавок для `ManageTokensAdapter` придется прокидывать кучу кложур (билдеров `Binding`), показалось не очень рационально

2024-05-24 06:00 UTC, Andoran90 commented on Tangem/Modules/Welcome/SearchTokens/WelcomeSearchTokensViewModel.swift
> +            .map { viewModel, items -> [LegacyCoinViewModel] in
а на счет `setupListDataLoader()` - тут он переехал в старом формате, можно его переделать без `lazy var` и вместе с вью моделью, а потом просто подписываться на получение списка

Можно было бы в `ListDataLoader` передавать парсер, чтобы убрать эту логику из вью модели и адаптера, но тогда общая утилита по маппингу будет бесполезна.

В общем, пока не видится мне смысл в объединении (вдобавок только разделили вью модель на 2 части))

2024-05-24 06:37 UTC, Andoran90 commented
пока что видится что тут в МРе вьюхи не сильно большие, простые и без дублирования кода.
На счет легаси листа, не хотелось дублировать какую-то логику, но можно откатить и сделать отдельную вьюху и вью модель, закрытые тогглами.
Давай созвонимся и обсудим что можно с этим сделать

2024-05-24 07:10 UTC, skibinalexander commented
Если честно мне тоже показалось немного сложновато, теперь есть Адаптер, где если нам скажут поменять что-то в экранах или как-то видоизменить, мы тронем и поедет во всех точках вызова, потому как я понял настраивается и UI и поведение.

Может как то доработать в сторону, по нашим паттернам, типо конфигов, или внести абстракцию какую-то, где для каждого экрана будет своя настройка UI

По сути это 2 разных флоу, может не стоило бы объединять поведения UI как минимум, @Andoran90 что скажешь?

2024-05-24 07:11 UTC, skibinalexander commented
Лично на мой вкус, плоские списки были приятнее, с переиспользованием UI компонентов по возможности, как Саша выше написал

2024-05-24 07:13 UTC, skibinalexander commented
+ параметры настройки экрана (longHashesSupported: Bool, existingCurves: [EllipticCurve], supportedBlockchains: Set<Blockchain>, userTokensManager: UserTokensManager)

может занести в какую - то утилиту, и через фабрику поднастраивать, где она ходила бы в стораджи, брала нужное, и уже через конфигурацию / утилиту работать в самом экране непосредственно

2024-05-24 07:14 UTC, skibinalexander commented
И если хочется разделить бизнес логику, может быть адаптер поделить на 2 части, 1 сущность логики работала бы с загрузкой списка, вторая часть отвечала бы за добавление / удаление

2024-05-24 07:16 UTC, skibinalexander commented
> Если честно мне тоже показалось немного сложновато, теперь есть Адаптер, где если нам скажут поменять что-то в экранах или как-то видоизменить, мы тронем и поедет во всех точках вызова, потому как я понял настраивается и UI и поведение.
> 
> Может как то доработать в сторону, по нашим паттернам, типо конфигов, или внести абстракцию какую-то, где для каждого экрана будет своя настройка UI
> 
> По сути это 2 разных флоу, может не стоило бы объединять поведения UI как минимум, @Andoran90 что скажешь?

то есть по пробовать пойти в сторону полиморфной структуры, тогда список будет плоским, а настройка будет через бизнес логические сущности, UI собирать из более простых компонентов

2024-05-24 07:35 UTC, Andoran90 commented
> * параметры настройки экрана (longHashesSupported: Bool, existingCurves: [EllipticCurve], supportedBlockchains: Set, userTokensManager: UserTokensManager)
> 
> может занести в какую - то утилиту, и через фабрику поднастраивать, где она ходила бы в стораджи, брала нужное, и уже через конфигурацию / утилиту работать в самом экране непосредственно

я хотел почистить настройки экрана, но они передаются дальше в кастомные токены и все же лучше один раз настроить работу экрана и потом не делать это по новой, т.к. есть шанс ошибки

2024-05-24 07:57 UTC, Andoran90 commented
> Если честно мне тоже показалось немного сложновато, теперь есть Адаптер, где если нам скажут поменять что-то в экранах или как-то видоизменить, мы тронем и поедет во всех точках вызова, потому как я понял настраивается и UI и поведение.
>
> Может как то доработать в сторону, по нашим паттернам, типо конфигов, или внести абстракцию какую-то, где для каждого экрана будет своя настройка UI

@skibinalexander  Собственно адаптер нужен чтобы была одинаковая логика на 3х экранах - онбординг, старый менедж токенс и новый менедж токенс. Т.к. сейчас везде одинаковая логика работы экранов - наоборот надо объединить все, чтобы в каждом месте по отдельности не менять. На счет отвязки адаптера от ячеек - тут сложность в том как эти ячейки работают, они сейчас сделаны через биндинги, которые сложнее делать чем делегат, как мне кажется. За счет этого код получается более связанным. Может стоит передавать в адаптер фабрику биндингов, чтобы каждая вью модель сама внутри себя это создавала, но тогда в 3х местах будет одна и та же логика.

Суть адаптера - сделать единый функционал добавления/удаление токенов для конкретно этого вида управления токенами. Если создать фабрику ячеек, думаю она все время будет выглядеть вот так:
``` swift
func mapToCoinViewModel(coinModel: CoinModel, isSelectedBindingFactory: (TokenItem) -> Binding<Bool>, isCopiedBinding: Binding<Bool>) -> LegacyCoinViewModel {
        let currencyItems = coinModel.items.enumerated().map { index, item in
            LegacyCoinItemViewModel(
                tokenItem: item.tokenItem,
                isReadonly: false,
                isSelected: bindSelection(item.tokenItem),
                isCopied: bindCopy(),
                position: .init(with: index, total: coinModel.items.count)
            )
        }

        return LegacyCoinViewModel(with: coinModel, items: currencyItems)
    }
```

Пока что выглядит как бесполезное усложнение, особенно с учетом что это нигде больше не понадобится. На экране `Add portfolio` не кажется что будет тоже очень полезным. А может и будет, если сделать альтернативный вариант стиля

2024-05-24 14:00 UTC, Andoran90 commented
@tureck1y @skibinalexander запушил изменения последние.
Откатил правки в `LegacyTokenListView` + `LegacyTokenListViewModel`, осталось только переименовывание ячеек и удаление всего что связано было с режимами работы

2024-05-24 17:21 UTC, tureck1y approved these changes

2024-05-24 20:17 UTC, skibinalexander approved these changes

2024-05-25 07:04 UTC, merged