Feature/ios 6823 make new cell markets list
tangem/tangem-app-ios-old pull request #3354
Opened 2024-05-28 11:47 UTC by skibinalexander

В рамках МР:

- Убрал не нужные действия, которых больше не будет
- Для запроса Get general market data for a list of tokens сделал модель MarketTokenModel (CoinModel выглядит избыточной)
- Сделал изменения для UI ячейки
- Расставил TODO: где не удалось выполнить имплементацию, смогу доделать в рамках задач (например charts или подключение ручки получения списки, пока ее нет)
- Переходы пока отсутствуют

2024-05-28 11:47 UTC, skibinalexander commented on Tangem/App/Utilities/DummyComponents/DummyMarketTokenModelFactory.swift
> +    func list() -> [MarketTokenModel] {
Необходимо для preview, была портянка которая мешала навигации, и сложно было разрабатывать

2024-05-28 11:47 UTC, skibinalexander commented on Tangem/Modules/Markets/TokenList/MarketsItemView.swift
> -    private func manageButton(for action: MarketsItemViewModel.Action, with id: String) -> some View {
Больше этого не будет

2024-05-28 11:48 UTC, skibinalexander commented on Tangem/Modules/Markets/TokenList/MarketsItemView.swift
> -                tokenInfo
Небольшой рефакторинг для единообразия

2024-05-28 11:48 UTC, skibinalexander commented on Tangem/Modules/Markets/TokenList/MarketsItemView.swift
> -                Text(viewModel.priceValue)
Полностью скелетоны можно будет проверить после рабочей ручки

2024-05-28 11:48 UTC, skibinalexander commented on Tangem/Modules/Markets/TokenList/MarketsItemView.swift
> -private struct AddButtonView: View {
Больше не нужно

2024-05-28 11:49 UTC, skibinalexander commented on Tangem/Modules/Markets/TokenList/MarketsItemView.swift
> +#Preview {
Небольшой рефакторинг, убрать портянку которая ниже

2024-05-28 11:49 UTC, skibinalexander commented on Tangem/Modules/Markets/TokenList/MarketsViewModel.swift
> -    func updateDerivationBind() {
Больше не будет этой логике на этом экране

2024-05-28 11:49 UTC, skibinalexander commented on Tangem/Modules/Markets/TokenList/MarketsViewModel.swift
> +                tokenViewModels = items.compactMap {
Полностью использовать модель смогу после реализации ручки

2024-05-28 11:50 UTC, skibinalexander commented on Tangem/Modules/Markets/TokenList/MerketsItemViewModel.swift
> -    enum Action {
Больше не будет

2024-05-28 11:50 UTC, skibinalexander commented on Tangem/Modules/Markets/TokenList/MerketsItemViewModel.swift
> +    struct InputData {
Для агрегации данных для ViewModel

2024-05-28 11:51 UTC, skibinalexander commented
![IMG_1038 2](https://github.com/tangem/tangem-app-ios/assets/5384724/bd92d571-371b-443b-8a7c-52ce001a4395)

2024-05-28 11:53 UTC, skibinalexander commented on Tangem/Modules/Markets/TokenList/MarketsViewModel.swift
> -    func updateAlreadyExistTokenUserList() {
Код больше не понадобится

2024-05-28 14:03 UTC, skibinalexander commented on Tangem/App/Utilities/DummyComponents/DummyMarketTokenModelFactory.swift
> +    func list() -> [MarketTokenModel] {
@Andoran90 тут может подскажешь куда лучше переложить, что не смог придумать куда приземлить

2024-05-29 05:35 UTC, Andoran90 commented
> <img alt="" width="300" src="https://private-user-images.githubusercontent.com/5384724/334399176-bd92d571-371b-443b-8a7c-52ce001a4395.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5NjExODcsIm5iZiI6MTcxNjk2MDg4NywicGF0aCI6Ii81Mzg0NzI0LzMzNDM5OTE3Ni1iZDkyZDU3MS0zNzFiLTQ0M2ItOGE3Yy01MmNlMDAxYTQzOTUuUE5HP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjlUMDUzNDQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTJjNjUyM2RkMjkwMzVhNTk3NmY5OTI1ZWM3NmMxNGE5OTUzYjg2YjBiNmE5ODA4OTA3ZmVhOThhZTFhMTU0MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.TsyGlsigh8C_5sP2ElLZPK3h_kN5gEd1mNxeZv8Lvl4">

а почему значения в фиате без символа валюты?

2024-05-29 06:29 UTC, Andoran90 requested changes
Пока что не понятно как именно `MarketsViewModel` и `MarketsItemViewModel` должны работать, но текущая реализация похоже неверная. Нужна пояснительная бригада

2024-05-29 06:29 UTC, Andoran90 commented on Tangem/App/Models/Coins/CoinModel.swift
> +            name: "----------------", symbol: "",
Ну раз уж меняется форматирование, давай уж полностью)
```suggestion
            name: "----------------", 
            symbol: "",
```

2024-05-29 06:29 UTC, Andoran90 commented on Tangem/App/Models/Markets/MarketTokenModel.swift
> +    let marketRaiting: String
```suggestion
    let marketCap: String
    let marketRating: String
```

собственно все то же самое в инициализаторе

2024-05-29 06:29 UTC, Andoran90 commented on Tangem/App/Utilities/DummyComponents/DummyMarketTokenModelFactory.swift
> +    func list() -> [MarketTokenModel] {
надо перекинуть в папку `Preview Content`, он тогда при сборке будет вырезаться и не будет добавлен в билд. Можно его положить в `Stubs`, там есть примеры

2024-05-29 06:29 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenList/MarketsItemView.swift
> -                tokenInfo
хм, как будто неправильный лейаут получается. Сейчас все лежит в одном `HStack`, в котором куча ещё `HStack`, внутри которых `VStack`. Надо проверить всякие крайние кейсы, как будет, если название будет длинным, название и цена будут длинные, капитализация и позиция длинные.
``` swift
HStack {
    HStack {
        VStack { }
    }
   
    HStack {
        VStack { }
    }
}
```

На главной изначально по такой же схеме была сделана верстка, но её переделали в вертикальную для текстовок:
``` swift
HStack {

    VStack {

        HStack { }
      
        HStack { }
    }

} 
```
чтобы верхняя и нижние строки не влияли друг на друга, если длинные текстовки. Возможно тут тоже имеет смысл так сделать, не только из-за длинных значений, но и для увеличенных шрифтов может сыграть роль

И ещё, ты проверял как это все выглядит с увеличенными шрифтами?

2024-05-29 06:29 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenList/MarketsViewModel.swift
> -    func updateDerivationBind() {
🪚🪚🪚
@tureck1y твоё любимое)))

2024-05-29 06:29 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenList/MarketsViewModel.swift
> +                    #warning("Need to replace on GET /v1/market_general/ model MarketTokenModel from response")
если есть номер задачи, добавь, пожалуйста, её сразу тоже сюда

2024-05-29 06:29 UTC, Andoran90 commented on TangemApp.xcworkspace/xcshareddata/swiftpm/Package.resolved
> -        "revision" : "b979e8b52c7ae7f3f39fa0182e738e9e7257eb78",
похоже лишние изменения

2024-05-29 06:29 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenList/MerketsItemViewModel.swift
>          priceValue = priceFormatter.formatFiatBalance(quote.price)
хм, немного непонятно получается. Для этой вью модели есть 2 источника данных:
1. запрос `market_general`, из которого создается эта вьюха
2. репозиторий квот - запрос `quotes`, причем условия использования значения из репозитория странные - `priceValue.isEmpty || priceChangeState == .loading || priceChangeState == .noData`.

Не понимаю зачем 2 запрос вообще нужен, если данные для этой вью модели должны браться из 1 всегда. И на экране маркетсов мы будем дергать все время именно `market_general`, а не квоты. Может я чего-то не понимаю тут, конечно. Не совсем понимаю как должно это все работать и обновляться регулярно. Может тут вообще не нужен класс и достаточно структуры, которая будет быстро пересоздаваться, либо нужен какой-то менеджер этих вью моделей, который предоставит паблишеры для нужных значений (возможно инпут даты или же вообще сырых данных, т.к. это вью модель и она должна подготавливать данные для своей вьюхи)

В общем, пока больше вопросов к этой вью модели, чем ответов...

2024-05-29 06:29 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenList/MerketsItemViewModel.swift
>  extension MarketsItemViewModel {
а ещё у файла неправильное название M_e_rketsItemViewModel -> M_a_rketsItemViewModel

2024-05-29 07:48 UTC, skibinalexander commented on Tangem/Modules/Markets/TokenList/MerketsItemViewModel.swift
>          priceValue = priceFormatter.formatFiatBalance(quote.price)
Да ты правильно написал, думал меньше ломать, но давай сразу тогда сделаю, потому что ручка вроде как отдает все необходимое

"current_price": 4000.18
		  "price_change_percentage": {
		        "24h": 14,
		        "1m": 1,
		        "1y": 16,
		      }

2024-05-29 07:49 UTC, skibinalexander commented
@Andoran90 все посмотрел, давай сразу сломаю и переделаю на нормальный запрос

2024-05-31 13:09 UTC, skibinalexander commented on Tangem/App/Models/Markets/MarketsTokenModel.swift
> +    let priceChangePercentage: [MarketsPriceIntervalType: Decimal]
Нужно для того чтобы не перегонять данные из одного типа в другой

2024-05-31 13:09 UTC, skibinalexander commented on Tangem/Modules/Markets/TokenList/MarketsItemView.swift
> -                tokenInfo
Поправил по предложению

2024-05-31 13:09 UTC, skibinalexander commented on Tangem/Modules/Markets/TokenList/MarketsItemView.swift
> -                .skeletonable(isShown: viewModel.isLoading)
Скелетны пока убираю, нет решения как это будет

2024-05-31 13:19 UTC, skibinalexander commented
@tureck1y подожди пожалуйста, пока @Andoran90 посмотрит, мы обсуждали чтобы не стопорится делаем изменения, но предварительно Андрюха посмотрит

2024-05-31 13:21 UTC, skibinalexander commented
@Andoran90 частично сломал, обсудили голосом можно смотреть

2024-06-03 06:37 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenList/MarketsItemView.swift
> +                    IconView(url: viewModel.imageURL, size: iconSize, forceKingfisher: true)
слушай, а иконка на своем месте? иконка же будет привязана к положению первого `VStack` и не будет находиться в центре ячейки.
Кажется её надо вынести в первый `HStack` и положить перед `VStack`

2024-06-03 06:37 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenList/MarketsItemViewModel.swift
> +    var symbol: String
наверное можно сделать все `let`

2024-06-03 14:23 UTC, skibinalexander commented on Tangem/Modules/Markets/TokenList/MarketsItemView.swift
> +                    IconView(url: viewModel.imageURL, size: iconSize, forceKingfisher: true)
поменял 
![IMG_1041](https://github.com/tangem/tangem-app-ios/assets/5384724/a04bf946-1ec2-42a5-ae61-3443203372dc)

Сейчас тоже ок

2024-06-04 05:49 UTC, Andoran90 approved these changes

2024-06-04 08:20 UTC, skibinalexander commented
@tureck1y можно глядеть

2024-06-04 16:12 UTC, tureck1y approved these changes

2024-06-04 16:14 UTC, merged