IOS-6825 Make network layer for markets list
tangem/tangem-app-ios-old pull request #3363
Opened 2024-05-29 18:11 UTC by skibinalexander

В рамках задачи сделал network layer для получения списка токенов. По реализации ничего не особенного кмк. Сделал по аналогии с текущим решением, за исключением только Publisher сделал на Async / Await показало более чистым подходом

2024-05-30 08:05 UTC, Andoran90 requested changes

2024-05-30 08:05 UTC, Andoran90 commented on Tangem/App/Services/TangemApiService/CommonTangemApiService.swift
> +    }
этого не должно быть тут.
Замени, пожалуйста, на `InfoDictionaryUtils`

2024-05-30 08:05 UTC, Andoran90 commented on Tangem/App/Services/TangemApiService/TangemApiTarget.swift
> +    init(type: TargetType, authData: AuthData?, appVersion: String? = nil) {
там ещё платформу надо вроде как отправлять, давай её тоже сразу добавим для всех запросов на бэк

2024-05-30 08:05 UTC, Andoran90 commented on Tangem/Modules/Markets/Providers/MarketsListDataProvider.swift
> +        runTask(in: self) { provider in
думаю это (`runTask`) можно вынести в `fetch`, а `loadItems` сделать `async throws`

2024-05-30 08:05 UTC, Andoran90 commented on Tangem/Modules/Markets/Providers/MarketsListDataProvider.swift
> +    func fetchMore() {
кстати, что в итоге решили с перезагрузкой инфы? как она будет осуществляться? договорились с андроидом?

2024-05-30 08:05 UTC, Andoran90 commented on Tangem/Preview Content/Fakes/FakeTangemApiService.swift
> +        throw "Not implemented"
сюда можно вставить парсинг json файла, который лежит в `Preview content`, чтобы когда запускаешь превьюху она не дергала бэк, а просто парсила файлик, можешь тут чекнуть:
https://github.com/tangem/tangem-app-ios/pull/3355/files#diff-482749e3cbddc7a0a1fd7188fced5d8ecdb2b5c177a9b7a8c6cd38c3a73684be

2024-05-30 09:08 UTC, skibinalexander commented on Tangem/App/Services/TangemApiService/TangemApiTarget.swift
> +    init(type: TargetType, authData: AuthData?, appVersion: String? = nil) {
> там ещё платформу надо вроде как отправлять, давай её тоже сразу добавим для всех запросов на бэк

Ну сделано по спеке

<img width="738" alt="Снимок экрана 2024-05-30 в 12 08 15" src="https://github.com/tangem/tangem-app-ios/assets/5384724/95030231-b291-4d88-9b7b-5fc96b2e2438">

2024-05-30 09:09 UTC, skibinalexander commented on Tangem/Modules/Markets/Providers/MarketsListDataProvider.swift
> +    func fetchMore() {
> кстати, что в итоге решили с перезагрузкой инфы? как она будет осуществляться? договорились с андроидом?

Пока не понимаю с чем решить, делал по документашке, что-то пока не понятно

2024-05-30 09:09 UTC, skibinalexander commented on Tangem/Preview Content/Fakes/FakeTangemApiService.swift
> +        throw "Not implemented"
> сюда можно вставить парсинг json файла, который лежит в `Preview content`, чтобы когда запускаешь превьюху она не дергала бэк, а просто парсила файлик, можешь тут чекнуть: https://github.com/tangem/tangem-app-ios/pull/3355/files#diff-482749e3cbddc7a0a1fd7188fced5d8ecdb2b5c177a9b7a8c6cd38c3a73684be

Контракты меняются на лету, ручек нет, завел задачу, когда будет утверждено json добавлю

2024-05-30 09:09 UTC, skibinalexander commented on Tangem/App/Services/TangemApiService/CommonTangemApiService.swift
> +    }
> этого не должно быть тут. Замени, пожалуйста, на `InfoDictionaryUtils`

Тут приду уточню

2024-05-30 10:58 UTC, skibinalexander commented on Tangem/Modules/Markets/Providers/MarketsListDataProvider.swift
> +    func fetchMore() {
Обсудили подождем финализации контрактов

2024-05-30 10:59 UTC, skibinalexander commented on Tangem/Preview Content/Fakes/FakeTangemApiService.swift
> +        throw "Not implemented"
Поменял под твой вид, подожду ручку вот вот если все ок закину Моки

2024-05-30 13:46 UTC, tureck1y commented on Tangem/App/Services/TangemApiService/TangemApiTarget.swift
> +    init(type: TargetType, authData: AuthData?) {
а зачем конструктор прописывать явно?

2024-05-30 13:46 UTC, tureck1y commented on Tangem/App/Services/TangemApiService/TangemApiTarget.swift
> +        } ?? [:]
Давай плиз чуть чуть упростим:
- объявили headers
- добавили authData
- добавили версию

p.s может с merging будет компактнее

2024-05-30 13:46 UTC, tureck1y commented on Tangem/App/Models/Markets/MarketDTO.swift
> +enum MarketDTO {
Предлагаю везде юзать Markets, а не Market. Что думаете @Andoran90 @skibinalexander ?

2024-05-30 13:46 UTC, tureck1y commented on Tangem/Modules/Markets/Providers/MarketsListDataProvider.swift
> +    @Injected(\.tangemApiService) var tangemApiService: TangemApiService
private

2024-05-30 13:46 UTC, tureck1y commented on Tangem/Modules/Markets/Providers/MarketsListDataProvider.swift
> +                AppLog.shared.debug("\(String(describing: self)) loaded market list tokens with count = \(tokens.count)")
а тут захват не надо прописать?

2024-05-30 13:46 UTC, tureck1y commented on Tangem/Modules/Markets/Providers/MarketsListDataProvider.swift
> +    func fetchMore() {
Обсуждалось переделать загрузку. Сейчас подгружаются ячейки по мере видимости крутилки, а хочется подгружать по количеству проскроленых, тут учтено?

2024-05-30 14:08 UTC, Andoran90 commented on Tangem/App/Models/Markets/MarketDTO.swift
> +enum MarketDTO {
проглядел этот момент, да, мы договаривались на `Markets`

2024-05-30 14:37 UTC, skibinalexander commented on Tangem/App/Models/Markets/MarketDTO.swift
> +enum MarketDTO {
Да понял, специально делал по спеке, а модули Markets, давайте одинаково сделаю

2024-05-30 14:37 UTC, skibinalexander commented on Tangem/App/Models/Markets/MarketDTO.swift
> +enum MarketDTO {
> Да понял, специально делал по спеке, а модули Markets, давайте одинаково сделаю

В спеке просто Market

2024-05-30 14:37 UTC, skibinalexander commented on Tangem/Modules/Markets/Providers/MarketsListDataProvider.swift
> +                AppLog.shared.debug("\(String(describing: self)) loaded market list tokens with count = \(tokens.count)")
> а тут захват не надо прописать?

Да, лучше сделаю, копипастой просмотрел

2024-05-30 14:41 UTC, skibinalexander commented
`Обсуждалось переделать загрузку. Сейчас подгружаются ячейки по мере видимости крутилки, а хочется подгружать по количеству проскроленых, тут учтено?`

@tureck1y Сань по этому поводу, тут еще утвердимся, но кажется пока это не влияет. Кто будет автором крутилка или скрол не важно. + подъедет бек, еще отлалиться надо, поэтому решили с мистером Соном посмотреть чуть дальше. 

Помню что пожелание было делать готовыми кусками, но так пока не выходит, бек ждем, и декомпозировать как - то надо

2024-05-30 14:42 UTC, skibinalexander commented
@tureck1y @Andoran90 я комменты посмотрел, как поправлю переспрошу ревью как готово будет

2024-05-30 14:43 UTC, skibinalexander commented on Tangem/App/Services/TangemApiService/TangemApiTarget.swift
> +    init(type: TargetType, authData: AuthData?) {
> а зачем конструктор прописывать явно?

Рудимент вариации, когда версию приложения передавал в конструкторе, решили с @Andoran90 по месту оставить. Уберу

2024-05-30 18:32 UTC, skibinalexander commented on Tangem/App/Services/TangemApiService/TangemApiTarget.swift
> +        } ?? [:]
Сделал линейно прям, действительно не будем красоваться что умеет swift :)

2024-05-30 18:33 UTC, skibinalexander commented
@tureck1y @Andoran90 готово кажется ничего не забыл

2024-05-30 20:44 UTC, tureck1y approved these changes

2024-05-31 07:05 UTC, Andoran90 approved these changes

2024-05-31 07:26 UTC, merged