Feature/markets/ios 6824 make filter UI components
tangem/tangem-app-ios-old pull request #3377
Opened 2024-06-04 10:48 UTC by skibinalexander

МР для работы фильтра + UI изменения

<img width="541" alt="Снимок экрана 2024-06-04 в 13 45 48" src="https://github.com/tangem/tangem-app-ios/assets/5384724/fac9d529-1bbc-488b-8c99-ce864d700053">

Пока в драфте, ожидаю влитие 6823, позже допишу изменения

2024-06-09 20:34 UTC, skibinalexander commented on Tangem/App/Models/Markets/MarketsListOrderType.swift
> +        // TODO: - Need localize
Локализации пока нет, жду уточнений

2024-06-09 20:35 UTC, skibinalexander commented on Tangem/Common/UI/GroupedScrollView/SelectableGropedSection.swift
> +    private var backgroundColor: Color = Colors.Background.primary
Изменения нужны для корректных отображения цветов ботомшита

2024-06-09 20:36 UTC, skibinalexander commented on Tangem/Modules/Markets/Navigation/MarketsCoordinator.swift
> +    @Published var marketsListOrderBottonSheetViewModel: MarketsListOrderBottonSheetViewModel? = nil
Экран ботом шита настроек

2024-06-09 20:37 UTC, skibinalexander commented on Tangem/Modules/Markets/Providers/MarketsListDataFilterProvider.swift
> +class MarketsListDataFilterProvider {
Обсудили данную сущность вместе с @Andoran90, решили она будет отвечать за владением и предоставление фильтра.

2024-06-09 20:39 UTC, skibinalexander commented on Tangem/Modules/Markets/Providers/MarketsListDataFilterProvider.swift
> +    var onUpdateOrderAction: (() -> Void)?
Без кложуры не обойтись, так как segment control работает Через binding selection а выбор order делается через bottom sheet

2024-06-09 20:40 UTC, skibinalexander commented on Tangem/Modules/Markets/Providers/MarketsListDataFilterProvider.swift
> +class MarketsListDataFilterProvider {
> Обсудили данную сущность вместе с @Andoran90, решили она будет отвечать за владением и предоставление фильтра.

Она же делегат к выбранным значениям фильтра

2024-06-09 20:40 UTC, skibinalexander commented on Tangem/Modules/Markets/Providers/MarketsListDataProvider.swift
> +    func fetch(_ searchText: String, with filter: Filter, generalCoins: Bool = false) {
В отдельном параметре, потому что вызов по кнопке

2024-06-09 20:57 UTC, skibinalexander commented on Tangem/UIComponents/SegmentPickerView/SegmentedPickerView.swift
> +public struct SegmentedPickerView<Option: Hashable & Identifiable, SelectionView: View, SegmentContent: View>: View {
Компонент нужен для того, чтобы Segment показывать по дизайну. Компонент общий пригодится точно

2024-06-09 20:57 UTC, skibinalexander commented on Tangem/UIComponents/SegmentPickerView/SegmentedPickerView.swift
> +public struct SegmentedPickerView<Option: Hashable & Identifiable, SelectionView: View, SegmentContent: View>: View {
Реализация по статье, вроде неплохая

2024-06-09 20:58 UTC, skibinalexander commented on Tangem/Modules/Markets/UIComponents/MarketRaitingHeaderView.swift
> +        .frame(width: 32, height: 16)
Без frame никак было не обойтись, чтобы было по дизайну

2024-06-10 06:01 UTC, skibinalexander commented
![IMG_1042](https://github.com/tangem/tangem-app-ios/assets/5384724/a07ca4ed-243b-433a-bb34-eba4b118d4a4)
![IMG_1043](https://github.com/tangem/tangem-app-ios/assets/5384724/726cdd58-2867-4c00-8426-cb35d6695841)

2024-06-10 06:02 UTC, skibinalexander commented
@tureck1y пусть @Andoran90 сначала глянет

2024-06-11 08:45 UTC, tureck1y submitted a review, later dismissed

2024-06-11 08:45 UTC, tureck1y commented on Tangem/App/Models/Markets/MarketsPriceIntervalType.swift
> +enum MarketsPriceIntervalType: String, CaseIterable, Codable, CustomStringConvertible, Identifiable, Equatable {
Столько протоколов, все нужны? Codable можно на Decodable поменять?

2024-06-11 10:01 UTC, skibinalexander commented on Tangem/App/Models/Markets/MarketsPriceIntervalType.swift
> +enum MarketsPriceIntervalType: String, CaseIterable, Codable, CustomStringConvertible, Identifiable, Equatable {
> Столько протоколов, все нужны? Codable можно на Decodable поменять?

Да выглядит много, но получается так:

string rawValue
case iterable для перечисления, чтобы не писать в массив
Codable посмотрю, вроде как да, предполагал чтобы прям через . передавать в параметры
customStringConertible - чтобы поле description заюзать для локализации и не делать отдельный параметр
Identifiable для published
Equtable нужен был для ForEach если не изменяет память

2024-06-11 10:03 UTC, skibinalexander commented on Tangem/Modules/Markets/UIComponents/MarketRaitingHeaderView.swift
> +                .padding(.vertical, 5)
Пока так, потому что в дизайне не поменяно, как поменяют исправлю

2024-06-17 07:57 UTC, Andoran90 requested changes

2024-06-17 07:57 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenList/MarketsListOrderBottonSheetViewModel.swift
> +}
не обязательно:

думаю лучше переложить в начало файла перед вью моделью или же в другой файл выложить. Как по мне первый вариант норм)

2024-06-17 07:57 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenList/MarketsViewModel.swift
> +        }
мы, кажется, не обсуждали это, но в целом думаю лучше делать не кложуры, а протоколы-делегаты, чтобы код не находился в инициализаторах и всю обвязку проводить не в инициализаторах, а в билдерах, фабриках, координаторах (т.к. координаторы у нас отвечают за настройку сущностей), а от подобного рода кложур постараться отказываться. Т.к. этот код сложнее найти и инициализатор толще. Надо бы это обсудить на командной встрече

2024-06-17 07:57 UTC, Andoran90 commented on Tangem/Modules/Markets/UIComponents/MarketRaitingHeaderView.swift
> +        VStack {
а он нужен тут? наверное можно оставить просто кнопку

2024-06-17 07:57 UTC, Andoran90 commented on Tangem/Modules/Markets/UIComponents/MarketRaitingHeaderView.swift
> +                HStack {
может `spacing` явно прописать?

2024-06-17 07:57 UTC, Andoran90 commented on Tangem/Modules/Markets/UIComponents/MarketRaitingHeaderView.swift
> +        .frame(width: 32, height: 16)
а что с увеличенными шрифтами? тут сразу проблемы будут. 
Думаю лучше обсудить с дизайнерами эту проблему и немного подтюнить дизайн, чтобы потом не переделывать на увеличенные шрифты.

2024-06-17 07:57 UTC, Andoran90 commented on Tangem/Modules/Markets/UIComponents/MarketRaitingHeaderView.swift
> +    }
а зачем функция и дефолтный цвет, если нигде нет альтернативного варианта? давай лучше сразу сделаем рассчитываемым свойством

2024-06-17 07:57 UTC, Andoran90 commented on Tangem/Modules/Markets/UIComponents/MarketRaitingHeaderView.swift
> +    }
```suggestion
    var selectionView: some View {
        Colors.Background.primary
            .clipShape(RoundedRectangle(cornerRadius: containerCornerRadius - 2))
    }
```

2024-06-17 07:57 UTC, Andoran90 commented on Tangem/Modules/Markets/UIComponents/MarketRaitingHeaderViewModel.swift
> +    private weak var delegate: MarketOrderHeaderViewModelDelegate?
вообще, наверное, лучше не делать делегат приватным, т.к. если понадобится настроить его с другой сущностью, то надо будет её в инициализатор передавать.

Это больше концептуальные размышления. Понимаю для чего тут именно так сделано, но в целом кажется лучше бы делегаты и дата сорсы не делать приватными. Что думаешь?

2024-06-17 07:57 UTC, Andoran90 commented on Tangem/Modules/Markets/UIComponents/MarketRaitingHeaderViewModel.swift
> +}
до этого тоже писал, как будто лучше чтобы протоколы делегаты лежали в начале файла, а не в конце. Что скажете?

2024-06-17 07:57 UTC, Andoran90 commented on Tangem/Resources/Localizations/ru.lproj/Localizable.strings
> +"markets_sort_by_title" = "Sort By";
плиз спик рашн...

не дает Леша ответов?..

2024-06-17 07:57 UTC, Andoran90 commented on Tangem/Resources/Localizations/zh-Hant.lproj/Localizable.strings
> +"markets_common_title" = "Market";
не хватает немецкой и французской версий

2024-06-17 07:57 UTC, Andoran90 commented on Tangem/UIComponents/SegmentPickerView/SegmentedPickerView.swift
> +public struct SegmentedPickerView<Option: Hashable & Identifiable, SelectionView: View, SegmentContent: View>: View {
приложи, пожалуйста, ссылочку откуда реализация, чтобы если надо подтюнить могли проще найти откуда пришло

2024-06-17 07:57 UTC, Andoran90 commented on Tangem/UIComponents/SegmentPickerView/SegmentedPickerView.swift
> +public struct SegmentedPickerView<Option: Hashable & Identifiable, SelectionView: View, SegmentContent: View>: View {
а вьюха из сенда не подошла? где выбор валюты с иконкой

2024-06-17 07:57 UTC, Andoran90 commented on Tangem/UIComponents/SegmentPickerView/SegmentedPickerView.swift
> +    @Binding private var selection: Option
а ещё, подскажи, пожалуйста, что с системным не подходит? проблемы с кастомизацией чего-то? или что именно

2024-06-17 08:21 UTC, skibinalexander commented on Tangem/Resources/Localizations/ru.lproj/Localizable.strings
> +"markets_sort_by_title" = "Sort By";
> плиз спик рашн...
> 
> не дает Леша ответов?..

Ну текстовки это наша боль, ждать текстовок это очень долго ...

2024-06-17 08:21 UTC, skibinalexander commented on Tangem/Modules/Markets/UIComponents/MarketRaitingHeaderViewModel.swift
> +}
> до этого тоже писал, как будто лучше чтобы протоколы делегаты лежали в начале файла, а не в конце. Что скажете?

Принято

2024-06-17 08:22 UTC, skibinalexander commented on Tangem/Modules/Markets/UIComponents/MarketRaitingHeaderViewModel.swift
> +    private weak var delegate: MarketOrderHeaderViewModelDelegate?
> вообще, наверное, лучше не делать делегат приватным, т.к. если понадобится настроить его с другой сущностью, то надо будет её в инициализатор передавать.
> 
> Это больше концептуальные размышления. Понимаю для чего тут именно так сделано, но в целом кажется лучше бы делегаты и дата сорсы не делать приватными. Что думаешь?

Ну в целом по идеологии этого паттерна в iOS может и не стоит, давай уберу

2024-06-17 08:24 UTC, skibinalexander commented
Вьюха из сенда оказалось совсем не кастомизированной, чтобы сделать ее общей, есть риск сломать в сенде, я этого делать не стал

2024-06-17 09:31 UTC, Balashov152 commented
А есть вариант сделать что типо `Picker` нативного,  что бы можно было массив индексов, и View под каждый индекс? Я бы в сенде переиспользовал тогда

Что то типо `SegmentControll` можно назвать

2024-06-17 09:38 UTC, skibinalexander commented
> А есть вариант сделать что типо `Picker` нативного, что бы можно было массив индексов, и View под каждый индекс? Я бы в сенде переиспользовал тогда
> 
> Что то типо `SegmentControll` можно назвать

Так это реализация так и предполагает, ее можно и в сенд и куда угодно, и именно поэтому затащил реализацию

2024-06-17 09:39 UTC, skibinalexander commented
> А есть вариант сделать что типо `Picker` нативного, что бы можно было массив индексов, и View под каждый индекс? Я бы в сенде переиспользовал тогда
> 
> Что то типо `SegmentControll` можно назвать

Она хорошо кастомизируется

2024-06-17 21:00 UTC, skibinalexander commented on Tangem/Resources/Localizations/zh-Hant.lproj/Localizable.strings
> +"markets_common_title" = "Market";
Пока что-то с этими текстовками, там бампятся большие изменения из-за внесения переводов, поэтому меняется сильно порядок, отдельной задачей все станет на место да и все

2024-06-17 21:01 UTC, skibinalexander commented on Tangem/UIComponents/SegmentPickerView/SegmentedPickerView.swift
> +    @Binding private var selection: Option
Основная проблема добится такого же дизайна. Дело в том что цвета селектора должны быть наши. Кастомить цвета надо через аппиарнсы синглтона SegmentControl и все равно это будет не по дизайну, потому что от блюров там не уйти

2024-06-17 21:05 UTC, skibinalexander commented on Tangem/Modules/Markets/UIComponents/MarketRaitingHeaderView.swift
> +    }
> а зачем функция и дефолтный цвет, если нигде нет альтернативного варианта? давай лучше сразу сделаем рассчитываемым свойством

Оставлял как пример кастомизации, поменял

2024-06-17 21:09 UTC, skibinalexander commented on Tangem/Modules/Markets/TokenList/MarketsViewModel.swift
> +        }
Надо обсудить, так как не провайдер нужно где - то инициализовароть, городить дополнительную фабрику

2024-06-18 07:15 UTC, skibinalexander commented on Tangem/Modules/Markets/UIComponents/MarketRaitingHeaderView.swift
> +        .frame(width: 32, height: 16)
> а что с увеличенными шрифтами? тут сразу проблемы будут. Думаю лучше обсудить с дизайнерами эту проблему и немного подтюнить дизайн, чтобы потом не переделывать на увеличенные шрифты.

Поставил в настройках самый больший и жирный было ок

2024-06-19 07:59 UTC, Andoran90 reviewed
после рефака осталось несколько ненужных протоколов и немного кода, надо бы подчистить, а в остальном вроде все ок

2024-06-19 07:59 UTC, Andoran90 commented on Tangem/Modules/Markets/Providers/MarketsListDataFilterProvider.swift
> +protocol MarketsListDataFilterProviderDelegate {}
похоже забыл удалить, после рефака

2024-06-19 07:59 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenList/MarketsListOrderBottonSheetViewModel.swift
> +protocol MarketsListOrderBottonSheetViewModelDelegate: AnyObject {
похоже тоже забыл удалить. Напрямую же с провайдером общение идет теперь

2024-06-19 07:59 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenList/MarketsListOrderBottonSheetViewModel.swift
> +    private weak var delegate: MarketsListOrderBottonSheetViewModelDelegate?
и это уже лишнее

2024-06-19 07:59 UTC, Andoran90 commented on Tangem/Resources/Localizations/zh-Hant.lproj/Localizable.strings
> +"markets_common_title" = "Market";
ну ты смотри чтобы не забылось, в любом случае придется проверять тогда руками есть эти текстовки или нет. 
Я бы сейчас добавил ручками эти две

2024-06-19 08:39 UTC, Andoran90 submitted a review, later dismissed

2024-06-19 09:19 UTC, Andoran90 approved these changes

2024-06-19 09:45 UTC, tureck1y approved these changes

2024-06-19 09:54 UTC, merged