IOS-7098 Add `TransactionBuildingFactory` for send flow
tangem/tangem-app-ios-old pull request #3405
Opened 2024-06-10 10:25 UTC by Balashov152

- [ ] #3404 

Добавлена фабрика, часть вынесена в нее, в следующих MR буду дальше менять подход для сборки модулей

2024-06-10 10:27 UTC, Balashov152 commented on Tangem/Modules/Send/Destination/SendDestinationView.swift
> + struct SendDestinationView_Previews: PreviewProvider {
Все preview буду возвращать когда `init` устаканиться при обновлении Input/Output

2024-06-13 13:02 UTC, m3g0byt3 commented on Tangem/App/Factories/TransactionBuildingFactories/TransactionBuildingStepsBuilder.swift
> +                        !ignoredAddresses.contains(walletModel.defaultAddress)
А это условие не ломают логику, которая разрешает отправку себе? 
Пару дней назад видел пулл, где такую отправку включали для определенных сетей

2024-06-13 13:02 UTC, m3g0byt3 commented on Tangem/App/Factories/TransactionBuildingFactories/TransactionBuildingStepsBuilder.swift
> +                    return walletModel.blockchainNetwork.blockchain.networkId == self.walletModel.tokenItem.blockchain.networkId &&
А это корректное сравнение? Как минимум в таком случае testnet == mainnet, не знаю уж насколько это крит. 
И возможно что-то еще

2024-06-13 13:02 UTC, m3g0byt3 commented on Tangem/App/Factories/TransactionBuildingFactories/TransactionBuildingStepsBuilder.swift
> +                    (name: userWalletModel.name, address: walletModel.defaultAddress)
Получается legacy btc address будет отброшен?

2024-06-13 14:56 UTC, Balashov152 commented on Tangem/App/Factories/TransactionBuildingFactories/TransactionBuildingStepsBuilder.swift
> +                        !ignoredAddresses.contains(walletModel.defaultAddress)
хм, вообще переносил это условие **as is** сейчас там есть функция валидации destination, это в след MR есть
Это по факту suggest кошельки, и предлагать самому себе отправить наверно не надо. Запишу в TODO тоже

2024-06-13 14:58 UTC, ba1ashov commented on Tangem/App/Factories/TransactionBuildingFactories/TransactionBuildingStepsBuilder.swift
> +                    return walletModel.blockchainNetwork.blockchain.networkId == self.walletModel.tokenItem.blockchain.networkId &&
Был коммент что это игнорируется, но вроде так изначально и должно быть, не знаю, тоже запишу потом уточнить

2024-06-13 15:00 UTC, Balashov152 commented on Tangem/App/Factories/TransactionBuildingFactories/TransactionBuildingStepsBuilder.swift
> +                    (name: userWalletModel.name, address: walletModel.defaultAddress)
ага, опять же это адреса которые мы "предлагаем", по этому "легаси" нет смысла предлагать )

2024-06-17 17:50 UTC, tureck1y approved these changes, later dismissed

2024-06-17 17:50 UTC, tureck1y commented on Tangem/App/Factories/SendFactories/SendModulesStepsBuilder.swift
> +struct SendModulesStepsBuilder {
Вроде тут билдится все что угодно, но не шаги) Если сюда переедут шаги, а эти метода станут приватными, то ок наверное. Ничего не предлагаю сейчас менять

2024-06-17 17:50 UTC, tureck1y commented on Tangem/Modules/Send/SendCoordinator.swift
> -    @Injected(\.quotesRepository) private var quotesRepository: TokenQuotesRepository
❤️

2024-06-17 18:02 UTC, Balashov152 commented on Tangem/App/Factories/SendFactories/SendModulesStepsBuilder.swift
> +struct SendModulesStepsBuilder {
Ну да, тут получается что всякие статичные штуки делаются, я решил что неймингом в последнем MR все поправлю

2024-06-18 08:34 UTC, Andoran90 requested changes
немного порядок надо навести в фабрике

2024-06-18 08:34 UTC, Andoran90 commented on Tangem/App/Factories/SendFactories/SendModulesFactory.swift
> +    }
чет все вперемежку получилось. свойства после функций, последней лежит не приватная функция вообще. Если есть желание логически разделить на блоки, давай тогда в `extension` выносить, а внутри пусть сохраняется порядок, чтобы не надо было слоняться по всему файлу и искать что куда затесалось

2024-06-18 08:34 UTC, Andoran90 commented on Tangem/App/Factories/SendFactories/SendModulesFactory.swift
> +        SendFeeViewModel(
где-то есть `return`, где-то нет в функциях.

2024-06-18 08:34 UTC, Andoran90 commented on Tangem/App/Factories/SendFactories/SendModulesFactory.swift
> +    func makeSendSummarySectionViewModelFactory(walletInfo: SendWalletInfo) -> SendSummarySectionViewModelFactory {
кстати, эту функция наверное тоже должна быть приватной?..

2024-06-18 08:34 UTC, Andoran90 commented on Tangem/App/Factories/SendFactories/SendModulesStepsBuilder.swift
> +        return SendWalletInfo(
ох уж эти инициализаторы... жесть

2024-06-18 10:22 UTC, Balashov152 commented on Tangem/App/Factories/SendFactories/SendModulesFactory.swift
> +    }
поправил,  думаю сделать вообще все через методы может
Пока все что без параметров создается сверху, а методы дальше снизу

2024-06-18 10:22 UTC, Balashov152 commented on Tangem/App/Factories/SendFactories/SendModulesFactory.swift
> +        SendFeeViewModel(
✅

2024-06-18 10:22 UTC, Balashov152 commented on Tangem/App/Factories/SendFactories/SendModulesFactory.swift
> +    func makeSendSummarySectionViewModelFactory(walletInfo: SendWalletInfo) -> SendSummarySectionViewModelFactory {
Добавил `private`

2024-06-18 10:22 UTC, Balashov152 commented on Tangem/App/Factories/SendFactories/SendModulesStepsBuilder.swift
> +        return SendWalletInfo(
Вообще у меня уже 4 MR которые вообще все поменяют)

2024-06-18 12:40 UTC, Andoran90 commented on Tangem/App/Factories/SendFactories/SendModulesStepsBuilder.swift
> +        return SendWalletInfo(
😅 😅 😅

2024-06-18 12:42 UTC, Andoran90 approved these changes

2024-06-18 12:57 UTC, tureck1y approved these changes

2024-06-18 15:32 UTC, merged