IOS-6892 [Send/Staking] Amount step
tangem/tangem-app-ios-old pull request #3426
Opened 2024-06-14 10:40 UTC by Balashov152

- [ ] #3419

2024-06-14 10:43 UTC, Balashov152 commented on Tangem/Modules/Send/Amount/SendAmountView.swift
> +                .frame(width: proxy.size.width / 3)
занимает 1/3 экрана, а не фиксированный размер

2024-06-14 10:45 UTC, Balashov152 commented on Tangem/Modules/Send/Namespace/StakingSummaryViewGeometryEffectNames.swift
> +protocol SendSummaryViewGeometryEffectNames {
Для будущих MR

2024-06-18 15:53 UTC, tureck1y requested changes
Cтало хуже с FiatCrypto. Опять появилось ветвление логики, возможность задавать одновременно и фиат и крипту. Можем созвониться на троих побреинштормить.

2024-06-18 15:53 UTC, tureck1y commented on Tangem/App/Factories/SendFactories/SendModulesFactory.swift
не уверен, что стоит такие штуки добавлять, их тут может стать многовато и засоряют

2024-06-18 15:53 UTC, tureck1y commented on Tangem/Modules/Send/Amount/SendAmountView.swift
> +    }
может откажемся от такого подхода? Нет смысл делать приватными поля, ведь вью же нельзя создать где-то вне контекста и получить доступ к этим полям

2024-06-18 15:53 UTC, tureck1y commented on Tangem/Modules/Send/Amount/SendAmountViewModel.swift
> +        }
Идея адаптера была в том, чтобы не делать ифчиков во вью модели

2024-06-18 16:51 UTC, Balashov152 commented on Tangem/Modules/Send/Amount/SendAmountView.swift
> +    }
Да давайте откажемся, в приницпе все равно)
убрал

2024-06-18 16:54 UTC, Balashov152 commented on Tangem/App/Factories/SendFactories/SendModulesFactory.swift
Я пробовал добавлять, если потом передевать в init сразу TokenItem, а не WalletModel. Ну пока убрал, если нужно будет, можно вернуть будет

2024-06-25 11:40 UTC, Andoran90 commented on Tangem/App/Factories/SendFactories/SendModulesFactory.swift
> +        let initital = SendAmountViewModel.Initital(
может все же `Settings`? непонятно что за `Initial`

2024-06-25 11:40 UTC, Andoran90 commented on Tangem/App/Factories/SendFactories/SendModulesFactory.swift
> +        let initial = SendSummaryViewModel.Initial(tokenItem: walletModel.tokenItem)
то же самое на счет `Settings`

2024-06-25 11:40 UTC, Andoran90 commented on Tangem/App/Factories/SendFactories/SendModulesFactory.swift
> +        let initial = SendFinishViewModel.Initial(tokenItem: walletModel.tokenItem, amount: amount)
и туть

2024-06-25 11:40 UTC, Andoran90 commented on Tangem/App/Factories/SendFactories/SendModulesFactory.swift
> +    func makeSendAmountValidator() -> SendAmountValidator {
забыл приватными сделать? если они ещё где-то понадобятся, надо бы тогда пересортировать, чтобы приватные были в конце

2024-06-25 11:40 UTC, Andoran90 commented on Tangem/Modules/Send/Amount/SendAmountInteractor.swift
> +    private func crypto(fiatValue: Decimal?) -> Decimal? {
может стоит назвать обе функции `convertToCrypto(_:Decimal?)` и `convertToFiat(_:Decimal?)`, чтобы быть более явными?

2024-06-25 11:40 UTC, Andoran90 commented on Tangem/Modules/Send/Amount/SendAmountInteractor.swift
> +    func errorPublisher() -> AnyPublisher<String?, Never> {
давай сделаем его `var errorPublisher: AnyPublisher<String?, Never>` и перенесем его в начало расширения

2024-06-25 11:40 UTC, Andoran90 commented on Tangem/Modules/Send/Amount/SendAmountViewModel.swift
> +    @Published var userWalletName: String
а разве оно может меняться по ходу дела?

2024-06-25 11:40 UTC, Andoran90 commented on Tangem/Modules/Send/Amount/SendAmountViewModel.swift
> +    @Published var tokenIconInfo: TokenIconInfo
это тоже, по идее, не будет меняться. Надо все не изменяемые оставить константами, нет смысла плодить новые `@Published` свойства

2024-06-25 11:40 UTC, Andoran90 commented on Tangem/Modules/Send/Amount/Utils/SendAmount.swift
> +    static let sendAmount = BalanceFormattingOptions(
```suggestion
    static let sendAmountFormattingOptions = BalanceFormattingOptions(
```

2024-06-25 11:47 UTC, Balashov152 commented on Tangem/Modules/Send/Amount/SendAmountInteractor.swift
> +    func errorPublisher() -> AnyPublisher<String?, Never> {
все таки будем как проперти делать ? 
я чет все как методы уже сделал

2024-06-25 11:52 UTC, Balashov152 commented on Tangem/App/Factories/SendFactories/SendModulesFactory.swift
> +        let initital = SendAmountViewModel.Initital(
✅

2024-06-25 11:52 UTC, Balashov152 commented on Tangem/App/Factories/SendFactories/SendModulesFactory.swift
> +        let initial = SendSummaryViewModel.Initial(tokenItem: walletModel.tokenItem)
✅

2024-06-25 11:52 UTC, Balashov152 commented on Tangem/App/Factories/SendFactories/SendModulesFactory.swift
> +        let initial = SendFinishViewModel.Initial(tokenItem: walletModel.tokenItem, amount: amount)
✅

2024-06-25 11:52 UTC, Balashov152 commented on Tangem/App/Factories/SendFactories/SendModulesFactory.swift
> +    func makeSendAmountValidator() -> SendAmountValidator {
✅

2024-06-25 11:52 UTC, Balashov152 commented on Tangem/Modules/Send/Amount/SendAmountInteractor.swift
> +    private func crypto(fiatValue: Decimal?) -> Decimal? {
✅

2024-06-25 11:52 UTC, Balashov152 commented on Tangem/Modules/Send/Amount/SendAmountViewModel.swift
> +    @Published var userWalletName: String
не может, убрал `@Published` ✅

2024-06-25 11:52 UTC, Balashov152 commented on Tangem/Modules/Send/Amount/SendAmountViewModel.swift
> +    @Published var tokenIconInfo: TokenIconInfo
✅

2024-06-25 11:52 UTC, Balashov152 commented on Tangem/Modules/Send/Amount/Utils/SendAmount.swift
> +    static let sendAmount = BalanceFormattingOptions(
✅

2024-06-26 03:26 UTC, Andoran90 approved these changes

2024-06-26 03:26 UTC, Andoran90 commented on Tangem/Modules/Send/Amount/SendAmountInteractor.swift
> +    func errorPublisher() -> AnyPublisher<String?, Never> {
у меня лично ожидание что если функция, то она что-то делает с сущностью, изменяет, генерирует и т.д., а если рассчитываемое свойство - выдает наружу какие-то данные, может быть предварительно их немного оформив

2024-06-27 07:22 UTC, Andoran90 commented on Tangem/Modules/Send/Summary/SendSummaryViewModel.swift
> +    struct Initial {
а ты ж не поменял с `Initial` -> `Settings` O_o

2024-06-27 08:52 UTC, tureck1y approved these changes

2024-06-27 08:52 UTC, tureck1y commented on Tangem/Modules/Send/Summary/SendSummaryViewModel.swift
> +                let formattedAlternativeAmount = amount?.formatAlternative(currencySymbol: viewModel.tokenItem.currencySymbol)
вроде amount же научился сам себя форматировать?

2024-06-27 08:53 UTC, tureck1y commented on Tangem/Modules/Send/Summary/SendSummaryViewModel.swift
> +                let formattedAlternativeAmount = amount?.formatAlternative(currencySymbol: viewModel.tokenItem.currencySymbol)
Только с форматированием вопрос остался

2024-06-27 12:09 UTC, Balashov152 commented on Tangem/Modules/Send/Summary/SendSummaryViewModel.swift
> +    struct Initial {
хм, вроде поиском все делал, ну в шаге с Summary поправлю тогда

2024-06-27 12:10 UTC, ba1ashov commented on Tangem/Modules/Send/Summary/SendSummaryViewModel.swift
> +                let formattedAlternativeAmount = amount?.formatAlternative(currencySymbol: viewModel.tokenItem.currencySymbol)
ну да, он сам себя форматирует, ему только symbol нужен, как так он хранит только Decimal внутри

2024-06-27 12:30 UTC, merged