IOS-7169 Both eth fees
tangem/tangem-app-ios-old pull request #3444
Opened 2024-06-19 13:40 UTC by tureck1y

2024-06-19 14:06 UTC, Andoran90 requested changes
в текстовках не очень норм все)

2024-06-19 14:06 UTC, Andoran90 commented on Tangem/App/Services/EnvironmentProvider/Feature.swift
> -        case .sendV2: return .version("5.10")
может уже не менять тут и просто удалить все разом в этом спринте?

2024-06-19 14:06 UTC, Andoran90 commented on Tangem/App/Services/WalletConnect/WalletConnectEthTransaction.swift
> +    let gasPrice: String?
на самом деле ни разу не натыкался чтобы присылали инфу связанную с газом в принципе...

2024-06-19 14:06 UTC, Andoran90 commented on Tangem/Resources/Localizations/de.lproj/Localizable.strings
> + "send_gas_price_footer" = "This is the cost you are willing to pay for each unit of gas. The higher the gas price, the faster your transaction will be processed.";
не отсортированы строки, кто-то не сделал билд, похоже, после добавления текстовки 😄

2024-06-19 14:06 UTC, Andoran90 commented on Tangem/Resources/Localizations/zh-Hant.lproj/Localizable.strings
> +"send_gas_price" = "Цена газа";
дубли на англ и на рус для обеих текстовок.

Русскую версию не туда добавил, в ру локализацию вообще ничего не попало

2024-06-19 14:22 UTC, tureck1y commented on Tangem/App/Services/EnvironmentProvider/Feature.swift
> -        case .sendV2: return .version("5.10")
Поправил, ну задача в плане по выпилу

2024-06-19 14:23 UTC, tureck1y commented on Tangem/App/Services/WalletConnect/WalletConnectEthTransaction.swift
> +    let gasPrice: String?
Да, это просто возврат того что было

2024-06-19 14:23 UTC, tureck1y commented on Tangem/Resources/Localizations/de.lproj/Localizable.strings
> + "send_gas_price_footer" = "This is the cost you are willing to pay for each unit of gas. The higher the gas price, the faster your transaction will be processed.";
Да вообще делал, странно

2024-06-19 14:23 UTC, tureck1y commented on Tangem/Resources/Localizations/zh-Hant.lproj/Localizable.strings
> +"send_gas_price" = "Цена газа";
Поправил

2024-06-19 14:41 UTC, Andoran90 commented on Tangem/Resources/Localizations/de.lproj/Localizable.strings
> + "send_gas_price_footer" = "This is the cost you are willing to pay for each unit of gas. The higher the gas price, the faster your transaction will be processed.";
Похоже там в начале пробел, поэтому не сортируется

2024-06-19 18:21 UTC, tureck1y commented on Tangem/Resources/Localizations/de.lproj/Localizable.strings
> + "send_gas_price_footer" = "This is the cost you are willing to pay for each unit of gas. The higher the gas price, the faster your transaction will be processed.";
Точно, спасибо, поправил

2024-06-20 05:27 UTC, Andoran90 submitted a review, later dismissed

2024-06-20 09:22 UTC, Balashov152 commented on Tangem/App/Services/ExpressFeeProvider/CommonExpressFeeProvider.swift
> +        let increaseMultiplicator = BigUInt(112) / BigUInt(100)
а здесь какой результат? 
не факт что верно будет как будто

2024-06-20 20:58 UTC, tureck1y commented on Tangem/App/Services/ExpressFeeProvider/CommonExpressFeeProvider.swift
> +        let increaseMultiplicator = BigUInt(112) / BigUInt(100)
Так внутри multiplyingGasLimit будет умножение на это значение

2024-06-24 10:58 UTC, Balashov152 commented on Tangem/App/Services/ExpressFeeProvider/CommonExpressFeeProvider.swift
> +        let increaseMultiplicator = BigUInt(112) / BigUInt(100)
Просто кажется что это не интовое значение, а если оно и норм, то может сразу его задать

ранее смысл умножить и потом делить был в том, что бы флоатинг поинт не использовать

2024-06-24 10:59 UTC, Balashov152 commented on Tangem/App/Services/ExpressFeeProvider/CommonExpressFeeProvider.swift
> +        let increaseMultiplicator = BigUInt(112) / BigUInt(100)
ну да, так не будет увеличиваться( 
![Screenshot 2024-06-24 at 11 59 43](https://github.com/tangem/tangem-app-ios/assets/25799680/2fe1bc35-9be8-43f9-8ba9-0534d78afd7a)
![Screenshot 2024-06-24 at 11 59 43](https://github.com/tangem/tangem-app-ios/assets/25799680/2fe1bc35-9be8-43f9-8ba9-0534d78afd7a)

2024-06-27 19:47 UTC, tureck1y commented on Tangem/App/Services/ExpressFeeProvider/CommonExpressFeeProvider.swift
> +        let increaseMultiplicator = BigUInt(112) / BigUInt(100)
поправил

2024-06-28 11:03 UTC, Andoran90 submitted a review, later dismissed

2024-07-01 10:25 UTC, tureck1y commented
Поднял тэг и починил конфликты

2024-07-01 10:28 UTC, Andoran90 approved these changes

2024-07-01 10:37 UTC, Balashov152 approved these changes

2024-07-01 10:40 UTC, merged