Feature/markets/ios 7166 make charts for tokens list
tangem/tangem-app-ios-old pull request #3455
Opened 2024-06-25 08:00 UTC by skibinalexander

Добавлены изменения для превью графиков токенов.

Сделано в конве текущей реализации маркеты

![IMG_02BD0AB10E61-1](https://github.com/tangem/tangem-app-ios/assets/5384724/5dfc2cff-c71c-4686-bda6-84b60c972554)

2024-06-25 08:01 UTC, skibinalexander commented
Смотреть после #3408

2024-06-25 11:41 UTC, Andoran90 commented
поменяй, пожалуйста, целевую ветку с дева на ту с чего ветвился, не особо понятно что смотреть, а что не смотреть

2024-06-25 12:43 UTC, skibinalexander commented
> поменяй, пожалуйста, целевую ветку с дева на ту с чего ветвился, не особо понятно что смотреть, а что не смотреть

А тут комментик же есть что смотреть после 3408, но сейчас да сделаю

2024-06-25 12:44 UTC, skibinalexander commented
> поменяй, пожалуйста, целевую ветку с дева на ту с чего ветвился, не особо понятно что смотреть, а что не смотреть

Готово

2024-06-25 13:43 UTC, Andoran90 requested changes

2024-06-25 13:43 UTC, Andoran90 commented on Tangem/Modules/Markets/Providers/MarketsListChartsPreviewProvider.swift
> +final class MarketsListChartsPreviewProvider {
Звучит как будто для превью 😅
удивился в начале что лежит не в `Preview Content` папке))

2024-06-25 13:43 UTC, Andoran90 commented on Tangem/Modules/Markets/Providers/MarketsListChartsPreviewProvider.swift
> +            }
такие вещи не хорошо делать на основном потоке - в цикле проходиться по словарю. Давай сделаем мерж за пределами основного потока после получения ответа, а на основном потоке произведем только присваивание нового словаря. Если будет большое количество элементов - подлагивать будет UI

2024-06-25 13:43 UTC, Andoran90 commented on Tangem/Modules/Markets/Providers/MarketsListChartsPreviewProvider.swift
> +            }
`MarketsListDataProvider` тоже стоит проверить и все не связанные с UI операции вынести за пределы `runOnMain`, в целом понятно что не так много элементов будет, но с одного места прилетит задача на основной поток, с другого места и в итоге подвисать будет UI

2024-06-25 13:43 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenList/MarketsViewModel.swift
>              .receive(on: DispatchQueue.main)
в целом тут итак идет переключение на основной поток, поэтому из провайдера можно подумать о том чтобы вообще убрать обновление списка на основном потоке, но тогда надо перепроверить как будет обновляться список, не будет ли слишком много апдейтов лететь через паблишеры. Думаю лучше после получения инфы с бэка, смержить два словаря (ремоут данные и локальные данные), а потом одним действием заменить словарь `items`

2024-06-25 13:43 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenList/MarketsViewModel.swift
> +    }
чет странная логика получается. Мы в начале грузим список токенов, потом начинаем грузить инфу по чартам. Когда инфа по чартам загрузилась - мы ищем вью модель и вставляем туда инфу про чарт...
Думаю правильнее будет если вью модель будет подписываться на изменения списка чартов из провайдера и сама будет находить инфу для себя. Как никак у нас модель это класс и он может сам делать что-то. А тут подход будто это структура, которая ни за что не отвечает, а просто является хранилищем данных и кто-то извне должен её обслуживать и предоставлять ей данные

2024-06-25 13:43 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenList/MarketsViewModel.swift
> +            charts: chartsDoubleConvertedValues
вот тут должен передаваться провайдер чартов, тогда каждая вью модель сама сможет искать инфу для себя в словаре

2024-06-25 16:08 UTC, skibinalexander commented on Tangem/Modules/Markets/TokenList/MarketsViewModel.swift
> +            charts: chartsDoubleConvertedValues
> вот тут должен передаваться провайдер чартов, тогда каждая вью модель сама сможет искать инфу для себя в словаре

Ну давай перенесу логику во вьюшку окей, в целом так и было, хотел чтобы один подход был, но сделаю окей

2024-06-26 16:11 UTC, skibinalexander commented
@Andoran90 вроде как все замечания учел

2024-06-26 16:29 UTC, tureck1y submitted a review, later dismissed
Бегло посмотрел, архитектурно сложно сказать без полной картины

2024-06-26 16:29 UTC, tureck1y commented on Tangem/Modules/Markets/Providers/MarketsListDataProvider.swift
> +            AppLog.shared.debug("\(String(describing: provider)) loaded market list tokens with count = \(response.tokens.count)")
Если это не очень нужная информация, то лучше не добавлять, чтобы не засорять логи

2024-06-26 18:52 UTC, skibinalexander commented on Tangem/Modules/Markets/Providers/MarketsListDataProvider.swift
> +            AppLog.shared.debug("\(String(describing: provider)) loaded market list tokens with count = \(response.tokens.count)")
Да окей, вообще помогает когда с бека мусор приходит

2024-06-27 04:29 UTC, Andoran90 commented on Tangem/Modules/Markets/Providers/MarketsListChartsPreviewProvider.swift
> +            }
Сань, на сколько этот код будет эффективен? Смотри при каждом добавлении нового ключа-значения будет происходить апдейт UI, я писал до этого про мерж словаря в локальном скопе и потом одним движением обновить весь словарь, чтобы во вью модель прилетел один апдейт, а не 20.
я думаю лучше сделать смержить словари, а потом произвести один апдейт
`self.items = newItemsList`

Можешь запустить этот код и глянуть как будет вести себя счетчик
``` swift
class PublishedTestViewModel: ObservableObject {
    @Published var counter: Int = 0

    func launchCounter() {
        Task {
            for i in 1...20000 {
                counter = i
            }
        }
    }
}
struct PublishedTest: View {
    @ObservedObject var viewModel = PublishedTestViewModel()
    var body: some View {
        VStack(spacing: 16) {
            Button(action: viewModel.launchCounter, label: {
                Text("Launch Counter")
                    .foregroundStyle(.green)
            })

            Text("Counter: \(viewModel.counter)")
                .foregroundStyle(.blue)
        }
    }
}

#Preview {
    PublishedTest()
}
```

попробуй, пожалуйста, поставить брейкпоинт в подписке `MarketsItemViewModel`, будет ли там множество апдейтов вызываться, когда загружается 2 и 3 страница. Или задержка именно для фикса этих апдейтов?

2024-06-27 04:29 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenList/MarketsItemViewModel.swift
> +            .delay(for: 0.5, scheduler: DispatchQueue.main)
а зачем вообще эта задержка нужна? 
Если она используется для фильтрации постоянных апдейтов, то `delay` в этом случае не работает, нужен `debounce`, т.к. `delay` все равно публикует все события, а `debounce` только последнее.

2024-06-27 05:53 UTC, skibinalexander commented on Tangem/Modules/Markets/Providers/MarketsListChartsPreviewProvider.swift
> +            }
Блин , сори , я был уверен , что через мап сделал а не через for each, видел и предыдущий комент , просто сконцентрировался , чтобы перенести провайдер во вью модель , исправлю 

Задержку сделал , чтобы графики по глазам не били скелетонами , чтобы переход со скелетона на вьюху графика был более плавный

2024-06-28 10:52 UTC, Andoran90 approved these changes

2024-06-28 12:12 UTC, tureck1y approved these changes

2024-06-28 12:12 UTC, merged