IOS-6526: [KOINOS] APP Integration
tangem/tangem-app-ios-old pull request #3457
Opened 2024-06-25 10:09 UTC by amuraveinik

[IOS-6526](https://tangem.atlassian.net/browse/IOS-6526)

2024-06-25 10:18 UTC, Balashov152 requested changes

2024-06-25 10:18 UTC, Balashov152 commented on Tangem/App/Services/NotificationManagers/BlockchainSDKNotifications/ValidationErrorEvent.swift
> +            return .init(iconType: .image(Assets.attention.image))
Мне кажется для этого тоже можно `Assets.redCircleWarning.image`  использовать, как я понял это же Крит при отправке

2024-06-25 10:18 UTC, Balashov152 commented on Tangem/App/Services/NotificationManagers/SingleTokenNotifications/SingleTokenNotificationManager.swift
> +                    maxMana: "\(amounts[.coin]?.value ?? .zero)"
я бы это через `if` проверил перед добавлением, что бы `?? .zero` не было

2024-06-25 10:18 UTC, Balashov152 commented on Tangem/App/Services/NotificationManagers/ExpressNotifications/ExpressNotificationManager.swift
> +             .invalidMaxAmount: // TODO: [KOINOS] Maybe do something with it
По факту если кнопок и доп логики нет, то и TODO не нужно, просто должно отобразиться тоже самое что и в Send

2024-06-25 10:18 UTC, Balashov152 commented on Tangem/Modules/Send/SendNotifications/SendNotificationEvent.swift
> +    case invalidMaxAmount(validMax: Decimal)
А сюда не нужно добавлять, это все должно быть только в `ValidationErrorEvent.swift` и все

2024-06-25 10:55 UTC, amuraveinik commented on Tangem/App/Services/NotificationManagers/BlockchainSDKNotifications/ValidationErrorEvent.swift
> +            return .init(iconType: .image(Assets.attention.image))
В дизайне желтый значок

2024-06-25 10:55 UTC, amuraveinik commented on Tangem/App/Services/NotificationManagers/BlockchainSDKNotifications/ValidationErrorEvent.swift
> +            return .init(iconType: .image(Assets.attention.image))
Но я согласен что выглядит так как будто должен быть красный

2024-06-25 10:57 UTC, amuraveinik commented on Tangem/App/Services/NotificationManagers/BlockchainSDKNotifications/ValidationErrorEvent.swift
> +            return .init(iconType: .image(Assets.attention.image))
Спросил в слаке https://tangem.slack.com/archives/C072KMWE9AL/p1719313015216559

2024-06-25 11:05 UTC, amuraveinik commented on Tangem/Modules/Send/SendNotifications/SendNotificationEvent.swift
> +    case invalidMaxAmount(validMax: Decimal)
Почему не надо? У нас кастомные нотификации же на экране сенда

<img width="744" alt="image" src="https://github.com/tangem/tangem-app-ios/assets/163782033/857e523a-afe8-4e8c-9eb8-435d3ad7049b">

2024-06-25 11:08 UTC, Balashov152 commented on Tangem/Modules/Send/SendNotifications/SendNotificationEvent.swift
> +    case invalidMaxAmount(validMax: Decimal)
Они должны в `BlockchainSDKNotification` генериться, что бы одинаковые были на send/swap/staking

По факту здесь должен быть `case validationErrorEvent(ValidationErrorEvent)`

2024-06-25 16:37 UTC, amuraveinik commented on Tangem/Modules/Send/SendNotifications/SendNotificationEvent.swift
> +    case invalidMaxAmount(validMax: Decimal)
Это было сложно, но кажется я понял

2024-06-25 16:39 UTC, amuraveinik commented on Tangem/Modules/Send/SendNotifications/SendNotificationEvent.swift
> +    case invalidMaxAmount(validMax: Decimal)
В некоторых кейсах, пока не понял в каких именно, вместо моих кастомных уведомлений появляются какие-то другие, которые предлагают купить ману. По всей видимости надо что-то менять в транзакшн валидаторе в BSDK

![image](https://github.com/tangem/tangem-app-ios/assets/163782033/5489edca-3848-4d4f-8ca1-6f1d92aa605e)

2024-06-25 17:28 UTC, amuraveinik commented on Tangem/App/Services/NotificationManagers/BlockchainSDKNotifications/ValidationErrorEvent.swift
> +            return .init(iconType: .image(Assets.attention.image))
Решили красный значок делать

2024-06-27 12:37 UTC, tureck1y commented
блин, а я только что какой-то другой мр в приложение посмотрел

2024-06-27 12:38 UTC, tureck1y reviewed
Не понял почему два одинаковых мр, но все комменты оттуда валидны и здесь

2024-06-27 14:42 UTC, AlekseiMuraveinik1 commented
> Не понял почему два одинаковых мр, но все комменты оттуда валидны и здесь

Тот был драфт, без нормального названия ветки.
Я перенесу сюда сейчас все комменты которые там были

2024-06-27 14:44 UTC, amuraveinik commented on Tangem/App/ViewModels/WalletModel/WalletModel.swift
> +            )
tokenItem/feeTokenItem нужны ля корректной навигации в нужную walletModel. В случае с Маной, отдельного токена на главной у пользователя не будет и переходить надо в коин, получается что тут доп кейс не нужен, должно быть как в coin

2024-06-27 14:44 UTC, amuraveinik commented on Tangem/App/ViewModels/WalletModel/WalletModel.swift
> +        case .token, .feeResource:
как и здесь, потому что отдельного токена под ману не будет

2024-06-27 14:44 UTC, amuraveinik commented on Tangem/Common/Extensions/Wallet+.swift
> +        case .feeResource(let type):
Тут надо проверить для чего используется этот метод, чтобы решить делать отдельный кейс или нет

2024-06-27 14:45 UTC, amuraveinik commented on Tangem/App/ViewModels/WalletModel/WalletModel.swift
> +            )
@tureck1y Это я сделал чтобы на экране сенда в качестве комиссии была мана а не коин

2024-06-27 17:26 UTC, tureck1y commented on Tangem/App/ViewModels/WalletModel/WalletModel.swift
> +            )
Давай завтра посмотрим тогда, я не очень понял

2024-06-28 11:59 UTC, amuraveinik commented on Tangem/App/ViewModels/WalletModel/WalletModel.swift
> +        case .token, .feeResource:
Конкретно в этом месте положил `.feeResource` рядом с кейсом `.coin`

2024-06-28 12:00 UTC, amuraveinik commented on Tangem/Common/Extensions/Wallet+.swift
> +        case .feeResource(let type):
Тут проверил, проблем никаких не обнаружил. Ниже по коду написал коммент еще

2024-06-28 12:00 UTC, amuraveinik commented on Tangem/App/ViewModels/WalletModel/WalletModel.swift
> +            )
Выше по коду отписал коммент

2024-06-28 18:04 UTC, tureck1y approved these changes, later dismissed

2024-07-01 12:22 UTC, Balashov152 commented on Tangem/App/Services/NotificationManagers/BlockchainSDKNotifications/ValidationErrorEvent.swift
> +    case notEnoughBalance
А у нас уже есть `case insufficientBalance`
Это не подходит? или там отличия есть ?

2024-07-01 12:26 UTC, AlekseiMuraveinik1 commented on Tangem/App/Services/NotificationManagers/BlockchainSDKNotifications/ValidationErrorEvent.swift
> +    case notEnoughBalance
Неа, не подходит. Тут для коиноса текстовка другая и внешний вид тоже. 

Кейс из описания эпика:
Not enough balance
Your balance should be higher than the fee value to make a transfer
Недостаточно cредств
Ваш баланс должен быть выше суммы комиссии для осуществления перевода

2024-07-01 12:31 UTC, Balashov152 commented on Tangem/App/Services/NotificationManagers/BlockchainSDKNotifications/ValidationErrorEvent.swift
> +    case notEnoughBalance
Тогда я бы переименовал что то типо `notEnoughManaBalance` или хз, как-то обозначить это именно для coinos штука )
Как для cardano есть уже, можно прям `notEnoughCoinosBalance` я думаю, что бы просто не спутать в дальнейшем

2024-07-01 12:48 UTC, amuraveinik commented on Tangem/App/Services/NotificationManagers/BlockchainSDKNotifications/ValidationErrorEvent.swift
> +    case notEnoughBalance
Поменял нейминг

2024-07-01 12:58 UTC, Balashov152 approved these changes, later dismissed

2024-07-09 11:57 UTC, tureck1y submitted a review, later dismissed

2024-07-09 13:09 UTC, tureck1y approved these changes

2024-07-09 13:48 UTC, ba1ashov approved these changes

2024-07-09 14:26 UTC, merged