IOS-6136: Push notifications support
tangem/tangem-app-ios-old pull request #3467
Opened 2024-06-28 16:00 UTC by m3g0byt3

[IOS-6136](https://tangem.atlassian.net/browse/IOS-6136)

2024-07-02 02:59 UTC, m3g0byt3 commented on Tangem/Modules/Onboarding/OnboardingInputFactory.swift
> +        )
@tureck1y мне непонятно, где и как юзается этот инпут, какие шаги на его основе строятся? Нужен ли тут шаг с пушами?

2024-07-02 03:00 UTC, m3g0byt3 commented on Tangem/Modules/Onboarding/OnboardingInputFactory.swift
> +            pushNotificationsPermissionManager: nil,
аналогично тут - @tureck1y мне непонятно, где и как юзается этот инпут, какие шаги на его основе строятся? Нужен ли тут шаг с пушами?

2024-07-02 03:00 UTC, m3g0byt3 commented on Tangem/Modules/Onboarding/OnboardingInputFactory.swift
> +            pushNotificationsPermissionManager: nil,
аналогично тут - @tureck1y мне непонятно, где и как юзается этот инпут, какие шаги на его основе строятся? Нужен ли тут шаг с пушами?

2024-07-02 03:02 UTC, m3g0byt3 commented on Tangem/App/Services/PushNotifications/CommonPushNotificationsInteractor.swift
> +final class CommonPushNotificationsInteractor {
Вся логика работы описана в таске https://tangem.atlassian.net/browse/IOS-6135

2024-07-02 03:04 UTC, m3g0byt3 commented on Tangem/Modules/PushNotifications/PushNotificationsPermissionRequestView.swift
> +    let buttonsAxis: Axis
Пока нет ответа от дизайнеров нужно ли горизонтальное размещение кнопок (на макетах они есть, должны ли они быть в реальности - не понятно)

2024-07-02 03:07 UTC, m3g0byt3 commented on Tangem/UIComponents/Onboarding/OnboardingFeatureDescriptionView.swift
> +        return colorScheme == .light ? Colors.Background.secondary : Colors.Text.disabled
Был некорректный цвет подложки буллетов

2024-07-02 03:07 UTC, m3g0byt3 commented on Tangem/UIComponents/Onboarding/OnboardingFeatureDescriptionView.swift
> +struct OnboardingFeatureDescriptionView: View {
Вынес саму вьюху из UserWalletStorageAgreementView.swift

2024-07-02 03:14 UTC, m3g0byt3 commented on Tangem/App/ServicesManager.swift
> +    @Injected(\.pushNotificationsInteractor) private var pushNotificationsInteractor: PushNotificationsInteractor
Не особо хочется держать тут интерактор, но простого способа передать как зависимость я не вижу

2024-07-02 03:14 UTC, m3g0byt3 commented on Tangem/App/Services/UserWalletRepository/CommonUserWalletRepository.swift
> +    @Injected(\.pushNotificationsInteractor) private var pushNotificationsInteractor: PushNotificationsInteractor
Не особо хочется держать тут интерактор, но простого способа передать как зависимость я не вижу

2024-07-02 03:15 UTC, m3g0byt3 commented on Tangem/App/ViewModels/CommonUserWalletModel.swift
> +    @Injected(\.pushNotificationsInteractor) private var pushNotificationsInteractor: PushNotificationsInteractor
Не особо хочется держать тут интерактор, но простого способа передать как зависимость я не вижу

2024-07-02 03:16 UTC, m3g0byt3 commented on Tangem/Modules/PushNotifications/PushNotificationsPermissionRequestView.swift
> +                        .foregroundColor(Colors.Icon.onboarding)
Пришлось добавить новый цвет в палитру с фикс значением в light/dark, существуюшие не подходят

2024-07-02 03:45 UTC, m3g0byt3 commented on Tangem/Modules/UserWalletStorageAggreement/UserWalletStorageAgreementView.swift
> +                FixedSpacer(height: 28.0)
Эквивалентно

2024-07-02 10:01 UTC, tureck1y requested changes

2024-07-02 10:01 UTC, tureck1y commented on Podfile
> -
Давай пожалуйста оставим, нарочно не удалял все следы чата, аналогично и по остальным файлам

2024-07-02 10:01 UTC, tureck1y commented on Tangem/Modules/Onboarding/OnboardingInputFactory.swift
> +            pushNotificationsPermissionManager: nil,
Тут не нужен, это ретвин карт (Используется вместо сброса к заводским для твинов)

2024-07-02 10:01 UTC, tureck1y commented on Tangem/Modules/Onboarding/OnboardingInputFactory.swift
> +            pushNotificationsPermissionManager: nil,
Тут тоже не нужен, это режим восстановления прерванного бэкапа, тут только шаги бэкапа

2024-07-02 10:01 UTC, tureck1y commented on Tangem/Modules/Onboarding/OnboardingInputFactory.swift
> +            pushNotificationsAvailabilityProvider: availabilityProvider
Я бы в билдер шагов передавал примитив (Bool), чтобы проще мокнуть было

2024-07-02 10:01 UTC, tureck1y commented on Tangem/Modules/Onboarding/OnboardingInputFactory.swift
> +        )
Здесь нужен, это уже основной онбординг

2024-07-02 10:01 UTC, tureck1y commented on Tangem/App/ViewModels/CommonUserWalletModel.swift
> +    @Injected(\.pushNotificationsInteractor) private var pushNotificationsInteractor: PushNotificationsInteractor
Да, придется пока так, отрефакторим позже

2024-07-02 10:01 UTC, tureck1y commented on Tangem/App/Services/UserWalletRepository/CommonUserWalletRepository.swift
> +    @Injected(\.pushNotificationsInteractor) private var pushNotificationsInteractor: PushNotificationsInteractor
Да, не хватает фабрики бэкапа, сделаем позже

2024-07-02 10:01 UTC, tureck1y commented on Tangem/Modules/Welcome/WelcomeOnboarding/WelcomeOnboaringStepsBuilder.swift
>  struct WelcomeOnboaringStepsBuilder {
Блин, опечатался(

2024-07-02 10:01 UTC, tureck1y commented on Tangem/Modules/Onboarding/OnboardingStepsBuilders/OnboardingStepsBuilderFactory.swift
> +        pushNotificationsAvailabilityProvider: PushNotificationsAvailabilityProvider
Вот тут получается булки достаточно, тогда и DummyPushNotificationsAvailabilityProvider не понадобится

2024-07-03 23:00 UTC, m3g0byt3 commented on Tangem/Modules/Onboarding/OnboardingInputFactory.swift
> +        )
А ты уверен? 

Если да, тогда мне непонятно что такое `makeOnboardingInput` выше в этом же файле - мне казалось это именно и есть основной онбординг?

Сейчас я отдаю `isPushNotificationsAvailable: true` именно в `makeOnboardingInput` и это вызывает запрос пушей после сканирования карты и запроса биометрии, как и ожидается (но я тестил только на карте, на которой уже есть кошелек)

Не будет такого, что если `isPushNotificationsAvailable: true` будет и в `makeOnboardingInput` и в `makeBackupInput` - то шаг запроса пушей будет добавлен в оба? 
Backup разве не идет после Onboarding?

Или же `makeOnboardingInput` юзается только для онбординга карт, на которых уже есть кошельки, а `makeBackupInput` - только для новых, без кошельков?

2024-07-03 23:01 UTC, m3g0byt3 commented on Podfile
> -
Ревертнул коммит с выпилом

2024-07-03 23:03 UTC, m3g0byt3 commented on Tangem/Modules/Onboarding/OnboardingInputFactory.swift
> +            pushNotificationsAvailabilityProvider: availabilityProvider
Сделал так
Мне казалось просто что тут есть какая-то логика с передачей сущностей, а не флажков (аналогично backupService). А дальше флажки уже вычисляются непосредственно внутри метода при вызове

2024-07-03 23:03 UTC, m3g0byt3 commented on Tangem/Modules/Onboarding/OnboardingStepsBuilders/OnboardingStepsBuilderFactory.swift
> +        pushNotificationsAvailabilityProvider: PushNotificationsAvailabilityProvider
Заменил, выпилил dummy

2024-07-03 23:05 UTC, m3g0byt3 commented on Tangem/Modules/Welcome/WelcomeOnboarding/WelcomeOnboaringStepsBuilder.swift
>  struct WelcomeOnboaringStepsBuilder {
Ну раз ты сам обратил внимание - то поправил эту и еще пару опечаток, которые нашел пока встраивал в онбординг)
Изначально не хотел, чтобы поменьше было чейнджей 

Смотреть можно атомарно в одном коммите, a9c6a4c089861cfaecaa186b32a339ae0bdf639f

2024-07-06 02:20 UTC, m3g0byt3 commented on Tangem/Modules/Welcome/WelcomeOnboarding/WelcomeOnboardingViewModel.swift
> +            // TODO: Andrey Fedorov - Add actual implementation (IOS-7302)
IOS-7302 вливается сразу следом

2024-07-08 08:56 UTC, m3g0byt3 commented
Вынес весь UI в https://github.com/tangem/tangem-app-ios/pull/3489

2024-07-09 11:20 UTC, tureck1y commented on Podfile
> -  # support chat
Тут удаление осталось

2024-07-09 11:20 UTC, tureck1y commented on Podfile
> +  pod 'Firebase/Messaging'
Давай тоже верстю прибьем

2024-07-10 09:19 UTC, m3g0byt3 commented on Podfile
> -  # support chat
Откатил

2024-07-10 09:21 UTC, m3g0byt3 commented on Podfile
> +  pod 'Firebase/Messaging'
Прибил версию

Также апнул весь FCM на 10.29.0 так как до этой версии возможен реджект на ревью из-за кода в FC, а именно в 10.29.0 есть фикс https://github.com/firebase/firebase-ios-sdk/issues/13134

2024-07-10 09:24 UTC, tureck1y submitted a review, later dismissed

2024-07-10 10:41 UTC, Balashov152 submitted a review, later dismissed

2024-07-11 12:22 UTC, m3g0byt3 commented on Tangem/App/Services/EnvironmentProvider/Feature.swift
> +        case .pushNotifications: return .version("5.13")
Обсудили с @tureck1y в личке, релиз планируется в эту версию

2024-07-11 13:54 UTC, Balashov152 approved these changes

2024-07-11 14:58 UTC, tureck1y approved these changes

2024-07-11 15:15 UTC, merged