Feature/markets/ios 7193 make token selection
tangem/tangem-app-ios-old pull request #3495
Opened 2024-07-10 08:27 UTC by skibinalexander

Сделан экран выбора списка токенов для маркетс. По логике вроде бы ничего особенного. По компонентам соответствуют с тем рефаком что был для ManageTokens by Мистер Сон

![Simulator Screenshot - iPhone 15 - 2024-07-10 at 11 26 48](https://github.com/tangem/tangem-app-ios/assets/5384724/b8263164-d232-45d9-9e16-4abfdfe02c9e)
![Simulator Screenshot - iPhone 15 - 2024-07-10 at 11 27 02](https://github.com/tangem/tangem-app-ios/assets/5384724/da156daa-791b-4182-ae35-eaf805170c06)

2024-07-10 10:30 UTC, tureck1y submitted a review, later dismissed

2024-07-10 14:08 UTC, Andoran90 requested changes

2024-07-10 14:08 UTC, Andoran90 commented on Tangem/Modules/Markets/TokensNetworkSelector/MarketsTokensNetworkSelectorItemViewModel.swift
> +        lhs.id == rhs.id
не совсем понимаю зачем это надо, классы же сравниваются по ссылке. Этого не достаточно?

2024-07-10 14:08 UTC, Andoran90 commented on Tangem/Modules/Markets/TokensNetworkSelector/MarketsTokensNetworkSelectorView.swift
> +                        Color.clear.frame(width: 10, height: 58, alignment: .center)
наверное можно заменить просто паддингм у `VStack`

2024-07-10 14:08 UTC, Andoran90 commented on Tangem/Modules/Markets/TokensNetworkSelector/MarketsTokensNetworkSelectorView.swift
> +            .padding(.leading, 7)
ошиблись в дизайне, надо им закинуть, чтобы поменяли на 8
```suggestion
            .padding(.leading, 8)
```

2024-07-10 14:08 UTC, Andoran90 commented on Tangem/Modules/Markets/UIComponents/MarketsGeneratedAddressView.swift
> +                Text(LocalizedStringKey("To generate addresses for selected networks, you need to attach a Tangem card"))
захадкоженный текст, надо его вынести в локалайз

2024-07-10 14:08 UTC, Andoran90 commented on Tangem/Modules/Markets/UIComponents/MarketsGeneratedAddressView.swift
> +        )
посмотри, наверное можно заменить на `.defaultRoundedBackground(with: Colors.Button.disabled)`

2024-07-10 14:08 UTC, Andoran90 commented on Tangem/Resources/Localizations/de.lproj/Localizable.strings
> +"markets_token_details_circulating_supply" = "Circulating supply";
дубли

2024-07-10 14:08 UTC, Andoran90 commented on Tangem/Resources/Localizations/de.lproj/Localizable.strings
> +"markets_token_details_circulating_supply" = "Circulating supply";
тут должна добавиться только 1 текстовка `markets_generate_addresses_notification`

2024-07-10 14:08 UTC, Andoran90 commented on Tangem/Resources/Localizations/de.lproj/Localizable.strings
> +"markets_generate_addresses_notification" = "To generate addresses for selected networks, you need to attach a Tangem card";
забыл добавить её во вьюху

2024-07-10 14:08 UTC, Andoran90 commented on Tangem/Resources/Localizations/zh-Hant.lproj/Localizable.strings
> +"markets_token_details_circulating_supply" = "Circulating supply";
надо во всех языках почистить дублирующиеся текстовки

2024-07-11 10:34 UTC, Andoran90 approved these changes, later dismissed

2024-07-11 10:34 UTC, Andoran90 commented on Tangem/Modules/Markets/TokensNetworkSelector/MarketsTokensNetworkSelectorView.swift
> +                            .padding(58)
я имел ввиду добавить паддинг `VStack` который лежит внутри `ScrollView`, это не сильно отличается от хака с прозрачным цветом))

2024-07-11 10:34 UTC, Andoran90 commented on Tangem/UIComponents/ManageTokensListView/ListItems/ManageTokensItemNetworkSelectorView.swift
> +            isDisabled: false,
может задать дефолтное значение `var isDisabled: Bool = false`?

2024-07-11 12:25 UTC, Andoran90 approved these changes

2024-07-11 17:11 UTC, tureck1y approved these changes

2024-07-11 19:25 UTC, merged