Feature/markets/ios 7088 make portfolio exist tokens
tangem/tangem-app-ios-old pull request #3504
Opened 2024-07-11 14:37 UTC by skibinalexander

Реализация портфолио токенов.

- Особенности сложно выделить. Набор кошельков берется из WalletDataProvider, который работает для всего markets
- Реализация портфолио выполнена в виде контейнера, которая контроль 3 стейте. 

1. Нет мультивалюток, заходим в неподерживаемую валюту должны увидеть no available assets. заходим в поддерживаемую валюту, видим токен добавленный в портфолио, но нет кнопок добавить
2. Есть мультивалютки но нет токенов, большая кнопка добавить портфолио, 
3. Есть мультивалютки, есть токены, отображаем токены и маленькую кнопку добавить токены

@tureck1y пусть сначала Мистер Сон глянет, потом приду к тебе

https://github.com/tangem/tangem-app-ios/assets/5384724/12965fb4-c39f-4923-9518-0c51757fa474

https://github.com/tangem/tangem-app-ios/assets/5384724/1b89c29f-b0b5-4de3-9dbf-818d784178ef

2024-07-11 14:38 UTC, skibinalexander commented on Tangem/App/Services/IconURLBuilder/IconURLBuilder.swift
> +    func tokenIconURL(optionalId: String?, size: TokenURLIconSize = .large) -> URL? {
Нужно для корректного вызова опционала, больно не красиво в имплементации на уровне потребителя

2024-07-11 14:38 UTC, skibinalexander commented on Tangem/Modules/Markets/Providers/MarketsWalletDataSource.swift
> +class MarketsWalletDataProvider {
DataSource не очень вяжется с неймингом концепции Markets

2024-07-11 14:39 UTC, skibinalexander commented on Tangem/Modules/Markets/Providers/MarketsWalletDataSource.swift
> +        let userWalletModels = userWalletRepository.models.filter { !$0.isUserWalletLocked }
Поскольку для портфолио не нужна фильтрация тут убрал, перенес чуть ниже именно для выбора кошелька

2024-07-11 14:39 UTC, skibinalexander commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioContainerView.swift
> +    private var contentView: some View {
ContentView переключение стейтов

2024-07-11 14:40 UTC, skibinalexander commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioContainerViewModel.swift
> +                let viewModels = filteredWalletModels.map { walletModel in
Получаем TokenItem из WalletModel

2024-07-11 14:40 UTC, skibinalexander commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioContainerViewModel.swift
> +        if hasMultiCurrency {
Логика построения состояния компонентов вьюх в контейнере

2024-07-11 14:41 UTC, skibinalexander commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioTokenItemView.swift
> +struct MarketsPortfolioTokenItemView: View {
Модель токена в списке портфолио

2024-07-11 14:41 UTC, skibinalexander commented on Tangem/Modules/Markets/TokenMarketsDetails/TokenMarketsDetailsRoutable.swift
> +    func openTokenSelector(with coinModel: CoinModel, with walletDataProvider: MarketsWalletDataProvider)
Изменения связаны с тем что WalletDataProvider прокидываем как в портфолио так и в токен селектор, чтобы не пересоздавать

2024-07-11 14:41 UTC, skibinalexander commented on Tangem/Modules/Markets/TokensNetworkSelector/MarketsTokensNetworkSelectorViewModel.swift
> +        walletDataProvider.selectedUserWalletModel
Просто переименование

2024-07-11 14:42 UTC, skibinalexander commented on Tangem/Modules/Markets/TokensNetworkSelector/MarketsTokensNetworkSelectorViewModel.swift
> +                guard let userWalletModel = viewModel.walletDataProvider.userWalletModels.first(where: { $0.userWalletId == userWalletId }) else {
Просто переименование

2024-07-11 14:42 UTC, skibinalexander commented on Tangem/Modules/Markets/TokensNetworkSelector/MarketsTokensNetworkSelectorViewModel.swift
> +        if let userTokensManager = walletDataProvider.selectedUserWalletModel?.userTokensManager {
Просто переименование

2024-07-11 14:42 UTC, skibinalexander commented on Tangem/Modules/Markets/TokensNetworkSelector/MarketsTokensNetworkSelectorViewModel.swift
> +        guard let userTokensManager = walletDataProvider.selectedUserWalletModel?.userTokensManager else {
Просто переименование

2024-07-11 14:42 UTC, skibinalexander commented on Tangem/Modules/Markets/TokensNetworkSelector/MarketsTokensNetworkSelectorViewModel.swift
> +            let userWalletModel = walletDataProvider.selectedUserWalletModel,
Просто переименование

2024-07-11 14:42 UTC, skibinalexander commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioContainerViewModel.swift
> +    @Published var isShowTopAddButton: Bool = false
Отдельный паблишед все таки нужно, используется для кнопки добавления в хедере

2024-07-11 17:29 UTC, tureck1y commented on TangemApp.xcworkspace/xcshareddata/swiftpm/Package.resolved
>        "kind" : "remoteSourceControl",
что-то лишнее залетело

2024-07-11 17:29 UTC, tureck1y reviewed
👀

2024-07-12 12:11 UTC, Andoran90 commented
немного конфликтов насыпалось

2024-07-12 13:45 UTC, Andoran90 requested changes

2024-07-12 13:45 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenMarketsDetails/TokenMarketsDetailsView.swift
> +            Group {
а зачем группа? я так понимаю что второй вьюхи тут не будет, поэтому можно паддинг просто приложить к `MarketsPortfolioContainerView`

2024-07-12 13:45 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioContainerView.swift
> +                                .image
не крит: в целом думаю такое можно писать в одну строчку `Assets.plus24.image`, а остальное уже переносить

2024-07-12 13:45 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioContainerView.swift
> +                    .padding(.trailing, 10)
блин, похоже будто косякнули в дизайне...

2024-07-12 13:45 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioContainerView.swift
> +                Text("This asset is not available")
локализацию забыл

2024-07-12 13:45 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioContainerView.swift
> +        .roundedBackground(with: Colors.Background.action, padding: 14, radius: 14)
думаю тут лучше заюзать `.defaultRoundedBackground(with: Colors.Background.action)`, т.к. отступы контента будут отличаться от всех остальных вьюх ниже

2024-07-12 13:45 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioContainerView.swift
> +        VStack {
думаю лучше явно указать отступ между элементами

2024-07-12 13:45 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioTokenItemView.swift
> +    }
а чем не подходит: `TokenIcon`? Думаю её можно тут заюзать

2024-07-12 13:45 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioTokenItemView.swift
> +        }
так, думаю тут неправильный лэйаут и надо не 2 вертикальных сделать, а 2 горизонтальных. Если будет длинное название кошелька и большой баланс - какой-то контент будет рано обрезаться и выглядеть будет странно. Думаю тут надо сделать как на главной в `TokenItemView`

2024-07-12 13:45 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioTokenItemView.swift
> +    }
вроде нигде не используется и можно удалить

2024-07-12 13:45 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioTokenItemViewModel.swift
> +    let balanceValue: String
а почему константы? они же могут грузиться медленно. Добавил токены в портфолио и она начали грузиться. В итоге тут будет неправильная инфа, если медленный инет. Вообще думаю эта модель должна держать внутри `WalletModel` и подписываться на обновления баланса в крипте и фиате, чтобы она могла обновляться.

2024-07-12 14:34 UTC, skibinalexander commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioContainerView.swift
> +                    .padding(.trailing, 10)
Ну я уточнял, Дизы для кнопок такое специально делают, вот кнопочка https://www.figma.com/design/ZJoUO3kZGCcVgOUbCMQcY4/iOS-%E2%80%93-UI?node-id=30603-22027&t=lJIlvQ7zFkKHltBS-4

2024-07-12 14:59 UTC, skibinalexander commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioTokenItemView.swift
> +        }
Поменял

2024-07-12 14:59 UTC, skibinalexander commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioTokenItemView.swift
> +    }
> а чем не подходит: `TokenIcon`? Думаю её можно тут заюзать

Спс, не знал про него, буду знать .....

2024-07-12 14:59 UTC, skibinalexander commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioContainerView.swift
> +                Text("This asset is not available")
> локализацию забыл

Ага спс, была, померил видимо не правильно ...

2024-07-12 16:25 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioTokenItemView.swift
> +}
не, все равно не правильно будет. Надо фиатный баланс перенести в `HStack` к названию, а криповый баланс к названию блокчеина

2024-07-12 16:29 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioTokenItemView.swift
> +    }
```suggestion
    private var tokenInfoView: some View {
        VStack(alignment: .leading, spacing: 4) {
            HStack {
                Text(viewModel.walletName)
                    .lineLimit(1)
                    .style(Fonts.Bold.subheadline, color: Colors.Text.primary1)
                    
                Spacer(minLength: 8) // ну или что-то типа такого отступа
                
                Text(viewModel.fiatBalanceValue)
                    .lineLimit(1)
                    .style(Fonts.Regular.subheadline, color: Colors.Text.primary1)
            }

            HStack {
                Text(viewModel.tokenName)
                    .lineLimit(1)
                    .style(Fonts.Regular.caption1, color: Colors.Text.tertiary)
                    
                 Spacer(minLength: 8) // ну или что-то типа такого отступа
                  
                 Text(viewModel.balanceValue)
                    .truncationMode(.middle)
                    .lineLimit(1)
                    .style(Fonts.Regular.caption1, color: Colors.Text.tertiary)
            }
        }
    }
```

2024-07-12 16:40 UTC, skibinalexander commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioTokenItemView.swift
> +}
> не, все равно не правильно будет. Надо фиатный баланс перенести в `HStack` к названию, а криповый баланс к названию блокчеина

Ага понял проблему

2024-07-12 16:59 UTC, Andoran90 approved these changes

2024-07-12 17:05 UTC, tureck1y approved these changes

2024-07-12 17:12 UTC, merged