Feature/markets/ios 7290 make quick actions for token detail
tangem/tangem-app-ios-old pull request #3515
Opened 2024-07-14 19:03 UTC by skibinalexander

Требуется сделать LongTap actions для токенов портфолио. При этом если портфолио состоит из одного токена, нужно показывать отдельную вьюшку с 3мя действиями.

Сложность была в том, что для экранов Main и TokenDetail жесткая привязка к TokenItemViewModel, который мы не использовали по причине того, что UI разный. При этом настройки и конфигурации требуют как UserWalletModel, так и WalletModel

WIP потому что требуется потестить LongTap, но уже собираюсь показать мистеру Сону, чтобы глянул архитектуру пробросов ивентов, честно сказать как симпатичнее сделать не очень понятно. Там где мог уйти от переиспользования кода сделал утилиты. также сделал фабрику с прицелом что сборка координаторов будет общей видно будет в МР. 

Также добавил локали для необходимых вью

![IMG_1075](https://github.com/user-attachments/assets/0865c404-f6eb-4cab-b9aa-2905a04aa99c)

https://github.com/user-attachments/assets/f7a597fa-e757-42ec-bd64-f4099df0c60d

2024-07-14 19:04 UTC, skibinalexander commented on Tangem/Common/TokenActions/CanStakeActionUtility.swift
> +struct CanStakeActionUtility {
Утилита, чтобы уйти от дублирования кода

2024-07-14 19:04 UTC, skibinalexander commented on Tangem/Common/TokenActions/TokenActionType.swift
> +enum TokenActionType: String {
Нужно было для перебора кейсов .id

2024-07-14 19:05 UTC, skibinalexander commented on Tangem/Modules/Markets/TokenMarketsDetails/Common/TokenMarketsDetailsPortfolioCoodinatorFactory.swift
> +struct TokenMarketsDetailsPortfolioCoodinatorFactory {
Фабрика подготовки координаторов, с прицелом чтобы уйти от дублирования кода в TokenDetailCoordinator

2024-07-14 19:06 UTC, skibinalexander commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/Actions/MarketsPortfolioQuickActionsView.swift
> +struct MarketsPortfolioQuickActionsView: View {
Вьюшка для быстрых действий одного токена

2024-07-14 19:07 UTC, skibinalexander commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioContainerViewModel.swift
> +    func onExternalTapAction(type actionType: TokenActionType) {
Контейнер токенов и вьюха быстрых действий разные вьюшки, объединять смысла нет, и переносить логику выбора токена из необходимости владения WalletModel и UserWalletModel затруднительно, сделал внешний вызов TypeAction

2024-07-14 19:08 UTC, skibinalexander commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioTokenItemViewModel.swift
> +        self.userWalletId = userWalletId
Нужно для поиска токена в нужном кошельке, Потмоу как портфолио строится из множества UserWalletModel

2024-07-14 19:08 UTC, skibinalexander commented on Tangem/Modules/Markets/TokenMarketsDetails/TokenMarketsDetailsViewModel.swift
> -    func onAddToPortfolioTapAction() {
Перестало быть нужным, ивенты пробрасываются в роутере

2024-07-14 19:09 UTC, skibinalexander commented on Tangem/Modules/Markets/TokenMarketsDetails/TokenMarketsDetailsViewModel.swift
> +extension TokenMarketsDetailsViewModel {
Координатор для перехода в TokenSelector должен получить эти сущности, закрыл методом, чтобы не делать public

2024-07-14 21:05 UTC, skibinalexander commented
Визуалку лонг тапа дотяну , смотрю еще

2024-07-16 18:13 UTC, skibinalexander commented
https://github.com/user-attachments/assets/765f8931-5ee1-49f9-9141-8fa6da89e5c0

2024-07-16 18:15 UTC, skibinalexander commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioContainerView.swift
> +            ForEach(indexed: elementItems.indexed()) { itemIndex, itemViewModel in
Такие сложности из - за "красивой" отрисовки long tap context menu

2024-07-16 18:15 UTC, skibinalexander commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioContainerView.swift
> +    struct HeaderCornerRadiusModify: ViewModifier {
Скруглять только верхние границы header

2024-07-16 18:16 UTC, skibinalexander commented on Tangem/Common/UI/AuxiliaryTypes.swift
> +enum RoundedCornersVerticalEdge {
Общая реализация

2024-07-17 08:38 UTC, Andoran90 requested changes

2024-07-17 08:38 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenMarketsDetails/Common/TokenMarketsDetailsPortfolioCoodinatorFactory.swift
> +struct TokenMarketsDetailsPortfolioCoodinatorFactory {
давай сразу поменяем название, чтобы потом не надо было переименовывать:
`MarketsTokenDetailsPortfolioCoordinatorFactory`

2024-07-17 08:38 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenMarketsDetails/Common/TokenMarketsDetailsPortfolioCoodinatorFactory.swift
> +        ExchangeCryptoUtility(
по стилю обсуждали наоборот: в свойствах без ретурна, в функциях с ретурном

2024-07-17 08:38 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenMarketsDetails/Common/TokenMarketsDetailsPortfolioCoodinatorFactory.swift
> +    func makeExchangeCoordinator(
```suggestion
    func makeExpressCoordinator(
```

2024-07-17 08:38 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenMarketsDetails/Common/TokenMarketsDetailsPortfolioCoodinatorFactory.swift
> +            type: .sell(parameters: .init(amount: amountToSend.value, destination: request.targetAddress, tag: request.tag))
а почему тут внутрь `amount` передается `amountToSend.value`? это же получается весь баланс будет передаваться. Надо брать `request.amount`

2024-07-17 08:38 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioContainerRoutable.swift
> +    func showCopyAddressAlert()
а зачем тут алерт? кажется тоста достаточно, а тост можно вызвать из любого места.
Или было требование именно алерт показывать?

2024-07-17 08:38 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioContainerView.swift
>          }
а зачем это условие? есть 2 вьюхи, у которых одинаковый бэкграунд и закругление. Думаю `VStack`, внутри  которого лежат `headerView` и `contentView` должны иметь свой закругленный бэкграунд и `quickActionsView` - тоже

2024-07-17 08:38 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioQuickActionsView.swift
> +        .padding(.vertical, 12)
кажется неправильно выходит, надо в `defaultRoundedBackground` указать что `verticalPadding: 0`, а то слишком большой отступ снизу получается.
В принципе можно убрать и горизонтальный отступ и сделать только закругление и фон, чтобы область нажатия была на всю ширину

2024-07-17 08:38 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioContainerView.swift
> +                    }
слишком много лишнего кода. Думаю можно вот так сократить
```suggestion
                    let cornersConfig: RoundedCornersConfiguration?
                    if isFirstItem {
                        cornersConfig = elementItems.count == 1 ? .all : .topEdge
                    } else {
                        cornersConfig = isLastItem ? .bottomEdge : nil
                    }
                    
                    MarketsPortfolioTokenItemView(
                          viewModel: itemViewModel,
                          cornerRadius: Constants.cornerRadius,
                          roundedCornersVerticalEdge: cornersConfig
                    )
```

2024-07-17 08:38 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioContainerView.swift
> +        .offset(y: -Constants.defaultVerticalOffsetSpacingBetweenContent)
а зачем этот сдвиг?..

2024-07-17 08:38 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioContainerView.swift
> +                .modifier(HeaderCornerRadiusModify())
что-то дофига заморочистая вьюха получается с кучей условий.
```suggestion
                .modifier(HeaderCornerRadiusModifier())
```

2024-07-17 08:38 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioContainerViewModel.swift
> +    @Published var showQuickActions: Bool = false
пока что выглядит так, что можно убрать эту булку и в UI проверить 1 элемент или нет. ну или на крайняк убрать этот паблишер и заменить на свойство, если хочется держать всю логику во вью модели. С другим названием можно будет заюзать внутри `maskFilterSingleTokenAvailableToken`
```suggestion
    var isOneTokenInPortfolio: Bool {
        tokenItemViewModels.count == 1
    }
```

2024-07-17 08:38 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioContainerViewModel.swift
> +    private func maskFilterSingleTokenAvailableToken(actions: [TokenActionType]) -> [TokenActionType] {
очень непонятное название. Давай лучше
```suggestion
    private func filterAvailableTokenActions(_ actions: [TokenActionType]) -> [TokenActionType] {
```

2024-07-17 08:38 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioContainerViewModel.swift
> +        )
где-то я это уже видел)))
В фабрике есть генерация этой утилиты, давай её заюзаем или из фабрики её удалим

2024-07-17 08:38 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioContainerViewModel.swift
> +    }
думаю это лишняя функция, т.к. нигде не переиспользуется, только в соседней функции.

2024-07-17 08:38 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioContainerViewModel.swift
> +            .first(where: { $0.id == tokenItemViewModel.walletModelId }),
что-то жесткая каша получается. Давай это вынесем за пределы `guard`, а в гарде только разворачивание опционалов сделаем. 

Опциональное, но я не вижу особого смысла писать. Какого-то требования к этому нет
``` swift
userWalletModel
  .walletModelsManager
  .walletModels
```

думаю вполне нормально и понятно выглядит:
``` swift
userWalletModel.walletModelsManager.walletModels
    .first...
```

2024-07-17 08:38 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioContainerViewModel.swift
> +            coordinator.showCopyAddressAlert()
продублирую тут коммент:
думаю тут не нужен алерт, а достаточно тоста (ну там: выпьем за любовь, все дела)

2024-07-17 08:38 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioTokenItemView.swift
> +                .renderingMode(.template)
слиплись немного...
```suggestion
            Text(action.title)
            
            action.icon.image
                .renderingMode(.template)
```

я не помню, а `renderingMode` добавляешь чтобы за счет роли `destructive` покрасилась иконка, верно? а то там вроде нигде цвет не задается.

2024-07-17 08:38 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioTokenItemViewModel.swift
> +    }
лишнее, нигде не используется вроде как. Можно удалить, вдобавок дублирует `id`

2024-07-17 08:38 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioTokenItemViewModel.swift
> +        "\(walletModel.tokenItem.currencySymbol) \(walletModel.tokenItem.networkName)"
уточни, пожалуйста, мне кажется что тут какая-то ерунда получается) например если взять BNB будет
`BNB BNB Smart Chain`. В дизайне похоже ерунда какая-то)
В принципе символ валюты указан в криптовом балансе, может этого будет достаточно?.. Правда при длинных названиях он может обрезаться и при увеличенных шрифтах

2024-07-17 08:38 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioTokenItemViewModel.swift
> +    private weak var walletModel: WalletModel!
можно обойтись без `!` и в целом без `weak`, эта вьюха не должна жить дольше чем `WalletModel`

2024-07-17 08:38 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenMarketsDetails/TokenMarketsDetailsCoordinator.swift
> +            )
дошел до этого места)) а зачем нам тут тост?) и почему функция с алертом?) давай прям на месте где копируется адрес - добавим показ тоста. Лишнее усложнение. Собственно и тосты и алерты у нас во вью моделях создаются, а тост сделали таким, чтобы его можно было где угодно вызвать. Старый вариант предусматривал прокидывание во вьюху, теперь этого делать не надо

2024-07-17 08:38 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenMarketsDetails/TokenMarketsDetailsCoordinator.swift
> +            url: URL(string: "https://tangem.com/howtobuy.html")!,
думаю эту ссылку надо вынести в `AppConstants`

2024-07-17 08:38 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenMarketsDetails/TokenMarketsDetailsCoordinator.swift
> +        }
так, ну вот это совсем плохо получается. Я думаю не должно быть никаких обращений к рутовой вью модели для получения данных, координатору должны предоставить всю инфу и он должен снавигировать куда надо, а не ходить по каким-то вьюхам и искать нужную информацию. Надо добавить в `openAddToken(CoinModel, WalletDataProvider)`. Собственно такая функция уже есть `openTokenSelector`. Вообще не понимаю смысла этой функции, она перемешивает код очень сильно.

Вью модель портфолио сама должна предоставлять всю информацию для навигации или же прокидывать запрос в родительскую вью модель, если у неё чего-то не хватает.

2024-07-17 08:38 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenMarketsDetails/TokenMarketsDetailsRoutable.swift
> -    func openTokenSelector(with coinModel: CoinModel, with walletDataProvider: MarketsWalletDataProvider)
не надо удалять эту функцию. Она в таком виде должна сохраниться, чтобы координатор не ходил в 3 источник (`rootViewModel`) за дополнительными данными

2024-07-17 08:38 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenMarketsDetails/TokenMarketsDetailsViewModel.swift
> -    func onAddToPortfolioTapAction() {
нет-нет, верните как было лучше, если нет альтернативного варианта. Новый вариант усложняет код сильно

2024-07-17 13:15 UTC, skibinalexander commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioContainerViewModel.swift
> +        )
> где-то я это уже видел))) В фабрике есть генерация этой утилиты, давай её заюзаем или из фабрики её удалим

Не очень понимаю как ее можно удалить, в одном случае она используется для фабрики действий, в другом для получения URL

2024-07-17 13:20 UTC, skibinalexander commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioTokenItemView.swift
> +                .renderingMode(.template)
Насколько знаю да, реализация с TokenItemView

2024-07-17 13:20 UTC, skibinalexander commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioTokenItemViewModel.swift
> +    }
> лишнее, нигде не используется вроде как. Можно удалить, вдобавок дублирует `id`

Сори, рудимент разработки

2024-07-17 13:23 UTC, skibinalexander commented on Tangem/Modules/Markets/TokenMarketsDetails/TokenMarketsDetailsCoordinator.swift
> +        }
> так, ну вот это совсем плохо получается. Я думаю не должно быть никаких обращений к рутовой вью модели для получения данных, координатору должны предоставить всю инфу и он должен снавигировать куда надо, а не ходить по каким-то вьюхам и искать нужную информацию. Надо добавить в `openAddToken(CoinModel, WalletDataProvider)`. Собственно такая функция уже есть `openTokenSelector`. Вообще не понимаю смысла этой функции, она перемешивает код очень сильно.
> 
> Вью модель портфолио сама должна предоставлять всю информацию для навигации или же прокидывать запрос в родительскую вью модель, если у неё чего-то не хватает.

Да я согласен, просто наложение слоев случилось в виду того что ViewModel разные, и Coordinator получился фасадом, уберу сделаю через проброс childViewModel -> masterViewModel -> Coodinator

2024-07-17 14:41 UTC, skibinalexander commented on Tangem/Modules/Markets/TokenMarketsDetails/TokenMarketsDetailsRoutable.swift
> -    func openTokenSelector(with coinModel: CoinModel, with walletDataProvider: MarketsWalletDataProvider)
> не надо удалять эту функцию. Она в таком виде должна сохраниться, чтобы координатор не ходил в 3 источник (`rootViewModel`) за дополнительными данными

Ревертнул

2024-07-17 14:48 UTC, skibinalexander commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioContainerView.swift
>          }
> а зачем это условие? есть 2 вьюхи, у которых одинаковый бэкграунд и закругление. Думаю `VStack`, внутри которого лежат `headerView` и `contentView` должны иметь свой закругленный бэкграунд и `quickActionsView` - тоже

Не совсем так, связано с работного контекстного меню чтобы не обрезались грани, можем обсудить как упростить ...

2024-07-17 14:49 UTC, skibinalexander commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioContainerView.swift
> +                .modifier(HeaderCornerRadiusModify())
> что-то дофига заморочистая вьюха получается с кучей условий.

SUI контекстное меню :(((

2024-07-17 14:49 UTC, skibinalexander commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioContainerView.swift
> +                    }
Поправил, код который ты предложил не работает из за специфичности оси 16+ / 16-

2024-07-17 14:50 UTC, skibinalexander commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioContainerView.swift
> +        .offset(y: -Constants.defaultVerticalOffsetSpacingBetweenContent)
> а зачем этот сдвиг?..

Чтобы не видно было скруглений, предлагаю обсудить станет понятнее зачем такие костыли, либо упростим :)

2024-07-17 21:34 UTC, Balashov152 commented on Tangem/Common/TokenActions/CanStakeActionUtility.swift
> +struct CanStakeActionUtility {
Там вообще поменяется все 
можно будет `walletModel.stakingManagerState.isAvailable` проверять, и все

2024-07-17 21:36 UTC, Balashov152 commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioContainerViewModel.swift
> +        let canStake = CanStakeActionUtility().canStake(with: userWalletModel, by: walletModel)
Вообще уже есть `StakingFeatureProvider` 
Лучше его доработать

2024-07-18 06:39 UTC, Andoran90 commented on Tangem/Resources/Localizations/de.lproj/Localizable.strings
> +"staking_validator" = "Validator";
ожидайте конфликты)
https://github.com/tangem/tangem-app-ios/pull/3528

2024-07-18 12:00 UTC, Andoran90 approved these changes, later dismissed

2024-07-18 12:00 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioContainerView.swift
> +                        roundedCornersVerticalEdge = nil
не залил те правки?

2024-07-18 12:00 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioTokenItemViewModel.swift
> +        "\(walletModel.tokenItem.currencySymbol) \(walletModel.tokenItem.networkName)"
тут ничего не ответили?

2024-07-18 12:31 UTC, skibinalexander commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioContainerViewModel.swift
> +        let canStake = CanStakeActionUtility().canStake(with: userWalletModel, by: walletModel)
Поправил

2024-07-19 10:53 UTC, skibinalexander commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioContainerView.swift
> +                        roundedCornersVerticalEdge = nil
> не залил те правки?

Мистер Сон, спасибо, извините, потерял изменения из-за того что вчера много переключались

2024-07-19 10:54 UTC, skibinalexander commented
По tokenName - "Это просто название сети"

2024-07-19 13:09 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioContainerViewModel.swift
> +        if tokenItemViewModels.count == 1 {
забыл тут заменить на `isOneTokenInPortfolio`

2024-07-19 14:12 UTC, Andoran90 approved these changes

2024-07-22 11:05 UTC, tureck1y commented on Tangem/Modules/Markets/TokenMarketsDetails/Common/MarketsTokenDetailsPortfolioCoordinatorFactory.swift
> +struct MarketsTokenDetailsPortfolioCoordinatorFactory {
У нас была похожая история в стейкинге, но пока отказались. Нужно выработать единый подход и поправить сразу во всем приложении, если хотим сборку выносить из координаторов. Сейчас получается сборка кто в лес кто по дрова

2024-07-22 11:07 UTC, tureck1y approved these changes

2024-07-22 11:08 UTC, tureck1y commented on Tangem/Modules/Markets/TokenMarketsDetails/Common/MarketsTokenDetailsPortfolioCoordinatorFactory.swift
> +struct MarketsTokenDetailsPortfolioCoordinatorFactory {
Может будем в модуль класть файлик  Assembly и там собирать? Типа будет набор MarketsAssembly, MarketsCoordinator, MarketsViewModel и тп

2024-07-22 13:11 UTC, merged