IOS-7365 [Staking] Update to use `StakingManager` everywhere
tangem/tangem-app-ios-old pull request #3520
Opened 2024-07-16 10:00 UTC by Balashov152

`WalletModel`
↓
`StakingManagerProvider`- слушает `StakingRepositoryProxy` и создает менеджер если его еще нет, кейс с долгой подрузкой.
↓
`StakingManager`
↓
`StakingDetails` && `StakingFlow`

2024-07-16 11:43 UTC, tureck1y commented on Tangem/Modules/StakingDetails/StakingDetailsViewModel.swift
> +    private let userWalletModel: UserWalletModel
а зачем она тут нужна?

2024-07-16 11:45 UTC, tureck1y commented on Tangem/App/Factories/StakingFactories/StakingModulesFactory.swift
> +    func makeStakingDetailsViewModel(
Мне пока не очень нравится идея тут стейкинг собирать. Если мы уходим от сборки в координаторах, то нужно договорить как это делать и сделать сразу по всему проекту, а то будет вразнобой

2024-07-16 11:48 UTC, tureck1y commented on Tangem/App/ViewModels/WalletModel/WalletModel.swift
> +    var stakingManager: StakingManager? {
Давай обсудим, надо это отсюда убирать все же

2024-07-16 11:54 UTC, tureck1y requested changes

2024-07-16 11:54 UTC, tureck1y commented on Tangem/App/Services/StakingManagerProvider/StakingManagerProvider.swift
> +class StakingManagerProvider {
Я подлил папочку Staking в Services. Надо все туда переложить. Чет сущностей так много, точно столько нужно? Где точка входа в сборку стейкинга?

2024-07-16 11:54 UTC, tureck1y commented on Tangem/App/Services/StakingManagerProvider/StakingManagerProvider.swift
> +        guard StakingFeatureProvider().isAvailable(for: tokenItem) else {
Проверка по конфигу не потерялась?

2024-07-16 11:54 UTC, tureck1y commented on Tangem/Modules/Main/MultiWalletMainContent/MultiWalletMainContentViewModel.swift
>              userWalletModel.config.isFeatureVisible(.staking),
Вот про эту проверку имел в виду, может есть смысл это тоже в провайдер унести?

2024-07-16 14:33 UTC, Balashov152 commented on Tangem/Modules/TokenDetails/TokenDetailsViewModel.swift
> +    @Injected(\.stakingAvailabilityProvider) private var stakingAvailabilityProvider: StakingAvailabilityProvider
@fedorov-d Можно использовать менеджер отсюда что бы отобразить балансы

2024-07-16 16:03 UTC, tureck1y commented on Tangem/App/Factories/StakingFactories/StakingModulesFactory.swift
> +    func makeStakingDetailsViewModel(
перенес мб?

2024-07-16 16:06 UTC, tureck1y submitted a review, later dismissed

2024-07-17 09:11 UTC, Balashov152 commented on Tangem/App/Services/EnvironmentProvider/FeaturesStorage.swift
> +    @AppStorageCompat(FeatureStorageKeys.stakingBlockchainsIds)
Поправил ключ

2024-07-17 09:12 UTC, Balashov152 commented on Tangem/App/Services/EnvironmentProvider/StakingFeatureProvider.swift
> +            "cosmos": "cosmos-atom-native-staking",
Решил захардкодить yield id здесь, так как при добавлении новых, обновление приложения обязательно )

2024-07-17 09:13 UTC, Balashov152 commented on Tangem/App/ViewModels/WalletModel/WalletModel.swift
> -    var transactionHistoryNotLoaded: Bool {
забыл удалить после рефака сенда

2024-07-17 09:14 UTC, Balashov152 commented on Tangem/App/ViewModels/WalletModel/WalletModel.swift
> +    var stakingManager: StakingManager? {
Решили на звонке что все таки будем хранить `StakingManager` здесь

2024-07-17 09:15 UTC, Balashov152 commented on Tangem/Modules/Main/MainCoordinatorView.swift
> +            }
Должна быть `push` анимация

2024-07-17 09:20 UTC, Balashov152 commented on Tangem/App/Factories/StakingFactories/StakingModulesFactory.swift
> +    func makeStakingDetailsViewModel(
✅

2024-07-17 09:20 UTC, Balashov152 commented on Tangem/App/Services/StakingManagerProvider/StakingManagerProvider.swift
> +class StakingManagerProvider {
Получается вообще все удалил нафиг )

Остался `StakingManager` который в отдельном `framework`

2024-07-17 10:22 UTC, fedorov-d commented on Tangem/App/Services/EnvironmentProvider/StakingFeatureProvider.swift
> +        guard let yieldId = yieldIds[tokenItem.blockchain.networkId] else {
```suggestion
        return yieldIds[tokenItem.blockchain.networkId]
```

2024-07-17 10:26 UTC, Balashov152 commented on Tangem/App/Services/EnvironmentProvider/StakingFeatureProvider.swift
> +        guard let yieldId = yieldIds[tokenItem.blockchain.networkId] else {
Я пока так сделал для дебага, так как может еще поменяется, и включать будем сами yield, а не токены )

2024-07-17 10:27 UTC, Balashov152 commented on Tangem/App/Services/EnvironmentProvider/StakingFeatureProvider.swift
> +        guard let yieldId = yieldIds[tokenItem.blockchain.networkId] else {
ну вообще да, можно будет поменять, как устаканиться

2024-07-17 10:44 UTC, fedorov-d approved these changes

2024-07-17 17:34 UTC, tureck1y approved these changes

2024-07-17 17:34 UTC, tureck1y commented on Tangem/App/Services/EnvironmentProvider/StakingFeatureProvider.swift
> +    func yieldId(for tokenItem: TokenItem) -> String? {
Эх сюда бы еще проверку из конфига

2024-07-17 20:46 UTC, Balashov152 commented on Tangem/App/Services/EnvironmentProvider/StakingFeatureProvider.swift
> +    func yieldId(for tokenItem: TokenItem) -> String? {
Ну вообще да, проверю в финальном MR это

2024-07-17 20:46 UTC, merged