IOS-7051 Ability to send new transaction on ETH like networks with active transaction
tangem/tangem-app-ios-old pull request #3541
Opened 2024-07-21 20:29 UTC by amuraveinik

[IOS-7051](https://tangem.atlassian.net/browse/IOS-7051)

[Соответствующий PR в BSDK ](https://github.com/tangem/blockchain-sdk-swift/pull/775)

2024-07-21 20:30 UTC, amuraveinik commented
Пока что билды будут фейлиться, т.к. не подключал сюда ветку из BSDK

2024-07-21 20:30 UTC, amuraveinik commented on Tangem/App/Services/Express/ExpressTransactionBuilder/CommonExpressTransactionBuilder.swift
> -                let nonce = try await ethereumNetworkProvider.getTxCount(source).async()
Нонс перестал запрашивать, т.к. он убран из `EthereumTransactionParams`.

[Вот тут про это написал](https://github.com/tangem/blockchain-sdk-swift/pull/775#discussion_r1685806813)

2024-07-21 20:31 UTC, amuraveinik commented on Tangem/App/Services/WalletConnect/Utilities/WalletConnectEthTransactionBuilder.swift
> +        transaction.params = EthereumTransactionParams(data: wcTxData)
Аналогично предыдущему комменту

2024-07-22 10:59 UTC, tureck1y requested changes

2024-07-22 10:59 UTC, tureck1y commented on Tangem/App/Services/WalletConnect/Utilities/WalletConnectEthTransactionBuilder.swift
> +        transaction.params = EthereumTransactionParams(data: wcTxData)
Тут надо оставить, либо берем нонс от dapp, либо сами запрашиваем в бсдк, если его нет

2024-07-23 10:27 UTC, amuraveinik commented on Tangem/App/Services/Express/ExpressTransactionBuilder/CommonExpressTransactionBuilder.swift
> -                let nonce = try await ethereumNetworkProvider.getTxCount(source).async()
Получается это это уже не актуально, т.к. решили засунуть нонс обратно в параметры

2024-07-23 11:44 UTC, tureck1y commented on Tangem/App/Services/Express/ExpressTransactionBuilder/CommonExpressTransactionBuilder.swift
> -                let nonce = try await ethereumNetworkProvider.getTxCount(source).async()
так в методе sign же запросится nonce и подставится в парамсы

2024-07-23 13:51 UTC, amuraveinik commented on Tangem/App/Services/Express/ExpressTransactionBuilder/CommonExpressTransactionBuilder.swift
> -                let nonce = try await ethereumNetworkProvider.getTxCount(source).async()
Убрал повторно

2024-07-23 18:37 UTC, tureck1y approved these changes

2024-07-23 18:37 UTC, merged