IOS-6905 [Staking] balance segmented control
tangem/tangem-app-ios-old pull request #3571
Opened 2024-07-26 12:52 UTC by fedorov-d

Добавил segmented control на детали токена. Пришлось порефачить MarketsPickerView, сделал из него generic компонент.

2024-07-26 12:57 UTC, fedorov-d commented on Tangem/UIComponents/SegmentPickerView/SegmentedPicker.swift
> +        .frame(height: 24) // TODO: discuss
тут пришлось вкорячить хардкод высоты, т.к. если задавать снаружи - не работает, @Andoran90 сломает ли это что-то в markets?

2024-07-26 12:58 UTC, fedorov-d commented on Tangem/UIComponents/SegmentPickerView/SegmentedPicker.swift
> +struct SegmentedPicker<Option: Hashable & Identifiable>: View {
это просто переименованный MarketsPickerView с generic параметром, внутри почти ничего не менял, только высоту, на это есть комент ниже.

2024-07-26 12:59 UTC, fedorov-d commented on TangemStaking/Models/StakingBalanceInfo.swift
> +public enum BalanceGroupType {
сделал аналогично андроиду

2024-07-26 13:00 UTC, fedorov-d commented on TangemStaking/Services/StakingManager/StakingManager.swift
> +    case staked(StakingBalanceInfo, YieldInfo)
2 кейса на активный стейкинг не нужно, все данные будут в StakingBalanceInfo

2024-07-26 14:49 UTC, Andoran90 commented on Tangem/UIComponents/SegmentPickerView/SegmentedPicker.swift
> +        .frame(height: 24) // TODO: discuss
угу, сломает динамические шрифты, @m3g0byt3  тоже собирался сделать правку на этот счет, такие вещи надо решать паддингами

2024-07-26 15:17 UTC, tureck1y commented on Tangem/UIComponents/SegmentPickerView/SegmentedPicker.swift
> +        .frame(height: 24) // TODO: discuss
что тут в итоге? Оставляем так и правим отдельной задачей? Есть ли задача?

2024-07-26 15:25 UTC, tureck1y requested changes

2024-07-26 15:25 UTC, tureck1y commented on Tangem/Modules/StakingDetails/StakingDetailsViewModel.swift
>          // TODO: Dmitry Fedorov
тудушка еще нужна?

2024-07-26 15:25 UTC, tureck1y commented on Tangem/UIComponents/BalanceWithButtonsView/BalanceWithButtonsViewModel.swift
> +        didSet {
Давай лучше через подписку сделаем на $selectedBalanceType в bind. В целом лучше бы не смешивать подходы и все didSet переделать на подписки, чтобы не распутывать логику, бегая глазами по файлу

2024-07-26 15:25 UTC, tureck1y commented on Tangem/UIComponents/BalanceWithButtonsView/BalanceWithButtonsViewModel.swift
> +            .sink(receiveValue: { [weak self] availableBalance in
через assign такие штуки компактнее получаются

2024-07-26 16:18 UTC, fedorov-d commented on Tangem/UIComponents/SegmentPickerView/SegmentedPicker.swift
> +        .frame(height: 24) // TODO: discuss
не совсем понял как это решается с помощью паддингов. minHeight не поможет с динамическими шрифтами?

2024-07-26 17:15 UTC, fedorov-d commented on Tangem/Modules/StakingDetails/StakingDetailsViewModel.swift
>          // TODO: Dmitry Fedorov
пока да

2024-07-26 17:16 UTC, fedorov-d commented on Tangem/UIComponents/BalanceWithButtonsView/BalanceWithButtonsViewModel.swift
> +        didSet {
убрал лишние переменные и все didSet, переделал на combineLatest3

2024-07-26 17:16 UTC, fedorov-d commented on Tangem/UIComponents/BalanceWithButtonsView/BalanceWithButtonsViewModel.swift
> +            .sink(receiveValue: { [weak self] availableBalance in
убрал совсем

2024-07-26 17:32 UTC, Balashov152 approved these changes, later dismissed

2024-07-26 17:32 UTC, Balashov152 commented on Tangem/UIComponents/BalanceWithButtonsView/BalanceWithButtonsView.swift
> +        }
nit: просто на будущее )
```suggestion
        }
```

2024-07-26 17:32 UTC, Balashov152 commented on Tangem/UIComponents/BalanceWithButtonsView/BalanceWithButtonsViewModel.swift
> +        }
Переводы может нужны ?

2024-07-26 17:48 UTC, tureck1y submitted a review, later dismissed

2024-07-29 06:11 UTC, Andoran90 commented on Tangem/UIComponents/SegmentPickerView/SegmentedPicker.swift
> +        .frame(height: 24) // TODO: discuss
на 51 строке ответ на этот вопрос :) подкрути паддинги на нужное значение

2024-07-29 13:21 UTC, Andoran90 approved these changes

2024-07-29 13:43 UTC, tureck1y approved these changes

2024-07-29 13:43 UTC, merged