Feature/markets/ios 7539 fix switch interval
tangem/tangem-app-ios-old pull request #3614
Opened 2024-08-05 14:16 UTC by skibinalexander

- Доработал переключение процентов по изменению интервала фильтра
- Также поправил значение процентов

Пусть посмотрит мистер Сон сначала

![IMG_1106 3](https://github.com/user-attachments/assets/39ffd7cd-ed2d-4f3d-b090-aa91deae5bb1)

2024-08-05 14:19 UTC, skibinalexander commented
https://github.com/user-attachments/assets/731dfc13-bd01-4f22-86d7-0ebbcbff5a27

2024-08-06 07:50 UTC, Andoran90 requested changes

2024-08-06 07:50 UTC, Andoran90 commented on Tangem/App/Utilities/PriceChange/PriceChangeUtility.swift
> +    func convertToPriceChangeState(changePercent: Decimal?, isDevide: Bool = true) -> TokenPriceChangeView.State {
подожди, для этого есть функция выше `convertToPriceChangeState`, тут должны конвертироваться только процентные значения, вызывай просто другую функцию, не надо добавлять сюда булку.

Возможно надо немного названия поменять, в этой функции оставлять без изменений, а верхней умножать на 100, чтобы конвертировать в проценты, но в таком случае надо посмотреть по местам использования

2024-08-06 07:50 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenList/MarketsItemViewModel.swift
> +        priceChangeState = priceChangeUtility.convertToPriceChangeState(changePercent: priceChangeValue, isDevide: false)
используй тут `convertToPriceChangeState`, т.к. с бэка приходит инфа уже в процентах

2024-08-06 07:50 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenList/MarketsItemViewModel.swift
> +                }
там же словарь, не надо в цикле гонять
```suggestion
                guard let newQuote = viewModel.quotesRepository.quotes[viewModel.tokenId] else {
                    return
                }
```

2024-08-06 09:07 UTC, tureck1y commented on Tangem/Modules/Markets/TokenList/MarketsItemViewModel.swift
> +        #if DEBUG
давай этот весь код удалим, если не нужно больше, либо юзать общий логгер

2024-08-06 09:37 UTC, skibinalexander commented on Tangem/Modules/Markets/TokenList/MarketsItemViewModel.swift
> +        #if DEBUG
> давай этот весь код удалим, если не нужно больше, либо юзать общий логгер

Я просто не уверен был, что уже не нужно для дебага, так как Мистер Сон, еще гоняет обновления. И добавил просто чтобы не пропустить в релиз ... Давай уберу, угу

2024-08-06 09:38 UTC, skibinalexander commented on Tangem/Modules/Markets/TokenList/MarketsItemViewModel.swift
> +                }
> там же словарь, не надо в цикле гонять

Угу неверный рудимент разработки

2024-08-06 11:43 UTC, Andoran90 approved these changes

2024-08-06 12:05 UTC, Andoran90 submitted a review, later dismissed

2024-08-06 12:05 UTC, tureck1y approved these changes, later dismissed

2024-08-06 12:14 UTC, Andoran90 approved these changes

2024-08-06 12:18 UTC, tureck1y approved these changes

2024-08-06 13:38 UTC, merged