IOS-7542: Fix issue with wrong Twin image on retwin
tangem/tangem-app-ios-old pull request #3625
Opened 2024-08-06 13:32 UTC by Andoran90

Была проблема что использовалась существующая модель, а не бралась та, что была отсканирована. Картинки изображений формируется используя `userWalletModel`, всплыло это по такой схеме:
1. добавляешь твин карту с номером 1
2. заходишь в настройки и сканируешь карту с номером 2
3. пытаешься сбросить до заводских - используется существующая модель из репозитория с 1 номером

2024-08-06 15:28 UTC, tureck1y requested changes

2024-08-06 15:28 UTC, tureck1y commented on Tangem/Modules/ScanCardSettings/ScanCardSettingsViewModel.swift
> +            let model = CommonUserWalletModel(cardInfo: cardInfo)
Здесь не должна создаваться новая модель, мы передаем уже имеющуюся, а создание происходит во время онбординга в `func initializeUserWallet(from cardInfo: CardInfo)`

2024-08-07 05:40 UTC, Andoran90 commented on Tangem/Modules/ScanCardSettings/ScanCardSettingsViewModel.swift
> +            let model = CommonUserWalletModel(cardInfo: cardInfo)
я думаю наоборот, конкретно в случае твинов надо создавать новую модель, т.к. карточки абсолютно разные, твин карты не такие же как воллеты, у каждого твина свои пары ключей, у каждой захардкожена пара и это важно с какой картой ты заходишь в экран настройки. Инпут для ретвина должен браться не по сохраненной карте, а по только что отсканированной, т.к. это совершенно разные карточки, в них одинаковые же только 4 цифры в номере. А `CommonUserWalletModel` должна описывать карточку отсканированную

2024-08-07 08:10 UTC, tureck1y commented on Tangem/Modules/ScanCardSettings/ScanCardSettingsViewModel.swift
> +            let model = CommonUserWalletModel(cardInfo: cardInfo)
При сканировании создаются данные и вот из этих данных уже можно прокинуть нужную информацию, создание новой модели - тяжелая операция с синками и прочим, я не просто так все создания лишние выпилил

2024-08-08 10:08 UTC, tureck1y commented on Tangem/Modules/ScanCardSettings/ScanCardSettingsViewModel.swift
> +            let model = CommonUserWalletModel(cardInfo: cardInfo)
что с этим багом?

2024-08-21 12:22 UTC, tureck1y commented on Tangem/Modules/Onboarding/Twins/TwinsOnboardingViewModel.swift
> +                        if !viewModel.retwinMode {
После рефакторинга флоу сброса, при успешно сбросе будет кошелек все равно удален, поэтому тут ничего инициализировать не надо

2024-08-21 12:23 UTC, tureck1y commented on Tangem/Modules/ScanCardSettings/ScanCardSettingsViewModel.swift
> +            cardInput: .cardInfo(cardInfo),
Нет необходимости передавать сюда ссылку на текущий userwallet

2024-08-21 12:24 UTC, tureck1y commented
Подлил правки, проверил 
- онбординг
- ретвин с прямым порядком карт и с началом с разных карт
- ретвин с перекрестным порядком карт и  с началом с разных карт

2024-08-21 12:25 UTC, tureck1y commented
@Andoran90 не могу тебя назанчить ревьювером, посмотри пожалуйста так

2024-08-21 12:26 UTC, tureck1y approved these changes
Случился самоапрув, однако изменения остальные остались

2024-08-23 06:16 UTC, Andoran90 commented
слушай, а сейчас карточка после ретвина пропадает и не сохраняется. Это же не норм поведение вроде как.

2024-08-23 19:14 UTC, tureck1y commented
> слушай, а сейчас карточка после ретвина пропадает и не сохраняется. Это же не норм поведение вроде как.

да, я вот тут про это написал 

**После рефакторинга флоу сброса, при успешно сбросе будет кошелек все равно удален, поэтому тут ничего инициализировать не надо**

Я думаю это ок поведение, примерно как у всех остальных. Чем меньше костылей, тем лучше)

2024-08-26 06:33 UTC, Andoran90 commented
ну дело в том что остальные карты мы сбрасываем, а эти ретвиним и по новой все создаем, так что звучит будто должно быть иначе. Хз в общем-то

2024-08-26 06:45 UTC, Balashov152 approved these changes
Вроде норм, но я профан в онбординге )

2024-08-26 16:25 UTC, tureck1y commented
Как бы то ни было, это не касается этого пулла. Общая парадигма - не делать костылей под старые карты, не проблема взять и отсканить карту, если уж надо будет

2024-08-26 16:25 UTC, merged