IOS-7586 Add wallet selector condiotion
tangem/tangem-app-ios-old pull request #3641
Opened 2024-08-09 08:47 UTC by skibinalexander

Комментарий Лёши был, что мы не должны показывать выбор кошелька если у нас их 1. Спрятал ...

2024-08-09 09:02 UTC, tureck1y requested changes

2024-08-09 09:02 UTC, tureck1y commented on Tangem/Modules/Markets/TokensNetworkSelector/MarketsTokensNetworkSelectorViewModel.swift
> +    @Published var isShowWalletSelector: Bool = false
Лучше сделать computed

2024-08-09 12:14 UTC, tureck1y commented on Tangem/Modules/Markets/TokensNetworkSelector/MarketsTokensNetworkSelectorViewModel.swift
> +        walletDataProvider.userWalletModels.count > 1
isEmpty эффективнее работает, сорри, сразу не заметил

2024-08-09 12:15 UTC, tureck1y approved these changes

2024-08-12 06:46 UTC, Andoran90 approved these changes

2024-08-12 07:46 UTC, merged