IOS-7573 Send: when a custom commission is entered, it is automatically reduced
tangem/tangem-app-ios-old pull request #3654
Opened 2024-08-12 16:04 UTC by amuraveinik

[IOS-7573](https://tangem.atlassian.net/browse/IOS-7573)

<img src="https://github.com/user-attachments/assets/65c8df9e-9a5c-4692-bb86-15ed794384c9" width=300>

2024-08-12 18:10 UTC, tureck1y commented
Накинь пожалуйста комментариев, с ходу совсем непонятно зачем нужно 3 класса для рассчета кастомной комсы в каспе

2024-08-13 08:25 UTC, amuraveinik commented
В первый раз когда реализовывал этот сервис было непонятно что вообще происходит (смотрел на пример сервиса для биткоина) из-за большого количества паблишеров/сабджектов, результат эмита элементов одной последовательности передавались в другую, выполнялись `dropFirst()`, но не было совсем понятно зачем.
В общем, это все очень тяжело читается и порождает такие баги, как текущий.

```swift
Publishers.CombineLatest3(
    satoshiPerByte.dropFirst(),
    input.cryptoAmountPublisher,
    input.destinationAddressPublisher
)
// Skip the initial values
.dropFirst()
.withWeakCaptureOf(self)
.compactMap { service, args in
    let (satoshiPerByte, amount, destination) = args
    return service.recalculateCustomFee(
        satoshiPerByte: satoshiPerByte,
        amount: amount,
        destination: destination
    )
}
.withWeakCaptureOf(self)
.sink { service, fee in
    service.customFee.send(fee)
}
.store(in: &bag)

customFee
    .compactMap { $0 }
    // Skip the initial value
    .dropFirst()
    .withWeakCaptureOf(self)
    .sink { service, customFee in
        service.customFeeDidChanged(fee: customFee)
    }
    .store(in: &bag)
```

В этом PR для каспы я разделил логику на несколько частей:

1. FeeService (изначальный)
2. FeeCalculationModel
3. ReactiveFeeCalculationModel

FeeService мы используем для реализации протокола `CustomFeeService`, то есть в основном чтобы получить изначальные данные и сконфигурировать поля ввода (и в моем случае форматирование числа в фиат тоже происходит здесь.)

FeeCalculationModel - это основная сущность, которая непосредственно занимается просчетом комиссии по введенным данным. Она написана максимально прямолинейна и в императивном стиле, как раз-таки чтобы легко прослеживалась логика непосредственно просчета, также такую модель легко тестировать.

ReactiveFeeCalculationModel - это просто хелпер-враппер над FeeCalculationModel, который во внешний мир отдает нужные уже замапленные паблишеры

2024-08-13 11:29 UTC, tureck1y reviewed
Я все же предлагаю еще подумать над архитектурой, может быть получится упростить. Мы будем и дальше добавлять кастомные комиссии сетей и хочется прийти к единообразному и понятному решению. Сейчас неочевидны ответственности у новых классов. Может сделать в одном и вынести в сушности мапперы и математику? Можем вместе подумать

2024-08-13 11:29 UTC, tureck1y commented on Tangem/Modules/Send/Fee/CustomFeeService/Kaspa/KaspaReactiveFeeCalculationModel.swift
> +            .eraseToAnyPublisher()
Кажется можно эти паблишеры сделать var

2024-08-13 11:29 UTC, tureck1y commented on Tangem/Modules/Send/Fee/CustomFeeService/Kaspa/KaspaFeeCalculationModel.swift
> +        delta = 1 / feeTokenItem.decimalValue
подобрано экспериментально?

2024-08-13 22:13 UTC, amuraveinik commented on Tangem/Modules/Send/Fee/CustomFeeService/Kaspa/KaspaFeeCalculationModel.swift
> +        delta = 1 / feeTokenItem.decimalValue
У нас в полях ввода максимальное количество знаков после запятой равно `feeTokenItem.decimalCount` (например 8) и если продолжать вводить дальше, то значение меняться не будет.

Поэтому если числа отличаются на число которое меньше чем 10^-8, то считаю их одинаковыми

2024-08-13 22:15 UTC, amuraveinik commented on Tangem/Modules/Send/Fee/CustomFeeService/Kaspa/KaspaReactiveFeeCalculationModel.swift
> +            .eraseToAnyPublisher()
Можно, но кажется что разницы абсолютно никакой не будет (только мб код стайл)

2024-08-13 22:23 UTC, amuraveinik commented
> Я все же предлагаю еще подумать над архитектурой, может быть получится упростить. Мы будем и дальше добавлять кастомные комиссии сетей и хочется прийти к единообразному и понятному решению. Сейчас неочевидны ответственности у новых классов. Может сделать в одном и вынести в сушности мапперы и математику? Можем вместе подумать

По сути `FeeCalculationModel` это и есть чисто математика.
А `ReactiveFeeCalculationModel` это маппер рассчитанной комиссии в нужные значения.

Наверное можно сделать маппер в императивном стиле, типа такого, чтобы был тоже хорошо покрываем тестами
```swift
struct KaspaFeeMapper {
  func mapFeeInfoToFee(_ feeInfo: FeeInfo) -> Fee {
    ...
  }

  func mapFeeInfoToAmount(_ feeInfo: FeeInfo) -> Decimal {
    ...
  }

  func mapFeeInfoToValuePerUtxo(_ feeInfo: FeeInfo) -> Decimal {
    ...
  }
}
```

И тогда `feeInfoSubject` можно перенести в сервис, а `ReactiveFeeCalculationModel` удалить.
Тогда мы в тех местах где будет обращение к паблишерам будем писать что-то вроде
```swift
let feePublisher = feeInfoSubject
  .compactMap { $0 }
  .compactMap(mapper. mapFeeInfoToFee)
  .eraseToAnyPublisher()
```


Но мне честно говоря больше нравится текущий вариант, т.к. все маппинги и создание паблишеров мы прячем под капот

2024-08-14 10:18 UTC, tureck1y commented on Tangem/Modules/Send/Fee/CustomFeeService/Kaspa/KaspaReactiveFeeCalculationModel.swift
> +            .eraseToAnyPublisher()
Разница будет в чистоте кода, не нужен будет такой большой init

2024-08-14 10:21 UTC, tureck1y commented
> > Я все же предлагаю еще подумать над архитектурой, может быть получится упростить. Мы будем и дальше добавлять кастомные комиссии сетей и хочется прийти к единообразному и понятному решению. Сейчас неочевидны ответственности у новых классов. Может сделать в одном и вынести в сушности мапперы и математику? Можем вместе подумать
> 
> По сути `FeeCalculationModel` это и есть чисто математика. А `ReactiveFeeCalculationModel` это маппер рассчитанной комиссии в нужные значения.
> 
> Наверное можно сделать маппер в императивном стиле, типа такого, чтобы был тоже хорошо покрываем тестами
> 
> ```swift
> struct KaspaFeeMapper {
>   func mapFeeInfoToFee(_ feeInfo: FeeInfo) -> Fee {
>     ...
>   }
> 
>   func mapFeeInfoToAmount(_ feeInfo: FeeInfo) -> Decimal {
>     ...
>   }
> 
>   func mapFeeInfoToValuePerUtxo(_ feeInfo: FeeInfo) -> Decimal {
>     ...
>   }
> }
> ```
> 
> И тогда `feeInfoSubject` можно перенести в сервис, а `ReactiveFeeCalculationModel` удалить. Тогда мы в тех местах где будет обращение к паблишерам будем писать что-то вроде
> 
> ```swift
> let feePublisher = feeInfoSubject
>   .compactMap { $0 }
>   .compactMap(mapper. mapFeeInfoToFee)
>   .eraseToAnyPublisher()
> ```
> 
> Но мне честно говоря больше нравится текущий вариант, т.к. все маппинги и создание паблишеров мы прячем под капот

Да, давай упрощать, разделение ради разделения тоже плохо. Тут по сути логики три копейки - пользователь ввел, пересчитали. Поле всего одно, а кода масса.

2024-08-14 10:22 UTC, tureck1y requested changes
Нужно простое и аккуратное решение с минимальным количеством кода и перекладываний.

2024-08-14 14:37 UTC, amuraveinik commented
> Нужно простое и аккуратное решение с минимальным количеством кода и перекладываний.

Оставил чисто математику отдельно, паблишеры и маппинги засунул обратно в сервис

2024-08-14 15:52 UTC, tureck1y approved these changes

2024-08-15 09:28 UTC, fedorov-d approved these changes

2024-08-15 09:43 UTC, merged