IOS-7508 Swap / Update erro 2240 for unavailable pair
tangem/tangem-app-ios-old pull request #3657
Opened 2024-08-13 22:48 UTC by amuraveinik

[IOS-7508](https://tangem.atlassian.net/browse/IOS-7508)

Замечания:
1. Пока не тестил работоспособность
2. Что делать с текстовками для других языков (кроме англ и рус)

2024-08-13 22:49 UTC, amuraveinik commented on Tangem/Resources/Localizations/de.lproj/Localizable.strings
> +"warning_express_refresh_required_title_2240" = "Selected pair temporarily unavailable";
Название дурацкое, согласен, пока не пойму логику создания неймингов

2024-08-14 07:30 UTC, skibinalexander commented
Там вроде как в название МР [SWAP] делаем

2024-08-14 07:31 UTC, skibinalexander commented
Ревью лучше чтобы @tureck1y глянул, что добавляется title, я не совсем в контексте

2024-08-14 07:31 UTC, skibinalexander approved these changes, later dismissed

2024-08-14 10:17 UTC, tureck1y requested changes

2024-08-14 10:17 UTC, tureck1y commented on Tangem/Resources/Localizations/de.lproj/Localizable.strings
> +"warning_express_refresh_required_title_2240" = "Selected pair temporarily unavailable";
- Нужно оставить старый комплект текстовок и добавить новый:

"warning_express_pair_unavailable_title"
"warning_express_pair_unavailable_message"

- Русская текстовка используется в русском, английская - во всех остальных
- Не забыть добавить в локалайз

2024-08-14 10:17 UTC, tureck1y commented on Tangem/App/Services/NotificationManagers/ExpressNotifications/ExpressNotificationManager.swift
> +            event = .refreshRequired(title: occurredError.localizedTitle, message: occurredError.localizedMessage)
Еще забыл про аналитику, в задаче есть. Смотри ExpressNotificationEvent.analyticsEvent. По всей видимости нужно будет прокинуть в refreshRequired ошибку(occurredError) целиком, чтобы по коду уже смотреть какое событие аналитики показывать. В дальнейшем события будут расширяться. Надо проверить, что событие улетает

2024-08-14 10:58 UTC, amuraveinik commented on Tangem/App/Services/NotificationManagers/ExpressNotifications/ExpressNotificationManager.swift
> +            event = .refreshRequired(title: occurredError.localizedTitle, message: occurredError.localizedMessage)
Да, PR должен быть в драфте, сорян, забыл проставить

2024-08-14 13:19 UTC, amuraveinik commented on Tangem/Resources/Localizations/de.lproj/Localizable.strings
> +"warning_express_refresh_required_title_2240" = "Selected pair temporarily unavailable";
Поправил

2024-08-14 13:19 UTC, amuraveinik commented on Tangem/App/Services/NotificationManagers/ExpressNotifications/ExpressNotificationManager.swift
> +            event = .refreshRequired(title: occurredError.localizedTitle, message: occurredError.localizedMessage)
Поправил

2024-08-14 14:01 UTC, amuraveinik commented on Tangem/App/Services/NotificationManagers/ExpressNotifications/ExpressNotificationManager.swift
> +            event = .refreshRequired(title: occurredError.localizedTitle, message: occurredError.localizedMessage)
Проверил, в аплитуду прилетает

<img width="216" alt="image" src="https://github.com/user-attachments/assets/9797e497-7b1a-4365-ab75-65c88b7e1706">

2024-08-14 15:48 UTC, tureck1y commented on Tangem/App/Services/NotificationManagers/ExpressNotifications/ExpressNotificationManager.swift
> +        analyticsService.setup(with: self, contextDataProvider: contextDataProvider)
@Andoran90 а зачем вообще нужен contextDataProvider, если аналитика сама умеет контекст добавлять?

2024-08-14 15:50 UTC, tureck1y approved these changes, later dismissed

2024-08-15 05:15 UTC, Andoran90 commented on Tangem/App/Services/NotificationManagers/ExpressNotifications/ExpressNotificationManager.swift
> +        analyticsService.setup(with: self, contextDataProvider: contextDataProvider)
если правильно помню, у нас оповещения на главной неправильные ивенты отправляли. Всегда отсылалась инфа с выбранным кошельком, а ивенты выбрасывались и для остальных экранов, поэтому надо было добавлять провайдер контекста.
Вообще по хорошему немного поменять этот провайдер и сделать чтобы он предоставлял не `AnalyticsContextData` а сразу словарь с параметрами, тогда можно будет по разному определять контекст события, добавить туда аккаунты, например.

2024-08-15 09:04 UTC, skibinalexander submitted a review, later dismissed

2024-08-15 10:12 UTC, tureck1y commented on Tangem/App/Services/NotificationManagers/ExpressNotifications/ExpressNotificationManager.swift
> +        analyticsService.setup(with: self, contextDataProvider: contextDataProvider)
Получается это нужно для нотификейшен менеджеров, которые висят одновременно в приложении (по разным user wallet). В express такого быть не может, поэтому contextDataProvider передавать не нужно

2024-08-15 13:22 UTC, tureck1y approved these changes

2024-08-15 14:15 UTC, merged