IOS-7548: [Markets] Update token quotes repository for markets requests
tangem/tangem-app-ios-old pull request #3661
Opened 2024-08-14 12:54 UTC by Andoran90

* Убрал перевод процента изменения в дробные части, стремный сайд-эффект, когда пытаешься разобраться почему у нас с бэка приходит одна информация, а в аппке уже оказывается другая. Этот перевод порождал неправильную трактовку в названиях функций
* Разделил протокол `TokenQuoteRepository` на 2 протокола:
    *  `TokenQuoteDataProvider` - предоставляет инфу по квотам
    * `TokenQuotesRepositoryUpdater` - позволяет как запрашивать новые данные, так обновлять инфу в репозитории извне, то что надо для маркетсов
* Пересмотрел форматтеры, поменял названия на явные `formatFractionalValue` и `formatPercentValue`. Внутри уже делается нужная конвертация, если она нужна. Для процентов она нужна, т.к. `NumberFormatter` при стиле `precent` умножает все значения на 100
* Добавил юнитов для новых кейсов для `PercentFormatter`, т.к. он выполняет всю работу
* Добавил очистку репозитория квот, если произошел логаут, с @tureck1y обсуждали это поведение. 
*

2024-08-14 16:08 UTC, tureck1y requested changes

2024-08-14 16:08 UTC, tureck1y commented on Tangem/App/Services/TokenQuotesRepository/TokenQuotesRepository.swift
> +protocol TokenQuotesRepositoryUpdater: AnyObject {
Я все же предлагаю разделить по принципу read/write.  TokenQuotesRepository/TokenQuotesRepositoryUpdater. А от провайдера отказаться и изменений будет сильно меньше

Даже вот по неймингу видно разницу
tokenQuotesDataProvider.load() vs tokenQuotesRepositoryUpdater.load()

2024-08-14 16:08 UTC, tureck1y commented on Tangem/App/Services/TokenQuotesRepository/CommonTokenQuotesRepository.swift
> +            .sink { repository, event in
NP: можно было через фильтр

2024-08-14 16:08 UTC, tureck1y commented on Tangem/App/Utilities/PriceChange/PriceChangeFormatter.swift
> +    func formatPercentValue(_ value: Decimal, option: PercentFormatter.Option) -> PriceChangeFormatter.Result {
Не очень конечно хорошо, что мы постоянно эти форматтеры переписываем, нужно уже зафиксировать апи. Мое имхо понятнее совсем не стало, наоборот сложнее. Нужно добавить доки с примером хотя бы

2024-08-14 16:08 UTC, tureck1y commented on Tangem/App/ViewModels/WalletModel/WalletModel.swift
> +    @Injected(\.quotesRepositoryUpdater) private var quotesRepositoryUpdater: TokenQuotesRepositoryUpdater
такого быть не должно, всегда один инжект

2024-08-14 16:08 UTC, tureck1y commented on TangemTests/PriceChangeFormatterTests.swift
> +        let result = formatter.formatPercentValue(0.1, option: .priceChange)
какая-то жесть formatFractionalValue, formatPercentValue, при этом formatFractionalValue + option: .express тоже выдает проценты. Нужно либо отдельной задачей делать рефак, либо работать с тем что было

2024-08-15 05:21 UTC, Andoran90 commented on Tangem/App/Services/TokenQuotesRepository/TokenQuotesRepository.swift
> +protocol TokenQuotesRepositoryUpdater: AnyObject {
изначально так и хотел сделать, но тогда не понимаю как назвать `typealias`?.. просто `typealias TokenQuotesRepository` включает в себя весь репозиторий. А он нужен, чтобы все хранить под одним ключом `TokenQuotesRepositoryKey`.
На счет `loadQuotes` - почему это не в репозитории, а в `Updater` - потому что эта функция не дает тебе ответа о квотах, она делает запрос и обновляет репозиторий, поэтому она не часть read, можно переименовать: `requestUpdate(for currencyId: String)`, тогда это будет справедливо + будет отображать то что запрос на эту валюту даже не сразу отправится. Что скажешь?

2024-08-15 05:22 UTC, Andoran90 commented on Tangem/App/Services/TokenQuotesRepository/TokenQuotesRepository.swift
> +protocol TokenQuotesRepositoryUpdater: AnyObject {
собственно я эту функцию оставил в `DataProvider` из-за того что она тебе в итоге вернет квоты, хоть и сделает сетевой запрос и обновит инфу репозитории, но результат будет дан
`func quote(for currencyId: String) async throws -> TokenQuote`

2024-08-15 05:24 UTC, Andoran90 commented on Tangem/App/Services/TokenQuotesRepository/CommonTokenQuotesRepository.swift
> +            .sink { repository, event in
в начале сделал через фильтр, просто не очень понравилось что все равно остается `if case .locked`, т.к. ивенты не реализуют `Equatable`. Давай сделаю так

2024-08-15 05:27 UTC, Andoran90 commented on Tangem/App/Utilities/PriceChange/PriceChangeFormatter.swift
> +    func formatPercentValue(_ value: Decimal, option: PercentFormatter.Option) -> PriceChangeFormatter.Result {
ну до этого был косяк что мы данные с бэка изменяем где-то глубоко и это совершенно неоднозначно, потому что в другом запросе мы получаем проценты, но вся команда должна помнить, что именно с квотами когда-то решили работать не с процентами, а с дробными значениями и конвертить абсолютно везде теперь надо.
Думаю сейчас гораздо прозрачнее стало и по неймингу тоже - ты можешь отформатировать либо проценты, либо дробную версию. Доку с примером добавлю.

2024-08-15 05:30 UTC, Andoran90 commented on TangemTests/PriceChangeFormatterTests.swift
> +        let result = formatter.formatPercentValue(0.1, option: .priceChange)
это форматтер, который всегда выдает проценты, вопрос во входных данных - если у тебя на входе проценты - одна обработка, если нет - другая.
Все делалось в одной задаче, т.к. проблемы были в разных местах и надо было все разом поправить и перепроверить, потому что из-за скрытой конвертации процентов в квотах - были странные баги, что какие-то данные в 100 раз отличались, а какие-то - нет.

2024-08-15 11:41 UTC, Andoran90 commented on Tangem/App/Utilities/PriceChange/PriceChangeFormatter.swift
> +    func formatPercentValue(_ value: Decimal, option: PercentFormatter.Option) -> PriceChangeFormatter.Result {
добавил небольшую доку с примерами

2024-08-15 12:10 UTC, Andoran90 commented on Tangem/App/ViewModels/WalletModel/WalletModel.swift
> +    @Injected(\.quotesRepositoryUpdater) private var quotesRepositoryUpdater: TokenQuotesRepositoryUpdater
вернул старую реализацию, как обсудили

2024-08-15 12:14 UTC, tureck1y commented on Tangem/App/Services/TokenQuotesRepository/TokenQuotesRepository.swift
> +    var quotesRepository: TokenQuotesRepository & TokenQuotesRepositoryUpdater {
Тут получается надо переименовать, сделать приватным и добавить отдельный 
var quotesRepository: TokenQuotesRepository

2024-08-15 12:15 UTC, Andoran90 commented on Tangem/App/Services/TokenQuotesRepository/TokenQuotesRepository.swift
> +    var quotesRepository: TokenQuotesRepository & TokenQuotesRepositoryUpdater {
если сделаем приватным сломаются превьюхи, в некоторых случаях надо сеттить фейковый репозиторий

2024-08-15 12:17 UTC, Andoran90 commented on Tangem/App/Services/TokenQuotesRepository/TokenQuotesRepository.swift
> +    var quotesRepository: TokenQuotesRepository & TokenQuotesRepositoryUpdater {
такие сущности лучше полностью не закрывать, особенно ~если~ когда начнем добавлять юниты для вью моделей

2024-08-15 12:52 UTC, tureck1y submitted a review, later dismissed

2024-08-15 15:03 UTC, m3g0byt3 commented on Tangem/App/Services/TokenQuotesRepository/CommonTokenQuotesRepository.swift
> +    private let lock = Lock(isRecursive: true)
1. Если в `saveQuotes(_ quotes: [TokenQuote])` обращаться к `_quotes` вместо `self.quotes` - то лок можно сделать не-рекурсивным (что в общем случае лучше по перформансу)
2. А тут вообще нужен лок? Если не путаю у `CurrentValueSubject` его `value` и так защищена локом или чем-то еще. Кажется разбирали это какое-то время назад с @Balashov152

2024-08-15 15:03 UTC, m3g0byt3 commented on Tangem/App/Services/TokenQuotesRepository/CommonTokenQuotesRepository.swift
> +                }
Есть же вроде акксессор для `_quotes` у репозитория

Обращаться к его приватным пропетям вроде `lock` и `_quotes` снаружи не выглядит ок

2024-08-15 15:03 UTC, m3g0byt3 commented on Tangem/App/Utilities/PriceChange/PriceChangeFormatter.swift
> +    func formatPercentValue(_ value: Decimal, option: PercentFormatter.Option) -> PriceChangeFormatter.Result {
С примерами все стало понятно и нейминг вроде всё хорошо отражает

2024-08-15 15:03 UTC, m3g0byt3 commented on Tangem/App/Utilities/PriceChange/PriceChangeFormatter.swift
> +        let valueToFormat = value * 0.01
Здесь может теряться точность из-за double литерала
Не знаю, критично ли это конкретно в форматтере, так как проценты обычно и так округляют, но fyi

2024-08-15 15:03 UTC, m3g0byt3 commented on Tangem/Modules/Markets/TokenMarketsDetails/Helpers/MarketsTokenQuoteHelper.swift
> +        }
nit: нет необходимости анврапить тут, можно просто
```
priceChangeDict[MarketsPriceIntervalType.day.rawValue] = tokenQuote.priceChange24h
priceChangeDict[MarketsPriceIntervalType.week.rawValue] = tokenQuote.priceChange7d
priceChangeDict[MarketsPriceIntervalType.month.rawValue] = tokenQuote.priceChange30d
```

2024-08-15 15:03 UTC, m3g0byt3 commented on Tangem/Modules/Markets/TokenMarketsDetails/TokenMarketsDetailsViewModel.swift
> +    private lazy var quotesPublisher: some Publisher<TokenQuote?, Never> = {
Для этого паблишера share не нужно?
Заэмитится самое свежее значение новому подписчику при подписке?
И должен ли он быть lazy?

---

Ранее `currentPricePublisher` как раз намеренно сделан lazy + `.share(replay: 1)` чтобы в нем был стейт и чтобы каждому подписчику при подписке прилетело самое свежее значение 
А не сначала то, что лежит в prepend (в этом пуле prepend удален btw), а затем последнее значение из репы, как только репа сделает эмит - как было бы, если бы `currentPricePublisher` был computed var

2024-08-15 15:03 UTC, m3g0byt3 commented on Tangem/Modules/Markets/Utilities/MarketsQuotesUpdatesScheduler.swift
> +        }
nit: вроде как у lock сложура может возвращать значение, то есть 
```
let quotesToUpdate = lock { Array(updateList) }
```
должно работать

2024-08-16 07:26 UTC, Andoran90 commented on Tangem/App/Utilities/PriceChange/PriceChangeFormatter.swift
> +        let valueToFormat = value * 0.01
не должно быть проблемой

2024-08-16 07:26 UTC, Andoran90 commented on Tangem/App/Services/TokenQuotesRepository/CommonTokenQuotesRepository.swift
> +    private let lock = Lock(isRecursive: true)
сейчас перепроверил все по новой, да с локом проседания есть некоторые, пока что удалил, погонял без лока, вроде норм, не зависает. Надо рефичить загрузку списка...

2024-08-16 07:26 UTC, Andoran90 commented on Tangem/App/Services/TokenQuotesRepository/CommonTokenQuotesRepository.swift
> +                }
убрал лок

2024-08-16 07:26 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenMarketsDetails/TokenMarketsDetailsViewModel.swift
> +    private lazy var quotesPublisher: some Publisher<TokenQuote?, Never> = {
согласен, добавил `share` и оставил `lazy`, чтобы не было доп.инстансов и у всех был единый стейт, т.к. в нем и цены и изменение цены

2024-08-16 07:26 UTC, Andoran90 commented on Tangem/Modules/Markets/Utilities/MarketsQuotesUpdatesScheduler.swift
> +        }
обновил

2024-08-16 07:26 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenMarketsDetails/Helpers/MarketsTokenQuoteHelper.swift
> +        }
обновил

2024-08-16 09:16 UTC, tureck1y approved these changes

2024-08-16 10:50 UTC, m3g0byt3 approved these changes

2024-08-16 10:51 UTC, merged