Bugfix/markets/ios 7604 fix problem add token portfolio
tangem/tangem-app-ios-old pull request #3664
Opened 2024-08-14 19:30 UTC by skibinalexander

Доработаны состояния под загрузку портфолио.
Также сделана фильтрация доступных сетей для отображения кнопки "Добавить"
Сделан опицонал состояния View для того чтобы не было сайд эффектов начальной инициализации

2024-08-15 05:18 UTC, skibinalexander commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/TokenMarketsDetailsView+Skeletons.swift
> +        private var portfolio: some View {
Состояние загрузки перенес в скелетоны соотственно, чтобы лежало все в одном месте

2024-08-15 05:18 UTC, skibinalexander commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioContainerViewModel.swift
> -        let hasMultiCurrency = !userWalletModels.filter { $0.config.hasFeature(.multiCurrency) }.isEmpty
Вынес в отдельный метод

2024-08-15 05:19 UTC, skibinalexander commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioContainerViewModel.swift
> +    private func preflightCanAddAvailableNetworks(for coinModel: CoinModel?) -> Bool {
Проверяем все условия на возможность добавления (поддержку блокчейна картами)

2024-08-15 05:19 UTC, skibinalexander commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioContainerViewModel.swift
> +    func updateState(with coinModel: CoinModel?) {
Метод вызывается после подгрузки деталей токены

2024-08-15 05:20 UTC, skibinalexander commented on Tangem/Modules/Markets/TokenMarketsDetails/TokenMarketsDetailsViewModel.swift
> -                guard let self, let coinModel = loadedInfo?.coinModel, !coinModel.items.isEmpty else {
Не нужное условие

2024-08-15 08:03 UTC, Andoran90 requested changes

2024-08-15 08:03 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioContainerView.swift
> +            MainButton(title: Localization.marketsAddToPortfolioButton) {
если правильно помню - она должна быть задизейблена, пока идет загрузка

2024-08-15 08:03 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioContainerViewModel.swift
> +    }
много лишних действий, перекладываний и преобразований. Думаю лучше что-то типа такого сделать, т.к. у нас цель найти хоть один мультивалютный кошелек поддерживает добавление токена хотя бы в одной сети. Можно ещё оптимизировать, но думаю уже не так критично. + название совсем непонятное, думаю `canAddToPortfolio` норм описывает суть функции
```suggestion
    private func canAddToPortfolio(coinModel: CoinModel?) -> Bool {
        let multiCurrencyUserWalletModels = userWalletModels.filter { $0.config.hasFeature(.multiCurrency) }
        guard
            let coinModel,
            !coinModel.items.isEmpty,
            !multiCurrencyUserWalletModels.isEmpty
        else {
            return false
        }

        var coinModelBlockchains = Set<Blockchain>()
        coinModel.items.forEach {
            coinModelBlockchains.insert($0.blockchain)
        }

        for model in multiCurrencyUserWalletModels {
            if !coinModelBlockchains.intersection(model.config.supportedBlockchains).isEmpty {
                return true
            }
        }

        return false
    }
```

2024-08-15 08:03 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioContainerViewModel.swift
> +    }
может тогда удалим вообще `initialSetup` и в месте вызова сделаем сразу `updateTokenList`? или ты планируешь ещё что-то сюда добавлять?

2024-08-15 08:03 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioContainerViewModel.swift
> +        guard canAddAvailableNetworks else {
```suggestion
        guard canAddToPortfolio(coinModel: coinModel) else {
```

2024-08-15 08:03 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenMarketsDetails/TokenMarketsDetailsViewModel.swift
> +                }
так, проглядел я это в прошлый раз. Зачем нам подписка на `isLoading`, когда мы точно знаем что пришла инфа и в ней есть `coinModel`? надо убрать эту подписку и перенести эту логику в `setupUI`, т.к. там происходит настройка UI после загрузки информации по деталке

2024-08-15 08:27 UTC, skibinalexander commented on Tangem/Modules/Markets/TokenMarketsDetails/TokenMarketsDetailsViewModel.swift
> +                }
> так, проглядел я это в прошлый раз. Зачем нам подписка на `isLoading`, когда мы точно знаем что пришла инфа и в ней есть `coinModel`? надо убрать эту подписку и перенести эту логику в `setupUI`, т.к. там происходит настройка UI после загрузки информации по деталке

Не проглядел, передавали флаг, уберу

2024-08-15 08:28 UTC, skibinalexander commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioContainerView.swift
> +            MainButton(title: Localization.marketsAddToPortfolioButton) {
> если правильно помню - она должна быть задизейблена, пока идет загрузка

<img width="403" alt="Снимок экрана 2024-08-15 в 11 27 56" src="https://github.com/user-attachments/assets/beb84168-0485-46ef-a75e-18be0b81d4c7">

Совсем не будет вьюшки пока не загружено, поэтому вынес в общий блок скелетной

2024-08-15 08:28 UTC, skibinalexander commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioContainerViewModel.swift
> +    }
> много лишних действий, перекладываний и преобразований. Думаю лучше что-то типа такого сделать, т.к. у нас цель найти хоть один мультивалютный кошелек поддерживает добавление токена хотя бы в одной сети. Можно ещё оптимизировать, но думаю уже не так критично. + название совсем непонятное, думаю `canAddToPortfolio` норм описывает суть функции

Тут согласен, посмотрю учитывает твой вариант все рейсы или нет

2024-08-15 08:29 UTC, skibinalexander commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioContainerViewModel.swift
> +    }
> может тогда удалим вообще `initialSetup` и в месте вызова сделаем сразу `updateTokenList`? или ты планируешь ещё что-то сюда добавлять?

Думаю будет, но давай уберу чтобы не смущало

2024-08-15 08:30 UTC, skibinalexander commented on Tangem/Modules/Markets/TokenMarketsDetails/TokenMarketsDetailsViewModel.swift
> +                }
> > так, проглядел я это в прошлый раз. Зачем нам подписка на `isLoading`, когда мы точно знаем что пришла инфа и в ней есть `coinModel`? надо убрать эту подписку и перенести эту логику в `setupUI`, т.к. там происходит настройка UI после загрузки информации по деталке
> 
> Не проглядел, передавали флаг, уберу, сейчас можно в целом напрямую контролить Стейт в месте вызова, а не через подписку

2024-08-15 13:45 UTC, skibinalexander commented
@Andoran90 вроде как все комменты учел

2024-08-16 11:11 UTC, Andoran90 approved these changes, later dismissed

2024-08-16 13:17 UTC, Andoran90 approved these changes, later dismissed

2024-08-16 13:50 UTC, tureck1y approved these changes, later dismissed

2024-08-16 15:08 UTC, Andoran90 approved these changes

2024-08-16 15:11 UTC, tureck1y approved these changes

2024-08-16 15:27 UTC, merged