IOS-7296 [Staking] Add keys and values for staking, add several calls
tangem/tangem-app-ios-old pull request #3675
Opened 2024-08-16 15:14 UTC by fedorov-d

Добавил ключи и значения, несколько вызовов, не успел разобраться как нормально разрулить во флоу сенда (там как будто не хватает данных в нужных местах). Также некоторые вызовы еще невозможно добавить т.к. соотвествующие флоу не реализованы.

2024-08-16 16:56 UTC, Balashov152 approved these changes, later dismissed

2024-09-05 06:56 UTC, fedorov-d commented on TangemStaking/Services/StakingAnalytics/StakingAnalytics.swift
> +public protocol StakingAnalytics {
тут не придумал как лучше добавить аналитику внутрь TangemStaking

2024-09-05 08:19 UTC, Balashov152 commented on Tangem/Modules/Send/SendCoordinator.swift
> +            Analytics.log(.stakingAmountScreenOpened)
Как будто не очень место, это только один раз должно быть? 
Вообще лучше бы в `SendAmountStep` это перенести, можно туда `SendModel.Source` прокидывать, и там уже отправлять. причем там как раз надо будет убрать аналитику от Send, так как дублироваться будет

2024-09-05 08:20 UTC, ba1ashov commented on Tangem/Modules/Send/SendCoordinator.swift
> +            Analytics.log(event: .stakingConfirmationScreenOpened, params: [.validator: validator.name])
Это тоже лучше не здесь, а что за `ConfirmationScreenOpened` ?

2024-09-05 08:27 UTC, Balashov152 commented on Tangem/Modules/Send/UnstakingModel.swift
> +        guard let validator = stakingManager.state.validator(for: action.validator) else { return }
вообще так как `validator` не обязателен для Tron, и он не приходит с API, то и такие проверки будут не актуальны

2024-09-05 08:27 UTC, Balashov152 commented on Tangem/Modules/Send/UnstakingModel.swift
> +        logOpenRewards()
мы сюда заодим не только для `Rewards` еще `Unstaking` и будет  `Unlocking`

2024-09-05 08:30 UTC, Balashov152 commented
Вообще пройдись плиз по вызовам `Analytics` в папке `Send` что бы где то дубликатов не было, может там как то можно прокидывать все что нужно из `StakingFlowBaseBuilder` / `UnstakingFlowBaseBuilder`. Они все собирают, и могут шагам рассказать все

2024-09-05 12:26 UTC, tureck1y requested changes

2024-09-05 12:26 UTC, tureck1y commented on Tangem/App/Factories/StakingFactories/StakingDependenciesFactory.swift
> +extension Analytics: StakingAnalytics {
Можно без этого обойтись? Загрязняет общий интерфейс аналитики

2024-09-05 12:26 UTC, tureck1y commented on Tangem/Modules/Send/StakingModel.swift
> +extension StakingModel {
private?

2024-09-05 12:26 UTC, tureck1y commented on Tangem/Modules/Send/StakingModel.swift
> +    func logTransactionRejected() {
Имхо лучше максимально точечно вызывать аналитику. В случае функции выше да, смысл вынести есть, а тут только спагетти добавляет)

2024-09-05 12:26 UTC, tureck1y commented on Tangem/Modules/Send/UnstakingModel.swift
> +extension PendingActionType {
Тут и ниже тоже наверное можно сделать private

2024-09-05 12:26 UTC, tureck1y commented on Tangem/Modules/Send/UnstakingModel.swift
> +    func logTransactionRejected() {
тут аналогично

2024-09-05 12:26 UTC, tureck1y commented on Tangem/Modules/StakingDetails/StakingDetailsViewModel.swift
> +        stakingManager
Хм, проще открытие экрана не затрекать?

2024-09-05 12:26 UTC, tureck1y commented on TangemStaking/Services/StakingAPIService/StakeKitStakingAPIService.swift
> +            analytics.log(Constants.errors)
а что тут происходит, не очень понял( Как-то в обход обшего флоу. 

Обычно модули соединяли с аналитикой прилы через интерфейс, в котором просто набор методов, log, logErrors (например). И уже реализация в приле дергала аналитику. Так что эти errors надо унести к остальным ивентам, а тут просто метод интерфейса стейкинг аналитики дергать

2024-09-05 12:26 UTC, tureck1y commented on TangemStaking/Services/StakingAnalytics/StakingAnalytics.swift
> +public protocol StakingAnalytics {
отписал в другом комменте

2024-09-05 12:31 UTC, tureck1y commented
посмотри как реф ExpressAnalyticsLogger

2024-09-06 09:02 UTC, fedorov-d commented on Tangem/Modules/Send/SendCoordinator.swift
> +            Analytics.log(event: .stakingConfirmationScreenOpened, params: [.validator: validator.name])
нейминг кривоват, это открытие summary экрана, проблема в том что нужен валидатор и source (Stake/Restake/Claim/ Withdraw), не придумал как пробросить в SendAmountStep

2024-09-06 11:20 UTC, fedorov-d commented on Tangem/Modules/Send/SendCoordinator.swift
> +            Analytics.log(.stakingAmountScreenOpened)
перенес

2024-09-06 11:22 UTC, fedorov-d commented on Tangem/Modules/Send/SendCoordinator.swift
> +            Analytics.log(event: .stakingConfirmationScreenOpened, params: [.validator: validator.name])
перенес во вьюмодель

2024-09-06 11:22 UTC, fedorov-d commented on Tangem/Modules/Send/UnstakingModel.swift
> +        guard let validator = stakingManager.state.validator(for: action.validator) else { return }
поправил

2024-09-06 11:23 UTC, fedorov-d commented on Tangem/Modules/Send/UnstakingModel.swift
> +        logOpenRewards()
добавил логику, трекаем только для pending

2024-09-06 11:23 UTC, fedorov-d commented on Tangem/App/Factories/StakingFactories/StakingDependenciesFactory.swift
> +extension Analytics: StakingAnalytics {
сделал по аналогии с express

2024-09-06 11:23 UTC, fedorov-d commented on Tangem/Modules/Send/StakingModel.swift
> +extension StakingModel {
готово

2024-09-06 11:23 UTC, fedorov-d commented on Tangem/Modules/Send/StakingModel.swift
> +    func logTransactionRejected() {
поправил

2024-09-06 11:26 UTC, fedorov-d commented on Tangem/Modules/Send/UnstakingModel.swift
> +extension PendingActionType {
одно сделал, второе еще используется в другом месте

2024-09-06 11:26 UTC, fedorov-d commented on Tangem/Modules/Send/UnstakingModel.swift
> +    func logTransactionRejected() {
поправил

2024-09-06 11:26 UTC, fedorov-d commented on Tangem/Modules/StakingDetails/StakingDetailsViewModel.swift
> +        stakingManager
перенес в onAppear, вроде ничего не сломалось

2024-09-06 11:26 UTC, fedorov-d commented on TangemStaking/Services/StakingAPIService/StakeKitStakingAPIService.swift
> +            analytics.log(Constants.errors)
поправил

2024-09-06 11:29 UTC, Balashov152 commented on Tangem/Modules/Send/SendCoordinator.swift
> +            Analytics.log(event: .stakingConfirmationScreenOpened, params: [.validator: validator.name])
В прицнипе там в `SendSummaryViewModel` есть через input настройка, может там как то

2024-09-06 12:41 UTC, tureck1y approved these changes

2024-09-06 12:41 UTC, tureck1y commented on Tangem/App/Services/Analytics/CommonStakingAnalyticsLogger.swift
> +        Analytics.log(.stakingErrors)
Вроде странно без уточнения что за ошибка, может быть стоило в параметры какую-то доп инфу класть на будущее?

2024-09-06 13:32 UTC, Balashov152 approved these changes

2024-09-06 17:27 UTC, merged