Feature/ios 7625 make dynamic update portfolio
tangem/tangem-app-ios-old pull request #3682
Opened 2024-08-20 11:33 UTC by skibinalexander

WIP - для просмотра еще не готово. Описание подробное и UI приложу как будет готово

2024-08-20 14:26 UTC, Andoran90 requested changes

2024-08-20 14:26 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioTokenItemView.swift
> +                        if viewModel.hasPendingTransactions {
а это нам тут точно надо? не уточнял?

2024-08-20 14:26 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioTokenItemView.swift
> +     private var tokenInfoWithPriceView: some View {
удаляй, если не используется, а то диф.засоряет

2024-08-20 14:26 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioTokenItemView.swift
> +    }
можно удалить

2024-08-20 14:26 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioTokenItemView.swift
> +}
это тоже можно удалить, да?

2024-08-20 14:26 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioTokenItemViewModel.swift
>  class MarketsPortfolioTokenItemViewModel: ObservableObject, Identifiable {
не нравится то что получается прям такая жесткая копипаста...

2024-08-20 14:26 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioContainerContextActionsProvider.swift
> +        return filterAvailableTokenActions(contextActions)
и тут тоже жесткая копипаста. Мне совсем не нравится это все. Напиши, пожалуйста, почему нельзя это сейчас вынести в отдельную утилиту. Думаю куа придется все равно тестировать главную и если они будут тестить - надо сразу почище все сделать, чтобы потом не возвращаться к этому вопросу...

2024-08-20 14:26 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioContainerContextActionsProvider.swift
> +    }
думаю это обязанность вью модели заниматься обработкой действий или же отдельного роутера. У этой сущности вообще странное название, которое не дает понять что эта сущность должна делать...

2024-08-20 14:26 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioContainerViewModel.swift
> +    }
это все можно вынести в отдельный маппер

2024-08-20 14:29 UTC, skibinalexander commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioContainerContextActionsProvider.swift
> +        return filterAvailableTokenActions(contextActions)
> и тут тоже жесткая копипаста. Мне совсем не нравится это все. Напиши, пожалуйста, почему нельзя это сейчас вынести в отдельную утилиту. Думаю куа придется все равно тестировать главную и если они будут тестить - надо сразу почище все сделать, чтобы потом не возвращаться к этому вопросу...

Как раз хотел обсудить на звонке, что лучше трогать, а что не стоит

2024-08-20 14:29 UTC, skibinalexander commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioContainerContextActionsProvider.swift
> +    }
> думаю это обязанность вью модели заниматься обработкой действий или же отдельного роутера. У этой сущности вообще странное название, которое не дает понять что эта сущность должна делать...

Окей, посмотрю

2024-08-20 14:30 UTC, skibinalexander commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioContainerViewModel.swift
> +    }
> это все можно вынести в отдельный маппер

Да окей, также хотел обсудить

2024-08-21 05:47 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioContainerView.swift
> +        if viewModel.showQuickAction, let tokenItemViewModel = viewModel.tokenItemViewModels.first {
думаю эту штуку лучше сразу переделать, на звонке же обсуждали, что при тапе будут разворачиваться действия для каждого токена. Так что при ситуации 1 токена - ячейка сразу развернута. Но это надо в начале уточнить в канале и объяснить что на это тоже надо время

2024-08-21 05:47 UTC, Andoran90 commented on Tangem/Common/TokenActions/TokenActionContextBuilder.swift
> +}
думаю это можно сделать структурой, тут ничего такого нет, чтобы оно было классом.

2024-08-21 05:47 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioContainerViewModel.swift
> +    }
а почему это не вынес тоже в фабрику? Думаю в фабрику надо передать массив `WalletModel` и обратно вернуть сразу уже целевые `MarketsPortfolioTokenItemViewModel`, чтобы вся логика маппинга ушла в фабрику, а то какие-то полумеры получаются

2024-08-21 18:58 UTC, skibinalexander commented
![IMG_5E6F454D2260-1](https://github.com/user-attachments/assets/94d031f0-5ef0-4e80-8cdf-1f3d0f563528)
![IMG_AD159F3A1B79-1](https://github.com/user-attachments/assets/8757cab2-8702-44e5-b100-6b92add2089c)

2024-08-21 18:59 UTC, skibinalexander commented on Tangem/Common/TokenActions/TokenActionContextBuilder.swift
> +struct TokenActionContextBuilder {
@Andoran90 как и говорили отдельный билдер структурой

2024-08-21 18:59 UTC, skibinalexander commented on Tangem/Common/TokenItemInfo/TokenItemInfoProviderFactory.swift
> +struct TokenItemInfoProviderFactory {
Обсудили с @Andoran90 фабрика панадобится в дальнейшем

2024-08-21 19:00 UTC, skibinalexander commented on Tangem/Common/TokenItemInfo/TokenItemType.swift
> +enum TokenItemType: Equatable {
Нужно для унификации логики с главной, потребуется дальше

2024-08-21 19:00 UTC, skibinalexander commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioContainerView.swift
> +        if !viewModel.quickActions.isEmpty, let tokenItemViewModel = viewModel.tokenItemViewModels.first {
Изменения из-за особенности требований UI под 3 действия

2024-08-21 19:01 UTC, skibinalexander commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioContainerViewModel.swift
> +    private var coinModel: CoinModel?
Нужна модель целиком, чтобы знать о сетях и об id

2024-08-21 19:01 UTC, skibinalexander commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioContainerViewModel.swift
> -        updateTokenList()
Список строим после того как пришли токен листы

2024-08-21 19:02 UTC, skibinalexander commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioContainerViewModel.swift
> +        Publishers.MergeMany(publishers)
Получаем обновления токен листов

2024-08-21 19:02 UTC, skibinalexander commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioContainerViewModel.swift
> -        let canExchange = userWalletModel.config.isFeatureVisible(.exchange)
Ушло в билдер отдельный

2024-08-21 19:02 UTC, skibinalexander commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioContainerViewModel.swift
> +    func didTapContextAction(_ action: TokenActionType, for walletModelId: WalletModelId, with userWalletId: UserWalletId) {
Изменения в связи с переездом на TokenInfoProvider

2024-08-21 19:02 UTC, skibinalexander commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioTokenItemFactory.swift
> +struct MarketsPortfolioTokenItemFactory {
Обсудили с @Andoran90 чтобы логика была похожа с главной

2024-08-21 19:03 UTC, skibinalexander commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioTokenItemView.swift
> +                        if viewModel.hasPendingTransactions {
> а это нам тут точно надо? не уточнял?

Уточню спасибо

2024-08-21 19:03 UTC, skibinalexander commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioTokenItemView.swift
> -    private var iconView: some View {
UI теперь как на главной

2024-08-21 19:03 UTC, skibinalexander commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioTokenItemViewModel.swift
>  class MarketsPortfolioTokenItemViewModel: ObservableObject, Identifiable {
> не нравится то что получается прям такая жесткая копипаста...

Обсудили, можно зарезолвить

2024-08-22 12:30 UTC, Andoran90 submitted a review, later dismissed

2024-08-22 12:30 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioContainerViewModel.swift
> +    private lazy var tokenActionContextBuilder: TokenActionContextBuilder = .init(userWalletModels: walletDataProvider.userWalletModels)
nit: такие билдеры можно создавать по месту требования и не хранить их в памяти лишнее время

2024-08-22 13:32 UTC, skibinalexander commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioContainerViewModel.swift
> +    private lazy var tokenActionContextBuilder: TokenActionContextBuilder = .init(userWalletModels: walletDataProvider.userWalletModels)
Ок почищу в мр которые будут

2024-08-22 18:43 UTC, tureck1y commented
> WIP - для просмотра еще не готово. Описание подробное и UI приложу как будет готово

забыл приложить

2024-08-23 05:54 UTC, skibinalexander commented
> > WIP - для просмотра еще не готово. Описание подробное и UI приложу как будет готово
> 
> 
> 
> забыл приложить

Скрины есть , вместо описания прокоменнтил строчки по МР

2024-08-23 06:25 UTC, skibinalexander commented
> > > WIP - для просмотра еще не готово. Описание подробное и UI приложу как будет готово
> > 
> > 
> > забыл приложить
> 
> Скрины есть , вместо описания прокоменнтил строчки важные по МР

2024-08-23 06:30 UTC, skibinalexander commented
@tureck1y давай не буду мучать по строчкам - допишу.

Вообщем, сделал динамическое обновление портфолио. Основная сложность и отличие от главной, такая, что мы бегаем не по одному выбранному кошельку, а сразу по всем UserWalletModel. 

Поэтому есть Publishers.MergeMany по токен листам, которые кидают обновление листа токенов и тем самым перестраивают список портфолио.

При этом есть фильтрация по coinId и поддерживаемым блокчейнам по entry.

Стиль и Техническая реализация и UI практически не отличается от главной, но дублирующий код решили пока не править, чтобы не сломать главную, а только действительно повторяющий код, вынесли в сущности и положили в common, чтобы мистер Сон в рамках отдельного рефака, объединил с главной.

Других особенностей работы бизнес логики нет.

Также в рамках отдельно рефака, решили с @Andoran90 убрать коин модель, а работать с id и с NetworkModel, это будет отдельной задачей https://tangem.atlassian.net/browse/IOS-7659

2024-08-23 12:29 UTC, tureck1y requested changes

2024-08-23 12:29 UTC, tureck1y commented on Tangem/Common/TokenActions/TokenActionContextBuilder.swift
> +        self.userWalletModels = userWalletModels
предлагаю все же инжектить сюда репозиторий и брать userWalletModels из него, в таком случае, этот ко будет правильно работать всегда. Сейчас же может быть ситуация, данные могут рахойтись с репозиторием, если эта структура будет жить долгий промежуток времени

2024-08-23 12:29 UTC, tureck1y commented on Tangem/Common/TokenItemInfo/TokenItemInfoProviderFactory.swift
> +struct TokenItemInfoProviderFactory {
Да маппером мне кажется можно было обозвать TokenItemInfoProviderMapper

2024-08-23 12:29 UTC, tureck1y commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioContainerViewModel.swift
> +    private lazy var tokenActionContextBuilder: TokenActionContextBuilder = .init(userWalletModels: walletDataProvider.userWalletModels)
вот как раз и пример косяка, пошел, в репе удалили userWallet и все сломается. Нужно еще и walletDataProvider.userWalletModels перепроверить. Все же источником правды для userWalletModels должен выступать репозиторий, а дальше уже можно филттры накладывать

2024-08-23 12:29 UTC, tureck1y commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioContextActions.swift
> +    func buildContextActions(for walletModelId: WalletModelId, with userWalletId: UserWalletId) -> [TokenActionType]
предлагаю убрать for и with. 
buildContextActions(walletModelId: id1, userWalletId: id2) в точке вызова будет гораздо понятнее, чем buildContextActions(for: id1, with: id2)

2024-08-23 12:29 UTC, tureck1y commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioContextActions.swift
> +    func buildContextActions(for walletModelId: WalletModelId, with userWalletId: UserWalletId) -> [TokenActionType]
метода ниже тоже касается

2024-08-23 16:02 UTC, skibinalexander commented on Tangem/Common/TokenItemInfo/TokenItemInfoProviderFactory.swift
> +struct TokenItemInfoProviderFactory {
✅

2024-08-23 16:02 UTC, skibinalexander commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioContextActions.swift
> +    func buildContextActions(for walletModelId: WalletModelId, with userWalletId: UserWalletId) -> [TokenActionType]
Да, согласен

2024-08-23 16:06 UTC, skibinalexander commented on Tangem/Common/TokenActions/TokenActionContextBuilder.swift
> +        self.userWalletModels = userWalletModels
> предлагаю все же инжектить сюда репозиторий и брать userWalletModels из него, в таком случае, этот ко будет правильно работать всегда. Сейчас же может быть ситуация, данные могут рахойтись с репозиторием, если эта структура будет жить долгий промежуток времени

Убрал в виду отсутствия необходимости все таки, перенес на потребителя

2024-08-23 16:06 UTC, skibinalexander commented
@tureck1y вроде как все зарезолвил

2024-08-23 16:11 UTC, tureck1y approved these changes
Проверь пожалуйста в целом по маркетсам, что userWalletModels нигде не кешируются. Пользователь может в любой момент времени добавить или удалить кошелек, а маркетсы(портфолио) должны на это адекватно реагировать

2024-08-23 16:15 UTC, skibinalexander commented
> Проверь пожалуйста в целом по маркетсам, что userWalletModels нигде не кешируются. Пользователь может в любой момент времени добавить или удалить кошелек, а маркетсы(портфолио) должны на это адекватно реагировать

Ага пробегусь, в целом понятно да, что вычисляемо всегда должно быть, для этого у нас есть WalletModelProvider

2024-08-26 07:18 UTC, Andoran90 approved these changes

2024-08-26 07:18 UTC, merged