IOS-7659: [Markets] Add filter by network ids
tangem/tangem-app-ios-old pull request #3703
Opened 2024-08-23 16:27 UTC by skibinalexander

Рефакторинг понадобился из-за того, что маппер у CoinModel ничего не знает о конфигацих supported blockchains
Для v2 конфига другие кривые при одинаковых networkId, поэтому требуется фильтровать именно таким образом.

Из изменений:

1. Уходим от использования CoinModel, оперируя только CoinId и NetworkModel
2. Прокидываем в портфолио и выбор токенов соотвественно
3. Берем фильтруем нужные NetworkId и строим TokenItem только исходя из SupportedBlockchains только конкретного config UserWalletModel

2024-08-24 17:34 UTC, tureck1y submitted a review, later dismissed
бегло посмотрел

2024-08-24 18:23 UTC, skibinalexander commented
> бегло посмотрел

Я подожду мистера Сона

2024-08-26 06:54 UTC, Andoran90 requested changes

2024-08-26 06:54 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioContainerViewModel.swift
> +    struct LoadableState {
плохое название, ничего не понятно. Вообще, надо убрать эту сущность, она не нужна

2024-08-26 06:54 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioContainerViewModel.swift
> +    }
и вот эту функцию тоже надо убрать. Сейчас у скелетона портфолио отдельная вьюха, так что эта вью модель может создаваться как и все остальные модели, когда инфа загрузилась и тогда не нужна будет вообще эта функция и в инициализатор можно просто передать строку и массив моделей сети.

2024-08-26 06:54 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenMarketsDetails/TokenMarketsDetailsViewModel.swift
> -        portfolioViewModel?.updateState(with: model.coinModel)
вот убрать это и перенести инициализацию в `makeBlocksViewModels`

2024-08-26 07:59 UTC, skibinalexander commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioContainerViewModel.swift
> +    }
Да , согласен , спасибо, не учел этого. Забыл что у нас так теперь

2024-08-26 13:10 UTC, Andoran90 approved these changes

2024-08-26 19:21 UTC, tureck1y approved these changes
только тесты упали

2024-08-26 22:10 UTC, merged