iOS 1603 add total sum
tangem/tangem-app-ios-old pull request #371
Opened 2022-05-12 15:45 UTC by gre4ixin

2022-05-13 04:59 UTC, tureck1y requested changes
Давай обсудим реализацию. Есть ощущение, что можно сделать проще, например прокидывать в эту новую вьюху сразу суммарный баланс и биндинг на refreshing, вероятно я упускаю какие-то тонкости.

2022-05-13 04:59 UTC, tureck1y commented on Tangem/Main/TotalSumBalanceView.swift
> +class TotalSumBalanceViewModel: ObservableObject {
Разнеси пожалуйста по разным файлам модель и вьюху

2022-05-13 04:59 UTC, tureck1y commented on Tangem/Main/MainView.swift
> +                            TotalSumBalanceView(viewModel: TotalSumBalanceViewModel(currencyRateService: viewModel.assembly.services.ratesService,
сборка вьюмоделей в Assembly, а тут просто вызов assembly.makeTotalSumBalanceViewModel ...

2022-05-13 06:04 UTC, megakoko requested changes

2022-05-13 06:04 UTC, megakoko commented on Tangem/Assets/Assets.xcassets/tangemArrowDown.imageset/Contents.json
> +{
В PDF удобнее

2022-05-13 06:04 UTC, megakoko commented on Tangem/Common/Localizations/de.lproj/Localizable.strings
> +"main_page_balance" = "TOTAL BALANCE";
Лучше обычным регистром писать текстовки и в коде делать `uppercase`.

2022-05-13 06:04 UTC, megakoko commented on Tangem/Common/Extensions/Color+.swift
> +    }
Если есть существующие цвета которые хотя бы примерно похожи на нужные, лучше использовать их, а не добавлять новые.

2022-05-13 06:04 UTC, megakoko commented on Tangem/Main/MainViewModel.swift
> +              let walletModels = cardModel.walletModels else { return }
else и return надо перенести на новые строки

2022-05-13 06:04 UTC, megakoko commented on Tangem/Main/TotalSumBalanceView.swift
> +    func shimmerOff() {
Если функция делает что-то, надо ее называть глаголом.

2022-05-13 06:04 UTC, megakoko commented on Tangem/Main/TotalSumBalanceView.swift
> +    @Published var countBalance: String = ""
"Количество баланса"?

2022-05-13 06:04 UTC, megakoko commented on Tangem/Main/TotalSumBalanceView.swift
> +            } receiveValue: { currencyes in
currencies

2022-05-13 06:04 UTC, megakoko commented on Tangem/Main/TotalSumBalanceView.swift
> +                guard let symbol = currencyes.first(where: { $0.code == self.currencyRateService.selectedCurrencyCode }) else { return }
Возвращается тип CurrenciesResponse.Currency, надо назвать соответствующе. Symbol — это обычно символ валюты, $, €, etc.

2022-05-13 06:04 UTC, megakoko commented on Tangem/Main/TotalSumBalanceView.swift
> +                    count += token.fiatValue
count — обычно используется для подсчета чего-то, обычно целочисленных значений. Если суммируешь fiatValue в переменную, можно назвать ее totalFiatValue / fiatValueSum.

2022-05-13 06:04 UTC, megakoko commented on Tangem/Main/TotalSumBalanceView.swift
> +    @Published var countBalance: String = ""
Могу предложить totalBalanceFormatted или что-то подобное.

2022-05-13 06:04 UTC, megakoko commented on Tangem/Main/TotalSumBalanceView.swift
> +    @Published var shimmer: Bool = false
Лучше переименовать в isLoading.

2022-05-13 06:04 UTC, megakoko commented on Tangem/Main/TotalSumBalanceView.swift
> +    var currencyRateService: CurrencyRateService
Тут все публичные переменные используются извне или можно часть сделать private?

2022-05-13 06:04 UTC, megakoko commented on Tangem/Main/TotalSumBalanceView.swift
> +            .frame(width: UIScreen.main.bounds.width - 32, height: 101)
Можно ли тут обойтись без использования явной ширины экрана? 
Можно не фиксировать высоту, а позволить содержимому самому выбрать нужную основываясь на spacing'ах и padding'ах?

2022-05-13 06:04 UTC, megakoko commented on Tangem/Main/TotalSumBalanceView.swift
> +//struct TotalSumBalanceView_Previews: PreviewProvider {
Если превью рабочее, то лучше раскомментировать. Если не нужно — удалить.

2022-05-13 06:17 UTC, megakoko commented on Tangem/Assets/Assets.xcassets/tangemArrowDown.imageset/Contents.json
> +{
В случае замены надо будет менять 1 файл вместо 3.

2022-05-13 06:18 UTC, megakoko commented on Tangem/Common/Localizations/de.lproj/Localizable.strings
> +"main_page_balance" = "TOTAL BALANCE";
Чтобы например можно было использовать текстовки в нескольких местах или копировать перевод в другое место.

2022-05-16 08:52 UTC, tureck1y approved these changes, later dismissed

2022-05-16 09:06 UTC, megakoko commented on Tangem/Main/TotalSumBalance/TotalSumBalanceView.swift
> +        .frame(height: 120)
Нельзя прибивать гвоздями высоту таких сложных вьюх. Они должны выбирать размер сами, на основе размера своих компонентов, спейсингов и паддингов.

Иначе при внесении изменений в структуру вьюхи все пойдет по бороде и надо будет придумывать новые магические числа и обновлять `.frame(height: 120)` и `.frame(height: 101)`.

2022-05-16 09:12 UTC, megakoko commented on Tangem/Main/TotalSumBalance/TotalSumBalanceView.swift
> +    @Environment(\.screenSize) var screenSize: CGRect
Это как-то используется?

2022-05-16 09:12 UTC, megakoko commented on Tangem/Main/TotalSumBalance/TotalSumBalanceViewModel.swift
> +                var countFiatValue: Decimal = 0.0
Переименуй в totalFiatValue, пожалуйста.

2022-05-16 09:19 UTC, gre4ixin commented on Tangem/Main/TotalSumBalance/TotalSumBalanceViewModel.swift
> +                var countFiatValue: Decimal = 0.0
переименовал

2022-05-16 09:19 UTC, gre4ixin commented on Tangem/Main/TotalSumBalance/TotalSumBalanceView.swift
> +    @Environment(\.screenSize) var screenSize: CGRect
больше нет, убрал из View

2022-05-16 09:20 UTC, gre4ixin commented on Tangem/Main/TotalSumBalance/TotalSumBalanceView.swift
> +        .frame(height: 120)
поправил и убрал frame

2022-05-16 09:23 UTC, megakoko commented on Tangem/Common/Extensions/Environment+.swift
> +private struct ScreenSizeEnvironmentKey: EnvironmentKey {
Это тогда тоже можно удалить

2022-05-16 09:32 UTC, megakoko approved these changes

2022-05-16 09:39 UTC, tureck1y approved these changes

2022-05-16 09:39 UTC, merged