IOS-7772 [Markets] make expanded quick actions
tangem/tangem-app-ios-old pull request #3728
Opened 2024-08-29 11:20 UTC by skibinalexander

Сделаны быстрые действия по новым требованиям. Из особенностей только переделанный UI. 

![IMG_E0D585ED7350-1](https://github.com/user-attachments/assets/a634a9d4-dddb-498c-b794-e3184b4e2d75)
![Simulator Screenshot - iPhone 15 - 2024-08-29 at 16 20 32](https://github.com/user-attachments/assets/2243efd6-2efd-451e-864d-bd9befe9e8da)

2024-08-29 21:41 UTC, tureck1y approved these changes, later dismissed

2024-08-30 11:59 UTC, Andoran90 requested changes

2024-08-30 11:59 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioTokenItemView.swift
> +        .padding(.vertical, 15)
15 не ставим, ставь 14

2024-08-30 11:59 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioTokenItemView.swift
> +        .frame(maxWidth: .infinity)
вообще выглядит так, что можно сделать:
```suggestion
            Rectangle()
                .fill(Colors.Stroke.primary)
                .frame(width: 1, height: 16)
                .padding(.vertical, 4)
                .padding(.leading, 18)
```

2024-08-30 11:59 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioTokenItemView.swift
> +                .padding(6)
выгрузи из дизайна, пожалуйста, правильные иконки. В `actionType` лежат размером 20,  а в дизе указаны 12. Я за то чтобы не рескейлить иконки. Выгрузи просто `arrowDown12` и заюзай их тут, тогда и паддинги будут понятные, а не 6, которого в дизайне нет.

2024-08-30 11:59 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioTokenItemView.swift
> +                .padding(.vertical, 3)
уже много раз обсуждали, не используй нечетные значения. Это во первых, а во вторых, зачем тут паддинг? размер вьюхи должен определяться за счет блока с текстом. Вдобавок он может становиться ещё больше при увеличенных шрифтах

2024-08-30 11:59 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioTokenItemView.swift
> +                .padding(.vertical, 3)
и вообще можно следующий паддинг `.padding(.horizontal, 2)` заменить на `.padding(2)`

2024-08-30 11:59 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioTokenItemView.swift
> +        .frame(maxWidth: .infinity)
а ещё выглядит так, будто эта полоска должна быть длинней, если текст описания действия на 2 строки, т.к. отступы начинают варьироваться. Или это обсуждали и черточка всегда фиксированной высоты?

2024-08-30 11:59 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioTokenItemView.swift
> +            .offset(y: -12)
а зачем оффсет?

2024-08-30 11:59 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioTokenItemView.swift
> +                        .frame(width: 12)
можно заюзать: `FixedSpacer(width: 12)`

2024-08-30 11:59 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioTokenItemView.swift
> +                if index == viewModel.contextActions.count {
а индекс же никогда не будет равен количеству значений

2024-08-30 12:28 UTC, skibinalexander commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioTokenItemView.swift
> +                .padding(.vertical, 3)
Да я за четные значения ... баги прилетают потом, но зафиксировал , буду четные 👋

2024-08-30 12:34 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioTokenItemView.swift
> +                .padding(.vertical, 3)
ну это тоже говорили, надо дизайнерам писать, чтобы правили и не делали такие отступы, но в данном случае - отступ по вертикали вообще не нужен, т.к. текст контроллирует высоту

2024-09-01 19:34 UTC, skibinalexander commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioTokenItemView.swift
> +                .padding(.vertical, 3)
> ну это тоже говорили, надо дизайнерам писать, чтобы правили и не делали такие отступы, но в данном случае - отступ по вертикали вообще не нужен, т.к. текст контроллирует высоту

Да согласен

2024-09-01 19:35 UTC, skibinalexander commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioTokenItemView.swift
> +        .frame(maxWidth: .infinity)
> а ещё выглядит так, будто эта полоска должна быть длинней, если текст описания действия на 2 строки, т.к. отступы начинают варьироваться. Или это обсуждали и черточка всегда фиксированной высоты?

Черточка же фиксированной высоты

2024-09-01 19:36 UTC, skibinalexander commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioTokenItemView.swift
> +            .offset(y: -12)
> а зачем оффсет?

Задумка по дизайну

2024-09-01 19:41 UTC, skibinalexander commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioTokenItemView.swift
> +                .padding(6)
> выгрузи из дизайна, пожалуйста, правильные иконки. В `actionType` лежат размером 20, а в дизе указаны 12. Я за то чтобы не рескейлить иконки. Выгрузи просто `arrowDown12` и заюзай их тут, тогда и паддинги будут понятные, а не 6, которого в дизайне нет.

Переделал , дизайн раньше был другой ...

2024-09-01 20:02 UTC, skibinalexander commented
https://github.com/user-attachments/assets/1d1b5b4e-fc6a-468f-82ef-1762c936202f

2024-09-02 08:33 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioTokenItemView.swift
> +        .frame(maxWidth: .infinity)
она фиксированная, потому что в дизайне не указан вариант с двухстрочной текстовкой, когда отступы вокруг иконки становятся больше

2024-09-02 09:34 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioTokenItemView.swift
> +                .frame(size: .init(bothDimensions: 12))
говорю же, это не работает. Сравни нормально что в приложении получается и что в дизайне. В приложении иконки значительно больше. В чем проблема добавить 3 иконки?

2024-09-02 09:34 UTC, Andoran90 commented on Tangem/Common/TokenActions/TokenContextActionsBuilder.swift
> +    }
зачем полностью скопированная функция, когда отличается только фильтр? этот фильтр можно добавить опциональным в первую функцию и не копипастить кучу кода.

2024-09-02 09:34 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioContainerViewModel.swift
> +        let availableActions = viewModel.contextActions.filter { actionsFilter.contains($0) }
а зачем тут фильтр, если в билдере есть фильтрация?

2024-09-02 09:34 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioContainerViewModel.swift
> +            sortedFilter: [.buy, .exchange, .receive]
вообще это все выглядит так, что можно в билдере не делать никакие правки, ты в билдере запросил все действия, которые доступны, а во вью модели уже отсортировал и положил только то что надо. Или же открывать создание только базовых действий и опять же фильтровать во вью модели, а не в билдере, т.к. это специфика вью модели, а не билдера

2024-09-02 09:49 UTC, skibinalexander commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioTokenItemView.swift
> +                .frame(size: .init(bothDimensions: 12))
> говорю же, это не работает. Сравни нормально что в приложении получается и что в дизайне. В приложении иконки значительно больше. В чем проблема добавить 3 иконки?

Да окей, надо обсудить, я сначала добавил их, но есть нюанс, коротенько надо проговорить как лучше их привязать к enum

2024-09-02 09:50 UTC, skibinalexander commented on Tangem/Common/TokenActions/TokenContextActionsBuilder.swift
> +    }
> зачем полностью скопированная функция, когда отличается только фильтр? этот фильтр можно добавить опциональным в первую функцию и не копипастить кучу кода.

Да окей, было 2 варианта, не хочет просто портить интерфейс для специфичного места

2024-09-02 09:51 UTC, skibinalexander commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioContainerViewModel.swift
> +            sortedFilter: [.buy, .exchange, .receive]
> вообще это все выглядит так, что можно в билдере не делать никакие правки, ты в билдере запросил все действия, которые доступны, а во вью модели уже отсортировал и положил только то что надо. Или же открывать создание только базовых действий и опять же фильтровать во вью модели, а не в билдере, т.к. это специфика вью модели, а не билдера

Тут согласен, искал более простой вариант, чтобы не перекладывать в секции а прям фильтровать исходный enum ок посмотрю

2024-09-02 16:26 UTC, skibinalexander commented
@tureck1y пока не трать время, надо ревью мистера Сна подождать

2024-09-02 19:18 UTC, tureck1y approved these changes, later dismissed

2024-09-03 06:33 UTC, Andoran90 submitted a review, later dismissed

2024-09-03 06:33 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioContainerViewModel.swift
> +        let baseAcctions = TokenContextActionsBuilder().makeBaseContextActions(
очепяточка
``` suggestion
        let baseActions = TokenContextActionsBuilder().makeBaseContextActions(
```

2024-09-03 06:35 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioContainerViewModel.swift
> +        return filteredActions.filter { baseAcctions.contains($0) }
```suggestion
        return filteredActions.filter { baseActions.contains($0) }
```

2024-09-03 08:17 UTC, skibinalexander commented
@tureck1y @Andoran90 только поправил опечатку, извините

2024-09-03 08:29 UTC, Andoran90 approved these changes

2024-09-03 09:05 UTC, tureck1y approved these changes

2024-09-03 11:17 UTC, merged