IOS-7689 [Markets] make analytics events
tangem/tangem-app-ios-old pull request #3747
Opened 2024-09-03 18:14 UTC by skibinalexander

Переделаны ивенты аналитики. Сделаны по таблице

2024-09-04 06:21 UTC, Andoran90 requested changes

2024-09-04 06:21 UTC, Andoran90 commented on Tangem/Modules/Markets/Providers/MarketsListDataFilterProvider.swift
> -        Analytics.log(event: .marketsTokenPeriod, params: [.source: interval.rawValue])
хм, странно, а тут разве не надо отправлять так же аналитику по периоду и добавить сортировку?

2024-09-04 06:21 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/HistoryChart/MarketsHistoryChartViewModel.swift
> +                .source: Analytics.ParameterValue.chart.rawValue,
а почему пропал `Token`? он почти во всех событиях должен быть

2024-09-04 06:21 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/HistoryChart/MarketsHistoryChartViewModel.swift
> +            Analytics.log(.marketsChartDataError, params: [.source: .chart])
вот это тоже странно, думаю тут надо добавлять токен, чтобы знать по каким токенам чаще всего не удается загрузить график

2024-09-04 06:21 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioContainerViewModel.swift
>              coordinator.openSend(for: walletModel, with: userWalletModel)
забыли удалить эту и другие навигации, которые не используются больше. Надо бы, наверное, почистить, не в этой задаче

2024-09-04 06:21 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenMarketsDetails/TokenMarketsDetailsViewModel.swift
> +        Analytics.log(event: .marketsChartScreenOpened, params: analyticsParams)
зачем это событие? оно же дублирует то что отправляется из `MultiWalletMainContentViewModel`, `SingleWalletMainContentViewModel` и `TokenDetailsViewModel` только тут не правильно отправляется инфа об источнике. Надо перенести отправку этого события либо в `MarketsViewModel` либо в `MarketsCoordinator`, думаю лучше в первое перед отправкой команды в координатор на открытие экрана деталки токена маркетсов

2024-09-04 06:21 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenMarketsDetails/TokenMarketsDetailsViewModel.swift
> +    func makeAnalyticsViewModel(using model: TokenMarketsDetailsModel) {
тут не создается никакая вью модель, а отправляется аналитика. Вообще немного странная аналитика, т.к. некоторые блоки не везде присутствуют это считается ошибкой? Или у нас на старте будет по каждому токену инсайты?
```suggestion
    func sendBlocksAnalyticsErrors(using model: TokenMarketsDetailsModel) {
```

2024-09-04 06:21 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenMarketsDetails/TokenMarketsDetailsViewModel.swift
> +        }
странная аналитика) тут просто прилетят события, что нет какого-то блока, но не понятно к какой монете это относится, а ещё это будет куча разрозненных событий. Думаю тут лучше отправить 1 событие, в котором указать для какого токена отсутствуют какие блоки...

2024-09-04 06:53 UTC, skibinalexander commented on Tangem/Modules/Markets/Providers/MarketsListDataFilterProvider.swift
> -        Analytics.log(event: .marketsTokenPeriod, params: [.source: interval.rawValue])
<img width="1201" alt="Screenshot 2024-09-04 at 11 46 07" src="https://github.com/user-attachments/assets/b55cc3ee-0eb5-4c70-8e71-71f8fe8cacb5">

Параметр preiod на этом экране переехал, на экран списка токенов

2024-09-04 06:57 UTC, skibinalexander commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/HistoryChart/MarketsHistoryChartViewModel.swift
> +                .source: Analytics.ParameterValue.chart.rawValue,
> а почему пропал `Token`? он почти во всех событиях должен быть

Спасибо, давно сделал, перенес не правильно

2024-09-04 06:58 UTC, skibinalexander commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/HistoryChart/MarketsHistoryChartViewModel.swift
> +            Analytics.log(.marketsChartDataError, params: [.source: .chart])
> вот это тоже странно, думаю тут надо добавлять токен, чтобы знать по каким токенам чаще всего не удается загрузить график

<img width="1261" alt="Screenshot 2024-09-04 at 11 57 54" src="https://github.com/user-attachments/assets/e2582fa5-4606-4e61-a1da-e0436dba2116">

2024-09-04 06:59 UTC, skibinalexander commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioContainerViewModel.swift
>              coordinator.openSend(for: walletModel, with: userWalletModel)
> забыли удалить эту и другие навигации, которые не используются больше. Надо бы, наверное, почистить, не в этой задаче

Я почищу без проблем, но я чего - то думал , а вдруг добавятся действия, придется впиливать ... Вообщем тут как скажешь , согласен и с тем, что лишнее сбивает с толку, но и не гибко относительно enum

2024-09-04 07:00 UTC, skibinalexander commented on Tangem/Modules/Markets/TokenMarketsDetails/TokenMarketsDetailsViewModel.swift
> +    func makeAnalyticsViewModel(using model: TokenMarketsDetailsModel) {
> тут не создается никакая вью модель, а отправляется аналитика. Вообще немного странная аналитика, т.к. некоторые блоки не везде присутствуют это считается ошибкой? Или у нас на старте будет по каждому токену инсайты?

По названию согласен, не обратил внимание. По наполнению 
<img width="766" alt="Screenshot 2024-09-04 at 12 00 36" src="https://github.com/user-attachments/assets/328117de-844a-4def-a6ad-0640a02b559e">

2024-09-04 07:01 UTC, skibinalexander commented on Tangem/Modules/Markets/TokenMarketsDetails/TokenMarketsDetailsViewModel.swift
> +        }
> странная аналитика) тут просто прилетят события, что нет какого-то блока, но не понятно к какой монете это относится, а ещё это будет куча разрозненных событий. Думаю тут лучше отправить 1 событие, в котором указать для какого токена отсутствуют какие блоки...

Я такого же мнение, но делал по табличке, проговорю с Лёшей, надо вчера обсудить конечно

2024-09-04 17:08 UTC, skibinalexander commented
@Andoran90 Согласовываю с Лёшей твои замечания, жду ответов по Аналитики. Что точно к исправлению внес изменения. @tureck1y пока не торопись, закончу ревью с мистером Сном

2024-09-05 12:46 UTC, tureck1y commented on Tangem/Modules/Markets/TokenMarketsDetails/TokenMarketsDetailsViewModel.swift
> +    func sendBlocksAnalyticsErrors(using model: TokenMarketsDetailsModel) {
странный метод, нет ретурнов, это так задумано спамить событиями? Может лучше на свитчкейс переделать, сложно

2024-09-05 12:46 UTC, tureck1y commented on Tangem/Modules/Markets/UIComponents/MarketsRaitingHeaderViewModel.swift
> +            .dropFirst()
Нужно убедиться, что этологику никакую не ломает

2024-09-05 12:54 UTC, skibinalexander commented on Tangem/Modules/Markets/UIComponents/MarketsRaitingHeaderViewModel.swift
> +            .dropFirst()
Проверит , все окей

2024-09-05 12:55 UTC, skibinalexander commented on Tangem/Modules/Markets/TokenMarketsDetails/TokenMarketsDetailsViewModel.swift
> +    func sendBlocksAnalyticsErrors(using model: TokenMarketsDetailsModel) {
Передал лёше жду ответы

2024-09-06 20:25 UTC, skibinalexander commented
Опускаю в драфт :( что-то есть непонятные вещи

2024-09-11 06:24 UTC, skibinalexander commented
@Andoran90 готово к ревью

2024-09-11 09:18 UTC, tureck1y submitted a review, later dismissed

2024-09-11 09:57 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenMarketsDetails/TokenMarketsDetailsViewModel.swift
> +                .token: tokenInfo.symbol.uppercased(),
почему где-то `uppercased` а где-то нет? важно чтобы везде отправлялись одинаковые данные, иначе статистика будет жопная

2024-09-11 10:57 UTC, skibinalexander commented on Tangem/Modules/Markets/TokenMarketsDetails/TokenMarketsDetailsViewModel.swift
> +                .token: tokenInfo.symbol.uppercased(),
> почему где-то `uppercased` а где-то нет? важно чтобы везде отправлялись одинаковые данные, иначе статистика будет жопная

Пробегусь проставлю, конечно оно по умолчанию ожидаем с большой, но лучше в одном формате да

2024-09-11 11:34 UTC, Andoran90 submitted a review, later dismissed

2024-09-11 13:48 UTC, tureck1y approved these changes, later dismissed

2024-09-12 14:14 UTC, skibinalexander commented
Пофиксил конфликты ...

2024-09-12 14:51 UTC, Andoran90 approved these changes

2024-09-12 16:16 UTC, tureck1y approved these changes

2024-09-12 16:16 UTC, merged