IOS-7278 Added Sei blockchain into app
tangem/tangem-app-ios-old pull request #3790
Opened 2024-09-09 08:25 UTC by Vyachesl0ve

МР в BSDK https://github.com/tangem/blockchain-sdk-swift/pull/828

2024-09-09 13:55 UTC, tureck1y commented on Tangem/App/Models/Config/SupportedBlockchains.swift
> +            .sei(testnet: false),
Надо положить в testableBlockchains(), под тоггл, а тестнет остается там где есть. По умолчанию всегда под тоггл кладем

2024-09-09 14:26 UTC, amuraveinik requested changes

2024-09-09 14:26 UTC, amuraveinik commented on Tangem/App/Services/ExchangeService/MoonPayService.swift
> +        case .filecoin: return "fil"
Дубликат?

2024-09-09 14:27 UTC, AlekseiMuraveinik1 commented on Tangem/App/Services/ExchangeService/MoonPayService.swift
> +        case .filecoin: return "fil"
Вероятно поэтому тесты упали

2024-09-09 15:21 UTC, amuraveinik submitted a review, later dismissed

2024-09-09 20:13 UTC, tureck1y approved these changes, later dismissed

2024-09-10 10:13 UTC, tureck1y approved these changes

2024-09-10 10:14 UTC, merged