IOS-7812 [Staking] Update data on main and token details on staking status change
tangem/tangem-app-ios-old pull request #3793
Opened 2024-09-09 10:02 UTC by fedorov-d

Завязался на паблишер состояния стейкинга в нескольких местах.

2024-09-09 10:04 UTC, Balashov152 submitted a review, later dismissed
вроде норм должно быть

2024-09-09 10:05 UTC, tureck1y commented on Tangem/Modules/Main/MultiWalletMainContent/Views/TokenList/DefaultTokenItemInfoProvider.swift
> +            walletModel.stakingManagerStatePublisher
Не уверен, может лучше сделать внутри WalletModel? Чтобы триггерился walletModel.walletDidChangePublisher?

2024-09-09 10:09 UTC, tureck1y commented on Tangem/Modules/Main/MultiWalletMainContent/Views/TokenList/DefaultTokenItemInfoProvider.swift
> +            walletModel.stakingManagerStatePublisher
Теоретически что-то сломать может конечно, надо будет делить паблишеры на все

2024-09-09 10:13 UTC, tureck1y requested changes
Нужна следующая логика:
- ответ от стейканых балансов не должен тормозить апдейт от апи блокчейна
- нужно предусмотреть, что не у всех есть stakingManager и ничего не заэмитится
- обновлять баланс нужно и на главной и в токен детеилс
- лучше сделать это все под капотом WalletModel

2024-09-09 10:13 UTC, tureck1y commented on Tangem/Common/TokenItemInfo/TokenItemInfoProvider.swift
> +    var isStaked: AnyPublisher<Bool, Never> { get }
isStakedPublisher

2024-09-09 10:13 UTC, tureck1y commented on Tangem/Modules/TokenDetails/TokenDetailsViewModel.swift
> +            walletModel.walletDidChangePublisher,
На главной же тоже нужно анверное балансы обновлять?

2024-09-09 10:57 UTC, fedorov-d commented on Tangem/Modules/TokenDetails/TokenDetailsViewModel.swift
> +            walletModel.walletDidChangePublisher,
так в DefaultTokenItemInfoProvider.swift как раз обновляются, или я что-то не так понял?

2024-09-09 11:04 UTC, fedorov-d commented
> Нужна следующая логика:
> 
> * ответ от стейканых балансов не должен тормозить апдейт от апи блокчейна
> * нужно предусмотреть, что не у всех есть stakingManager и ничего не заэмитится
> * обновлять баланс нужно и на главной и в токен детеилс
> * лучше сделать это все под капотом WalletModel

1. он не будет тормозить, т.к. сначала заэмитится либо notEnabled (если стейкинг выключен для валюты) либо loading
2. в этом случае заэмитит notEnabled
3. существующие правки DefaultTokenItemInfoProvider обновляют на главной TokenDetailsViewModel - в деталях токена
4. тут затронет дофига лишнего, ну и это вещи как будто несильно связанные

2024-09-09 13:11 UTC, Balashov152 commented on Tangem/Modules/TokenDetails/TokenDetailsViewModel.swift
> +            walletModel.walletDidChangePublisher,
да, это как раз для главной провайдер

2024-09-09 13:55 UTC, Andoran90 commented on Tangem/Modules/Main/MultiWalletMainContent/Views/TokenList/DefaultTokenItemInfoProvider.swift
> +            walletModel.stakingManagerStatePublisher
не совсем понимаю смысл завязывать апдейт стейта на стейкинг. Если надо обновить балансы, после загрузки стейкинга - то это можно сделать через `isStakedPublisher`, у тебя как раз есть подписка на него в `TokenItemViewModel` и если надо обновить баланс, то можно делать не `.assign(to: \.isStaked...`, а клоружу написать, в которой будет обновляться баланс.
Или я не понял смысла подвязываться тут на `stakingManagerStatePublisher`, т.к. во вью модель ячейки будет публиковаться последний стейт из `walletDidChangePublisher`

2024-09-11 04:52 UTC, fedorov-d commented on Tangem/Modules/Main/MultiWalletMainContent/Views/TokenList/DefaultTokenItemInfoProvider.swift
> +            walletModel.stakingManagerStatePublisher
да, надо обновить балансы, вроде поправил

2024-09-11 05:58 UTC, Andoran90 approved these changes

2024-09-11 05:58 UTC, Andoran90 commented on Tangem/UIComponents/TokenItemView/TokenItemViewModel.swift
> +                guard let self else { return }
можно через `.withWeakCapture(of: self)`, но не принципиально, у нас тут ещё не было этого расширения, поэтому все по старинке

2024-09-11 09:18 UTC, tureck1y approved these changes

2024-09-11 09:20 UTC, Balashov152 approved these changes

2024-09-11 09:28 UTC, merged