IOS-7947 Hide bottom sheet on logout
tangem/tangem-app-ios-old pull request #3837
Opened 2024-09-12 12:06 UTC by tureck1y

Выделил мелкий фикс в релизную задачу. Рефакторить флоу входа буду отдельно

2024-09-12 12:07 UTC, fedorov-d approved these changes, later dismissed

2024-09-12 12:11 UTC, m3g0byt3 requested changes

2024-09-12 12:11 UTC, m3g0byt3 commented on Tangem/Modules/App/AppCoordinator.swift
> +        }
Это уже реализовано, ниже в `closeAllSheetsIfNeeded` происходит скрытие шита при локе
Если что-то работает не так, как ожидается - надо разбираться

Вообще, вызывать `bottomSheetVisibility.hide()` для ПОЛНОГО скрытия (с убийством VM и стейта - то что и надо при локе) некорректно, потому что он оставляет VM живой

2024-09-12 12:16 UTC, m3g0byt3 commented on Tangem/Modules/App/AppCoordinator.swift
> +        }
Сейчас получается что AppCoordinator через вызов bottomSheetVisibility.hide() сам себе посылает false в isShownPublisher, который он же и обсервит

Это явно происходит медленнее, чем уже существующий эквивалентный код в closeAllSheetsIfNeeded - поэтому этот фикс ничего не фиксит
Но он может казаться рабочим в дебаггере, когда есть какие-то задержки и т.д.

2024-09-12 13:07 UTC, tureck1y commented on Tangem/Modules/App/AppCoordinator.swift
> +        }
Я приложил видео до/после, разница налицо. Какое тогда решение правильное?

2024-09-12 13:18 UTC, tureck1y commented on Tangem/Modules/App/AppCoordinator.swift
> +        }
Попробую поковырять работу с паблишед напрямую, без вызова hide

2024-09-12 15:39 UTC, tureck1y commented on Tangem/Modules/App/AppCoordinator.swift
> +        }
В общем проблема была в неконсистентности  bottomSheetVisibility.isHidden, при скрытии напрямую через проперти marketsCoordinator. Поэтому при рестарте, шторка появлялась заново, причем раньше остальных вьюх. Убрал скрытие через проперти, добавил удаление backport __marketsCoordinator. Проверил на альфе - все ок

2024-09-13 12:41 UTC, m3g0byt3 approved these changes

2024-09-13 15:56 UTC, fedorov-d approved these changes

2024-09-13 16:05 UTC, merged