IOS-1603 redesign main page
tangem/tangem-app-ios-old pull request #385
Opened 2022-05-19 10:38 UTC by gre4ixin

2022-05-19 11:46 UTC, megakoko requested changes

2022-05-19 11:46 UTC, megakoko commented on Tangem/Common/ImpactFeedback/ImpactFeedback.swift
> +
Убери пожалуйста пустые строки после открывающей скобки и перед закрывающей. У нас так не принято.

2022-05-19 11:46 UTC, megakoko commented on Tangem/Common/ImpactFeedback/ImpactFeedback.swift
> +class Impack {
Нет такого слова в английском. Переименуй в ImpactGenerator, play в generate, перечисление помести внутрь.

2022-05-19 11:46 UTC, megakoko commented on Tangem/Common/Localizations/de.lproj/Localizable.strings
> +"tokens" = "Tokens";
Если это текстовки с главной страницы — добавь к идентификаторам префикс main.

2022-05-19 11:46 UTC, megakoko commented on Tangem/Main/MainView.swift
> +            Impack.play(.light)
Почему не поместить это в onScan?

2022-05-19 11:46 UTC, megakoko commented on Tangem/Main/MainView.swift
> +        .buttonStyle(PlainButtonStyle())
TangemButtonStyle еще контролирует индикатор загрузки. С PlainButtonStyle это пропало.

Зачем переместил эту кнопку в коде?

2022-05-19 11:46 UTC, megakoko commented on Tangem/Common/ImpactFeedback/ImpactFeedback.swift
> +class Impack {
В xcode есть поддержка spell-checker, удобная штука.

2022-05-19 11:46 UTC, megakoko commented on Tangem/Main/MainView.swift
> -                                                TokensListItemView(item: item)
TokensListItemView больше не используется в проекте?

2022-05-19 11:46 UTC, megakoko commented on Tangem/Main/TokenView/TokensView.swift
> +                                Button {
Выравнивание поехало

2022-05-19 11:46 UTC, megakoko commented on Tangem/Main/TokenView/TokensView.swift
> +                    Spacer()
Добавь пустую строку чтобы не слипалось с предыдущим огромным определением

2022-05-19 11:46 UTC, megakoko commented on Tangem/Main/TokenView/TokensView.swift
> +                    VStack(spacing: 0) {
Зачем класть один VStack в другой VStack с прозрачным фоном?

2022-05-19 11:46 UTC, megakoko commented on Tangem/Main/TokenView/TokensView.swift
> +                        HStack(spacing: 0) {
Вместо добавления еще одного уровня вложенности лучше сделать `.frame(width: .infinity)`, чтобы текст занимал всю ширину и выравнивался по левому краю.

2022-05-19 11:46 UTC, megakoko commented on Tangem/Main/TokenView/TokensView.swift
> +                                        if items.firstIndex(of: item) != items.count - 1 {
Разделитель надо вынести из кнопки. В проекте уже есть вьюха Separator.

2022-05-19 11:46 UTC, megakoko commented on Tangem/Main/TokenView/TokensView.swift
> +        TokensView(items: [], action: { _ in })
Почему нельзя было использовать TokensListItemView? Там и превью было.

2022-05-19 11:46 UTC, megakoko commented on Tangem/Main/TotalSumBalance/TotalSumBalanceView.swift
> +                        Impack.play(.light)
Можно внутрь функции положить?

2022-05-19 11:46 UTC, megakoko commented on Tangem/Main/TotalSumBalance/TotalSumBalanceView.swift
> -                            view.shimmering()
Шиммеринг больше на проекте не используется?

2022-05-19 11:46 UTC, megakoko commented on Tangem/Main/TotalSumBalance/TotalSumBalanceViewModel.swift
> +    @Published var totalFiatValueString: String = "0,00"
Почему `0,00`? У пользователя может быть локаль, в которой ноль форматируется как `0.00`.

2022-05-19 11:46 UTC, megakoko commented on Tangem/Main/TotalSumBalance/TotalSumBalanceViewModel.swift
>              self?.tokenItems = newValue
Надо выровнять код.

2022-05-19 11:46 UTC, megakoko commented on Tangem/Main/TotalSumBalance/TotalSumBalanceView.swift
> +                .padding(.bottom, viewModel.isFailed ? 0 : 16)
Если тексту, который появляется на экране при `viewModel.isFailed` нужно дополнительное место — то пусть он сам его и добавляет. Ну или можно не указывать `VStack(spacing: 0)` и пусть VStack сам добавляет промежутки.

2022-05-19 11:46 UTC, megakoko commented on Tangem/Main/TotalSumBalance/TotalSumBalanceViewModel.swift
> +    deinit {
Просматривай свой код перед отправкой на ревью, хотя бы мельком.

2022-05-19 12:13 UTC, tureck1y commented on Tangem/Main/TotalSumBalance/TotalSumBalanceViewModel.swift
> +    @Published var totalFiatValueString: String = "0,00"
У нас есть форматтер для фиата, там все учтено, обязательно через него надо прогонять

2022-05-19 12:17 UTC, tureck1y commented on Tangem/Main/MainView.swift
> +        .buttonStyle(PlainButtonStyle())
Все операции с картой в обязательном порядке вешаются на кастомную кнопку, из-за индикатора загрузки

2022-05-19 12:34 UTC, tureck1y commented on Tangem/Main/MainView.swift
> +        .sheet(isPresented: $navigation.mainToCardOnboarding, content: {
С шитами надо быть аккуратным,вещать их на color.clear в одной иерархии, по аналогии с остальными, иначе не будет на старых иос открываться

2022-05-19 12:34 UTC, tureck1y commented on Tangem/Main/MainView.swift
> +        .buttonStyle(PlainButtonStyle())
Однако если тут логика осталась старой с переходом на страницу сторис, то тут индикатор делать необязательно

2022-05-19 13:20 UTC, gre4ixin commented on Tangem/Main/TotalSumBalance/TotalSumBalanceView.swift
> +                .padding(.bottom, viewModel.isFailed ? 0 : 16)
я наоборот убираю отступ, иначе текст появится и будет отступ от текста 16 и у текста снизу еще будет отступ 16

2022-05-19 13:23 UTC, gre4ixin commented on Tangem/Common/ImpactFeedback/ImpactFeedback.swift
> +class Impack {
поправил

2022-05-19 13:23 UTC, gre4ixin commented on Tangem/Common/ImpactFeedback/ImpactFeedback.swift
> +
поправил

2022-05-19 13:23 UTC, gre4ixin commented on Tangem/Common/Localizations/de.lproj/Localizable.strings
> +"tokens" = "Tokens";
поправил

2022-05-19 13:25 UTC, gre4ixin commented on Tangem/Main/MainView.swift
> +            Impack.play(.light)
убрал в функцию

2022-05-19 13:25 UTC, gre4ixin commented on Tangem/Main/MainView.swift
> +        .buttonStyle(PlainButtonStyle())
TangemButtonStyle логика не менялась, поменялась только кнопка и ее расположение

2022-05-19 13:26 UTC, gre4ixin commented on Tangem/Main/MainView.swift
> -                                                TokensListItemView(item: item)
убрал

2022-05-19 13:26 UTC, gre4ixin commented on Tangem/Main/TokenView/TokensView.swift
> +                                Button {
поправил

2022-05-19 13:26 UTC, gre4ixin commented on Tangem/Main/TokenView/TokensView.swift
> +                    Spacer()
поправил

2022-05-19 13:27 UTC, gre4ixin commented on Tangem/Main/TokenView/TokensView.swift
> +                                        if items.firstIndex(of: item) != items.count - 1 {
Вынес разделитесь, тот, что в проекте не подходит, оставил свой

2022-05-19 13:27 UTC, megakoko commented on Tangem/Main/TotalSumBalance/TotalSumBalanceView.swift
> +                .padding(.bottom, viewModel.isFailed ? 0 : 16)
Понял. А зачем при отсутствующем тексте нижний паддинг тогда? Там у всего VStack еще добавляется второй раз паддинг.

Можно это как-то упростить?

2022-05-19 13:27 UTC, gre4ixin commented on Tangem/Main/TotalSumBalance/TotalSumBalanceView.swift
> +                        Impack.play(.light)
поправил

2022-05-19 13:27 UTC, gre4ixin commented on Tangem/Main/TotalSumBalance/TotalSumBalanceView.swift
> -                            view.shimmering()
удалил

2022-05-19 13:27 UTC, gre4ixin commented on Tangem/Main/TotalSumBalance/TotalSumBalanceViewModel.swift
> +    @Published var totalFiatValueString: String = "0,00"
вернул пустую строку

2022-05-19 13:28 UTC, gre4ixin commented on Tangem/Main/TotalSumBalance/TotalSumBalanceViewModel.swift
>              self?.tokenItems = newValue
поправил

2022-05-19 13:28 UTC, gre4ixin commented on Tangem/Main/TotalSumBalance/TotalSumBalanceViewModel.swift
> +    deinit {
удалил

2022-05-19 13:28 UTC, megakoko commented on Tangem/Common/ImpactFeedback/ImpactFeedback.swift
> +
Поправь во всех файлах в этом МРе.

2022-05-19 13:28 UTC, gre4ixin commented on Tangem/Main/MainView.swift
> +        .sheet(isPresented: $navigation.mainToCardOnboarding, content: {
перенес на Color.clear

2022-05-19 13:28 UTC, megakoko commented on Tangem/Common/Localizations/de.lproj/Localizable.strings
> +"tokens" = "Tokens";
В табличке тоже

2022-05-19 13:36 UTC, megakoko commented on Tangem/Main/TokenView/TokensView.swift
> +                                        if items.firstIndex(of: item) != items.count - 1 {
Надо подкрутить существующий и его заюзать.

2022-05-19 13:46 UTC, gre4ixin commented on Tangem/Common/ImpactFeedback/ImpactFeedback.swift
> +
убрал

2022-05-19 13:47 UTC, gre4ixin commented on Tangem/Common/Localizations/de.lproj/Localizable.strings
> +"tokens" = "Tokens";
в табличку добавил, андроидов предупредил

2022-05-19 13:48 UTC, gre4ixin commented on Tangem/Main/TokenView/TokensView.swift
> +                                        if items.firstIndex(of: item) != items.count - 1 {
свой убрал, проектный поправил

2022-05-19 13:50 UTC, gre4ixin commented on Tangem/Main/TokenView/TokensView.swift
> +        TokensView(items: [], action: { _ in })
превью добавил

2022-05-19 13:52 UTC, megakoko commented on Tangem/Main/TokenView/TokensView.swift
> +        TokensView(items: [], action: { _ in })
Было больше.

2022-05-19 13:53 UTC, megakoko commented on Tangem/Main/TokenView/TokensView.swift
> +        TokensView(items: [], action: { _ in })
И разнообразнее, со всякими странными кейсами.

2022-05-19 14:00 UTC, gre4ixin commented on Tangem/Main/TokenView/TokensView.swift
> +        TokensView(items: [], action: { _ in })
вернул

2022-05-19 14:07 UTC, gre4ixin commented on Tangem/Main/TotalSumBalance/TotalSumBalanceView.swift
> +                .padding(.bottom, viewModel.isFailed ? 0 : 16)
При отсутствующем тексте у нас отступ снизу 16, при появившемся тексте, у конкретного стека нет отступа, он ведь считает уже от этого текста, поэтому отступ делает уже текст

2022-05-19 20:41 UTC, gre4ixin commented on Tangem/Main/TokenView/TokensView.swift
> +                    VStack(spacing: 0) {
Один является контейнером, второй имеет белый фон и отступы, чтобы в итоге мы получили прямоугольник с токенами внутри

2022-05-19 20:47 UTC, gre4ixin commented on Tangem/Main/TokenView/TokensView.swift
> +                        HStack(spacing: 0) {
убрал HStack

2022-05-19 20:50 UTC, gre4ixin commented on Tangem/Main/TokenView/TokensView.swift
> +                    VStack(spacing: 0) {
убрал лишний VStack

2022-05-19 21:19 UTC, gre4ixin commented on Tangem/Main/TotalSumBalance/TotalSumBalanceView.swift
> +                .padding(.bottom, viewModel.isFailed ? 0 : 16)
поправил

2022-05-20 06:15 UTC, megakoko requested changes

2022-05-20 06:15 UTC, megakoko commented on Tangem/MultiWallet/WalletsList/TokensView.swift
> +                            VStack(spacing: 0) {
Зачем этот VStack?

2022-05-20 06:15 UTC, megakoko commented on Tangem/Main/TotalSumBalance/TotalSumBalanceView.swift
> +                    Text(viewModel.isFailed ? "main_processing_full_amount".localized : "")
Зачем здесь тернарный оператор если вьюха показывается только при isFailed?

2022-05-20 06:15 UTC, megakoko commented on Tangem/Main/TotalSumBalance/TotalSumBalanceView.swift
> +                            .padding(.trailing, 6)
Вместо того, чтобы разделять вьюхи паддингом лучше делать это через `spacing` у HStack

2022-05-20 06:15 UTC, megakoko commented on Tangem/Main/TotalSumBalance/TotalSumBalanceView.swift
> +                    .padding(.leading, 16)
У `Text("main_page_balance")`, `ActivityIndicatorView`, `Text(viewModel.totalFiatValueString)` установлен левый паддинг 16. Можно не задавать его к каждой вьюхе, а вынести его выше по иерархии.

То же самое с trailing паддингом. Я вижу что он 20, нет причин чтобы правый паддинг отличался от левого, даже если в фигме так. Сделай его тоже 16, пожалуйста.

2022-05-20 06:15 UTC, megakoko commented on Tangem/Main/TotalSumBalance/TotalSumBalanceView.swift
> +            VStack(alignment: .leading, spacing: 0) {
Нужен этот VStack? Он и так содержится в другом VStack с такими же параметрами.

2022-05-20 06:15 UTC, megakoko commented on Tangem/Main/TotalSumBalance/TotalSumBalanceView.swift
>          .onDisappear {
Посмотри на скрин — думай о вьюхе которую тебе надо нарисовать как о каком-то внутреннем контейнере с паддингом примененном ко всем четырем сторонам. Потом результат взяли и добавили к нему белый фон закругленный. Потом взяли результат и добавили горизонтальный паддинг.

Не переусложняй иерархию и модификторы. Если можно более плоскую иерархию в коде сделать — делай более плоскую, если можно вынести какие-то модификаторы наверх по иерархии чтобы они ко всему контейнеру применялись — выноси.

![IMG_F88D40BD3C80-1](https://user-images.githubusercontent.com/12209839/169463964-8f710a34-e7ab-46d8-b206-9e096632dda0.jpeg)

2022-05-20 06:15 UTC, megakoko commented on Tangem/MultiWallet/WalletsList/TokensView.swift
> +        Group {
Группа здесь нужна? У меня без нее работает.

2022-05-20 06:15 UTC, megakoko commented on Tangem/MultiWallet/WalletsList/TokensView.swift
> +                            Separator(height: 1, padding: 0, separatorColor: Color.tangemBgGray2)
Тут лучше переименовать separatorColor в просто color, чтобы не было тавтологии.

2022-05-20 06:15 UTC, megakoko commented on Tangem/MultiWallet/WalletsList/TokensView.swift
> +                            ImpactGenerator.generate(.light)
Можно тоже положить в action(item)

2022-05-20 08:21 UTC, gre4ixin commented on Tangem/Main/TotalSumBalance/TotalSumBalanceView.swift
> +                    Text(viewModel.isFailed ? "main_processing_full_amount".localized : "")
поправил

2022-05-20 08:21 UTC, gre4ixin commented on Tangem/MultiWallet/WalletsList/TokensView.swift
> +                            VStack(spacing: 0) {
поправил

2022-05-20 08:21 UTC, gre4ixin commented on Tangem/MultiWallet/WalletsList/TokensView.swift
> +        Group {
поправил

2022-05-20 08:21 UTC, gre4ixin commented on Tangem/MultiWallet/WalletsList/TokensView.swift
> +                            Separator(height: 1, padding: 0, separatorColor: Color.tangemBgGray2)
переименовал

2022-05-20 08:22 UTC, gre4ixin commented on Tangem/MultiWallet/WalletsList/TokensView.swift
> +                            ImpactGenerator.generate(.light)
убрал в функцию

2022-05-20 09:01 UTC, gre4ixin commented on Tangem/Main/TotalSumBalance/TotalSumBalanceView.swift
> +            VStack(alignment: .leading, spacing: 0) {
с помощью него я выравниваю 3 вьюхи

2022-05-20 09:10 UTC, megakoko commented on Tangem/Main/TotalSumBalance/TotalSumBalanceView.swift
> +            VStack(alignment: .leading, spacing: 0) {
А зачем выравнивать этот VStack, если можно выравнивать их родительский VStack. Я про это и говорю.

Ты добавляешь модификаторы padding(.leading, 16) к каждой внутренней вьюхе вместо того чтобы добавить его к их общему контейнеру. Тогда и этот внутренний VStack не нужен будет.

2022-05-20 10:43 UTC, megakoko approved these changes, later dismissed

2022-05-20 11:25 UTC, Balashov152 commented on Tangem/Main/MainView.swift
> +        trailing: Button(action: {
Может trailing тоже в отдельную переменную вынести, что бы читабельность лучше была

2022-05-20 11:25 UTC, Balashov152 commented on Tangem/MultiWallet/WalletsList/TokensView.swift
> +            .padding([.horizontal], 16)
я бы вынес в отдельную переменную `@ViewBuilder private var content: some View {}`

2022-05-20 11:25 UTC, Balashov152 commented on Tangem/MultiWallet/WalletsList/TokensView.swift
> +struct TokenItemView: View {
Может в отдельный файл ?

2022-05-20 11:25 UTC, Balashov152 commented on Tangem/MultiWallet/WalletsList/TokensView.swift
> +    }
Если переменные нигде снаружи не нужны, то лучше их делать private

2022-05-20 11:43 UTC, gre4ixin commented on Tangem/MultiWallet/WalletsList/TokensView.swift
> +            .padding([.horizontal], 16)
а какой смысл? читаемость от этого не улучшиться, а вот прыгать по переменным придется

2022-05-20 11:46 UTC, gre4ixin commented on Tangem/Main/MainView.swift
> +        trailing: Button(action: {
да, вынес ее тоже в отдельную переменную

2022-05-20 11:47 UTC, gre4ixin commented on Tangem/MultiWallet/WalletsList/TokensView.swift
> +struct TokenItemView: View {
вынес

2022-05-20 11:47 UTC, gre4ixin commented on Tangem/MultiWallet/WalletsList/TokensView.swift
> +    }
поправил

2022-05-20 11:52 UTC, Balashov152 commented on Tangem/MultiWallet/WalletsList/TokensView.swift
> +            .padding([.horizontal], 16)
Ну как предложение )

Что бы body не разрастался, да оставляй так

2022-05-20 11:54 UTC, Balashov152 approved these changes, later dismissed

2022-05-20 11:55 UTC, megakoko submitted a review, later dismissed

2022-05-20 12:40 UTC, megakoko approved these changes

2022-05-20 13:10 UTC, tureck1y approved these changes

2022-05-20 13:14 UTC, ba1ashov approved these changes

2022-05-20 13:15 UTC, merged