IOS-1648 Exceed amount disable send button
tangem/tangem-app-ios-old pull request #389
Opened 2022-05-20 14:47 UTC by Balashov152

2022-05-23 03:45 UTC, megakoko commented
Зачем столько изменений? Надо было только кнопку починить.

2022-05-23 10:05 UTC, Balashov152 commented
> Зачем столько изменений? Надо было только кнопку починить.

Ну если чинить, то чинить, а не просто костылем подпирать) Сложная логика по управлению ошибочного/валидного состояния экрана, сделал более унифицированно, если если ошибка, то кнопка не может быть валидной, и наоборот

2022-05-23 10:39 UTC, megakoko commented
Хорошо. А зачем менять выравнивание строк, паддинги и спейсинги?

2022-05-23 10:43 UTC, megakoko commented
Напиши, пожалуйста, в чем баг заключался. Я смотрю на череду красных и зеленых линий в диффе и не понимаю что к чему.

2022-05-23 11:25 UTC, tureck1y reviewed
Изменений действительно много, и логика там действительно запутанная, потому что постоянно обрастает чем-то новым. Потестируй сам пожалуйста получше, в частности случай как у тезоса, когда предлагается уменьшить сумму вывода и деаллоцируется ли вьюмодель при пересоздании.

Описание бага можно в жире посмотреть. Может нам тогда для удобства ревьюверов в описание pr вставлять ссылку на жиру?

2022-05-23 11:25 UTC, tureck1y commented on Tangem/Send/SendViewModel.swift
> +            .assign(to:\.destinationState, on: self)
у нас есть weakAssign чтобы не было ретейна

2022-05-23 11:25 UTC, tureck1y commented on Tangem/Send/SendViewModel.swift
> +            .assign(to:\.destinationState, on: self)
у каждого assign коммент уж писать не буду)

2022-05-23 14:30 UTC, ba1ashov commented
> Напиши, пожалуйста, в чем баг заключался. Я смотрю на череду красных и зеленых линий в диффе и не понимаю что к чему.

Баг в том что переключатель доступности кнопки был отдельным булем, и при написании ошибки, никто не дизейблел кнопку

2022-05-23 14:32 UTC, ba1ashov commented on Tangem/Send/SendViewModel.swift
> +            .assign(to:\.destinationState, on: self)
На счет изменений решил что надо отдельно заводить задачи на рефакторинг, и делать его, так как видно много мест потенциальных багов

weakAssign поглядел, буду его юзать в дальнейшем

2022-05-23 14:33 UTC, Balashov152 commented
> Хорошо. А зачем менять выравнивание строк, паддинги и спейсинги?

Это Cmd+I проставил, в не которых местах совсем все плохо с этим(
надо swiftformat завозить, а то с читабельностью беда

Откатил изменения, надо будет отдельно это делать

2022-05-24 04:52 UTC, megakoko commented
Полноценный линтер это по-моему оверкил, иначе мы или погрязнем в предупреждениях, или будет раздутое поле ignore для файлов.

А вот какой-нибудь простенький style guide нужен, чтобы не было разногласий в коде. Надо обсудить когда Александр вернется.

2022-05-24 06:04 UTC, megakoko requested changes

2022-05-24 06:04 UTC, megakoko commented on Tangem/Send/SendView.swift
> +                    Spacer().frame(height: 8)
Сделай как было, пожалуйста.

2022-05-24 06:04 UTC, megakoko commented on Tangem/Send/SendViewModel.swift
> +                transaction == nil].allSatisfy { !$0 }
Сделай через обычные булевы операторы, пожалуйста. 

На всякий случай — если выражение большое и многокомпонентное, то удобнее отрицать его полностью, чем его части.

```
!AAA && !BBB && !CCC
!(AAA || BBB || CCC)
```

2022-05-24 06:33 UTC, tureck1y commented on Tangem/Send/SendViewModel.swift
> +                transaction == nil].allSatisfy { !$0 }
такое лучше читается имхо !AAA && !BBB && !CCC

2022-05-24 08:20 UTC, Balashov152 commented on Tangem/Send/SendView.swift
> +                    Spacer().frame(height: 8)
✅

2022-05-24 08:20 UTC, Balashov152 commented on Tangem/Send/SendViewModel.swift
> +                transaction == nil].allSatisfy { !$0 }
✅

2022-05-24 08:30 UTC, megakoko approved these changes

2022-05-24 08:35 UTC, merged