IOS-7809 Show provider slippage
tangem/tangem-app-ios-old pull request #3971
Opened 2024-09-30 08:09 UTC by Vyachesl0ve

[Задача](https://tangem.atlassian.net/browse/IOS-7809) алерты оставили, как были
<img src="https://github.com/user-attachments/assets/beda9da8-5482-48fb-81e5-d43a35b9309e" width="300">

2024-09-30 08:13 UTC, JustGuitarKitty commented on Tangem/Modules/ExpressView/ExpressViewModel.swift
> +    func fetchAmountAfterSlippage(for providerName: String) -> Decimal {
стоит ли покрывать тестами с учетом, что фича не покрыта?

2024-09-30 08:32 UTC, skibinalexander commented on Tangem/Common/UI/ReceiveCurrencyView/ReceiveCurrencyViewModel.swift
> +            self.expectAmount = 0
Тут self ниже нет self

2024-09-30 08:34 UTC, skibinalexander commented on Tangem/Modules/ExpressView/ExpressViewModel.swift
> +        case "changenow": 3
Может как-то названия в enum, ошибиться легко достаточно, но не критично

2024-09-30 08:54 UTC, amuraveinik requested changes

2024-09-30 08:54 UTC, amuraveinik commented on Tangem/Resources/Localizations/ru.lproj/Localizable.strings
> +"swapping_alert_dex_description" = "В сумму включена комиссия провайдера сервиса. \n\nПроскальзывание провайдера составляет до %@ \nПри максимальном проскальзывании сумма к получению будет %@";
Для других языков, где нет перевода, тогда надо продублировать английский

2024-09-30 08:54 UTC, amuraveinik commented on Tangem/Modules/ExpressView/ExpressViewModel.swift
> +    // a crutch for the time being while this information is not on the backend
Стоит оставить TODO чтобы на забыть потом.
Желательно завести сразу тикет на апдейт и сюда же прилинковать

2024-09-30 08:54 UTC, amuraveinik commented on Tangem/Modules/ExpressView/ExpressViewModel.swift
> +    func fetchAmountAfterSlippage(for providerName: String) -> Decimal {
Наверное не стоит, выглядит как довольно маленькая штука

2024-09-30 11:54 UTC, JustGuitarKitty commented on Tangem/Common/UI/ReceiveCurrencyView/ReceiveCurrencyViewModel.swift
> +            self.expectAmount = 0
а там компилятор понять не может, куда мы присваиваем значение, если self явно не указать

2024-09-30 13:15 UTC, JustGuitarKitty commented on Tangem/Modules/ExpressView/ExpressViewModel.swift
> +    func fetchAmountAfterSlippage(for providerName: String) -> Decimal {
обсудили с @tureck1y, решили добавить хотя бы в таком виде, как сейчас

2024-09-30 13:16 UTC, JustGuitarKitty commented on Tangem/Modules/ExpressView/ExpressViewModel.swift
> +    // a crutch for the time being while this information is not on the backend
жду номер тикета пока

2024-09-30 13:18 UTC, skibinalexander approved these changes, later dismissed

2024-09-30 13:40 UTC, JustGuitarKitty commented on Tangem/Modules/ExpressView/ExpressViewModel.swift
> +    // a crutch for the time being while this information is not on the backend
Добавил

2024-09-30 13:50 UTC, amuraveinik approved these changes, later dismissed

2024-09-30 13:53 UTC, skibinalexander submitted a review, later dismissed

2024-10-02 17:13 UTC, tureck1y submitted a review, later dismissed
@Balashov152 тоже пробегись плиз

2024-10-02 18:51 UTC, Balashov152 submitted a review, later dismissed

2024-10-02 18:51 UTC, Balashov152 commented on Tangem/Modules/ExpressView/ExpressViewModel.swift
> +extension ExpressViewModel {
Хорошо бы тоже private 
```suggestion
private extension ExpressViewModel {
```

2024-10-02 18:51 UTC, Balashov152 commented on Tangem/Common/UI/ReceiveCurrencyView/ReceiveCurrencyViewModel.swift
> +    private(set) var expectAmountDecimals: Int = 0
Не совсем понял зачем тут хранить, а не брать по месту в ExpressViewModel

2024-10-25 19:43 UTC, tureck1y approved these changes

2024-10-25 20:23 UTC, Balashov152 approved these changes

2024-10-28 09:04 UTC, amuraveinik approved these changes

2024-10-28 09:08 UTC, skibinalexander approved these changes

2024-10-28 14:51 UTC, merged