iOS-8075 [Staking] Vote after lock
tangem/tangem-app-ios-old pull request #3977
Opened 2024-09-30 13:20 UTC by fedorov-d

Добавил флоу vote locked, локализацию добавил руками.

2024-10-01 17:21 UTC, tureck1y commented
ветка 5.16.1

2024-10-02 09:08 UTC, Balashov152 requested changes
Остальное вроде все хорошо, собрал, проверил, все норм

2024-10-02 09:08 UTC, ba1ashov commented on Tangem/Modules/Send/StakingNotifications/StakingNotificationManager.swift
> +        case .validationError: break
Как будто тоже надо, если вдруг на fee не хватит, можно взять из других методов

2024-10-02 09:08 UTC, ba1ashov commented on Tangem/Modules/Send/StakingNotifications/StakingNotificationManager.swift
> +                show(notification: .revote(description: Localization.stakingNotificationsRevoteTronText))
А почему `description` здесь? Это если в других сетях будет ?)

2024-10-02 09:08 UTC, ba1ashov commented on Tangem/Modules/Send/VoteModel.swift
> +        _selectedValidator
При каждом выборе будем обновлять? На меня был баг, что бы обновляли, только при открытии summary. Я думаю это сейчас в ValidatorsStep есть, в willDisappear. Давай просто на 220 строке в этой модели `updateState` вызовем, и все. 

А то так может быть слишком часто обновляться

2024-10-02 09:08 UTC, ba1ashov commented on Tangem/Modules/Send/VoteModel.swift
> +            return .validationError(error, fee: fee)
вот на это нотификации все так может быть

2024-10-02 09:08 UTC, ba1ashov commented on Tangem/Modules/Send/VoteModel.swift
> +        Analytics.log(event: .transactionSent, params: [
Это актуальная инфа ? По аналитике, может есть доп задача, надо к Леше наверно идти?
Можно подумать над отдельным сервисом `SendAnalyticsLogger`, что бы там собирать все это, и во все модели закинуть, ну это на будущее

2024-10-02 09:08 UTC, ba1ashov commented on Tangem/Modules/Send/VoteModel.swift
> +        // Do not show any text in the unstaking flow
```suggestion
        // Do not show any text in the vote flow
```

2024-10-02 09:08 UTC, ba1ashov commented on Tangem/Modules/Send/SendCoordinator.swift
>          case .unstaking(let manager, let action):
Давай плиз в `SendType` добавим уж тоже, а то везде есть, а тут нет )
Будет просто `vote(manager: StakingManager, action: VoteModel.Action)`
и можно будет `pendingType.isVoteLocked` убрать, что лишним не висел

2024-10-02 09:13 UTC, Balashov152 commented on Tangem/Modules/Send/StakingNotifications/StakingNotificationEvent.swift
> +            description
Чет мне кажется что можно убрать `description` из параметров, а здесь просто прописать. Как будто vote это только для TRON )

2024-10-02 14:17 UTC, fedorov-d commented on Tangem/Modules/Send/VoteModel.swift
> +        _selectedValidator
была проблема в том что на момент вызова `updateState` валидатор был пустой, можно в эту цепочку добавить `first() ` после `compactMap`

2024-10-02 14:34 UTC, fedorov-d commented on Tangem/Modules/Send/VoteModel.swift
> +        Analytics.log(event: .transactionSent, params: [
Леша сказал что все также, потом в целом над рефактом надо будет подумать и аналитикой в том числе конечно

2024-10-02 14:51 UTC, fedorov-d commented on Tangem/Modules/Send/StakingNotifications/StakingNotificationManager.swift
> +        case .validationError: break
добавил

2024-10-02 14:51 UTC, fedorov-d commented on Tangem/Modules/Send/StakingNotifications/StakingNotificationManager.swift
> +                show(notification: .revote(description: Localization.stakingNotificationsRevoteTronText))
убрал

2024-10-02 14:51 UTC, fedorov-d commented on Tangem/Modules/Send/SendCoordinator.swift
>          case .unstaking(let manager, let action):
добавил

2024-10-02 14:52 UTC, fedorov-d commented on Tangem/Modules/Send/StakingNotifications/StakingNotificationEvent.swift
> +            description
убрал

2024-10-02 14:56 UTC, Balashov152 commented on Tangem/Modules/Send/RestakingModel.swift
> +    private let action: Action
хм, а получится убрать этот `action` отсюда? А то он будет не совсем валидный получается, например выбрав валидатора, мы захотим глянуть `RestakingModelStateProvider.stakingAction` и там валидатора не найдем. 
как будто можно каждый раз там создавать что ли

2024-10-02 16:32 UTC, Balashov152 commented on Tangem/Modules/Send/RestakingModel.swift
> +    func updateFees() {}
```suggestion
    func updateFees() {
         updateState()
    }
```

2024-10-02 16:48 UTC, Balashov152 commented on Tangem/Modules/Send/VoteModel.swift
> +        _selectedValidator
Осталось только еще в `updateFees()`

2024-10-02 16:51 UTC, Balashov152 approved these changes

2024-10-02 17:00 UTC, tureck1y approved these changes

2024-10-02 17:00 UTC, merged