IOS-8065 update unavailable portfolio text
tangem/tangem-app-ios-old pull request #3978
Opened 2024-09-30 13:30 UTC by skibinalexander

Требовалось внести изменения для одновалюток показывать строчку  ~ "This asset is not available for this wallet" а не использовать общую "This asset is not available"

```
если у тебя только одновалютка, то в шторке также показываются все токены, как и на мультивалютках, просто при переходе в чарты ты не сможешь его добавит.
В блоке My portfolio пишем "This asset is not available for this wallet" (были предложения и идеи тут писать, чтобы переходили на мультивалютку, но пока не стали)
```

2024-10-02 07:25 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioContainerViewModel.swift
> +        return hasMultiCurrencyWallet ? .unsupported : .unavailable
эту булку можно получить в цикле 117-121, ты итак ходишь по всему массиву моделей, нет смысла дополнительно создавать рассчитываемое свойство, которое нигде больше не используется и вдобавок ко всему снова проходиться по массиву, по которомы ты только что закончил проходить. Сделай локальную булку `var hasMultiCurrencyWallet = false` и после 120 строки добавь:
``` swift
if !hasMultiCurrencyWallet, model.config.hasFeature(.multiCurrency) {
    hasMultiCurrencyWallet = true
}
```

2024-10-02 08:28 UTC, skibinalexander commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioContainerViewModel.swift
> +        return hasMultiCurrencyWallet ? .unsupported : .unavailable
Окей, спс, посмотрю по оптимизации

2024-10-02 11:00 UTC, Andoran90 submitted a review, later dismissed

2024-10-02 17:21 UTC, tureck1y commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioContainerViewModel.swift
> +        return hasMultiCurrencyWallet ? .unsupported : .unavailable
я совсем не понимаю этот код если честно. мы будем идти по userWalletModels до первого ретурна, либо до конца, а следовательно нет гарантии, что hasMultiCurrencyWallet будет выставлено корректно. В userWalletModels не будет огромного числа моделей и тут не нужны оптимизации в ущерб читаемости и понятности кода, на будущее надо тогда комментами снабжать осмысленными

Может переписать с цикла на функциональщину?

2024-10-02 17:21 UTC, tureck1y requested changes
Нужно еще разок посмотреть на код и сделать его понятнее

2024-10-03 08:13 UTC, Andoran90 commented on Tangem/Modules/Markets/TokenMarketsDetails/Subviews/MarketsPortfolioContainerView/MarketsPortfolioContainerViewModel.swift
> +        return hasMultiCurrencyWallet ? .unsupported : .unavailable
нам надо закончить выполнение после первого подходящего результата. тут нет смысла перебирать все, если уже найден подходящий результат. Функциональщина сделает код ещё более запутанным, если мы будем делать через `contains`. А гонять через фильтр - тоже нет смысла. Предыдущий вариант тоже не особо нужен был, т.к. добавляется рассчитываемое свойство, которое нужно только в 1 месте. Мы уже такое делали и получилась `CardViewModel` с 100500 свойств, которые используются в 1 месте.
Гарантия выставления `hasMultiCurrencyWallet` не нужна, если мы раньше времени вышли, это же локальная переменная, если мы вернем `.available` остальное нам не важно.

2024-10-03 11:44 UTC, skibinalexander commented
Уточнил, почему у Андроида нет проблем, решили сделать чуть проще. Всегда показывать текстовку unavailable и только для отстуствующих сеток unsupported. Обновил код

2024-10-03 13:03 UTC, Andoran90 approved these changes

2024-10-03 15:21 UTC, tureck1y approved these changes

2024-10-03 15:49 UTC, Balashov152 approved these changes

2024-10-03 16:09 UTC, merged