IOS-1665 Token list loadable from API
tangem/tangem-app-ios-old pull request #398
Opened 2022-05-24 16:09 UTC by ba1ashov

Заодно перенес items именно как массив ViewModels в ViewModel вьюхи так как view по факту не должна знать ничего про лоадер да и вообще про варианты загрузки. 

Ну и как по мне ListDataLoader не должен влиять на View никак, у него одна задача, загрузить.

2022-05-25 06:52 UTC, megakoko requested changes

2022-05-25 06:52 UTC, megakoko commented on Tangem/App/Services/Common/SupportedTokenItems.swift
> +    private func readList() -> AnyPublisher<CoinsResponse, Error> {
readTestnetList, loadTestnetCoins, чтобы понятнее было

2022-05-25 06:52 UTC, megakoko commented on Tangem/App/Services/Common/SupportedTokenItems.swift
> +        readList().map { list in
Перенеси оператор комбайна на новую строку, у нас так принято.

2022-05-25 06:52 UTC, megakoko commented on Tangem/App/Services/Extensions/Moya+.swift
> +
Лишняя пустая строка

2022-05-25 06:52 UTC, megakoko commented on Tangem/MultiWallet/TokenList/ListDataLoader.swift
> +                self?.cached = output
Можно наверное удалить и кеширование, и пагинацию тестнетовского списка. Лишний код, который вряд ли понадобится в будущем.

На твое усмотрение.

2022-05-25 06:52 UTC, megakoko commented on Tangem/MultiWallet/TokenList/ListDataLoader.swift
> +    func loadCoinsItems(_ searchText: String) -> AnyPublisher<[CoinModel], Never> {
loadMainnetItems

2022-05-25 06:52 UTC, megakoko commented on Tangem/MultiWallet/TokenList/TokenListView.swift
> -                            Spacer()
Зачем поменял местами spacer и индикатор загрузки?

2022-05-25 06:52 UTC, megakoko commented on Tangem/MultiWallet/TokenList/TokenListViewModel.swift
> +    var haveNextPage: Bool {
hasNextPage

Почти везде лучше has писать, если в прошедшем времени — had. Т.к. неявно указываем на третье лицо — "оно имеет", "оно имело".

2022-05-25 06:52 UTC, megakoko commented on Tangem/MultiWallet/TokenList/TokenListViewModel.swift
> +    func setupListDataLoader() -> ListDataLoader {
Можно private сделать. И перенеси, пожалуйста, оператор map на новую строку.

2022-05-25 06:52 UTC, megakoko commented on Tangem/MultiWallet/TokenList/ListDataLoader.swift
> +    private var currentRequests: [String: AnyCancellable?] = [:]
Не используется?

2022-05-25 06:52 UTC, megakoko commented on Tangem/MultiWallet/TokenList/ListDataLoader.swift
> +        )
Надо передавать все доступные networkId в networkIds

2022-05-25 07:03 UTC, megakoko commented on Tangem/App/Services/CoinsService/Types/CoinsListRequestModel.swift
> +    let networkIds: [String]?
Нам сейчас получается всегда надо будет передавать массив `networkIds` на бекенд, можно убрать опциональность.

Если от конструктора можно избавиться — было бы здорово, меньше кода.

2022-05-25 08:19 UTC, Balashov152 commented on Tangem/App/Services/Common/SupportedTokenItems.swift
> +    private func readList() -> AnyPublisher<CoinsResponse, Error> {
✅

2022-05-25 08:19 UTC, Balashov152 commented on Tangem/App/Services/Common/SupportedTokenItems.swift
> +        readList().map { list in
✅

2022-05-25 08:19 UTC, Balashov152 commented on Tangem/App/Services/Extensions/Moya+.swift
> +
✅

2022-05-25 08:20 UTC, Balashov152 commented on Tangem/MultiWallet/TokenList/ListDataLoader.swift
> +    func loadCoinsItems(_ searchText: String) -> AnyPublisher<[CoinModel], Never> {
✅

2022-05-25 08:20 UTC, Balashov152 commented on Tangem/MultiWallet/TokenList/TokenListView.swift
> -                            Spacer()
Я убрал вообще Spacer() и сделал Alignment == .center, тоже самое получается, и Spacer() можно убрать

2022-05-25 08:21 UTC, Balashov152 commented on Tangem/MultiWallet/TokenList/TokenListViewModel.swift
> +    var haveNextPage: Bool {
Пора продолжать учить английский 😄 
✅

2022-05-25 08:22 UTC, Balashov152 commented on Tangem/MultiWallet/TokenList/TokenListViewModel.swift
> +    func setupListDataLoader() -> ListDataLoader {
✅

2022-05-25 08:22 UTC, Balashov152 commented on Tangem/MultiWallet/TokenList/ListDataLoader.swift
> +    private var currentRequests: [String: AnyCancellable?] = [:]
Удалил ✅

2022-05-25 08:23 UTC, Balashov152 commented on Tangem/App/Services/CoinsService/Types/CoinsListRequestModel.swift
> +    let networkIds: [String]?
там есть обработка на пустоту, без init() не получится никак( 
Да и в принципе хорошее место управлять моделькой )

2022-05-25 09:03 UTC, megakoko commented on Tangem/MultiWallet/TokenList/TokenListViewModel.swift
> +    var haveNextPage: Bool {
Это самый полезный скилл, который у меня есть, серьезно.

2022-05-25 09:05 UTC, megakoko commented on Tangem/MultiWallet/TokenList/TokenListView.swift
> -                            Spacer()
Извини, невнимательно посмотрел

2022-05-25 09:08 UTC, megakoko commented on Tangem/App/Services/CoinsService/Types/CoinsListRequestModel.swift
> +    let networkIds: [String]?
При добавлении нового поля нужно будет в трех местах это делать вместо одного, неудобно. Но окей.

2022-05-25 09:10 UTC, megakoko commented on Tangem/MultiWallet/TokenList/TokenListViewModel.swift
> +    func setupListDataLoader() -> ListDataLoader {
Перенеси еще к другим private методам.

2022-05-25 12:26 UTC, Balashov152 commented on Tangem/MultiWallet/TokenList/ListDataLoader.swift
> +                self?.cached = output
Пока оставлю, что бы каждый раз с диска не читать

2022-05-25 12:27 UTC, Balashov152 commented on Tangem/MultiWallet/TokenList/TokenListViewModel.swift
> +    func setupListDataLoader() -> ListDataLoader {
собрал всю приватную реализацию в одном extension

2022-05-25 12:27 UTC, ba1ashov commented on Tangem/MultiWallet/TokenList/ListDataLoader.swift
> +        )
✅

2022-05-25 12:34 UTC, megakoko requested changes

2022-05-25 12:34 UTC, megakoko commented on Tangem/MultiWallet/TokenList/ListDataLoader.swift
> +    private var isTestnet: Bool { cardInfo?.isTestnet ?? false }
Добавь переносов строк, проще читать будет чем однострочники.

2022-05-25 12:36 UTC, ba1ashov commented on Tangem/MultiWallet/TokenList/ListDataLoader.swift
> +    private var isTestnet: Bool { cardInfo?.isTestnet ?? false }
✅

2022-05-25 12:39 UTC, megakoko approved these changes, later dismissed

2022-05-26 06:05 UTC, megakoko commented on Tangem/App/Services/CoinsService/CommonCoinsService.swift
> +        let target = TangemApiTarget(type: .coins(requestModel), card: nil)
`card` все-таки тут надо передавать. Мы в будущем будем добавлять авторизацию на сервер по данным с карты, понадобится.

Убери тогда еще, пожалуйста, опциональность у TangemApiTarget.card, чтобы больше не смущала.

И еще, можно переписать checkContractAddress через loadCoins? Код почти совпадает.

2022-05-26 06:05 UTC, megakoko commented on Tangem/App/Services/CoinsService/CommonCoinsService.swift
> +        let target = TangemApiTarget(type: .coins(requestModel), card: nil)
`card` все-таки тут надо передавать. Мы в будущем будем добавлять авторизацию на сервер по данным с карты, понадобится.

Убери тогда еще, пожалуйста, опциональность у TangemApiTarget.card, чтобы больше не смущала.

И еще, можно переписать checkContractAddress через loadCoins? Код почти совпадает.

2022-05-26 08:44 UTC, Balashov152 commented on Tangem/App/Services/CoinsService/CommonCoinsService.swift
> +        let target = TangemApiTarget(type: .coins(requestModel), card: nil)
у нас же есть "Поиск токенов" когда мы еще карту не сканировали, так что убрать опционал не получится(

сейчас попробую объединить в один метод

2022-05-26 11:52 UTC, Balashov152 commented on Tangem/App/Services/CoinsService/CommonCoinsService.swift
> +        let target = TangemApiTarget(type: .coins(requestModel), card: nil)
Сделал все через loadCoins метод

2022-05-26 11:56 UTC, megakoko commented on Tangem/MultiWallet/AddCustomToken/AddCustomTokenViewModel.swift
> +            .loadCoins(requestModel: requestModel)
Я бы оставил helper-метод checkContractAddress, но ок.

2022-05-26 11:56 UTC, megakoko approved these changes, later dismissed

2022-05-26 13:19 UTC, tureck1y commented on Tangem/MultiWallet/TokenList/ListDataLoader.swift
> +    private let coinsService: CoinsService
у нас же DI есть для этого)

2022-05-26 13:19 UTC, tureck1y commented on Tangem/MultiWallet/TokenList/TokenListViewModel.swift
> +    @Injected(\.coinsService) var coinsService: CoinsService
отсюда наверное можно будет вкинуть, если в самой вьюмодели не используется

2022-05-26 13:34 UTC, Balashov152 commented on Tangem/MultiWallet/TokenList/ListDataLoader.swift
> +    private let coinsService: CoinsService
почему-то думал что DI только для ViewModel будем юзать) ✅

2022-05-26 13:34 UTC, Balashov152 commented on Tangem/MultiWallet/TokenList/TokenListViewModel.swift
> +    @Injected(\.coinsService) var coinsService: CoinsService
✅

2022-05-26 13:48 UTC, tureck1y approved these changes

2022-05-26 13:50 UTC, megakoko approved these changes

2022-05-26 13:59 UTC, gre4ixin approved these changes

2022-05-26 14:00 UTC, merged