Ios 1667 fix main page
tangem/tangem-app-ios-old pull request #399
Opened 2022-05-24 21:42 UTC by gre4ixin

2022-05-24 21:44 UTC, gre4ixin commented
[Task](https://tangem.atlassian.net/browse/IOS-1667)

2022-05-26 04:43 UTC, megakoko commented
Будут конфликты, я updateCompletedPublisher удалил и отрефакторил все немножко.

https://github.com/tangem/tangem-app-ios/pull/390

2022-05-26 05:37 UTC, megakoko requested changes

2022-05-26 05:37 UTC, megakoko commented on Tangem/App/ViewModels/CardViewModel.swift
> +    private var walletBalanceBag: AnyCancellable? = nil
Это не Bag, а Subscription. Bag несколько подписок держит.

2022-05-26 05:37 UTC, megakoko commented on Tangem/App/ViewModels/CardViewModel.swift
> +        case balancesLoaded
Если balances это префикс, его можно удалить из кейсов.

2022-05-26 05:37 UTC, megakoko commented on Tangem/App/ViewModels/WalletModel.swift
> +        var mainPageErrorDescription: String? {
Не очень хорошо, когда WalletModel знает что-то там о главном экране.

`errorDescription` занят, может `fatalErrorDescription` / `failureDescription`?

2022-05-26 05:37 UTC, megakoko commented on Tangem/Common/Extensions/Color+.swift
> +    }
Ни один из других серых цветов не был хотя бы приблизительно похож на нужный?

2022-05-26 05:37 UTC, megakoko commented on Tangem/Common/ImpactFeedback/ImpactFeedback.swift
> -class ImpactGenerator {
Ты этот файл разве не удалял уже?

2022-05-26 05:37 UTC, megakoko commented on Tangem/Common/Localizations/de.lproj/Localizable.strings
> +"main_manage_tokens" = "Manage tokens";
Зачем переименовал?

2022-05-26 05:37 UTC, megakoko commented on Tangem/Common/Localizations/en.lproj/Localizable.strings
> +"wallet_balance_blockchain_unreachable" = "Network is unreachable";
В русской локализации не надо менять эту текстовку?

2022-05-26 05:37 UTC, megakoko commented on Tangem/Main/MainViewModel.swift
> -    // MARK: - Scan
Не удаляй такие вещи, надо централизовано пройтись по проекту и решить, что из закоментированного нам нужно, а что нет.

2022-05-26 05:37 UTC, megakoko commented on Tangem/Main/TotalSumBalance/TotalSumBalanceView.swift
> -                Text("main_page_balance".localized.uppercased())
Видишь как удобно, а так пришлось бы лезть в локализацию, там обновлять.

2022-05-26 05:37 UTC, megakoko commented on Tangem/Main/TotalSumBalance/TotalSumBalanceView.swift
> +                    .frame(width: 15, height: 1)
`—` — такая штуковина тут не подойдет? Em dash называется.

2022-05-26 05:37 UTC, megakoko commented on Tangem/Main/TotalSumBalance/TotalSumBalanceViewModel.swift
> +        tokenItems = tokens
Переименуй tokenItems во что-то другое, можно в tokenItemViewModels. У нас есть перечисление TokenItem, такое название переменной будет вводить в заблуждение.

2022-05-26 05:37 UTC, megakoko commented on Tangem/Main/TotalSumBalance/TotalSumBalanceViewModel.swift
> +        var hasBlockchainError = false
Если переменная используется только в sink, то там ее и надо определять.

2022-05-26 05:37 UTC, megakoko commented on Tangem/Main/TotalSumBalance/TotalSumBalanceViewModel.swift
> +        var hasBlockchainError = false
Можно проще назвать — hasErrors. 

isSuccesfullyLoaded ведь не дает нам каких-то причин, из-за блокчейна оно не загрузилось или нет.

2022-05-26 05:37 UTC, megakoko commented on Tangem/Main/TotalSumBalance/TotalSumBalanceViewModel.swift
> +        refresh(with: false)
Что значит "обновить(с: ложь)"?

2022-05-26 05:37 UTC, megakoko commented on Tangem/Main/TotalSumBalance/TotalSumBalanceViewModel.swift
> +                    self.isFailed = hasBlockchainError
Перенеси этот код в stopLoading, пусть этот метод полностью заведует isFailed. Удобнее в одном месте устанавливать переменную в одном месте, чем в двух.

2022-05-26 05:37 UTC, megakoko commented on Tangem/MultiWallet/WalletsList/TokenItemView.swift
> +                        .skeleton(with: isLoading, size: CGSize(width: 70, height: 11))
Если мы изменим размер шрифта, то высоту этого скелетона тоже надо будет менять?

2022-05-26 07:17 UTC, gre4ixin commented on Tangem/App/ViewModels/CardViewModel.swift
> +    private var walletBalanceBag: AnyCancellable? = nil
поправил

2022-05-26 07:18 UTC, gre4ixin commented on Tangem/App/ViewModels/CardViewModel.swift
> +        case balancesLoaded
поправил

2022-05-26 07:19 UTC, gre4ixin commented on Tangem/App/ViewModels/WalletModel.swift
> +        var mainPageErrorDescription: String? {
поправил на failureDescription

2022-05-26 07:20 UTC, gre4ixin commented on Tangem/Main/TotalSumBalance/TotalSumBalanceViewModel.swift
> +        tokenItems = tokens
поправил

2022-05-26 07:23 UTC, gre4ixin commented on Tangem/Main/TotalSumBalance/TotalSumBalanceViewModel.swift
> +        var hasBlockchainError = false
поправил

2022-05-26 07:28 UTC, gre4ixin commented on Tangem/Common/Localizations/de.lproj/Localizable.strings
> +"main_manage_tokens" = "Manage tokens";
подогнал под файл локализаций

2022-05-26 07:31 UTC, gre4ixin commented on Tangem/Common/Localizations/en.lproj/Localizable.strings
> +"wallet_balance_blockchain_unreachable" = "Network is unreachable";
да, поправил

2022-05-26 07:33 UTC, gre4ixin commented on Tangem/Main/MainViewModel.swift
> -    // MARK: - Scan
если он понадобится, по диффу легко можно будет найти в xcode, куча комментированного кода усложняет поиск

2022-05-26 07:43 UTC, gre4ixin commented on Tangem/Main/TotalSumBalance/TotalSumBalanceViewModel.swift
> +        refresh(with: false)
поправил

2022-05-26 07:48 UTC, gre4ixin commented on Tangem/Common/Extensions/Color+.swift
> +    }
был, но в дизайне этот цвет, а задача по дизайну все шрифты, цвета и прочее

2022-05-26 08:08 UTC, gre4ixin commented on Tangem/Main/TotalSumBalance/TotalSumBalanceView.swift
> +                    .frame(width: 15, height: 1)
заменил

2022-05-26 08:36 UTC, Balashov152 commented on Podfile
> +  pod 'SkeletonUI'
Я бы конечно использовал свой вариант, может прям из этой библиотеки вытащить

2022-05-26 09:10 UTC, gre4ixin commented on Tangem/MultiWallet/WalletsList/TokenItemView.swift
> +                        .skeleton(with: isLoading, size: CGSize(width: 70, height: 11))
размеры скелетона брал из дизайна, если без размеров, то он будет тянуться во всю ширину вьюхи

2022-05-26 10:43 UTC, megakoko commented on Tangem/Common/Extensions/Color+.swift
> +    }
Если хотя бы примерно похож — используй, пожалуйста, существующий. А то без какого-то дизайнерского UIKit'а наш Color+ превратится в 50 оттенков серого и зеленого.

2022-05-26 10:43 UTC, gre4ixin commented on Podfile
> +  pod 'SkeletonUI'
я думал над тем, чтобы вынести, но не знаю на сколько в этом профит есть, так мы в любой момент можем избавиться от этого через кокоаподс

2022-05-26 10:44 UTC, megakoko commented on Tangem/Main/TotalSumBalance/TotalSumBalanceViewModel.swift
> +        tokenItems = tokens
Немного не так

tokenItemsViewModel — это вью-модель, отвечающая за массив tokenItems.

У нас массив моделей tokenItem — tokenItemViewModel**s**

2022-05-26 10:46 UTC, megakoko commented on Tangem/MultiWallet/WalletsList/TokenItemView.swift
> +                        .skeleton(with: isLoading, size: CGSize(width: 70, height: 11))
Можно ограничить только ширину без высоты?

2022-05-26 10:46 UTC, megakoko commented on Tangem/MultiWallet/WalletsList/TokenItemView.swift
> +                        .skeleton(with: isLoading, size: CGSize(width: 70, height: 11))
Или сделать чтобы текст не растягивался. Не хочется так хардкодить размеры.

2022-05-26 10:48 UTC, gre4ixin commented on Tangem/MultiWallet/WalletsList/TokenItemView.swift
> +                        .skeleton(with: isLoading, size: CGSize(width: 70, height: 11))
это CGSize ведь

2022-05-26 10:51 UTC, megakoko commented on Tangem/Common/Localizations/de.lproj/Localizable.strings
> +"main_manage_tokens" = "Manage tokens";
У нас уже был main_manage_tokens_button в локализации, на вкладке app-ios.

2022-05-26 10:53 UTC, megakoko commented on Tangem/Common/Localizations/en.lproj/Localizable.strings
> +"wallet_balance_blockchain_unreachable" = "Network is unreachable";
В табличке тоже тогда.

2022-05-26 10:56 UTC, megakoko commented on Tangem/Main/MainViewModel.swift
> -    // MARK: - Scan
Я согласен, но надо это сделать раз и по всему проекту. Иначе ты свое внимание на это тратишь, я как ревьювер внимание трачу, и т.д.

2022-05-26 10:57 UTC, megakoko commented on Podfile
> +  pod 'SkeletonUI'
А что она делает вообще? Фигурку рисует по аналогии с redacted?

2022-05-26 10:57 UTC, megakoko commented on Tangem/MultiWallet/WalletsList/TokenItemView.swift
> +                        .skeleton(with: isLoading, size: CGSize(width: 70, height: 11))
Ну может там другие перегрузки есть.

2022-05-26 10:57 UTC, gre4ixin commented on Tangem/Common/Localizations/en.lproj/Localizable.strings
> +"wallet_balance_blockchain_unreachable" = "Network is unreachable";
в табличку добавил

2022-05-26 10:58 UTC, gre4ixin commented on Tangem/Common/Localizations/de.lproj/Localizable.strings
> +"main_manage_tokens" = "Manage tokens";
да, но потом ключ изменили, я обновил в проекте тоже

2022-05-26 11:03 UTC, gre4ixin commented on Tangem/MultiWallet/WalletsList/TokenItemView.swift
> +                        .skeleton(with: isLoading, size: CGSize(width: 70, height: 11))
других нет

2022-05-26 11:19 UTC, megakoko commented on Tangem/Common/Localizations/de.lproj/Localizable.strings
> +"main_manage_tokens" = "Manage tokens";
Вот со старым ключем:

<img width="1018" alt="Screenshot 2022-05-26 at 15 18 37" src="https://user-images.githubusercontent.com/12209839/170477970-37e691d5-0ade-4626-80d7-c6e9cd7a5ee5.png">

2022-05-26 12:55 UTC, gre4ixin commented on Tangem/Common/Localizations/de.lproj/Localizable.strings
> +"main_manage_tokens" = "Manage tokens";
мы ведь ориентируемся на APP FINAL

2022-05-26 13:03 UTC, megakoko commented on Tangem/Common/Localizations/de.lproj/Localizable.strings
> +"main_manage_tokens" = "Manage tokens";
Не совсем. 

ios-app — это текстовки, которые у нас были до того как мы решили всерьез заняться синхронизацией локализации. Там бардак, на каждой платформе свой текст, свои идентификаторы. Но те текстовки еще используются, мы их меняем и иногда при необходимости удаляем.

App final — это уже синхронизированные между платформами текстовки. Все новое добавляем сюда.

@Balashov152 тоже будет полезно

2022-05-26 13:25 UTC, megakoko commented on Tangem/Common/Localizations/de.lproj/Localizable.strings
> +"main_manage_tokens" = "Manage tokens";
Удали тогда из ios-app

2022-05-26 13:27 UTC, gre4ixin commented on Tangem/Common/Localizations/de.lproj/Localizable.strings
> +"main_manage_tokens" = "Manage tokens";
удалил

2022-05-26 13:36 UTC, megakoko commented on Tangem/MultiWallet/WalletsList/TokenItemView.swift
> +                        .skeleton(with: isLoading, size: CGSize(width: 70, height: 11))
Попробуй такой костыль:
```
Text("$99999999")
    .lineLimit(1)
    .font(Font.system(size: 28, weight: .semibold))
    .foregroundColor(Color.tangemGrayDark6)
    .fixedSize(horizontal: true, vertical: true)
    .frame(height: 33)
    .overlay(
        Color.clear
            .skeleton(with: true)
            .shape(type: .rounded(.radius(3, style: .circular)))
    )
```

2022-05-27 07:43 UTC, Balashov152 commented on Podfile
> +  pod 'SkeletonUI'
Договорились оставить зависимость с точной версией)

2022-05-27 07:43 UTC, Balashov152 approved these changes

2022-05-27 07:45 UTC, megakoko approved these changes

2022-05-27 10:27 UTC, tureck1y approved these changes

2022-05-27 10:38 UTC, merged

2022-07-07 06:03 UTC, megakoko commented on Tangem/Common/Localizations/ru.lproj/Localizable.strings
> +"wallet_balance_blockchain_unreachable" = "Сеть недоступна";
@gre4ixin в табличке по этому идентификатору текст "Блокчейн недоступен". Перепроверь пожалуйста текстовки и обнови где необходимо.