IOS-8084 [Staking] Rewards schedule
tangem/tangem-app-ios-old pull request #3992
Opened 2024-10-02 19:24 UTC by Balashov152

Чуток подожду с обновлением slippage

2024-10-03 15:34 UTC, tureck1y commented
из-за локализаций падает

2024-10-03 15:40 UTC, tureck1y requested changes

2024-10-03 15:40 UTC, tureck1y commented on TangemFoundation/Extensions/Foundation/DateComponentsFormatter.swift
> +public extension DateComponentsFormatter {
Давай лучше в какой-то фабрике стейкинга сделаем, а то мало того что в Foundation, да еще и в общий скоп попадает

2024-10-04 07:43 UTC, Balashov152 commented on Tangem/App/Services/EnvironmentProvider/StakingFeatureProvider.swift
> +            StakingItem(network: .ethereum, contractAddress: TangemStaking.Constants.polygonContactAddress),
Убрал хардкод в разным местах в одну `TangemStaking.Constants`

2024-10-04 07:48 UTC, tureck1y approved these changes

2024-10-04 07:49 UTC, merged