IOS-1644 Add < symbol for fee in tron tokens
tangem/tangem-app-ios-old pull request #400
Opened 2022-05-26 11:53 UTC by Balashov152

2022-05-26 12:13 UTC, megakoko requested changes

2022-05-26 12:13 UTC, megakoko commented on Tangem/Send/SendViewModel.swift
> +
Вороти обратно пробелы

2022-05-26 12:13 UTC, megakoko commented on Tangem/Send/SendViewModel.swift
> +            return amountDescription
Если getFiatFormatted не сможет отформатировать, то вернется amount.description.

Предлагаю `if isFiat { ... ?? "" }  else { ... ?? "" }`

2022-05-26 12:13 UTC, megakoko commented on Tangem/Send/SendViewModel.swift
> +        let feeDummyAmount = Amount(with: walletModel.wallet.blockchain, type: .coin, value: 0)
Есть Amount.zeroCoin

Лучше dummyFeeAmount, ну или прямо в вызов formattedFee засунуть

2022-05-26 12:13 UTC, megakoko commented on Tangem/Send/SendViewModel.swift
> +        var formatted: String
Должно быть константой, т.к. не меняется в коде.

2022-05-26 12:13 UTC, megakoko commented on Tangem/Send/SendViewModel.swift
> +    func needToShowGreaterThanSymbol() -> Bool {
Лучше назвать "isFeeApproximate", чтобы не завязываться на какой-то определенный символ. Тем-более мы используем символ "меньше чем", а не "больше чем" как в названии.

Можно сделать private переменной.

2022-05-26 13:36 UTC, Balashov152 commented on Tangem/Send/SendViewModel.swift
> +
Я верну, а в них смысл? Обычно их swiftformat убирает )

2022-05-26 13:37 UTC, Balashov152 commented on Tangem/Send/SendViewModel.swift
> +            return amountDescription
✅

2022-05-26 13:37 UTC, Balashov152 commented on Tangem/Send/SendViewModel.swift
> +        let feeDummyAmount = Amount(with: walletModel.wallet.blockchain, type: .coin, value: 0)
✅

2022-05-26 13:37 UTC, megakoko commented on Tangem/Send/SendViewModel.swift
> +
Наоборот же в xcode по православному пробелы сохраняются.

2022-05-26 13:38 UTC, Balashov152 commented on Tangem/Send/SendViewModel.swift
> +    func needToShowGreaterThanSymbol() -> Bool {
Переименовал ✅ 
Это все в private extension, по этому смысла добавлять private к каждому методу нет)

2022-05-26 13:38 UTC, Balashov152 commented on Tangem/Send/SendViewModel.swift
> +        var formatted: String
✅

2022-05-26 13:39 UTC, Balashov152 commented on Tangem/Send/SendViewModel.swift
> +
добавляет веса файлу ))

2022-05-26 13:42 UTC, megakoko commented on Tangem/Send/SendViewModel.swift
> +    func needToShowGreaterThanSymbol() -> Bool {
А, окей, я невнимательно читал...

2022-05-26 13:49 UTC, megakoko approved these changes

2022-05-26 14:00 UTC, gre4ixin approved these changes

2022-05-27 10:25 UTC, tureck1y approved these changes

2022-05-27 10:27 UTC, merged