IOS-8229 [Staking] Skip updating staking manager after approve
tangem/tangem-app-ios-old pull request #4045
Opened 2024-10-11 11:53 UTC by fedorov-d

Пока не финальное решение, скорее на обсудить. Проблема в следующем: вызов `updateAfterSendingTransaction` после исполнения транзакции на approve по длинной цепочке приводит к вызову `CommonStakingManager -> updateState()` в результате этого стейкинг менеджер оказывается в состоянии loading. В этот же момент после завершения approve вызывается `updateState` уже внутри `StakingModel` что приводит к вызову `CommonStakingManager -> estimateFee(action:)` в котором происходит падение в дефолтный ошибочный кейс из-за состояния `loading` в менеджере. Пока закрыл костылем, вроде работает, но решение сомнительное как по мне.

2024-10-14 07:16 UTC, Balashov152 commented on Tangem/Modules/Send/SendTransactionDispatcher/CommonSendTransactionDispatcher.swift
> +    func send(transaction: SendTransactionType, updateWalletAfterSending: Bool) async throws -> SendTransactionDispatcherResult {
я бы вот так предложил лучше
```suggestion
    func send(transaction: SendTransactionType, options: SendTransactionDispatcherOptions?) async throws -> SendTransactionDispatcherResult {
```

```
enum SendTransactionDispatcherOptions {
    case updateWallet
}

2024-10-14 08:50 UTC, fedorov-d commented on Tangem/Modules/Send/SendTransactionDispatcher/CommonSendTransactionDispatcher.swift
> +    func send(transaction: SendTransactionType, updateWalletAfterSending: Bool) async throws -> SendTransactionDispatcherResult {
поправил

2024-10-14 09:11 UTC, Balashov152 commented on Podfile.lock
> -PODFILE CHECKSUM: 132799f98da8bc986f49e63c0731d125fa64189d
чет лишнее )

2024-10-14 11:56 UTC, Balashov152 approved these changes, later dismissed

2024-10-14 13:54 UTC, tureck1y requested changes
Либо давайте сделаем отдельный менеджер, либо обсудим

2024-10-14 16:06 UTC, tureck1y commented
может это получится на уровне моделей стейкинг/анстейкинг/сенд разруливать?

2024-10-15 06:10 UTC, fedorov-d commented
> может это получится на уровне моделей стейкинг/анстейкинг/сенд разруливать?

там тоже не очень удобно, помимо моделей этот код еще вызывается в ExpressInteractor-е и WalletConnectV2SendTransactionHandler, в 8 мест придется добавлять вызов. Сергей предложил еще один вариант как пофиксить, сейчас потестирую его.

2024-10-15 06:40 UTC, fedorov-d commented
в общем-то решение Сергея тоже работает https://github.com/tangem/tangem-app-ios/compare/releases/5.17...temp/Wait-when-CommonStakingManager-did-load?expand=1

2024-10-15 08:23 UTC, Balashov152 commented
> в общем-то решение Сергея тоже работает https://github.com/tangem/tangem-app-ios/compare/releases/5.17...temp/Wait-when-CommonStakingManager-did-load?expand=1

Его бы тоже залить надо, так как не обязательно при approve кейсе это стрельнет, у меня было еще и в других местах раньше. Например на StakingDetails дернуть PTR, и сразу же пока `loading` открыть `unstaking flow`

2024-10-15 09:54 UTC, fedorov-d commented
> > в общем-то решение Сергея тоже работает https://github.com/tangem/tangem-app-ios/compare/releases/5.17...temp/Wait-when-CommonStakingManager-did-load?expand=1
> 
> Его бы тоже залить надо, так как не обязательно при approve кейсе это стрельнет, у меня было еще и в других местах раньше. Например на StakingDetails дернуть PTR, и сразу же пока `loading` открыть `unstaking flow`

использовал его

2024-10-15 09:55 UTC, tureck1y approved these changes

2024-10-15 10:11 UTC, Balashov152 approved these changes

2024-10-15 11:34 UTC, merged