iOS-8282 [Staking] analytics errors track
tangem/tangem-app-ios-old pull request #4107
Opened 2024-10-23 09:54 UTC by fedorov-d

Добавил проброс токена в аналитику стейкинга. Также добавил отправку http ошибки если не удалось распарсить ответ от стейккита.

2024-10-23 09:56 UTC, fedorov-d commented on Tangem/App/Factories/StakingFactories/StakingDependenciesFactory.swift
> +    func makePendingHashesSender(token: TokenItem? = nil) -> StakingPendingHashesSender {
тут сделать не опциональным достаточно геморно, обсудили с Лешей, что помониторим насколько много будет событий без инфы о токене, и если понадобится - доработаем.

2024-10-23 09:57 UTC, tureck1y requested changes
Надо наоборот аналитику вытащить, а не токен туда передавать, в итоге засорилась куча интерфейсов

2024-10-23 10:20 UTC, tureck1y commented
Думаю надо убирать этот логгер совсем и промаркировать точечно все вызовы в CommonStakingManager, если они все там и передавать токен, если он есть

2024-10-23 11:52 UTC, fedorov-d commented
> Думаю надо убирать этот логгер совсем и промаркировать точечно все вызовы в CommonStakingManager, если они все там и передавать токен, если он есть

CommonStakingManager не достаточно, нужно еще в CommonStakingPendingHashesSender, интерфейсы все равно пострадают, плюс в CommonStakingManager придется добавить логику разбора ошибок.

2024-10-23 13:05 UTC, tureck1y commented
> CommonStakingManager не достаточно, нужно еще в CommonStakingPendingHashesSender, интерфейсы все равно пострадают, плюс в CommonStakingManager придется добавить логику разбора ошибок.

непонятно зачем sender, давай обсудим, такое решение как сейчас не ок

2024-10-24 11:04 UTC, tureck1y approved these changes

2024-10-24 11:08 UTC, Balashov152 approved these changes

2024-10-24 11:08 UTC, Balashov152 commented on TangemStaking/Services/StakingManager/CommonStakingManager.swift
> +                )
не крит, но вроде два раза `try await` можно не писать

```suggestion
            return try await execute(provider.estimateStakeFee(
                    request: mapToActionGenericRequest(action: action)
                )
```

2024-10-24 11:08 UTC, merged

2024-10-24 11:09 UTC, tureck1y commented on TangemStaking/Services/StakingManager/CommonStakingManager.swift
> +                )
@fedorov-d посмотри плиз, уже отдельно потом в девелоп