IOS 8249 bsdk krc20
tangem/tangem-app-ios-old pull request #4144
Opened 2024-11-01 08:25 UTC by siblockchaina

2024-11-08 14:59 UTC, dbaturin requested changes

2024-11-08 14:59 UTC, dbaturin commented on BlockchainSdk/Blockchains/Kaspa/KaspaFeeMapper.swift
> +    }
Почти одинаковые функции, можно одну оставить, а во второй доставать массу из респонса и первую вызывать. Или я что-то упустил?

2024-11-08 14:59 UTC, dbaturin commented on BlockchainSdk/Blockchains/Kaspa/KaspaKRC20/KaspaKRC20.swift
> +    static let RevealTransactionMassConstant: Decimal = 3000
Захардкоженную массу решили увеличить на всякий случай.

2024-11-08 14:59 UTC, dbaturin commented on BlockchainSdk/Blockchains/Kaspa/KaspaKRC20/KaspaNetworkProviderKRC20.swift
> +        url = testnet ? URL("https://tn10api.kasplex.org/v1")! : URL("https://api.kasplex.org/v1/")!
Вот это надо было бы подсветить, кстати, что у нас всего одна апиха для получения баланса токенов. Надо может попробовать в чатике Касплексовцев спросить про резервную

2024-11-08 14:59 UTC, dbaturin commented on BlockchainSdk/Blockchains/Kaspa/KaspaTransactionBuilder.swift
> +    func buildForMassCalculationKRC20(transaction: Transaction, token: Token) throws -> (commit: KaspaTransactionData, reveal: KaspaTransactionData) {
Не используется сейчас? Может удалить

2024-11-13 13:27 UTC, tureck1y requested changes
Я верхнеуровнево комменты накидал, в логику не вдавался

2024-11-13 13:27 UTC, tureck1y commented on BlockchainSdk/Common/Blockchain.swift
> +             .kaspa:
кастомные токены поддерживаем, там все ок?

2024-11-13 13:27 UTC, tureck1y commented on BlockchainSdk/Blockchains/Kaspa/KaspaWalletManager.swift
> +        cancellable = Publishers.Zip(
надо бы сделать так, что неудачный запрос баланса по токенам не фейлил баланс самомй монеты

2024-11-13 13:27 UTC, tureck1y commented on BlockchainSdk/Blockchains/Kaspa/KaspaWalletManager.swift
> +        let kaspaCommitTransaction: KaspaTransaction
Надо бы весь код в реактивном контексте написать. Сам метод очень большой и компиллятору будет трудно и разработчикам читать, надо бы побить

2024-11-13 13:27 UTC, tureck1y commented on BlockchainSdk/Blockchains/Kaspa/KaspaWalletManager.swift
> +         */
тут и далее ожидается какое-то обсудение? Надо бы подчистить

2024-11-13 13:27 UTC, tureck1y commented on BlockchainSdk/Blockchains/Kaspa/KaspaTransactionBuilder.swift
> +    public func buildCommitTransactionKRC20(transaction: Transaction, token: Token, includeFee: Bool = true) throws -> KaspaKRC20.CommitTransction {
Опять же оч сложный метод, давай хотя бы комментов добавим где что происходит

2024-11-13 13:27 UTC, tureck1y commented on BlockchainSdk/Blockchains/Kaspa/KaspaTransactionBuilder.swift
> +            ()
break?

2024-11-13 13:27 UTC, tureck1y commented on BlockchainSdk/Blockchains/Kaspa/KaspaKRC20/KaspaNetworkProviderKRC20.swift
> +        url = testnet ? URL("https://tn10api.kasplex.org/v1")! : URL("https://api.kasplex.org/v1/")!
только урл давай в ассембли передавать, пусть и хардкодом

2024-11-13 13:27 UTC, tureck1y commented on BlockchainSdk/Blockchains/Kaspa/KaspaFeeMapper.swift
> +        .suffix(3) // select the 3 largest baskets
Этот код есть уже выше в mapFee, давай вынесем в функцию и переиспользуем

2024-11-13 16:24 UTC, m3g0byt3 commented on BlockchainSdk/Blockchains/Kaspa/KaspaKRC20/KaspaKRC20.swift
> +            let payload = "{\"amt\":\"\(amt)\",\"op\":\"\(op)\",\"p\":\"\(p)\",\"tick\":\"\(tick)\",\"to\":\"\(to)\"}".data(using: .utf8)!
Эту сериализацию надо будет переделать на codable

2024-11-14 09:21 UTC, siblockchaina commented on BlockchainSdk/Blockchains/Kaspa/KaspaFeeMapper.swift
> +    }
убрал

2024-11-14 09:22 UTC, siblockchaina commented on BlockchainSdk/Blockchains/Kaspa/KaspaKRC20/KaspaKRC20.swift
> +    static let RevealTransactionMassConstant: Decimal = 3000
увеличил до 4100

2024-11-14 09:23 UTC, siblockchaina commented on BlockchainSdk/Blockchains/Kaspa/KaspaTransactionBuilder.swift
> +    func buildForMassCalculationKRC20(transaction: Transaction, token: Token) throws -> (commit: KaspaTransactionData, reveal: KaspaTransactionData) {
используется, убрал из нее сборку reveal, т.к хардкод

2024-11-14 09:37 UTC, siblockchaina commented on BlockchainSdk/Blockchains/Kaspa/KaspaTransactionBuilder.swift
> +            ()
+

2024-11-14 09:44 UTC, siblockchaina commented on BlockchainSdk/Blockchains/Kaspa/KaspaFeeMapper.swift
> +        .suffix(3) // select the 3 largest baskets
вынес

2024-11-19 12:11 UTC, siblockchaina commented on BlockchainSdk/Blockchains/Kaspa/KaspaWalletManager.swift
> +         */
удалено

2024-11-19 12:11 UTC, siblockchaina commented on BlockchainSdk/Blockchains/Kaspa/KaspaTransactionBuilder.swift
> +    public func buildCommitTransactionKRC20(transaction: Transaction, token: Token, includeFee: Bool = true) throws -> KaspaKRC20.CommitTransction {
добавил пояснений, старался максимально доступно

2024-11-19 12:11 UTC, siblockchaina commented on BlockchainSdk/Blockchains/Kaspa/KaspaWalletManager.swift
> +        let kaspaCommitTransaction: KaspaTransaction
вынес кусок в билдер, остальное догооврились не трогать

2024-11-19 12:13 UTC, siblockchaina commented on BlockchainSdk/Blockchains/Kaspa/KaspaWalletManager.swift
> +        cancellable = Publishers.Zip(
сетевые ошибки мапятся в словарь в `networkServiceKRC20.balance(address: wallet.address, tokens: cardTokens)`

2024-11-19 12:16 UTC, siblockchaina commented on BlockchainSdk/Blockchains/Kaspa/KaspaKRC20/KaspaKRC20.swift
> +            let payload = "{\"amt\":\"\(amt)\",\"op\":\"\(op)\",\"p\":\"\(p)\",\"tick\":\"\(tick)\",\"to\":\"\(to)\"}".data(using: .utf8)!
Договорились не трогать этот кусок

2024-11-19 12:22 UTC, siblockchaina commented on BlockchainSdk/Common/Blockchain.swift
> +             .kaspa:
вобще работает в bsdk, в апке надо проверить
добавил тут tokenTypeName для kaspa

2024-11-20 10:22 UTC, m3g0byt3 commented on Modules/Package.resolved
> -  "originHash" : "f4db68609e7f14bf89c4092c7c9275ff72bf1143baf6863092f268fafb155d01",
В деве не обновлен SPM lock, обновил его

2024-11-20 10:22 UTC, m3g0byt3 commented on TangemApp.xcworkspace/xcshareddata/swiftpm/Package.resolved
> -  "originHash" : "6b035953f736066530f0d187d9ba246ef7feaaf3f9e8bf5106f9f10b0ba6d560",
И тут

2024-11-21 13:07 UTC, m3g0byt3 reviewed
1. С учетом того, что апишка для токенов одна и она бета - надо обязательно сделать фоллбек, чтобы зафейленная загрузка токенов не фейлила каспу. Примерно как сделано тут https://github.com/tangem/tangem-app-ios/pull/4253

2. В ключах, по которым мы храним incomplete txs в сторейдже - надо учитывать адрес воллета, а не только контракт адрес токена. Сторейдж - это единый инстанс для всего BSDK и сейчас получается, что incomplete txs от одного воллета показываются в другом воллете, если на нем тоже добавлен этот токен.

2024-11-22 08:12 UTC, tureck1y submitted a review, later dismissed

2024-11-25 21:09 UTC, m3g0byt3 commented
> 1. С учетом того, что апишка для токенов одна и она бета - надо обязательно сделать фоллбек, чтобы зафейленная загрузка токенов не фейлила каспу. Примерно как сделано тут [IOS-7610 Don't fail balance loading on token error #4253](https://github.com/tangem/tangem-app-ios/pull/4253)
> 2. В ключах, по которым мы храним incomplete txs в сторейдже - надо учитывать адрес воллета, а не только контракт адрес токена. Сторейдж - это единый инстанс для всего BSDK и сейчас получается, что incomplete txs от одного воллета показываются в другом воллете, если на нем тоже добавлен этот токен.


1. Посмотрел внимательнее - фоллбек уже реализован в `KaspaNetworkServiceKRC20`
2. Добавил адрес воллета в ключ

2024-11-25 22:20 UTC, tureck1y approved these changes

2024-11-27 09:54 UTC, Balashov152 approved these changes

2024-11-27 09:54 UTC, ba1ashov commented on BlockchainSdk/Blockchains/Kaspa/KaspaFeeMapper.swift
> +        let mass = mass
как будто лишнее

2024-11-27 09:54 UTC, Balashov152 commented on BlockchainSdk/Blockchains/Kaspa/KaspaKRC20/KaspaNetworkServiceKRC20.swift
> +    private let blockchain: Blockchain
Как будто не используется, да и не нужен целый `enum Blockchain` здесь

2024-11-27 09:54 UTC, Balashov152 commented on BlockchainSdk/Blockchains/Kaspa/KaspaKRC20/KaspaNetworkServiceKRC20.swift
> +                .setFailureType(to: Error.self)
как будто `.setFailureType(to: Error.self)` лишний, раз `mapToResult` юзаем
и возвращать можно Never вместо Error

2024-11-27 10:28 UTC, skibinalexander approved these changes

2024-11-27 20:41 UTC, dbaturin approved these changes

2024-11-27 20:41 UTC, dbaturin commented on BlockchainSdk/Blockchains/Kaspa/KaspaTransactionBuilder.swift
> +            let commitTx = try buildCommitTransactionKRC20(transaction: transaction, token: token)
Странно, что только одну транзакцию возвращаем здесь

2024-11-27 20:41 UTC, dbaturin commented on BlockchainSdk/Blockchains/Kaspa/KaspaWalletManager.swift
> +                let revealSignatures = Array(signatures[txgroup.hashesCommit.count...])
Непонятный синтаксис какой-то. Но может это я в свифте плохо разбираюсь.

2024-11-28 09:38 UTC, m3g0byt3 approved these changes

2024-11-28 11:58 UTC, merged