IOS-8357 IOS-8158 IOS-8358 [Onramp] Country + Currency + Settings
tangem/tangem-app-ios-old pull request #4155
Opened 2024-11-04 10:45 UTC by amuraveinik

[IOS-8357](https://tangem.atlassian.net/browse/IOS-8357)
[IOS-8158](https://tangem.atlassian.net/browse/IOS-8158)
[IOS-8358](https://tangem.atlassian.net/browse/IOS-8358)

2024-11-04 10:50 UTC, amuraveinik commented on Tangem/Modules/OnrampCountrySelector/OnrampCountrySelectorView.swift
> +                placeholder: "Search by country",
TODO: Lokalise

2024-11-04 10:50 UTC, amuraveinik commented on Tangem/Modules/OnrampCountrySelector/OnrampCountrySelectorView.swift
> +                Text("Unavailable")
TODO: Lokalise

2024-11-04 10:50 UTC, amuraveinik commented on Tangem/Modules/OnrampCurrencySelect/OnrampCurrencySelectorView.swift
> +                placeholder: "Search by currency",
TODO: Lokalise

2024-11-04 10:50 UTC, amuraveinik commented on Tangem/Modules/OnrampSettings/OnrampSettingsView.swift
> +            Text("Please select the correct country to ensure accurate payment options and services.")
TODO: Lokalise

2024-11-04 10:50 UTC, amuraveinik commented on Tangem/Modules/OnrampSettings/OnrampSettingsView.swift
> +        .navigationBarTitle("Settings", displayMode: .inline)
TODO: Lokalise

2024-11-04 10:50 UTC, amuraveinik commented on Tangem/Modules/OnrampSettings/OnrampSettingsView.swift
> +            Text("Residence")
TODO: Lokalise

2024-11-04 10:50 UTC, AlekseiMuraveinik1 commented on Tangem/Modules/Send/UI/Onramp/OnrampView/OnrampView.swift
> +                    viewModel.router?.openOnrampCurrencySelectorView()
@Balashov152 Тут нужен комментарий, архитектурно не понимаю куда этот вызов положить.
По идее у OnrampAmountView есть своя вьюмодель, но как оттуда вызвать роутер я не понимаю

2024-11-04 10:50 UTC, AlekseiMuraveinik1 commented on TangemExpress/Manager/OnrampDataRepository/OnrampDataRepository.swift
> +    var popularFiats: [OnrampFiatCurrency] {
Тут как договаривались - захардкожено просто на клиенте

2024-11-04 10:50 UTC, AlekseiMuraveinik1 commented on Tangem/Modules/OnrampCurrencySelect/OnrampCurrencySelectorViewModel.swift
> +            title: "Popular Fiats",
TODO: Lokalise `onramp_currency_popular`

2024-11-04 10:50 UTC, AlekseiMuraveinik1 commented on Tangem/Modules/OnrampCurrencySelect/OnrampCurrencySelectorViewModel.swift
> +            title: "Other currencies",
TODO: Lokalise `onramp_currency_other`

2024-11-04 11:12 UTC, amuraveinik commented on Tangem/Modules/OnrampCountrySelector/OnrampCountrySelectorView.swift
> +                placeholder: "Search by country",
`onramp_country_search`

2024-11-05 11:49 UTC, Balashov152 requested changes
Вообще правильно одна задача - один MR. Плюс там есть апдейт по дизайну с `error` и `loading` стейтами. Тут много достаточно что бы хорошо посмотреть

2024-11-05 11:49 UTC, Balashov152 commented on Tangem/Modules/OnrampCountrySelector/OnrampCountrySelectorView.swift
> +    private func rowViewLabel(country: OnrampCountry) -> some View {
Лучше в отдельную view. Что то типо `OnrampCountryRowView` / `OnrampCountryRowViewData`

2024-11-05 11:49 UTC, Balashov152 commented on Tangem/Modules/OnrampCountrySelector/OnrampCountrySelectorViewModel.swift
> +        }
Можно так)
```suggestion
        .replaceError(with: [])
```

2024-11-05 11:49 UTC, Balashov152 commented on Tangem/Modules/OnrampCountrySelector/OnrampCountrySelectorViewModel.swift
> +    @Published private(set) var countries: [OnrampCountry] = []
И здесь будет `[OnrampCountryRowViewData]`

2024-11-05 11:49 UTC, Balashov152 commented on Tangem/Modules/OnrampCountrySelector/OnrampCountrySelectorViewModel.swift
> +    @Published private(set) var countries: [OnrampCountry] = []
А пока загрузка идет? Надо наверное через `LoadingValue<[OnrampCountryRowViewData]>` делать, что бы разные View были

2024-11-05 11:49 UTC, Balashov152 commented on Tangem/Modules/OnrampCurrencySelect/OnrampCurrencySelectorView.swift
> +                .padding(.vertical, 8)
Это есть уже
```suggestion
      GrabberViewFactory().makeSwiftUIView()
```

2024-11-05 11:49 UTC, Balashov152 commented on Tangem/Modules/OnrampCurrencySelect/OnrampCurrencySelectorView.swift
> +    private func rowViewLabel(currency: OnrampFiatCurrency) -> some View {
Тоже бы в `OnrampFiatCurrencyView` / `OnrampFiatCurrencyViewData`

2024-11-05 11:49 UTC, Balashov152 commented on Tangem/Modules/OnrampCurrencySelect/OnrampCurrencySelectorViewModel.swift
> +private func mapToSections(
А почему не в классе ?)

2024-11-05 11:49 UTC, Balashov152 commented on Tangem/Modules/OnrampSettings/OnrampSettingsView.swift
> +            Text("Please select the correct country to ensure accurate payment options and services.")
Вообще это можно сделать через GroupedSection, там есть footer: который везде через `DefaultFooterView` делаем

2024-11-05 11:49 UTC, Balashov152 commented on Tangem/Modules/OnrampSettings/OnrampSettingsView.swift
> +                .cornerRadius(14, corners: .allCorners)
```suggestion
                .cornerRadiusContinuous(14)
```

2024-11-05 11:49 UTC, Balashov152 commented on Tangem/Modules/OnrampSettings/OnrampSettingsView.swift
> +                    .foregroundColor(Colors.Text.primary1)
Обычно используем общий метод 
```suggestion
                    .style(Fonts.Regular.subheadline, color: Colors.Text.primary1)
```

2024-11-05 11:49 UTC, Balashov152 commented on Tangem/Modules/OnrampSettings/OnrampSettingsView.swift
> +                .foregroundColor(Colors.Icon.informative)
```suggestion
            Assets.chevronRightWithOffset24.image
                .resizable()
                .frame(size: .init(bothDimensions: 24))
                .foregroundColor(Colors.Icon.informative)
```

2024-11-05 11:49 UTC, Balashov152 commented on Tangem/Modules/OnrampSettings/OnrampSettingsView.swift
> +        .padding(.vertical, 11)
Вообще с дизайнерами договаривались что паддинги всегда кратные 2ум
либо 10 либо 12, может коммент в фигме оставить, обычно это просто косяк макета

2024-11-05 11:49 UTC, Balashov152 commented on Tangem/Modules/OnrampSettings/OnrampSettingsViewModel.swift
> +            .assign(to: &$selectedCountry)
без `store(in: )` не имеет смысла же
```suggestion
        selectedCountry  = repository.preferenceCountry
```

2024-11-05 11:49 UTC, Balashov152 commented on Tangem/Modules/Send/UI/Base/SendCoordinatorView.swift
> +        NavigationView {
Send / Sell / Staking не сломались? Проверь плиз

2024-11-05 11:49 UTC, Balashov152 commented on Tangem/Modules/Send/UI/Onramp/OnrampView/OnrampView.swift
> +                    viewModel.router?.openOnrampCurrencySelectorView()
не, точно не тут

Получается надо добавить `OnrampAmountRoutable` с этим методом, и потом проставить router в `OnrampAmountViewModel`, в `OnrampFlowBaseBuilder`

и уже через router открыть, а сам `OnrampAmountRoutable` будет `SendViewModel` подерживать, так же как и `OnrampSummaryRoutable`

2024-11-05 11:49 UTC, Balashov152 commented on TangemExpress/Manager/OnrampDataRepository/OnrampDataRepository.swift
> +    var popularFiats: [OnrampFiatCurrency] {
Я думаю лучше просто `code` хардкодить ["GBP", "USD"] целая модель то не нужна

2024-11-05 11:49 UTC, Balashov152 commented on TangemExpress/Manager/OnrampDataRepository/OnrampDataRepository.swift
> +    nonisolated var countriesPublisher: AnyPublisher<[OnrampCountry], Error> {
а зачем так сложно, можно через Task во ViewModel  делать
Это же не паблишер, а только один запрос - ответ

2024-11-05 12:53 UTC, amuraveinik commented on Tangem/Modules/OnrampSettings/OnrampSettingsView.swift
> +            Text("Please select the correct country to ensure accurate payment options and services.")
Я хотел тут использовать по аналогии как в настройках приложения, но:
1. GroupedSection не подходит тут по отсупам.
2. DefaultRowView не подходит тут по шрифту
3. DefaultFooterView не подходит тут по шрифту

2024-11-05 14:58 UTC, amuraveinik commented on Tangem/Modules/OnrampSettings/OnrampSettingsViewModel.swift
> +            .assign(to: &$selectedCountry)
.assign(to: ) работает не так как обычные паблишеры, глянь эпл доку

2024-11-05 14:58 UTC, amuraveinik commented on Tangem/Modules/Send/UI/Base/SendCoordinatorView.swift
> +        NavigationView {
Вроде все ок

2024-11-05 15:29 UTC, amuraveinik commented on Tangem/Modules/OnrampCountrySelector/OnrampCountrySelectorViewModel.swift
> +        }
Стало неактуально как только появились стейты ошбика

2024-11-05 15:30 UTC, amuraveinik commented on Tangem/Modules/OnrampSettings/OnrampSettingsViewModel.swift
> +            .assign(to: &$selectedCountry)
https://developer.apple.com/documentation/combine/publisher/assign(to:)

2024-11-05 15:32 UTC, amuraveinik commented
В общем, я сделал выводы что лучше сразу делать все в разный PRах.
Этот уже сложно разделить, но я сделал разбивку по коммитам к каждой задаче для удобства ревьюера

2024-11-05 16:25 UTC, Balashov152 commented on Tangem/App/Utilities/SearchUtil.swift
> +        let loweccasedSearchText = searchText.lowercased()
может еще `trimmed` ?
```suggestion
        let loweccasedSearchText = searchText.lowercased().trimmed()
```

2024-11-05 16:25 UTC, Balashov152 commented on Tangem/Modules/OnrampCountrySelector/OnrampCountrySelectorViewModel.swift
> +        .assign(to: &$countries)
Как то сложно получается

1. Можно все сделать через Task, который будет ходить за `countries` так как они там тоже лежат в кэше. 
2. получается что изначально у тебя self.countries = .loading. Потом ты вызываешь метод `updateView(searchText: "")` и "без поиска" обновляешь View с данными из репозитория.
3. По подписке в методе `bind()` подписываешься на $searchText. и там вызываешь этот же метод `updateView(searchText: searchText)`. Все делаешь в одном Таске, отменяя его, сохранив при этом в проперти класса. И плюс сортировку можно делать тоже в background потоке, и потом просто через `await runOnMain {} ` обновлять список

2024-11-05 16:25 UTC, Balashov152 commented on Tangem/Modules/OnrampCountrySelector/Subviews/OnrampCountryViewData.swift
> +    let isSelected: Bool
nit: Как будто можно через `enum DetailsType` сделать, что бы по switch case во View проходить, но так тоже норм )

2024-11-05 16:25 UTC, Balashov152 commented on Tangem/Modules/OnrampCurrencySelector/OnrampCurrencySelectorView.swift
> +        MarketsUnableToLoadDataView(
Может переименовать ее как то более общее, а то в Markets поменяют, и даже не знаю что в onramp она же юзается )

2024-11-05 16:25 UTC, Balashov152 commented on Tangem/Modules/OnrampCurrencySelector/OnrampCurrencySelectorViewModel.swift
> +        .assign(to: &$currencies)
Тут тоже самое что и в `OnrampCountySelectorViewModel`

2024-11-05 16:25 UTC, Balashov152 commented on Tangem/Modules/OnrampCurrencySelector/Subviews/OnrampCurrencySkeletonView.swift
> +        .padding(.vertical, 15)
Как то смущают 15 и 7. Хорошо бы через PixelPerfect проверить, у нас CTO любит такое замечать )

2024-11-05 16:25 UTC, Balashov152 commented on Tangem/Modules/OnrampSettings/OnrampSettingsViewModel.swift
> +            .assign(to: &$selectedCountry)
хм, интересно, не знал

2024-11-05 16:25 UTC, Balashov152 commented on Tangem/Modules/Send/UI/Base/SendCoordinator.swift
> +    @Published var onrampSettingsViewModel: OnrampSettingsViewModel?
А это не надо делать через отдельный `coordinator`? Вроде понятно что и так должно работать, но не было бы проблем на старых осях, где SUI дальше чем одна View не может

2024-11-05 16:25 UTC, Balashov152 commented on Tangem/Modules/Send/UI/Base/SendCoordinatorView.swift
> +        .accentColor(Colors.Text.primary1)
`accentColor` вроде `deprecated`. Можно `tint` использовать

2024-11-05 16:26 UTC, Balashov152 commented on Tangem/Modules/OnrampCurrencySelector/Subviews/OnrampCurrencySkeletonView.swift
> +        .padding(.vertical, 15)
Глянь плиз в остальных местах, есть вот ответ от дизайна что должно быть 14 везде 
https://www.figma.com/design/ZJoUO3kZGCcVgOUbCMQcY4?node-id=38164-85535#1013677827

2024-11-05 18:36 UTC, AlekseiMuraveinik1 commented on Tangem/Modules/OnrampCountrySelector/OnrampCountrySelectorViewModel.swift
> +        .assign(to: &$countries)
Ну это уже вкусовщина, абсолютно никакой разницы в функционале нет.
Мне просто удобнее работать с реактивными последовательностями, потому что они тут органичнее встраиваются, например:
1. `$searchText` - это поток данных, самый что ни на есть
2. `countriesSubject` - тут как бы да, мы в него данные отправляем одноразово после асинхронного запроса, но если помнишь то в предыдущей версии я выкачку данных из репозитория тоже организовал через комбайн.

Короче после нескольких таких итераций получится что ты просто моими руками напишешь код который тебе самому больше нравится)

2024-11-05 18:59 UTC, amuraveinik commented on Tangem/Modules/OnrampCountrySelector/OnrampCountrySelectorViewModel.swift
> +        .assign(to: &$countries)
Либо надо зафиксировать на уровне соглашения такой подход - что в приоритете используем async/await

2024-11-05 19:07 UTC, amuraveinik commented on Tangem/Modules/Send/UI/Base/SendCoordinator.swift
> +    @Published var onrampSettingsViewModel: OnrampSettingsViewModel?
Потестил на 
- 18.0 
- 17.5 
- 16.4 
- 15.5
По этому флоу все ок

2024-11-05 19:09 UTC, amuraveinik commented on Tangem/Modules/OnrampCurrencySelector/OnrampCurrencySelectorViewModel.swift
> +        .assign(to: &$currencies)
https://github.com/tangem/tangem-app-ios/pull/4155#discussion_r1829835879

2024-11-06 10:31 UTC, amuraveinik commented on Tangem/Modules/Send/UI/Base/SendCoordinator.swift
> +    @Published var onrampSettingsViewModel: OnrampSettingsViewModel?
На 15.5 не ок, сейчас запушу фикс

2024-11-06 10:40 UTC, amuraveinik commented on Tangem/Modules/Send/UI/Base/SendCoordinator.swift
> +    @Published var onrampSettingsViewModel: OnrampSettingsViewModel?
Запушил фикс

2024-11-06 12:58 UTC, Balashov152 commented on Tangem/Modules/OnrampCountrySelector/OnrampCountrySelectorViewModel.swift
> +        .assign(to: &$countries)
>Либо надо зафиксировать на уровне соглашения такой подход - что в приоритете используем async/await

Согласен, надо обсудить всем, просто учитывая будущий переход swift 6, то concurrency как будто более приоритетная штука

2024-11-06 12:59 UTC, Balashov152 submitted a review, later dismissed

2024-11-07 08:53 UTC, Andoran90 reviewed
не помню говорил или нет, но когда много чего сделано по UI прикладывайте видос или хотя бы скрины, что как работает, иногда помогает выявить бажки на ревью, во время изначальной разработки сенда много чего из скринкастов сразу выявлялось. + я не в контексте онрампа и тут МР на 1.1к строк, не особо легко ревьюить это все

2024-11-07 08:53 UTC, Andoran90 commented on Tangem/Common/UI/UnableToLoadDataView.swift
> +//  Created by Aleksei Muraveinik on 5.11.24..
вот так происходит переписывание истории! и добавляются лишние точки

2024-11-07 08:53 UTC, Andoran90 commented on Tangem/Modules/OnrampCountrySelector/OnrampCountrySelectorRoutable.swift
> +//  Created by Aleksei Muraveinik on 3.11.24..
откуда они у тебя берутся все время?.. есть некоторая недосказанность из-за этой второй точки)

2024-11-07 08:53 UTC, Andoran90 commented on Tangem/Modules/OnrampCountrySelector/OnrampCountrySelectorView.swift
> +            }
опционально:
можно вынести в отдельное `@ViewBuilder` свойство

2024-11-07 08:53 UTC, Andoran90 commented on Tangem/Modules/OnrampCountrySelector/OnrampCountrySelectorView.swift
> +            }
похоже тут не хватает анимированного перехода между стейстами

2024-11-07 08:53 UTC, Andoran90 commented on Tangem/Modules/OnrampCountrySelector/OnrampCountrySelectorViewModel.swift
> +        .assign(to: &$countries)
я бы предложил это вынести в `bind()` функцию, чтобы было похоже на то как сделано в большинстве мест. У нас изначально в сенде до рефака кое-что пошло не так и начали появляться огромные инициализаторы, давайте не будем так больше делать.

2024-11-07 08:53 UTC, Andoran90 commented on Tangem/Modules/OnrampCurrencySelector/OnrampCurrencySelectorView.swift
> +            }
то же что и `OnrampCountrySelectorView` на счет выноса в отдельное свойство и добавление анимации

2024-11-07 08:53 UTC, Andoran90 commented on Tangem/Modules/OnrampCurrencySelector/OnrampCurrencySelectorViewModel.swift
> +        .assign(to: &$currencies)
хм, а `.assign(to:on:)` утекал, надеюсь что этот не утекает
+ надо бы тоже перенести это в `bind()`

2024-11-07 08:53 UTC, Andoran90 commented on Tangem/Modules/Send/UI/Base/SendCoordinatorView.swift
> +        NavigationView {
а на всех осях чекнул, а то на 15 были проблемы с навигацией и навбаром

2024-11-08 14:11 UTC, amuraveinik commented on Tangem/Modules/Send/UI/Base/SendCoordinatorView.swift
> +        NavigationView {
Чуть выше обсудили
https://github.com/tangem/tangem-app-ios/pull/4155#discussion_r1830790869

2024-11-11 07:03 UTC, fedorov-d commented
на анимации видно что во время загрузки валют и стран проскакивает состояние "Unable to load data", это ок?

2024-11-11 08:04 UTC, amuraveinik commented
> на анимации видно что во время загрузки валют и стран проскакивает состояние "Unable to load data", это ок?

Да, это я специально для демки сделал, чтобы все стейты отобразились.
Там и делей в загрузке тоже увеличен

2024-11-11 08:18 UTC, fedorov-d commented on Tangem/App/Utilities/SearchUtil.swift
> +        let loweccasedSearchText = searchText.lowercased().trimmed()
nit: опечатка lowercasedSearchText

2024-11-11 09:02 UTC, Andoran90 approved these changes, later dismissed

2024-11-11 09:21 UTC, amuraveinik commented
@tureck1y @Andoran90 @Balashov152 @fedorov-d Гляньте повторно плз после фиксов

2024-11-11 09:24 UTC, Andoran90 submitted a review, later dismissed

2024-11-11 09:25 UTC, Balashov152 submitted a review, later dismissed

2024-11-11 12:25 UTC, fedorov-d submitted a review, later dismissed

2024-11-11 12:54 UTC, tureck1y commented on Tangem/Modules/OnrampCountrySelector/OnrampCountrySelectorRoutable.swift
> +//  Created by Aleksei Muraveinik on 3.11.24..
надо подчистить бы в икскоде темплейт, можно уже отдельным пуллом

2024-11-11 12:56 UTC, tureck1y commented on Tangem/Modules/OnrampCountrySelector/OnrampCountrySelectorViewModel.swift
> +        Task {
weak self забыл, у нас есть способ красиво эти таски вызывать с захватом, runtask или как-то так

2024-11-11 13:39 UTC, amuraveinik commented on Tangem/Modules/OnrampCountrySelector/OnrampCountrySelectorViewModel.swift
> +        Task {
Поменял на `runTask(in: self)` по аналогии как в других местах в проекте.
Если кроме этого все ок - вмерджи плз годмодом, от остальных оки были

2024-11-11 13:41 UTC, tureck1y commented on Tangem/Modules/OnrampCountrySelector/OnrampCountrySelectorViewModel.swift
> +        .assign(to: &$countries)
так, тут что-то не то. assign использовать нельзя, он держит ссылку сильно и будет утечка, для этого есть assign(... ownership: weak). Второй момент - а где хранение подписки в сумке?

Проверь пожалуйста остальные места и подебажь, что везде вызывается deinit

2024-11-11 13:41 UTC, tureck1y commented on Tangem/Modules/OnrampCurrencySelector/OnrampCurrencySelectorViewModel.swift
> +        Task {
про Task и weak везде писать не буду, нужно поправить и проверить на утечки через логи в deinit, можно профайлером еще

2024-11-11 13:41 UTC, tureck1y commented on Tangem/Modules/OnrampCurrencySelector/OnrampCurrencySelectorViewModel.swift
> +        .assign(to: &$currencies)
давайте не изобретать)

2024-11-11 13:41 UTC, tureck1y commented on Tangem/Modules/OnrampSettings/OnrampSettingsViewModel.swift
> +            .assign(to: &$selectedCountry)
не, не надо так

2024-11-11 13:41 UTC, tureck1y commented on Tangem/Modules/Send/UI/Base/SendCoordinatorView.swift
> +            .navigation(item: $coordinator.onrampSettingsViewModel) {
emtyNavigationLink не хватает, нигде не должно быть одной линки, минимум две

2024-11-11 13:42 UTC, tureck1y commented on Tangem/Modules/OnrampCountrySelector/OnrampCountrySelectorViewModel.swift
> +        .assign(to: &$countries)
увидео коммент что работает иначе, но давай оставим проверенный вариант

2024-11-11 13:42 UTC, tureck1y commented on Tangem/Modules/Send/UI/Base/SendView/SendViewModel.swift
> +    func openOnrampSettingsView() {
Что-то меня уже эт начинает смущать, давайте после окончания работ по онрампу подумаем как сделать красивее @Balashov152 @amuraveinik

2024-11-11 14:53 UTC, amuraveinik commented on Tangem/Modules/OnrampCountrySelector/OnrampCountrySelectorViewModel.swift
> +        .assign(to: &$countries)
Запушил фикс, проверил что деиниты в вьюмоделей вызываются

2024-11-11 18:22 UTC, tureck1y commented on Tangem/Modules/OnrampCurrencySelector/OnrampCurrencySelectorViewModel.swift
> +        .store(in: &bag)
а это же необязательно, разве что для отмены, точно надо?

2024-11-11 19:05 UTC, amuraveinik commented on Tangem/Modules/OnrampCurrencySelector/OnrampCurrencySelectorViewModel.swift
> +        .store(in: &bag)
Это не обязательно, но в других местах видел также

2024-11-11 19:09 UTC, Balashov152 commented on Tangem/Modules/OnrampCurrencySelector/OnrampCurrencySelectorViewModel.swift
> +        .store(in: &bag)
Это походу были попытки пофиксить утечки памяти без [weak self] 
Хз, вроде да, обычно не пишем, но и мешать не будет наверно

2024-11-12 05:12 UTC, Andoran90 commented on Tangem/Modules/OnrampCurrencySelector/OnrampCurrencySelectorViewModel.swift
> +        .store(in: &bag)
Вообще этот код 'eraseToAntCancellable' использовался чтобы не надо было указывать дженериковые типы Task и чтобы можно было отменять таску, не думаю что тут оно сильно надо + внутри таски может добавить проверку на отмену, чтобы лишний раз не пытаться сделать апдейт интерфейса, если все задеинитилось

2024-11-12 09:04 UTC, AlekseiMuraveinik1 commented on Tangem/Modules/OnrampCurrencySelector/OnrampCurrencySelectorViewModel.swift
> +        .store(in: &bag)
Выпилил

2024-11-12 09:10 UTC, Balashov152 approved these changes

2024-11-12 09:12 UTC, tureck1y approved these changes

2024-11-12 09:12 UTC, merged