IOS-8310 [Onramp] Updating quotes logic
tangem/tangem-app-ios-old pull request #4164
Opened 2024-11-05 12:55 UTC by Balashov152

- [ ] #4146

2024-11-11 12:46 UTC, Balashov152 commented on TangemExpress/Models/Onramp/OnrampQuote.swift
> +    public let expectedAmount: Decimal
TODO: будет добавляться в зависимости от дизайна

2024-11-11 18:24 UTC, tureck1y commented on Tangem/Modules/Send/UI/OnrampProviders/OnrampProvidersView/OnrampProvidersViewModel.swift
> +//        case .failed(error:):
тут норм?

2024-11-11 18:25 UTC, tureck1y approved these changes

2024-11-11 18:50 UTC, Balashov152 commented on Tangem/Modules/Send/UI/OnrampProviders/OnrampProvidersView/OnrampProvidersViewModel.swift
> +//        case .failed(error:):
ну пока да, там просто думают еще, показывать error кейс или нет)

2024-11-12 09:08 UTC, Balashov152 commented on Tangem/Modules/Send/UI/OnrampProviders/OnrampProvidersView/OnrampProvidersViewModel.swift
> +//        case .failed(error:):
Собственно вот )
<img width="832" alt="Screenshot 2024-11-12 at 09 07 38" src="https://github.com/user-attachments/assets/b57321fa-67f1-4b06-a922-d033c8e5198a">

2024-11-12 09:14 UTC, tureck1y submitted a review, later dismissed

2024-11-12 09:15 UTC, tureck1y commented on Tangem/Modules/Send/UI/OnrampProviders/OnrampProvidersView/OnrampProvidersViewModel.swift
> +//        case .failed(error:):
да просто закомментированный код

2024-11-12 09:15 UTC, tureck1y commented
конфликты набежали

2024-11-12 09:40 UTC, amuraveinik requested changes

2024-11-12 09:40 UTC, amuraveinik commented on Tangem/Modules/Send/Services/ManagmentModels/OnrampModel.swift
> +            let selected = providers.first!
Давай без форс анврапа

2024-11-12 09:40 UTC, amuraveinik commented on Tangem/Modules/Send/UI/OnrampProviders/OnrampProviderRowView/OnrampProviderRowView.swift
> +                .style(Fonts.Regular.caption1, color: Colors.Text.tertiary)
На первый взгляд кажется что можно объединить с предыдущим кейсом

2024-11-12 09:40 UTC, amuraveinik commented on TangemExpress/Services/ExpressAPIProvider/CommonExpressAPIProvider.swift
> +            .filter { branch.supportedProviderTypes.contains($0.type) }
nit: Можно сделать `supportedProviderTypes` сетом, тогда операция проверки наличия элемента будет быстрее :nerd_face:

2024-11-12 09:53 UTC, Balashov152 commented on Tangem/Modules/Send/Services/ManagmentModels/OnrampModel.swift
> +            let selected = providers.first!
Это вообще должно уйти в норм сортировщик, там еще жду требований. Да и в след MR уже обновленная логика есть
убрал пока, что бы на всякий не падало ✅

2024-11-12 09:53 UTC, Balashov152 commented on TangemExpress/Services/ExpressAPIProvider/CommonExpressAPIProvider.swift
> +            .filter { branch.supportedProviderTypes.contains($0.type) }
✅

2024-11-12 09:54 UTC, ba1ashov commented on Tangem/Modules/Send/UI/OnrampProviders/OnrampProviderRowView/OnrampProviderRowView.swift
> +                .style(Fonts.Regular.caption1, color: Colors.Text.tertiary)
Добавил комменты везде, и завел задачку где все это делать буду

2024-11-12 09:56 UTC, amuraveinik commented on Tangem/Modules/Send/UI/OnrampProviders/OnrampProviderRowView/OnrampProviderRowView.swift
> +                .style(Fonts.Regular.caption1, color: Colors.Text.tertiary)
А, это типа плейсхолдеры...

2024-11-12 09:56 UTC, amuraveinik approved these changes

2024-11-12 10:18 UTC, Balashov152 commented on Tangem/Modules/Send/UI/OnrampProviders/OnrampProviderRowView/OnrampProviderRowView.swift
> +                .style(Fonts.Regular.caption1, color: Colors.Text.tertiary)
ну пока да)

2024-11-12 10:58 UTC, JustGuitarKitty approved these changes

2024-11-12 10:58 UTC, JustGuitarKitty commented on Tangem/Modules/Send/UI/Base/SendCoordinator.swift
> +            }, popToRootAction: popToRootAction
nit: перенос

2024-11-12 11:05 UTC, Balashov152 commented on Tangem/Modules/Send/UI/Base/SendCoordinator.swift
> +            }, popToRootAction: popToRootAction
✍️ . В след сделаю

2024-11-12 11:51 UTC, tureck1y approved these changes

2024-11-12 11:52 UTC, merged