IOS-1671 Present alert when remove coin or token
tangem/tangem-app-ios-old pull request #420
Opened 2022-05-31 11:40 UTC by Balashov152

2022-05-31 11:46 UTC, megakoko commented
Эту задачу уже по фичеветочной методологии делаем?

2022-05-31 12:51 UTC, tureck1y commented
если это не в релиз, то тогда придержим до след мержа в релиз и после уже будем коммитить раздельно в релиз - баги, в девелоп все остальное

2022-05-31 12:53 UTC, Balashov152 commented
Да, это в след релиз. Может CI настроим что бы он мог с ветки собирать для теста, и уже потом после успешного теста сливаем в дев

И деве в теории должен быть меньше багов

2022-05-31 13:06 UTC, tureck1y commented
сначала релиз, потом рефакторинг, а потом обсудим ветки,  пока давайте в рамках гитфлоу действовать

2022-06-01 05:50 UTC, megakoko commented on Tangem/MultiWallet/TokenDetails/TokenDetailsView.swift
> +                .foregroundColor(viewModel.canRemove ? .tangemGrayDark6 : .tangemGrayLight5)
При добавлении `disabled` цвет не меняется автоматически?

2022-06-01 05:50 UTC, megakoko commented on Tangem/MultiWallet/TokenDetails/TokenDetailsViewModel.swift
> +    let didRequestDissmiss = PassthroughSubject<Void, Never>()
Кто угодно снаружи может посылать значения через этот паблишер. Обычно Subject делают private, а наружу торчит AnyPublisher основанный на Subject.

2022-06-01 05:50 UTC, megakoko commented on Tangem/MultiWallet/TokenDetails/TokenDetailsViewModel.swift
> +
Удали пустые строки, пожалуйста. У нас вроде так не принято, по крайней мере я не видел.

2022-06-01 05:50 UTC, megakoko commented on Tangem/MultiWallet/TokenDetails/TokenDetailsViewModel.swift
> +            assertionFailure("Unimplemented case")
Сюда конечно не зайдет, но все равно страшно.

2022-06-01 05:50 UTC, megakoko commented on Tangem/Common/Localizations/de.lproj/Localizable.strings
> +"token_details_delete_warning_hasTokens" = "You want to delete the blockchain to which the tokens are linked. To delete a blockchain, you should delete its tokens first.";
Нужно единообразие, а то и snake case, и pascalCase вместе.

2022-06-01 05:50 UTC, megakoko commented on Tangem/Common/Localizations/de.lproj/Localizable.strings
> +// MARK: Token details
Мы эти файлы можем еще генерировать из таблички, поэтому такими красивостями можно не заниматься, все равно перезапишется.

2022-06-01 05:50 UTC, megakoko commented on Tangem/Common/Localizations/ru.lproj/Localizable.strings
> +"token_details_delete_warning_coinHasAmount" = "Вы удаляете блокчейн, на балансе которого есть средства. После удаления средства, связанные с блокчейном, не будут включены в расчет общего баланса. Фа
> После удаления средства, связанные с блокчейном, не будут включены в расчет общего баланса

Это не к тебе, но все же — читается немного странно. Я бы изменил на 
"После удаления средства, связанные с блокчейном, будут исключены из расчета общего баланса"

2022-06-01 05:50 UTC, megakoko commented on Tangem/Common/Localizations/de.lproj/Localizable.strings
> +"token_details_delete_warning_hasTokens" = "You want to delete the blockchain to which the tokens are linked. To delete a blockchain, you should delete its tokens first.";
"to which the tokens are linked"
->
"to which tokens are linked"


"To delete a blockchain, you should delete its tokens first"
— запятая не нужна.

2022-06-01 05:50 UTC, megakoko commented on Tangem/Common/Localizations/de.lproj/Localizable.strings
> +"token_details_delete_warning_coinHasAmount" = "You are removing a blockchain that has funds on its balance. After removal, the funds associated with the blockchain will not be included in your total
"You are removing a blockchain that has funds on its balance. After removal, the funds associated with the blockchain will not be included in your total balance calculation. Actual funds on your wallet are not changed or removed and can be made visible when you add blockchain again."

Предлагаю так (с токенами аналогично):
"You are removing a blockchain that has funds in its balance. After removing it the funds associated with the blockchain will be excluded from your total balance calculation. The actual funds in your wallet are not changed nor removed and can be made visible when you add the blockchain again."

2022-06-01 05:52 UTC, megakoko commented on Tangem/Common/Localizations/de.lproj/Localizable.strings
> +"token_details_delete_warning_hasTokens" = "You want to delete the blockchain to which the tokens are linked. To delete a blockchain, you should delete its tokens first.";
"You want to delete the blockchain"
->
"You are trying to delete a blockchain"

2022-06-02 07:49 UTC, Balashov152 commented on Tangem/Common/Localizations/de.lproj/Localizable.strings
> +"token_details_delete_warning_hasTokens" = "You want to delete the blockchain to which the tokens are linked. To delete a blockchain, you should delete its tokens first.";
✅

2022-06-02 07:50 UTC, Balashov152 commented on Tangem/Common/Localizations/de.lproj/Localizable.strings
> +// MARK: Token details
Пока оставил, перезапишется и ладно)

2022-06-02 07:50 UTC, ba1ashov commented on Tangem/Common/Localizations/ru.lproj/Localizable.strings
> +"token_details_delete_warning_coinHasAmount" = "Вы удаляете блокчейн, на балансе которого есть средства. После удаления средства, связанные с блокчейном, не будут включены в расчет общего баланса. Фа
С Лешей обсудил, сказал все отравляем как есть

2022-06-02 07:50 UTC, Balashov152 commented on Tangem/Common/Localizations/de.lproj/Localizable.strings
> +"token_details_delete_warning_hasTokens" = "You want to delete the blockchain to which the tokens are linked. To delete a blockchain, you should delete its tokens first.";
С Лешей обсудил, он поговорил с переводчиком, решено брать как в задаче)

2022-06-02 07:51 UTC, Balashov152 commented on Tangem/Common/Localizations/de.lproj/Localizable.strings
> +"token_details_delete_warning_coinHasAmount" = "You are removing a blockchain that has funds on its balance. After removal, the funds associated with the blockchain will not be included in your total
С Лешей обсудил, он поговорил с переводчиком, решено брать как в задаче)

2022-06-02 07:51 UTC, Balashov152 commented on Tangem/MultiWallet/TokenDetails/TokenDetailsViewModel.swift
> +            assertionFailure("Unimplemented case")
Ну assert() на то и нужен он только в дебаг упадет, что бы сам разработчик мог проверить) а в realise уже падать не будет)

2022-06-02 07:52 UTC, Balashov152 commented on Tangem/MultiWallet/TokenDetails/TokenDetailsViewModel.swift
> +
как по мне с ними лучше читабельность) Ну ок, удалил

2022-06-02 10:07 UTC, megakoko commented on Tangem/MultiWallet/TokenDetails/TokenDetailsViewModel.swift
> +            assertionFailure("Unimplemented case")
Да, точно. Меня в молодости ассерты покусали, боюсь теперь

2022-06-02 11:00 UTC, megakoko commented on Tangem/Common/Localizations/ru.lproj/Localizable.strings
> +"token_details_delete_warning_coinHasAmount" = "Вы удаляете блокчейн, на балансе которого есть средства. После удаления средства, связанные с блокчейном, не будут включены в расчет общего баланса. Фа
Поговорили с Алексеем — сказал, что уточнит еще у другого переводчика.

2022-06-02 11:03 UTC, megakoko commented on Tangem/Common/Localizations/de.lproj/Localizable.strings
> +"token_details_delete_warning_hasTokens" = "You want to delete the blockchain to which the tokens are linked. To delete a blockchain, you should delete its tokens first.";
На счет SwiftGen согласен. Посмотрел в своем проекте, у меня идентификаторы типа `Transactions.CantSaveTransactionReadOnlyWallet`. У нас по-моему подчеркивания из-за совместимости с андроидом.

2022-06-02 11:16 UTC, Balashov152 commented on Tangem/MultiWallet/TokenDetails/TokenDetailsView.swift
> +                .foregroundColor(viewModel.canRemove ? .tangemGrayDark6 : .tangemGrayLight5)
Пробовал, если мы явно указываем `foregroundColor` то не меняется 
А иначе он синий/серый по дефолту

2022-06-02 11:16 UTC, Balashov152 commented on Tangem/MultiWallet/TokenDetails/TokenDetailsViewModel.swift
> +    let didRequestDissmiss = PassthroughSubject<Void, Never>()
✅

2022-06-03 06:36 UTC, megakoko commented on Tangem/Common/Localizations/ru.lproj/Localizable.strings
> +"token_details_delete_warning_coinHasAmount" = "Вы удаляете блокчейн, на балансе которого есть средства. После удаления средства, связанные с блокчейном, не будут включены в расчет общего баланса. Фа
Мне у другого переводчика тоже перевод не особо понравился, поэтому возможно проблема во мне, все предъявы снимаю.

Уточни у Алексея какие текстовки в итоге использовать.

2022-06-03 06:42 UTC, megakoko commented on Tangem/MultiWallet/TokenDetails/TokenDetailsViewModel.swift
> +    var didRequestDissmiss: AnyPublisher<Void, Never> {
Давай переименуем в requestDismissalPublisher, а Subject в requestDismissalSubject.

А то сейчас как название метода читается.

2022-06-03 06:45 UTC, megakoko commented on Tangem/MultiWallet/TokenDetails/TokenDetailsViewModel.swift
> +
Во всех кейсах

2022-06-06 11:34 UTC, ba1ashov commented on Tangem/MultiWallet/TokenDetails/TokenDetailsViewModel.swift
> +    var didRequestDissmiss: AnyPublisher<Void, Never> {
✅

2022-06-06 11:34 UTC, Balashov152 commented
обновил текста в соотвествии с задачей

2022-06-06 11:41 UTC, megakoko submitted a review, later dismissed

2022-06-06 11:42 UTC, megakoko commented
А `localized(...)` не работает с несколькими параметрами?

2022-06-06 11:47 UTC, tureck1y commented
c variadic не работает, крашится, только если наделать несколько методов с разными количеством параметров

2022-06-06 11:47 UTC, Balashov152 commented
> А `localized(...)` не работает с несколькими параметрами?

Блин, я вообще про него не знал, добавил троеточие после, с несколькими получилось? правда iOS 15.0

2022-06-06 11:49 UTC, megakoko commented
Может накопипастим до 10 параметров, например? Удобно ведь.

2022-06-06 11:50 UTC, Balashov152 commented
> Может накопипастим до 10 параметров, например? Удобно ведь.

да давайте SwiftGen завезем, там тоже через `CVarArg...` сделано
Просто пока не буду старое трогать, новые текста будем добавлять уже норм

2022-06-06 11:56 UTC, tureck1y requested changes

2022-06-06 11:56 UTC, tureck1y commented on Tangem/App/ViewModels/WalletModel.swift
> +            return .ableThroughtAlert
дефолтный токен нельзя удалять, как и дефолтный блокчейн

2022-06-06 11:56 UTC, tureck1y commented on Tangem/App/ViewModels/WalletModel.swift
> +    func removeState(amountType: Amount.AmountType) -> RemoveState {
Немножко смущает название. Я это прочитал как удалить стейт. Предлагаю getRemoveState или-что то типа такого.

2022-06-06 11:56 UTC, megakoko commented on Tangem/App/ViewModels/WalletModel.swift
> +    func removeState(amountType: Amount.AmountType) -> RemoveState {
`RemovalState`?

2022-06-06 11:58 UTC, Balashov152 commented on Tangem/App/ViewModels/WalletModel.swift
> +    func removeState(amountType: Amount.AmountType) -> RemoveState {
Обновил на `getRemovalState`

2022-06-06 12:00 UTC, Balashov152 commented on Tangem/App/ViewModels/WalletModel.swift
> +            return .ableThroughtAlert
Пошел к Леше

2022-06-06 12:01 UTC, megakoko commented on Tangem/App/ViewModels/WalletModel.swift
> +        var isCanRemove: Bool {
Лучше isRemovable

2022-06-06 12:02 UTC, Balashov152 commented on Tangem/App/ViewModels/WalletModel.swift
> +        var isCanRemove: Bool {
✅

2022-06-07 12:41 UTC, tureck1y commented on Tangem/App/ViewModels/WalletModel.swift
> +            return .ableThroughtAlert
решили отдельной задачей разобраться с дефолтными токенами.

2022-06-07 12:48 UTC, tureck1y commented on Tangem/Common/Extensions/String+.swift
> +    internal func localized(_ arguments: CVarArg...) -> String {
Ну это будет крашить приложение на 14 оси, как мы обсудили, так что пока предлагаю вернуть, и либо добавить вариант с двумя параметрами, либо не добавлять. Больше у нас обычно не бывает. ViewBuilder вон так и работает, 10 методов наклепали)

2022-06-07 13:03 UTC, Balashov152 commented on Tangem/Common/Extensions/String+.swift
> +    internal func localized(_ arguments: CVarArg...) -> String {
добавил другой вариант с массивом [CVarArg], String(format: String, arguments: [CVarArg]) так тоже может)

2022-06-07 13:22 UTC, tureck1y commented on Tangem/Common/Extensions/String+.swift
> +    internal func localized(_ arguments: CVarArg...) -> String {
ну вот это придется проверять теперь, у меня у одного иос 14 остался, да?

2022-06-07 13:25 UTC, Balashov152 commented on Tangem/Common/Extensions/String+.swift
> +    internal func localized(_ arguments: CVarArg...) -> String {
Ну можно сделать [Any] как в SwiftGen работает
Просто если копипастить, то все равно тоже самое получается, тоже массив будет, или через запятую

2022-06-07 13:25 UTC, ba1ashov commented on Tangem/Common/Extensions/String+.swift
> +    internal func localized(_ arguments: CVarArg...) -> String {
Можно (arguments: [String]) что бы CVarArg не использовать )

2022-06-08 05:50 UTC, megakoko commented on Tangem/Common/Extensions/String+.swift
> +    internal func localized(_ arguments: CVarArg...) -> String {
Я честно в шоке от такого поведения свифта, но если не будет работать давайте просто накопипастим перегрузки от 1 до 9 аргументов.

2022-06-08 06:52 UTC, tureck1y commented on Tangem/MultiWallet/TokenDetails/TokenDetailsViewModel.swift
> +        let title = "token_details_unable_hide_alert_title".localized(amountToSend?.currencySymbol ?? "")
Пока тестил вот что заметил. Если выключить на телефоне интернет, просканировать карту и перейти в детальный вид токена, то amountToSend будет пустой. Соответственно текстовка сломается. Код можно через amountType вот так:

 private var currencySymbol: String {
        if let token = amountType.token {
            return token.symbol
        } else {
            return blockchainNetwork.blockchain.currencySymbol
        }
    }

2022-06-08 07:01 UTC, tureck1y commented on Tangem/Common/Extensions/String+.swift
> +    internal func localized(_ arguments: CVarArg...) -> String {
массив ок

2022-06-08 07:27 UTC, Balashov152 commented on Tangem/MultiWallet/TokenDetails/TokenDetailsViewModel.swift
> +        let title = "token_details_unable_hide_alert_title".localized(amountToSend?.currencySymbol ?? "")
✅

2022-06-08 07:28 UTC, tureck1y approved these changes

2022-06-08 07:36 UTC, gre4ixin approved these changes

2022-06-08 08:00 UTC, megakoko approved these changes

2022-06-08 08:30 UTC, merged