IOS-8238 Add action buttons swap flow
tangem/tangem-app-ios-old pull request #4260
Opened 2024-11-22 12:16 UTC by ViacheslavEfimenko

2024-11-22 18:13 UTC, tureck1y approved these changes, later dismissed

2024-11-22 18:13 UTC, tureck1y commented on Tangem/Modules/ExpressView/ExpressCoordinatorView.swift
> +        ZStack {
Тут надо бы потестить, чтобы не отвалилось как в сенде @Balashov152

2024-11-22 18:13 UTC, tureck1y commented on Tangem/Modules/Main/ActionButtonsSwap/Service/SwapToTokenAvailabilitySorter.swift
> +struct SwapSourceTokenAvailabilitySorter: TokenAvailabilitySorter {
а в чем отличие от CommonSwapTokenAvailabilitySorter? Можно в коде пару слов кинуть)

2024-11-24 15:54 UTC, JustGuitarKitty commented on Tangem/Modules/Main/ActionButtonsSwap/Service/SwapToTokenAvailabilitySorter.swift
> +struct SwapSourceTokenAvailabilitySorter: TokenAvailabilitySorter {
а забыл нейминги отрефачить, там один для вью модели сорца, другой для детали, сортировки по-разному работают

2024-11-24 18:22 UTC, Balashov152 commented on Tangem/App/Services/Express/ExpressInteractor/ExpressInteractor.swift
> +            }
Это все не нужно, добавь просто в `ExpressInteractor:76` строке в `_swappingPair` нужный `destinationWallet.map { .loaded($0) }  ?? .loading`
и под `if` закинуть метод `initialLoading`
P.S. Можно его переименовать в `initialLoadingDestination`

2024-11-24 18:22 UTC, Balashov152 commented on Tangem/App/Services/ExpressDestinationService/CommonExpressDestinationService.swift
> +        }
Это тоже лишнее все )

2024-11-25 09:13 UTC, ba1ashov commented on Tangem/Modules/ExpressView/ExpressView.swift
> +                .frame(height: 110)
динамические шрифты не оторвет?)

2024-11-25 09:17 UTC, JustGuitarKitty commented on Tangem/Modules/ExpressView/ExpressView.swift
> +                .frame(height: 110)
это удалю

2024-11-25 09:18 UTC, JustGuitarKitty commented on Tangem/Modules/ExpressView/ExpressView.swift
> +                .frame(height: 110)
но там проблемка есть, после правок отпишу чо там

2024-11-25 10:03 UTC, ba1ashov commented on Tangem/Modules/Main/ActionButtonsSwap/Coordinator/ActionButtonsSwapCoordinator.swift
> +
А можешь плиз MARK'и добавить и сортировать как везде делаем, что ежинаборазно было )
 как в `MainCoordinator` - Dependencies / Root view model / Child view models

2024-11-25 10:03 UTC, Balashov152 commented on Tangem/Modules/Main/ActionButtonsSwap/Coordinator/ActionButtonsSwapCoordinator.swift
> +extension ActionButtonsSwapCoordinator: ActionButtonsSwapRoutable {
это конечно лучше под `Options` :)

2024-11-25 10:05 UTC, Balashov152 commented on Tangem/Modules/Main/ActionButtonsSwap/Coordinator/ActionButtonsSwapCoordinatorView.swift
> +                        .transition(.opacity.animation(.easeInOut))
блин, это как то вообще не coordinator, полноценная View получается, с логикой, нигде так не пишем )

2024-11-25 10:07 UTC, Balashov152 commented on Tangem/Modules/Main/ActionButtonsSwap/View/ActionButtonsChooseTokenView.swift
> +struct ActionButtonsChooseTokenView: View {
Выглядит как будто много логики во View, может `ActionButtonsChooseTokenViewModel` добавим, и туда все уберем ?

2024-11-25 10:09 UTC, Balashov152 commented on Tangem/Modules/Main/ActionButtonsSwap/View/ActionButtonsSwapView.swift
> +                if viewModel.isNotAvailablePairs {
Тоже выглядит как ту матч "решений" для View, лучше по ViewModel какой нибудь флаг считать

2024-11-25 10:10 UTC, Balashov152 commented on Tangem/Modules/Main/ActionButtonsSwap/View/ActionButtonsSwapView.swift
> +    var noAvailablePairsNotification: some View {
У нас вообще есть NotificationView, которая я так предполагаю выглядит так же
и есть `NotificationManager` и много реализаций его, через `NotificationEvent` все показывается, думаю тут надо так же

2024-11-25 10:21 UTC, Balashov152 commented on Tangem/Modules/Main/ActionButtonsSwap/ViewModel/ActionButtonsSwapViewModel.swift
> +        return destinationTokenSelectorViewModel
nit:
```suggestion
        destinationTokenSelectorViewModel ?? sourceSwapTokeSelectorViewModel
```

2024-11-25 10:23 UTC, JustGuitarKitty commented on Tangem/Modules/Main/ActionButtonsSwap/View/ActionButtonsSwapView.swift
> +    var noAvailablePairsNotification: some View {
кажется, что слишком запарно делать под  2 нотификашки отдельный классс

2024-11-25 10:24 UTC, Balashov152 commented on Tangem/Modules/Main/ActionButtonsSwap/ViewModel/ActionButtonsSwapViewModel.swift
> +        )
Все бы это через внешнюю фабрику делать, на будущее, что ViewModel более чистая была, просто в init `expressRepository: ExpressRepository`
а уж откуда придется, это не ответственность не ViewModel

2024-11-25 10:26 UTC, JustGuitarKitty commented on Tangem/Modules/Main/ActionButtonsSwap/ViewModel/ActionButtonsSwapViewModel.swift
> +        )
вот опять же архитектурный компромисс, где-то мы ради проперти создаем отдельные фабрики/интеракторы, где-то нет, вроде сошлись на том, что если все относительно просто, то все в вм, иначе там и запросы надо выносить, и все остальное

2024-11-25 10:28 UTC, Balashov152 commented on Tangem/Modules/Main/ActionButtonsSwap/ViewModel/ActionButtonsSwapViewModel.swift
> +        guard let sourceToken, let destinationToken else { return }
вообще не должно быть так, что у нас `sourceToken` может быть `nil` если мы уже выбираем `destinationToken`. Может какой то стейт, который ограничивает это все
```
enum State {
case sourceList
case destinationList(source: WalletModel)
}
```
Плюс так же раз мы уже открываем `coordinator?.openExpress` то вместо `destinationToken` мы можем уже `token` использовать. Обычно вот таких безобидных местах отрывает )

2024-11-25 10:29 UTC, ba1ashov commented on Tangem/Modules/Main/ActionButtonsSwap/ViewModel/ActionButtonsSwapViewModel.swift
> +    }
Лучше бы это все отдельный NotificationManager вынести, пускай там все делает, что нужно

2024-11-25 10:31 UTC, Balashov152 commented on Tangem/Modules/Main/MainCoordinatorView.swift
> +                    .expressNavigationView()
А для чего этот `extension` если после `ActionButtonsSwapCoordinatorView` открывется модалка через `sheet` ?

2024-11-25 10:32 UTC, Balashov152 commented on Tangem/Resources/Localizations/de.lproj/Localizable.strings
Локализацию может лучше сразу в `develop` сникнуть, что изменений меньше было в MR

2024-11-25 10:34 UTC, Balashov152 commented on Modules/TangemFoundation/PropertyWrappers/OptionalPublishedObject.swift
> +public struct OptionalPublishedObject<Value: ObservableObject> {
А можешь плиз описать для чего это и как это использовать, и надо ли)
в этом MR не нашел для чего это юзается)

2024-11-25 10:37 UTC, JustGuitarKitty commented on Modules/TangemFoundation/PropertyWrappers/OptionalPublishedObject.swift
> +public struct OptionalPublishedObject<Value: ObservableObject> {
чтобы мы могли обзервить изменения пропертей у дочернего observableObject

2024-11-25 10:38 UTC, JustGuitarKitty commented on Tangem/Modules/Main/MainCoordinatorView.swift
> +                    .expressNavigationView()
я вынес NavigationView из ExpressCoordinatorView, чтобы не дублировать кучу кода, сделал модификатор

2024-11-25 10:42 UTC, JustGuitarKitty commented on Tangem/Modules/Main/ActionButtonsSwap/ViewModel/ActionButtonsSwapViewModel.swift
> +        guard let sourceToken, let destinationToken else { return }
Мне кажется, что заводить отдельный стейт под нажатие кнопки странно, с учетом, что sourceToken и destinationToken некуда выкидывать, они биндятся с вьюхами внутри

2024-11-26 15:54 UTC, fedorov-d commented on Tangem/Modules/Main/ActionButtons/ViewModel/ActionButtonsViewModel.swift
> +            .receive(on: DispatchQueue.main)
withWeakCapture ?

2024-11-26 15:54 UTC, fedorov-d commented on Tangem/Modules/Main/ActionButtons/ViewModel/ActionButtonsViewModel.swift
> +        Task { @MainActor in
через runTask вроде делаем

2024-11-26 15:54 UTC, fedorov-d commented on Tangem/Modules/Main/ActionButtonsSwap/ViewModel/ActionButtonsSwapViewModel.swift
> +        ActionButtonsTokenSelectorItem,
несколько раз используется, мб какой-то typealias сделать?

2024-11-26 16:49 UTC, JustGuitarKitty commented on Tangem/Modules/Main/ActionButtons/ViewModel/ActionButtonsViewModel.swift
> +            .receive(on: DispatchQueue.main)
там нет цикла

2024-11-26 16:49 UTC, JustGuitarKitty commented on Tangem/Modules/Main/ActionButtons/ViewModel/ActionButtonsViewModel.swift
> +        Task { @MainActor in
поправил

2024-11-27 09:28 UTC, Balashov152 commented on Modules/TangemFoundation/PropertyWrappers/OptionalPublishedObject.swift
> +public struct OptionalPublishedObject<Value: ObservableObject> {
комментик бы в коде)

2024-11-29 09:36 UTC, JustGuitarKitty commented on Modules/TangemFoundation/PropertyWrappers/OptionalPublishedObject.swift
> +public struct OptionalPublishedObject<Value: ObservableObject> {
удалил его, по-другому решил

2024-11-29 09:53 UTC, Balashov152 requested changes

2024-11-29 09:53 UTC, Balashov152 commented on Tangem/App/Services/ExchangeService/CombinedExchangeService.swift
> +protocol CombinedExchangeService {
а мы же вроде на `onramp` уже завязываемся, это точно нужно?)

2024-11-29 09:53 UTC, Balashov152 commented on Tangem/App/Services/ExpressAvailabilityProvider/CommonExpressAvailabilityProvider.swift
> +}
а давай это лучше в файл с протоколом `ExpressAvailabilityProvider`

2024-11-29 09:53 UTC, Balashov152 commented on Tangem/App/Services/UserTokensManager/CommonUserTokensManager.swift
> +        TangemFoundation.runTask(in: self) { tokenManager in
лишнее ?

2024-11-29 09:53 UTC, Balashov152 commented on Tangem/Common/UI/SendCurrencyView/SendCurrencyView.swift
> +                .appearance(.init(font: Fonts.Regular.title1))
а стандартный же шрифт тоже `Fonts.Regular.title1`

2024-11-29 09:53 UTC, Balashov152 commented on Tangem/Modules/Main/ActionButtons/BaseActionButton/View/ActionButtonView.swift
> +    @Environment(\.isEnabled) var isEnabled
Может это лучше в `ViewModel: ActionButtonViewModel` добавить ?

2024-11-29 09:53 UTC, Balashov152 commented on Tangem/Modules/Main/ActionButtons/BaseActionButton/View/ActionButtonView.swift
> +                .foregroundStyle(isDisabled ? Colors.Text.disabled : Colors.Text.primary1)
Лучше через общий `style` наш

 ```suggestion
                .style(font: Fonts.Bold.subheadline, color: isDisabled ? Colors.Text.disabled : Colors.Text.primary1)
```

2024-11-29 09:53 UTC, Balashov152 commented on Tangem/Modules/Main/ActionButtons/BaseActionButton/View/ActionButtonView.swift
> +        .onTapGesture(perform: viewModel.tap)
через Button конечно лучше, там `highlight` приятный есть )
а что бы заблочить без изменения цвета , можно вместо `disabled` юзать `allowHitTesting(false)`

2024-11-29 09:53 UTC, Balashov152 commented on Tangem/Modules/Main/ActionButtons/BaseActionButton/ViewModel/ActionButtonViewModel.swift
> +import SwiftUI
а вроде не нужен тут `SwiftUI`

2024-11-29 09:53 UTC, Balashov152 commented on Tangem/Modules/Main/ActionButtons/BuyButton/BuyActionButtonViewModel.swift
> +    private(set) var presentationState: ActionButtonPresentationState = .idle
не крит, но мы сейчас в одну строку везде пишем, тоже вопрос нашего подхода к кодстайлу

2024-11-29 09:53 UTC, Balashov152 commented on Tangem/Modules/Main/ActionButtons/Coordinator/ActionButtonsBuyFlowRoutable.swift
> +protocol ActionButtonsBuyFlowRoutable: AnyObject {
я тебя не много обманул )
теперь просто вызвать `openBuy` не хватит, надо на уровне ViewModel решить через `FeatureProvider` и вызвать `openOnramp`

2024-11-29 09:53 UTC, Balashov152 commented on Tangem/Modules/Main/ActionButtons/SellButton/SellActionButtonViewModel.swift
> +            alert = .init(title: "Ошибка", message: message)
```suggestion
            alert = .init(title: Localization.commonError, message: message)
```

2024-11-29 09:53 UTC, Balashov152 commented on Tangem/Modules/Main/ActionButtons/SellButton/SellActionButtonViewModel.swift
> +            .sink { model in
self if strong here
```suggestion
            .receive(on: DispatchQueue.main)
            .withWeakCapture(self)
            .sink { viewModel, model in
```

2024-11-29 09:53 UTC, Balashov152 commented on Tangem/Modules/Main/ActionButtons/SellButton/SellActionButtonViewModel.swift
> +            guard !isOpeningRequired else { return }
nit: 
```
case .idle where !isOpeningRequired:
```

2024-11-29 09:53 UTC, Balashov152 commented on Tangem/Modules/Main/ActionButtons/SellButton/SellActionButtonViewModel.swift
> +        alert = .init(title: "Ошибка", message: message)
```suggestion
        alert = .init(title: Localization.commonError, message: message)
```
Or will be better use `AlertBuilder`
```suggestion
        alert = AlertBuilder.makeOkErrorAlert(message: message)
```

2024-11-29 09:53 UTC, Balashov152 commented on Tangem/Modules/Main/ActionButtons/SwapButton/SwapButtonViewModel.swift
> +            .store(in: &bag)
вообще лучше в отдельный метод bind() такие подписки выносить, и так же вместо didSet из `presentationState` в подписку тоже

2024-11-29 09:53 UTC, Balashov152 commented on Tangem/Modules/Main/ActionButtons/SwapButton/SwapButtonViewModel.swift
> +            guard !isOpeningRequired else { return }
ну тут все тоже самое что и в `SellActionButtonViewModel.swift`

2024-11-29 09:53 UTC, Balashov152 commented on Tangem/Modules/Main/ActionButtons/ViewModel/ActionButtonsViewModel.swift
> +            }
self is strong link (

2024-11-29 09:53 UTC, Balashov152 commented on Tangem/Modules/Main/ActionButtons/ViewModel/ActionButtonsViewModel.swift
> +                    to: .disabled(message: "Что-то пошло не так, попробуйте позже.")
лучше на англ, все таки он `primary language`

2024-11-29 09:53 UTC, Balashov152 commented on Tangem/Modules/Main/ActionButtons/ViewModel/ActionButtonsViewModel.swift
> +                    message: "Количество токенов в портфеле менее двух. Пожалуйста, добавьте еще один токен."
тут так же, можно сделать и там описать, как например `OnrampProviderManagerError`
```
enum ActionButtonsError: LocalizedError { 
}
```

2024-11-29 09:53 UTC, Balashov152 commented on Tangem/Modules/Main/ActionButtons/ViewModel/ActionButtonsViewModel.swift
> +            }
self is strong again

2024-11-29 09:53 UTC, Balashov152 commented on Tangem/Modules/Main/ActionButtons/ViewModel/ActionButtonsViewModel.swift
> +        }()
Это все можно в одну ошибку смапить, и там описать на англ

2024-11-29 09:53 UTC, Balashov152 commented on Tangem/Modules/Main/ActionButtonsBuy/Coordinator/ActionButtonsBuyCoordinator.swift
> +    // MARK: - Dependencies
👍

2024-11-29 09:53 UTC, Balashov152 commented on Tangem/Modules/Main/ActionButtonsBuy/Coordinator/ActionButtonsBuyCoordinator.swift
>              self?.dismiss()
в принципе `self?.dismiss()` должно хватить

2024-11-29 09:53 UTC, Balashov152 commented on Tangem/Modules/Main/ActionButtonsBuy/Coordinator/ActionButtonsBuyCoordinatorView.swift
> +        } else if let actionButtonsBuyViewModel = coordinator.actionButtonsBuyViewModel {
а как у тебя может быть `rootView` = `SendCoordinatorView`. Если нужен `SendCoordinatorView` то надо сразу минуя `ActionButtonsBuyCoordinatorView` открывать `SendCoordinatorView`

2024-11-29 09:53 UTC, Balashov152 commented on Tangem/Modules/Main/ActionButtonsSwap/ActionButtonsChooseToken/View/ActionButtonsChooseTokenView.swift
> +        _viewModel = StateObject(wrappedValue: .init(field: field))
а зачем так сложно 

```suggestion
        viewModel =.init(field: field)
```

2024-11-29 09:53 UTC, Balashov152 commented on Tangem/Modules/Main/ActionButtonsSwap/ActionButtonsChooseToken/View/ActionButtonsChooseTokenView.swift
> +        VStack(alignment: .leading, spacing: 29) {
что то `spacing: 29` конечно не то, должен быть кратным 2. С дизайнерами был договор, вероятно макет не верный, не крит

2024-11-29 09:53 UTC, Balashov152 commented on Tangem/Modules/Main/ActionButtonsSwap/ActionButtonsChooseToken/View/ActionButtonsChooseTokenView.swift
> +        }
по логике одного `selectedToken` из ViewModel `viewModel.selectedToken` должно хватить, раз ViewModel у тебя сверху передается, в том же мете можно на этот `viewModel.selectedToken` и смотреть

2024-11-29 09:53 UTC, Balashov152 commented on Tangem/Modules/Main/ActionButtonsSwap/ActionButtonsSwap/Coordinator/ActionButtonsSwapCoordinatorView.swift
> +            }
все равно не понимаю как так, если это не `push` и не `sheet` он просто меняется на express без анимации ?

2024-11-29 09:53 UTC, Balashov152 commented on Tangem/Modules/Main/ActionButtonsSwap/ActionButtonsSwap/NotificationManager/ActionButtonsNotificationEvent.swift
> +}
👍

2024-11-29 09:53 UTC, Balashov152 commented on Tangem/Modules/Main/ActionButtonsSwap/ActionButtonsSwap/NotificationManager/ActionButtonsSwapNoficationManager.swift
> +            )
Nit: но может прям тут просто показывать да и все 
```suggestion
            makeNotification(with: .refreshRequired(
                title: title,
                message: message
            )
            )
```

2024-11-29 09:53 UTC, Balashov152 commented on Tangem/UIComponents/TokenSelectorView/View/TokenSelectorView.swift
> +                        .frame(height: 18)
dynamic fonts ? Вообще так себе практика хардкодить высоту View. Она же сама может свою высоту посчитать

2024-11-29 09:55 UTC, Balashov152 commented on Tangem/Modules/Main/ActionButtonsSwap/ViewModel/ActionButtonsSwapViewModel.swift
> +        guard let sourceToken, let destinationToken else { return }
Это просто с виду выглядит как потенциально место для бага, по этому и отписал )

2024-11-29 09:56 UTC, JustGuitarKitty commented on Tangem/App/Services/UserTokensManager/CommonUserTokensManager.swift
> +        TangemFoundation.runTask(in: self) { tokenManager in
Не, у нас же паблик runTask есть, который деприкейтед

2024-11-29 09:57 UTC, JustGuitarKitty commented on Tangem/App/Services/ExchangeService/CombinedExchangeService.swift
> +protocol CombinedExchangeService {
Да, у нас мунпей же еще

2024-11-29 11:58 UTC, JustGuitarKitty commented on Tangem/Modules/Main/ActionButtonsSwap/ActionButtonsChooseToken/View/ActionButtonsChooseTokenView.swift
> +        VStack(alignment: .leading, spacing: 29) {
изящное решение, чтобы при анимации перехода на экспресс не было проблем, т.к. текстфидл имеет дробную высоту

2024-11-29 13:39 UTC, JustGuitarKitty commented on Tangem/Modules/Main/ActionButtons/SellButton/SellActionButtonViewModel.swift
> +            guard !isOpeningRequired else { return }
тогда придется обычный case .idle отдельно еще хэндлить, как будто больше кода

2024-11-29 17:19 UTC, ba1ashov commented on Tangem/App/Services/UserTokensManager/CommonUserTokensManager.swift
> +        TangemFoundation.runTask(in: self) { tokenManager in
так а там же не async метод )

2024-11-29 17:25 UTC, Balashov152 submitted a review, later dismissed

2024-11-29 17:36 UTC, JustGuitarKitty commented on Tangem/App/Services/UserTokensManager/CommonUserTokensManager.swift
> +        TangemFoundation.runTask(in: self) { tokenManager in
в ходе рефаков потерял, теперь да)

2024-11-29 17:36 UTC, JustGuitarKitty commented on Tangem/App/Services/UserTokensManager/CommonUserTokensManager.swift
> +        TangemFoundation.runTask(in: self) { tokenManager in
поправил

2024-12-02 06:12 UTC, fedorov-d commented on Tangem/App/Services/ExchangeService/MoonPayService.swift
> +                guard let self = self else { return }
может в отдельную функцию (или несколько) маппинг перенести? в экран не помещается

2024-12-02 06:22 UTC, fedorov-d commented on Tangem/Modules/Main/ActionButtons/SwapButton/SwapButtonViewModel.swift
> +    var clousure: () -> Void = {}
nit: не совсем понятно по имени как это используется

2024-12-02 09:36 UTC, m3g0byt3 commented on Tangem/Common/UI/RefreshableScrollView.swift
> -                await refreshContainer?.refreshAsync()
А этот фикс разве не возвращает утечку, которая фиксилась тут?
https://github.com/tangem/tangem-app-ios/pull/3940

https://tangem.slack.com/archives/D07LHLDPXPG/p1732896826281179

2024-12-02 09:47 UTC, JustGuitarKitty commented on Tangem/Common/UI/RefreshableScrollView.swift
> -                await refreshContainer?.refreshAsync()
хм, почему-то в локальной версии у меня как слабая захвачена :\\\\ ща поправлю

2024-12-02 09:50 UTC, JustGuitarKitty commented on Tangem/Common/UI/RefreshableScrollView.swift
> -                await refreshContainer?.refreshAsync()
к неактуальному коммиту коммент, уже слабый захват

2024-12-02 19:03 UTC, tureck1y commented on Tangem/Modules/Main/LockedWalletMainContent/LockedWalletMainContentView.swift
> +            if let actionButtonsViewModel = viewModel.actionButtonsViewModel {
а для заблокированной карты оно нам вообще зачем? Обсуждали уже?

2024-12-02 19:08 UTC, tureck1y reviewed
Погоняй плиз в профайлере что нигде ничего не течет

2024-12-02 19:08 UTC, tureck1y commented on Tangem/Modules/Main/LockedWalletMainContent/LockedWalletMainContentView.swift
> +            if let actionButtonsViewModel = viewModel.actionButtonsViewModel {
а для заблокированной карты оно нам вообще зачем? Обсуждали уже?

2024-12-02 19:08 UTC, tureck1y commented on Tangem/Modules/Main/ActionButtonsSwap/ActionButtonsSwap/ViewModel/ActionButtonsSwapViewModel.swift
> +            Task {
[weak self] ?

2024-12-02 19:08 UTC, tureck1y commented on Tangem/Modules/Main/ActionButtonsSwap/ActionButtonsSwap/ViewModel/ActionButtonsSwapViewModel.swift
> +            Task { @MainActor in
тут наверное тоже надо? Вообще протестить бы что везде deinit вызывается

2024-12-03 05:53 UTC, JustGuitarKitty commented on Tangem/Modules/Main/ActionButtonsSwap/ActionButtonsSwap/ViewModel/ActionButtonsSwapViewModel.swift
> +            Task {
нет цикла ж

2024-12-03 05:53 UTC, JustGuitarKitty commented on Tangem/Modules/Main/ActionButtonsSwap/ActionButtonsSwap/ViewModel/ActionButtonsSwapViewModel.swift
> +            Task { @MainActor in
и тут

2024-12-03 05:54 UTC, JustGuitarKitty commented on Tangem/Modules/Main/LockedWalletMainContent/LockedWalletMainContentView.swift
> +            if let actionButtonsViewModel = viewModel.actionButtonsViewModel {
На одновалютке отображаются одновалютные кнопки(ток неправильно, отдельный баг завели), на мультивалютке должны новые блокнутые отображаться, ну собсна это тоже баг был

2024-12-03 06:08 UTC, JustGuitarKitty commented on Tangem/Modules/Main/ActionButtonsSwap/ActionButtonsSwap/ViewModel/ActionButtonsSwapViewModel.swift
> +            Task { @MainActor in
<img width="1251" alt="Снимок экрана 2024-12-03 в 17 08 24" src="https://github.com/user-attachments/assets/81bc6ecf-c07b-4eef-897a-66d304f486c1">
Добавил новый wallet, прогнал все флоу, удалил wallet 

было 1 место с комбучей, где случайно self напрямую, вместо captured value указал

2024-12-03 11:56 UTC, tureck1y approved these changes

2024-12-03 12:22 UTC, merged