IOS-8496 remove pending solana transaction
tangem/tangem-app-ios-old pull request #4291
Opened 2024-11-26 15:09 UTC by skibinalexander

Убираем pending транзакции для сокращения числа запросов. Транзакции считаем, что пролетают мгновенно

Рекомендация @dbaturin

2024-11-26 19:53 UTC, tureck1y commented on BlockchainSdk/Blockchains/Solana/SolanaWalletManager.swift
> -        wallet.removePendingTransaction { hash in
так альтернатива то должна быть какая-то

2024-11-26 19:54 UTC, tureck1y requested changes

2024-11-26 19:54 UTC, tureck1y commented on BlockchainSdk/Blockchains/Solana/SolanaWalletManager.swift
> -                wallet.addPendingTransaction(record)
ну нет, этот  код должен остаться и на апдейте пендинг нужно чистить

2024-11-26 21:08 UTC, skibinalexander commented on BlockchainSdk/Blockchains/Solana/SolanaWalletManager.swift
> -                wallet.addPendingTransaction(record)
> ну нет, этот  код должен остаться и на апдейте пендинг нужно чистить

Так , ну я убрал не спроста , сходил в Андроид , узнал что обсуждали с Денисом , и объяснили сделать именно так , завтра тогда уточню еще разок

2024-11-26 21:09 UTC, skibinalexander commented on BlockchainSdk/Blockchains/Solana/SolanaWalletManager.swift
> -                wallet.addPendingTransaction(record)
> ну нет, этот  код должен остаться и на апдейте пендинг нужно чистить

Может я конечно не так понял , но суть такая да , что транзакции становятся мгновенно , и подвешивать их смысла нет

2024-11-28 09:10 UTC, tureck1y approved these changes

2024-11-28 12:37 UTC, Andoran90 approved these changes

2024-11-29 08:23 UTC, fedorov-d approved these changes

2024-11-29 08:24 UTC, merged