IOS-8604 [Onramp] iOS 15 fixes
tangem/tangem-app-ios-old pull request #4303
Opened 2024-11-28 10:49 UTC by Balashov152

- Переделана логика на отдельный coordinator `OnrampCountryDetectionCoordinator`, так как не получится открыть `.sheet` поверх `.bottomSheet`. на iOS 15 получаем ошибку, на iOS 16+ закрытие `.bottomSheet` и открытие `.sheet`
- Скрыты `NavigationBar` там где они не нужны

2024-11-28 10:50 UTC, Balashov152 commented on Tangem/Modules/OnrampCountrySelector/OnrampCountrySelectorViewModel.swift
> +        repository.updatePreference(country: country, currency: country.currency)
Здесь теперь по требованиям обновляем и стану и валюту всегда

2024-11-29 09:21 UTC, AlekseiMuraveinik1 requested changes

2024-11-29 09:21 UTC, AlekseiMuraveinik1 commented on Tangem/Modules/OnrampCountryDetection/OnrampCountryDetectionCoordinator.swift
> +    private var options: Options!
Может все-таки обычный опшенл, и проверять в местах вызова, как минимум можно будет понятную текстовку сделать в assertionFailure, а не просто форс анврап креш в случае чего

2024-11-29 09:58 UTC, Balashov152 commented on Tangem/Modules/OnrampCountryDetection/OnrampCountryDetectionCoordinator.swift
> +    private var options: Options!
согласен, чуток поленился ✅

2024-11-29 18:54 UTC, AlekseiMuraveinik1 approved these changes, later dismissed

2024-12-02 12:09 UTC, m3g0byt3 submitted a review, later dismissed

2024-12-02 12:09 UTC, m3g0byt3 commented on Tangem/Modules/OnrampCountryDetection/OnrampCountryDetectionCoordinatorView.swift
> +                .overlay(content: { sheets })
Это нужно чтобы с правильного vc презентовать шит, а не с top?

2024-12-02 12:09 UTC, m3g0byt3 commented on Tangem/Modules/OnrampCountrySelector/OnrampCountrySelectorViewModel.swift
> +        Publishers.CombineLatest(countriesSubject, $searchText)
А это будет работать если от юзера не было ввода текста? В searchText изначально прилетает пустая строка?
CombineLatest просто требует чтобы все паблишеры заэмиттили значение как минимум один раз
>The combined publisher doesn’t produce elements until each of its upstream publishers publishes at least one element.

2024-12-02 13:19 UTC, tureck1y commented on TangemApp.xcworkspace/xcshareddata/swiftpm/Package.resolved
> +  "originHash" : "fb88693ec6eb8c944317f17399fedd658adb0ee151c3756ba45bdd6824f813fa",
тут все ок?

2024-12-02 13:19 UTC, tureck1y commented on Tangem/Modules/OnrampCountryDetection/OnrampCountryDetectionCoordinatorView.swift
> +                .overlay(content: { sheets })
выглядит как костыль(( не очень понял в чем прикол с размером

2024-12-02 13:20 UTC, Balashov152 commented on Tangem/Modules/OnrampCountryDetection/OnrampCountryDetectionCoordinatorView.swift
> +                .overlay(content: { sheets })
получается на iOS 14 что раз уже bottom sheet показан с top не работает, то `.sheet` из координатора не работает. Вообще как будто этот хак с показом на `topViewController` был только для iOS 14. Вероятно его можно выпилить, и все будет работать через ZStack просто

2024-12-02 13:21 UTC, ba1ashov commented on Tangem/Modules/OnrampCountrySelector/OnrampCountrySelectorViewModel.swift
> +        Publishers.CombineLatest(countriesSubject, $searchText)
Вообще код не мой ) Я просто перенес в метод `bind()`, сейчас все ок работает

2024-12-02 13:22 UTC, ba1ashov commented on TangemApp.xcworkspace/xcshareddata/swiftpm/Package.resolved
> +  "originHash" : "fb88693ec6eb8c944317f17399fedd658adb0ee151c3756ba45bdd6824f813fa",
я не понимаю какой у нас сейчас актуальный `originHash`. Мне Xcode всегда новый подкидывает (

2024-12-02 13:42 UTC, Balashov152 commented on TangemApp.xcworkspace/xcshareddata/swiftpm/Package.resolved
> +  "originHash" : "fb88693ec6eb8c944317f17399fedd658adb0ee151c3756ba45bdd6824f813fa",
откатил

2024-12-02 13:43 UTC, Balashov152 commented on Tangem/Modules/OnrampCountryDetection/OnrampCountryDetectionCoordinatorView.swift
> +                .overlay(content: { sheets })
обновил коммент, завел задачу, возможно после апдейта bottom sheet это не нужно будет

2024-12-02 13:51 UTC, tureck1y approved these changes

2024-12-02 14:14 UTC, m3g0byt3 approved these changes

2024-12-02 14:15 UTC, AlekseiMuraveinik1 approved these changes

2024-12-02 14:18 UTC, merged