IOS-8527 [Markets] exchanges performance
tangem/tangem-app-ios-old pull request #4369
Opened 2024-12-10 10:29 UTC by fedorov-d

Пофиксил лаг при входе на экран обменников. Теперь при наличии кеша данные берутся из него и отображаются без скелетона.

2024-12-10 10:30 UTC, fedorov-d commented on Tangem/Modules/Markets/MarketsTokenDetails/Subviews/ExchangesList/MarketsTokenDetailsExchangesListView.swift
> +            LazyVStack(spacing: 0) {
при большом кол-ве обменников был значительный лаг из-за попытки отобразить все сразу

2024-12-10 10:47 UTC, tureck1y commented on BlockchainSdk/Extensions/Moya+.swift
> +    /// Get cached response for provided target.
Давай сразу в новый модуль NatngemNetworkUtils добавим

2024-12-10 12:30 UTC, fedorov-d commented on BlockchainSdk/Extensions/Moya+.swift
> +    /// Get cached response for provided target.
перенес

2024-12-10 13:34 UTC, tureck1y submitted a review, later dismissed

2024-12-10 18:43 UTC, m3g0byt3 requested changes

2024-12-10 18:43 UTC, m3g0byt3 commented on Modules/TangemNetworkUtils/MoyaProvider+CachedResponse.swift
> +        return session.session.configuration.urlCache?.cachedResponse(for: urlRequest)
Первый раз вижу такую реализацию

В этом случае нет же никакого метода управления кешем, как его инвалидировать на бэке?
Сколько он будет жить на клиенте?
Клиент учитывает max-age и Expires?

Как минимум при таком доставании руками невозможно же нормально работать с max-age, который должен ресетится если нет изменений

В других ручках же вроде сейчас нормально работает через etag и 304, чем ручка бирж такая специфичная?

2025-01-09 07:06 UTC, fedorov-d commented on Modules/TangemNetworkUtils/MoyaProvider+CachedResponse.swift
> +        return session.session.configuration.urlCache?.cachedResponse(for: urlRequest)
обсуждали с Сашей возможность использования кеша чтобы при повторном входе экран отображался без задержек и доп анимаций. замечание валидное, проверил - проблема с max age действительно есть. еще раз проговорим и возможно избавимся от доп сложности.

2025-01-13 18:36 UTC, tureck1y commented on Modules/TangemNetworkUtils/MoyaProvider+CachedResponse.swift
> +        return session.session.configuration.urlCache?.cachedResponse(for: urlRequest)
идея в том, что не должно быть даже скелетонов при переходе на биржи

2025-01-24 13:38 UTC, fedorov-d commented on Modules/TangemNetworkUtils/MoyaProvider+CachedResponse.swift
> +        return session.session.configuration.urlCache?.cachedResponse(for: urlRequest)
обсудили, убрал костыли с кешем.

2025-01-24 17:50 UTC, tureck1y approved these changes

2025-01-25 22:15 UTC, m3g0byt3 approved these changes

2025-01-25 22:15 UTC, m3g0byt3 commented on Tangem/Modules/Markets/MarketsTokenDetails/Subviews/ExchangesList/MarketsTokenDetailsExchangesListView.swift
> +            .onAppear(perform: viewModel.loadExchangesList)
На каких-то старых осях, если вьюха встроена в навигейшн - `onAppear` мог вызываться два раза
Сам ловил такую проблему

Надо или отписать этот кейс в QA notes или воткнуть флажок в VM

2025-01-26 11:28 UTC, fedorov-d commented on Tangem/Modules/Markets/MarketsTokenDetails/Subviews/ExchangesList/MarketsTokenDetailsExchangesListView.swift
> +            .onAppear(perform: viewModel.loadExchangesList)
а во VM уже есть флажок loadingCancellable

2025-01-27 06:49 UTC, Andoran90 approved these changes

2025-01-27 07:55 UTC, merged