IOS-8789 [Onramp] More providers coming soon
tangem/tangem-app-ios-old pull request #4401
Opened 2024-12-13 15:20 UTC by Balashov152

2024-12-13 15:20 UTC, ba1ashov commented on Tangem/Common/UI/SendDecimalNumberTextField/DecimalNumberTextField.swift
> +            Publishers.Merge(
чуть обновил, так как иногда терялось значение, сделал более проще

2024-12-13 15:21 UTC, ba1ashov commented on Tangem/Modules/Send/UI/OnrampAmount/Interactor/OnrampAmountInteractor.swift
> +                    return .failure(.tooBigAmount(maxAmount))
копипаста была не верная (

2024-12-13 15:21 UTC, Balashov152 commented on Tangem/Modules/Send/UI/OnrampAmount/OnrampAmountView/OnrampAmountView.swift
> +            .multilineTextAlignment(.center)
оказывается lineLimit который выше не оверрайдит который внутри (

2024-12-13 15:23 UTC, tureck1y approved these changes, later dismissed

2024-12-16 09:10 UTC, AlekseiMuraveinik1 approved these changes, later dismissed

2024-12-16 09:12 UTC, JustGuitarKitty requested changes

2024-12-16 09:12 UTC, JustGuitarKitty commented on Tangem/Modules/ExpressProvidersSelectorView/ExpressMoreProvidersSoonView.swift
> +        VStack(alignment: .center, spacing: 4) {
nit: `.center` по-дефолту

2024-12-16 09:12 UTC, JustGuitarKitty commented on Tangem/Modules/ExpressProvidersSelectorView/ExpressMoreProvidersSoonView.swift
> +                .foregroundColor(Colors.Icon.inactive)
`foregroundStyle`

2024-12-16 09:24 UTC, Balashov152 commented on Tangem/Modules/ExpressProvidersSelectorView/ExpressMoreProvidersSoonView.swift
> +        VStack(alignment: .center, spacing: 4) {
вообще копи паст был c `ExpressProviderSelector`. ✅

2024-12-16 09:24 UTC, Balashov152 commented on Tangem/Modules/ExpressProvidersSelectorView/ExpressMoreProvidersSoonView.swift
> +                .foregroundColor(Colors.Icon.inactive)
вообще копи паст был c `ExpressProviderSelector`. ✅

2024-12-16 09:31 UTC, JustGuitarKitty approved these changes

2024-12-16 11:26 UTC, tureck1y approved these changes

2024-12-16 11:26 UTC, merged