IOS-8811 [Action Buttons] Demo notification inside buy/sell
tangem/tangem-app-ios-old pull request #4410
Opened 2024-12-17 09:56 UTC by ViacheslavEfimenko

2024-12-17 09:59 UTC, skibinalexander commented on Tangem/Modules/Main/ActionButtonsSell/ViewModel/ActionButtonsSellViewModel.swift
> +        if let disabledLocalizedReason = userWalletModel.config.getDisabledLocalizedReason(
Какой - то дублирующийся код с canBuy, если ок, то ок

2024-12-17 09:59 UTC, skibinalexander submitted a review, later dismissed

2024-12-17 10:01 UTC, JustGuitarKitty commented on Tangem/Modules/Main/ActionButtonsSell/ViewModel/ActionButtonsSellViewModel.swift
> +        if let disabledLocalizedReason = userWalletModel.config.getDisabledLocalizedReason(
в угоду "непереусложнения" в кнопках много дублирования по результатам начальных ревью, поэтому пока ок

2024-12-17 11:01 UTC, tureck1y submitted a review, later dismissed

2024-12-17 12:19 UTC, Balashov152 requested changes
Вообще для Onramp Demo - Алерт не нужен

2024-12-17 12:19 UTC, Balashov152 commented on Tangem/Modules/Main/ActionButtonsBuy/ViewModel/ActionButtonsBuyViewModel.swift
> +            alert = .init(title: "", message: disabledLocalizedReason)
Вообще вот так везде 
```suggestion
            alert = AlertBuilder.makeDemoAlert(disabledLocalizedReason)
```

2024-12-17 12:19 UTC, Balashov152 commented on Tangem/Modules/Main/ActionButtonsSell/ViewModel/ActionButtonsSellViewModel.swift
> +        if let disabledLocalizedReason = userWalletModel.config.getDisabledLocalizedReason(
да норм, потом Buy = Onramp(без этой проверки) / Sell - останется старым

2024-12-17 12:31 UTC, ba1ashov approved these changes

2024-12-18 09:23 UTC, skibinalexander approved these changes

2024-12-18 09:47 UTC, tureck1y approved these changes

2024-12-18 09:47 UTC, merged