IOS-8861 add missing analytics parameters
tangem/tangem-app-ios-old pull request #4446
Opened 2024-12-23 15:31 UTC by skibinalexander

Аналитика для нотификашки каспы

Не знаю как симпатичнее сделать, остальные варианты костыли сильнее получались

2024-12-23 15:48 UTC, Balashov152 requested changes

2024-12-23 15:48 UTC, Balashov152 commented on Tangem/App/Services/NotificationManagers/SingleTokenNotifications/SingleTokenNotificationManager.swift
>                      self?.dismissNotification(with: id)
Это лучше сделать в методе `dismissNotification(with:)` по конкретному `event` что бы везде не добавлять

2024-12-23 15:48 UTC, Balashov152 commented on Tangem/App/Services/NotificationManagers/SingleTokenNotifications/SingleTokenNotificationManager.swift
> +                    }
а это вынести в отдельный метод, и там так же сделать `switch case` как и в `dismissNotification`

2024-12-23 15:48 UTC, Balashov152 commented on Tangem/App/Services/NotificationManagers/NotificationEvent.swift
> +    var analyticsEventWhenMainAction: Analytics.Event? { get }
как будто лишнее здесь, не знаю, вроде как и есть аналитика, но по идее надо именно кнопки здесь идут отдельно. как будто сейчас это надо делать либо для всех нотификашек, что бы в будущем без проблем можно было трекать нажатие на кнопку, либо не делать вовсе тут

2024-12-23 16:08 UTC, skibinalexander commented
Окей, сейчас переделаю

2024-12-23 18:38 UTC, Balashov152 commented on Tangem/App/Services/NotificationManagers/SingleTokenNotifications/TokenNotificationEvent.swift
> +    var analyticsEventWhenDismissAction: Analytics.Event? {
так и здесь тож не надо

2024-12-23 18:38 UTC, Balashov152 commented on Tangem/App/Services/NotificationManagers/SingleTokenNotifications/SingleTokenNotificationManager.swift
>              case .hasUnfulfilledRequirements(.incompleteKaspaTokenTransaction(let revealTransaction)):
вот здесь просто 
```
case .hasUnfulfilledRequirements(configuration: .incompleteKaspaTokenTransaction):
Analytics.log(event: .tokenButtonRevealCancel, params: event.analyticsParams)
```

2024-12-23 18:43 UTC, skibinalexander commented on Tangem/App/Services/NotificationManagers/SingleTokenNotifications/SingleTokenNotificationManager.swift
>              case .hasUnfulfilledRequirements(.incompleteKaspaTokenTransaction(let revealTransaction)):
> вот здесь просто
> 
> ```
> case .hasUnfulfilledRequirements(configuration: .incompleteKaspaTokenTransaction):
> Analytics.log(event: .tokenButtonRevealCancel, params: event.analyticsParams)
> ```

Оке, сделаю in place

2024-12-23 19:26 UTC, Balashov152 approved these changes

2024-12-23 19:26 UTC, Balashov152 commented
И кода меньше)

2024-12-23 23:32 UTC, tureck1y approved these changes

2024-12-24 06:40 UTC, fedorov-d approved these changes

2024-12-24 07:40 UTC, merged