IOS-1744 Backup warning view
tangem/tangem-app-ios-old pull request #452
Opened 2022-06-15 14:34 UTC by gre4ixin

2022-06-16 05:29 UTC, megakoko commented on Tangem/Main/BackupWarning/BackUpWarningView.swift
> +                        .padding(.leading, 10)
Можно применить ко всему VStack

2022-06-16 05:29 UTC, megakoko commented on Tangem/Main/BackupWarning/BackUpWarningView.swift
> +
Пустая строка

2022-06-16 05:29 UTC, megakoko commented on Tangem/Main/BackupWarning/BackUpWarningView.swift
> +struct BackUpWarningView: View {
Если это кнопка, то лучше назвать кнопкой.

2022-06-16 05:29 UTC, megakoko commented on Tangem/Main/BackupWarning/BackUpWarningView.swift
> +        .padding(.leading, 16)
Почему левый паддинг применяется на уровне всей вьюхи, а правый на уровне картинки-стрелки?

2022-06-16 05:29 UTC, megakoko commented on Tangem/Main/MainViewModel.swift
> +        } receiveValue: { [weak self] steps in
Выравнивание поехало

2022-06-16 05:29 UTC, megakoko commented on Tangem/Main/MainViewModel.swift
> +
Лишняя строка

2022-06-16 05:29 UTC, megakoko commented on Tangem/Main/MainViewModel.swift
> +        } receiveValue: { [weak self] steps in
Можно weak self тоже добавить

2022-06-16 05:35 UTC, megakoko commented on Tangem/Main/MainView.swift
> +            .cornerRadius(16)
Такие штуки обычно включают в саму кнопку.

2022-06-16 08:07 UTC, gre4ixin commented on Tangem/Main/MainView.swift
> +            .cornerRadius(16)
поправил

2022-06-16 08:07 UTC, gre4ixin commented on Tangem/Main/MainViewModel.swift
> +
поправил

2022-06-16 08:07 UTC, gre4ixin commented on Tangem/Main/MainViewModel.swift
> +        } receiveValue: { [weak self] steps in
поправил

2022-06-16 08:07 UTC, gre4ixin commented on Tangem/Main/BackupWarning/BackUpWarningView.swift
> +        .padding(.leading, 16)
поправил

2022-06-16 08:07 UTC, gre4ixin commented on Tangem/Main/BackupWarning/BackUpWarningView.swift
> +struct BackUpWarningView: View {
поправил

2022-06-16 08:07 UTC, gre4ixin commented on Tangem/Main/BackupWarning/BackUpWarningView.swift
> +
поправил

2022-06-16 08:07 UTC, gre4ixin commented on Tangem/Main/BackupWarning/BackUpWarningView.swift
> +                        .padding(.leading, 10)
поправил

2022-06-16 08:54 UTC, Balashov152 commented on Tangem/Main/MainView.swift
> +                            }
`force_unwrap` ? 

может лучше вынести в отдельную переменную все условия
и вернуть Bool

А то страшно, вдруг падать начнет

2022-06-16 09:01 UTC, megakoko commented on Tangem/Main/MainView.swift
> +                            }
Вообще да, но по там соседству куча такого кода, поэтому я бы сказал норм.

2022-06-16 09:03 UTC, Balashov152 commented on Tangem/Main/MainView.swift
> +                            }
Лучше потихоньку избавляться от такого) Хотя бы не добавлять нового

2022-06-16 09:03 UTC, megakoko submitted a review, later dismissed

2022-06-16 09:24 UTC, gre4ixin commented on Tangem/Main/MainView.swift
> +                            }
убрал

2022-06-16 09:29 UTC, megakoko submitted a review, later dismissed

2022-06-16 09:36 UTC, tureck1y requested changes

2022-06-16 09:36 UTC, tureck1y commented on Tangem/Main/MainView.swift
> +                            if viewModel.isMultiWallet && viewModel.hasNoBackUp {
Надо вынести во вьюмодель сингл прочерти. Само условие неправильное. Нужно заменить viewModel.isMultiWallet на  cardInfo.card.settings.isBackupAllowed

2022-06-16 09:36 UTC, tureck1y commented on Tangem/Main/MainView.swift
> +            .sheet(isPresented: $navigation.detailsToBackup, content: {
нельзя реющать навигационные проперти (navigation.detailsToBackup)

2022-06-16 09:36 UTC, tureck1y commented on Tangem/Main/MainViewModel.swift
> +                    self?.navigation.detailsToBackup = false
тут тоже и чуть ниже

2022-06-16 10:55 UTC, gre4ixin commented on Tangem/Main/MainViewModel.swift
> +                    self?.navigation.detailsToBackup = false
поправил

2022-06-16 10:55 UTC, gre4ixin commented on Tangem/Main/MainView.swift
> +            .sheet(isPresented: $navigation.detailsToBackup, content: {
поправил

2022-06-16 10:55 UTC, gre4ixin commented on Tangem/Main/MainView.swift
> +                            if viewModel.isMultiWallet && viewModel.hasNoBackUp {
поправил

2022-06-16 11:11 UTC, megakoko approved these changes, later dismissed

2022-06-16 13:08 UTC, megakoko submitted a review, later dismissed

2022-06-16 13:08 UTC, Balashov152 approved these changes, later dismissed

2022-06-16 13:10 UTC, tureck1y commented on Tangem/Main/MainViewModel.swift
> +    @Published var isTwinRecreationModel: Bool = true
можно удалить

2022-06-17 08:05 UTC, gre4ixin commented on Tangem/Main/MainViewModel.swift
> +    @Published var isTwinRecreationModel: Bool = true
✅

2022-06-17 08:06 UTC, megakoko commented on Tangem/Main/MainViewModel.swift
> -
Тут пустую строку тогда надо вернуть

2022-06-17 08:14 UTC, gre4ixin commented on Tangem/Main/MainViewModel.swift
> -
✅

2022-06-17 08:16 UTC, megakoko approved these changes

2022-06-17 08:17 UTC, tureck1y approved these changes

2022-06-17 09:14 UTC, Balashov152 approved these changes

2022-06-17 09:14 UTC, merged