IOS 1626 add chat support in the app
tangem/tangem-app-ios-old pull request #467
Opened 2022-06-23 07:28 UTC by gre4ixin

2022-06-24 04:22 UTC, megakoko requested changes

2022-06-24 04:22 UTC, megakoko commented on Tangem/App/Services/KeysManager/ZendeskConfig.swift
> +}
В идеале бы убрать zendesk из названия полей; на твое усмотрение.

2022-06-24 04:22 UTC, megakoko commented on Tangem/ChatSupport/SupportChatViewModel.swift
> +        Zendesk.instance!.setIdentity(Identity.createAnonymous())
Тут никогда не будет nil?

2022-06-24 04:22 UTC, megakoko commented on Tangem/ChatSupport/SupportChatViewModel.swift
> +    func openChat() -> some View {
Лучше `chat` / `chatView`. "OpenChat" предполагает какое-то действие.

2022-06-24 04:22 UTC, megakoko commented on Tangem/Common/Localizations/en.lproj/Localizable.strings
> +"details_ask_a_question" = "Задать вопрос";
Надо английскую текстовку во всех языки кроме русского.

2022-06-24 04:22 UTC, megakoko commented on Tangem/Modules/Details/DetailsCoordinator.swift
> +    @Published var chatSupportViewModel: SupportChatViewModel? = nil
Было бы лучше единообразие в наименовании, а то где-то chatSupport, где-то supportChat. SupportChat читается лучше.

2022-06-24 07:14 UTC, Balashov152 commented on Tangem/ChatSupport/SupportChatViewModel.swift
> +        Zendesk.instance!.setIdentity(Identity.createAnonymous())
Даже если не будет лучше написать 
`Zendesk.instance?.setIdentity(Identity.createAnonymous())` 
суть та же, и если что не упадет

2022-06-24 08:38 UTC, gre4ixin commented on Tangem/Modules/Details/DetailsCoordinator.swift
> +    @Published var chatSupportViewModel: SupportChatViewModel? = nil
поправил

2022-06-24 09:31 UTC, gre4ixin commented on Tangem/ChatSupport/SupportChatViewModel.swift
> +        Zendesk.instance!.setIdentity(Identity.createAnonymous())
поправил

2022-06-24 10:49 UTC, gre4ixin commented on Tangem/ChatSupport/SupportChatViewModel.swift
> +    func openChat() -> some View {
поправил

2022-06-24 10:50 UTC, gre4ixin commented on Tangem/Common/Localizations/en.lproj/Localizable.strings
> +"details_ask_a_question" = "Задать вопрос";
добавил англ вариант, в табличку занес

2022-06-24 10:59 UTC, megakoko commented on Tangem/Modules/Details/DetailsCoordinator.swift
> +    @Published var chatSupportViewModel: SupportChatViewModel? = nil
`coordinator.chatSupportViewModel` осталось, название папки тоже

2022-06-24 11:05 UTC, gre4ixin commented on Tangem/Modules/Details/DetailsCoordinator.swift
> +    @Published var chatSupportViewModel: SupportChatViewModel? = nil
да, поправил

2022-06-24 11:12 UTC, megakoko commented on Tangem/Modules/Details/DetailsCoordinator.swift
> +    @Published var chatSupportViewModel: SupportChatViewModel? = nil
Папка осталась ChatSupport.

И еще конфликты у МРа

2022-06-24 11:22 UTC, megakoko submitted a review, later dismissed

2022-06-27 05:53 UTC, tureck1y commented on Tangem/SupportChat/SupportChatViewModel.swift
> +        Zendesk.initialize(appId: keysManager.zendesk.zendeskAppId,
А это ок, что будет инициализироваться много раз? Я бы предложил чат сделать сервисом и там его конфигурировать, кажется вьюмодель таким не должна заниматься

2022-06-27 05:53 UTC, tureck1y commented on Tangem/SupportChat/SupportChatViewModel.swift
> +        Zendesk.initialize(appId: keysManager.zendesk.zendeskAppId,
А группу SupportChat предлагаю переместить в Modules/Details

2022-06-27 14:52 UTC, tureck1y approved these changes, later dismissed

2022-06-27 14:59 UTC, megakoko commented on Tangem/Modules/Details/DetailsCoordinator.swift
> +        supportChatViewModel = SupportChatViewModel() // supportChatService: supportChatService)
Зачем комментарий?

2022-06-27 15:10 UTC, gre4ixin commented on Tangem/Modules/Details/DetailsCoordinator.swift
> +        supportChatViewModel = SupportChatViewModel() // supportChatService: supportChatService)
упс, пропустил

2022-06-27 15:10 UTC, gre4ixin commented on Tangem/Modules/Details/DetailsCoordinator.swift
> +        supportChatViewModel = SupportChatViewModel() // supportChatService: supportChatService)
поправил

2022-06-27 15:14 UTC, Balashov152 commented on Tangem/Modules/Details/DetailsView.swift
> +        case currency, disclaimer, cardTermsOfUse, securityManagement, walletConnect, resetToFactory, chatSupport
`supportChat` ?

2022-06-27 15:14 UTC, Balashov152 commented on Tangem/Modules/Details/DetailsViewModel.swift
> +    func openChat() {
`openSupportChat()` ?

2022-06-27 15:14 UTC, Balashov152 commented on Tangem/Modules/Details/SupportChat/SupportChatView.swift
> +        return viewController
Может `do {} catch {}` ?

2022-06-27 20:06 UTC, gre4ixin commented on Tangem/Modules/Details/DetailsView.swift
> +        case currency, disclaimer, cardTermsOfUse, securityManagement, walletConnect, resetToFactory, chatSupport
✅

2022-06-27 20:06 UTC, gre4ixin commented on Tangem/Modules/Details/DetailsViewModel.swift
> +    func openChat() {
✅

2022-06-27 20:07 UTC, gre4ixin commented on Tangem/Modules/Details/SupportChat/SupportChatView.swift
> +        return viewController
а есть разница в данном случае? мне просто guard привычнее

2022-06-28 02:39 UTC, tureck1y approved these changes

2022-06-28 04:52 UTC, megakoko approved these changes

2022-06-28 07:38 UTC, Balashov152 approved these changes

2022-06-28 07:52 UTC, merged