IOS-1753 Hide back up button
tangem/tangem-app-ios-old pull request #474
Opened 2022-06-28 10:49 UTC by gre4ixin

2022-06-28 11:00 UTC, Balashov152 requested changes

2022-06-28 11:00 UTC, Balashov152 commented on Tangem/Modules/Details/DetailsView.swift
> +                if viewModel.backupVisible && viewModel.canCreateBackup {
как будто это лучше сделать в viewModel

```
    var backupVisible: Bool {
        return cardModel.cardInfo.isTangemWallet && canCreateBackup
    }
```

что бы view просто знала, показывать или нет, и все

2022-06-28 11:01 UTC, tureck1y commented on Tangem/Modules/Details/DetailsView.swift
> +                if viewModel.backupVisible && viewModel.canCreateBackup {
backupVisible надо удалить и смотреть только на canCreateBackup

2022-06-28 14:16 UTC, gre4ixin commented on Tangem/Modules/Details/DetailsView.swift
> +                if viewModel.backupVisible && viewModel.canCreateBackup {
✅

2022-06-28 14:16 UTC, Balashov152 submitted a review, later dismissed

2022-06-28 14:21 UTC, tureck1y commented on Tangem/Modules/Details/DetailsView.swift
> +                if viewModel.backupVisible && viewModel.canCreateBackup {
забыл backupVisible удалить

2022-06-28 14:26 UTC, gre4ixin commented on Tangem/Modules/Details/DetailsView.swift
> +                if viewModel.backupVisible && viewModel.canCreateBackup {
пропустил, что нигде не используется больше, удалил

2022-06-28 14:27 UTC, ba1ashov approved these changes

2022-06-29 05:35 UTC, megakoko approved these changes

2022-06-29 06:01 UTC, tureck1y approved these changes

2022-06-29 08:52 UTC, merged