IOS-1750 Fixed animation of wallets' appearance. Fixed the card image dimensions
tangem/tangem-app-ios-old pull request #477
Opened 2022-06-28 14:14 UTC by megakoko

2022-06-28 14:27 UTC, megakoko commented
https://user-images.githubusercontent.com/12209839/176204276-d880b0f8-0d03-48da-bf2d-19b192b11461.mov

2022-06-28 14:29 UTC, gre4ixin submitted a review, later dismissed

2022-06-28 14:32 UTC, ba1ashov commented on Tangem/Modules/Welcome/WelcomeViewModel.swift
> +                                            cardsPosition: nil,
как будто теперь везде `cardsPosition: nil`

Может удалить вообще?

2022-06-28 14:40 UTC, tureck1y commented on Tangem/Modules/Welcome/WelcomeCoordinator.swift
> +            self?.pushedOnboardingCoordinator = nil
Тут все ок? После онбординга на главный норм переход работает?

2022-06-29 05:56 UTC, megakoko commented on Tangem/Modules/Welcome/WelcomeCoordinator.swift
> +            self?.pushedOnboardingCoordinator = nil
Откатил, было сломано. Это я пытался добавить кнопку "назад", перед заливкой впопыхах откатывал код, часть проглядел.

2022-06-29 05:56 UTC, megakoko commented on Tangem/Modules/Welcome/WelcomeViewModel.swift
> +                                            cardsPosition: nil,
Убрал

2022-06-29 05:57 UTC, megakoko commented
Видео работы до главного экрана:

https://user-images.githubusercontent.com/12209839/176362213-f9227c04-4245-48e9-a67a-78519f62154c.MP4

2022-06-29 06:52 UTC, tureck1y requested changes

2022-06-29 06:52 UTC, tureck1y commented on Tangem/Modules/Onboarding/BaseModels/OnboardingViewModel.swift
> +        isFromMain = true
Я хочу вообще от этой isFromMain избавиться, но пока так, иначе поломается кнопка назад/отмена
isFromMain = input.isStandalone

2022-06-29 06:52 UTC, tureck1y commented on Tangem/Modules/Onboarding/BaseModels/OnboardingViewModel.swift
> +        isFromMain = true
isNavBarVisible  = input.isStandalone

2022-06-29 06:52 UTC, tureck1y commented on Tangem/Modules/Onboarding/Wallet/WalletOnboardingView.swift
> +        .dark
поменялся дизайн?

2022-06-29 07:22 UTC, megakoko commented on Tangem/Modules/Onboarding/Wallet/WalletOnboardingView.swift
> +        .dark
Нет. Просто показывалась светлая плейсхолдер-карта, которую через секунду заменяла бы черная картинка с бекенда.

2022-06-29 07:57 UTC, megakoko commented on Tangem/Modules/Onboarding/BaseModels/OnboardingViewModel.swift
> +        isFromMain = true
Обновил

2022-06-29 07:58 UTC, tureck1y approved these changes, later dismissed

2022-06-29 12:55 UTC, megakoko commented
Обновил:

https://user-images.githubusercontent.com/12209839/176441271-2799a1ea-3b47-43a0-ba43-22bb2df37ff5.MP4

2022-06-30 03:03 UTC, tureck1y approved these changes

2022-06-30 12:30 UTC, gre4ixin approved these changes

2022-06-30 12:33 UTC, merged