Release into develop
tangem/tangem-app-ios-old pull request #515
Opened 2022-07-08 14:22 UTC by gre4ixin

2022-07-11 05:43 UTC, megakoko commented on Tangem/App/Services/Assembly/AssemblyProvider.swift
> +}
Что-то не так, эти два файла были удалены в рефакторинге навигации.

2022-07-11 05:43 UTC, megakoko commented on .gitmodules
> -	path = tangem-app-config
Обрати на это внимание тоже Файл не менялся ни в девелоп, ни в релизе с апреля.

2022-07-11 05:55 UTC, tureck1y commented
я в субботу в релиз еще коммитил, надо обновить этот PR

2022-07-11 08:06 UTC, gre4ixin commented on .gitmodules
> -	path = tangem-app-config
с этим видимо мой косяк, я случайно удалил сабмодуль и подтянул его снова

2022-07-11 08:42 UTC, gre4ixin commented on Tangem/App/Services/Assembly/AssemblyProvider.swift
> +}
поправил

2022-07-11 08:50 UTC, tureck1y commented
WarningBankCardView.swift добавлена два раза, проверь пожалуйста еще разок, что все ок

2022-07-11 08:56 UTC, gre4ixin commented
> WarningBankCardView.swift добавлена два раза, проверь пожалуйста еще разок, что все ок

да, я нашел тоже, еще проверяю

2022-07-11 09:06 UTC, megakoko approved these changes, later dismissed

2022-07-11 09:53 UTC, Balashov152 approved these changes, later dismissed

2022-07-11 10:49 UTC, tureck1y requested changes

2022-07-11 10:49 UTC, tureck1y commented on Tangem/Modules/TokenDetails/TokenDetailsViewModel.swift
> +            coordinator.showP2PTutorial()
Вызов через экстеншн, по аналогии остальными

2022-07-11 10:49 UTC, tureck1y commented on Tangem/Modules/TokenDetails/TokenDetailsViewModel.swift
> +            coordinator.showP2PTutorial()
Давайте придерживаться единообразия, openXXX, dismiss

2022-07-11 10:49 UTC, tureck1y commented on Tangem/Modules/TokenDetails/TokenDetailsView.swift
> +                                  action: viewModel.buyCryptoIfPossible)
Невнимательно мержил, я правил еще и кнопку trade

2022-07-11 10:49 UTC, tureck1y commented on Tangem/Modules/TokenDetails/TokenDetailsRoutable.swift
> +    func showP2PTutorial()
вот тут хорошо видно, 6 методов начинаются с open, ты добавляешь show

2022-07-11 10:49 UTC, tureck1y commented on Tangem/Modules/TokenDetails/TokenDetailsCoordinatorView.swift
> +            }
Зачем это, когда уже есть modalWebViewModel?

2022-07-11 10:49 UTC, tureck1y commented on Tangem/Modules/TokenDetails/TokenDetailsCoordinatorView.swift
> +                BottomSheetView(isPresented: coordinator.$showWarning,
1. Пример оформления BottomSheetView можно посмотреть в  MainCoordinatorView
2. Конфигурация  BottomSheetView отличается от релизной
3. Во вью не должно быть никакой логики и обработки нажатий, только верстка.

2022-07-11 10:49 UTC, tureck1y commented on Tangem/Modules/TokenDetails/WarningBankCardViewModel.swift
> +    let confirmCallback: () -> ()
Модель есть, а не используется

2022-07-11 10:49 UTC, tureck1y commented on Tangem/Modules/TokenDetails/TokenDetailsCoordinator.swift
> +    func showWarningIfNeeded(confirmCallback: @escaping () -> (), declineCallback: @escaping () -> ()) {
либо open либо нет, это тупой координатор навигации, который ничего не решает. IfNeeded тут быть не должно

2022-07-11 10:49 UTC, tureck1y commented on Tangem/Modules/TokenDetails/TokenDetailsCoordinator.swift
> +    @Published var p2pTutorialWebViewModel: WebViewContainerViewModel? = nil
modalWebViewModel можно и нужно реюзать, дженериковое название намекает

2022-07-11 10:49 UTC, tureck1y commented on Tangem/Modules/TokenDetails/TokenDetailsCoordinator.swift
> +    @Published var showWarning: Bool = false
1. Повторюсь, оформление BotеomSheet и всякой обвязки у нему можно посмотреть в MainCoordinator
2. Все прочерти в координаторе аккуратно сгруппированы и помечены марками, почему новые проперти лежат как попало?

2022-07-11 10:49 UTC, tureck1y commented on Tangem/Modules/Main/MainCoordinator.swift
> +    func showP2PTutorial() { }
Кажется тут что-то не доделано, где все мои вчерашние изменения?

2022-07-11 12:17 UTC, gre4ixin commented on Tangem/Modules/TokenDetails/TokenDetailsViewModel.swift
> +            coordinator.showP2PTutorial()
поправил

2022-07-11 12:18 UTC, gre4ixin commented on Tangem/Modules/TokenDetails/TokenDetailsView.swift
> +                                  action: viewModel.buyCryptoIfPossible)
поправил

2022-07-11 12:18 UTC, gre4ixin commented on Tangem/Modules/TokenDetails/TokenDetailsRoutable.swift
> +    func showP2PTutorial()
переименовал

2022-07-11 12:19 UTC, gre4ixin commented on Tangem/Modules/TokenDetails/TokenDetailsCoordinatorView.swift
> +            }
поправил

2022-07-11 12:22 UTC, gre4ixin commented on Tangem/Modules/TokenDetails/WarningBankCardViewModel.swift
> +    let confirmCallback: () -> ()
поправил

2022-07-11 12:22 UTC, gre4ixin commented on Tangem/Modules/TokenDetails/TokenDetailsCoordinator.swift
> +    @Published var p2pTutorialWebViewModel: WebViewContainerViewModel? = nil
поправил

2022-07-11 12:23 UTC, gre4ixin commented on Tangem/Modules/Main/MainCoordinator.swift
> +    func showP2PTutorial() { }
поправил

2022-07-11 12:24 UTC, gre4ixin commented on Tangem/Modules/TokenDetails/TokenDetailsCoordinator.swift
> +    @Published var showWarning: Bool = false
поправил

2022-07-11 12:24 UTC, gre4ixin commented on Tangem/Modules/TokenDetails/TokenDetailsCoordinator.swift
> +    func showWarningIfNeeded(confirmCallback: @escaping () -> (), declineCallback: @escaping () -> ()) {
убрал

2022-07-12 11:02 UTC, tureck1y commented on Tangem/Modules/Main/MainCoordinatorView.swift
> +                        closeOnTapOutside: false,
```suggestion
```

2022-07-12 11:02 UTC, tureck1y commented on Tangem/Modules/Main/MainCoordinatorView.swift
> +                        closeOnTapOutside: false,
Перейти на общий щит)

2022-07-12 11:02 UTC, tureck1y commented on Tangem/Modules/Main/MainCoordinator.swift
> +    @Published var openWarning: Bool = false
эта штука уйдет

2022-07-12 11:02 UTC, tureck1y commented on Tangem/Modules/TokenDetails/TokenDetailsCoordinator.swift
> +    @Published var openWarning: Bool = false
все то же самое

2022-07-12 11:02 UTC, tureck1y commented on Tangem/Modules/TokenDetails/WarningBankCardView.swift
> +    let viewModel: WarningBankCardViewModel?
remove ?

2022-07-12 12:22 UTC, gre4ixin commented on Tangem/Modules/TokenDetails/WarningBankCardView.swift
> +    let viewModel: WarningBankCardViewModel?
убрал

2022-07-12 14:47 UTC, tureck1y approved these changes

2022-07-12 20:27 UTC, ba1ashov approved these changes

2022-07-13 05:51 UTC, megakoko commented on Tangem/Common/UI/BottomSheets/BottomSheetSettings.swift
> +            return 30
Почему в одном месте одно скругление, а в другом другое? Спрашивал еще в оригинальном МРе но ты так и не ответил.

https://github.com/tangem/tangem-app-ios/pull/508#discussion_r916474503


![IMG_3908](https://user-images.githubusercontent.com/12209839/178660147-dbd7a6fe-d8c0-4aa7-a105-b02b3750dd23.PNG)
![IMG_3907](https://user-images.githubusercontent.com/12209839/178660152-9138a5d3-f2d0-438a-adbf-7fa758a9b8f7.PNG)
?

2022-07-13 05:53 UTC, tureck1y commented on Tangem/Common/UI/BottomSheets/BottomSheetSettings.swift
> +            return 30
это наверное к дизайнеру вопрос

2022-07-13 07:23 UTC, gre4ixin commented on Tangem/Common/UI/BottomSheets/BottomSheetSettings.swift
> +            return 30
это дизайн и он так видит)
это мерж релиза в девелоп, поэтому давайте вольем, если ничего не сломано, а скругление, редизайн и прочее в других задачах решим

2022-07-13 07:25 UTC, megakoko commented on Tangem/Common/UI/BottomSheets/BottomSheetSettings.swift
> +            return 30
Ты в прошлый раз говорил с ним на эту тему? Дизайн должен быть последовательным.

2022-07-13 07:28 UTC, tureck1y commented on Tangem/Common/UI/BottomSheets/BottomSheetSettings.swift
> +            return 30
Тут я согласен с Павлом, этот PR лишь синк, напишите просто дизайнеру в фигме коммент и погнали дальше

2022-07-13 07:28 UTC, megakoko approved these changes

2022-07-13 07:38 UTC, gre4ixin commented on Tangem/Common/UI/BottomSheets/BottomSheetSettings.swift
> +            return 30
дизайнер щас приводит к единому виду все, но до этого элемента еще не дошел, так что возможно скоро кому-то прилетит задача сделать единый боттом щит)

2022-07-13 07:44 UTC, merged

2022-07-19 09:21 UTC, megakoko commented
Отсутствует список реселлеров. Учитывая, что некоторые мои правки тоже не были включены в этот мердж надо проверить, что не пропало.

https://github.com/tangem/tangem-app-ios/pull/504/files