Ios 1943 implement user wallets screen
tangem/tangem-app-ios-old pull request #582
Opened 2022-08-04 07:08 UTC by megakoko

2022-08-23 13:21 UTC, megakoko commented
Самое важное:
- CommonUserWalletListService / UserWalletListService
- UserWallet
- UserWalletListViewModel / UserWalletListView
- CardViewModel

2022-08-23 13:24 UTC, megakoko commented
Сейчас в CardViewModel одновременно сосуществуют и CardInfo, и UserWallet

2022-08-24 07:11 UTC, megakoko commented on Tangem/App/ViewModels/CardViewModel.swift
> +    }
Завел ветку с последующими изменениями/дополнениями по сохранению карт, там этот быдлокод уйдет, будет использоваться `state.walletModels`.

2022-08-24 07:41 UTC, ba1ashov commented on Podfile
> -   #pod 'TangemSdk', :path => '../tangem-sdk-ios'
наверно надо SDK обновить, у нас же нет такой папки)

2022-08-24 07:41 UTC, ba1ashov commented on Tangem/App/Models/UserWallet/Implementations/LegacyConfig.swift
> +        "TODO"
Не утверждали? Может таску завести что бы не забыть?

2022-08-24 07:41 UTC, ba1ashov commented on Tangem/App/Models/UserWallet/UserWallet.swift
> +struct UserWallet: Identifiable, Codable {
как будто это потом будет `class` но пока можно оставить, лишь бы не оторвало при изменении

2022-08-24 07:41 UTC, ba1ashov commented on Tangem/App/ViewModels/CardViewModel.swift
> +        let walletData: DefaultWalletData = cardInfo.walletData
надо бы избавлять от такой огромной CardViewModel. 

Сейчас это как будто должно выглядеть так(как будто много надо будет переписывать), но надо, мне для синка токенов сложно будет следить за изменением userWallet

Есть MainViewModel=AppState, как место которое является главным в приложении, и там получается должен быть private var UserWallet, при измении которого должна меняться view, и вообще поведение приложения

что бы в итоге получилось
1. Сканирование лица/карты
2. инициализации массива UserWallet с необходимыми погрузками 
3. Создание MainViewModel с определенным UserWallet

2022-08-24 07:41 UTC, ba1ashov commented on Tangem/Modules/AppSettings/AppSettingsViewModel.swift
> +        let isSavingWallet = (AppSettings.shared.saveUserWallets == true)
`== true` лишнее

Можно 
`self.isSavingWallet = AppSettings.shared.saveUserWallets`

2022-08-24 07:41 UTC, Balashov152 commented on Tangem/Modules/AppSettings/AppSettingsViewModel.swift
> +        self.cardModel = cardModel
А можно прокинуть только`UserWallet` ? без `cardModel`

2022-08-24 07:41 UTC, Balashov152 commented on Tangem/Modules/Main/MainCoordinator.swift
> +        userWalletStorageAgreementCoordinator = .init(dismissAction: dismissAction, popToRootAction: { _ in }, router: self)
`popToRootAction: { _ in }` вроде можно опустить?

2022-08-24 07:41 UTC, Balashov152 commented on Tangem/Modules/Main/MainCoordinator.swift
> +extension MainCoordinator: UserWalletListCoordinatorRoutable { }
методы `UserWalletListCoordinatorRoutable` лучше в `extension` и писать

2022-08-24 07:41 UTC, Balashov152 commented on Tangem/Modules/Main/MainCoordinator.swift
> +extension MainCoordinator: UserWalletStorageAgreementCoordinatorRoutable { }
и тут тоже

2022-08-24 07:41 UTC, Balashov152 commented on Tangem/Modules/Main/MainCoordinatorView.swift
> +            }
Надо бы использовать $0 в клоужере, который можно прокинуть из объекта на который мы смотрим что активировать `Link`

2022-08-24 07:41 UTC, Balashov152 commented on Tangem/Modules/Main/MainViewModel.swift
> +        DispatchQueue.main.asyncAfter(deadline: .now() + delay) { [weak self] in
Как то не очень с `delay`, ну может и ладно)
А зачем отдельной переменной?

2022-08-24 07:41 UTC, Balashov152 commented on Tangem/Modules/UserWalletList/CommonUserWalletListService.swift
> +
`else if` без `guard` может ?
а потом просто `else` для `completion(.failure(TangemSdkError.cardError))
                 return`

2022-08-24 07:41 UTC, Balashov152 commented on Tangem/Modules/UserWalletList/CommonUserWalletListService.swift
> +
лишняя строка)

2022-08-24 07:41 UTC, Balashov152 commented on Tangem/Modules/UserWalletList/UserWalletListCellView.swift
> +    @ObservedObject var model: CardViewModel
вот это не очень хорошо, для рефакторинга будет плохо)
Можешь создать `UserWalletListCellViewModel` и там уже разместить то что нужно из `CardViewModel` 
что бы view была обособлена от всяких внешних моделей

2022-08-24 07:41 UTC, Balashov152 commented on Tangem/Modules/UserWalletList/UserWalletListCellView.swift
> +    let didTapUserWallet: (UserWallet) -> Void
это я бы тоже вынес в `UserWalletListCellViewModel`

2022-08-24 07:41 UTC, Balashov152 commented on Tangem/Modules/UserWalletList/UserWalletListCoordinator.swift
> +    }
тут вероятно надо создать `UserWalletListViewModel` ?
как будто весь coordinator выглядит не доделанным ) Или лишним )
Если у него child'ов, то можно обойтись и без него, просто через ViewRoutable прикидывать события

2022-08-24 07:41 UTC, Balashov152 commented on Tangem/Modules/UserWalletList/UserWalletListCoordinatorView.swift
> +}
Удалить ?

2022-08-24 07:41 UTC, Balashov152 commented on Tangem/Modules/UserWalletList/UserWalletListService.swift
> +}
как будто много методов для одного сервиса, но как по другому тоже не знаю )
Может lock/unlock и save/delete разделить на два)
Один с биометрией, другой со стораджем
Как в задаче про пиццу из собеседования ))

2022-08-24 07:41 UTC, Balashov152 commented on Tangem/Modules/UserWalletList/UserWalletListView.swift
> +    @ObservedObject private var viewModel: UserWalletListViewModel
Вот здесь прям круто, View -> ViewModel -> А там уже разные зависимости

2022-08-24 07:41 UTC, Balashov152 commented on Tangem/Modules/UserWalletList/UserWalletListView.swift
> +                }
Может в отдельную переменную вынести?

2022-08-24 07:41 UTC, Balashov152 commented on Tangem/Modules/UserWalletStorageAggreement/UserWalletStorageAgreementCoordinator.swift
> +    }
Тоже выглядит так, что если нет Childs, то и coordinator не нужен)

2022-08-24 08:18 UTC, megakoko commented on Podfile
> -   #pod 'TangemSdk', :path => '../tangem-sdk-ios'
Забыл откатить, сделал чтобы использовалась последняя версия с недавними изменениями Александра.

2022-08-24 08:19 UTC, megakoko commented on Tangem/App/Models/UserWallet/Implementations/LegacyConfig.swift
> +        "TODO"
У Алексея запросил давно, еще не дал. Добавил #warning везде

2022-08-24 08:20 UTC, megakoko commented on Tangem/App/Models/UserWallet/UserWallet.swift
> +struct UserWallet: Identifiable, Codable {
А зачем класс? По-моему это максимально тупая структура должна быть.

2022-08-24 08:22 UTC, megakoko commented on Tangem/App/ViewModels/CardViewModel.swift
> +        let walletData: DefaultWalletData = cardInfo.walletData
Ну это временный код чтобы как-то синхронизироваться и начать работать всем вместе с UserWallet. Потом надо будет заняться рефакторингом всего этого добра.

2022-08-24 08:23 UTC, megakoko commented on Tangem/Modules/AppSettings/AppSettingsViewModel.swift
> +        let isSavingWallet = (AppSettings.shared.saveUserWallets == true)
Обновил

2022-08-24 08:28 UTC, megakoko commented on Tangem/Modules/Main/MainCoordinatorView.swift
> +            }
Чтобы как здесь было?

```
NavHolder()
    .sheet(item: $coordinator.userWalletStorageAgreementCoordinator) {
        UserWalletStorageAgreementView(viewModel: UserWalletStorageAgreementViewModel(coordinator: $0))
    }
```

Модификатор resizableBottomSheet так не умеет, только на булеву переменную может смотреть.

2022-08-24 08:29 UTC, megakoko commented on Tangem/Modules/Main/MainViewModel.swift
> +        DispatchQueue.main.asyncAfter(deadline: .now() + delay) { [weak self] in
Не нравится хардкодить магические числа.

Без задержки то ли не работало, то ли некрасиво было.

2022-08-24 13:31 UTC, Balashov152 commented on Tangem/App/Models/UserWallet/UserWallet.swift
> +struct UserWallet: Identifiable, Codable {
Да, окей)

2022-08-24 14:27 UTC, megakoko commented on Tangem/Modules/AppSettings/AppSettingsViewModel.swift
> +        self.cardModel = cardModel
Сделал

2022-08-24 14:27 UTC, megakoko commented on Tangem/Modules/Main/MainCoordinator.swift
> +        userWalletStorageAgreementCoordinator = .init(dismissAction: dismissAction, popToRootAction: { _ in }, router: self)
Там кастомный конструктор, добавил значение по-умолчанию

2022-08-24 14:27 UTC, megakoko commented on Tangem/Modules/Main/MainCoordinator.swift
> +extension MainCoordinator: UserWalletListCoordinatorRoutable { }
Перенес

2022-08-24 14:27 UTC, megakoko commented on Tangem/Modules/Main/MainCoordinator.swift
> +extension MainCoordinator: UserWalletStorageAgreementCoordinatorRoutable { }
Перенес

2022-08-24 14:28 UTC, megakoko commented on Tangem/Modules/Main/MainCoordinatorView.swift
> +            }
Сделал, и залил твою реализацию модификатора resizeableBottomSheet с поддержкой Binding<Item>

2022-08-24 14:29 UTC, megakoko commented on Tangem/Modules/UserWalletList/CommonUserWalletListService.swift
> +
Спасибо, обновил, так проще читается

2022-08-24 14:29 UTC, megakoko commented on Tangem/Modules/UserWalletList/CommonUserWalletListService.swift
> +
Убрал

2022-08-24 14:29 UTC, megakoko commented on Tangem/Modules/UserWalletList/UserWalletListCellView.swift
> +    @ObservedObject var model: CardViewModel
Обмозговали и решили пока так оставить

2022-08-24 14:29 UTC, megakoko commented on Tangem/Modules/UserWalletList/UserWalletListCellView.swift
> +    let didTapUserWallet: (UserWallet) -> Void
Оставили так пока

2022-08-24 14:29 UTC, megakoko commented on Tangem/Modules/UserWalletList/UserWalletListCoordinator.swift
> +    }
Удалил координатор

2022-08-24 14:29 UTC, megakoko commented on Tangem/Modules/UserWalletList/UserWalletListCoordinatorView.swift
> +}
Удалил всю вьюху

2022-08-24 14:30 UTC, megakoko commented on Tangem/Modules/UserWalletList/UserWalletListService.swift
> +}
Удалил setName, реализовав через save

2022-08-24 14:31 UTC, megakoko commented on Tangem/Modules/UserWalletList/UserWalletListView.swift
> +                }
Вынес ячейку во вспомогательную функцию

2022-08-24 14:31 UTC, megakoko commented on Tangem/Modules/UserWalletStorageAggreement/UserWalletStorageAgreementCoordinator.swift
> +    }
Удалил тоже координатор с вьюхой

2022-08-25 07:53 UTC, Balashov152 submitted a review, later dismissed

2022-08-25 07:53 UTC, ba1ashov commented on Tangem/Common/UI/BottomSheet/View+BottomSheet.swift
> +    }
Все таки решил оставить, на костыль похоже) 
@gre4ixin глянь, будет норм так?)

2022-08-25 07:53 UTC, ba1ashov commented on Tangem/Modules/Main/MainCoordinator.swift
> +    @Published var userWalletListPresented: Bool = false
это получается не нужно больше? Если тот костыль оставлять с 
`as! Content`

2022-08-25 07:54 UTC, megakoko commented on Tangem/Modules/Main/MainCoordinator.swift
> +    @Published var userWalletListPresented: Bool = false
Удалил

2022-08-25 07:55 UTC, megakoko commented on Tangem/Common/UI/BottomSheet/View+BottomSheet.swift
> +    }
Ну да, работает и удобно

2022-08-25 12:15 UTC, Balashov152 commented on Tangem/Common/UI/BottomSheet/View+BottomSheet.swift
> +    }
вот это пугает `as! Content` только, лишь бы не оторвало)

2022-08-26 03:42 UTC, tureck1y commented on Tangem/App/Services/TangemSdk/TangemSdkProvider.swift
> +        sdk.config.attestationMode = .offline
Отмечу комментом, чтобы не забыть

2022-08-26 03:42 UTC, tureck1y commented on Tangem/App/Models/CardInfo.swift
>      var walletData: DefaultWalletData
В DefaultWalletData надо внести изменение и поменять 
 case note(WalletData)
 на 
 case file(WalletData)

2022-08-26 03:42 UTC, tureck1y commented on Tangem/App/ViewModels/CardViewModel.swift
> +    }
нужны наружу?

2022-08-26 03:42 UTC, tureck1y commented on Tangem/Modules/AppSettings/AppSettingsViewModel.swift
> +                    }
Думаю можно это все унести внутрь userWalletListService. Пусть сам себя анлочит и сохраняет

2022-08-26 03:42 UTC, tureck1y commented on Tangem/Modules/Main/MainCoordinatorView.swift
> +            .resizableBottomSheet(item: $coordinator.userWalletListViewModel, viewModelSettings: BottomSheetSettings(showClosedButton: false, contentBackgroundColor: UserWalletListView.sheetBackgroun
NP: ошэнь длинный строчка

2022-08-26 03:42 UTC, tureck1y commented on Tangem/Modules/Main/MainViewModel.swift
> +        DispatchQueue.main.asyncAfter(deadline: .now() + delay) { [weak self] in
от перестановки мест слагаемых)

2022-08-26 03:42 UTC, tureck1y commented on Tangem/Modules/Welcome/WelcomeCoordinator.swift
> +            welcomeViewModel.unlockWithBiometry()
это точно надо здесь решать?

2022-08-26 03:42 UTC, tureck1y commented on Tangem/Modules/UserWalletList/CommonUserWalletListService.swift
> +    private typealias UserWalletListDerivedKeys = [Data: UserWalletDerivedKeys]
надо скорее подливать develop

2022-08-26 03:42 UTC, tureck1y commented on Tangem/Modules/UserWalletList/CommonUserWalletListService.swift
> +        case userWallet(id: Data, encryptionKey: SymmetricKey)
card думаю тут лучше подойдет

2022-08-26 03:42 UTC, tureck1y commented on Tangem/Modules/UserWalletList/CommonUserWalletListService.swift
> +    }
напиши пожалуйста где-нибудь схему хранения всего по файлам, можно в mobile-team, чтобы все посмотрели и обсудили тоже

2022-08-26 03:42 UTC, tureck1y commented on Tangem/Modules/UserWalletList/CommonUserWalletListService.swift
> +                let encryptionKeyData = Data(hex: encryptionKey.dataRepresentation.hex) // WTF?
и правда странно)

2022-08-26 03:42 UTC, tureck1y commented on Tangem/Modules/UserWalletList/CommonUserWalletListService.swift
> +    private let biometricsStorage = BiometricsStorage()
Давай в этом кейсе попробуем поресерчить переход на хранение мастер ключа в SecureEnclave.
Суть в том, что ключ лежит внутри чипа, а в кейчейн хранится его репрезентация. Чип сам расшифровывает данные внутри себя. У нас в сдк это используется для аттестации, но без биометрии. В доках пишут что и биометрий можно прикрутить.

https://developer.apple.com/documentation/security/certificate_key_and_trust_services/keys/protecting_keys_with_the_secure_enclave

2022-08-26 06:37 UTC, megakoko commented on Tangem/App/ViewModels/CardViewModel.swift
> +    }
Да, используются тут:
```
let card = cardModel.card

let userWallet = UserWallet(
    userWalletId: card.cardPublicKey,
    name: "",
    card: card,
    walletData: cardModel.walletData,
    artwork: nil,
    isHDWalletAllowed: card.settings.isHDWalletAllowed
)
```

2022-08-26 06:40 UTC, megakoko commented on Tangem/Modules/AppSettings/AppSettingsViewModel.swift
> +                    }
Не всегда надо сохранять UserWallet после анлока. При входе в приложение надо просто разблокировать ключи.

2022-08-26 06:52 UTC, megakoko commented on Tangem/Modules/UserWalletList/CommonUserWalletListService.swift
> +                let encryptionKeyData = Data(hex: encryptionKey.dataRepresentation.hex) // WTF?
Не знаю, может у меня телефон кривой, может кривая реализация `dataRepresentation`, но если просто брать `dataRepresentation` и сохранять, то сохраняется какой-то мусор. Куча нулевых байт и потом немного данных. Если переводить в hex и обратно, то все норм. 

Перенес в `extension ContiguousBytes` с нормальным комментарием.

2022-08-26 06:53 UTC, tureck1y commented on Tangem/App/ViewModels/CardViewModel.swift
> +    }
Лучше уже сейчас начинать создавать UserWallet независимо. Либо ради совместимости из cardViewModel в фабричном методе. В UserWallet должен присутствовать только конфиг.

2022-08-26 06:54 UTC, megakoko commented on Tangem/Modules/UserWalletList/CommonUserWalletListService.swift
> +    private let biometricsStorage = BiometricsStorage()
Не против, но давай так сейчас смерджим чтобы не стопорить работу.

2022-08-26 06:55 UTC, megakoko commented on Tangem/Modules/UserWalletList/CommonUserWalletListService.swift
> +        case userWallet(id: Data, encryptionKey: SymmetricKey)
Переименовал

2022-08-26 06:55 UTC, megakoko commented on Tangem/Modules/UserWalletList/CommonUserWalletListService.swift
> +    private typealias UserWalletListDerivedKeys = [Data: UserWalletDerivedKeys]
Ждал ревью с фиксами, подлил

2022-08-26 06:55 UTC, megakoko commented on Tangem/Modules/Welcome/WelcomeCoordinator.swift
> +            welcomeViewModel.unlockWithBiometry()
Вроде нормальное место, карту же тут сканируем

2022-08-26 06:55 UTC, megakoko commented on Tangem/Modules/Main/MainCoordinatorView.swift
> +            .resizableBottomSheet(item: $coordinator.userWalletListViewModel, viewModelSettings: BottomSheetSettings(showClosedButton: false, contentBackgroundColor: UserWalletListView.sheetBackgroun
Покромсал

2022-08-26 06:57 UTC, megakoko commented on Tangem/App/Models/CardInfo.swift
>      var walletData: DefaultWalletData
Переименовал. noteData, NoteConfig оставить так?

```
case .file(let noteData):
    if isDemo {
        return NoteDemoConfig(card: cardInfo.card, noteData: noteData)
    } else {
        return NoteConfig(card: cardInfo.card, noteData: noteData)
    }
```

2022-08-26 06:57 UTC, megakoko commented on Tangem/App/Services/TangemSdk/TangemSdkProvider.swift
> +        sdk.config.attestationMode = .offline
Удолил. Надо будет это добавить в тестнет-схему

2022-08-26 06:57 UTC, megakoko commented on Tangem/Modules/UserWalletList/CommonUserWalletListService.swift
> +    }
Займусь

2022-08-26 06:59 UTC, megakoko commented
@tureck1y готово

2022-08-26 08:31 UTC, megakoko commented on Tangem/App/ViewModels/CardViewModel.swift
> +    }
Сделал фабрику по созданию UserWallet

2022-08-26 09:22 UTC, megakoko commented on Tangem/Modules/UserWalletList/CommonUserWalletListService.swift
> +    }
Написал, и еще добавил шифрование публичных данных по UserWallet. Ключ храню в Keychain.

2022-09-05 03:53 UTC, tureck1y commented on Tangem/App/Models/CardInfo.swift
>      var walletData: DefaultWalletData
Ну конфиги все равно я переделаю, можно пока оставить)

2022-09-05 03:57 UTC, tureck1y submitted a review, later dismissed

2022-09-05 03:57 UTC, tureck1y commented on Tangem/Common/Extensions/Card+.swift
> +        let message = "AccountID".data(using: .utf8)!
Тут кстати неправильный message, надо будет аккуратно мержить

2022-09-05 04:01 UTC, tureck1y commented
У меня только два вопроса 

Задерайвленные ключи теперь лежат внутри кошельков, ты шифруешь теперь только кошельки?

Очень смущает преобразование ключа через hex. Может как-то понадёжнее можно?

2022-09-05 06:53 UTC, megakoko commented
Мы решили, что будем тестить фиче-ветки, поэтому я потом еще подолью сюда дополнительные изменения.

> Задерайвленные ключи теперь лежат внутри кошельков, ты шифруешь теперь только кошельки?
Да, сейчас вот эта структура шифруется:
```
struct SensitiveInformation: Codable {
    let wallets: [Card.Wallet]
}
```

> Очень смущает преобразование ключа через hex. Может как-то понадёжнее можно?
Возможно, что баг в реализации dataRepresentation, в работе с withUnsafeBytes и CFDataCreateWithBytesNoCopy, но я не разбирался.
```
var dataRepresentation: Data {
    return self.withUnsafeBytes { bytes in
        let cfdata = CFDataCreateWithBytesNoCopy(nil, bytes.baseAddress?.assumingMemoryBound(to: UInt8.self), bytes.count, kCFAllocatorNull)
        return ((cfdata as NSData?) as Data?) ?? Data()
    }
}
```

2022-09-07 10:00 UTC, megakoko commented on Tangem/Common/Extensions/Card+.swift
> +        let message = "AccountID".data(using: .utf8)!
Сделал "UserWalletID"

2022-09-07 10:01 UTC, megakoko commented
Смерджил изменения из дополнительной ветки, раз все одним махом будем тестировать/мерджить.

2022-11-10 13:01 UTC, ba1ashov commented on Tangem/App/Models/CardInfo.swift
> +    var card: CardDTO
`CardDTO` разве остается?

2022-11-10 13:01 UTC, ba1ashov commented on Tangem/App/Models/UserWallet/UserWallet.swift
> +    let userWalletId: Data
почему для `id` не использовать `userWalletId` ?

2022-11-10 13:01 UTC, ba1ashov commented on Tangem/App/Models/UserWallet/UserWallet.swift
> +    let artwork: ArtworkInfo?
Это используется? Сейчас уже не надо для загрузки картинки карты это так хранить

2022-11-10 13:01 UTC, ba1ashov commented on Tangem/App/Models/UserWallet/UserWallet.swift
> +        let message = "TokensSymmetricKey".data(using: .utf8)!
`"TokensSymmetricKey"` в константы бы

2022-11-10 13:01 UTC, ba1ashov commented on Tangem/App/Models/UserWallet/UserWallet.swift
> +    func cardInfo() -> CardInfo {
у CardInfo больше нет artwork

2022-11-10 13:01 UTC, ba1ashov commented on Tangem/App/Models/UserWallet/UserWalletConfigFactory.swift
> +        case .file(let noteData):
а почему не `note` ?)

2022-11-10 13:01 UTC, ba1ashov commented on Tangem/App/Services/CardImageProvider/CardImageProvider.swift
> +    private let cardVerifier = OnlineCardVerifier()
а зачем свой `OnlineCardVerifier` если уже есть`tangemSdkProvider.sdk.loadCardInfo` ?

2022-11-10 13:01 UTC, ba1ashov commented on Tangem/App/Services/CardImageProvider/CardImageProvider.swift
> +            .eraseToAnyPublisher()
Выглядит не нужным изменения

2022-11-10 13:01 UTC, ba1ashov commented on Tangem/App/Services/CardsRepository/CardsRepository.swift
> +    func add(_ cardModels: [CardViewModel])
Можно оставить метод с массивом и через `extension` сделать метод с одним элементом

2022-11-10 13:01 UTC, ba1ashov commented on Tangem/App/Services/CardsRepository/CommonCardsRepository.swift
> +    private(set) var models = [CardViewModel]()
чет может в памяти много элементов быть, главное что бы не утекало

2022-11-10 13:01 UTC, ba1ashov commented on Tangem/App/Utilities/BiometricAuthorizationUtils.swift
> +import SwiftUI
не очень хорошо в утилите иметь SwiftUI

2022-11-10 13:01 UTC, ba1ashov commented on Tangem/App/Utilities/BiometricAuthorizationUtils.swift
> +        }
Можно вернуть просто String, и добавить `.localize` для ключей

2022-11-10 13:01 UTC, ba1ashov commented on Tangem/App/ViewModels/CardViewModel.swift
> +    }
Лишнее я думаю

2022-11-10 13:01 UTC, ba1ashov commented on Tangem/Common/Extensions/Card+.swift
> +    }
Наверно не нужно уже, @Andoran90 выносил в утилиту это

2022-11-10 13:01 UTC, ba1ashov commented on Tangem/Common/TangemSdk/Tasks/PreparePrimaryCardTask.swift
> +        let config = GenericConfig(card: CardDTO(card: card))
в девелопе не так( Там UserConfigFactory, хорошо бы подмержить

2022-11-10 13:01 UTC, ba1ashov commented on Tangem/Common/UI/Navigation/NavigationBar.swift
> +    static let color = Color.tangemGrayDark6
Может из новой палитры цвета взять?

2022-11-10 13:01 UTC, ba1ashov commented on Tangem/Modules/AppSettings/AppSettingsCoordinator.swift
>  }
Точно ли нужен координатор если в нем только одна view? Если будет еще разширяться, то ок

2022-11-10 13:01 UTC, ba1ashov commented on Tangem/Modules/Main/MainCoordinator.swift
> +            userWalletModel: options.cardModel.userWalletModel!,
эх, рефачить надо что бы опционалов не было(

2022-11-10 13:01 UTC, ba1ashov commented on Tangem/Modules/Main/MainView.swift
> +                   Image("scan-with-phone")
Давай лучше `Assets.scanWithPhone`

2022-11-10 13:33 UTC, megakoko commented on Tangem/App/Models/CardInfo.swift
> +    var card: CardDTO
Нет, но пока не знаю чем заменить. Жду комментариев от Саши.

2022-11-10 15:30 UTC, gre4ixin commented on Tangem/App/Models/SavedCard.swift
> +    public var isHdWalletAllowed: Bool {  chainCode != nil }
похожу на лишний пробел перед chainCode

2022-11-10 15:30 UTC, gre4ixin commented on Tangem/App/Models/UserWallet/UserWallet.swift
> +    var id = UUID()
let нельзя тут?

2022-11-10 15:30 UTC, gre4ixin commented on Tangem/App/ViewModels/UserWalletFactory.swift
> +
а тут нужен инит пустой? может убрать, если он не нужен

2022-11-10 15:30 UTC, gre4ixin commented on Tangem/Common/Preview/PreviewCard.swift
> +        let vm = CardViewModel(cardInfo: ci, config: config)
мне кажется, что лучше полное наименование, а то в одном месте полное, в другом сокращение, но это необязательно

2022-11-10 15:30 UTC, gre4ixin commented on Tangem/Common/UI/Buttons/ButtonStyles.swift
> +    #warning("TODO: add all buttons styles properly")
это будет вечный warning?

2022-11-10 15:30 UTC, gre4ixin commented on Tangem/Modules/AppSettings/AppSettingsViewModel.swift
> +
у нас везде зависимости идут первыми вроде

2022-11-10 15:30 UTC, gre4ixin commented on Tangem/Modules/Details/DetailsViewModel.swift
> +        guard let userWallet = cardModel.userWallet else { return }
пробел после guard

2022-11-10 15:30 UTC, gre4ixin commented on Tangem/Modules/UserWalletList/CommonUserWalletListService.swift
> +    }
а зачем инит пустой?

2022-11-10 15:30 UTC, gre4ixin commented on Tangem/Modules/UserWalletList/CommonUserWalletListService.swift
> +    @Injected(\.cardsRepository) private var cardsRepository: CardsRepository
везде идет первой

2022-11-10 15:30 UTC, gre4ixin commented on Tangem/Modules/UserWalletList/CommonUserWalletListService.swift
> +        let _ = save(userWallet)
тут без `let _ =` нельзя?

2022-11-10 15:30 UTC, gre4ixin commented on Tangem/Modules/UserWalletList/CommonUserWalletListService.swift
> +        let _ = saveUserWallets([])
тоже без `let _ =` можно?

2022-11-10 15:30 UTC, gre4ixin commented on Tangem/Modules/UserWalletList/CommonUserWalletListService.swift
> +    func save(_ userWallet: UserWallet) -> Bool {
можно `@discardableResult` использовать, чтобы без `let _ = ` использовать

2022-11-10 15:30 UTC, gre4ixin commented on Tangem/Modules/UserWalletList/CommonUserWalletListService.swift
> +            }
может сократить количество вложенностей? через `&&`

2022-11-10 15:30 UTC, gre4ixin commented on Tangem/Modules/UserWalletList/UserWalletEncryptionKeyStorage.swift
> +                guard let self = self else { return }
`guard let self else { return }`

2022-11-10 15:30 UTC, gre4ixin commented on Tangem/Modules/UserWalletList/UserWalletListCellView.swift
> +    var userWallet: UserWallet { userWalletModel.userWallet }
к var'ам

2022-11-10 15:30 UTC, gre4ixin commented on Tangem/Modules/UserWalletList/UserWalletListCellView.swift
> +    let totalBalanceProvider: TotalBalanceProviding
к let'ам

2022-11-10 15:30 UTC, gre4ixin commented on Tangem/Modules/UserWalletList/UserWalletListView.swift
> +
пробел лишний?

2022-11-10 15:30 UTC, gre4ixin commented on Tangem/Modules/UserWalletList/UserWalletListViewModel.swift
> +    @Injected(\.failedScanTracker) var failedCardScanTracker: FailedScanTrackable
`@Injected` везде в начале ставится у нас

2022-11-10 15:30 UTC, gre4ixin commented on Tangem/Modules/UserWalletList/UserWalletListViewModel.swift
> +            guard case .success = result else { return }
отступ после `guard`

2022-11-10 15:30 UTC, gre4ixin commented on Tangem/Modules/UserWalletList/UserWalletListViewModel.swift
> +            let _ = self?.userWalletListService.save(newUserWallet)
`let _ =` можно убрать

2022-11-11 06:01 UTC, megakoko commented on Tangem/App/Models/UserWallet/UserWallet.swift
> +    let userWalletId: Data
Попробовал — не получается

2022-11-11 06:02 UTC, megakoko commented on Tangem/App/Models/UserWallet/UserWallet.swift
> +        let message = "TokensSymmetricKey".data(using: .utf8)!
Убрал

2022-11-11 06:06 UTC, megakoko commented on Tangem/App/Models/UserWallet/UserWalletConfigFactory.swift
> +        case .file(let noteData):
https://github.com/tangem/tangem-app-ios/pull/582#discussion_r955611197

2022-11-11 06:08 UTC, megakoko commented on Tangem/App/Services/CardImageProvider/CardImageProvider.swift
> +    private let cardVerifier = OnlineCardVerifier()
Там один onlineVerificationCancellable на весь СДК, загружается по одной картинке за раз.

2022-11-11 06:13 UTC, megakoko commented on Tangem/App/Services/CardImageProvider/CardImageProvider.swift
> +            .eraseToAnyPublisher()
Иначе только по одной картинке будет загружать

2022-11-11 06:15 UTC, megakoko commented on Tangem/App/Services/CardsRepository/CommonCardsRepository.swift
> +    private(set) var models = [CardViewModel]()
Да, на счет этого репозитория надо еще поговорить

2022-11-11 06:15 UTC, megakoko commented on Tangem/App/Services/CardsRepository/CardsRepository.swift
> +    func add(_ cardModels: [CardViewModel])
Сделал

2022-11-11 06:16 UTC, megakoko commented on Tangem/App/Utilities/BiometricAuthorizationUtils.swift
> +import SwiftUI
Нужно для ключей

2022-11-11 06:18 UTC, megakoko commented on Tangem/App/Utilities/BiometricAuthorizationUtils.swift
> +        }
Код в онбординге ожидает от нас ключей, не строк

2022-11-11 06:20 UTC, megakoko commented on Tangem/App/Models/UserWallet/UserWallet.swift
> +    func cardInfo() -> CardInfo {
В девелопе удалили? В этой ветке есть

2022-11-11 06:20 UTC, megakoko commented on Tangem/App/ViewModels/CardViewModel.swift
> +    }
Нужно для конктруктора userwallet

2022-11-11 06:23 UTC, megakoko commented on Tangem/Common/Extensions/Card+.swift
> +    }
Не могу найти. По поиску "UserWalletId\(wi" везде такое создание userwalletid

2022-11-11 06:23 UTC, megakoko commented on Tangem/Common/TangemSdk/Tasks/PreparePrimaryCardTask.swift
> +        let config = GenericConfig(card: CardDTO(card: card))
Обновил

2022-11-11 06:25 UTC, megakoko commented on Tangem/Modules/AppSettings/AppSettingsCoordinator.swift
>  }
Это же настройки, уже существующий код. Давай ничего не делать в рамках этой задачи тут.

2022-11-11 06:27 UTC, megakoko commented on Tangem/Common/UI/Navigation/NavigationBar.swift
> +    static let color = Color.tangemGrayDark6
Это рефакторинг. Я просто вынес значение в этот енам чтобы везде одинаковое использовать

2022-11-11 06:30 UTC, megakoko commented on Tangem/Modules/Main/MainView.swift
> +                   Image("scan-with-phone")
Сделал

2022-11-11 06:30 UTC, megakoko commented on Tangem/Modules/Main/MainCoordinator.swift
> +            userWalletModel: options.cardModel.userWalletModel!,
Угу

2022-11-11 06:33 UTC, megakoko commented on Tangem/App/Models/SavedCard.swift
> +    public var isHdWalletAllowed: Bool {  chainCode != nil }
Лишний файл, удалил

2022-11-11 06:33 UTC, megakoko commented on Tangem/App/Models/UserWallet/UserWallet.swift
> +    var id = UUID()
codable ругается

Immutable property will not be decoded because it is declared with an initial value which cannot be overwritten

2022-11-11 06:35 UTC, megakoko commented on Tangem/Common/Preview/PreviewCard.swift
> +        let vm = CardViewModel(cardInfo: ci, config: config)
У нас повсеместно vm

2022-11-11 06:35 UTC, megakoko commented on Tangem/App/ViewModels/UserWalletFactory.swift
> +
Убрал

2022-11-11 06:35 UTC, megakoko commented on Tangem/Common/UI/Buttons/ButtonStyles.swift
> +    #warning("TODO: add all buttons styles properly")
Пока @Balashov152 не обновит стили

2022-11-11 06:37 UTC, megakoko commented on Tangem/Modules/AppSettings/AppSettingsViewModel.swift
> +
Перенес

2022-11-11 06:39 UTC, megakoko commented on Tangem/Modules/UserWalletList/CommonUserWalletListService.swift
> +    @Injected(\.cardsRepository) private var cardsRepository: CardsRepository
Сделал

2022-11-11 06:39 UTC, megakoko commented on Tangem/Modules/UserWalletList/CommonUserWalletListService.swift
> +    }
Удалил

2022-11-11 06:39 UTC, megakoko commented on Tangem/Modules/Details/DetailsViewModel.swift
> +        guard let userWallet = cardModel.userWallet else { return }
Добавил

2022-11-11 06:41 UTC, megakoko commented on Tangem/Modules/UserWalletList/CommonUserWalletListService.swift
> +        let _ = save(userWallet)
Убрал

2022-11-11 06:41 UTC, megakoko commented on Tangem/Modules/UserWalletList/CommonUserWalletListService.swift
> +        let _ = saveUserWallets([])
Убрал

2022-11-11 06:42 UTC, megakoko commented on Tangem/Modules/UserWalletList/CommonUserWalletListService.swift
> +    func save(_ userWallet: UserWallet) -> Bool {
Убрал возвращаемое значение

2022-11-11 06:43 UTC, megakoko commented on Tangem/Modules/UserWalletList/CommonUserWalletListService.swift
> +            }
Не получится. Содержимое веток разное. Если userwallets.isempty = true, но файла нет, то мы все равно должны выходить из функции

2022-11-11 06:44 UTC, megakoko commented on Tangem/Modules/UserWalletList/UserWalletListView.swift
> +
Убрал

2022-11-11 06:45 UTC, megakoko commented on Tangem/Modules/UserWalletList/UserWalletListViewModel.swift
> +            let _ = self?.userWalletListService.save(newUserWallet)
Убрал везде

2022-11-11 06:46 UTC, megakoko commented on Tangem/Modules/UserWalletList/UserWalletListViewModel.swift
> +            guard case .success = result else { return }
Добавил

2022-11-11 06:47 UTC, megakoko commented on Tangem/Modules/UserWalletList/UserWalletListViewModel.swift
> +    @Injected(\.failedScanTracker) var failedCardScanTracker: FailedScanTrackable
Перенес

2022-11-11 06:49 UTC, megakoko commented on Tangem/Modules/UserWalletList/UserWalletListCellView.swift
> +    let totalBalanceProvider: TotalBalanceProviding
Перенес

2022-11-11 06:49 UTC, megakoko commented on Tangem/Modules/UserWalletList/UserWalletListCellView.swift
> +    var userWallet: UserWallet { userWalletModel.userWallet }
Перенес

2022-11-11 06:49 UTC, megakoko commented on Tangem/Modules/UserWalletList/UserWalletEncryptionKeyStorage.swift
> +                guard let self = self else { return }
Сделал

2022-11-11 07:02 UTC, megakoko commented on Tangem/App/Models/UserWallet/UserWallet.swift
> +    let artwork: ArtworkInfo?
Используется чтобы сохранить на диск и потом быстрее загрузить картинку

2022-11-11 10:49 UTC, Andoran90 reviewed
1 часть ревью)

2022-11-11 10:49 UTC, Andoran90 commented on Tangem/App/Models/SavedCard.swift
> +struct SavedCard: Codable { // TODO: Migrate to a new saved cards system
этого файла нет в .pbxproj, это так и задумано?

2022-11-11 10:49 UTC, Andoran90 commented on Tangem/App/Models/UserWallet/UserWallet.swift
> +//  Created by Andrey Chukavin on 04.08.2022.
😃

2022-11-11 10:49 UTC, Andoran90 commented on Tangem/App/Models/UserWallet/UserWallet.swift
> +    var isLocked: Bool {
а почему isLocked? для чего он закрыт? по коду уместнее `isEmpty` или что-то вроде `isWithoutWallets`

2022-11-11 10:49 UTC, Andoran90 commented on Tangem/App/Models/UserWallet/UserWallet.swift
> +        guard let firstWalletPublicKey = card.wallets.first?.publicKey else { return nil }
Мне не очень нравится что эта моделька контейнер начинает получать логику по шифрованию. Думаю это стоит вынести в UserWalletEncryptionKey, как это было сделано с UserWalletId, а в инициализатор он может принимать публичный ключ кошелька

2022-11-11 10:49 UTC, Andoran90 commented on Tangem/App/Services/CardsRepository/CardsRepository.swift
> +    func removeModel(withUserWalletId userWalletId: Data)
```suggestion
    func removeModel(with userWalletId: Data)
```
чтобы было единообразие со сканами и чтобы при вызове не было: `removeModel(withUserWalletId: userWalletId)`

2022-11-11 10:49 UTC, Andoran90 commented on Tangem/App/Services/CardsRepository/CommonCardsRepository.swift
> +    func scan(with batch: String? = nil, requestBiometrics: Bool, _ completion: @escaping (Result<CardViewModel, Error>) -> Void) {
а зачем отдельная функция с кложурами и тут и в протоколе? это же не сдк, в котором надо поддерживать разные версии.

2022-11-11 10:49 UTC, Andoran90 commented on Tangem/App/Services/CardsRepository/CardsRepository.swift
> +    func didSwitchToModel(_ cardModel: CardViewModel)
```suggestion
    func didSwitch(to cardModel: CardViewModel)
```

2022-11-11 10:49 UTC, Andoran90 commented on Tangem/App/Services/CardsRepository/CommonCardsRepository.swift
> +        walletConnectServiceProvider.reset()
надо убрать отсюда этот сброс, потому что если ты начинаешь скан, а потом отменяешь его, у тебя WC сбросится. Это надо делать вместе с инициализацией сервисов, когда карточка у тебя уже точно новая выбрана/отсканирована.

2022-11-11 10:49 UTC, Andoran90 commented on Tangem/App/Services/Common/Analytics.swift
> +import Foundation
лишний файл, его уже нет в деве

2022-11-11 10:49 UTC, Andoran90 commented on Tangem/App/Services/Common/TangemSigner.swift
> +                    self.userWalletListService.didScan(card: cardDto)
а почему при подписи чего-либо сохраняется инфа в `UserWalletListService`? разве эта карточке не должна уже быть там после сканирования карточки? Вдобавок каким образом TangemSigner зависит от userWalletListService? мне кажется это должен делать как минимум тут кто запрашивает подпись, но никак не TangemSigner

2022-11-11 10:49 UTC, Andoran90 commented on Tangem/App/Services/CardsRepository/CommonCardsRepository.swift
> +    private func startInitializingServices(for cardInfo: CardInfo) {
не очень удачные названия для этих двух функций, вообще не понятно почему одна начинает инициализировать сервисы, а другая заканчивает.

2022-11-11 10:49 UTC, Andoran90 commented on Tangem/App/Services/CardsRepository/CommonCardsRepository.swift
> +        if let primaryCard = cardInfo.primaryCard {
может стоит первую функцию назвать `resetServices` и сюда добавить WC service, а во вторую перекинуть настройку `backupServiceProvider` и назвать вторую - `setupService`. Или бэкап сервис используется где-то в промежутке между этими двумя функциями?

2022-11-11 10:49 UTC, Andoran90 commented on Tangem/App/Utilities/TwinCardsUtils.swift
>      static func makeCombinedWalletKey(for card: Card, pairData: TwinData?) -> Data? {
давай удалим эту функцию, она вроде нигде не используется.

2022-11-11 10:49 UTC, Andoran90 commented on Tangem/App/ViewModels/CardViewModel.swift
> +        self.init(cardInfo: userWallet.cardInfo(), config: config, userWallet: userWallet)
```suggestion
        self.init(cardInfo: cardInfo, config: config, userWallet: userWallet)
```

2022-11-11 10:49 UTC, Andoran90 commented on Tangem/App/ViewModels/CardViewModel.swift
> +        onAppear()
```suggestion
        updateSdkConfig()
```
пока в `onAppear()` нет никакой дополнительной логики нужной для `didScan()`, думаю тут лучше поставить `updateSdkConfig()`, а то получается, что если ты отсканировал карточку, значит обязательно что-то появилось, но что?..

2022-11-11 10:50 UTC, megakoko commented on Tangem/App/Models/UserWallet/UserWallet.swift
> +//  Created by Andrey Chukavin on 04.08.2022.
Ну он пустой был и в другом месте, я потом просто перезаписал все (:

2022-11-11 10:50 UTC, megakoko commented on Tangem/App/Models/SavedCard.swift
> +struct SavedCard: Codable { // TODO: Migrate to a new saved cards system
Удалил ранее

2022-11-11 10:51 UTC, megakoko commented on Tangem/App/Models/UserWallet/UserWallet.swift
> +    var isLocked: Bool {
Означает, что пользователь его не разблокировал. Разблокировать userwallet можно через биометрию, или отсканировав карту

2022-11-11 10:52 UTC, Andoran90 commented on Tangem/App/ViewModels/CardViewModel.swift
> +    }
все же можно убрать отсюда, и из:
CardInfo, UserWallet и UserWalletFactory.
Приложение запустилось у меня и все картинки грузятся

2022-11-11 11:50 UTC, ba1ashov commented on Tangem/Modules/Main/MainCoordinator.swift
> +            mainViewModel?.onRefresh {}
Лучше `onAppear()` вызывать, там больше логики для открытия

2022-11-11 11:50 UTC, ba1ashov commented on Tangem/Modules/Main/MainView.swift
> +        if AppSettings.shared.saveUserWallets {
Лучше во viewModel сделать `isSaveUserWallets` и внутри viewModel управлять этой переменной, не надо что бы view знала откуда инфа идет

2022-11-11 11:50 UTC, ba1ashov commented on Tangem/Modules/UserWalletList/UserWalletListCellView.swift
> +                    .foregroundColor(Colors.Text.tertiary)
Что то не стилю ) style лучше использовать

2022-11-11 11:51 UTC, Balashov152 commented on Tangem/Common/UI/Buttons/ButtonStyles.swift
> +    #warning("TODO: add all buttons styles properly")
О, а чего за стили? Для новой кнопки?

2022-11-11 11:52 UTC, Andoran90 commented on Tangem/Common/Extensions/Card+.swift
> +    }
мне потом Саня сказал что он создавал уже сущность и утилиту удалили. Может имеет смысл не дату выкидывать, а сохранить UserWalletId и не генерировать его каждый раз по новой? или в какой он момент сейчас создается? очень много где есть он, не понятно в какой момент он создается и где хранится

2022-11-11 11:53 UTC, megakoko commented on Tangem/Common/UI/Buttons/ButtonStyles.swift
> +    #warning("TODO: add all buttons styles properly")
Это еще августовский коммент вроде, там в этом файле куча старых цветов для кнопочных стилей. Надо что-то с этим делать, или менять, или удалить

2022-11-11 11:57 UTC, megakoko commented on Tangem/Modules/Main/MainCoordinator.swift
> +            mainViewModel?.onRefresh {}
Хм, судя по блейму это твой код. Не знаю почему он зеленым показывается

2022-11-11 11:59 UTC, megakoko commented on Tangem/Modules/UserWalletList/UserWalletListCellView.swift
> +                    .foregroundColor(Colors.Text.tertiary)
Сделал

2022-11-11 12:00 UTC, megakoko commented on Tangem/Modules/Main/MainView.swift
> +        if AppSettings.shared.saveUserWallets {
Сделал

2022-11-11 12:01 UTC, megakoko commented on Tangem/App/ViewModels/CardViewModel.swift
> +        onAppear()
Обновил

2022-11-11 12:04 UTC, megakoko commented on Tangem/App/Utilities/TwinCardsUtils.swift
>      static func makeCombinedWalletKey(for card: Card, pairData: TwinData?) -> Data? {
Удалил

2022-11-11 12:08 UTC, megakoko commented on Tangem/App/Services/CardsRepository/CommonCardsRepository.swift
> +        if let primaryCard = cardInfo.primaryCard {
Не знаю, это рефакторинг. Было несколько вызовов до создания cardVM и несколько после. Порядок я сохранил.

2022-11-11 12:11 UTC, megakoko commented on Tangem/App/Services/CardsRepository/CommonCardsRepository.swift
> +    private func startInitializingServices(for cardInfo: CardInfo) {
А как назвать так, чтобы было понятнее? Если сделать reset/setup, то почему нельзя сразу одно за другим вызвать без создания cardVM между ними?

2022-11-11 12:14 UTC, megakoko commented on Tangem/App/Services/CardsRepository/CommonCardsRepository.swift
> +    private func startInitializingServices(for cardInfo: CardInfo) {
Надо подумать насчет бекапа.

2022-11-11 12:15 UTC, megakoko commented on Tangem/App/Services/CardsRepository/CardsRepository.swift
> +    func didSwitchToModel(_ cardModel: CardViewModel)
Сделал

2022-11-11 12:15 UTC, megakoko commented on Tangem/App/Services/Common/Analytics.swift
> +import Foundation
Используется:

`extension Analytics {`

2022-11-11 12:20 UTC, megakoko commented on Tangem/App/Services/Common/TangemSigner.swift
> +                    self.userWalletListService.didScan(card: cardDto)
Это сделано для обновления списка ассоциированных воллетов в UserWallet

2022-11-11 12:26 UTC, Balashov152 commented on Tangem/App/Models/UserWallet/UserWallet.swift
> +    func cardInfo() -> CardInfo {
Да, я в девелопе удалял, теперь в статической переменной храниться, можно туда складывать например при разблокировке кошельков

2022-11-11 12:31 UTC, megakoko commented on Tangem/App/Models/UserWallet/UserWallet.swift
> +    func cardInfo() -> CardInfo {
А, я видимо при разруливании мердж-конфликтов добавил обратно. artwork нужен, мы его сохраняем на диск чтобы быстрее загрузить картинку.

2022-11-11 12:33 UTC, Balashov152 commented on Tangem/App/Services/CardImageProvider/CardImageProvider.swift
> +            .eraseToAnyPublisher()
Понял )

2022-11-11 12:43 UTC, Balashov152 commented on Tangem/Modules/AppSettings/AppSettingsCoordinator.swift
>  }
А, да, сорян, чет не заметил что это в деве есть

2022-11-11 12:51 UTC, megakoko commented on Tangem/App/Services/Common/TangemSigner.swift
> +                    self.userWalletListService.didScan(card: cardDto)
Переделаю, увидел CardViewModel.onSigned

2022-11-11 13:13 UTC, megakoko commented on Tangem/App/Services/Common/TangemSigner.swift
> +                    self.userWalletListService.didScan(card: cardDto)
Сделал

2022-11-11 13:16 UTC, megakoko commented on Tangem/App/Services/CardsRepository/CommonCardsRepository.swift
> +        walletConnectServiceProvider.reset()
Я это не трогал. Вот девелоп: https://github.com/tangem/tangem-app-ios/blob/develop/Tangem/App/Services/CardsRepository/CommonCardsRepository.swift#L58

2022-11-11 13:19 UTC, megakoko commented on Tangem/App/Services/CardsRepository/CommonCardsRepository.swift
> +    func scan(with batch: String? = nil, requestBiometrics: Bool, _ completion: @escaping (Result<CardViewModel, Error>) -> Void) {
Я это не трогал

2022-11-11 13:23 UTC, megakoko commented on Tangem/App/Services/CardsRepository/CardsRepository.swift
> +    func removeModel(withUserWalletId userWalletId: Data)
Cделал

2022-11-11 13:32 UTC, megakoko commented on Tangem/App/Services/CardsRepository/CommonCardsRepository.swift
> +        walletConnectServiceProvider.reset()
Там видимо функции менялись местами зачем-то, вернул на место

2022-11-11 13:53 UTC, Andoran90 reviewed
2 подход

2022-11-11 13:53 UTC, Andoran90 commented on Tangem/Common/Extensions/Card+.swift
> -extension Card {
надо отрефакторить это дело, чтобы CardDTO (или как он там будет потом называться) не умел так много всего делать

2022-11-11 13:53 UTC, Andoran90 commented on Tangem/App/Models/UserWallet/UserWallet.swift
> +    var isLocked: Bool {
какое можно ещё название подобрать для этого? потому что логика в коде одна, а смысл у свойства совсем иной

2022-11-11 13:53 UTC, Andoran90 commented on Tangem/Common/Preview/PreviewCard.swift
> +        let card = CardDTO(card: Card.card)
а превьюха вообще нормально работает? экран DetailsView вообще не отображается :(

2022-11-11 13:53 UTC, Andoran90 commented on Tangem/Common/TangemSdk/Tasks/AppScanTask.swift
> +    @Injected(\.userWalletListService) private var userWalletListService: UserWalletListService
зачем таске эта зависимость? почему это сохранение не может сделать CardsRepository? Я думаю таска вообще не должна знать что-то про какие-то сервисы

2022-11-11 13:53 UTC, Andoran90 commented on Tangem/App/Services/Common/TangemSigner.swift
> +                    self.userWalletListService.didScan(card: cardDto)
но вопрос зависимостей все равно остается. Я думаю этим не должен заниматься TangemSigner

2022-11-11 13:53 UTC, Andoran90 commented on Tangem/App/Services/Common/Analytics.swift
> +import Foundation
эта вся инфа переехала в папку Common/Analytics/. Конкретно этого файла нет даже в составе проекта, он просто в гите трекается
<img width="494" alt="image" src="https://user-images.githubusercontent.com/24321494/201341167-7d677487-7549-4170-a911-d3d20b5ce24e.png">

2022-11-11 13:53 UTC, Andoran90 commented on Tangem/App/Services/CardsRepository/CommonCardsRepository.swift
> +    private func startInitializingServices(for cardInfo: CardInfo) {
я так понял что ты разделил логику из-за того что можно теперь не сканировать карточку, а выбирать другую. Когда выбираешь карточку - тебе не надо создавать CardViewModel, но сбрасывать сервисы и настраивать по новой надо. Поэтому думаю логичнее что одна функция их сбрасывает, а вторая настраивает

2022-11-11 13:53 UTC, Andoran90 commented on Tangem/App/Services/CardsRepository/CommonCardsRepository.swift
> +        if let primaryCard = cardInfo.primaryCard {
но ты в любом случае из 1й функции сделал - 2. ты уже сделал рефакторинг, только я не понимаю логики формирования двух функций.

2022-11-11 13:53 UTC, Andoran90 commented on Tangem/Common/UI/Buttons/ButtonStyles.swift
> +    #warning("TODO: add all buttons styles properly")
у меня есть задачка по обновлению цветов на кнопках. займусь этим после рефералки. Сейчас некоторые кнопки неправильного цвета в темной теме

2022-11-11 13:53 UTC, Andoran90 commented on Tangem/Common/UI/Navigation/NavigationBar.swift
> +    static let color = Color.tangemGrayDark6
обновлю в IOS-2492

2022-11-11 13:53 UTC, Andoran90 commented on Tangem/Modules/AppSettings/AppSettingsViewModel.swift
> +            .sink { [weak self, userWallet] saveWallet in
может поменяет название с `saveWallet` на `shouldSaveWallet`? Текущее не очень понятно

2022-11-11 13:53 UTC, Andoran90 commented on Tangem/Modules/AppSettings/AppSettingsViewModel.swift
> +                Analytics.log(.faceIDSwitcherChanged,
разные названия, поле называется isSavingWallet, в тексте "Keep the wallet in the app", а в аналитике про Face ID. Надо к одному названию прийти и ему следовать. Причем Face ID не самое подходящее, т.к. есть ещё Touch ID.

2022-11-11 13:53 UTC, Andoran90 commented on Tangem/Modules/AppSettings/AppSettingsViewModel.swift
наверное эту логику создания алерта лучше перекинуть в `AlertBuilder`

2022-11-11 13:53 UTC, Andoran90 commented on Tangem/Modules/AppSettings/AppSettingsViewModel.swift
> +        let okButton = Alert.Button.destructive(Text("common_delete")) { [weak self] in
точно лучше в `AlertBuilder`, дублируется

2022-11-11 13:53 UTC, Andoran90 commented on Tangem/Modules/Main/MainCoordinator.swift
> -
а почему удалил эту проверку?

2022-11-11 13:53 UTC, Andoran90 commented on Tangem/Modules/Main/MainCoordinator.swift
> +    func didTapCardModel(cardModel: CardViewModel) {
```suggestion
    func didTap(_ cardModel: CardViewModel) {
```

2022-11-11 13:53 UTC, Andoran90 commented on Tangem/Modules/Main/MainCoordinator.swift
> +    func didAgree() {
может чуть накинуть контекста что именно приняли? а то в координаторе будешь писать: `did` и тебе покажется: `didAgree`, что didAgree, зачем?.. То же самое на счет `didDecline`. Когда ревьюишь и смотришь сверху вниз понятно что да как, но вот когда будешь использовать - будут вопросы.

2022-11-11 13:53 UTC, Andoran90 commented on Tangem/Modules/Onboarding/BaseModels/OnboardingViewModel.swift
> +    @Injected(\.userWalletListService) private var userWalletListService: UserWalletListService
Давай перенесем все `@Injected` на верх файла, а то всюду они в шапке файла, а тут возле инициализатора

2022-11-11 13:53 UTC, Andoran90 commented on Tangem/Modules/Onboarding/BaseModels/OnboardingViewModel.swift
> +        tangemSdkProvider.setup(with: config)
не совсем понял для чего это

2022-11-11 13:53 UTC, Andoran90 commented on Tangem/Modules/Onboarding/BaseModels/OnboardingViewModel.swift
> +        }
```suggestion
        goToStep(with: newIndex)
```

2022-11-11 13:53 UTC, Andoran90 commented on Tangem/Modules/Onboarding/BaseModels/OnboardingViewModel.swift
> +                {
скобочка съехала на новую строку

2022-11-11 13:53 UTC, Andoran90 commented on Tangem/Modules/Onboarding/BaseModels/OnboardingViewModel.swift
> +        completion(.success(()))
а зачем тут кложура, если по всем направлениям отправляется только `success`?

2022-11-14 04:57 UTC, megakoko commented on Tangem/Common/Extensions/Card+.swift
> -extension Card {
Давай потом, чтобы не раздувать этот МР. Это в-основном старый код

2022-11-14 05:01 UTC, megakoko commented on Tangem/Common/Preview/PreviewCard.swift
> +        let card = CardDTO(card: Card.card)
А в develop работает? У меня такая ошибка:

```


CompileDylibError: Failed to build DetailsView.swift

Compiling failed: no such module 'Tangem'

/Users/megakoko/Library/Developer/Xcode/DerivedData/TangemApp-cpayujbuchbmzgghbwobmdwelsoe/Build/Intermediates.noindex/Previews/Tangem Beta/Intermediates.noindex/TangemApp.build/Debug(beta)-iphonesimulator/Tangem.build/Objects-normal/arm64/DetailsView.1.preview-thunk.swift:1:51: error: no such module 'Tangem'
@_private(sourceFile: "DetailsView.swift") import Tangem
                                                  ^
```

2022-11-14 05:04 UTC, megakoko commented on Tangem/Modules/AppSettings/AppSettingsViewModel.swift
> +            .sink { [weak self, userWallet] saveWallet in
Почему? Вполне нормально — "сохранять кошелек"

2022-11-14 05:49 UTC, megakoko commented on Tangem/Modules/AppSettings/AppSettingsViewModel.swift
> +                Analytics.log(.faceIDSwitcherChanged,
Переименовал событие в saveUserWalletSwitcherChanged. Save/keep — тут проблемы не вижу. В коде считаю лучше save, т.к. привычнее, пользователям же решили показывать Keep чтобы не вызывало ненужных ассоциаций.

2022-11-14 05:52 UTC, megakoko commented on Tangem/Modules/AppSettings/AppSettingsViewModel.swift
А что здесь не так? Тут логика специфичная для этого экрана

2022-11-14 05:54 UTC, megakoko commented on Tangem/Modules/AppSettings/AppSettingsViewModel.swift
> +        let okButton = Alert.Button.destructive(Text("common_delete")) { [weak self] in
Я думаю ничего страшного нет

2022-11-14 06:01 UTC, megakoko commented on Tangem/Modules/Main/MainCoordinator.swift
> -
Не удалял, криво смерджилось

2022-11-14 06:04 UTC, megakoko commented on Tangem/Modules/Main/MainCoordinator.swift
> +    func didTapCardModel(cardModel: CardViewModel) {
Сделал

2022-11-14 06:06 UTC, megakoko commented on Tangem/Modules/Main/MainCoordinator.swift
> +    func didAgree() {
Думал что будет очевидно из контекста UserWalletStorageAgreementRoutable. Переименовал

2022-11-14 06:09 UTC, megakoko commented on Tangem/Modules/Onboarding/BaseModels/OnboardingViewModel.swift
> +        tangemSdkProvider.setup(with: config)
Переустанавливаем конфиг в дефолтный. Т.к. онбординг показывается поверх главного экрана, где до этого был установлен другой конфиг.

2022-11-14 06:09 UTC, megakoko commented on Tangem/Modules/Onboarding/BaseModels/OnboardingViewModel.swift
> +    @Injected(\.userWalletListService) private var userWalletListService: UserWalletListService
Сделал

2022-11-14 06:12 UTC, megakoko commented on Tangem/Modules/Onboarding/BaseModels/OnboardingViewModel.swift
> +        }
Исправил, спасибо

2022-11-14 06:12 UTC, megakoko commented on Tangem/Modules/Onboarding/BaseModels/OnboardingViewModel.swift
> +                {
Так и задумывалось

2022-11-14 06:35 UTC, megakoko commented on Tangem/Modules/Onboarding/BaseModels/OnboardingViewModel.swift
> +        completion(.success(()))
Раньше были асинхронные вызовы. Исправил

2022-11-14 06:57 UTC, megakoko commented on Tangem/Common/TangemSdk/Tasks/AppScanTask.swift
> +    @Injected(\.userWalletListService) private var userWalletListService: UserWalletListService
Перенес в CardsRepo

2022-11-14 06:58 UTC, megakoko commented on Tangem/App/ViewModels/CardViewModel.swift
> +        self.init(cardInfo: userWallet.cardInfo(), config: config, userWallet: userWallet)
Обновил

2022-11-14 06:59 UTC, megakoko commented on Tangem/App/Services/CardsRepository/CommonCardsRepository.swift
> +        if let primaryCard = cardInfo.primaryCard {
Логика в том, что одна вызывается до создания модели, другая — после

2022-11-14 07:03 UTC, megakoko commented on Tangem/App/Services/Common/Analytics.swift
> +import Foundation
Скажи что надо сделать чтобы исправить

2022-11-14 07:07 UTC, megakoko commented on Tangem/App/Models/UserWallet/UserWallet.swift
> +    var isLocked: Bool {
Ну смысл в том, что кошельки становятся доступными только после разблокировки — unlock. Соответственно до этого момента userwallet имеет статус locked.

2022-11-14 07:14 UTC, megakoko commented on Tangem/App/ViewModels/CardViewModel.swift
> +    }
Я добавил чтобы использовалось

2022-11-14 07:22 UTC, megakoko commented on Tangem/Common/Extensions/Card+.swift
> +    }
Эта генерация не часто вызывается, только в фабричных методах или при сканировании карты. Дальше уже используем то, что в UserWallet хранится

2022-11-14 07:28 UTC, megakoko commented on Tangem/App/Models/UserWallet/UserWallet.swift
> +        guard let firstWalletPublicKey = card.wallets.first?.publicKey else { return nil }
Вынес

2022-11-14 07:31 UTC, Balashov152 commented on Tangem/App/Services/TotalBalanceProvider/TotalBalanceProvider.swift
> +            totalBalanceAnalyticsService?.sendFirstLoadBalanceEventForCard(
Аналитика не сломается, если будет `nil` или там только для главного экрана она нужна? 

Если с `nil` ок, то может дефолтные значения добавить в `init`

2022-11-14 07:55 UTC, Balashov152 commented on Tangem/Common/UI/Buttons/ButtonStyles.swift
> +    #warning("TODO: add all buttons styles properly")
А, кнопку постраюсь на ревью отдать сегодня

2022-11-14 10:37 UTC, megakoko commented on Tangem/App/Services/TotalBalanceProvider/TotalBalanceProvider.swift
> +            totalBalanceAnalyticsService?.sendFirstLoadBalanceEventForCard(
Да, это только для главного экрана. Я бы nil явно оставил, чтобы видно было, что это скорее исключение из правила.

2022-11-14 14:30 UTC, Andoran90 reviewed
3 раунд

2022-11-14 14:30 UTC, Andoran90 commented on Tangem/Modules/Onboarding/Note/SingleCardOnboardingViewModel.swift
> +        currentStep == .saveUserWallet
думаю это стоит перенести в `SingleCardOnboardingStep`

2022-11-14 14:30 UTC, Andoran90 commented on Tangem/Modules/Onboarding/Note/SingleCardOnboardingViewModel.swift
> +        }
и это тоже в `SingleCardOnboardingStep`

2022-11-14 14:30 UTC, Andoran90 commented on Tangem/Modules/Onboarding/Note/SingleCardOnboardingViewModel.swift
> -            fallthrough
может стоит показать пользователю конфети, а после того как он попробует пойти дальше - предложить биометрию? мне кажется сейчас конфети вообще показываться не будут, даже если биометрия была включена ранее

2022-11-14 14:30 UTC, Andoran90 commented on Tangem/Modules/Onboarding/OnboardingCoordinator.swift
>              walletViewModel = model
это стоит вынести в фабрику, которая генерирует вью модели для онбординга и на вход принимает опции. Будет дополнительная сущность, но координатор не должен заниматься выбором какую вью модель сгенерировать.

2022-11-14 14:30 UTC, Andoran90 commented on Tangem/Modules/Onboarding/Twins/TwinsOnboardingViewModel.swift
> +        currentStep == .saveUserWallet
тот же коммент что и для `SingleCardOnboardingViewModel`, думаю такое же будет и для Wallet

2022-11-14 14:30 UTC, Andoran90 commented on Tangem/Modules/ScanCardSettings/ScanCardSettingsViewModel.swift
> +                cardModel.didScan() // TODO: refactor
тут вся та же логика что и в `processSuccessScan`, надо почистить, и тут и там создается конфиг, и тут и там кард модель и `didScan` вызывается.

2022-11-14 14:30 UTC, Andoran90 commented on Tangem/Modules/UserWalletList/CommonUserWalletListService.swift
> +        return models.first {
можно `return` убрать

2022-11-14 14:30 UTC, Andoran90 commented on Tangem/Modules/UserWalletList/CommonUserWalletListService.swift
> +    }
давай уберем пустую функцию или же она понадобится?

2022-11-14 14:30 UTC, Andoran90 commented on Tangem/Modules/UserWalletList/CommonUserWalletListService.swift
> +class CommonUserWalletListService: UserWalletListService {
думаю стоит добавить сюда `UserWalletsStorage` зависимость, в которую вынести всю логику сохранения в файл информации про пользовательские кошельки. Получается у менеджера будут зависимости от `UserWalletsStorage`, `UserWalletEncryptionKeyStorage` и `CardsRepository` (который, к слову, было бы хорошо тоже переименовать или отрефакторить, потому что репозиторий занимается сканированием, созданием вью моделей, настройкой сервисов и хранением вью моделей)

2022-11-14 14:30 UTC, Andoran90 commented on Tangem/Modules/UserWalletList/CommonUserWalletListService.swift
> +            loadModels()
карточка которой разблокировали добавляется только после биометрии? тут не надо добавлять карточку в список `userWallets`?

2022-11-14 14:30 UTC, Andoran90 commented on Tangem/Modules/UserWalletList/CommonUserWalletListService.swift
> +        }
как вариант можно сделать:
```suggestion
        let models = userWallets.map(CardViewModel.init)
```

2022-11-14 14:30 UTC, Andoran90 commented on Tangem/Modules/UserWalletList/UserWalletEncryptionKeyStorage.swift
> +    }
а зачем пустой инициализатор?

2022-11-14 14:30 UTC, Andoran90 commented on Tangem/Modules/UserWalletList/CommonUserWalletListService.swift
> +    private func publicDataEncryptionKey() throws -> SymmetricKey {
не до конца понятно что это: сервис или репозиторий? основная логика все же по хранению и синхронизации нескольких хранилищ. Как минимум логику шифрования/дешифрования надо вынести в отдельный класс, который будет этим заниматься.

2022-11-14 14:30 UTC, Andoran90 commented on Tangem/Modules/UserWalletList/UserWalletEncryptionKeyStorage.swift
> +            print("Failed to add UserWallet ID to the list: \(error)")
может добавить сюда аналитику? или это в другой задаче есть?

2022-11-14 14:30 UTC, Andoran90 commented on Tangem/Modules/UserWalletList/UserWalletEncryptionKeyStorage.swift
> +    private func encryptionKeyStorageKey(for userWallet: UserWallet) -> String {
это приватная функция `UserWalletEncryptionKeyStorage`, думаю нет смысла дублировать эти названия
```suggestion
    private func storageKey(for userWallet: UserWallet) -> String {
```

2022-11-14 14:30 UTC, Andoran90 commented on Tangem/Modules/UserWalletList/UserWalletEncryptionKeyStorage.swift
> +    private func userWalletIds() throws -> Set<Data> {
мне кажется что `userWalletIds` больше подходит не в качестве названия функции, а в качестве свойства или переменной, а функции это действия (как например ниже: `saveUserWalletIds`), которые надо выполнить, поэтому думаю лучше изменить название:
```suggestion
    private func fetchUserWalletIds() throws -> Set<Data> {
```
или же `loadUserWalletIds()`

2022-11-14 14:30 UTC, Andoran90 commented on Tangem/Modules/UserWalletList/UserWalletListCellView.swift
> +            .sink { [unowned self] balance in
на версия иос ниже 15 может утекать память, есть проблемы с `unowned` в комбайне, таких элементов (`UserWalletListCellView`) может быть много, поэтому давай лучше сделаем через `weak`

2022-11-14 14:30 UTC, Andoran90 commented on Tangem/Modules/UserWalletList/UserWalletListCellView.swift
> +                        self.numberOfTokens = nil
сильный захват `self`

2022-11-14 14:30 UTC, Andoran90 commented on Tangem/Modules/UserWalletList/UserWalletListCellView.swift
> +            }
```suggestion
            .weakAssignAnimated(to: (\.image), on: self)
```

2022-11-14 14:30 UTC, Andoran90 commented on Tangem/Modules/UserWalletList/UserWalletListCellView.swift
> +class UserWalletListCellViewModel: ObservableObject {
вынеси в отдельный файл, пожалуйста

2022-11-14 14:30 UTC, Andoran90 commented on Tangem/Modules/UserWalletList/UserWalletListCellView.swift
> +struct UserWalletListCellView: View {
добавь превьюшку, пожалуйста

2022-11-14 14:30 UTC, Andoran90 commented on Tangem/Modules/UserWalletList/UserWalletListCellView.swift
> +    @ObservedObject private var viewModel: UserWalletListCellViewModel
а почему приватной сделал? у нас же везде вью модель не приватная и без инциализатора

2022-11-14 14:30 UTC, Andoran90 commented on Tangem/Modules/UserWalletList/UserWalletListCellView.swift
> +            Color.tangemGrayLight4
наверное лучше брать из Colors. Ты темную тему проверял?

2022-11-14 14:30 UTC, Andoran90 commented on Tangem/Modules/UserWalletList/UserWalletListView.swift
> +            return Color(hex: "F2F2F7")!
печаль, надо бы что-то придумать для темной темы на 13 оси

2022-11-14 14:30 UTC, Andoran90 commented on Tangem/Modules/UserWalletList/UserWalletListView.swift
> +extension UserWalletListView {
а зачем `extension`?

2022-11-14 14:30 UTC, Andoran90 commented on Tangem/Modules/UserWalletList/UserWalletListView.swift
> +    static var sheetBackground: Color {
почему статичное свойство?

2022-11-14 14:30 UTC, Andoran90 commented on Tangem/Modules/UserWalletList/UserWalletListView.swift
> +                    if !viewModel.isUnlocked {
давай лучше `isLocked`, чтобы не было отрицания. Я за то чтобы избегать отрицания в условных конструкциях, проще читается

2022-11-14 14:30 UTC, Andoran90 commented on Tangem/Modules/UserWalletList/UserWalletListView.swift
> +    private func list() -> some View {
может лучше свойством и остальные пустые функции тоже?
```suggestion
    private var list: some View {
```

2022-11-14 14:30 UTC, Andoran90 commented on Tangem/Modules/UserWalletList/UserWalletListView.swift
> +    }
```suggestion
    @ViewBuilder
    private func sectionHeader(name: String) -> some View {
        if #available(iOS 15, *) {
            UserWalletListHeaderView(name: name)
                .listRowSeparator(.hidden)
                .listRowInsets(EdgeInsets())
        } else {
            UserWalletListHeaderView(name: name)
        }
    }
```

бесполезная функция

2022-11-14 14:30 UTC, Andoran90 commented on Tangem/Modules/UserWalletList/UserWalletListView.swift
> +                    }
стоит выбрать одно из двух:
```suggestion
                    Button(role: .destructive) {
                        self.viewModel.showDeletionConfirmation(viewModel)
                    } label: {
                        deleteButtonLabel()
                    }
```

для второго варианта надо переделать `deleteButtonLabel` в свойство
```suggestion
                    Button(role: .destructive) {
                        self.viewModel.showDeletionConfirmation(viewModel)
                    } label: {
                        deleteButtonLabel
                    }
```

Думаю лучше использовать второй вариант, потому что стоит придерживаться одного стиля написания кода, в данном случае в виде свойств, если нет параметров

2022-11-14 14:30 UTC, Andoran90 commented on Tangem/Modules/UserWalletList/UserWalletListView.swift
> +}
сделай превью, пожалуйста

2022-11-14 14:30 UTC, Andoran90 commented on Tangem/Modules/UserWalletList/UserWalletListViewModel.swift
> +        singleCurrencyModels.removeAll { $0.userWalletId == viewModel.userWalletId }
```suggestion
        if viewModel.isMultiWallet {
            multiCurrencyModels.removeAll { $0.userWalletId == viewModel.userWalletId }
        } else {
            singleCurrencyModels.removeAll { $0.userWalletId == viewModel.userWalletId 
        }    
```

2022-11-14 14:30 UTC, Andoran90 commented on Tangem/Modules/UserWalletList/UserWalletListViewModel.swift
> +        {
скобочка скатилась на новую строчку

2022-11-14 14:30 UTC, Andoran90 commented on Tangem/Modules/UserWalletList/UserWalletListViewModel.swift
> +        }
странно получается, вместо того чтобы сохранять ссылку на вью модель, ты сохраняешь `userWalletId`, чтобы потом по этой инфе искать вью модель. Давай лучше сразу сохранять ссылку на вью модель, не надо будет искать по новой, а если во вьюхе передавать ещё и индекс, тогда вообще будет простое взаимодействие с массивами, не надо будет постоянно их объединять и прогонять их в циклах для поиска и удаления. Надо будет хранить только вью модель для удаления и её индекс, а через `isMultiWallet` определять из какого массива удалять

2022-11-14 14:30 UTC, Andoran90 commented on Tangem/Modules/UserWalletList/UserWalletListViewModel.swift
> +//                selectedModel.userWalletModel?.updateAndReloadWalletModels(showProgressLoading: true)
может удалить или это на Новый год?

2022-11-14 14:30 UTC, Andoran90 commented on Tangem/Modules/Welcome/WelcomeCoordinator.swift
> +    @Injected(\.userWalletListService) private var userWalletListService: UserWalletListService
лучше все `@Injected` держать в одном месте в шапке файла

2022-11-14 14:30 UTC, Andoran90 commented on Tangem/Modules/Welcome/WelcomeView.swift
> +                storiesView
лучше бы это разделить на 2 экрана отдельных, а то `WelcomeView` и `WelcomeViewModel` становятся чем монструозным

2022-11-14 15:02 UTC, Andoran90 commented on Tangem/Modules/AppSettings/AppSettingsViewModel.swift
> +            .sink { [weak self, userWallet] saveWallet in
если сохранять кошелек - если должен сохранить кошелек, но это минор)

2022-11-14 15:04 UTC, Andoran90 commented on Tangem/Modules/AppSettings/AppSettingsViewModel.swift
не, логика кнопки специфичная её трогать не надо, надо перенести создание самого алерта с кнопками, у тебя они дублируются в соседних функциях. чище и без повторения таких кусков будет

2022-11-14 19:07 UTC, tureck1y requested changes

2022-11-14 19:07 UTC, tureck1y commented on Tangem/App/Models/CardInfo.swift
> +    var name: String
лишнее и не используется

2022-11-14 19:07 UTC, tureck1y commented on Tangem/App/Models/UserWallet/UserWalletConfig.swift
> +    var cardName: String { get }
имя воллета?

2022-11-14 19:07 UTC, tureck1y commented on Tangem/App/Models/UserWallet/UserWalletConfig.swift
> +    var needUserWalletSavingSteps: Bool {
Это и userWalletSavingSteps это внутренняя кухня конфига, ее не надо в публичный интерфейс. Лучше пока сделать по аналогии с _backupSteps.

2022-11-14 19:07 UTC, tureck1y commented on Tangem/App/Models/UserWallet/Implementations/GenericConfig.swift
> +        guard needUserWalletSavingSteps else { return [] }
нет пустой строки после guard

2022-11-14 19:07 UTC, tureck1y commented on Tangem/App/Models/UserWallet/Implementations/GenericConfig.swift
> +            return .wallet([.createWallet] + _backupSteps + userWalletSavingSteps + [.success])
В _backupSteps тоже остался success шаг. Надо убрать его из _backupSteps, но оставить в backupSteps. 

В дело конфиге аналогично

2022-11-14 19:07 UTC, tureck1y commented on Tangem/App/Models/UserWallet/Implementations/GenericDemoConfig.swift
В демо конфиге тоже наверное нужны все эти шаги новые?

2022-11-14 19:07 UTC, tureck1y commented on Tangem/App/Models/UserWallet/Implementations/GenericDemoConfig.swift
И в легаси конфиге

2022-11-14 19:07 UTC, tureck1y commented on Tangem/App/Models/UserWallet/Implementations/NoteConfig.swift
> +            return .singleWallet([.createWallet, .topup, .successTopup] + userWalletSavingSteps + [.success])
Тут что-то очень странное. У нас есть два типа успешных последних шагов: success и successTopup.  successTopup работает в паре с topup. Тут очевидно, что success лишний, а userWalletSavingSteps должны идти после создания кошелька.

2022-11-14 19:07 UTC, tureck1y commented on Tangem/App/Models/UserWallet/Implementations/NoteDemoConfig.swift
>  struct NoteDemoConfig {
Демо ноута тоже без шагов остался

2022-11-14 19:07 UTC, tureck1y commented on Tangem/App/Models/UserWallet/Implementations/SaltPayConfig.swift
> +    private let card: CardDTO
У солтпэя видимо надо шаги положить прям в registrationSteps перед добавлением success-шагов. Некрасиво, потом поправим

2022-11-14 19:07 UTC, tureck1y commented on Tangem/App/Models/UserWallet/Implementations/SaltPayConfig.swift
> +        "Salt Pay"
SaltPay

2022-11-14 19:07 UTC, tureck1y commented on Tangem/App/Models/UserWallet/Implementations/Start2CoinConfig.swift
Нет доп шагов

2022-11-14 19:07 UTC, tureck1y commented on Tangem/App/Models/UserWallet/Implementations/TwinConfig.swift
> +            steps.append(TwinsOnboardingStep.success)
TwinsOnboardingStep.topupSteps содержит в себе уже успешный шаг done. [.topup, .done]
TwinsOnboardingStep.success тут не нужен
думаю надо удалить topupSteps и добавлять явно .topup,  userWalletSavingSteps, .done

2022-11-14 19:07 UTC, tureck1y commented on Tangem/Assets/Colors.xcassets/Background/BackgroundAction.colorset/Contents.json
> +          "blue" : "0x00",
@Balashov152 вроде уже менял в цветах что-то

2022-11-14 19:07 UTC, tureck1y commented on Tangem/App/Models/UserWallet/UserWalletEncryptionKey.swift
> +    init(publicKey: Data) {
Нужна единая утилита с этим алгоритмом, в которую можно передать сообщение, закрытое enum

2022-11-14 19:07 UTC, tureck1y commented on Tangem/Modules/Welcome/WelcomeView.swift
> +    var storiesView: some View {
private

2022-11-14 19:07 UTC, tureck1y commented on Tangem/Modules/Welcome/WelcomeView.swift
> +    var unlockView: some View {
private

2022-11-14 19:07 UTC, tureck1y commented on Tangem/Modules/Welcome/WelcomeCoordinator.swift
> +import TangemSdk
зачем координатору TangemSdk?

2022-11-14 19:07 UTC, tureck1y commented on Tangem/Modules/Welcome/WelcomeCoordinator.swift
> +            welcomeViewModel.unlockWithBiometry()
Да сканирование тут тоже лишнее. Координатор это про навигацию. Может попробовать все в onAppear унести?

2022-11-14 19:07 UTC, tureck1y commented on Tangem/Modules/Welcome/WelcomeCoordinator.swift
> +    @Injected(\.userWalletListService) private var userWalletListService: UserWalletListService
не используется

2022-11-14 19:07 UTC, tureck1y commented on Tangem/Modules/Welcome/WelcomeViewModel.swift
> +        cardsRepository.didSwitch(to: model)
userWalletListService наверное сам может этот вызов сделать

2022-11-14 19:07 UTC, tureck1y commented on Tangem/Modules/Welcome/WelcomeViewModel.swift
> +    private func scanCardInternal(_ completion: @escaping (CardViewModel) -> Void) {
не понял сути этих изменений. Обычный скан должен отрабатывать со всей солпеевской логикой, независимо от места, где он вызван. Скан должен уехать в репозиторий

2022-11-14 19:07 UTC, tureck1y commented on Tangem/Modules/UserWalletStorageAggreement/UserWalletStorageAgreementRoutable.swift
> +    func didAgreeToSaveUserWallets()
В Routable держим только навигацию, открыть то, закрыть это.

2022-11-14 19:07 UTC, tureck1y commented on Tangem/Modules/Main/MainView.swift
> +    var leadingNavigationButtons: some View {
надо нам не забывать во вьюхах тоже пользоваться модификаторами уровня доступа

2022-11-14 19:07 UTC, tureck1y commented on Tangem/App/Services/CardsRepository/CommonCardsRepository.swift
> +    private(set) var models = [CardViewModel]()
UserWalletListService и CommonCardsRepository это одно и то же, их нужно объединить и код сканирования разместить внутри. Репозииторий можно открыть биометрией или картой.
Сейчас на велком одни операции выполняются, а в UserWalletListViewModel - другие

2022-11-14 19:07 UTC, tureck1y commented on Tangem/App/Services/CardsRepository/CommonCardsRepository.swift
> +    func scan(with batch: String? = nil, requestBiometrics: Bool, _ completion: @escaping (Result<CardViewModel, Error>) -> Void) {
requestBiometrics тут лишний. Фабрика конфига может сама сходить в UserPrefs и понять как собирать конфигурации

2022-11-14 19:07 UTC, tureck1y commented on Tangem/App/Services/Common/Analytics/Analytics.swift
> +    static func logScan(card: CardDTO, config: UserWalletConfig) {
вроде бы в аналитике можно было обычную карту оставить. DTO только для стораджа нужна

2022-11-14 19:07 UTC, tureck1y commented on Tangem/App/Services/TotalBalanceProvider/TotalBalanceProvider.swift
> +            totalBalanceAnalyticsService?.sendFirstLoadBalanceEventForCard(
а в чем проблема проинициализировать аналитику?

2022-11-14 19:07 UTC, tureck1y commented on Tangem/App/Services/UserWalletModel/CommonUserWalletModel.swift
> +    convenience init(config: UserWalletConfig, userWallet: UserWallet) {
userWallet: UserWallet совершенно лишний. Его надо выкинуть.  Вот у нас уже есть CommonUserWalletModel, которую надо просто создать из репозитория

2022-11-14 19:07 UTC, tureck1y commented on Tangem/App/Models/UserWallet/UserWallet.swift
> +struct UserWallet: Identifiable, Codable {
Его надо вообще удалить, у нас уже есть модель

2022-11-14 19:07 UTC, tureck1y commented on Tangem/App/Utilities/BiometricAuthorizationUtils.swift
>  enum BiometricAuthorizationUtils {
1) Я согласен SwiftUI тут быть не должно. Возвращать можно строки, а уже в онбординге конвертную в ключи. У нас уже где-то это использовалось.
2) Зачем вообще нужна отдельная утилита, когда есть BiometricsUtil? К ней можно написать экстеншн. А так плодим утилиты с похожими названиями и сами будем путаться. 
3) State не используется совсем, можно удалить и обойтись isAvailable.

2022-11-14 19:07 UTC, tureck1y commented on Tangem/Modules/Welcome/WelcomeViewModel.swift
> +    func bind() {
Ну этот код должен быть не здесь, а в сервисе. А завтра не будет экрана велком и все, секьюрность отвалится?

2022-11-14 19:07 UTC, tureck1y commented on Tangem/Common/UI/DefaultListViews/DefaultHeaderView.swift
> +struct DefaultHeaderView: View {
а почему эти изменения тут, мы же в девелоперах смержили?

2022-11-14 19:07 UTC, tureck1y commented on Tangem/Common/Extensions/Card+.swift
> +    }
Есть struct UserWalletId. Эту переменную надо удалить нафиг

2022-11-14 19:07 UTC, tureck1y commented on Tangem/App/ViewModels/CardViewModel.swift
> +    private(set) var cardInfo: CardInfo
запрещенный прием, я не просто так ее закрыл, а чтоб не осложнять рефакторинг

2022-11-14 19:07 UTC, tureck1y commented on Tangem/App/ViewModels/CardViewModel.swift
> +    lazy var signer: TangemSigner = config.tangemSigner
Лайнер должен уметь меняться, создали бэкап - лайнер будет иначе создаваться

2022-11-14 19:07 UTC, tureck1y commented on Tangem/App/ViewModels/CardViewModel.swift
> +
опять запрещенные приемы, нельзя отдавать это наружу

2022-11-14 19:07 UTC, tureck1y commented on Tangem/App/ViewModels/CardViewModel.swift
> +    }
Что-то лишнее

2022-11-14 19:07 UTC, tureck1y commented on Tangem/App/ViewModels/CardViewModel.swift
> +    }
карта, которая отдает UserWallet????

2022-11-14 19:07 UTC, tureck1y commented on Tangem/App/ViewModels/CardViewModel.swift
> +    convenience init(userWallet: UserWallet) {
Откуда тут вообще взялся userwallet???

2022-11-14 19:07 UTC, tureck1y commented on Tangem/App/ViewModels/CardViewModel.swift
> +    convenience init(userWallet: UserWallet) {
У нас уже есть модель UserWallet, почему она не используется?

2022-11-14 19:07 UTC, tureck1y commented on Tangem/App/ViewModels/CardViewModel.swift
> +    }
Это должна решать фабрика, которая создает конфигурацию сдк

2022-11-14 19:07 UTC, tureck1y commented on Tangem/App/ViewModels/UserWalletFactory.swift
> +    func userWallet(from cardInfo: CardInfo, config: UserWalletConfig) -> UserWallet {
1) makeUserWallet
2) конфиг вроде бы и не нужно сюда передавать

2022-11-14 19:07 UTC, tureck1y commented on Tangem/App/ViewModels/UserWalletFactory.swift
> +    func userWallet(from cardViewModel: CardViewModel) -> UserWallet {
что-то лишнее

2022-11-14 19:07 UTC, tureck1y commented on Tangem/Common/TangemSdk/Tasks/AppScanTask.swift
> +    let allowsAccessCodeFromRepository = false
```suggestion
    var allowsAccessCodeFromRepository: Bool { true }
```

2022-11-14 19:07 UTC, tureck1y commented on Tangem/Common/TangemSdk/Tasks/AppScanTask.swift
> +        guard let plainCard = session.environment.card else {
rawCard

2022-11-14 19:07 UTC, tureck1y commented on Tangem/Modules/Details/DetailsRoutable.swift
> +    func openAppSettings(userWallet: UserWallet)
```suggestion
    func openAppSettings(with userWallet: UserWallet)
```

2022-11-14 19:07 UTC, tureck1y commented on Tangem/Modules/AppSettings/AppSettingsViewModel.swift
> +            userWalletListService.clear()
тут явно какая-то ошибка

2022-11-14 19:07 UTC, tureck1y commented on Tangem/Modules/AppSettings/AppSettingsViewModel.swift
> +                    self.setSaveWallets(false)
Из вьюмодели дергается сервис, потом в каллбэке опять дергается сервис, потом дергается функция, которая дергает этот же сервис????

2022-11-14 19:07 UTC, tureck1y commented on Tangem/Modules/Onboarding/OnboardingCoordinator.swift
>              walletViewModel = model
потом

2022-11-14 19:07 UTC, tureck1y commented on Tangem/Modules/Onboarding/OnboardingCoordinator.swift
> +        let saveUserWalletOnFinish: Bool
Почему нельзя было  в input положить? Честно говоря я до конца не понял нужности этого параметра. Почему сохраняется в конце онбординга а не сразу, почему прокидывается откуда-то

2022-11-14 19:07 UTC, tureck1y commented on Tangem/Modules/Main/MainCoordinator.swift
> +        pushedOnboardingCoordinator = coordinator
@Andoran90 тут все ок? Мне кажется не нужен поптурут и destination main. По завершению нужны же просто назад выйти?

2022-11-14 19:07 UTC, tureck1y commented on Tangem/Modules/Main/MainCoordinator.swift
> +    }
я уже писал про это, но тут прям наглядно, если посмотреть на лог

2022-11-14 19:07 UTC, tureck1y commented on Tangem/Modules/Main/MainViewModel.swift
> +    var saveUserWallets: Bool {
из названия saveUserWallets непонятно за что переменная отвечает

2022-11-14 19:07 UTC, tureck1y commented on Tangem/Modules/Main/MainViewModel.swift
> +        cardModel.onAppear()
onAppear у модели?

2022-11-14 19:07 UTC, tureck1y commented on Tangem/Modules/Main/MainViewModel.swift
> +    }
почему этим занимается вьюмодель главного экрана?

2022-11-14 19:07 UTC, tureck1y commented on Tangem/Modules/UserWalletList/UserWalletListView.swift
> +            return Color(hex: "F2F2F7")!
Если изначально в ргб задать, то сконвертит вроде

2022-11-14 19:07 UTC, tureck1y commented on Tangem/Modules/UserWalletList/UserWalletListRoutable.swift
> +    func didTap(_ cardModel: CardViewModel)
openWallet или что-то подобное. didTap скорее для вьюмодели подходит

2022-11-14 19:07 UTC, tureck1y commented on Tangem/Modules/UserWalletList/UserWalletListViewModel.swift
> +final class UserWalletListViewModel: ObservableObject, Identifiable {
Identifiable нужен для модели?

2022-11-14 19:07 UTC, tureck1y commented on Tangem/Modules/UserWalletList/UserWalletListViewModel.swift
> +        cardsRepository.scanPublisher(requestBiometrics: true)
Скан и все что можно уносим в репу

2022-11-14 19:07 UTC, tureck1y commented on Tangem/Modules/UserWalletList/UserWalletListViewModel.swift
> +    private func openOnboarding(with input: OnboardingInput) {
все навигационные функции можно сгруппировать и положить вниз в экстеншн, как в других модулях

2022-11-14 19:07 UTC, tureck1y commented on Tangem/Modules/UserWalletList/UserWalletListViewModel.swift
> +    }
а зачем отдельно хранить?

2022-11-14 19:07 UTC, tureck1y commented on Tangem/Modules/UserWalletList/UserWalletListViewModel.swift
> +        let alert = UIAlertController(title: "user_wallet_list_rename_popup_title".localized, message: nil, preferredStyle: .alert)
UIKit  во вьюмодели выглядит немного странно. Лучше хотя бы вынести это в класс-фабрику AlertBuilder

2022-11-14 19:07 UTC, tureck1y commented on Tangem/Modules/UserWalletList/UserWalletListViewModel.swift
> +        }
Код это функции выглядит непонятно и чертовски хрупко. Нужно переписать полностью и снабдить комментами.

2022-11-14 19:07 UTC, tureck1y commented on Tangem/Modules/UserWalletList/UserWalletListService.swift
> +    var isUnlocked: Bool { get }
разбросаны переменные

2022-11-14 19:07 UTC, tureck1y commented on Tangem/Modules/UserWalletList/UserWalletListService.swift
> +    func unlockWithCard(_ userWallet: UserWallet, completion: @escaping (Result<Void, Error>) -> Void)
unlock c enum параметром biometrics/card, скан внутри будет происходить

2022-11-14 19:07 UTC, tureck1y commented on Tangem/Modules/UserWalletList/UserWalletListService.swift
> +    func didScan(card: CardDTO)
add?

2022-11-14 19:07 UTC, tureck1y commented on Tangem/Modules/UserWalletList/UserWalletListService.swift
> +private struct UserWalletListServiceKey: InjectionKey {
Объедини его пожалуйста с CardsRepository.  Он для этого и задумывался в своем время. Можно назвать с UserWalletRepository

2022-11-14 19:07 UTC, tureck1y commented on Tangem/Modules/UserWalletList/CommonUserWalletListService.swift
> +        savedUserWallets(withSensitiveData: false).isEmpty
что-то на неоптимальном

2022-11-14 19:07 UTC, tureck1y commented on Tangem/Modules/UserWalletList/CommonUserWalletListService.swift
> +    }
зачем нужны эти лишние переменные?

2022-11-14 19:07 UTC, tureck1y commented on Tangem/Modules/UserWalletList/CommonUserWalletListService.swift
> +            loadModels()
Публичная информация должна загружаться еще на конструкторе, а приватная уже при разблокировке

2022-11-14 19:07 UTC, tureck1y commented on Tangem/Modules/UserWalletList/CommonUserWalletListService.swift
> +            cardsRepository.add(CardViewModel(userWallet: userWallet))
Откуда вообще взялись карты в репозитория UserWallet? Да, cardViewModel у нас используется еще в приложении, нужно сделать адаптер, получение ее из UserWallet и потом удалить с рефакторингом, а не писать код, который уже нужно рефакторить

2022-11-14 19:07 UTC, tureck1y commented on Tangem/Modules/UserWalletList/CommonUserWalletListService.swift
> +        saveUserWallets([])
очень странная конструкция

2022-11-14 19:07 UTC, tureck1y commented on Tangem/Modules/UserWalletList/CommonUserWalletListService.swift
> +            for i in 0 ..< userWallets.count {
привет с++ ))

2022-11-14 19:07 UTC, tureck1y commented on Tangem/Modules/UserWalletList/CommonUserWalletListService.swift
> +    private func savedUserWallets(withSensitiveData loadSensitiveData: Bool) -> [UserWallet] {
1) Отдельно грузим все публичное
2) Отдельно грузим приватное по паре userWalletId и ключ

2022-11-14 19:07 UTC, tureck1y commented on Tangem/Modules/UserWalletList/CommonUserWalletListService.swift
> +    private func publicDataEncryptionKey() throws -> SymmetricKey {
1) Проблема с неймингом функций. Мне непонятно что делают функции publicDataEncryptionKey и userWalletListPath.
2) Никакой синхронизации хранилищ быть не должно. Кто это придумал вообще?
3) encrypt/decrypt надо сделать экстеншенами
4) publicDataEncryptionKey() заслуживает отдельного класса/утилиты

2022-11-14 19:07 UTC, tureck1y commented on Tangem/Modules/UserWalletList/UserWalletEncryptionKeyStorage.swift
> +            let userWalletIds = try userWalletIds()
В этом классе смешана работа с id и ключами. SRP?

2022-11-14 19:07 UTC, tureck1y commented on Tangem/Modules/UserWalletList/UserWalletEncryptionKeyStorage.swift
> +    }
Экономия на функциях?

2022-11-14 19:07 UTC, tureck1y commented on Tangem/Modules/Onboarding/BaseModels/OnboardingViewModel.swift
> +            if index == (steps.count - 1) {
что-то лишнее, конфетти показываем на последнем шаге

2022-11-14 19:07 UTC, tureck1y commented on Tangem/Modules/Onboarding/BaseModels/OnboardingViewModel.swift
> +        tangemSdkProvider.setup(with: config)
давай как-то иначе это сделаем, ну точно не на деините же

2022-11-14 19:07 UTC, tureck1y commented on Tangem/Modules/Onboarding/BaseModels/OnboardingViewModel.swift
> +                {
Тут проблема не в скобочке поехавшей, а в том, что мы вызываем у репы анлок, а потом в кллбэке во вьюмодели ОНБОРДИНГА, дергаем это

```
func saveUserWalletIfNeeded() throws {
         guard
             AppSettings.shared.saveUserWallets,
             let userWallet = input.cardInput.cardModel?.userWallet,
             !userWalletListService.contains(userWallet)
         else {
             return
         }

         userWalletListService.save(userWallet)
         userWalletListService.selectedUserWalletId = userWallet.userWalletId
     }
```

2022-11-14 19:07 UTC, tureck1y commented on Tangem/Modules/Onboarding/BaseModels/OnboardingViewModel.swift
> +            if saveUserWalletOnFinish {
Зачем это надо? Почему нельзя сохранить сразу, как только пользователь согласился на соотв экране?

2022-11-14 19:07 UTC, tureck1y commented on Tangem/Modules/Onboarding/BaseModels/OnboardingViewModel.swift
> +            if saveUserWalletOnFinish {
Невозможно читать этот метод. Вроде весь код синхронный, а вроде и на каллбэках

2022-11-14 19:07 UTC, tureck1y commented on Tangem/Modules/Onboarding/BaseModels/OnboardingViewModel.swift
> +    @Injected(\.tangemSdkProvider) private var tangemSdkProvider: TangemSdkProviding
нигде тут не используется кроме как для тасовки конфига

2022-11-14 19:07 UTC, tureck1y commented on Tangem/Modules/Onboarding/BaseModels/OnboardingTopupViewModel.swift
> +        }
лишнее

2022-11-14 19:07 UTC, tureck1y commented on Tangem/Modules/Onboarding/Note/SingleCardOnboardingStep.swift
> -        case .success, .successTopup: return true
надо вернуть на место

2022-11-14 19:07 UTC, tureck1y commented on Tangem/Modules/Onboarding/Twins/TwinsOnboardingStep.swift
> -        case .success, .done:
надо вернуть на место

2022-11-14 19:07 UTC, tureck1y commented on Tangem/Modules/Onboarding/OnboardingCoordinator.swift
> +        let options = MainCoordinator.Options(cardModel: cardModel, shouldRefresh: false)
что такое shouldRefresh?

2022-11-14 19:07 UTC, tureck1y commented on Tangem/Modules/Main/MainCoordinator.swift
> +    }
Запускает сам себя???

2022-11-14 19:07 UTC, tureck1y commented on Tangem/Modules/Onboarding/Wallet/WalletOnboardingViewModel.swift
> -            jumpToLatestStep()
это надо вернуть, ты ломаешь другую логику

2022-11-14 19:07 UTC, tureck1y commented on Tangem/Modules/Onboarding/Wallet/WalletOnboardingViewModel.swift
> +        try accessCodeRepository.save(accessCodeData, for: cardIds)
все это же можно в отдельный какой-то сервис положить, как и в базовой вьюмодели

2022-11-14 19:07 UTC, tureck1y commented on Tangem/Modules/Onboarding/Wallet/WalletOnboardingViewModel.swift
> +            self.accessCode = code
а потом этот код класть сразу туда

2022-11-14 19:07 UTC, tureck1y commented on Tangem/Modules/Onboarding/Twins/TwinsOnboardingViewModel.swift
> -        case .done, .success:
надо вернуть

2022-11-14 19:07 UTC, tureck1y commented on Tangem/Modules/Onboarding/Note/SingleCardOnboardingViewModel.swift
> -            fallthrough
конфетти же всегда на последнем успешном шаге

2022-11-15 03:47 UTC, megakoko commented on Tangem/App/Models/UserWallet/Implementations/GenericConfig.swift
> +            return .wallet([.createWallet] + _backupSteps + userWalletSavingSteps + [.success])
Удалил

2022-11-15 03:54 UTC, megakoko commented on Tangem/App/Models/UserWallet/Implementations/NoteConfig.swift
> +            return .singleWallet([.createWallet, .topup, .successTopup] + userWalletSavingSteps + [.success])
Хотели сохранение делать предпоследним шагом, поэтому так сделал

2022-11-15 03:55 UTC, megakoko commented on Tangem/App/Models/UserWallet/Implementations/NoteDemoConfig.swift
>  struct NoteDemoConfig {
Сделал

2022-11-15 03:55 UTC, megakoko commented on Tangem/App/Models/UserWallet/Implementations/GenericDemoConfig.swift
Добавил в демо воллета

2022-11-15 03:56 UTC, megakoko commented on Tangem/App/Models/UserWallet/Implementations/SaltPayConfig.swift
> +        "Salt Pay"
Сделал

2022-11-15 03:59 UTC, megakoko commented on Tangem/App/Models/UserWallet/Implementations/SaltPayConfig.swift
> +    private let card: CardDTO
Что делать если можно заклеймить монеты?

```
        if registrator.canClaim {
            steps.append(.claim)
            steps.append(.successClaim)
        } else {
            steps.append(.success)
        }
```

2022-11-15 04:04 UTC, megakoko commented on Tangem/App/Services/TotalBalanceProvider/TotalBalanceProvider.swift
> +            totalBalanceAnalyticsService?.sendFirstLoadBalanceEventForCard(
Лишний раз будет срабатывать на шторке

2022-11-15 04:09 UTC, megakoko commented on Tangem/Common/TangemSdk/Tasks/AppScanTask.swift
> +    let allowsAccessCodeFromRepository = false
Зачем? Мы же наоборот не хотим читать access code

2022-11-15 04:11 UTC, megakoko commented on Tangem/Modules/AppSettings/AppSettingsViewModel.swift
> +            userWalletListService.clear()
Все правильно, очищаем сохраненные user wallet

2022-11-15 04:15 UTC, megakoko commented on Tangem/Modules/UserWalletList/UserWalletListViewModel.swift
> +final class UserWalletListViewModel: ObservableObject, Identifiable {
Да, для .sheet(item: $coordinator.userWalletListViewModel)

2022-11-15 04:18 UTC, megakoko commented on Tangem/Modules/UserWalletList/CommonUserWalletListService.swift
> +    }
В PersistentStorage то же самое

2022-11-15 04:20 UTC, megakoko commented on Tangem/Modules/Onboarding/BaseModels/OnboardingViewModel.swift
> +            if index == (steps.count - 1) {
Все правильно, индекс с нуля

2022-11-15 04:51 UTC, Andoran90 commented on Tangem/Modules/Onboarding/Note/SingleCardOnboardingViewModel.swift
> -            fallthrough
для одновалентных карточек это пополнение, а сейчас получается, что после пополнения не показываются конфети, а сразу экран биометрии. Да и по логике думаю активация карточки заканчивается на пополнении, а не на биометрии, биометрия это уже настройка приложения, а не карточки. Вообще может лучше убрать биометрию как часть онбординга и показывать её модалкой?

2022-11-15 05:18 UTC, Andoran90 commented on Tangem/Modules/Main/MainCoordinator.swift
> +        pushedOnboardingCoordinator = coordinator
нет, т.к. это с главного экрана, он должен не направиться на главную, а попнуться на главную. т.е. destination должен быть `root`, но `dismissAction` и `popToRootAction` одинаковые, поэтому можно оставить вообще только `dismissAction` и в качестве `destination` указать `dismiss`

2022-11-15 05:34 UTC, megakoko commented on Tangem/Modules/UserWalletList/UserWalletListViewModel.swift
> +    }
Чтобы отдельно показывать, в двух секциях

2022-11-15 08:30 UTC, megakoko commented on Tangem/Modules/Onboarding/BaseModels/OnboardingViewModel.swift
> +            if saveUserWalletOnFinish {
Если мы сканируем карту со шторки то в рамках онбординга экран сохранения уже не показывается

2022-11-16 05:52 UTC, tureck1y commented on Tangem/App/Models/UserWallet/Implementations/GenericConfig.swift
> +            return .wallet([.createWallet] + _backupSteps + userWalletSavingSteps + [.success])
в backupSteps надо тоже добавить success шаг

2022-11-16 05:55 UTC, tureck1y commented on Tangem/App/Models/UserWallet/Implementations/GenericConfig.swift
> +            return .wallet([.createWallet] + _backupSteps + userWalletSavingSteps + [.success])
в дело конфиг тоже

2022-11-16 06:11 UTC, tureck1y reviewed
неактуальные комменты закрыл

2022-11-16 06:11 UTC, tureck1y commented on Tangem/Modules/Onboarding/BaseModels/OnboardingViewModel.swift
> +    }
весь этот код можно унести в сервис

2022-11-16 06:11 UTC, tureck1y commented on Tangem/Modules/Onboarding/Note/SingleCardOnboardingViewModel.swift
> -            fallthrough
сначала биометрия, потом пополнение, сделали так, логика конфетти не поменялась

2022-11-17 04:41 UTC, megakoko commented on Tangem/Modules/ScanCardSettings/ScanCardSettingsViewModel.swift
> +                cardModel.didScan() // TODO: refactor
Не знаю почему зеленым показывается, это Серегины изменения

<img width="1026" alt="Screenshot 2022-11-17 at 09 41 11" src="https://user-images.githubusercontent.com/12209839/202357294-82808b46-5601-4fc0-af10-6f1213a68bad.png">

2022-11-20 06:50 UTC, tureck1y commented on Tangem/App/Services/TotalBalanceProvider/TotalBalanceProvider.swift
> +            totalBalanceAnalyticsService?.sendFirstLoadBalanceEventForCard(
Надо аналитику выносить отсюда и подписываться на провайдер в другом месте

2022-11-20 06:50 UTC, tureck1y commented on Tangem/Modules/AppSettings/AppSettingsViewModel.swift
> +    init(coordinator: AppSettingsRoutable, userWallet: UserWallet) {
NP: лучше местами поменять

2022-11-20 06:50 UTC, tureck1y commented on Tangem/Modules/Onboarding/Twins/TwinsOnboardingViewModel.swift
> +    override func saveUserWalletIfNeeded() throws {
Всю новую логику можно поместить в самую базовую вью модель онбординга, она же одинаковые для всех типов карт, чего тут оверрайдить?

2022-11-20 07:08 UTC, megakoko commented on Tangem/Modules/Onboarding/Twins/TwinsOnboardingViewModel.swift
> +    override func saveUserWalletIfNeeded() throws {
Только у твинов надо удалять предыдущий userwallet из репозитория, из-за перетвинивания.

У воллетов логика другая, надо еще access code сохранять при сохранении карты.

2022-11-20 07:09 UTC, tureck1y commented on Tangem/Modules/Onboarding/Twins/TwinsOnboardingViewModel.swift
> +    override func saveUserWalletIfNeeded() throws {
ок

2022-11-21 12:38 UTC, megakoko commented on Tangem/App/Services/CardsRepository/CommonCardsRepository.swift
> +    private(set) var models = [CardViewModel]()
Объединил

2022-11-25 11:04 UTC, tureck1y approved these changes

2022-11-25 11:04 UTC, merged