IOS 2091 Optimism wrong request for rate
tangem/tangem-app-ios-old pull request #663
Opened 2022-09-06 21:42 UTC by gre4ixin

2022-09-07 02:59 UTC, tureck1y requested changes

2022-09-07 02:59 UTC, tureck1y commented on Tangem/Common/Extensions/Blockchain+.swift
> +            return Blockchain.optimism(testnet: testnet).codingKey
Нельзя тут опираться на codingKey

2022-09-07 08:11 UTC, gre4ixin commented on Tangem/Common/Extensions/Blockchain+.swift
> +            return Blockchain.optimism(testnet: testnet).codingKey
исправил на строку

2022-09-07 12:33 UTC, Balashov152 approved these changes

2022-09-12 10:58 UTC, tureck1y approved these changes

2022-09-13 06:21 UTC, megakoko approved these changes

2022-09-13 09:47 UTC, merged