IOS-1905 Amplitude events with category
tangem/tangem-app-ios-old pull request #730
Opened 2022-10-06 16:21 UTC by gre4ixin

2022-10-11 05:04 UTC, megakoko commented on Tangem/App/Services/Common/Analytics.swift
> +                let convertParams = params.reduce(into: [:]) { $0[$1.key.rawValue] = $1.value }
Тогда лучше convertedParams

2022-10-11 05:04 UTC, megakoko commented on Tangem/App/Services/Common/Analytics.swift
> +        case buttonScanCard = "Button-Scan Card"
Пробелы надо

2022-10-11 05:04 UTC, megakoko commented on Tangem/App/Services/Common/Analytics.swift
> +        case mainRefreshed = "Refreshed "
Лишний пробел

2022-10-11 05:04 UTC, megakoko commented on Tangem/App/Services/Common/Analytics.swift
> +        case buttonStartWalletConnectSession = "Button - Start Wallet Connect Session "
Лишний пробел

2022-10-11 05:04 UTC, megakoko commented on Tangem/App/Services/Common/Analytics.swift
> +        case buttonStartWalletConnectSession = "Button - Start Wallet Connect Session "
Посмотри сам где еще есть

2022-10-11 05:04 UTC, megakoko commented on Tangem/App/Services/Common/Analytics.swift
> +                return .introductionProcess
Лучше сделать 
```
case .a, 
.b,
.c 
```

2022-10-11 05:04 UTC, megakoko commented on Tangem/App/Services/TotalBalanceProvider/TotalBalanceProvider.swift
> +            if previousBalance == 0 {
Вложенный if

2022-10-11 05:04 UTC, megakoko commented on Tangem/App/Services/TotalBalanceProvider/TotalBalanceProvider.swift
> +    private func firstLoadBalanceForCard(tokenItemViewModels: [TokenItemViewModel], balance: Decimal) {
Функция должна быть названа действием, если она ничего не возвращает. "Первая загрузка баланс для карта" — не действие.

2022-10-11 05:04 UTC, megakoko commented on Tangem/App/Services/TotalBalanceProvider/TotalBalanceProvider.swift
> +    private func toppedUpCheck(tokenItemViewModels: [TokenItemViewModel], balance: Decimal) {
Что значит название "пополнено проверка"?

2022-10-11 05:04 UTC, megakoko commented on Tangem/App/Services/WalletConnectService/WalletConnect/WalletConnectService.swift
> +//        Analytics.log(.walletConnectInvalidRequest)
Нужно или нет?

2022-10-11 05:04 UTC, megakoko commented on Tangem/Modules/Main/MainViewModel.swift
> +    private var isFirstStart = true
Где-то используется эта переменная?

2022-10-11 05:04 UTC, megakoko commented on Tangem/Modules/Main/MainViewModel.swift
> +//        Analytics.log(.buttonExplore)
Нужно?

2022-10-11 05:04 UTC, megakoko commented on Tangem/Modules/Main/TotalSumBalance/TotalSumBalanceViewModel.swift
> +        self.isSingleCoinCard = isSingleCoinCard
Где-то используется эта штука?

2022-10-11 05:04 UTC, megakoko commented on Tangem/App/Services/Common/Analytics.swift
> +        case signedIn = "Signed in"
Проверь еще сам на грамматические ошибки новые текстовки и кейсы.

2022-10-11 07:00 UTC, tureck1y commented on Tangem/Modules/Main/TotalSumBalance/TotalSumBalanceViewModel.swift
> +        self.isSingleCoinCard = isSingleCoinCard
я проверил щас девелоп, я ее удалил, так что не нужно это тут

2022-10-11 07:19 UTC, tureck1y requested changes
Почему-то еще сабмодуль поменялся

2022-10-11 07:19 UTC, tureck1y commented on Tangem/App/Services/TotalBalanceProvider/TotalBalanceProvider.swift
> +    init(userWalletModel: UserWalletModel, userWalletAmountType: Amount.AmountType?, totalBalanceSupportData: TotalBalanceCardSupportInfo) {
Много кода, нужного для аналитики лежит в TotalBalanceProvider. Надо вынести куда-то в отдельный хелпер или в саму аналитику, чтобы не засорять основной функционал

2022-10-11 07:20 UTC, Balashov152 commented on Tangem/Modules/Welcome/Stories/StoriesViewModel.swift
>      private func move(forward: Bool) {
параметр `forward` нужен еще?

2022-10-11 13:14 UTC, gre4ixin commented on Tangem/Modules/Welcome/Stories/StoriesViewModel.swift
>      private func move(forward: Bool) {
в коде используется еще

2022-10-11 13:40 UTC, gre4ixin commented on Tangem/App/Services/Common/Analytics.swift
> +                let convertParams = params.reduce(into: [:]) { $0[$1.key.rawValue] = $1.value }
поправил

2022-10-11 13:40 UTC, gre4ixin commented on Tangem/App/Services/Common/Analytics.swift
> +        case buttonScanCard = "Button-Scan Card"
переделал немного, теперь категория внутри ивент

2022-10-11 13:40 UTC, gre4ixin commented on Tangem/App/Services/Common/Analytics.swift
> +        case mainRefreshed = "Refreshed "
убрал

2022-10-11 13:41 UTC, gre4ixin commented on Tangem/App/Services/Common/Analytics.swift
> +        case buttonStartWalletConnectSession = "Button - Start Wallet Connect Session "
тоже ушло

2022-10-11 13:41 UTC, gre4ixin commented on Tangem/App/Services/Common/Analytics.swift
> +                return .introductionProcess
категории убрал

2022-10-11 13:45 UTC, gre4ixin commented on Tangem/App/Services/TotalBalanceProvider/TotalBalanceProvider.swift
> +    private func toppedUpCheck(tokenItemViewModels: [TokenItemViewModel], balance: Decimal) {
поправил

2022-10-11 13:45 UTC, gre4ixin commented on Tangem/App/Services/TotalBalanceProvider/TotalBalanceProvider.swift
> +    private func firstLoadBalanceForCard(tokenItemViewModels: [TokenItemViewModel], balance: Decimal) {
поправил

2022-10-11 13:45 UTC, gre4ixin commented on Tangem/App/Services/TotalBalanceProvider/TotalBalanceProvider.swift
> +            if previousBalance == 0 {
поправил

2022-10-11 13:46 UTC, gre4ixin commented on Tangem/App/Services/WalletConnectService/WalletConnect/WalletConnectService.swift
> +//        Analytics.log(.walletConnectInvalidRequest)
убрал

2022-10-11 13:46 UTC, gre4ixin commented on Tangem/Modules/Main/MainViewModel.swift
> +    private var isFirstStart = true
убрал

2022-10-11 13:46 UTC, gre4ixin commented on Tangem/Modules/Main/MainViewModel.swift
> +    private var isFirstStart = true
убрал

2022-10-11 13:46 UTC, gre4ixin commented on Tangem/Modules/Main/MainViewModel.swift
> +//        Analytics.log(.buttonExplore)
убрал

2022-10-11 13:47 UTC, gre4ixin commented on Tangem/App/Services/TotalBalanceProvider/TotalBalanceProvider.swift
> +    init(userWalletModel: UserWalletModel, userWalletAmountType: Amount.AmountType?, totalBalanceSupportData: TotalBalanceCardSupportInfo) {
переложил в сервис

2022-10-11 13:47 UTC, gre4ixin commented on Tangem/App/Services/Common/Analytics.swift
> +        case signedIn = "Signed in"
проверил, исправил, Лесу предупредил

2022-10-11 13:47 UTC, gre4ixin commented on Tangem/Modules/Main/TotalSumBalance/TotalSumBalanceViewModel.swift
> +        self.isSingleCoinCard = isSingleCoinCard
убрал

2022-10-11 14:04 UTC, megakoko commented on Tangem/App/Services/Common/Analytics.swift
> +        case cardWasScanned = "[Main Screen] Card Was Scanned "
Лишний пробел

2022-10-11 14:04 UTC, megakoko commented on Tangem/Modules/Main/MainViewModel.swift
> +//        Analytics.log(.buttonExplore)
Эвент остался. Он не используется?

2022-10-11 14:07 UTC, gre4ixin commented on Tangem/App/Services/Common/Analytics.swift
> +        case cardWasScanned = "[Main Screen] Card Was Scanned "
убрал

2022-10-11 15:03 UTC, megakoko submitted a review, later dismissed

2022-10-11 15:04 UTC, megakoko commented on Tangem/Modules/Main/MainViewModel.swift
> +//        Analytics.log(.buttonExplore)
Нашли…

2022-10-12 06:45 UTC, Balashov152 commented
вызови ./bootstrap что бы форматен отработал

2022-10-12 06:46 UTC, tureck1y submitted a review, later dismissed

2022-10-12 06:50 UTC, Balashov152 commented on Tangem/App/Services/TotalBalanceProvider/TotalBalanceProvider.swift
> +        totalBalanceAnalyticsService = TotalBalanceAnalyticsService(totalBalanceCardSupportInfo: totalBalanceSupportData)
Зависимость лучше из вне передавать, что бы объект не знал как она создается, пришла и пришла

2022-10-12 06:50 UTC, Balashov152 commented on Tangem/App/Services/KeysManager/CommonKeysManager.swift
> +    var  appsFlyerDevKey: String {
Пробел лишний добавился

2022-10-12 07:35 UTC, gre4ixin commented on Tangem/App/Services/TotalBalanceProvider/TotalBalanceProvider.swift
> +        totalBalanceAnalyticsService = TotalBalanceAnalyticsService(totalBalanceCardSupportInfo: totalBalanceSupportData)
поправил

2022-10-12 07:35 UTC, gre4ixin commented on Tangem/App/Services/KeysManager/CommonKeysManager.swift
> +    var  appsFlyerDevKey: String {
убрал

2022-10-12 07:37 UTC, Balashov152 submitted a review, later dismissed

2022-10-12 07:48 UTC, Balashov152 approved these changes

2022-10-12 07:51 UTC, tureck1y approved these changes

2022-10-12 07:54 UTC, megakoko approved these changes

2022-10-12 07:54 UTC, merged