IOS-2287: Update UserWalletID for twin cards
tangem/tangem-app-ios-old pull request #811
Opened 2022-10-25 14:59 UTC by Andoran90

Для твинов UserWalletID будет создаваться из комбинации публичных ключей обоих кошельков. Добавил функцию объединения в утилиту, чтобы все в одном месте было.

2022-10-25 16:11 UTC, gre4ixin approved these changes, later dismissed

2022-10-26 03:24 UTC, Balashov152 submitted a review, later dismissed

2022-10-26 04:03 UTC, megakoko approved these changes, later dismissed

2022-10-26 04:03 UTC, megakoko commented on Tangem/App/Utilities/TwinCardsUtils.swift
> +                (walletPubKey + pairWalletPubKey))
Когда тернарный оператор разрастается до трех строк надо уже задумываться об if/else

2022-10-26 05:17 UTC, Andoran90 commented on Tangem/App/Utilities/TwinCardsUtils.swift
> +                (walletPubKey + pairWalletPubKey))
ну тогда уж guard красивше)

2022-10-26 05:17 UTC, tureck1y requested changes

2022-10-26 05:17 UTC, tureck1y commented on Tangem/App/Models/CardInfo.swift
> +    }
я хочу избавиться от cardInfo, лучше сюда ничего не добавлять

2022-10-26 05:17 UTC, tureck1y commented on Tangem/App/Utilities/TwinCardsUtils.swift
> +                (walletPubKey + pairWalletPubKey))
тут что-то не то, мы должны userWalletId считать из вин кошелька, а не суммировать ключи

2022-10-26 05:17 UTC, tureck1y commented on Tangem/App/Utilities/UserWalletIdGeneratorUtil.swift
> +enum UserWalletIdGeneratorUtil {
у меня уже есть такая тулза)

2022-10-26 05:17 UTC, tureck1y commented on Tangem/Modules/Onboarding/Wallet/WalletOnboardingViewModel.swift
> +        let repository = CommonTokenItemsRepository(key: card.userWalletId(walletData: nil).toHexString())
не то расширение, надо наше юзать

2022-10-26 05:18 UTC, tureck1y commented
> Для твинов UserWalletID будет создаваться из комбинации публичных ключей обоих кошельков. 
Откуда ты вообще это взял?))

2022-10-26 05:20 UTC, Andoran90 commented on Tangem/App/Models/CardInfo.swift
> +    }
тогда надо место где хранится walletData, чтобы достать инфу про твин пару. Куда вынесли это и когда будут эти правки?

2022-10-26 05:22 UTC, tureck1y commented on Tangem/App/Models/CardInfo.swift
> +    }
пока все, что непонятно куда складывать, собираем в cardViewModel

2022-10-26 05:24 UTC, Andoran90 commented on Tangem/App/Utilities/UserWalletIdGeneratorUtil.swift
> +enum UserWalletIdGeneratorUtil {
твин кошелек формируется в блокчеин сдк и туда передаются 2 ключа, там создается скрипт и выдается адрес, впоследствии, если я все правильно помню, ты можешь подписывать любым ключом транзакции и они будут валидны, но ты не создаешь кошелек из двух ключей.

А где твоя тулза для UserWalletId?

2022-10-26 05:38 UTC, megakoko commented on Tangem/App/Utilities/TwinCardsUtils.swift
> +                (walletPubKey + pairWalletPubKey))
У гарда семантика другая. Предполагаем условие, если не выполняется — выходим. Тут выходить не надо. Обычное ветвление —  if/else.

2022-10-26 06:34 UTC, tureck1y commented
Обсудили как делать, будем суммировать кошельки как точки

2022-10-26 11:53 UTC, tureck1y commented on Tangem/App/Utilities/TwinCardsUtils.swift
> +            let pairWalletPubKey = pairData.pairPublicKey
NP: я бы объединил

2022-10-26 11:53 UTC, tureck1y commented on Tangem/App/Models/CardInfo.swift
> +    }
забыл удалить

2022-10-26 11:53 UTC, tureck1y commented on Tangem/App/ViewModels/CardViewModel.swift
> -        let userTokenListManager = CommonUserTokenListManager(config: config, userWalletId: cardInfo.card.userWalletId)
лишнее изменение?

2022-10-26 11:53 UTC, tureck1y commented on Tangem/Common/Extensions/Card+.swift
> +    }
Давай все же сразу сделаем c книгами и чисто.
1)  key = (wallets.first?.publicKey ?? cardPublicKey)  - cardPublicKey выкидываем, его тут быть не должно
2) userWalletId это не свойство карты. Конфиг возвращает seedKey, который мы кидаем сюда UserWalletId(with: key).value
3) Реализация seedkey будет дефолтная, у теинов своя.

2022-10-26 13:43 UTC, tureck1y approved these changes

2022-10-26 13:49 UTC, Balashov152 approved these changes

2022-10-26 13:50 UTC, merged

2022-10-26 13:51 UTC, megakoko commented on Tangem/App/ViewModels/CardViewModel.swift
> +        guard userWalletModel == nil, let userWalletId = userWalletId else {
Без проверки на hasWallets не будет падения?