IOS-2085 Design review details view bugs
tangem/tangem-app-ios-old pull request #826
Opened 2022-10-27 05:43 UTC by Balashov152

- Переход в экране настроек от стандартного List, к ScrollView + LazyVStack
- Дизайн ревью не возможно было поправить без этого перехода, плюс убираем не предсказуемое поведение на разных iOS

2022-11-04 06:35 UTC, megakoko requested changes

2022-11-04 06:35 UTC, megakoko commented on Tangem/Common/UI/DefaultListViews/DefaultRowView/DefaultRowView.swift
> +            Button(action: { viewModel.action?() }) { content }
Не жалей переводов строк

2022-11-04 06:35 UTC, megakoko commented on Tangem/Common/UI/DefaultListViews/DefaultRowView/DefaultRowView.swift
> +        case let .text(string):
Надо let внутрь скобок перенести

2022-11-04 06:35 UTC, megakoko commented on Tangem/Common/UI/DefaultListViews/DefaultToggleRowView/DefaultToggleRowView.swift
> +                .disabled(!viewModel.isEnabled)
Давай сделаем isDisabled чтобы быть последовательными со SwiftUI и другими нашими местами

2022-11-04 06:35 UTC, megakoko commented on Tangem/Common/UI/GroupedScrollView/GroupedSection.swift
> +}
Может переименовать в GroupedSectionSeparatorStyle? Или внутрь GroupedSection перенести. Какое-то слишком общее название для глобальной области видимости

2022-11-04 06:35 UTC, megakoko commented on Tangem/Common/UI/GroupedScrollView/GroupedSection.swift
> +    @State private var separatorStyle: SeparatorStyle = .single
Можно убрать @State и сделать константными.

2022-11-04 06:35 UTC, megakoko commented on Tangem/Common/UI/GroupedScrollView/GroupedSection.swift
> +    }
Понимаю, что хочешь конструкторы на все случаи жизни, но давай хотя бы через convenience init запилим часть из них.

Нужен ли конструктор с `_ model: Model` или его можно совсем заменить тем, который опционал принимает?

2022-11-04 06:35 UTC, megakoko commented on Tangem/Common/UI/GroupedScrollView/GroupedSection.swift
> +                VStack(alignment: .leading, spacing: 12) {
spacing=12, получается в этих местах при нажатии ничего не будет происходить?

2022-11-04 06:35 UTC, megakoko commented on Tangem/Modules/AppSettings/AppSettingsViewModel.swift
> -            .store(in: &bag)
Тут без рефакторинга можно? Я в ветке с биометрией своего кода сюда уже добавил.

2022-11-04 06:35 UTC, megakoko commented on Tangem/Common/Extensions/Binding+.swift
> +        root: Root,
Может лучше не root, а object?

2022-11-04 06:35 UTC, megakoko commented on Tangem/Modules/AppSettings/AppSettingsViewModel.swift
> -            .store(in: &bag)
Ну или хотя бы с минимальными изменениями, чтобы новые модели завелись

2022-11-04 06:35 UTC, megakoko commented on Tangem/Modules/Details/DetailsView.swift
> +            socialNetworks
А как socialNetworks к низу страницы прилепает? Не увидел в коде

2022-11-04 06:35 UTC, megakoko commented on Tangem/Modules/Details/DetailsViewModel.swift
> +        } else {
Можно эту ветку опустить

2022-11-04 06:35 UTC, megakoko commented on Tangem/Modules/EnvironmentSetup/EnvironmentSetupViewModel.swift
> +            title: "isTestnet",
Давай сделаем "Use testnet"

2022-11-07 07:13 UTC, Balashov152 commented on Tangem/Common/UI/DefaultListViews/DefaultRowView/DefaultRowView.swift
> +        case let .text(string):
сделал, но кстати у swiftformat правило есть наоборот `let` выносить, что бы если параметров несколько, то `let` один был

2022-11-07 07:13 UTC, Balashov152 commented on Tangem/Common/UI/DefaultListViews/DefaultRowView/DefaultRowView.swift
> +            Button(action: { viewModel.action?() }) { content }
✅

2022-11-07 07:14 UTC, Balashov152 commented on Tangem/Common/UI/DefaultListViews/DefaultToggleRowView/DefaultToggleRowView.swift
> +                .disabled(!viewModel.isEnabled)
✅

2022-11-07 07:15 UTC, megakoko commented on Tangem/Common/UI/DefaultListViews/DefaultRowView/DefaultRowView.swift
> +        case let .text(string):
Можно будет вынести на обсуждение когда форматтером снова займемся, но как по мне — проще читать кейсы когда перед ними не стоит let. Просто глазами пробежался и все, они все на одном уровне. 

Вот if case let / guard case let — другое дело, там как-то удобнее вынести let наружу/

2022-11-07 07:17 UTC, megakoko commented on Tangem/Modules/Details/DetailsViewModel.swift
> +        } else {
Значение по-умолчанию все равно nil и вызывается этот код один раз

2022-11-07 07:19 UTC, Balashov152 commented on Tangem/Common/UI/GroupedScrollView/GroupedSection.swift
> +    @State private var separatorStyle: SeparatorStyle = .single
Хотел сделать изменяемыми снаружи через копирование view, но что то не вышло 
Убрал вообще ✅

2022-11-07 07:19 UTC, Balashov152 commented on Tangem/Common/UI/GroupedScrollView/GroupedSection.swift
> +}
Убрал внутрь GroupedSection ✅

2022-11-07 07:20 UTC, Balashov152 commented on Tangem/Common/UI/GroupedScrollView/GroupedSection.swift
> +    }
Убрал `_ model: Model`, оставил опционал, `convenience` же тоже самое, все равно все параметры должны быть) Оставил просто 2 инита

2022-11-07 07:21 UTC, Balashov152 commented on Tangem/Common/UI/GroupedScrollView/GroupedSection.swift
> +                VStack(alignment: .leading, spacing: 12) {
не выглядит критичным, все норм нажимается,  подумаю что можно сделать

2022-11-07 07:22 UTC, Balashov152 commented on Tangem/Modules/AppSettings/AppSettingsViewModel.swift
> -            .store(in: &bag)
без рефакторинга никак( меняется подход к построению view

Давай я может эту ветку в твою залью еще, перед литием в develop

2022-11-07 07:23 UTC, Balashov152 commented on Tangem/Common/Extensions/Binding+.swift
> +        root: Root,
делал по идеологии `assign keyPath: to root:`, могу поменять в принципе )

2022-11-07 07:23 UTC, Balashov152 commented on Tangem/Modules/Details/DetailsView.swift
> +            socialNetworks
`ZStack(alignment: .bottom)`
И они над списком )

2022-11-07 07:23 UTC, megakoko commented on Tangem/Common/UI/GroupedScrollView/GroupedSection.swift
> +                VStack(alignment: .leading, spacing: 12) {
Попробуй сделать спейсинг не 12, а 120, если нажатия не будут регистрироваться — надо исправить. Если все норм — то окей.

2022-11-07 07:24 UTC, Balashov152 commented on Tangem/Modules/Details/DetailsViewModel.swift
> +        } else {
надеюсь лишний раз не вылезет )

2022-11-07 07:25 UTC, Balashov152 commented on Tangem/Modules/EnvironmentSetup/EnvironmentSetupViewModel.swift
> +            title: "isTestnet",
✅

2022-11-07 07:25 UTC, megakoko commented on Tangem/Common/UI/GroupedScrollView/GroupedSection.swift
> +    }
convenience то же самое, да, но хотя бы реализация конструктора не будет копипастой, можно одно через другое вызвать

2022-11-07 07:25 UTC, megakoko commented on Tangem/Common/Extensions/Binding+.swift
> +        root: Root,
Тогда давай оставим

2022-11-07 07:26 UTC, Balashov152 commented on Tangem/Common/UI/DefaultListViews/DefaultRowView/DefaultRowView.swift
> +        case let .text(string):
Надо обсудить, запишу себе

2022-11-07 07:27 UTC, megakoko commented on Tangem/Modules/Details/DetailsView.swift
> +            socialNetworks
Так, а если будет много ячеек в таблице — оно не наложится друг на друга? Может лучше через vstack+spacer сделать?

2022-11-07 14:05 UTC, Balashov152 commented on Tangem/Modules/Details/DetailsView.swift
> +            socialNetworks
ZStack(alignment: .bottom) {} по логике как же как VStack { Spacer(); content } работает 
Так что все норм)

2022-11-07 14:16 UTC, megakoko commented on Tangem/Modules/AppSettings/AppSettingsViewModel.swift
> -            .store(in: &bag)
Ладно, я тогда залью аккуратно

2022-11-07 14:18 UTC, megakoko commented on Tangem/Common/UI/GroupedScrollView/GroupedSection.swift
> +                VStack(alignment: .leading, spacing: 12) {
Заменили на паддинг

2022-11-07 15:40 UTC, Balashov152 commented on Tangem/Common/UI/GroupedScrollView/GroupedSection.swift
> +                VStack(alignment: .leading, spacing: 12) {
Убрал вообще paddings и spacing в секции, сам контент решает свою область показа/нажатия

2022-11-08 10:59 UTC, megakoko approved these changes

2022-11-14 05:06 UTC, tureck1y approved these changes

2022-11-14 08:24 UTC, merged