IOS-2364 exchange view model
tangem/tangem-app-ios-old pull request #827
Opened 2022-10-27 07:21 UTC by gre4ixin

2022-11-01 13:58 UTC, Balashov152 commented on Tangem/Modules/Exchange/ExchangeItem.swift
> +    var id: UUID = UUID()
можно `let`

2022-11-01 13:58 UTC, Balashov152 commented on Tangem/Modules/Exchange/ExchangeItems.swift
> +    var id: UUID = UUID()
можно `let`

2022-11-01 13:58 UTC, ba1ashov commented on Tangem/Modules/Exchange/ExchangeViewModel.swift
> +    var prefetchedAvailableCoins: [CoinModel] = []
`private` ? Ну bag точно )

2022-11-01 14:04 UTC, gre4ixin commented on Tangem/Modules/Exchange/ExchangeItems.swift
> +    var id: UUID = UUID()
поправил

2022-11-01 14:05 UTC, gre4ixin commented on Tangem/Modules/Exchange/ExchangeItem.swift
> +    var id: UUID = UUID()
поправил

2022-11-01 14:06 UTC, megakoko requested changes

2022-11-01 14:06 UTC, megakoko commented on Tangem/App/Models/Coins/Entities/CoinsListRequestModel.swift
> +    let exchange: Bool?
Давай поменяем на exchangeable, exchange — это глагол, под булеву переменную не подходит

2022-11-01 14:06 UTC, megakoko commented on Tangem/Modules/Exchange/ExchangeCoordinator.swift
> +        exchangeViewModel = ExchangeViewModel(amountType: options.amountType, walletModel: options.walletModel, cardViewModel: options.cardViewModel, blockchainNetwork: options.blockchainNetwork)
Длинная строка

2022-11-01 14:06 UTC, megakoko commented on Tangem/Modules/Exchange/ExchangeItem.swift
> +    @Published var isLock: Bool = false
isLocked

2022-11-01 14:06 UTC, megakoko commented on Tangem/Modules/Exchange/ExchangeItem.swift
> +    private let exchangeFacade = ExchangeSdk.buildInchExchangeService(isDebug: false)
Тут тоже exchangeService надо?

2022-11-01 14:06 UTC, megakoko commented on Tangem/Modules/Exchange/ExchangeItem.swift
> +    private let isMainToken: Bool
Что значит главный токен?

2022-11-01 14:06 UTC, megakoko commented on Tangem/Modules/Exchange/ExchangeItem.swift
> +    private let exchangeFacade = ExchangeSdk.buildInchExchangeService(isDebug: false)
Пропустил 1 в названии — buildInchExchangeService

Можно для наглядности везде писать ...OneInch...

2022-11-01 14:06 UTC, megakoko commented on Tangem/Modules/Exchange/ExchangeItem.swift
> +        }
Лучше через `if case let .token = ` чтобы форс-анрап не торчал

2022-11-01 14:06 UTC, megakoko commented on Tangem/Modules/Exchange/ExchangeItem.swift
> +        self.isLock = false
Можно убрать, у нее есть значение по-умолчанию

2022-11-01 14:06 UTC, megakoko commented on Tangem/Modules/Exchange/ExchangeItem.swift
> +                }
Правильно понимаю, что тут отфильтровывается все кроме цифр? Точки/запятые не нужны?

2022-11-01 14:06 UTC, megakoko commented on Tangem/Modules/Exchange/ExchangeItem.swift
> +                let contractAddress: String = amountType.isToken ? amountType.token!.contractAddress : coinContractAddress
В таких случаях лучше делать early exit — если условие не выполняется то выходим из функции. Чтобы снижать градус вложенности.

2022-11-01 14:06 UTC, megakoko commented on Tangem/Modules/Exchange/ExchangeItem.swift
> +                case .success(let allowanceDTO):
От DTO вроде отказались? Если так, пройдись по всему МРу, посмотри тоже.

2022-11-01 14:06 UTC, megakoko commented on Tangem/Modules/Exchange/ExchangeItem.swift
> +                    }
Надо затолкать `??` в инициализацию, код проще будет

2022-11-01 14:06 UTC, megakoko commented on Tangem/Modules/Exchange/ExchangeItems.swift
> +    let toItem: ExchangeItem
Лучше sourceItem / destinationItem, может даже и без "item"

2022-11-01 14:06 UTC, megakoko commented on Tangem/Modules/Exchange/ExchangeView.swift
> +    }
Нужно?

2022-11-01 14:06 UTC, megakoko commented on Tangem/Modules/Exchange/ExchangeViewModel.swift
> +    @Injected(\.rateAppService) private var rateAppService: RateAppService
Не используется вроде

2022-11-01 14:06 UTC, megakoko commented on Tangem/Modules/Exchange/ExchangeViewModel.swift
> +    @Published private var swapInformation: SwapData?
`sendSwapTransaction(info: SwapData`

Где-то info, где-то information, где-то data. Надо бы к единому наименованию привести

2022-11-01 14:06 UTC, megakoko commented on Tangem/Modules/Exchange/ExchangeViewModel.swift
> +    var prefetchedAvailableCoins: [CoinModel] = []
Должны быть публичными?

2022-11-01 14:06 UTC, megakoko commented on Tangem/Modules/Exchange/ExchangeViewModel.swift
> +    private lazy var exchangeInteractor: ExchangeTxInteractor = ExchangeTxInteractor(walletModel: walletModel, card: card)
Тип переменной не обязательно ведь указывать?

2022-11-01 14:06 UTC, megakoko commented on Tangem/Modules/Exchange/ExchangeViewModel.swift
> +                    }.store(in: &bag)
Надо с красной строки

2022-11-01 14:06 UTC, megakoko commented on Tangem/Modules/Exchange/Utils/ExchangeState.swift
> +import Foundation
Пустой файл — нужен еще?

2022-11-01 14:06 UTC, megakoko commented on Tangem/Modules/Exchange/Utils/Exchange+Utils.swift
> +            return .bsc
Тут нет ошибки? У нас есть Blockchain.binance и Blockchain.bsc. Последний — это EVM сеть.

2022-11-01 14:06 UTC, megakoko commented on Tangem/Modules/Exchange/Utils/Exchange+Timer.swift
> +//  Exchange+Timer.swift
Давай тогда назовем ExchangeTimer как класс

2022-11-01 14:06 UTC, megakoko commented on Tangem/Modules/Exchange/Utils/Exchange+Timer.swift
> +                if timePassedSinceStart > 10 {
Лучше бы такие штуки выносить хотя бы в константные члены класса.

2022-11-01 14:06 UTC, megakoko commented on Tangem/Modules/Exchange/Utils/Exchange+Timer.swift
> +    func startTimer(callback: @escaping (State) -> ()) {
Надо completion как везде

2022-11-01 14:06 UTC, megakoko commented on Tangem/Modules/Exchange/Utils/Exchange+Timer.swift
> +                if timePassedSinceStart > 10 {
Тут кстати неравенство строгое должно быть?

2022-11-01 14:06 UTC, megakoko commented on Tangem/Modules/Exchange/Interactor/ExchangeInteractor.swift
> +    func sendApproveTransaction(info: ApprovedTransactionData) -> AnyPublisher<(), Error> {
sendApprove**d**Transaction?

2022-11-01 14:06 UTC, megakoko commented on Tangem/Modules/Exchange/Interactor/ExchangeInteractor.swift
> +        case loadFeeWasFail
failedToLoadFee

gasLoaderNotFind где-то используется? Если да, то надо failedToFindGasLoader

2022-11-01 14:27 UTC, gre4ixin commented on Tangem/Modules/Exchange/ExchangeItem.swift
> +    @Published var isLock: Bool = false
✅

2022-11-01 14:29 UTC, gre4ixin commented on Tangem/Modules/Exchange/ExchangeItem.swift
> +    private let exchangeFacade = ExchangeSdk.buildInchExchangeService(isDebug: false)
передал в зависимостях его

2022-11-01 14:30 UTC, gre4ixin commented on Tangem/Modules/Exchange/ExchangeItem.swift
> +    private let isMainToken: Bool
тот с которого мы пришли в обменник и который нельзя сменить

2022-11-01 14:44 UTC, gre4ixin commented on Tangem/Modules/Exchange/ExchangeItem.swift
> +        }
✅

2022-11-01 14:44 UTC, gre4ixin commented on Tangem/Modules/Exchange/ExchangeItem.swift
> +        self.isLock = false
✅

2022-11-01 14:56 UTC, gre4ixin commented on Tangem/Modules/Exchange/ExchangeItem.swift
> +                let contractAddress: String = amountType.isToken ? amountType.token!.contractAddress : coinContractAddress
✅

2022-11-01 14:58 UTC, gre4ixin commented on Tangem/Modules/Exchange/ExchangeItem.swift
> +                case .success(let allowanceDTO):
✅

2022-11-01 14:59 UTC, gre4ixin commented on Tangem/Modules/Exchange/ExchangeItem.swift
> +                    }
✅

2022-11-01 15:00 UTC, gre4ixin commented on Tangem/Modules/Exchange/ExchangeItems.swift
> +    let toItem: ExchangeItem
✅

2022-11-01 15:01 UTC, gre4ixin commented on Tangem/Modules/Exchange/ExchangeViewModel.swift
> +    @Injected(\.rateAppService) private var rateAppService: RateAppService
пока убрал, в будущих МР возможно пригодится

2022-11-01 15:02 UTC, gre4ixin commented on Tangem/Modules/Exchange/ExchangeViewModel.swift
> +    @Published private var swapInformation: SwapData?
✅

2022-11-01 15:03 UTC, gre4ixin commented on Tangem/Modules/Exchange/ExchangeViewModel.swift
> +    var prefetchedAvailableCoins: [CoinModel] = []
уже поправил

2022-11-01 15:05 UTC, gre4ixin commented on Tangem/Modules/Exchange/ExchangeViewModel.swift
> +    private lazy var exchangeInteractor: ExchangeTxInteractor = ExchangeTxInteractor(walletModel: walletModel, card: card)
убрал

2022-11-01 15:06 UTC, gre4ixin commented on Tangem/Modules/Exchange/ExchangeViewModel.swift
> +                    }.store(in: &bag)
у нас много где `guard let self` в одну строку, зачем переносить?

2022-11-01 15:06 UTC, gre4ixin commented on Tangem/Modules/Exchange/Utils/Exchange+Utils.swift
> +            return .bsc
да, поправил

2022-11-01 15:07 UTC, gre4ixin commented on Tangem/Modules/Exchange/Utils/Exchange+Timer.swift
> +//  Exchange+Timer.swift
✅

2022-11-01 15:09 UTC, gre4ixin commented on Tangem/Modules/Exchange/Utils/Exchange+Timer.swift
> +                if timePassedSinceStart > 10 {
✅

2022-11-01 15:09 UTC, gre4ixin commented on Tangem/Modules/Exchange/Utils/Exchange+Timer.swift
> +    func startTimer(callback: @escaping (State) -> ()) {
✅

2022-11-01 16:29 UTC, gre4ixin commented on Tangem/Modules/Exchange/Interactor/ExchangeInteractor.swift
> +        case loadFeeWasFail
✅

2022-11-01 16:30 UTC, gre4ixin commented on Tangem/Modules/Exchange/Interactor/ExchangeInteractor.swift
> +    func sendApproveTransaction(info: ApprovedTransactionData) -> AnyPublisher<(), Error> {
✅

2022-11-01 16:30 UTC, gre4ixin commented on Tangem/Modules/Exchange/Utils/ExchangeState.swift
> +import Foundation
✅

2022-11-01 16:31 UTC, gre4ixin commented on Tangem/Modules/Exchange/ExchangeCoordinator.swift
> +        exchangeViewModel = ExchangeViewModel(amountType: options.amountType, walletModel: options.walletModel, cardViewModel: options.cardViewModel, blockchainNetwork: options.blockchainNetwork)
✅

2022-11-01 16:42 UTC, gre4ixin commented on Tangem/Modules/Exchange/ExchangeItem.swift
> +    private let exchangeFacade = ExchangeSdk.buildInchExchangeService(isDebug: false)
✅

2022-11-01 16:43 UTC, gre4ixin commented on Tangem/Modules/Exchange/ExchangeView.swift
> +    }
Это часть модуля, когда перейду к верстке, то будет нужно, пока в дефолтном состоянии

2022-11-01 21:48 UTC, gre4ixin commented on Tangem/Modules/Exchange/ExchangeItem.swift
> +                }
✅

2022-11-02 04:54 UTC, megakoko commented on Podfile
> +  pod 'ExchangeSdk', :git => 'https://github.com/tangem/exchange-sdk-swift', :branch => 'develop'
Надо явно ссылаться на тег, иначе вроде кокоаподс с ума сходит

2022-11-02 04:54 UTC, megakoko commented on Tangem/Modules/Exchange/ExchangeViewModel.swift
> +                    }.store(in: &bag)
Не, я не про гард, а про store(in:)

2022-11-02 05:07 UTC, megakoko requested changes

2022-11-02 05:07 UTC, megakoko commented on Tangem/Modules/Exchange/ExchangeItem.swift
> +                }
Расскажи, что тут происходит, мне кажется можно упростить

2022-11-02 05:07 UTC, megakoko commented on Tangem/Modules/Exchange/ExchangeItem.swift
> +                    }
От decimalAllowance можно тоже тогда отказаться, сразу в allowance записывать

2022-11-02 05:07 UTC, megakoko commented on Tangem/Modules/Exchange/ExchangeViewModel.swift
> +    @Published private var swapInformation: SwapData?
Осталось прямо тут:

`@Published private var swapInformation: SwapData?`

2022-11-02 05:07 UTC, megakoko commented on Tangem/Modules/Exchange/Utils/Exchange+Utils.swift
> +        }
Нам удобно будет с таким дефолтным кейсом работать? Может nil возвращать?

2022-11-02 07:38 UTC, gre4ixin commented on Tangem/Modules/Exchange/Utils/Exchange+Utils.swift
> +        }
это лучше, чем `nil`, который надо еще анврапить, у нас не может открыться блокчейн, которого у нас нет тут, на севере идет синк токенов с 1инч, так что в обменник мы можем перейти только с токена, который доступен и у нас, и у 1инча

2022-11-02 09:05 UTC, megakoko commented on Tangem/Modules/Exchange/Utils/Exchange+Utils.swift
> +        }
А если сервер вдруг начнет возвращать новые токены для старых приложений, в которых новые токены не добавлены?

2022-11-02 09:10 UTC, gre4ixin commented on Tangem/Modules/Exchange/Utils/Exchange+Utils.swift
> +        }
он не сможет вернуть блокчейн, которого у нас нет, потому что мы переходим с экрана токена, если на главной у нас есть, значит все ок, если нет, значит и перехода нет

2022-11-02 09:15 UTC, megakoko commented on Tangem/Modules/Exchange/Utils/Exchange+Utils.swift
> +        }
Почему его у нас нет? Есть ethereumPoW, который добавлен в приложении, но не поддерживается обменником. Потом его стали поддерживать, бекенд начал его присылать в списке, и мы начали заходить в дефолтный кейс.

2022-11-02 09:53 UTC, gre4ixin commented on Tangem/Modules/Exchange/Utils/Exchange+Utils.swift
> +        }
эта проверка должна выполняться в любом случае не здесь, тут мы уже на экране и делаем запрос к 1инчу, тут уже поздно делать какие-то проверки на предмет блокчейна и прочего

2022-11-02 13:53 UTC, gre4ixin commented on Tangem/Modules/Exchange/ExchangeItem.swift
> +                    }
✅

2022-11-02 13:54 UTC, gre4ixin commented on Tangem/Modules/Exchange/ExchangeViewModel.swift
> +    @Published private var swapInformation: SwapData?
✅

2022-11-02 13:54 UTC, gre4ixin commented on Tangem/Modules/Exchange/ExchangeViewModel.swift
> +                    }.store(in: &bag)
✅

2022-11-02 13:54 UTC, gre4ixin commented on Podfile
> +  pod 'ExchangeSdk', :git => 'https://github.com/tangem/exchange-sdk-swift', :branch => 'develop'
✅

2022-11-02 14:03 UTC, megakoko commented on Tangem/App/Models/Coins/Entities/CoinsListRequestModel.swift
> +    let exchange: Bool?
active, но **is**Exchangeable 

Надо быть последовательными в именовании, хотя бы в рамках одной модели же

2022-11-02 14:10 UTC, megakoko commented on Tangem/Modules/Exchange/ExchangeItem.swift
> +                }
Сделали как в sendVM

2022-11-02 14:11 UTC, megakoko approved these changes

2022-11-02 15:32 UTC, Andoran90 requested changes

2022-11-02 15:32 UTC, Andoran90 commented on Tangem/Modules/Exchange/ExchangeViewModel.swift
> +    private let exchangeService = ExchangeSdk.buildOneInchExchangeService(isDebug: false)
зависимости лучше внедрять через инициализатор или же через Injected, когда мы все же разродимся тестами, нам не надо будет тут рефакторить

2022-11-02 15:32 UTC, Andoran90 commented on Tangem/Modules/Exchange/ExchangeItem.swift
> +    }
хм... такое чувство, будто эта логика не тут должна быть, как и `approveTxData()`...

2022-11-02 15:32 UTC, Andoran90 commented on Tangem/Modules/Exchange/ExchangeItem.swift
> +    func approveTxData() async throws -> ApprovedTransactionData {
думаю эта сущность не должна заниматься этими делами и логика относится к интерактору.

2022-11-02 15:32 UTC, Andoran90 commented on Tangem/Modules/Exchange/Interactor/ExchangeInteractor.swift
> +class ExchangeTxInteractor {
название файла отличается

2022-11-02 15:32 UTC, Andoran90 commented on Tangem/Modules/Exchange/Interactor/ExchangeInteractor.swift
> +                    throw ExchangeError.failedToLoadFee
думаю эта проверка лишняя. На сколько я помню блокчеин сдк проверяет чтобы было 3 фи и если нет - выбрасывает ошибку

2022-11-02 15:32 UTC, Andoran90 commented on Tangem/Modules/Exchange/Interactor/ExchangeInteractor.swift
> +                    throw ExchangeError.failedToBuildTx
может и без этого обойдемся? в общем-то нам из blockchains sdk будет приходить достаточно информации чтобы показать пользователю правильную ошибку, не хватает ли у него денег на фи или нов принципе мало денег и прочее.
Вдобавок код упростится, можно будет вообще убрать `do-catch` блок из-за того что это `tryMap`

2022-11-02 15:32 UTC, Andoran90 commented on Tangem/Modules/Exchange/Utils/ExchangeTimer.swift
> +    }
может его сделать через паблишеры, или в каком месте он будет использоваться? мне кажется на комбайне будет удобнее

2022-11-02 15:48 UTC, Andoran90 commented on Tangem/Modules/Exchange/ExchangeItem.swift
> +    private let coinContractAddress: String = "0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee"
это такая константа должна быть?

2022-11-02 15:49 UTC, gre4ixin commented on Tangem/Modules/Exchange/ExchangeItem.swift
> +    private let coinContractAddress: String = "0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee"
да, для 1инча это монета сети

2022-11-02 22:06 UTC, gre4ixin commented on Tangem/Modules/Exchange/Interactor/ExchangeInteractor.swift
> +class ExchangeTxInteractor {
✅

2022-11-02 22:07 UTC, gre4ixin commented on Tangem/Modules/Exchange/Interactor/ExchangeInteractor.swift
> +                    throw ExchangeError.failedToLoadFee
✅

2022-11-02 22:10 UTC, gre4ixin commented on Tangem/Modules/Exchange/Interactor/ExchangeInteractor.swift
> +                    throw ExchangeError.failedToBuildTx
✅

2022-11-02 22:24 UTC, gre4ixin commented on Tangem/Modules/Exchange/ExchangeItem.swift
> +    }
✅

2022-11-02 22:24 UTC, gre4ixin commented on Tangem/Modules/Exchange/ExchangeItem.swift
> +    func approveTxData() async throws -> ApprovedTransactionData {
✅

2022-11-02 22:24 UTC, gre4ixin commented on Tangem/Modules/Exchange/ExchangeViewModel.swift
> +    private let exchangeService = ExchangeSdk.buildOneInchExchangeService(isDebug: false)
✅

2022-11-02 22:35 UTC, gre4ixin commented on Tangem/Modules/Exchange/Utils/ExchangeTimer.swift
> +    }
✅

2022-11-03 04:46 UTC, Andoran90 commented
кажется обновление submodule лишнее

2022-11-03 04:55 UTC, Andoran90 requested changes

2022-11-03 04:55 UTC, Andoran90 commented on Tangem/Modules/Exchange/Interactor/ExchangeTxInteractor.swift
> +}
кажется забыл удалить их. Они же не используются нигде?

2022-11-03 06:49 UTC, gre4ixin commented on Tangem/Modules/Exchange/Interactor/ExchangeTxInteractor.swift
> +}
удалил и обновил конфиг

2022-11-03 06:52 UTC, Andoran90 approved these changes

2022-11-03 06:55 UTC, Balashov152 approved these changes

2022-11-03 06:55 UTC, merged