IOS-2438 Add MainButton
tangem/tangem-app-ios-old pull request #842
Opened 2022-10-31 05:44 UTC by Balashov152

2022-10-31 05:55 UTC, megakoko commented on Tangem/Common/UI/Buttons/MainButton.swift
> +    private var isDisabled: Bool { action == nil }
Давай лучше isDisabled сделаем отдельным параметром, у action уберем опциональность.

Для меня как пользователя совсем не очевидно что доступность кнопки надо регулировать таким образом.

2022-10-31 05:55 UTC, megakoko commented on Tangem/Common/UI/Buttons/MainButton.swift
> +    private var textView: some View {
NP Хочется переименовать чтобы не пересекалось с UITextView но не знаю стоит ли и на что вообще.

2022-10-31 07:08 UTC, Balashov152 commented on Tangem/Common/UI/Buttons/MainButton.swift
> +    private var isDisabled: Bool { action == nil }
Думал на счет этого, просто такой подход как будто решает гипотетическую проблему вызова action если кнопка должна быть задизейблена

Если все за доп параметр, то переделаю без проблем

2022-10-31 07:25 UTC, megakoko commented on Tangem/Common/UI/Buttons/MainButton.swift
> +    private var isDisabled: Bool { action == nil }
Никак экшн не вызовется если мы в SwiftUI передаем нужный параметр

2022-11-03 06:06 UTC, Balashov152 commented on Tangem/Common/UI/Buttons/MainButton.swift
> +    private var isDisabled: Bool { action == nil }
✅

2022-11-03 06:07 UTC, Balashov152 commented on Tangem/Common/UI/Buttons/MainButton.swift
> +    private var textView: some View {
Да наверно можно оставить)

2022-11-03 06:09 UTC, megakoko requested changes

2022-11-03 06:09 UTC, megakoko commented on Tangem/Common/UI/Buttons/MainButton.swift
> +        isDisabled: Bool = false
Надо поменять чтобы сокращенный синтаксис замыканий работал

2022-11-03 06:10 UTC, Balashov152 commented on Tangem/Common/UI/Buttons/MainButton.swift
> +        isDisabled: Bool = false
блин, точно, поправил

2022-11-03 06:11 UTC, megakoko approved these changes

2022-11-07 05:15 UTC, tureck1y approved these changes

2022-11-07 13:50 UTC, merged