IOS-2430: Referral loader
tangem/tangem-app-ios-old pull request #859
Opened 2022-11-02 14:17 UTC by Andoran90

- Add referral screen with navigation from settings screen
  - Add loader placeholders
  - add icons and localization

2022-11-02 15:32 UTC, gre4ixin commented on Tangem/Modules/Referral/ReferralViewModel.swift
> +
Пустая строка лишняя

2022-11-03 05:02 UTC, Andoran90 commented on Tangem/Modules/Referral/ReferralViewModel.swift
> +
done

2022-11-03 05:19 UTC, megakoko requested changes

2022-11-03 05:19 UTC, megakoko commented on Tangem/Modules/Details/DetailsCoordinatorView.swift
> +                ReferralCoordinatorView(coordinator: $0)
Не хватает единообразия. Где-то ReferralCoordinator, где-то ReferralProgramCoordinator

2022-11-03 05:19 UTC, megakoko commented on Tangem/Modules/Referral/ReferralView.swift
> +                Assets.referralDude
Надо переименовать в gentleman /s

2022-11-03 05:19 UTC, megakoko commented on Tangem/Modules/Referral/ReferralView.swift
> +    var isLoading: Bool { !viewModel.isLoading }
Почему так?

2022-11-03 05:19 UTC, megakoko commented on Tangem/Modules/Referral/ReferralView.swift
> +                Spacer()
Не жалей пустых строк

2022-11-03 05:19 UTC, megakoko commented on Tangem/Modules/Referral/ReferralView.swift
> +    var isLoading: Bool { !viewModel.isLoading }
Не могу найти использование переменной

2022-11-03 05:19 UTC, megakoko commented on Tangem/Modules/Referral/ReferralView.swift
> +struct ReferralView_Previews: PreviewProvider {
Ага, вот куда все пустые строки дел

2022-11-03 05:19 UTC, megakoko commented on Tangem/Modules/Referral/Views/ReferralLoaderView.swift
> +struct ReferralLoaderView: View {
Loading. Эта вьюха ничего ведь не загружает.

А лучше ReferralPlaceholderPointView, если эта вьюха отображает один из буллет-поинтов в списке.

2022-11-03 05:27 UTC, Andoran90 commented on Tangem/Modules/Referral/ReferralView.swift
> +                Assets.referralDude
а чем тебе чувак не нравится?))

2022-11-03 05:27 UTC, Andoran90 commented on Tangem/Modules/Referral/ReferralView.swift
> +    var isLoading: Bool { !viewModel.isLoading }
забыл почистить, сейчас почистию))

2022-11-03 05:30 UTC, megakoko commented on Tangem/Modules/Referral/ReferralView.swift
> +                Assets.referralDude
Сарказм же (:

2022-11-03 05:32 UTC, Andoran90 commented on Tangem/Modules/Referral/ReferralView.swift
> +                Assets.referralDude
ШОРД! 😅

2022-11-03 05:35 UTC, tureck1y reviewed
Все посмотрел, больше нечего добавить

2022-11-03 05:35 UTC, tureck1y commented on Tangem/Common/Localizations/de.lproj/Localizable.strings
> +"details_referral" = "Referral program";
я бы в ключ какой-нибудь идентификатор еще добавил. Title там или что это

2022-11-03 11:01 UTC, Andoran90 commented on Tangem/Common/Localizations/de.lproj/Localizable.strings
> +"details_referral" = "Referral program";
это в настройках название для кнопки и одновременно титульник навбар. добавлю title

2022-11-03 11:27 UTC, megakoko approved these changes

2022-11-03 13:12 UTC, tureck1y approved these changes

2022-11-03 15:58 UTC, gre4ixin approved these changes

2022-11-06 17:05 UTC, merged