IOS-2446: WC: app wrong work when go by deeplink
tangem/tangem-app-ios-old pull request #866
Opened 2022-11-03 10:57 UTC by Andoran90

Пришлось сделать сброс Welcome экрана через функцию, а не заменой на новый экземпляр, потому что были дополнительные баги среди которых:
* на 14.6 - появляется пустой навбар;
* onAppear в StoriesView не вызывается

Времени слишком много уже ушло на поиск другого решения.

  - Change validation logic in AppCoordinator to display alert
  - Add localization for alert
  - Update return to root logic

2022-11-03 11:15 UTC, megakoko commented on Tangem/Common/Localizations/ru.lproj/Localizable.strings
> +"wallet_connect_need_to_scan_card" = "Пожалуйста, отсканируйте карту и повторите ваш запрос.";
Надо убрать точку в конце, чтобы было как в английской версии.

Если предложение одно — точку не ставим. Два и более — ставим

2022-11-03 11:16 UTC, megakoko commented on Tangem/Common/Localizations/ru.lproj/Localizable.strings
> +"wallet_connect_need_to_scan_card" = "Пожалуйста, отсканируйте карту и повторите ваш запрос.";
Не забудь обновить табличку.

2022-11-03 11:25 UTC, megakoko commented on Tangem/App/Services/WalletConnectService/WalletConnect/WalletConnectService.swift
> +        }
Там внутри `self.sessions.remove(at: index)`, ничего не взорвется при итерации таким образом?

2022-11-03 11:25 UTC, megakoko commented on Tangem/AppCoordinator.swift
> +        let isContainWcSuffix = url.lastPathComponent == "wc"
containsWcSuffix, или даже hasWcSuffix

2022-11-03 11:27 UTC, Andoran90 commented on Tangem/App/Services/WalletConnectService/WalletConnect/WalletConnectService.swift
> +        }
хм... а ты прав

2022-11-03 12:23 UTC, Andoran90 commented on Tangem/App/Services/WalletConnectService/WalletConnect/WalletConnectService.swift
> +        }
updated

2022-11-03 12:23 UTC, Andoran90 commented on Tangem/AppCoordinator.swift
> +        let isContainWcSuffix = url.lastPathComponent == "wc"
done

2022-11-03 12:24 UTC, Andoran90 commented on Tangem/Common/Localizations/ru.lproj/Localizable.strings
> +"wallet_connect_need_to_scan_card" = "Пожалуйста, отсканируйте карту и повторите ваш запрос.";
обновлено

2022-11-03 12:24 UTC, megakoko commented on Tangem/App/Services/WalletConnectService/WalletConnect/WalletConnectService.swift
> +        save()
В disconnectSession был еще код кроме этого. Аналитика не будет вызываться

            Analytics.logWcEvent(.session(.disconnect, session.session.dAppInfo.peerMeta.url))
            Analytics.log(.sessionDisconnected)

2022-11-03 12:38 UTC, Andoran90 commented on Tangem/App/Services/WalletConnectService/WalletConnect/WalletConnectService.swift
> +        save()
вынес отключение сессии в функцию вместе с аналитикой

2022-11-03 12:52 UTC, tureck1y commented on Tangem/Modules/Welcome/WelcomeCoordinator.swift
> +    func reset() {
мне прям сильно не нравится

2022-11-03 12:56 UTC, Andoran90 commented on Tangem/Modules/Welcome/WelcomeCoordinator.swift
> +    func reset() {
ваше предложение?

2022-11-03 12:56 UTC, tureck1y requested changes
Давай все же поищем нормальное решение, с реестром очень криво выглядит( Количество добавляемых хаков просто зашкаливает. Зачем вообще нужен поп ту рут у  диплинка?

2022-11-03 12:56 UTC, tureck1y commented on Tangem/AppCoordinator.swift
> +            DispatchQueue.main.asyncAfter(deadline: .now() + 0.5, execute: {
обязательно прям из координатора Алерт показывать?

2022-11-03 12:56 UTC, tureck1y commented on Tangem/App/Services/WalletConnectService/WalletConnect/WalletConnectService.swift
> +    func terminateSessions() {
зачем делать дисконнект?

2022-11-03 13:04 UTC, tureck1y commented on Tangem/Modules/Welcome/WelcomeCoordinator.swift
> +    func reset() {
если есть активная карта, обрабатываем диплинк в walletConnectService
нет активной карты - показываем Алерт со сторисов, с просьбой отсканировать карту
никаких навигационных действий не предпринимаем

2022-11-03 13:18 UTC, Andoran90 commented on Tangem/App/Services/WalletConnectService/WalletConnect/WalletConnectService.swift
> +    func terminateSessions() {
потому что это создает баг:
ты нажал сканировать карточку и отменил сканирование, у тебя сессии сохранились и в WC сохранилась вью модель карты, в итоге, ты можешь из dApp отправлять сообщения, а в приложении у тебя будут висеть сессии и принимать команды и показывать Алерты на Welcome скрине

2022-11-03 13:21 UTC, tureck1y commented on Tangem/App/Services/WalletConnectService/WalletConnect/WalletConnectService.swift
> +    func terminateSessions() {
если ты отменил сканирование, ничего у тебя не сохранится

2022-11-03 13:22 UTC, Andoran90 commented on Tangem/App/Services/WalletConnectService/WalletConnect/WalletConnectService.swift
> +    func terminateSessions() {
все сохраняется, если у тебя уже была отсканирована карточка и ты нажал на главной: скан

2022-11-03 13:23 UTC, Andoran90 commented on Tangem/App/Services/WalletConnectService/WalletConnect/WalletConnectService.swift
> +    func terminateSessions() {
вернее, ничего не чистится

2022-11-03 13:24 UTC, Andoran90 commented on Tangem/App/Services/WalletConnectService/WalletConnect/WalletConnectService.swift
> +    func terminateSessions() {
а я добавил чтобы чистился WC: хочешь работать с другой картой - работай, но WC надо снова поднимать. А то в алерте ничего не указывает какой картой надо подписывать

2022-11-03 16:22 UTC, Andoran90 commented
Логику popToRoot убрали, т.к. она ломала сторисы и не особо нужна была.
Зафиксил баг с удаляющимися сессиями WC для разных карточек

2022-11-03 16:41 UTC, gre4ixin approved these changes

2022-11-03 16:41 UTC, gre4ixin approved these changes

2022-11-03 16:41 UTC, gre4ixin approved these changes

2022-11-03 16:41 UTC, gre4ixin approved these changes

2022-11-03 16:49 UTC, tureck1y requested changes

2022-11-03 16:49 UTC, tureck1y commented on Tangem/App/Services/WalletConnectService/WalletConnect/WalletConnectStorage.swift
> +protocol WalletConnectStorage {
рефакторинг в багофиксе быть не должно

2022-11-03 16:49 UTC, tureck1y commented on Tangem/AppCoordinator.swift
> +            DispatchQueue.main.asyncAfter(deadline: .now() + 0.5, execute: {
1) Этот метод стало читать еще сложнее из-за большого количества условий и ветвлений. 
2) Надо будет это все ПОТОМ унести  из координатора куда-то в wc

2022-11-03 16:50 UTC, Andoran90 commented on Tangem/App/Services/WalletConnectService/WalletConnect/WalletConnectStorage.swift
> +protocol WalletConnectStorage {
это не рефакторинг. Рефакторинг подразумевает сохранение функционала, это полноценный фикс, который предусматривает совсем иную логику

2022-11-03 16:53 UTC, Andoran90 commented on Tangem/AppCoordinator.swift
> +            DispatchQueue.main.asyncAfter(deadline: .now() + 0.5, execute: {
1. Согласен, но взаимодействие с WC сервисом итак сложное, да ещё он может и не существовать в этот момент.
2. унести получится только после изменения логики работы WC сервиса

2022-11-07 06:14 UTC, Andoran90 commented on Tangem/AppCoordinator.swift
> +            DispatchQueue.main.asyncAfter(deadline: .now() + 0.5, execute: {
обновил

2022-11-07 06:15 UTC, Andoran90 commented on Tangem/App/Services/WalletConnectService/WalletConnect/WalletConnectStorage.swift
> +protocol WalletConnectStorage {
обновил

2022-11-07 12:40 UTC, tureck1y approved these changes
Идеально!

2022-11-07 12:44 UTC, merged