IOS-2364
tangem/tangem-app-ios-old pull request #877
Opened 2022-11-09 10:14 UTC by gre4ixin

2022-11-09 10:48 UTC, tureck1y commented
Добавь пожалуйста название у пр и желательно краткое описание. Название должно быть всегда обязательно, описание уже по ситуации

2022-11-09 16:08 UTC, Andoran90 requested changes

2022-11-09 16:08 UTC, Andoran90 commented on Tangem/Modules/Exchange/ExchangeCoordinator.swift
> +                                                                                                 signer: options.signer))
мне однозначно не нравится эта функция, слишком много всего делает координатор. По сути он должен осуществлять только создание вью модели и навигацию, а тут ему приходится очень много всего знать. В идеале даже создание вью модели надо вынести за пределы координатора, в фабрику, но для такого подхода надо менять во всем приложении подход. Так что тут максимум что должно быть: создание вью модели и только её

2022-11-09 16:08 UTC, Andoran90 commented on Tangem/Modules/Exchange/ExchangeCurrency.swift
> +        }
зачем фабрика выбрасывает ошибку? и почему если вылетела ошибка все должно самоуничтожаться?

2022-11-09 16:08 UTC, Andoran90 commented on Tangem/Modules/Exchange/ExchangeCurrency.swift
> +        }
то же самое что и с предыдущей фабрикой.

2022-11-09 16:08 UTC, Andoran90 commented on Tangem/Modules/Exchange/ExchangeManager.swift
> +    var blockchainNetwork: BlockchainNetwork { get }
а зачем это свойство? думаю его можно передавать в инициализатор ExchangeOneInchFacade. это значение сейчас зависит от WalletModel, а WalletModel не меняется на экране свапалки

2022-11-09 16:08 UTC, Andoran90 commented on Tangem/Modules/Exchange/ExchangeManager.swift
> +}
мне совсем не нравится что WalletModel продолжает расширяться. Думаю тут лучше сделать класс `WalletManagerAdapter`, который будет реализовывать `ExchangeManager` и будет сам адаптировать менеджер для работы с сервисом

2022-11-09 16:08 UTC, Andoran90 commented on Tangem/Modules/Exchange/ExchangeViewModel.swift
> +                _ = try await exchangeFacade.sendSwapTransaction(destinationAddress: swapDataModel.destinationAddress,
а зачем тут `_ =`? функция `sendSwapTransaction` ничего не возвращает же

2022-11-09 16:08 UTC, Andoran90 commented on Tangem/Modules/Exchange/ExchangeViewModel.swift
> +                _ = try await exchangeFacade.submitPermissionForToken(destinationAddress: approveData.to,
то же самое что и с `onSwap`

2022-11-09 16:08 UTC, Andoran90 commented on Tangem/Modules/Exchange/ExchangeCoordinator.swift
> +                                                                                                 signer: options.signer))
думаю тут стоит сделать фабрику, которая будет создавать зависимости, но это стоит обсудить

2022-11-09 16:08 UTC, Andoran90 commented on Tangem/Modules/Exchange/ExchangeViewModel.swift
> +        }
вообще сейчас нет никакой логики по отображению, непонятно зачем отправлять `objectWillChange`, думаю всю UI логику лучше делать вместе с UI, при обновлении `@Published` переменной все должно отрабатываться нормально

2022-11-10 07:18 UTC, Andoran90 requested changes

2022-11-10 07:18 UTC, Andoran90 commented on Tangem/Modules/Exchange/ExchangeItem.swift
>  class ExchangeItem: Identifiable {
стоит разделить эту модель на две (вью модель и элемент обмена), потому что сейчас это и модель, которая будет нужна вьюхам для отображения и модель, которая хранит в себе информацию для сервиса, а вью модель будет обновляться из `ExchangeViewModel`

2022-11-10 07:18 UTC, Andoran90 commented on Tangem/Modules/Exchange/ExchangeItem.swift
> +    }
а почему бы не сделать allowance не приватной? все равно это значение может изменяться в любой момент, через эту функцию, думаю нам понадобится возможность отображать где-то максимально допустимую отправку.

2022-11-10 07:18 UTC, Andoran90 commented on Tangem/Modules/Exchange/ExchangeViewModel.swift
>  import BlockchainSdk
пока что BlockchainSdk можно отсюда выкинуть, думаю это вообще было бы хорошо, чтобы эта вью модель не знала толком ничего про блокчеин сдк.

2022-11-10 07:18 UTC, Andoran90 commented on Tangem/Modules/Exchange/ExchangeViewModel.swift
>  import ExchangeSdk
скорее всего, тут будет использоваться из ExchangeSdk только ошибки, поэтому стоит заменить на `import enum ExchangeSdk.ExchangeInchError`

2022-11-10 07:18 UTC, Andoran90 commented on Tangem/Modules/Exchange/ExchangeViewModel.swift
> +    @Published var outputAmountText: String = ""
а в свапалке можно вводить информацию в любое поле? например, я хочу получить 1к новой монеты и мне интересно сколько это будет стоит мне в текущей.

2022-11-10 07:18 UTC, Andoran90 commented on Tangem/Modules/Exchange/ExchangeViewModel.swift
>      }
тут и в последующих тасках захватывается в ссылка на self, могут возникнуть утечки памяти

2022-11-10 07:18 UTC, Andoran90 commented on Tangem/Modules/Exchange/ExchangeViewModel.swift
>              }
там чуть выше код, который можно обновить))

``` swift
.sink { completion in
    switch completion {
    ....
    }
}...
```
на
``` swift
.sink { 
    if case .failure(let error) = $0 {
         print(error.localizedDescription)
    }
}...
```

2022-11-10 07:18 UTC, Andoran90 commented on Tangem/Modules/Exchange/ExchangeViewModel.swift
>                  self?.onChangeInputAmount()
может стоит выходить из кложуры, если у нас пустое значение? а то получается дублирующая логика и слишком много апдейтов будет, повторно будут пытаться отмениться таймер и прочее

2022-11-10 07:18 UTC, Andoran90 commented on Tangem/Modules/Exchange/Facade/ExchangeOneInchFacade.swift
> +        }
бессмысленный кусок, с учетом того, что функция может выбрасывать ошибку. Пусть выбрасывает, нет смысла её отлавливать

2022-11-10 07:18 UTC, Andoran90 commented on Tangem/Modules/Exchange/Facade/ExchangeOneInchFacade.swift
> +            let gasValue = Decimal(string: gas) ?? 0 * gasPrice / exchangeManager.blockchainNetwork.blockchain.decimalValue
вообще, мне кажется `blockchainNetwork` можно сейчас передавать в инициализатор этого сервиса, т.к. он сейчас неизменен и убрать его из протокола `ExchangeManager`

2022-11-10 07:18 UTC, Andoran90 commented on Tangem/Modules/Exchange/Facade/ExchangeOneInchFacade.swift
> +        }
это тоже не имеет смысла, убери все бесполезные блоки `do-catch`

2022-11-10 07:18 UTC, Andoran90 commented on Tangem/Modules/Exchange/Facade/ExchangeOneInchFacade.swift
> +                                              toTokenAddress: swapData.toToken.address)
думаю можно это убрать в инициализатор `ExchangeSwapDataModel`, который на вход принимает `SwapData`

2022-11-10 07:18 UTC, Andoran90 commented on Tangem/Modules/Exchange/Facade/ExchangeOneInchFacade.swift
> +    }
как-то странно получается, а почему тут не вылетает ошибка, а в остальных вылетает? можно точно так же выкидывать ошибку, а не печатать в консоль или как?

2022-11-10 07:18 UTC, Andoran90 commented on Tangem/Modules/Exchange/Facade/ExchangeOneInchFacade.swift
> +                                                  to: approveTxData.to,
честно говоря, не очень мне нравятся такие названия `to`, в коде потом выглядят стремно, в некоторых местах это необходимость (например АПИшка такая и с этим ничего не поделаешь), но думаю все же надо избегать такого

2022-11-10 07:18 UTC, Andoran90 commented on Tangem/Modules/Exchange/Factory/ExchangeFactory.swift
> +    }
а почему `Router`? гораздо лучше `FactoryType`, особенно учитывая, что своего рода роутеры у нас есть в приложении.
И мне все же не нравится название Facade)

2022-11-10 07:18 UTC, Andoran90 commented on Tangem/Modules/Exchange/Factory/ExchangeTokensFactory.swift
> +            }
я за то чтобы не хардкодить эту информацию, тем более мы всю эту инфу получаем с нашей апишки, это лишняя логика, которая вдобавок не зависит от нас и привязана к нашим билдам, которые должны проходить ревью.

2022-11-10 07:18 UTC, Andoran90 commented on Tangem/Modules/Exchange/ExchangeViewModel.swift
> +    init(currency: ExchangeCurrency, exchangeFacade: ExchangeFacade) {
стоит подумать вообще на счет `ExchangeCurrency`, может имеет смысл сделать это сущностью по всему приложению и отказаться от `BlockchainSdk.Amount` совсем. Мне пока что не очень нравится как выглядит `ExchangeCurrency`, но пока нет предложений как переделать её. Посмотрим что ребята скажут на этот счет и что по итогу рефакторинга скажут Андрей и Саша

2022-11-10 09:26 UTC, gre4ixin commented on Tangem/Modules/Exchange/Factory/ExchangeFactory.swift
> +    }
просто обменники по типу 1inch роутерами называются, потому что объединяют в себе кучу других обменников, а сами являются просто посредниками, поэтому тут использовал роутер, для выбора конкретного

2022-11-10 14:20 UTC, Andoran90 reviewed
В целом вроде стало лучше понятнее, не ответил на счет можно ли вводить инфу в любое поле или нет, ну и мне не нравятся куча констант в `ExchangeTokensFactory`, думаю от неё можно избавиться или же заменить на сервис, который будет:
1. подтягивать все токены, которые можно поменять в этой сети
2. генерировать дефектный токен для этой сети

2022-11-11 09:30 UTC, ba1ashov commented on Tangem/Common/Extensions/AnyPublisher+.swift
> +            var cancellabel: AnyCancellable?
cancellabel -> cancellable

2022-11-11 09:30 UTC, ba1ashov commented on Tangem/Modules/Exchange/ExchangeCurrency.swift
> +        case token(blockchainNetwork: BlockchainNetwork, contractAddress: String)
Может чуть сократить ?

`
case coin(_ network: BlockchainNetwork),
case token(_ network: BlockchainNetwork, address: String)
`

2022-11-11 09:30 UTC, ba1ashov commented on Tangem/Modules/Exchange/ExchangeManager.swift
> +                           sourceAddress: String?, changeAddress: String?) throws -> Transaction
Давай может перенесем, что бы строчка не такой длинной была

2022-11-11 09:30 UTC, ba1ashov commented on Tangem/Modules/Exchange/ExchangeViewModel.swift
> +        items = ExchangeItems(sourceItem: sourceItem, destinationItem: destinationItem)
Я бы переставил exchangeFacade первым в init, так как с ним первая операция
И `ExchangeItem` после `:` лишний в `let destinationItem: ExchangeItem = ExchangeItem`

Что бы красиво было)

2022-11-11 09:30 UTC, ba1ashov commented on Tangem/Modules/Exchange/ExchangeViewModel.swift
> +            items = ExchangeItems(sourceItem: items.destinationItem, destinationItem: items.sourceItem)
А надо ли опять пересоздавать `items`, они же в init уже созданы?

2022-11-11 09:30 UTC, Balashov152 commented on Tangem/Modules/Exchange/ExchangeViewModel.swift
> +                // TODO: -
Для TODO может задачу оставить? или хотя бы описать что делать будем

2022-11-11 09:30 UTC, Balashov152 commented on Tangem/Modules/Exchange/Factory/ExchangeViewModelFactory.swift
> +            let contractAddress = amountType.token!.contractAddress
может проверить amountType.token поверить через `guard`, что бы не было такого кол-во force_unwrap

2022-11-11 09:30 UTC, Balashov152 commented on Tangem/Modules/Exchange/Models/ExchangeSwapDataModel.swift
> +    ) {
со скобками `()` надо одинаково. либо все перенести, либо оставлять на той же строке

2022-11-11 09:30 UTC, Balashov152 commented on Tangem/Modules/Exchange/WalletModelAdapter.swift
> +    }
`private` ? Лучше модификаторов, что бы кто не дергал что хочет, чисто с доступным методами работали

2022-11-11 11:43 UTC, megakoko commented on Tangem/Modules/Exchange/Factory/ExchangeViewModelFactory.swift
> +            let contractAddress = amountType.token!.contractAddress
У .token есть ассоциированное значение типа Token

2022-11-11 13:23 UTC, gre4ixin commented on Tangem/Common/Extensions/AnyPublisher+.swift
> +            var cancellabel: AnyCancellable?
✅

2022-11-11 13:24 UTC, gre4ixin commented on Tangem/Modules/Exchange/ExchangeCurrency.swift
> +        case token(blockchainNetwork: BlockchainNetwork, contractAddress: String)
лучше оставить blockchainNetwork мне кажется, но убрать название параметра при создании сделал ✅

2022-11-11 13:24 UTC, gre4ixin commented on Tangem/Modules/Exchange/ExchangeViewModel.swift
> +        items = ExchangeItems(sourceItem: sourceItem, destinationItem: destinationItem)
✅

2022-11-11 13:24 UTC, gre4ixin commented on Tangem/Modules/Exchange/ExchangeViewModel.swift
> +                // TODO: -
✅

2022-11-11 13:24 UTC, gre4ixin commented on Tangem/Modules/Exchange/Models/ExchangeSwapDataModel.swift
> +    ) {
✅

2022-11-11 13:24 UTC, gre4ixin commented on Tangem/Modules/Exchange/WalletModelAdapter.swift
> +    }
✅

2022-11-13 10:48 UTC, lazutkin-andrey commented on Tangem/Modules/Exchange/ExchangeItem.swift
> +    let isLockedForChange: Bool
```suggestion
    let isLocked: Bool
```

2022-11-13 17:48 UTC, lazutkin-andrey commented on Tangem/Modules/Exchange/Factory/ExchangeTokensFactory.swift
> +                                symbol: symbol,
А зачем этот хардкод?

2022-11-13 17:49 UTC, lazutkin-andrey commented on Tangem/Modules/Exchange/Factory/ExchangeTokensFactory.swift
> +                                symbol: symbol,
У нас есть сервер, который хранит все данные про токены, можно просто по ID загрузить нужный и все.

2022-11-13 17:52 UTC, lazutkin-andrey commented on Tangem/Modules/Exchange/Facade/ExchangeFacade.swift
> +protocol ExchangeFacade {
Давайте назовем ExchangeService, если я правильно понимаю, что это

2022-11-13 17:54 UTC, lazutkin-andrey commented on Tangem/Modules/Exchange/ExchangeCurrency.swift
> +struct ExchangeCurrency {
Вот эту штуку нужно сделать общей для всего приложения. Просто Currency.

2022-11-13 17:56 UTC, lazutkin-andrey commented on Tangem/Modules/Exchange/ExchangeCurrency.swift
> +struct ExchangeCurrency {
Это именно то, что мы подгружаем с сервера, когда синхронизируем монеты пользователя. Это именно то, что мы показываем на главном экране. Можно подумать, как это использовать на экране Manage Tokens.

2022-11-13 17:58 UTC, lazutkin-andrey commented on Tangem/Modules/Exchange/ExchangeCurrency.swift
> +    }
Да что же за желание то такое этот дерьмовый класс `Amount` затащить сюда. Нужно сделать абстракцию, на подпись и получения комиссии, чтобы этого класса в этом модуле не было. Мы от него избавимся скоро вообще везде.

2022-11-13 18:01 UTC, lazutkin-andrey commented on Tangem/Modules/Exchange/ExchangeCurrency.swift
> +}
Плохо. Статическая функция в extension, которая вызывает фабрику с хардкодом. А надо будет другие монеты использовать, будешь сюда новые и новые данные хардкодить?

2022-11-13 18:02 UTC, lazutkin-andrey commented on Tangem/Modules/Exchange/ExchangeCurrency.swift
> +        }
Мне кажется это должно быть в самой валюте. Можно обсудить. @tureck1y @Balashov152

2022-11-13 18:04 UTC, lazutkin-andrey commented on Tangem/Modules/Exchange/ExchangeCurrency.swift
> +        case token(_ blockchainNetwork: BlockchainNetwork, contractAddress: String)
Стоит ли отличать токен от монеты с помощью енума? @tureck1y @Balashov152 
Не зря же 1inch использует специальный адрес контракта для монет. Может оставить это BlockchainSDK?

2022-11-13 18:06 UTC, lazutkin-andrey commented on Tangem/Modules/Exchange/ExchangeItem.swift
> +    }
Почему нельзя через Currency ходить? Зачем дублировать?

2022-11-15 08:19 UTC, lazutkin-andrey commented on Tangem/Modules/Exchange/ExchangeManager.swift
> +protocol ExchangeManager {
Название не отражает сути

2022-11-15 08:19 UTC, lazutkin-andrey commented on Tangem/Modules/Exchange/ExchangeManager.swift
> +    var walletAddress: String { get }
Зачем тут адрес?

2022-11-15 08:19 UTC, lazutkin-andrey commented on Tangem/Modules/Exchange/ExchangeViewModel.swift
> +    @Published private(set) var outputAmountText: String = ""
sendAmout и receiveAmount?
Второе после нельзя ввести?

2022-11-15 08:19 UTC, lazutkin-andrey commented on Tangem/Modules/Exchange/Facade/ExchangeFacade.swift
> +                             txData: Data,
Что такое txData?

2022-11-15 08:19 UTC, lazutkin-andrey commented on Tangem/Modules/Exchange/Factory/ExchangeFacadeFactory.swift
> +class ExchangeFacadeFactory {
YAGNI

2022-11-15 08:19 UTC, lazutkin-andrey commented on Tangem/Modules/Exchange/Factory/ExchangeTokensFactory.swift
> +class ExchangeTokensFactory {
Я думаю не нужен хардкод, все есть на серваке.

2022-11-15 08:19 UTC, lazutkin-andrey commented on Tangem/Modules/Exchange/Factory/ExchangeTokensFactory.swift
> +    func createCoin(for blockchainNetwork: BlockchainNetwork) -> ExchangeCurrency {
Не жалко было времени делать логику, которая уже есть в приложении и уже работает через сервер?

2022-11-15 08:19 UTC, lazutkin-andrey commented on Tangem/Modules/Exchange/Factory/ExchangeViewModelFactory.swift
> +class ExchangeViewModelFactory {
Лишний класс, инициализация вынесена, а по факту, та же самая логика будет нужна для смены src монеты.

2022-11-15 08:19 UTC, lazutkin-andrey commented on Tangem/Modules/Exchange/ExchangeViewModel.swift
> +    convenience init(exchangeFacade: ExchangeFacade, blockchainNetwork: BlockchainNetwork) {
Тут похоже есть недопонимание в логике работы. Выбрать можно любую валюту в любой сети. Зачем пересевать сеть на конструктор?

2022-11-16 08:54 UTC, Balashov152 commented
Создал либу TangemExchange
перенес туда спи слой и DTO из exchangeSDK, по этому столько добавлено строк

Вынес логику в ExchangeManager у которого есть BlockchainNetworkProvider(для общения с сетью)
теперь ExchangeProvider интерфес для отправки всех запросов 

Надо еще по неймингами пробежаться, не думаю что все норм называться

2022-11-18 09:00 UTC, Balashov152 commented
Закрою, так ка комменты не актуальны

2022-11-18 09:00 UTC, closed without merging