Feature/ios 2428 layout referral screen
tangem/tangem-app-ios-old pull request #882
Opened 2022-11-10 12:27 UTC by Andoran90

Сделал верстку экранов для пользователя, который участвует и не участвует в реферальной программе. Пока сделал моковые данные, чтобы можно было посмотреть все ли правильно отображается, впоследствии думаю облагородить как-нибудь это данные, чтобы можно было не обращаясь к серваку смотреть разные стейты. Если что, на скринах старая текстовка "Invite your friends to Tangem", новая "Refer your friends to Tangem"

<img src="https://user-images.githubusercontent.com/24321494/201089710-fa8f0a55-77b4-4645-a010-094a3fe07d2f.png" alt="User is referral" width="300">
<img src="https://user-images.githubusercontent.com/24321494/201089734-b56d358e-f812-4ca9-ae0a-832b0675a101.png" width="300">
<img src="https://user-images.githubusercontent.com/24321494/201089752-de63c3f8-a824-409b-8976-4e8d7236686d.png" width="300">
<img src="https://user-images.githubusercontent.com/24321494/201089778-4ae12259-9977-452e-b468-6351c9bab539.png" width="300">

2022-11-10 12:45 UTC, megakoko commented
У чувака не должно быть градиента снизу?

<img width="212" alt="Screenshot 2022-11-10 at 17 45 35" src="https://user-images.githubusercontent.com/12209839/201095046-ce162cc1-9bb3-4542-9e19-42792b71ceb8.png">

2022-11-10 12:47 UTC, megakoko commented
Из stringdict надо все значения добавить в табличку APP_FINAL_PLURAL. Потом придумаем что с ними делать.

2022-11-10 13:30 UTC, megakoko requested changes

2022-11-10 13:30 UTC, megakoko commented on Tangem/Common/Localizations/ru.lproj/Localizable.strings
> +"referral_point_currencies_description_suffix" = " за каждый кошелек, который купит ваш друг на ваш адрес в сети Tron";
В конце строки нужен пробел, во всех языках

2022-11-10 13:30 UTC, megakoko commented on Tangem/App/Services/Referral/ReferralMocks.swift
> +    case notReferral
noReferral

2022-11-10 13:30 UTC, megakoko commented on Tangem/Modules/Referral/ReferralView.swift
> +        if !viewModel.isLoading, viewModel.isProgramInfoLoaded {
Лучше `&&`

2022-11-10 13:30 UTC, megakoko commented on Tangem/Modules/Referral/ReferralView.swift
> +        if !viewModel.isLoading, viewModel.isProgramInfoLoaded {
Два флага загрузки нужны? Не могу найти где внутри модели устанавливается isLoading.

2022-11-10 13:30 UTC, megakoko commented on Tangem/Modules/Referral/ReferralView.swift
> +        .foregroundColor(Colors.Text.tertiary)
У нас есть модификатор style, который и шрифт, и цвет задает, можно везде его заюзать

2022-11-10 13:30 UTC, megakoko commented on Tangem/Modules/Referral/ReferralViewModel.swift
> +    var isAlreadyReferral: Bool { referralProgramInfo?.referral != nil }
Читается как "уже реферальный". Раз кнопка называется "participate" я бы предложил переименовать в `isParticipating` / `isParticipatingInProgram`

2022-11-10 13:30 UTC, megakoko commented on Tangem/Modules/Referral/ReferralViewModel.swift
> +    var isAlreadyReferral: Bool { referralProgramInfo?.referral != nil }
alreadyReferralBottomView -> participantView

notReferralView -> participateView

2022-11-10 13:30 UTC, megakoko commented on Tangem/Modules/Referral/ReferralViewModel.swift
> +        return String.localizedStringWithFormat(stringFormat, info.walletPurchase)
Тут purchased, там bought

2022-11-10 13:30 UTC, megakoko commented on Tangem/App/Services/Referral/ReferralModels.swift
> +    let walletPurchase: Int
walletPurchase**d**

2022-11-10 13:30 UTC, megakoko commented on Tangem/App/Services/Referral/ReferralModels.swift
> +}
Давай перенесем эту структуру выше. Чтобы по иерархии читалось сверху вниз.

2022-11-10 13:30 UTC, megakoko commented on Tangem/App/Services/Referral/ReferralModels.swift
> +    let award: Decimal
Может awardAmount? Почему сумма награды одна, а токенов много?

2022-11-10 13:30 UTC, megakoko commented on Tangem/App/Services/Referral/ReferralModels.swift
> +    let discount: Int
Может discountValue? Может создать объект Discount { value, type } ?

2022-11-10 13:30 UTC, megakoko commented on Tangem/Modules/Referral/ReferralViewModel.swift
> +import struct SwiftUI.EdgeInsets
Зачем такими кусочками инклудить? Ничего ведь не кофликтует

2022-11-10 13:30 UTC, megakoko commented on Tangem/Modules/Referral/ReferralViewModel.swift
> +    @Published var referralProgramInfo: ReferralProgramInfo?
Можно ли сделать private(set)?

2022-11-10 13:30 UTC, megakoko commented on Tangem/App/Services/Referral/ReferralModels.swift
> +}
ReferralProgramInfo / ReferralInfo — может разнести по именам, чтобы не такими похожими были?

2022-11-10 13:30 UTC, megakoko commented on Tangem/Modules/Referral/Views/ReferralPointIcon.swift
> +
Лишняя пустая строка

2022-11-10 13:30 UTC, megakoko commented on Tangem/Modules/Referral/Views/ReferralPointIcon.swift
> +            .cornerRadius(16)
`.roundedBackground()`?

2022-11-10 13:30 UTC, megakoko commented on Tangem/Modules/Referral/Views/ReferralPointView.swift
> +
Пустая строка

2022-11-10 13:30 UTC, megakoko commented on Tangem/Modules/Referral/Views/ReferralPointView.swift
> +    private let bodyDescription: Text
Можно просто description

2022-11-10 13:30 UTC, megakoko commented on Tangem/Modules/Referral/Views/ReferralPointView.swift
> +                                   radius: 16)
Не надо лишний раз переносить, аргументов мало, строка короткая

2022-11-10 13:38 UTC, megakoko commented
Темная тема прям красота, жду с нетерпением как миллионы наших пользователей

2022-11-10 13:41 UTC, megakoko commented on Tangem/App/Services/Referral/ReferralModels.swift
> +    let walletPurchase: Int
Даже wallet**s**Purchase**d**

2022-11-12 09:57 UTC, Balashov152 commented on Tangem/Modules/Referral/ReferralView.swift
> +                        .font(Fonts.Bold.title1)
у нас для `Text` есть `style`. Лучше через него сделать, там шрифт и цвет сразу

что первый MR не посмотрел(

2022-11-12 09:57 UTC, Balashov152 commented on Tangem/Modules/Referral/ReferralView.swift
> +                        .padding(.bottom, geometry.safeAreaInsets.bottom == 0 ? 10 : geometry.safeAreaInsets.bottom)
```suggestion
                        .padding(.bottom, max(10, geometry.safeAreaInsets.bottom))
```
будет либо 10 либо safeArea

2022-11-12 09:57 UTC, Balashov152 commented on Tangem/Modules/Referral/ReferralView.swift
> +                .frame(minWidth: geometry.size.width, maxWidth: geometry.size.width, minHeight: geometry.size.height + geometry.safeAreaInsets.bottom)
```suggestion
                .frame(width: geometry.size.width)
                .frame(minHeight: geometry.size.height + geometry.safeAreaInsets.bottom)
```

Смысл в одном и том же значении. А вообще можно еще `.frame(maxWidth: .infinity)`

2022-11-12 09:57 UTC, Balashov152 commented on Tangem/Modules/Referral/ReferralView.swift
> +                .frame(minWidth: geometry.size.width, maxWidth: geometry.size.width, minHeight: geometry.size.height + geometry.safeAreaInsets.bottom)
А вообще нужно frame ставить?, `GeometryReader` же и так все пространство займет

2022-11-12 09:57 UTC, Balashov152 commented on Tangem/Modules/Referral/ReferralView.swift
> +        if !viewModel.isLoading, viewModel.isProgramInfoLoaded {
Swiftformat обычно убирает && на запятую, что бы везде клинообразно быть, где `if let` и условия

2022-11-12 09:57 UTC, Balashov152 commented on Tangem/Modules/Referral/ReferralView.swift
> +                    .fixedSize(horizontal: false, vertical: true)
тут тоже через style лучше

2022-11-12 09:57 UTC, Balashov152 commented on Tangem/Modules/Referral/ReferralView.swift
> +                .padding(.bottom, 12)
```suggestion
        VStack(spacing: 12) {
            touButton
```
может лучше через `spacing`?

2022-11-12 09:57 UTC, Balashov152 commented on Tangem/Modules/Referral/Views/Modifiers/RoundedBackgroundModifier.swift
> +}
проперти есть, а в `body` хардкод

2022-11-12 09:57 UTC, Balashov152 commented on Tangem/Modules/Referral/Views/ReferralPointView.swift
> +    }
что то мне кажется лучше все таки closer'ы хранить, помню у нас падало так на 14.2. Так конечно прикольно, что без `escaping`. Но по ему SUI тупит, на не которых осях

2022-11-12 09:57 UTC, Balashov152 commented on Tangem/Modules/Referral/Views/ReferralPointView.swift
> +    }
Ну и можно сделать body: body, с одинаковым неймингом

2022-11-14 09:04 UTC, tureck1y commented on Tangem/App/Services/Referral/ReferralMocks.swift
> +            {
Давайте все json держать в файлах

2022-11-14 09:04 UTC, tureck1y commented on Tangem/Modules/Referral/ReferralCoordinator.swift
> +        referralViewModel = .mock(.referral, with: ReferralCoordinator())
тут все ок?

2022-11-14 09:04 UTC, tureck1y commented on Tangem/Modules/Referral/ReferralView.swift
> +                        .font(Fonts.Bold.title1)
да, надо везде переходить на новую систему

2022-11-14 09:04 UTC, tureck1y commented on Tangem/Modules/Referral/ReferralView.swift
> +                .frame(minWidth: geometry.size.width, maxWidth: geometry.size.width, minHeight: geometry.size.height + geometry.safeAreaInsets.bottom)
Есть варианты упростить верстку? Без вот этих фреймов, оффсетов и geometryReader? Как показывает практика, чем меньше непонятно, тем лучше и стабильнее работает. Даже если на iOS 13/14 будет немного отличаться - не страшно.

2022-11-14 09:04 UTC, tureck1y commented on Tangem/Modules/Referral/ReferralViewModel.swift
> +    private init(coordinator: ReferralRoutable, json: String = "") {
1) Почему конструктор приватный?
2) Дефолтное значение я бы убрал, непонятно
3) Форс анрврап в декодинге я бы тоже убрал

2022-11-14 09:04 UTC, tureck1y commented on Tangem/Modules/Referral/ReferralViewModel.swift
> +    static func mock(_ mock: ReferralMock, with coordinator: ReferralRoutable) -> ReferralViewModel {
Вижу коммент про temp. Если статика останется, лучше ее в экстеншн унести, чтобы не болталась, как и все методы, в которых будет вызываться координатор, как делали в других модулях

2022-11-14 09:04 UTC, tureck1y commented on Tangem/Modules/Referral/ReferralView.swift
> +        if !viewModel.isLoading, viewModel.isProgramInfoLoaded {
Я предлагаю такую логику во вью не держать. Вью тупое и проверяют один флаг во вьюмодели, который скажет какой контент показывать

2022-11-15 05:47 UTC, Andoran90 commented on Tangem/App/Services/Referral/ReferralMocks.swift
> +    case notReferral
логика не - "нет реферала", а "не реферал", просто писать `notAReferral` некрасиво

2022-11-15 05:57 UTC, Andoran90 commented on Tangem/App/Services/Referral/ReferralModels.swift
> +    let award: Decimal
потому что токены награды могут быть разные, поэтому список присылается, может варьироваться. Эта структура отражение того что апишка возвращает. Можно перемапить во внутреннюю структуру

2022-11-15 05:59 UTC, Andoran90 commented on Tangem/App/Services/Referral/ReferralModels.swift
> +}
как вариант можно сложить все структуры внутрь `ReferralProgramInfo`, т.к. они относятся только к ней, тогда можно заменить с `ReferralInfo` - `Referral`

2022-11-15 07:18 UTC, Andoran90 commented on Tangem/Modules/Referral/ReferralCoordinator.swift
> +        referralViewModel = .mock(.referral, with: ReferralCoordinator())
пока что да. Как буду прикручивать сервис боевой избавлюсь от этого. Сейчас надо чтобы превьюхи работали и можно было посмотреть полностью весь интерфейс

2022-11-15 07:18 UTC, Andoran90 commented on Tangem/Modules/Referral/ReferralView.swift
> +                        .font(Fonts.Bold.title1)
да, чет не обратил внимания, обновлю

2022-11-15 07:25 UTC, Andoran90 commented on Tangem/Modules/Referral/ReferralView.swift
> +                .frame(minWidth: geometry.size.width, maxWidth: geometry.size.width, minHeight: geometry.size.height + geometry.safeAreaInsets.bottom)
там проблема с расположением элементов. Они находятся внутри скролла, а кнопка в нижней части экрана должна находиться на дне, да ещё и скролиться. + при разных размерах экрана и если увеличенный шрифт, она может тоже менять местоположение. поэтому приходится считывать размеры и задавать их для контейнера. В UIKit с этим было попроще. Как вариант можно менять весь базовый элемент (скролл) и для загрузчика ставить без скрола, но тогда объемы увеличатся.
Если посмотреть скрины - на девайсах с бровью - места дофига, а на 8+ (на последнем скриншот) уже почти впритык.

2022-11-15 10:57 UTC, Andoran90 commented on Tangem/App/Services/Referral/ReferralModels.swift
> +    let walletPurchase: Int
это мапится с апишного ответа, не очень хотелось из-за этого затаскивать `CodingKeys`, может быть будем делать обновление на серваке с переносом награды в токены, там же сразу и поправим. Если это критично, могу добавить `CodingKeys`

2022-11-15 11:01 UTC, Andoran90 commented on Tangem/Modules/Referral/ReferralView.swift
> +        if !viewModel.isLoading, viewModel.isProgramInfoLoaded {
`isLoading` этот флаг использовал до верстки основного контента. Надо удалить, `isProgramInfoLoaded` вполне достаточно

2022-11-15 11:08 UTC, Andoran90 commented on Tangem/Modules/Referral/ReferralView.swift
> +        .foregroundColor(Colors.Text.tertiary)
мммм, он же только для `Text`, а тут кнопка с кучей текстовок. Добавлю тогда такую же для кнопки

2022-11-15 11:09 UTC, Andoran90 commented on Tangem/Modules/Referral/ReferralView.swift
> +        .foregroundColor(Colors.Text.tertiary)
хотя я планирую проверять в скором времени все кнопки на темную тему, так скорее всего подрефакторю её. Поэтому думаю лучше пока так оставить, а потом заменю везде с новым кодом

2022-11-15 11:18 UTC, Andoran90 commented on Tangem/Modules/Referral/ReferralViewModel.swift
> +    private init(coordinator: ReferralRoutable, json: String = "") {
потому что этот конструктор пока нигде использоваться не будет, пока не будет готов сервис, а сервис в другой задачке. Пока просто чтобы заткнуть, нам json вообще не понадобится

2022-11-15 11:19 UTC, Andoran90 commented on Tangem/Modules/Referral/ReferralViewModel.swift
> +    static func mock(_ mock: ReferralMock, with coordinator: ReferralRoutable) -> ReferralViewModel {
у меня есть идея как это сделать, но тут статики не будет, думаю все в задаче с сервисом изменю. Пока сюда запихнул чтобы удобно было с этим работать

2022-11-15 11:22 UTC, Andoran90 commented on Tangem/Modules/Referral/Views/Modifiers/RoundedBackgroundModifier.swift
> +}
оп))) пардоньте 😅

2022-11-15 11:27 UTC, tureck1y commented on Tangem/Modules/Referral/ReferralViewModel.swift
> +    private init(coordinator: ReferralRoutable, json: String = "") {
сложна)

2022-11-15 11:28 UTC, Andoran90 commented on Tangem/Modules/Referral/Views/ReferralPointView.swift
> +    }
а что именно падало? мне просто хранение кложур вообще не нравится для этих целей

я в начале тоже хотел просто body, но есть проперти body)

2022-11-15 11:29 UTC, Andoran90 commented on Tangem/Modules/Referral/Views/ReferralPointView.swift
> +                                   radius: 16)
удалил нафиг это все)

2022-11-15 11:31 UTC, megakoko commented on Tangem/App/Services/Referral/ReferralModels.swift
> +    let walletPurchase: Int
Нельзя поменять апишку? Мы же еще не зарелизились

2022-11-15 11:32 UTC, Andoran90 commented on Tangem/Modules/Referral/Views/ReferralPointIcon.swift
> +
done

2022-11-15 11:32 UTC, Andoran90 commented on Tangem/Modules/Referral/Views/ReferralPointIcon.swift
> +            .cornerRadius(16)
заменил

2022-11-15 11:34 UTC, Andoran90 commented on Tangem/App/Services/Referral/ReferralMocks.swift
> +            {
давай я перенесу это в следующем МР? там поменяю логику моков

2022-11-15 11:41 UTC, Andoran90 commented on Tangem/Modules/Referral/ReferralViewModel.swift
> +    var isAlreadyReferral: Bool { referralProgramInfo?.referral != nil }
не вижу смысла подгонять все под текстовку кнопки. Потом будет не совпадать `referral` и `isParticipating`.

2022-11-15 11:41 UTC, Andoran90 commented on Tangem/Modules/Referral/Views/ReferralPointView.swift
> +
удалил

2022-11-15 11:41 UTC, Andoran90 commented on Tangem/Modules/Referral/Views/ReferralPointView.swift
> +    private let bodyDescription: Text
вполне)

2022-11-15 11:43 UTC, Andoran90 commented on Tangem/Modules/Referral/ReferralView.swift
> +                        .padding(.bottom, geometry.safeAreaInsets.bottom == 0 ? 10 : geometry.safeAreaInsets.bottom)
заменил

2022-11-15 11:43 UTC, Andoran90 commented on Tangem/Modules/Referral/ReferralView.swift
> +                    .fixedSize(horizontal: false, vertical: true)
обновлено

2022-11-15 11:43 UTC, Andoran90 commented on Tangem/Modules/Referral/ReferralView.swift
> +                .padding(.bottom, 12)
да, ок

2022-11-15 11:49 UTC, tureck1y commented on Tangem/Modules/Referral/ReferralViewModel.swift
> +    private init(coordinator: ReferralRoutable, json: String = "") {
да делай лучше сразу финальный вариант

2022-11-15 11:49 UTC, tureck1y commented on Tangem/App/Services/Referral/ReferralMocks.swift
> +            {
да зачем по несколько раз одно и то же смотреть, просто json в файл закинуть и всего делов)

2022-11-15 11:49 UTC, Andoran90 commented on Tangem/Modules/Referral/ReferralViewModel.swift
> +        return String.localizedStringWithFormat(stringFormat, info.walletPurchase)
обновил

2022-11-15 11:50 UTC, Andoran90 commented on Tangem/App/Services/Referral/ReferralModels.swift
> +    let walletPurchase: Int
можно, но лучше все разом заменить, а не по одной правке делать. пока что дикими страданиями апишка вышла на неделю позже чем должна была

2022-11-15 11:50 UTC, Andoran90 commented on Tangem/App/Services/Referral/ReferralModels.swift
> +    let discount: Int
ждем-с что Леша скажет

2022-11-15 11:51 UTC, Andoran90 commented on Tangem/Modules/Referral/ReferralViewModel.swift
> +import struct SwiftUI.EdgeInsets
чтобы доступа к лишнему не было

2022-11-15 11:52 UTC, tureck1y commented on Tangem/App/Services/Referral/ReferralModels.swift
> +    let walletPurchase: Int
да чего им долго поле поменять чтоль

2022-11-15 11:53 UTC, tureck1y commented on Tangem/Modules/Referral/ReferralViewModel.swift
> +import struct SwiftUI.EdgeInsets
мне кажется это уже эребор

2022-11-15 11:55 UTC, Andoran90 commented on Tangem/App/Services/Referral/ReferralMocks.swift
> +            {
просто не хочу тратить время на переделывание сейчас того, что через пару часов снова буду переделывать

2022-11-15 11:56 UTC, Andoran90 commented on Tangem/Modules/Referral/ReferralViewModel.swift
> +    private init(coordinator: ReferralRoutable, json: String = "") {
сервис апишный нужен для этого, а это другая задача

2022-11-15 11:57 UTC, tureck1y commented on Tangem/Modules/Referral/ReferralViewModel.swift
> +    private init(coordinator: ReferralRoutable, json: String = "") {
я не понимаю( Ты сделал пр с вьюмоделью, а в след пр полезешь ее переделывать?

2022-11-15 12:02 UTC, megakoko commented on Tangem/Modules/Referral/ReferralViewModel.swift
> +    var isAlreadyReferral: Bool { referralProgramInfo?.referral != nil }
Читается просто легче

2022-11-15 12:02 UTC, Andoran90 commented on Tangem/Modules/Referral/ReferralViewModel.swift
> +    private init(coordinator: ReferralRoutable, json: String = "") {
ну а как ты собираешься интегрировать сервис апишный? в любом случае надо будет обновлять его. Итак хватает комментариев: "это на Новый год", можно было бы сразу сделать протокол для сервиса, но это же другая логика уже: интеграция сервиса во вью модель

2022-11-15 12:05 UTC, tureck1y commented on Tangem/App/Services/Referral/ReferralMocks.swift
> +            {
Не совсем понял как перенос json в файлы поменяет логику, но ок

2022-11-15 12:08 UTC, tureck1y commented on Tangem/Modules/Referral/ReferralViewModel.swift
> +    private init(coordinator: ReferralRoutable, json: String = "") {
Каким образом влияет интеграция сервиса на приватность конструктора вью модели? 

Если json не используется то и удаляй его, если конструктор в след пр станет публичный, то почему бы сразу публичным не сделать?

2022-11-15 12:14 UTC, Andoran90 commented on Tangem/Modules/Referral/ReferralViewModel.swift
> +    private init(coordinator: ReferralRoutable, json: String = "") {
потому что сейчас у тебя на вход идет JSON, потом на вход будет идти сервис и эта логика будет вообще не нужна и переедет внутрь сервиса моковского.

2022-11-15 12:56 UTC, Andoran90 commented on Tangem/Modules/Referral/ReferralViewModel.swift
> +    private init(coordinator: ReferralRoutable, json: String = "") {
вообще, по уму надо было в начале сделать задачу с сервисом, а потом уже с вью моделью, но т.к. у нас бак пошел по одному месту, пришлось делать в начале вью модельку, а потом уже сервис интегрировать

2022-11-15 13:21 UTC, Andoran90 commented on Tangem/Modules/Referral/ReferralViewModel.swift
> +    var isAlreadyReferral: Bool { referralProgramInfo?.referral != nil }
и почему ты читаешь как "уже реферальный", если перевод "уже является рефералом"? я не пишу `isAlreadyAReferral`, потому что артикль "a" не ставятся в коде, но из-за этого менять названия думаю вообще нелепо.

2022-11-15 13:23 UTC, Andoran90 commented on Tangem/App/Services/Referral/ReferralModels.swift
> +    let walletPurchase: Int
я напишу Вадиму, но до этого 3 дня только заливали изменения, сейчас из-за этого буксовать и не мерить думаю пустая трата времени.

2022-11-15 13:24 UTC, Andoran90 commented on Tangem/Modules/Referral/ReferralViewModel.swift
> +import struct SwiftUI.EdgeInsets
после обновления все ушло, кроме UIKit.UIPasteboard. Или лучше импортировать весь UIKit?

2022-11-15 13:37 UTC, megakoko commented on Tangem/Modules/Referral/ReferralViewModel.swift
> +import struct SwiftUI.EdgeInsets
Это же не Си где все заголовочные файлы UIKit включились бы. Надо UIKit — включай весь, зачем осторожничать

2022-11-15 13:37 UTC, megakoko commented on Tangem/App/Services/Referral/ReferralModels.swift
> +    let walletPurchase: Int
Надо бы сделать все равно

2022-11-15 13:39 UTC, megakoko approved these changes

2022-11-15 16:26 UTC, tureck1y approved these changes

2022-11-16 16:43 UTC, merged