IOS-2364 Swapping refactoring
tangem/tangem-app-ios-old pull request #922
Opened 2022-11-18 09:03 UTC by Balashov152

Создал либу TangemExchange
перенес туда спи слой и DTO из exchangeSDK, по этому столько добавленых строк и файлов

Вынес логику в ExchangeManager у которого есть BlockchainNetworkProvider(для общения с сетью)
теперь ExchangeProvider интерфейс для отправки всех запросов

Входной точной является Currency объект
Для общения с блокчейн сетью есть абстракция BlockchainNetworkProvider

2022-11-23 09:35 UTC, Balashov152 commented
Убрал ExchangeModule что бы он не смущал
Главное глянуть

1. `ExchangeManager`
2. `ExchangeProvider`
3. `ExchangeOneInchProvider`
4. `BlockchainNetworkProvider`
5. `OneInchApiServiceProtocol`

2022-11-23 11:12 UTC, Andoran90 commented on Tangem/App/Services/Exchange/WalletManager+BlockchainProvider.swift
> +extension ExchangeBlockchainProvider: BlockchainNetworkProvider {
мне кажется не очень удачные названия... непонятно кто чем занимается.
может `CurrencyExchangeService` `ExchangeCurrencyService`? а то кажется что он предоставляет блокчеины. Наверное имеет смысл сделать так же как в блокчеин сдк, `BitcoinNetworkProvider` - протокол, который описывает как можно обращаться к биткоин сети,  `BitcoinNetworkService` - класс, который реализует это обращение. `ExchangeNetworkProvider` - протокол
`ExchangeNetworkService` - класс реализующий протокол

2022-11-23 11:12 UTC, Andoran90 commented on Tangem/App/Services/Exchange/WalletManager+BlockchainProvider.swift
> +struct ExchangeBlockchainProvider {
файл надо переименовать

2022-11-23 11:12 UTC, Andoran90 commented on Tangem/Modules/Exchange/ExchangeViewModel.swift
> +    private let router: ExchangeRoutable
давай поменяем название на coordinator и надо сделать его `unowned`

2022-11-23 11:12 UTC, Andoran90 commented on Tangem/Modules/Exchange/ExchangeViewModel.swift
> +    init(router: ExchangeRoutable, exchangeManager: ExchangeManager) {
заодно и тут поменяй, пожалуйста, местами. Пока везде закладываем, что координатор идет последним

2022-11-23 11:12 UTC, Andoran90 commented on Tangem/Modules/Exchange/ExchangeViewModel.swift
> +//        items = ExchangeItems(sourceItem: sourceItem, destinationItem: destinationItem)
можем удалим все закомментированные строки? или нычки нужны будут скоро?

2022-11-23 11:12 UTC, Andoran90 commented on Tangem/Modules/Exchange/ExchangeViewModel.swift
>  extension ExchangeViewModel {
тут какой-то хитрый план с пустым `Extension`? он будет заполняться методами?

2022-11-23 11:12 UTC, Andoran90 commented on Tangem/App/Services/Exchange/WalletManager+BlockchainProvider.swift
> +            .async()
прикольно, получается все равно используется комбайн полностью, а потом оборачивается только в async. Может лучше мапинг вытащить из комбайна и сразу после запроса фи делать?  (опциональный коммент)

2022-11-23 11:12 UTC, Andoran90 commented on TangemExchange/Interfaces/BlockchainNetworkProvider/BlockchainNetworkProvider.swift
> +}
мы потом будем путаться что это за провайдер, для каких целей он используется

2022-11-23 11:12 UTC, Andoran90 commented on TangemExchange/Interfaces/BlockchainNetworkProvider/BlockchainNetworkProvider.swift
> +public struct TransactionInfo {
может `ExchangeTransactionInfo`?

2022-11-23 11:12 UTC, Andoran90 commented on TangemExchange/Interfaces/ExchangeProviders/ExchangeOneInchProvider.swift
> +class ExchangeOneInchProvider {
`ExchangeOneInchService`?

2022-11-23 11:12 UTC, Andoran90 commented on TangemExchange/Interfaces/BlockchainNetworkProvider/BlockchainNetworkProvider.swift
> +public struct TransactionInfo {
+ это лучше вынести в отдельный файл

2022-11-23 11:12 UTC, Andoran90 commented on TangemExchange/Interfaces/ExchangeProviders/ExchangeOneInchProvider.swift
> +//        return tx
не понадобится?

2022-11-23 11:12 UTC, Andoran90 commented on TangemExchange/Interfaces/ExchangeProviders/ExchangeProvider.swift
> +struct SwapTransactionInfo {
тоже в отдельный файл надо перенести

2022-11-23 11:12 UTC, Andoran90 commented on TangemExchange/Managers/ExchangeManager.swift
> +}
понадобится?

2022-11-23 11:12 UTC, Andoran90 commented on TangemExchange/Managers/ExchangeManager.swift
> +//    func onSwapItems() {
а это?

2022-11-23 11:12 UTC, Andoran90 commented on Tangem/App/Services/Exchange/WalletManager+BlockchainProvider.swift
> +    private let signer: TangemSigner
лучше заменить на протокол: `TransactionSigner`

2022-11-23 11:12 UTC, Andoran90 commented on TangemExchange/Models/Currency.swift
> +//    }
понадобятся?

2022-11-23 11:12 UTC, Andoran90 commented on TangemExchange/Services/API/ExchangeNetworkService.swift
> +                            let object = try self.jsonDecoder.decode(T.self, from: response.data)
посмотри, пожалуйста, в рефералке как сделано (файл `Moya+`). Может оттуда возьмем реализацию? Мне кажется там почище получилось. Единственное  что там отменять запросы нельзя, но важно ли нам это?

2022-11-23 11:13 UTC, Balashov152 commented on Tangem/Modules/Exchange/ExchangeViewModel.swift
> +    private let router: ExchangeRoutable
удалил вообще файл)

2022-11-23 11:15 UTC, Balashov152 commented on TangemExchange/Services/API/ExchangeNetworkService.swift
> +                            let object = try self.jsonDecoder.decode(T.self, from: response.data)
посмотрю, думаю отменять важно, если вдруг debounce будет, или что такое

2022-11-23 14:00 UTC, Balashov152 commented on Tangem/App/Services/Exchange/WalletManager+BlockchainProvider.swift
> +struct ExchangeBlockchainProvider {
✅

2022-11-23 14:00 UTC, ba1ashov commented on Tangem/Modules/Exchange/ExchangeViewModel.swift
> +    init(router: ExchangeRoutable, exchangeManager: ExchangeManager) {
удалил вообще файл)

2022-11-23 14:00 UTC, Balashov152 commented on Tangem/Modules/Exchange/ExchangeViewModel.swift
> +//        items = ExchangeItems(sourceItem: sourceItem, destinationItem: destinationItem)
удалил вообще файл)

2022-11-23 14:00 UTC, Balashov152 commented on Tangem/Modules/Exchange/ExchangeViewModel.swift
>  extension ExchangeViewModel {
удалил вообще файл)

2022-11-23 14:00 UTC, Balashov152 commented on TangemExchange/Interfaces/BlockchainNetworkProvider/BlockchainNetworkProvider.swift
> +public struct TransactionInfo {
✅

2022-11-23 14:00 UTC, Balashov152 commented on TangemExchange/Interfaces/ExchangeProviders/ExchangeOneInchProvider.swift
> +class ExchangeOneInchProvider {
✅

2022-11-23 14:00 UTC, Balashov152 commented on TangemExchange/Interfaces/ExchangeProviders/ExchangeOneInchProvider.swift
> +//        return tx
✅

2022-11-23 14:00 UTC, Balashov152 commented on TangemExchange/Interfaces/ExchangeProviders/ExchangeProvider.swift
> +struct SwapTransactionInfo {
✅

2022-11-23 14:01 UTC, Balashov152 commented on TangemExchange/Managers/ExchangeManager.swift
> +}
думаю да, будет там писать когда буду делать реализацию

2022-11-23 14:02 UTC, Balashov152 commented on TangemExchange/Managers/ExchangeManager.swift
> +//    func onSwapItems() {
Решил оставить, что бы когда буду делать реализацию, проще было

2022-11-23 14:02 UTC, Balashov152 commented on TangemExchange/Models/Currency.swift
> +//    }
это убрал )

2022-11-23 14:06 UTC, Balashov152 commented on Tangem/App/Services/Exchange/WalletManager+BlockchainProvider.swift
> +extension ExchangeBlockchainProvider: BlockchainNetworkProvider {
Теперь есть 
- <ExchangeManager> / CommonExchangeManager
- CommonExchangeManager инжект <ExchangeProvider> / OneInchService
- OneInchService инжект 
<BlockchainNetworkProvider> / BlockchainNetworkService
и
 <OneInchAPIProvider> / OneInchAPIService

2022-11-23 14:15 UTC, tureck1y reviewed
Надо с протоколами-сервисами разобраться, наверное лучше в слэке отдельно обсудить

2022-11-23 14:15 UTC, tureck1y commented on TangemExchange/TExchange.docc/TExchange.md
> +# ``TExchange``
выглядит как дженериковый типок)

2022-11-23 14:15 UTC, tureck1y commented on TangemExchange/Constants.swift
> +    private enum APIVersion: String {
Надо наверное как-то дополнительно показать, что это версия именно oneinch

2022-11-23 14:15 UTC, tureck1y commented on TangemExchange/Factory/TangemExchangeFactory.swift
> +    public static func createExchangeManager(
Может лучше структуру и без статики?

2022-11-23 14:15 UTC, tureck1y commented on TangemExchange/Interfaces/BlockchainNetworkProvider/BlockchainNetworkProvider.swift
> +}
мы в итоге используем блокчейн сдк в этом модуле или нет?

2022-11-23 14:15 UTC, tureck1y commented on Tangem/App/Services/Exchange/ExchangeBlockchainProvider.swift
> +struct BlockchainNetworkService {
этот файл не должен лежать в TangemExchange?

2022-11-23 14:15 UTC, tureck1y commented on TangemExchange/Models/OneInch/DTO/QuoteParameters.swift
> +    func parameters() -> [String: Any] {
Повсюду эта штука в DTO, напрашивается протокол какой-то

2022-11-23 14:15 UTC, tureck1y commented on TangemExchange/Services/API/ExchangeNetworkService.swift
> +class NetworkService {
NetworkFacade.swift
NetworkService
ExchangeNetworkService.swift

кто же ты такой?)

2022-11-28 07:47 UTC, Balashov152 commented on TangemExchange/Services/API/ExchangeNetworkService.swift
> +class NetworkService {
Все удаленны

2022-11-28 08:03 UTC, Balashov152 commented on TangemExchange/Models/OneInch/DTO/QuoteParameters.swift
> +    func parameters() -> [String: Any] {
Переделал на `Encodable`

2022-11-28 08:04 UTC, Balashov152 commented on Tangem/App/Services/Exchange/ExchangeBlockchainProvider.swift
> +struct BlockchainNetworkService {
Он переименован, лежит в приложении как объект с которым будет взаимодействовать TangemExchange

2022-11-28 08:05 UTC, Balashov152 commented on TangemExchange/Constants.swift
> +    private enum APIVersion: String {
rename to `OneInchAPIVersion` ✅

2022-11-28 08:06 UTC, Balashov152 commented on TangemExchange/TExchange.docc/TExchange.md
> +# ``TExchange``
Переименовать забыл)

2022-11-28 09:17 UTC, Balashov152 commented on Tangem/App/Services/Exchange/WalletManager+BlockchainProvider.swift
> +    private let signer: TangemSigner
✅

2022-11-28 09:18 UTC, ba1ashov commented on TangemExchange/Interfaces/BlockchainNetworkProvider/BlockchainNetworkProvider.swift
> +}
Выпилил BlockchainSdk из модуля

2022-11-28 09:18 UTC, Balashov152 commented on TangemExchange/Factory/TangemExchangeFactory.swift
> +    public static func createExchangeManager(
✅

2022-11-29 07:06 UTC, tureck1y commented on TangemExchange/Types/Constants.swift
> +
Может папку Types переименовать в Models или Entities

2022-11-29 07:06 UTC, tureck1y commented on TangemExchange/Services/OneInch/API/LimitOrder/OneInchLimitOrderService.swift
> +    func request<T: Decodable>(target: BaseTarget) async -> Result<T, ExchangeInchError> {
private?

2022-11-29 07:06 UTC, tureck1y commented on TangemExchange/Extensions/Data+.swift
> +    public init(hexString: String) {
Эта штука будет конфликтовать и заместит собой другие реализации.  Если делаем фреймворк для свапалки, то такой экстеншн надо оставить приватным внутри него.

2022-11-29 07:06 UTC, tureck1y commented on TangemExchange/Managers/DefaultExchangeManager.swift
> +        blockchainInfoProvider: BlockchainInfoProvider,
Стоит ли их объединить через &? Скорее всего это всегда будет один и тот же объект

2022-11-29 07:33 UTC, Balashov152 commented on TangemExchange/Managers/DefaultExchangeManager.swift
> +        blockchainInfoProvider: BlockchainInfoProvider,
я думал, но решил лучше отдельно сделать, мало ли будем разделять, или кто то разделит
лучше много маленьких сервисов, чем один большой)

2022-11-29 07:33 UTC, Balashov152 commented on TangemExchange/Extensions/Data+.swift
> +    public init(hexString: String) {
сделал `internal`

2022-11-29 07:34 UTC, Balashov152 commented on TangemExchange/Services/OneInch/API/LimitOrder/OneInchLimitOrderService.swift
> +    func request<T: Decodable>(target: BaseTarget) async -> Result<T, ExchangeInchError> {
`private extension` все методы внутри делает приватными )

2022-11-29 07:34 UTC, Balashov152 commented on TangemExchange/Types/Constants.swift
> +
сделал `Models ` ✅

2022-11-29 09:16 UTC, tureck1y submitted a review, later dismissed

2022-11-30 08:55 UTC, Andoran90 requested changes

2022-11-30 08:55 UTC, Andoran90 commented on Tangem/App/Services/Exchange/BlockchainNetworkService.swift
> +            .async()
мне не особо нравится этот вариант. Думаю правильнее
```suggestion
        let fees = try await walletManager.getFee(amount: amount, destination: destination).async()
        return fees.map { $0.value }
```
а то получается что ты все равно всю работу выполняешь в комбайне, а потом выдаешь только результат. А в предложенном варианте у тебя только часть блокчеин сдк оборачивается в continuation

2022-11-30 08:55 UTC, Andoran90 commented on TangemExchange/Extensions/Data+.swift
> +    init(hexString: String) {
предложение на будущее:
может вынесем все наши вот такие расширения в отдельный модуль и импортировать его всюду будем. `TangemUtils` или `TangemExtensions` например.

2022-11-30 08:55 UTC, Andoran90 commented on Tangem/App/Services/Exchange/BlockchainNetworkService.swift
> +        return transaction
нужна пояснительная бригада 😅
зачем оно надо вообще если ничего не происходит? О_о
Я так понимаю что пользователям со стороны важно будет чтобы транзакции все же подписывалась сайнером, который они передали. или как?

2022-11-30 08:55 UTC, Andoran90 commented on TangemExchange/Managers/DefaultExchangeManager.swift
> +    }
не самое удачное название для функции, как мне кажется. Показалось что swapItems - поменять их местами, т.к. исходую монету с целевой поменять местами, а не провести транзакцию для обмена. Может `exchangeItems`, раз это ExchangeManager

2022-11-30 08:55 UTC, Andoran90 commented on TangemExchange/Managers/DefaultExchangeManager.swift
> +        exchangeItems: ExchangeItems,
я Паше писал об этом, но он не особо прокомментировал это. Для чего нам нужен ExchangeItems? просто контейнер, который держит основную и целевую монету? Почему бы не передавать просто исходную и целевую в методе?
А когда надо поменять местами исходную и целевую монеты, кто этим занимается?
Этим всем будет заниматься `ExchangeManager`?
ExchangeItems уже проросли всюду, поэтому просто поясните зачем оно надо)

2022-11-30 08:55 UTC, Andoran90 commented on TangemExchange/Managers/DefaultExchangeManager.swift
> +    func getNetworksAvailableToSwap() -> [String] {
не очень нравится что то exchange, то swap. у нас есть ExchangeItems, но мы их свапаем. ExchangeManager делает дает сети доступные для swap

2022-11-30 08:55 UTC, Andoran90 commented on TangemExchange/Managers/DefaultExchangeManager.swift
> +    func isAvailableForExchange(amount: Decimal) -> Bool {
`isAvailableForSwap`? ну и т.д. по файлу)

2022-11-30 08:55 UTC, Andoran90 commented on TangemExchange/Managers/DefaultExchangeManager.swift
> +        let info = SwapTransactionInfo(
блин, всюду разнобой получился, где-то exchange, где-то swap, хотя везде об одном и том же речь идет 😒

2022-11-30 08:55 UTC, Andoran90 commented on TangemExchange/Models/Currency.swift
> +
лишний пробел 😅

2022-11-30 08:55 UTC, Andoran90 commented on TangemExchange/Models/ExchangeItem.swift
> +class ExchangeItem: Identifiable {
наверное в будущих сезонах будут ссылки)

2022-11-30 08:55 UTC, Andoran90 commented on TangemExchange/Models/OneInch/Targets/BaseTarget.swift
> +    let target: TargetType
```suggestion
    let target: TargetType
    let blockchain: ExchangeBlockchain
```

2022-11-30 08:55 UTC, Andoran90 commented on TangemExchange/Models/OneInch/Targets/BaseTarget.swift
> +        target.path
```suggestion
        "/\(blockchain.id)/\(target.path)"
```
тогда из всех таргетов можно будет убрать эту логику. Будет проще, наверное

2022-11-30 08:55 UTC, Andoran90 commented on TangemExchange/Services/OneInch/API/OneInchAPIService.swift
> +    }
дважды одно и то же. Имеет смысл сделать это либо протоколом с дефолтным extension (`APIRequestProcessable`), либо сделать классом и от него наследоваться. Либо удалить нафиг `OneInchLimitOrderService` 😅
Мне больше всего нравится вариант с классом, который на вход принимает декодер и возможно `MoyaProvider`

2022-11-30 08:56 UTC, Balashov152 commented on TangemExchange/Extensions/Data+.swift
> +    init(hexString: String) {
Да, в планах есть `TangemFoundation` для такого
Пока просто copy-paste

2022-11-30 08:58 UTC, Balashov152 commented on Tangem/App/Services/Exchange/BlockchainNetworkService.swift
> +        return transaction
вообще идея в том что бы подпись и отправку можно было разделить в объекте который реализует протокол `TransactionBuilder`. Но так как у нас это не отдельно, то наш объект будет тупо возвращать не подписанную транзакцию

2022-11-30 08:59 UTC, Balashov152 commented on TangemExchange/Managers/DefaultExchangeManager.swift
> +    }
Да, можно, но я думаю по ходу добавления UI еще маленько будет меняться

2022-11-30 09:00 UTC, Balashov152 commented on TangemExchange/Managers/DefaultExchangeManager.swift
> +        exchangeItems: ExchangeItems,
Ну вообще идея в том, что бы сделать из этого  объекта один источник правды для того, какие items меняем, что бы вся инфа была именно в нем, и он в дальнейшем будет заниматься обновление UI

2022-11-30 09:01 UTC, Balashov152 commented on TangemExchange/Models/ExchangeItem.swift
> +class ExchangeItem: Identifiable {
забыл удалить `ExchangeItem`

2022-11-30 09:07 UTC, Andoran90 commented on Tangem/App/Services/Exchange/BlockchainNetworkService.swift
> +        return transaction
а, блин, это же в аппке объект. тупанул

2022-11-30 09:08 UTC, Andoran90 commented on TangemExchange/Managers/DefaultExchangeManager.swift
> +        exchangeItems: ExchangeItems,
а почему он будет заниматься обновлением UI? это же не вью моделька

2022-11-30 09:37 UTC, Balashov152 commented on Tangem/App/Services/Exchange/BlockchainNetworkService.swift
> +            .async()
согласен ✅

2022-11-30 09:58 UTC, Balashov152 commented on TangemExchange/Managers/DefaultExchangeManager.swift
> +    func getNetworksAvailableToSwap() -> [String] {
✅ getNetworksAvailableToExchange()

2022-11-30 09:58 UTC, Balashov152 commented on TangemExchange/Managers/DefaultExchangeManager.swift
> +        let info = SwapTransactionInfo(
ExchangeTransactionInfo ✅

2022-11-30 09:58 UTC, Balashov152 commented on TangemExchange/Models/Currency.swift
> +
✅

2022-11-30 10:20 UTC, Balashov152 commented on TangemExchange/Services/OneInch/API/OneInchAPIService.swift
> +    }
Да пускай пока так будет, может потом с LimitOrder расхождения будут, и придется чет костылять

2022-11-30 10:21 UTC, Balashov152 commented on TangemExchange/Models/OneInch/Targets/BaseTarget.swift
> +    let target: TargetType
✅

2022-11-30 10:21 UTC, Balashov152 commented on TangemExchange/Models/OneInch/Targets/BaseTarget.swift
> +        target.path
✅

2022-11-30 10:22 UTC, ba1ashov commented on TangemExchange/Services/OneInch/API/OneInchAPIService.swift
> +    }
Тем более класс уже не круто )

2022-11-30 10:30 UTC, Balashov152 commented on TangemExchange/Managers/DefaultExchangeManager.swift
> +    func getNetworksAvailableToSwap() -> [String] {
Вообще получается так, что уже framework это Exchange, а уже в приложении UI это Swapping
при переносе UI в отдельный модуль, думаю переименую

2022-11-30 10:31 UTC, Balashov152 commented on TangemExchange/Managers/DefaultExchangeManager.swift
> +        exchangeItems: ExchangeItems,
ну в плане объект по которому будет строиться UI, что бы вся инфа там точна была верная

2022-11-30 10:31 UTC, Balashov152 commented on TangemExchange/Managers/DefaultExchangeManager.swift
> +        exchangeItems: ExchangeItems,
Сменой местами будет заниматься ViewModel наверно, и менеджеру говорить что менять

2022-11-30 10:35 UTC, Andoran90 commented on TangemExchange/Managers/DefaultExchangeManager.swift
> -    func sendSwapTransaction(_ info: SwapTransactionInfo, gasValue: Decimal, gasPrice: Decimal) async throws {
а функция все равно свап)))

2022-11-30 10:36 UTC, Balashov152 commented on TangemExchange/Managers/DefaultExchangeManager.swift
> +    }
вообще пока убрал эти методы

2022-11-30 10:36 UTC, Andoran90 commented on TangemExchange/Models/OneInch/Targets/OneInchBaseTarget.swift
> +        blockchain.id + target.path
а там же вроде "/" ещё был в начале

2022-11-30 10:39 UTC, Andoran90 commented on TangemExchange/Services/OneInch/API/OneInchAPIService.swift
> +    }
а что такого плохого в классе?

2022-11-30 10:41 UTC, Balashov152 commented on TangemExchange/Managers/DefaultExchangeManager.swift
> -    func sendSwapTransaction(_ info: SwapTransactionInfo, gasValue: Decimal, gasPrice: Decimal) async throws {
ща пробегусь по всей либе

2022-11-30 10:41 UTC, Balashov152 commented on TangemExchange/Models/OneInch/Targets/OneInchBaseTarget.swift
> +        blockchain.id + target.path
добавил в BaseURL

2022-11-30 11:15 UTC, Andoran90 commented on TangemExchange/Managers/SwappingAvailabilityState.swift
> +//  ExchangeAvailabilityState.swift
файл забыл переименовать

2022-11-30 11:15 UTC, Andoran90 commented on TangemExchange/Models/OneInch/Targets/SwapTarget.swift
> +//  ExchangeTarget.swift
и тут тоже название файла 😅

2022-11-30 12:34 UTC, Balashov152 commented on TangemExchange/Managers/SwappingAvailabilityState.swift
> +//  ExchangeAvailabilityState.swift
✅

2022-11-30 12:34 UTC, Balashov152 commented on TangemExchange/Models/OneInch/Targets/SwapTarget.swift
> +//  ExchangeTarget.swift
✅

2022-11-30 12:36 UTC, Andoran90 approved these changes

2022-11-30 12:37 UTC, merged